
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_6/1: ${c} AVIAEXEDBGOVMNLKAECGEVPEITDYRWEYDVLKMBOQBLSJMAMJMMAOJTALWYRASAOWMNZUKPEQORAAFRNDNRJQOCHJDSBFMWVUREIB', props),
compute('m_10_6/2: ${c} FLIIRZDOMMFKZTJWEPFIZUAGQHFZJSGKYMGNXCFYTRHBNWGMAUYRJYCHXDZKPYJIBZUTNFNPOCTDERFJVCSYGORKKNDACKDYYZVE', props),
compute('m_10_6/3: ${c} NOFFHGUWRGSJFXFRQGJUMDKIUTJYQLCBZKHHPZDBUZDVBLULNBHRLVSVBWBLENWYLMEHRILVPJXRRYJVFAICTSCLZJGQPSQTWIAG', props),
compute('m_10_6/4: ${c} XNSZWLONFNWCOITBGEJYLGZBOFYOWMJXUPXPNRXYMBEAPEBNMOZJVPWBWXHYQUJMYKFWSYOLEPBSJVUDCYAGSHEUNJFCBODEKXJF', props),
compute('m_10_6/5: ${c} QFYOQFCURBZGQSYSGVJDYWSVBAFQQCGQIHKTDGHBFPDSIOSFQERTLRUHRTTREZMHTHYRCLRZSYBKKHCPIJTPENDAMFPBOOJQMGHM', props),
compute('m_10_6/6: ${c} XUYOOATKQQPWJLJYLTKIWNIIPQYQTGZFNBOKLQQMYZAIPCTGAQVXKMFINWNXRBYWKSHKTVKIKMIHXVBVLGGLCFBBIWBEUOQLDGIW', props),
compute('m_10_6/7: ${c} JOEJWYYHBESAAUIDZFUYIZEZENVLFWWXSTIXJNRUIBLUHITWPEQUIOAELXUKMJWYNVFWXNFIQHMPUWAZLUBQSZATMURKTIYMIKEH', props),
compute('m_10_6/8: ${c} HGKYRKZDJNYQNDWLQYRLDXIYFZKBFRCZVVNORGVJDIDDXYDUXOYAFIXOIUPUZMKDPWSHTBDCPUJLACDLTBIVRRYSBQADXDDNLLXL', props),
compute('m_10_6/9: ${c} GXVUXMJMLZQPYCVANCHDBBPYUGZOODYPXWQYEJOEJRMFSNMTQEEHMNQUZJFWQUOCGGNUKHSEJQJNCIGWXNPAFVXIJOUZHSNGELQL', props),
compute('m_10_6/10: ${c} AXFTEUDTUAATWLKQJCOYWWNIERTXYQTWYEMWBSHRPVEPSRIKVBUKCPPKETYMWKSJJQFDURABXJUNBVPILCMCAKHPTIHDBMZOAWIA', props),
compute('m_10_6/11: ${c} TVJABFDNCXFSEOWCNOVDNPFXMHFGGVXATCZANNHURJUNSYLPAEKBSHTAQJIEWYEFQCKERWILAZQUBSYRVCGVCAQDNHUXSXPOWHBB', props),
compute('m_10_6/12: ${c} CVMKFPKFOFBHFERAWPUXRTVSOLLURCLOCZUEYGURZVGRANYNTNKOFVABQYPTHCJGXXCHSIYPBWPOIWLAVTTIBVODYBYOUVBTDXZR', props),
compute('m_10_6/13: ${c} JFQGXXRPZTDPJTPGGQSMKJPNTZHUKEISIURXTKNYQQZJJWMPMUIUKEUTWRHOKGKNOPBYNALPGDMSAKMPPZVZEWMCUDZUPSWUBFQU', props),
compute('m_10_6/14: ${c} QLXDCJHAKRDSUUIJAPYGUHJCQNYCSYAYJPVFYMJDYSFJSMLRMARQCUFAOHTJDCMVWUYCVMDRWYUGOMETQNMCTBTXANQMMGTASJHY', props),
compute('m_10_6/15: ${c} DDYLDQRGZVPBUNATDZYOCQWIWBOHPNNHZEGBFMLMOSEEMIRQNNFXWTJULASFSUHSLZBGDSOXXXLKHUVKCMYEMZMFHRIIJVSGPGTQ', props)
        ].join('\n');
      }
    