
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_3/1: ${c} EIDPRWGIXDPIOCAHRBJPMLXCOQRYBSSSSUHQWWJBPXLTMSQJVQAVNZVKELMNWSLZUHULFSZJXLEDBIMFKGDKXKKEKRXTEVPPJREW', props),
compute('m_10_3/2: ${c} ZEHYXIMCFYQEDODBVJYURQXUQXXDRODJCOEVKADZAAEQJTOKRPFQPOMDMQZRORBERTRAFAVKUKGXFNXYUYNJWKMLWAHQBRBUYHQM', props),
compute('m_10_3/3: ${c} TFRWCBSNBKGLXMICYCSZGWLBAADHYLYVNOYNWBSQEPITQNKMDRFPMJTHVVEOAPUJVFCSDQYSWTKAQAFJLNVQWOUGGFMGEUKBEEZJ', props),
compute('m_10_3/4: ${c} ONUIZIJLZHMYLYCLVHOQQOPUAGAQKQNWCZXOKNORIIXSGOLDTWXJUHOTTBZXXAQOFDCYEFIGCOQIFLPEIEIQSMSJMWYLEHWQCKYH', props),
compute('m_10_3/5: ${c} ZMMICZQNYWBHJFNVKVUVDKAEKBAITCYLWQHBCHOMCCZFSFEPABEXFDVUOQUEEQHNMGPCLWLTSFDSVWDLYAYSICCLDPBQRMGSECQE', props),
compute('m_10_3/6: ${c} LIRISOEUYJDBVWDPBZYEFAMKGBHNWJPSWEXSIXBTCCUUBEDOXVZQTEZSOXNBALRUKXFGTCXKUHXITIVFKRKSAWCBIEDINJJCIXFU', props),
compute('m_10_3/7: ${c} ENTGLPNQARIWHBSULUYAFOBZECVTNJWJZCYMXDJADIBKSXMBWJDCAZMEOTAMHJENIAFALRPLRRSFSLKKJVDYPLRXAAEKOMGQQXTG', props),
compute('m_10_3/8: ${c} CXLKDMBAOTIQRRCZULAZFARBIAEXWWXBBCJJZYDWLCNQLRCCFNGHKZGQTFVEMAAVKPMZERQKLHTEUQHYTAWAFYVPRBPUINVIKPYS', props),
compute('m_10_3/9: ${c} BOIEVTZQFPABVNEVQOIBEZEDFYPDXGXGXVABZMCIBREYSWQBQLUATBHPIJIINETCWSQNXHZVFSNLEXLIXXXBVFFETPHKHNYBQDTP', props),
compute('m_10_3/10: ${c} MRDTUDVQKYFZCUQQVHVFJCWNEZDKSMDKEGZLRMXFLKAFTRGOOCIMQIFUDMUEHQKPBAMTSKFRRHVJPARQREHZGHYQFDLIUNXHDGGT', props),
compute('m_10_3/11: ${c} NERIIBKWOXMTKUXNHOSQMESZAUXOZJTEYHKIWILRQUFMCBGCXHSMEHUUREGZDPXLYUKTCXIAQPHGUBDXWKERZZSTIMNKIOMABIYV', props),
compute('m_10_3/12: ${c} UNYIJFDJOEMZUOHZSAYSHHIACOBQLHACUZRBONMLWQYRVPTYPIUAQKXIGGUMTLJISZKVAVTEVPYNWDBOWZAZNJCUDFFTGBXVCCKW', props),
compute('m_10_3/13: ${c} TGWRISSNPNUJMBVPRSRCRNLEHEDSHBYDCFCXXRKMPZCNDUWUOJFURXAEELFDUWVDRRXOUSOUXWQTTTLPCNYIOLJFAHYWTPHPJHOZ', props),
compute('m_10_3/14: ${c} HXHSFHJUXYMFIYVTHQRPSLVRHZVJQAGGKMZJBQAHEZGYBGTMUVLNQFBQNJNWRKLGQQNRXYKBHDLIANWYKUMGHQGDBNMSSWMPSIVT', props),
compute('m_10_3/15: ${c} DHGBGDTKDQFUFBHLPQDRVYQWPWPBTGPORRTPWMMFJYTKMPUASVGEESHUWCMNTNMVYUPPAYPSJVIIHEDCCQONFZTQYHGKENSTVERU', props)
        ].join('\n');
      }
    