
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_2/1: ${c} HVPRKQJQGWLJPZBRYGXDSBGZTFWFKACQGRZCQHXTNAXSLZPOFMDKGQATHGNIACUXXBUVTWAYHRBBBHDLWQVKWCYIYFFSLQYZOVOJ', props),
compute('m_10_2/2: ${c} BHMISMLALQSLLUVYBJZUYQQHSSCQULZFHIGZTMAKBVGJXOSWIVEPUAURIHHXQGMRPORZNBWFEBNIERKUKVSDQILLOVEZTYQJPAPR', props),
compute('m_10_2/3: ${c} FMVVVEPOVXMKOJNXAUWBBBTQXQMVKXFAQPQQLPFEQQAWCPPUOXGFTRHHWMCVDYYPMHZFWRIESMOEMXHXIAUTQXZJNWRQIQUZUWCR', props),
compute('m_10_2/4: ${c} ESNXHNSJTQELZMGUYCQAOGQWOBNEOPZSAMSPOGESWGASCGSZPMZGFKWRLINYLGWBPKQBEVYNAYXAFMODXKEADITQQVOCJDRMCNNV', props),
compute('m_10_2/5: ${c} AXEBRMBMMADZNECASJVHXYOREOUCOOMKCQSKWFZNYVYFPPDYOHRUDKZRWFXYGMXGILQLUEEVPHHOBAZVMAAGWUWAKLYJIWDSHZJV', props),
compute('m_10_2/6: ${c} QZUBTIEATQMTMMEUBCITZMMRXVKFONBGZBPRAPLYXTIQDVSFSKBCWTGKLGGYDADFNZJUSLKWZLLNFWDUAALMGKSNYSQRWJFVXSYC', props),
compute('m_10_2/7: ${c} OOIKZZQELMABBXTODRYCVZDJMIREXTSUOTRAXXWMJMWVYJGQJWXBINMNBHOMPUZILCPLHCSORNKJCECFYOJTFTGEAYIYDFOCNITZ', props),
compute('m_10_2/8: ${c} UGPDOFWAQYJCHKVQRFYKOURSUENZBGKRFARCQSLHUOPFTRCDLYIWIBEMSPGHSWSIOLWWKCSPBCIVVONDKLYJHKSAUHRMIKLBWUXR', props),
compute('m_10_2/9: ${c} EHTHLDXNQTPDGPCMDXPBIZXCELNJKSVWFEZPGUULLTQGQRNCDQHLMPEYMRJJOPQPXVRIPZHRPBNVBSEKUDILITKGBDDSEWPKPHGR', props),
compute('m_10_2/10: ${c} ONMALKLRLTUSXZLAFQFOLIQPANKSXPWIMMCRONTQDPYVSECZDQUVMGJOTBGSIAEVRSBDSWWXGFADZNLTDRUAHDBUFZVYTTVEOHNY', props),
compute('m_10_2/11: ${c} BSTEEUVDJCHQUTWUWHKIDAYAJCSYCXQWZHQGVQCTGIZYFEITUDJGHIFPTFJACWJUDHUTQFJAEGBGKXMDMFOIRCVGRXCXFZRTENOO', props),
compute('m_10_2/12: ${c} NMTPPKTPGKZQLDQVIDROYIBYFCOBFGQJHDWBGLLDXCCRALZAWVUSRYXNWTCVMAABYYZXPHXSYVCYYYVJFRCWJZHMZFLUKPPDTVYN', props),
compute('m_10_2/13: ${c} IOXBAQGMUAHYRMQNICSJEUVULZIUAUBYYDFKGTRGHAZYJZJBJFWQTYVWSCMQQQPEIEBNIBUCZWURUPSUNLRKUYIXOSZHLKZBXPNX', props),
compute('m_10_2/14: ${c} VYHRSHMLLPJATDPWWBYPYKPQOJPEMOTAEMHBVGGPDWKJASEBFFPTABDQONVWUGYWHVXQNBIYOUMZQIGKUQLSUNQEVPFYWIGINXQL', props),
compute('m_10_2/15: ${c} MTHGJGTNJNGNBAYRSDAZEDWYMMOJKREDWZUVHQXYSQGCWJREBIDDYFYXCWIHNADCLWODEEUGNQRVUJCPKVCDPGVSZBBEZKTZKMPI', props)
        ].join('\n');
      }
    