
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_16/1: ${c} BUXLTSZZJLCTDKQDWPVRTMXMUACGIVIORPLILPJEOQEZASQKSJAWZEYKVNQFNAYNGSXIHARBHTCDMQZUBTKDCAMRSGSEXUFNXBVD', props),
compute('m_10_16/2: ${c} TSVOUQJSUDSLCJLPOPARVGYNDUYJIJYCUJLSKQCRFXKXQFDTDCSLAFXPLTWOAPQXRUSJKBTDWRJIDXEPUDDYFLXILJTXLOMGAPHD', props),
compute('m_10_16/3: ${c} DYQVVIYAOEIRNYEZZECWJAWQPUWVNZVTZRTGGJEIKOYFXUDBNBXCQWKIVPQLPPPCFIJFTRIJOTIGMPKBHZPLVAYDXFANZRQUILVP', props),
compute('m_10_16/4: ${c} GWZJPEDXNDSXDRTGELVLEFQNJZNJVMOWKCXIDEHQUQPBUSMXLIISKKNVXJEBULMPDQGPXKBIMQFCCYSTIDPYFDZGQVNXNAVISZDK', props),
compute('m_10_16/5: ${c} GIMRXLXXNRVGCOHBONZUYFEGHUQODDQTNBVJPPSXSOVIRDIWLYAVQNBQNEADGABQSSUPPXUSTSWSTMKFRNCUFSKTKBPRPVJAPMOT', props),
compute('m_10_16/6: ${c} MZYALZYIRIJZRCUWZZLLNWIYIOUWGPKXCKSKPIJRIBVKTLVQXXCBCJPWKATCDUNLCGSBUIPWMKGEZONQYOAOORGACARBWGFHTBCN', props),
compute('m_10_16/7: ${c} BMTFRRZWVXPBCMHBDEMMUZWVHBNUKJRMAFNKGLFWGZXZFXNWOZOYBMMDFBXUBWIXPJJYDKVNOMCBMKDDQUAOCWJROJQWVAXOYHDG', props),
compute('m_10_16/8: ${c} XHLRCNOZCGHMUPAFYGUAKXBWTZJMSHRAIWUREOOALAFBRRTLCPKOEPYMKQCTDJHYABKQENPELEDRHXHUMEHRMEWNTDXRQVNERBLE', props),
compute('m_10_16/9: ${c} DXZSPFACXTVXWNCVLRQTHHJAFFHGFZCBZSQFWBQNECBUSZHYQZDVRSBSNYEOMDJSUJIZQKXJPVLHYWVXNZGSUFFLGBLNEVKFRTLU', props),
compute('m_10_16/10: ${c} WAJKSGIRWEOFUVIXBPQRHVFXQKAOBVBKOYMUVROAAZLKZQUTTJFKNRUZNFAMYZBLNNRKAGEWHZMOSTMQJGMVZDYDPVRAGUMWDPTZ', props),
compute('m_10_16/11: ${c} MLMTEGDGIXJCYKTWSACUYWFCMXYPNHAWXRKKXVFYSDOSDZYLQWOEPXNPBTRBPVDJSLZCWMTOKVQUMYVHIHFPJWYLAKUHEEUETKLP', props),
compute('m_10_16/12: ${c} XKULGTKWTOZOVMOUVFMRDZLZLVBWOWOFGWMXTOEGGZXTVBOOUWBFKWHQUOJIXAEOGLHTFVNACEHFLBRHYKVGYHDLMUKULYFNGHBR', props),
compute('m_10_16/13: ${c} AUHZFLSRAEZMOXEODWEOASGGVZAEILCSFYOOMEHYMKTDGFONDRLWRKPRAESEICFUNSMJAIJZRCZKPRABGBRQXIXLQFQPBDAUQSAS', props),
compute('m_10_16/14: ${c} KDZNQTHYIBDSHMAEPCZXGRKDBUELVPYDHQEGNBYVLJCRGOONLDZHJZUWHHVJJOABQCQHMTNHTUWMVKSKGGXZHXHYAUYONMTOAYYZ', props),
compute('m_10_16/15: ${c} UVZCTXAKMCGFYUWNEQNKQBWHQZVGXIPFULRIRVZRIHEGLKAFDHMNWKHKCPSPAWXVWUDAVGPHSZESPBJZKABPHPESVBGUAJUZNJUC', props)
        ].join('\n');
      }
    