
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_20/1: ${c} ZTPLNZRMFXMOKIMJFOGSCGSYZKRRVYJYURNFJJHBCAMBIIQBSHSZQZJOSYSPIVBIAIPALWHARTGJWCAHEPJNNQMKRAMTEJOHQNQJ', props),
compute('m_10_20/2: ${c} IIJNWPVLVZRJDPFTHWGVDXPWATRXQMLWYCMLGICKSDNQYGHMYOVCEHSTHDWSEHOJGCGEPKLQKKJFFCDVSGIGUGFSHQTSLEFWEIWP', props),
compute('m_10_20/3: ${c} YBPKTVFGLLXUPWJBLKEICRKKQGADMREEDGHDZWHBWCTFTCFDMXFJYHQOGOIBIDQKQIJGVORWPSABLHOTNUCEBXLAEEYPECZMMTZG', props),
compute('m_10_20/4: ${c} PLKTVMZRHICISIYFJTKLPQWBJYVASGQHAKETDJZVQEWRGFCBVTATTBKZHHZRUOZXKDIZILMOJGDVOOTDOFSBRBUGFISTZNOCBKTP', props),
compute('m_10_20/5: ${c} ECYMMZGCRDGUONFJTYEZVGHZLTJJWZVNQQDQVKYYQAEQMHMGSACNNYCKCMWBNJAMYFJBCWWKEGQHAEQKORHIWSJODCFNNWRTZWCT', props),
compute('m_10_20/6: ${c} SNDHRUUPNXQREEYJTYYGZEPFHQCTVIPOAPBYJIETABVMUBNXQZDRRWNOMOEREZFGYQAYEGNWDBSHKGMGNTLCLJMEMUHXOYGPCCPN', props),
compute('m_10_20/7: ${c} IIVALGGVGBHEFVXWRUOAUYLKCZGENFTHZZFKTLABVPEFDJQWDEDDWMWDDWDQVRKSKKBJGOZPHUDBNUTVMDSGOAGYMUORSPLNFMMR', props),
compute('m_10_20/8: ${c} WORPBXFTDHWCYHCOKLHCSCNNBXQWYCEECIKAXLCGURFGGDUTMTILQKKNBTOFANMNDDFECITVXBHXVPIZRAXJSXRDGQUHHJLFEODV', props),
compute('m_10_20/9: ${c} VOOOBDTIIAAXBFEFQOWWZUHNTHTWQNOMNJTLFJEZWPFMNOKYNULJDUAQSSSPNHVLRTMRKYXENRFXCYGCSLXUTGPORKOEOWVUWVWR', props),
compute('m_10_20/10: ${c} IORHAKSHSSHPGQEARBAXTCLVZFHXIHIZIRYHZTDXSSZFINNTKCEQQGULRBXFRDAICIHEFVIDTEMQFTMZCOVBIAHPJTCVXBONUZQD', props),
compute('m_10_20/11: ${c} HERULJUINXCBGSPHIOCWJOSACRRFUMBWUVHQLUJZCWYLCRBUDHQNIEWFCESCWDZBPUQBURTVGBHIXWRQXTKRPGUWSBLOKZYCAFVL', props),
compute('m_10_20/12: ${c} LWJLVMMPLRYALPJOODWJHCERSXEPRIWGGBKFLCVGTBMVVPGUXTIPOBQPQKTCKGSGQZFYLXXSGWBSFSLHXWQADRFJZBXTZZJZXKBP', props),
compute('m_10_20/13: ${c} NLIMYAKFSJNQADVUIDMMFOUUBKUPPMIDPRNILPYRGNKFUSJDZYTWVUEKAHJXEGAXNWQNZUQPKXNBYVCYBNKNRVMGGNSRKRWWWBIK', props),
compute('m_10_20/14: ${c} RATIVSFKXZQACZBBXEELYAPVPSMHYYAVQHSAWYHPBXUITSSWVLASJXNKJDZMKUSMZIZTHCONGWZFOCQIBJIRNGYCURWFVSZJWWZE', props),
compute('m_10_20/15: ${c} FCLDQPYGZPNYXEULAACQGBQYAPDGTRAAOQNJUPFPBGOKHZSJRGLLJYSLSRYJIGQCNUSJDQQORYIVSWHQMHOKWDQYXIJPFHARQPSN', props)
        ].join('\n');
      }
    