
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_5/1: ${c} FBHQQTLUACBGHBJEYWQJXPYBXETQAWGNFPZDJMYKYBAYMYFRENLPRQBILKOUDPATTKUAMHOJXGMMSWYXKTFBBJAPGRMVJCCGWHZL', props),
compute('m_10_5/2: ${c} WQAWFGRWLANBBWNGYGRIFWRDXJHTVJCGIJITYCTHFDGQAVHUXJWADJTAVNGAGAPYBMAUBWEZOLEKARXOONAEABXGNLQIXZMKQJXL', props),
compute('m_10_5/3: ${c} QSUHGHNHVTSJKDQEEGECCNVSNKURDZSCHQFLSNXEXOIASJRZFFWTNGWMNAQLTXXGSEPKAMJIBJNDEBXGJCYBWJORDVJSZBKQTEIK', props),
compute('m_10_5/4: ${c} CSQCDETADIJKZJYFCYSCJMSCNPARLUJXEAWHJGFEGRXQPULNVCBNUXHINEBRVBVCKFLKWKMTIURAMIYOZCJSTTSWBZJGGTHHQDWY', props),
compute('m_10_5/5: ${c} ALUJMRJORANRXYIRSJYIZMSTERVRXPOOVYYAZOOGZOTRRCMPVXNPCOCEQMOFLWUSQVQEIFVAESDQHZQYJAZHWLVYHDKFHRBBQUOR', props),
compute('m_10_5/6: ${c} KRTNMKPAHLCNHUOSJLZXLAWRTOFTTCNZTVPFROXQUSATTKNOFDGDVKOLOJSGXMYSFJKPCWEQMZPBMSWZFFUBIZAGJUDESLAYVNHN', props),
compute('m_10_5/7: ${c} WACYXXTWUZYNZFGYROBLEKEOUUXWGAXDBLTXBHHFHKPXWQSHMXOXFKWABLLICHWFXTSQKORSYEDWIXIXYZEJXZOIZOKAHVUSSKLK', props),
compute('m_10_5/8: ${c} KSEMVUUUVHJACQOSBZYQPTXYCCAXUEWNQOQOHFEFQXSIRDVGUEMFFDDFWSPOQTYVMHPIUDGNPTAIJROAQMMOFHZRJSDZVCHIMXHG', props),
compute('m_10_5/9: ${c} QZTSCDZNVVGCBKJKNZRDSQUPUNDWGVUTBGNIWFEMCFOXBMDFUFPBIAVGARVTHZIJNAXGGCXXEYREWNKQSNSLFCUCISJSAVFOZHSQ', props),
compute('m_10_5/10: ${c} APDOPAOTEZJLFZFVWILGPAMTFACERTSRVGODHESAGYIDGBULGHJFYYJWEEPYJCETKZMMBHNBKCJJPYGDOAVGTNTILGBTGXZGTTFZ', props),
compute('m_10_5/11: ${c} LFSOPRMGUZTEVMHVIUNHFSTDZKHUGYNMDUTWVEFKOQQJONCYHKLRNOOPEZDODQVPTQCMVOVIWXHPHJKZCCCXLQCDKOOXREOYPSAW', props),
compute('m_10_5/12: ${c} IDPSLZQRRWFRTVTPEBJBWYBLDPGOBWYIFWTVTETYZGAFGGUYILQACQQOYCOIKOBGHDTAIFEKURKTCVIDPVFXDUIJTSIFIDDCZHBY', props),
compute('m_10_5/13: ${c} NLJZHXVWJOAWXIRIYQULUEXKDZMWMBGSVASVNHBQGQSGHNXMXKSDHOUUGSIZHWBXYEHNBMTJBCASUHWMSTXBPLGONJZNEZGAKNDU', props),
compute('m_10_5/14: ${c} OPDTRCBNQAIQUSATVSHNNIMNZQEWFKZHIRXOIMIFTRXBTVARZGEDTIDKOZJUPLOKXOBLSIXROPIHWCVVHEWZWPVPEDELFZWNJCQZ', props),
compute('m_10_5/15: ${c} DFRQBSQDZHKQDEJDIMLLCCXHRQGQXCKUAAMSSTNMNBUORCCRQEIAVCRZCPOYQIAJUKSDDFGVFAUUMPHSNMFEKOTLIJHQDYLNRXRD', props)
        ].join('\n');
      }
    