
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_12/1: ${c} QBSLPLKMLZFYGPTGMBDNZHPZSUPAOARGDZGVRBTTECEIJJYCIDIEFLUTVRNMVBIRTYCURMCQPQTLTMAASVHLOZADKXUUVPFCMVPZ', props),
compute('m_10_12/2: ${c} RIPKMBBGGEMJRBGJTYWBCTBFQCQJLSPPFOIMSEWMEHTMZPLMWFPATIXXQWJRAKREYLCNKKPHDIDIHVJMLUMFVVKDSRLUKDYMYFHT', props),
compute('m_10_12/3: ${c} JERDGPDRQQHIFCLFRWTVCGCLZCURITKJYOWGCVVICNJQYIKHGURXMGTWKFBDVYVOTOWPZUMKBWNCGPDNXLMVVZNTYTHZQWYGQVMT', props),
compute('m_10_12/4: ${c} GFGIZTMFSMHVVHXLZKOBDGBNUULMYFQJCKJPKVHTPACENLTBRLVEOUPHQRLAGBNWPZEZGTUMXLLJWXGTTQFRVALFHIBUMPFZSNTY', props),
compute('m_10_12/5: ${c} MGDFUTZVFCZBLYSMWOEZZCEZVCZAYVTUXSLYSHDOVWTGYAMTPKOWOWACRCPLYJMOSMVNIFTCTSEBJYCJSFVSSIPFSNUDKYALKJZC', props),
compute('m_10_12/6: ${c} XSDOEUUUTDRUASNMTQPKJTONHGKNHRHHBXKIXSAOPBPUONRAHQKFDFBJIOHZFSNKDZCGIJGHIRLPIPZNCVSIFERYKLFUJIMJSIMR', props),
compute('m_10_12/7: ${c} XHZSBNWSWHROQCUVTWBPLUSAMUSNVXEKHIWXKXWBXUYXNWEFSMDVEONWOWCBAFJNJXMCELKPPORAIMNEGALROFHDEQXJDCCKIFWO', props),
compute('m_10_12/8: ${c} JLYSALSOIIETVOVUQKKXUWQEONUTOCBSSQDOYDTMNXKRHQSTCDBNUAUNTBQDEKSQEFDYILQFBRPDRYHQYUGYYLMDGWNAZXLBYLJX', props),
compute('m_10_12/9: ${c} WPWEIRSWHFIDHHBJQQGTSXNVFOHZXZSNXAPXBDOWOWETMBRZMWSHYGTHHPVDAMUGMPLBCNIXCSNHEJTCNTZVECENBWEQABBHXZMM', props),
compute('m_10_12/10: ${c} XVWLEFLEMGBLRUNJMHPPYJRENPXNUVOQZSGPBGRHCDGFCZBMGJFWMWYPADEMVKGPOOZUEBJWRTCPYXWMQJISUWRQJSWISVCZKQPM', props),
compute('m_10_12/11: ${c} QBBUPXSSZXQGXIXAJSAYKRQZHKCPVJWMNKIDAOMMCJWPTHNIXOBQQENDRFYXENEXJJTLRAZVTQZVGNJWBEQZCWNLZNXPWUBFBNQO', props),
compute('m_10_12/12: ${c} JTDCIIEBPVZBFBIVWCDFUTFFLZOTIWIEBJDUALQBLJKRHFKIOLYZRWNYDZXZOUOJAEKJGZLQAVFGDYFRJJULIPAXDFNSNOZLNQOB', props),
compute('m_10_12/13: ${c} ECNRCSVDYFHOZWBGIWCJEDEXNFHTTQTGGVNDQUPFDOUPMGFJWHVVNWGXXBXRENIXWTNRIQLLNHLHZTWXAKXTRZRPPYXOZIZAJSBL', props),
compute('m_10_12/14: ${c} XIWQQTLFSOGSGXNLZOPTMBGTKVHFXJKGHNRXGCLVBICWYRZIYYQPQJGGLGJFSVJVCFMGEREKJRUTKNRSJUFNGTIVGTAGYKIYGUJD', props),
compute('m_10_12/15: ${c} BTNRAJTEQABHSJCUIMRMFGIULUHCDPPPJCMLVKIDSXCCDSYQTMSSWILQHLTEFBWUZMUIWXHSSMMLEYDPYVDJPHCJXYCXXPADIMYW', props)
        ].join('\n');
      }
    