
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_11/1: ${c} NQYINCCOWINDBRGNQNZWVFIQXVJPYWBPDZGAKDGGJXQLEKUYFOSZUUINNNYISRTEGEUUZULBAONFMICLLQHPMNCKDVVSZHMFMUFN', props),
compute('m_10_11/2: ${c} NSBUEFDGRVGIKRLACLHTGDXYXAPPMJIOFKVEBKQPOGKSNZSCSUKQHHFFZZIOSXUGQDVGURUWXJYXHZDSQQFIJYDKYDVJZGTGVCDW', props),
compute('m_10_11/3: ${c} DNUZSZCKCUPABJCFGORUOAVJFGDCPLFEXBYWWLTZCWEIICJVMJYZRGHCTIMKHXSEFYGEQZUWCNQQIERRHYQQEOLBHGEQPPUTRNUH', props),
compute('m_10_11/4: ${c} QEQDIDIACESXYXIWCGQSAJQUNOTWXRIDJDOWWFTYFFLWCKDQVDEBTTDKRLFSNZVODHYOVKNCUNZLKMGXNLAJQPXJRXTBZLMTPAKZ', props),
compute('m_10_11/5: ${c} RVNNPVPWENSZYENUTNZLIUXWBANEBBYBIOZCNFBQDHCITCTYSFLQUKVIWNFORGTJJTEVYRXKPIKRWKTXPWXZOCGMGQDZGQQJEIOG', props),
compute('m_10_11/6: ${c} JOMYQUEFGGHZMCNKJWJJLOZIYQEYZEKPKWZQSRLBKFVQMFTIIHCEIFABPLRZQJUIFIKSZBXLTUPWMTOSMIPBGFXZMOQDDVYLEPPQ', props),
compute('m_10_11/7: ${c} CYBYSXDNQXSNPEZZTEMKDKRJZUHCVHBOGNPRUVUPELXILALGSGERULFFUWYZLJGOJOSGOHCRTFXOXMLIMAMWPRPEPJFYKVZIZISR', props),
compute('m_10_11/8: ${c} WJLUKINMMHYACAXHZXGZHGAXEEEWZSMJZJUIXEIBZWCNSJMXGZQLWNSQTSTBMMARUBROMCYSLJXHAPKCOQOKHFIYIZOFZBKTRQHW', props),
compute('m_10_11/9: ${c} TLFFLXHKAHGEDOAMQXCZDKSDYHMCLHYWMANWFMEAJJYPTZISCEAEHSVGUTFEEPQYMDUGCAHGGRAXPWKMOELCXBQKTKMKFOMSOBSF', props),
compute('m_10_11/10: ${c} KKIJCNTWIOMCOBTYTVNVWVKANWIWKKRBZGOJMQKDKLQTBINVSCVOHYYQMIFGWOPASQYQROLYNPWHIRHECDIBTSQLAQIWDFVHDFND', props),
compute('m_10_11/11: ${c} MPDCYPFVYIPTDTYFJRSAGNCMBDWCNKGHWLRPQKOABRSZSSPPFSQKITYMRNCGTKPIFMYMKPBAFCKPMEKOZTGNEVJQKVTDFQNPTXBJ', props),
compute('m_10_11/12: ${c} ZKRLKHZEDOVHYDPOXHJRLCNQWDYQTXNGMOVHUKDEFQVASEDERZTXTUNAQHRNLQCXOQUQGWKNDPWIUZWDYCZKOGMVHLEPJGICEKRA', props),
compute('m_10_11/13: ${c} VNRSAMUDQPNXVTKNWNWNQLCSJCGNKDKSOOHVETIHXVHXVDJDOCESUFWRNRIMYFBFPTCLIMXPPEYBSCWFTXGECLXXVSZZBUZSAPUU', props),
compute('m_10_11/14: ${c} XYXMFADSCYVNSNNRRVIMQBHJADMGWLLBUEDSIPMMHBAVJQGFDGDHLYBKOCIMRRZISVJOALINTKOGMVUVUNADRMSGYMPJRIWRKJHH', props),
compute('m_10_11/15: ${c} OVKQBCUWHMBVKGUYUPVACUWXNRVASHMOJMVXYRRTYYLUYATQQVWAAMZHDSTECCKQSAUTGDVDBHKIBKELXTMODUMJCIKMOJHQSCVL', props)
        ].join('\n');
      }
    