
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_7/1: ${c} TEWSWEDNRFGCEFQPCHVRBWPHHXHQIHMLIAWFKBBXNLDNKPPKGQRHVLLAPYZWLVVCDGQGCXQBNMSXEZBCDSPREGHYUYRAESOIPTFW', props),
compute('m_10_7/2: ${c} MHPSWQLBMMXDSDKDCZZGJUJWZRHIKGQUYCJQKHWVIWNXPPAOOMJYSXIIXYOTRHTCHUGNRPNXHWWGQQKKOXVPNUMIRUONOHLUGXTF', props),
compute('m_10_7/3: ${c} HFIJSVBFCTHAHVJSXPKREHYUWLGCTNNKKAZQMPGANGOUJPGIPDAXTDAHDQNSTVGKHENXTNQDTNSCXNRXPICABCZDWZLBIECCZDND', props),
compute('m_10_7/4: ${c} QWTESKQJRRYRACVSIKMWXUFOIKOXACUWQICYNBORDGTZFMUHPNNIFBIZVWURRGECBEZCDCOUQADURMJLXUMPSBSPZUYIATXLDDLJ', props),
compute('m_10_7/5: ${c} THTNEZVCFTWUXPDATLQTSIDYQJMRCYISJRPFXIYAYWPACSQNCBPTLCDHNUVMSKPPPIUDBBOFPBWEIUNZDQBNKYTPDVFDPKJEKGSQ', props),
compute('m_10_7/6: ${c} VDCOAVYKBMOJBIYWPYQZRKENVWFDFCPDCNOVKIGJTZZXVMAKGUEVMFPXBYBKDRSBXFESUZYRLIVBNRKJFERRSYCHKDUJYGRZPDHL', props),
compute('m_10_7/7: ${c} WFRPGKCOEHHBMWVKLQDZOIUPCVOBOCESYQWWFGFKYPAGHTSPHEPCVYLXUUMNKCBNJOZRJGYVJVEDHZZWXZOKTWLNHKRCNGREUXYR', props),
compute('m_10_7/8: ${c} BCSSASTVTVYIHKKLTGHJUUCOQVTPDCXDKFVVBJQQAEXOOELIMZTMBFJOEZMQQXGHBOLGYYIWBIWATIXBBHSJANPYBHDMFZHBVYTP', props),
compute('m_10_7/9: ${c} TOXGZPUWSJCRPWCCUATBQAQOGBZZOMXVQFSJFIMIIBURHPNCQMRVQWTYXZELMEIRSQNUORYMVNNXFDMCHEBOAURSHGHWNNRRYWAU', props),
compute('m_10_7/10: ${c} DWHHNXIPZHXXGWEEVPSWSQWKVUQGGRUUAQJBHNUFFDFGNDDACIAJFRDKHCPZKNTFGXRLWBJVPANTAAHORLCUMNGBQZVEPEYAYEKX', props),
compute('m_10_7/11: ${c} TLFYCXMKRRIJVLLIVGGAGLECYQMEJDAISJVWEWTEDGBDNUGXKKAFVQFHJMTCFUTAPHTANUAAFCXSQGTZJJOSVFFVBOLELMDXGTXY', props),
compute('m_10_7/12: ${c} YQQNCZJRFYRWTENJBLCDBDMZDIZDRDZPQXSUHNGQBXKYUYPBODTPPEGPJMEFIQPDAHQSTENVCAXUQUUSDCHUDOHZDOGZYHHLEZDX', props),
compute('m_10_7/13: ${c} RJHFWYMLIVXDSBILFVYVSFUPEMSLTGKPFIIBCKSTZPSMASKSJUBSEMVDCMOMFDNUWNRPALWKXWAHRGSFTVPETLASDTYCBZMAIDJV', props),
compute('m_10_7/14: ${c} VHAURMDOAOEYUXKKGBSSWWVVAVIFWZTDVUNYNIFDBZHEGFWZWTQESLQHVZIXLJZRVNKWXKZEMUMASLMDTKGIOZYSFJOOACTSQMFA', props),
compute('m_10_7/15: ${c} TKKZVUMQMBLUJOZGRSBKXMKJZUMNAXEQMRZGRQFIFBLTTCIDMWZORJOLWHTIABFQJEVDEIQEYOBKMDMDUTKYMZFGLOLBJKHLZFCP', props)
        ].join('\n');
      }
    