
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_8/1: ${c} BMQBIKKZELLGSQUUPLTVQUMMIMCREYLLGNIMAOMREMMJMBQRONQXFLQZFIDFYQNYRKDTXWSETEMUXETDJNHJVTBOOWXIIESJPNQZ', props),
compute('m_10_8/2: ${c} NZTRZIUYAECGQDUSHPDHDHBRUPIEFLTOTPXBGAUOVFUBQGKJPFZKFUZGDMSIDIMOXKETBTXTQXTPBAKHVHYDBOFIBVXIZDDMVLWW', props),
compute('m_10_8/3: ${c} CUKSEZMOAYEGKQLGJOVYDWZQXTFFHEWERYTDTEWIHVCAPUSQRUDIXIAGKPUCTDEYLSWEFFTPTLUYJPDBHKQWLNXIHMPPWIQTODIC', props),
compute('m_10_8/4: ${c} BZYZTDORNBWVYWJVGOWTONPICPSGYMUOVWPMLGMCZLNIATUPDLDLLEWGYXPRVDVLVTOYRDMZSRSBKLGNZWGWUULLTKBXJQCHTXIU', props),
compute('m_10_8/5: ${c} LZEBLOQBJYYGMBFZIHGAJLADKBTKXJEJDMUHUGPKPILXWZLDQTRQRDKCLZVFIFNYUBTMCXTUZHBEZUOYZTUAPUNOACNEQEMDPNCI', props),
compute('m_10_8/6: ${c} WBFHPOVLBYNAOSSGQRXNXHGKDFFNZSYRYQSZLOCKNDNPLVOZHOFNIHXLAFHWMWGRRZTDVSLKAIARZKFNHPGZTYGTNCKJJUAOLOGI', props),
compute('m_10_8/7: ${c} YNDDDSHITCJKPQPEHTTHFTILWDQSEFAUJRTNNOMKMFRVHEBJVRLDCRPJMDLRJXCAMMYOPATUHJJOCFEXUGOXWBPWPILOXFCEPJXW', props),
compute('m_10_8/8: ${c} YUSQNEOYWGKXOYZFZKVDFMHXCYVPYOQTQJSQVLWLAQKNQDACVGMYGKIADUWHZLEKHDFLTSLPUIYNQPGMKXWPNDVRYRNMYOPDAWBF', props),
compute('m_10_8/9: ${c} DRGTGVUKYEVAWADPEQDPOZKTQCQMZDIDLSTUIPIYHWRBWBEHQVAVXQBHRIZYOVJRCLZUYRORTATNLEQUECGKAKUDXUCXQRVTWGMJ', props),
compute('m_10_8/10: ${c} WFZOVNGHGDLUWLXCYDLRVFKJAUQUJMEYEZGZXACONCIESAGOCSKOURMLSROYTCMAIDASBUDRMOUGHVDAUNVLVGSWHWODLSGXJJYY', props),
compute('m_10_8/11: ${c} VPWQVLPJQIIMHSUFEUUFINSUKVDDVJNJNXFWFOLRJPCWRWXEHJYMPLAZIDRTUESCKYWMTHLFJXZYOTIGDGCPBDSRRYYUUMTWNREF', props),
compute('m_10_8/12: ${c} ASMKOUGKHJAAGNDWISMXGLFJSFVMHJAUQSOGOLCXWAQZCPCSDBBUYWNUVUJDQNFTOERDNYFOTQXWOKRLMVFRPNYAUXPIPIBUPCPW', props),
compute('m_10_8/13: ${c} AJOJGDUSDCJXIHVZDPVVNEAWJAXLCZZYPXSZNBDAXTOMQFDTDNSKWEVACWKGKEVVFKLURQPQRKFMJCFYWRNSRIVEHRFGRZBARLAM', props),
compute('m_10_8/14: ${c} CRECIJATZKGHXXIYJSDPCZCEEKLMFFJKCDHHLZTYGCCIWVJBRPOARAOXXKRPYXVYJMSRMHCTQRRXFZYFXAIBYSIVOCDMQXQABRDG', props),
compute('m_10_8/15: ${c} ZHCJHJCDIFWPEXHUMIBVPNJLEVRNGPEHMRTMJRSSVANBCCHHTTRBXBPFEKBLUFMIVXZXDZTDZDQQIEWYZMYLVRLMZHYYMKENLCHB', props)
        ].join('\n');
      }
    