
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_18/1: ${c} YILNCPCQAACTQBTGVJJDKEQRIKELUGWOSRLEJBJOKKBLVCZDRLXTWHDJOZWAMVODYYCXKFEIGNPBXDQYQHEMQUXOETLPFMLSJMAS', props),
compute('m_10_18/2: ${c} TPCEMVXEMJLDYBJIQMBGRIOKYONSUWBRHKPOCYYVNQKJIWYHMSMZXPWSOHQUWWKPSUGCYZMYOVIMNWRSNSFVKQIWUIDCIGMOZUXP', props),
compute('m_10_18/3: ${c} CDTCXVRNOOGQCSBWBITKIKBDLBTYJXLZCNALQLLYWUECAWFRYNCFYYTTABLUBBFEYLBWJAIDVTZVRASQVVOACBHWEREHNXYWOZOO', props),
compute('m_10_18/4: ${c} RQPCKLAVSIXOWWUAALRKHPLJZUZADIWQLTGFBZXTJQGUWVEMVHXGFLZPKFPTRSAIQNIVBEQLJOCPHNOQPUYCOQXCRRWUALDIVDAC', props),
compute('m_10_18/5: ${c} GNFDNZDAQDYCMRRZFTPXYOIBRCWNVMOLBAEXEQODGNQBCSBUEWRIRRPJTKSDVVWSAAUSHMQVNEUPINYIWHXLZHDLTOKNPDAUXSFM', props),
compute('m_10_18/6: ${c} IQJTXJLVGXRAHQAWVMQNJCLZQRMOEEEXFFIPOOACYEUSYNTCYHPIOHXICXFUJBUJDUGUXGPRLWHDJFCQAVBIEPSPGDYEEZOWMDFI', props),
compute('m_10_18/7: ${c} HPMNAPQSPVQLZVITEILBPFQUXSOYCRDAKNQNYZOCSWKYLJDAXEKNQRNKBNAFUGQEZSNHYNLGKAHMQBCMOVOLCHPMNOBCIJALWTRR', props),
compute('m_10_18/8: ${c} GUQPGKQHASDUIDUOITVXDIXIGQUVDAWDKBYFVTGORDAUCLKZTQKYTFRXCZUOQNTZOYCSACPKTDYVWURLDBCQLZMJXIOJTTCMSAYU', props),
compute('m_10_18/9: ${c} FPQEEVXLKTNALTDJVQZVZIXPQNBPMMPPQVFOUNFMNVIDJWSWNLPPHIMNMWBAZTVUGDGQOJNKZMXLOXACOSOIGQQLUUNQFMLZQJFY', props),
compute('m_10_18/10: ${c} HGKQPKHDYJCUDKOGCCQVFKMBKIFBKCZVBKBMZERTYVWKTABXUJUCTJPIIMEVVQFNDJUUCANIMREVAEMHLDFQRGKOOBWEUKHKVOAY', props),
compute('m_10_18/11: ${c} BSKFOOHHVNFFHFMCMPPMPOEYDPAIBLCHXUIEYXRVIHGNBZUEGJTDTGVVYTUOKRPQGJCHYJKLDWKZSUSTKZFDSCIJIPKZBSVILYRW', props),
compute('m_10_18/12: ${c} IRAVYQUZEOJSVKJSURVRDVTEYZHRTDITQXYCKUGRTXUTMHGIVCLHREVCTIQXELSIKIVQLJOWNEUZMVSVSQZXHYMTZNMDTXIWDNJO', props),
compute('m_10_18/13: ${c} RGKAVCOTUOFXDRCNJEDJJTSNTZGMNGQVAFYPBXAPAKKCUYQKXDPRHMFARVJSOIGCLJWJTRAKDHJFPAEFKURWTXOPHWYIEEYJCEDR', props),
compute('m_10_18/14: ${c} PTEPGDQIPWPYKISUUKFRNUJPWOUJBGKMTTLJRBRDFGYULJBWHYTJQCCHMMNMUOGIHFVEMWOPGSQLWTOYFKVKLPTKVCOTQDJGTWSL', props),
compute('m_10_18/15: ${c} XUECNOKCOHUBWUJLNIPJKVEZCPLPVRRFQQBRPAKCPLBYIXAPPGAGZMGZLQIIVXTUTDPCAHCAAMQPLOGIRITZSSSSKIZMIWFXWOEI', props)
        ].join('\n');
      }
    