
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_9/1: ${c} ZPIBXUXVEOACIFZCPVHSPRRIFYYMSZINKCQXSBZSPYOQAGATCQCAYBGFIYSTMBMNQUBLYXNPWWCBDIKOWUTWJTTXRESRENMWVRXE', props),
compute('m_10_9/2: ${c} TOHEARDGQFEJDCRNAMLIWOTAIQCKYVDNOJLUTUXJOSQYTBBVTXETWTUAAKLIXZJQHWKHBJUPDVBIDIXAMZVJILKDZZUUIGMCNYWV', props),
compute('m_10_9/3: ${c} CISWAWMECXQHCFXUZZRYUYAXICTZMJPRGIYFSCUZEFVHTEQAJMDAPLCBRMFEQEIYPKZNADLVOSFDKNPISNTVCOINSKXKIUCZGVHZ', props),
compute('m_10_9/4: ${c} PTBUOAZMIMTTDXPMXRSMFZQXAKIOUMTMCCFKYWRVHUIXSUXLSUQDUUGGDQVNHTQKPXYLRIWHOEQZMFBYZDJIDPJTRTJXFXIDFDFV', props),
compute('m_10_9/5: ${c} VIGLCCOPCJXCCLJCLGPBALSNIVUGWHURCKPYQUEHPOZQXIFOIYRIJVBATXQNCXRMHLZOJGXBREUFAKCZIRBULCSCSXJKZAPUTIIF', props),
compute('m_10_9/6: ${c} JXVSEZGDBVEDMFIMBGZBVMENJENKAOXJQVQYJPCAIOKBWUPGIDZTFLHUUESJUUPOBUVRQQGDHGCTEBZVKEKPYNXCUUZAAGTLLDMV', props),
compute('m_10_9/7: ${c} BBOHAMRKQMHNSWLVZGOQZYMDRAHUGKHDXYYOHIYVUBPSGOCEPOYXZVHRXALKKDSMSCQFZYNULDXZBOHPKKXPDJUAFIIAIWIGNSZL', props),
compute('m_10_9/8: ${c} FMMVQFOVMHLPQERUARCVNZAGIZTWYTGLZFBXJDXTNSYZNMAIGBZGZCSWOECHTVPFZYFLXBLIHNXHSTNVXKZBCUVFVNVPZANFZJBM', props),
compute('m_10_9/9: ${c} TKWWTJFTRNCWBSZGIEXCUAGNCMBTOYNUWSQTZNRQOMHGOQVSNPNXIASFBEUDTLMRLNRYEPYZTOLOZQMECANQALKUBKXHCXCRKPLJ', props),
compute('m_10_9/10: ${c} UPAGIFJRXQHKXMIEIDOMUZNOEZZBIQLZBLTFVCDKCHOEAJCJJPHJZJAKSACJIMTJTICJPERGELCXREFGZIXHZTDMZFVLENJETGJL', props),
compute('m_10_9/11: ${c} BSUASTTDJYZCLLRHSWONQJUQIPSLFRCWGHJXLDHDULQZRWJXRAOZARLBUYVPNJACVKTUACAVPFOGZGAEWWFLMGHAYKGJTQREYKNO', props),
compute('m_10_9/12: ${c} CJPZOTBRXPRNDZBNZFPVQMORDOQHZHOCLCYYUXTSICGYIWQGPDANQIYWCSUBJABLJNVBXJYSIIMGTGNJLKLISYJWATCGKHATAZDB', props),
compute('m_10_9/13: ${c} BRMVBFUSYAZRITMXUUUTXJXNIGQSHNGNLXFDZFYFFPSIGLFJGAKVYTHWSIFDTMIQCKNCYYKYKGXAPCPBXSYGMXGVXHESXCHPDHSW', props),
compute('m_10_9/14: ${c} FIEGVPCYGSYMKDGUBSKLNSJDARHZGBDWEGIICUMNNGLPIJDQDFYBLTHGWAZAUEMJPXHKPEEXNQSFDYXJDBSOMRJDKWHHVMBSPUXJ', props),
compute('m_10_9/15: ${c} PJHSYCRKXBVWWSDXAMUUUYGZBXZWSROBCHSSFORHKXNLKOFHVYGMCGPZNHRLYYRULMNYJXEABQEEDWAXLYHAWOBJQGAMBVYNLSGK', props)
        ].join('\n');
      }
    