
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_1/1: ${c} VYHKDKRGQCABSKILFZAHIRHYIXMBOPCQRLWPVQLROZYXBAGXRHBEBTCWHUGNINBAFDPVLAVNHKWSJOFBJHHGZGRHCZCDZLRBDUZT', props),
compute('m_10_1/2: ${c} GDRUEGDLSNRELUFFDYJTGQCUBILYFVBNPEDAEXOALHMOWIHIEZWCYIXKYRAPJLWMOEEAXSABVWPCKMWVVYDBGSHYAGJIXTVZIQRM', props),
compute('m_10_1/3: ${c} JEAXVQFIDRATSLVVOFJAWDEKCEVOOEZIWGZNEGDOCHSRFLAFVIISEFBHZKMLYLFPLVJBSZICTQQCGLPJHXYDYGKETYWNWTVMIGIA', props),
compute('m_10_1/4: ${c} YKHVZAKEKELLBTCZDCUPNNGNERDRJDXQCLOEYSHHNYIFUNEXABTKGDGCPXVQKDXOXYFWYBEHELBRYTIZQWVOJIYTAFYKPHCWKLJU', props),
compute('m_10_1/5: ${c} FPRREQISSTPHHGNPRAOMJNUHPXWIJTUZZTAJDJNKZXHPLZZESQLMELBJIZRUWPWOJTCYMFBXVHHPLUVZOHZVSMIZGAWGPDGCCANF', props),
compute('m_10_1/6: ${c} FUOJONEUZYOFOFHKXUTLYDGRZIZYOPXYRKQLJELWCEVHFUXCCFTYEKSADVRFLNNYYWKQSVVJPWFFTMMFFEAZTYPYJDIPHLKZFKXK', props),
compute('m_10_1/7: ${c} CIWLFGQERULIAFAKEDSULRONPIKIVAKZLNRJKIWNTVKDGRAGOMLTZSMUPWKRUSOMBQDNLPTTPFKNTUVAAGORZBJAMTKEXBOJADDN', props),
compute('m_10_1/8: ${c} PBRFDLOWOXCPRRJHSNMYTNONMORUPRKZTFDOKAJEKYMGXAEOUTITWJAISBWQALRJQBWKTBDEXVVRNTNOETTZINEMTXGXJHHTRLNR', props),
compute('m_10_1/9: ${c} DKHBIESDAYMJVMQWBYVUGSZXRUURQSWSPYOJZEIIWNNWDXHVWMCULZJDGCSEXWUNXWZIAQGNTFZAZHZABOWXOGVZCLZDWXIVAADN', props),
compute('m_10_1/10: ${c} MWRHBQNFAKXVOCWBBLAVZAISLEOIPDGLBOCOMTLPFZMXKKUPCARGUQOFYAULVGPXGKFYRXZDXPLRFQVMPLRDRZJUIDWKVPGUECAM', props),
compute('m_10_1/11: ${c} LUNLIYQJHCCFATIQYYELIBZDUMMEXPNDGTDYBBUZESMBPHQOZZXFBGTHLXQIXAZICUIRTBPTSQCMLXBEWRJUIHHZGIKQSDOTRJBQ', props),
compute('m_10_1/12: ${c} PZGEYFJERWBNNRZDUCGFDKXTVTXUVPCWMXYSPAHPFMFUTOJBZBJHIHBETNEPHIYNAKTBCIACNSYUFMHVPCXLQZRLRVOWGYAIZCLH', props),
compute('m_10_1/13: ${c} ELFNKWCRUQMHECZZWPLAZLZNTSXKKEIUACLWUGWFTJFVPJZFRZOTECIZOAHFAOMNFKFCQTXVFXMYTNOANNRQBGQMWDGSGFNTMKQA', props),
compute('m_10_1/14: ${c} HHLHHNNUCKXZAVYKTTDYOVXDQFKNBSCOLFYZSWWWABYIMEAHEXHTUWBGIYEQYHZWYMIEUBIEVNIEYCBPTRNUQEEQLMRJBPDMZHVR', props),
compute('m_10_1/15: ${c} BXREBCIXNZXCDUPZKGQSELIWMUHRYVQBOAFSVJIWIYJCXULMDSZVTZZFGWEHZDJXPZWLCCXYBFWIELVGYGSPVABWPMBEJAHYUXQU', props)
        ].join('\n');
      }
    