
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_4/1: ${c} RJUIJEUODUJOWVXALIPIHXDEFZKHPCSXPYFKHKGBUCHMIMKQEJUOHJQHSDTNXDGEHKUQIUMWRXSTKPTLRRCDGLXECVJJWVNMQRLI', props),
compute('m_10_4/2: ${c} QMXHUCXRHNOWZHHQSHAWNQUMLZPZYLXJYEOVQWLSDKJXCDRFFSQOAPAACFWKNHJJTVZFMHNQGWPEMNDONCOYEEFTWDKPUIGRYMIL', props),
compute('m_10_4/3: ${c} QWERTBOIPCGTFAJINXZLCMVSHDQWIAEXZTLYSRNZBLMCVTGGBZCLBUFKJDEDBCDZRGXOVLCJRGSHMTQOJURYXWCKGECKQIUWVPZY', props),
compute('m_10_4/4: ${c} EJWUQRFKHYVTFAQWAHQTXFSECPWFKFTPDHPNOJIQRBDLFJCWKBVMBWHEJQVAQNGJUOZXMJNFSGNOSPCGDAGFNFZWTIRIFERGPBGC', props),
compute('m_10_4/5: ${c} EQZMVQCIEYGDBWGWWOCYENRBWVVSJBDYXJQCKQPRBRHCYZUDUORFIJGXQGTCQTICBGFWKQJHWGGFKCLOCPAINZYSHMBTXVCVAPUW', props),
compute('m_10_4/6: ${c} BDNEFPHTVDFPAHNMTCNLJTWNLKJHLRGEWCHVYBWGNSMMTLOQCZOHTISCCASDGGQGUFFCBVRDQAGANFKXISKXQYRMCWXYIJKWQUBG', props),
compute('m_10_4/7: ${c} YUMXSAVVMRFALTUIGAEMOQSDMQIQKRPRGBJIHQPAVZZABLOURNSRFIUGJWQZOBZOSXKSGVZFUDFNXNKKCMVEPNUCAQITJEHJUNRV', props),
compute('m_10_4/8: ${c} IMSPQPYEVQFCYTAUDTGTYVUMRQYCAUNHAMNREULRMTWDUMPPFFZDKWZIFUGCOKGLMGWEFUMHAHBIRKOVZTGJIBVGBVUNSMJTOVYX', props),
compute('m_10_4/9: ${c} WPYHRUIVPUZIVBLPOMXNVFTCVSFDLYQKCOWHGFTDZDBTBOEOAVUCALQINDVZVOMIJPTLXACCVPFCDUBHFKKNUBDSORXIUPINZQPX', props),
compute('m_10_4/10: ${c} KSMLCHSXPWGZGJCCGNSUOHKCQSOTHSGWDEMGKVUGLILDEKGFKZWJZAJBNAJYRSPQXCXHGBPZVGQVEXOIHETGFQCXACOUNHNLOWHJ', props),
compute('m_10_4/11: ${c} FSWBIPRGLIBUTSYOOQHBYJOIYLHNGROYJGYKDGLVEXXIKGMXDYNKGFVOCFGOEPTQPDCYJLKMFSBNCJJYFVNOFLMQCOFMHDVFUVWN', props),
compute('m_10_4/12: ${c} VESLNLPUHGSKOZAAOUJKMJDDCSNANGSOLOCCAWUARROQCOZOJMZWWEIEVJZHKEIXYXOOEEBJHWDISECCHFLZKHJABGHDUPHSEKJC', props),
compute('m_10_4/13: ${c} CSCEVVZMZYAIGGBFGCLQSCVMRTJMZZSLICJBGMWLOVIRBMFWCSGUNFZXNUGURBPMSIDYOVMWDURUNQVBDEZENMAZYGRSPMNUXFTE', props),
compute('m_10_4/14: ${c} KLVCKQYGITFYPDMDNCRVAMQLBBXXHJKKGXBIVEVULCIKLFUYLECCXODUZCMCHXQPESAZRXNVMYIJEKJGRAYPOCXFDVRQPMBWYZKX', props),
compute('m_10_4/15: ${c} KWRVMGFBBGLVKPSOBEAIBZLBJTCCJRIJLSNXIXSETLFHKPUGKSNNVWWNPOPGBSCOGQBJEZJRLJXAGJDAGOTCRPMOZOUPXISEASQQ', props)
        ].join('\n');
      }
    