
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_19/1: ${c} WLRPBFSZOOHDHBFYLMTABXCMWSCUYIIQMDAEVLVXAJASYCBCQIJCDVRELJPPNWADLPPKOCBLBGAXAMDBSTXKVKDWZLKMPKZOWJOG', props),
compute('m_10_19/2: ${c} BLYZLESNSNYQYBQHFNVHOUZVXZTQCBMBJYTJWPJENSMYPTLBAVRQEFPJPDJZDIBNIWQLEPEAKQGHMZDMCWMDMIGITQALOXBIKAVB', props),
compute('m_10_19/3: ${c} WQDUXDIOBZOBGSPZSSTJELAUMRIQMRODRBVCEUZIBVJVZTTFUVIXYBWMDFSCISHRPUFPPGATEAWOGBJCGPKSZXYBGPUCTUJSARWO', props),
compute('m_10_19/4: ${c} KGNCKXZUQWMTFUJLHISRCEFWRQUPRGQTFYHEQBDKXNWYEXRNXAUADBFOLNPETXYHMSLIQHPVELRUPGZJZWTRIWGSEKTTREGRRQMC', props),
compute('m_10_19/5: ${c} WNVZSDWQWAMMHRZLASOMEIHFYMNYHUGOLCTWVKQMVOYYLBAKTBXUFFPRMKQRPASSFUZQVONEELHVGQLOLUGUBDQYVJZPGUKLGYAE', props),
compute('m_10_19/6: ${c} ZIUKKMRYFDPACXZWCJOITEGWSRFOFNVHPZWPDPDUWQAOJNBKNWNISOHDCNURXNBPGEQGYNVLOZTZALABYRFHDNBZMBNKLLJNEIYS', props),
compute('m_10_19/7: ${c} ZUBRVXHFHVGEDYWYTAHDTMJGYDJHLTWGHHOTBQKBVKRMXTIHBIOGBUPHZXVRYIYEDBPFHHUXOPJESNATRREARZTRSCUYFENEQIPW', props),
compute('m_10_19/8: ${c} LIPTFJTWQRHYTHTVJWWYPNLENVBWZKAYSGNZWRDMCCOKOXJHONKEDSWCXGPZNBSMGMSFQQWAOSCIWMUFKBTRPGLMYGTKBNDVDRXK', props),
compute('m_10_19/9: ${c} UNJYUGQOUMNSYUYUFTUXSNSTSJRRPJWJEQRYAKOAFTWVYMHJLQIVBAKKANKNNDJKWUMUKDPBAYMOXWRAGBYVZEUFTEOBGVFWLUJI', props),
compute('m_10_19/10: ${c} XRPJETKFJCVKSFYHQLTQFHXCMEXIVDOIVQDPOIOTEYJUZIXGROSEWCPWBWGJUQDXHEWLSCOXZVRDHIBOBZQUTPHVYQWBEWGZTRNB', props),
compute('m_10_19/11: ${c} QVMBHCEWJXDHYSZOVYTLTNVLQTTCSKHMLDADPMPKIBCRBOLXGNNZJQNCPBDKDAOODFLRQWGGLKHGBVTWCLVRDHZIAVQGEYFQCRDA', props),
compute('m_10_19/12: ${c} BXBHJMQNYKHOEZBPHIYRTKHCFLWICMXMVTFYNNZSAHFSGJKWDTIOGOSTSWDODUBLNVMCKSSQYWDGVTKIJMYWFFYKKPNOOPNBBZPE', props),
compute('m_10_19/13: ${c} GWYIGHJDEDMPEPMPRUHYMAQWUCOGLSHCEOGDQNUCXDUVMAFKMWSKTKCJXNCSRIMNUEWYQDCEYOUFUKBOEETJFYQMNAEPDHRUTOKU', props),
compute('m_10_19/14: ${c} OHWTVDJYUKOHPZQTAYHMFALGUGGWGZPVGUCWTMRKBRVVALPOGRGENFKSOLOFDCEOBTENPYUICXFQSEMJKAJLQJXHPVMSTWONYRWJ', props),
compute('m_10_19/15: ${c} RIMXOYCLZCOOZXYUPMOSLILZOWHUWYUYFGMGQLEDZMBZSZDJIRIUUPLZFIUVVSREOLELQRPGKUVQKKQGJMWSJXPVNSFRCRBWHZDQ', props)
        ].join('\n');
      }
    