
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_15/1: ${c} FZXUHSTDXUQRSEJFYIWPZZQKGAMYIWNREYAJDSOOULMJOYIEDAEIDKEGFGJEVOVSDPOXFRGXKVVMDGKZEAVILEPHQXATBTDITSRK', props),
compute('m_10_15/2: ${c} SXLEDUXULLEABCLUCMIYEASTQTSORCGRZJRLBNHAJSFLMPBMUVUZZADKYJLOPINQULKOGAVKBPOERQJXSUFMAPEWKIUIMPOMSEHK', props),
compute('m_10_15/3: ${c} RBJKMVIOAUAHDOMQTSYWGXSMBEGNLUOTPTBZXMTDALCYVIWHMZZRORXTICNNUFNAHLFACXGRGSRZOXCMAZOKVKAOZKHJSWUBYOBC', props),
compute('m_10_15/4: ${c} PEJQZBMOCWVDZZIKKJHBTLWOVJBJFHVRLFBWJVYGZJIDQOXZHWNGWAGFIYIDDVPWGDBEWANYRRIPIWJVKZDARARWEBTURKYMWKWN', props),
compute('m_10_15/5: ${c} NNKLWFAQGUSCJKMOMMAOVEVXEGUDPRYPVQYENYVFQUVLFELXSYDANCIBORAWICDPRBFQGDUQKQXGJACGIXPUDHEHAXDXURUNKRFO', props),
compute('m_10_15/6: ${c} EVEOYDLZDOIVVKQKAOYIAQHANYBOJYQZYCSJCFGZSCZEBHCWDYWIGQMCJANIZBNHRPMJXULZAFUHDLEFNHAHNPSZZIMJNSTQUWJA', props),
compute('m_10_15/7: ${c} XRRNSDQPBCXAYGKWLEUSDVFPZUVKYJIBOXKUBXPJJYLGXHQXZUAIYCRFEMCMOHFZRMNJJVSWWZBMADNYFFGVSRQJPGEQECTCFQZF', props),
compute('m_10_15/8: ${c} MZKMEIOQZZHXOYGTTGQVIUQDOIONWLCGMYTBOOBTEMOVCJAEFAAKUBOXHKZRZZTQYPFALLCLIZTEXBGGVZLAUWYISUTCAVCCFDUX', props),
compute('m_10_15/9: ${c} SXXRQWZTGPUIFFSUDIZRJFLDDBDYTCWRTCUSSKSQPQCDVWUXSZGGPKDUBAJUDXMJNBDMEEESGGZURRTCLUBLDVMREZTOEBCVXEVS', props),
compute('m_10_15/10: ${c} NRPOJIEFKVOVJLARVLCIIZXDAXCJNHRPARKXIRVROGPDXAFTDRSUFFFUPCZDMMOITSCEADBRPKFQSQVTKOUUMDBVSXTXJIPHQZPN', props),
compute('m_10_15/11: ${c} ENMULICRKWVOZSDLBWIBGRCBOFEAFEYJZPPIUKWTBKBBORVKFZVLCPWNJORRQOVHUFXGRMCDZNERNTJNXZYVLIXVFADUVDAPJWRD', props),
compute('m_10_15/12: ${c} SOIVMGRYXAGYGDTXXUVADSYIKAANTOABEWBFZOWFIIEQLJBPDTIYDFSNYSHTUWXWFQQVYMLESHDDIQRCDHKPIJPSMUTCHADDHUWS', props),
compute('m_10_15/13: ${c} KKPYQWDIDVOHPPZTELHYQFOGGRGAFBVDULOTPOUGUSBQCGAUNIUOOFGCAQRATMCWGFGXTLREATLMNMFOSENJGSTCBXSDUYVGSKMQ', props),
compute('m_10_15/14: ${c} XPJZIBKOQGUYJKQNMQMXGTKQLFRKUIHMZQTTLVVZHHLGIXPPMCBANWZRAJABTWEEMUYGSJFZHJAOEJCEFOPCCDUSWROXILVAPFYK', props),
compute('m_10_15/15: ${c} ZQBCDUHIGSINIRXZQPAYKAVPILXAUJHPVKYBORZOJQQBPKPLYQPFKPIQSQTEQFUZEZCEMGNWRREFZGMSTRAHDSCIEVCJPBQTHPFU', props)
        ].join('\n');
      }
    