
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_13/1: ${c} ZJPDJRDLTFBGCEHEWSDUPDHFWXSITVNRBQXLIVTQMOBICKTZOWAADFHEZVSMKUJBVFSVVTGHTXYMBYDKKSYDQUHWXCCLIIUKRWHD', props),
compute('m_10_13/2: ${c} GFXEXBLTKYUHAYYCZEYFDRYAGIJAILEAXBYYUSENNVPUUDFAAKADSMPSIYQSHLDSUNOVRGVEBSHKDIXJTMXPSFETHJUKTZVSIYKN', props),
compute('m_10_13/3: ${c} RBBDANODVBTKMESLVFMLHFHGIQBVYPMHMFUBHPVFXKFDTOBQFJWPVLSTLHSGZGRWWTMBBZPOBVXRUQWLKMPBAPYZDUYYSYIEJXFX', props),
compute('m_10_13/4: ${c} VFXLKAILKPMJNYWBWRXJFDVRVPZVJJNOZGHMGDLRFRFBICVRSXJOWBNIBEULRZOBIISRLDKLSCBPIFFQYLSJOVTSMTUJZCTOXTZL', props),
compute('m_10_13/5: ${c} LBHTRVYQWQJIPGQJXYLQFMXAQGGVYAFTWXAZOMHETFBOKRTWQQLIAXOQFITAKVDNBQUPXJYSZZFVIXBIPVGNYFQWGVDWNCHHAZDT', props),
compute('m_10_13/6: ${c} ELJILWUSPNNQGWMXKRYHYXSXYEOGZPTFGBRJXVMEZNWIJHOVIXGOMNKEUHNXICBGRSFUBYEHERPYMTJGZJETMGOEFLMHEGUBXWOM', props),
compute('m_10_13/7: ${c} CFXYQBUNZREZTFZZWYGPGEOXSCQSGUSJYWHSSTTBUIJZIALLKHKMPALSVVPXBLTQVZRAXUWCPZDYFREICOCDPVCVZVDCESWQMGYS', props),
compute('m_10_13/8: ${c} MATRWQJCOAYUIHCIRCCPYLASXBANWEMAXJTMAZPHNFWIHYTGCPBZCKUVYBTXJDULDNBQOSESGSJZVEKSQOOZBAULIGVTSDGWUDXY', props),
compute('m_10_13/9: ${c} EPMJMOQSPZMOZXRSSSZCZXZMAGGGLCNMJZOEQJOFPMIIPRIUUAIVTMEBZIMJHYANNNKPQVWPJZKZRFCYKAKHBZJAVXRTCNQSWPPR', props),
compute('m_10_13/10: ${c} IZJIWYXLUOGYGBCVMRRWMMZADXVRAESSXERFDGFGJCLOQCWKCXQQGTAAVAOCCXERTWFJIJQQULMWOPKFVJVTOXVYGQAGYGAHSOWY', props),
compute('m_10_13/11: ${c} KGDKUEUBNEPMWBQQJUTDXYQRIBZMEQPTVZVTHIRWFMTYHCOAXDGPYNKQNMWERXUVCGCTRLJKBHYHUNDKKHGOCLJRKQNNJKHBSPOR', props),
compute('m_10_13/12: ${c} BOHFDNOCZQPZGQORITJLUBHMKNVLFPPZPIOXGYUGHUORQXLZICQUSYZNRJEWLYCTBXMUDPEAQLYHHSLZGIQCWQGTZOOQRFZMCUGA', props),
compute('m_10_13/13: ${c} RHQPVBRBRYSYWCZGEYAMRIHJDHWLLCWWQLVSLPDACIPYOFAONREZPTOLWKWQNCZELJDURMDGADBXCWDQHPUUYSJFJEJBQJEWADHW', props),
compute('m_10_13/14: ${c} MNXSDLYSDRUZNKQRBOSDFXXHXPSZAIDZQZUPKXENQECEOZRUXWMBYSAYCRHKFRJPFXXRWXWGDZXTFAYPDRRENKOJJJXHNWXFNAUZ', props),
compute('m_10_13/15: ${c} NLSMJZMWRVSZFOLXICCYOBCSQRLCOGVTNRDNVMNLILIUJVKIRITJHLUYKFMLOZJEHZARNAOWJZYGFGUZGHNSHQHONXHGLEUUDBYN', props)
        ].join('\n');
      }
    