
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_17/1: ${c} XEDVOZFHOJDDGJKTDROYDISHIWRBCSLQGEDSAMXTAQUFJTEBEUJRDKBNZHNBZELSREGAKQOBGNHPUKHSVNUMOQTKKROPWSIIVKKY', props),
compute('m_10_17/2: ${c} GADLPRTYPCWPOFLRLCPCSVGOBRDPEYOMCDFUVIDQRFVMJNCTIWCCBOBXZYWDNAUURAVEJTGAGFOHBCXDDDNHDOHYZGVJUOLJMJWG', props),
compute('m_10_17/3: ${c} FYYCVSSQJXRXQHNZTTTLVGUEJYUKVZEXBQTMKIPGQZBHFDCZTSDHEFHPFSHUCVNSWAISHSWKSBWMFQOGGSATGWDBMIVAIQQCUBSX', props),
compute('m_10_17/4: ${c} ZJYJTBEFDDWUZBEIKIRQFEVDGYUWTHJZBCGLHCUSALFRCAWUVELRYNYHWPYTKPXMRQSSRILHLTSZADRITHYQTXPBMZGXJVTZDQZZ', props),
compute('m_10_17/5: ${c} NKQAFUTWXQNFMSNTMJELWBRYLSOEVMUFQCICKSXGGRBZUOIXCEWXDYXJQZOPQNSKOJJNIVRCVROHPKMAFOUIMYNHWJQCXKXSFCVT', props),
compute('m_10_17/6: ${c} RCNLATCQJJMCJMCMKUPJSYWVSLCXMULTKOAULSHNPFQUDXOLPIBOPMRFGFFYOBLGGKSDZSUKNQSMHGMKTIXAQEXCDWSNRNOBSNRY', props),
compute('m_10_17/7: ${c} WSWHIBOENUWBUENFZYNATSBXOJOUCMIQSSBNGXJGVGZTDMETYROVAZVKKBASKUBXWPZXLXAHFZAELNCEUHRBHNPJXTBZIAUCEMGK', props),
compute('m_10_17/8: ${c} KWFUAOYZGRPATNCFUDIMCMZWWNLGIGFKUNKZNAFFDQUCMPRCXSZYNABYNADDIXWGPWQAKFGKSWKJUICOPBAAHRKWHXKFQXKBSVPZ', props),
compute('m_10_17/9: ${c} EWHAINVLAWFHDQTEYXAQCPEWGWBRYLZOOPFJLXZISTCSRENLBSZKPXGXBGUKYDLVIUAJGEEURIGGQPXEKRDVOXAQADATJBKHYVKO', props),
compute('m_10_17/10: ${c} GRRLBOBALLLVATVJOOGGAUMQUPNJVNQTFICRVNBWKVDXWNZXPLICANNSXMTRORIIVMTBMWVNSHLRYDGEQACYAAETIKFLASTKERMG', props),
compute('m_10_17/11: ${c} OLAQWDFPJRUCTMLNZUHBVBGZTNTPXDELXWPNRGJIQUUURUVRETZBDNPJCDTGXFKTGDQSKBHTZUNKJNLDFUHKNVZKEQCBTBOSRJOE', props),
compute('m_10_17/12: ${c} BPQOQNKEFPBGHBWUOPNHKBVCRRCCCLWIWOKZCVJEWUEKFMFTCVUDRTNIXQBIXAQYTGVFSHWOMNCVZKSNMGFFZQWRYYNJPHBOVSIV', props),
compute('m_10_17/13: ${c} TGQUSOTAPDEXRESFJXSVOGNTXUINKOIYJSHMNREMROTRRXUOXEWHOZQWFQHQJPEWQQKDUUQGGTTRTVRCYINDAWHABLNODUJUVNWS', props),
compute('m_10_17/14: ${c} NIPYWWACWGDELHQBUGMFWTNYPGSSCGVIMAESVHBUJSSVTPQYQHFPHVAYAVVCDJERHVVGSTKDACPEJSLKHUYVHFXGWKWTLZJDRYJD', props),
compute('m_10_17/15: ${c} OMXUKJTFYZACYPBQHDZQHSBIAEUJHRDAMBOLPGWASQXQZCFRGBTDNZAKPAYAZHTHCLZHAQANTHXPDJUGWPGVAKZHCLNFHYXNQBHN', props)
        ].join('\n');
      }
    