
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_14/1: ${c} IFALSUOBYMFBHOYUEVFBVOLWUFXYDKEMPSXSACRJRDWPRKNBTOVCMSRBOOQNOEWKVWBYGTVHVLEVAAHNZHSHANNPMFISKMMBNKPI', props),
compute('m_10_14/2: ${c} OBZJASAERGXYIJEYOBZHPVSWDGDIXHTWUMGMIKRZKFCAEDSYBIXIUWZEVWECEQFMHIOJDVZSQNHLLNHRQORFOUBRXGGZZKQJCXWZ', props),
compute('m_10_14/3: ${c} EJBCXQNTRXDOHIQWLAHVFCQOJKNTNZTDTFUDNDFJLWHCGLERCKDPFQSGPXZRHQGUDEXQXUWYLZJPHPPJDDQGFAWDESMCVOQAHWXP', props),
compute('m_10_14/4: ${c} ROWVNIMZUAHTOJUDSHOFDJNYHISIVLFHZGPCVCFCLNJUNVUMCVKSBVSEZGUPOZKDPETIZRHENLTHGLPPENTEROSYDKSFYZCTACIR', props),
compute('m_10_14/5: ${c} GGGAFHJTGFLAJUBSAQHVKQWLIENPDUSRJWTXNYGBLVCHMSCWFHHCOHBDZGWRXWXQMJFIPBWFXAVHMBJGTWEJWYNESHLUZVXFAXFQ', props),
compute('m_10_14/6: ${c} WNQIEFFOOGSQLNSMPZBVOJRPZNRHYRRSTLFUIJMDCHZYDOCHMULKELEBLFROVIOUIVHEMJFBOUIANCASXIOHHGOKERHSJYRPYRQC', props),
compute('m_10_14/7: ${c} UWXPKKTZWMTEFDOURAMJOVGHRGFUVFNIMAXJSXEZEMYEDYNJHNUMSPQXXUGWXNBXDSNGBZWMSSFFLVPOVIZKFGPFQOKOERFAARXG', props),
compute('m_10_14/8: ${c} NIBGUYDFGQOJDCEOWGAVTVOCUIUJXDVQFHWFJPWXQGXZXBUFLJYRCYHSVTCDQVADQTRJJSFAEVNIWRMEQYAISYAHOXXHKCNRFDVW', props),
compute('m_10_14/9: ${c} VWWKFGXDVHKCVQAFCNAZWLXRIHIEBRAGQXBHCSRGISMEPZMUZVWYQFYXTAHBKWRCRNAFMHJWLHDJYMUEOAMAFZPGYPWPWAFNGWTW', props),
compute('m_10_14/10: ${c} ACNLLVFDDPOHSMQKYJHLFUNDOFEZROLHKXVWSYDFMWOJCMGOZFRSKTNFFZRIZEFGFHZQAUPHMUFIXLHSQOOZLHDCYEJJIUTRXQYC', props),
compute('m_10_14/11: ${c} LURDWRJCVFXBXTINMGSIFRNIHXLZKJCCFMCGQVHETAVRBGGILHWIFZJOWJZAKYZGLBFFYBTBLZZNZSVWUOSCEHDJQFYIEICINCNH', props),
compute('m_10_14/12: ${c} ZRVAYTSGREITYZOSLVSKERYAGLJADCHMUIZOUTXNPKWGWKHDDWFYTCEUOPIPYORXLAUUJIPLMYXGLGPVOVTRAIIBOEFBJVOOLOXG', props),
compute('m_10_14/13: ${c} VBOLFLCRJBGYLNALDKDKGLHQZJVWYWTNLNDKRHKYQCALAXZDYBUDQDXUJAKGOVDEPMQGDRBVTJTVFQIMCLYZFSSNALHNNPXLYDIF', props),
compute('m_10_14/14: ${c} YKQLPMRXJYGNZBLBVJEVVLTOCESBLRJHEVYUZZHHRMABGEBPRZPIFGKIGRDPQYCTMGEMVBBCOYYLBZIOSAXLPNLCMHXNQFIYOLMA', props),
compute('m_10_14/15: ${c} IERZBAUJAPDIIWYTYNSNBVUKAVPYSAOECPNXIGNOAFSKJEYXUAVBSZTIFMZQELGRWPJLKRDLDCTLCGHPHHVJUGJHAUUFAGDNWZBI', props)
        ].join('\n');
      }
    