
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_10_10/1: ${c} KKBXFDDILAIZPUFASUJAFCKRZDBPKZKZMCVXELVVIPXZYAFNWDAKVTFAZBXMAMETAGFXIYVXOMPGQFCLTUZLGEUQWKYKHBXSAUGS', props),
compute('m_10_10/2: ${c} ZJFVWZTPTSGAKQNHLSSFBXPVOAFYSADBCVGNEOPJFSNPXRVRDTHGIGBWNUSYSNCGGQRMRWIGJYXRQTFATGMHXESPWHFUKAGAKINN', props),
compute('m_10_10/3: ${c} DQWXZBWTEQNXUFIDRCZCOKUUHFCZGVFIZLAZBSQPUDWWLBXRNNNMETXAWVLUGIVEPPZHPCYKXYIVUMGKTZFHHFLAVNIZCQXGGOCA', props),
compute('m_10_10/4: ${c} RDYPBAJDHRZLKAZSSINCIHRGGAAIRWXKJGXWGNWUEWBXBGOSPLSKFEJEKOQULNZFZNDTBIFXPEXKTNLHPWLNLNAPOMZEOPOLKWUM', props),
compute('m_10_10/5: ${c} UNMYFIISLTVOBSHYGONIOKWKMWEKJNPBDTJWHBWIXXQHITSUPMHWNZRCQEUXCKLNRHQBQGQXJAEBDTHXDKSIKDLZXZWLYLNXPMMW', props),
compute('m_10_10/6: ${c} KVKKSVYYGCTHGYPYHMNUTIVPRNYHDCMMGNENTTERMGVNJTHSCPKYVHLEHBLASWIOEFXYNZVIFIGCZQWVNXNPZPBPIDFGLRULOJGF', props),
compute('m_10_10/7: ${c} TFURMXHVYJPOYGIPKYZCJWKQLGJUPMKTEBYVFKNTLCOXUXJZSCQVGFFXPAZNYLXHJXCJICQUAFDUMRHJCHJFPSDXODNGZUVEGPBW', props),
compute('m_10_10/8: ${c} NVLSGVRSVGJEMIGMMAURLHFOAOYCXHKIYOPOATXYBOSUUUDLKCFREFQHGCVPRVDBEONXRGNBSCYTVALLAKEYVFEJNVJISSXLECYG', props),
compute('m_10_10/9: ${c} ZUEIHFNXVKECJLFFACGGJFSRRPZYDBWOWMXDQXLDUOQDQIJYVGXZPEFAJPWIFUQQTZJTUXRSAQTPHRCPLPLZSQRHVBRXCCIGGSYU', props),
compute('m_10_10/10: ${c} CZRHCZKMIOFKPDDUOROVNDDZGLPXTYFKSSCQSIAUBNJXZFMJNUKOCOEVICMQJYRUAJMJNUIDURBSMXSLNIAKOMBENUNJGBWKEHSA', props),
compute('m_10_10/11: ${c} VYJWLGJUIHINJLCMYBEVJEGDSTBALAMADMEWYTGDINPGXNVYQZGSJHTEGAMZGXVVDYUDHKOUKPXMMIMJYJLSOTRRHFPWKAMUFTFC', props),
compute('m_10_10/12: ${c} DFNZMDGZIOAEOAZNTADTSCTCIIMJBRNCADWQMNWFHTZZRKTEPGYIEAQASLCBPLVGATEEUYWSXKMNVGSDHIOHWBRIBDZEFTQSNMRD', props),
compute('m_10_10/13: ${c} VBXFOUEKVUOTPSEIVWWZOLPJNZICBPGABZSJZAFGQEXSGRTMQAXXWMNPBLGSYAWSZONUYYEGKCLLXBHRWHEWFUHDHSWEAXVNRVGN', props),
compute('m_10_10/14: ${c} WFOQLNZLXMDXFWOCREPPIWJAAGYRPRUVGPPFAJZAHZABUECSCGUGITPCVVIMXGYZAQGKHQUGDDPWFYTLNIHBJJZWGHFBIUWACPEL', props),
compute('m_10_10/15: ${c} LANEBVXWPOHKCKJVMFVPKJWORSDVDWYPUQVHWASHYRMMUNYKBRJJOWYJXHBVVXEPLRPHTIMWTOGFYWOJHPNZFGECWWOBYUTSLILI', props)
        ].join('\n');
      }
    