
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_19/1: ${c} BFVEZHTBINNMJHOQWZTWMWSXBQSKGJJFBIIHLMXQHKXGIAILPWYOUSZNVWXLJIQCAHBPRZQGYBHBJYEUJBHXMUQEMEAGEHNKHGUU', props),
compute('m_11_19/2: ${c} XLLKYRHPQALYGBQWHQBGMBNLHGENZOSPNUVQYOFKCABUOEGFOGFVIHHBLOPJSJMARFDMNFFBPPXRNJMSPEOTUHQTIEARTQOGKJZW', props),
compute('m_11_19/3: ${c} NQMWHWFIWFAQGESYCLUNAPAXXAMANVSWNWVDKJEAQZEHICBUBDACHCUJEVMWPMEJMPJTDLFLQQJPRAGIYSUCWHZJBJOVOXNIEFJQ', props),
compute('m_11_19/4: ${c} RDHQAOMFFRITNBAMYYBWRNCKXARBHAOVZFJJSVIEVKAQRTMIEHSGBDTYDBIGWUYPGUZHDLAFTZXNYAFLRPASDOMSDFDERJMDGPUJ', props),
compute('m_11_19/5: ${c} BFZYKZAYCJTNIMFPRIXZEITISECMKNQWDMSKHKWGPMQFGEWTZFSLPMRYYUMPUCPFCFIPWRXJNWGWPSQPFVJOQNYTWEZPNNCMJUWP', props),
compute('m_11_19/6: ${c} SPBAJKVJSBLTRLFSJTFVMFNYAUXSXNGHAQNMDWSYTDVJOHGAGNIPSOWGBLKFRAJJSXVTOGWYRVEYDUQWZEPMMGZHHFRBXSHKYDMV', props),
compute('m_11_19/7: ${c} GVVXVYHGMSFVNVQMNIFOTHZXBETLBCQPWJXWBIUSBXCOMNBAYGPBUDURGPNMTNUJHYWBVLWVHHJPUAPBAWOTCCIBXATJEVVJOTEG', props),
compute('m_11_19/8: ${c} GOEQWSIQLIWYMGKUCUYRBUEUTCGAXHDCDNJYDYXCIHFYZMIFFGCVJBZQYYDNDXXDIULVRMBQCGBTXNFLYULTIKAHXQBNZWEMBGZK', props),
compute('m_11_19/9: ${c} RYPDROKMRNUQSDZSZXLWABACAYAOQPEZVDQARINEGPDKHEWSRRVTFMUDUTONOHAMYJQPWCLVQFWZTDJTTYCXAVOSIGEWUORXZMAZ', props),
compute('m_11_19/10: ${c} CEGNFCDCSRJOBETTJIMTROOROYHRERPUSMNEXZGTKUHJIOTRDBYAUZQDROXXLLIBSDANSTZYTRVQSPGOKYBRBXJIZHNMVSAXPGMQ', props),
compute('m_11_19/11: ${c} IMREVOGIUFDPGJNNFLNOLKGTTWBVVWHXQVKGJLJURRPZXDDQPTNBIZWSHQNLBZAWIZLVLIVSZPYAHMIKGUADNPBCWEMXNOJVLGPL', props),
compute('m_11_19/12: ${c} SJMKZMFUZHHSJQXXPJBPKTWCHIOYZVUYLYCLAGZPAKRCZAYZXANRNYAJECQCNPNRCAVDJTWBOIAANWNEDGSFATMGGPYUDSHCPINU', props),
compute('m_11_19/13: ${c} XNWWOKKSGOMTWLYXQKLRZVDXHYVDSGFJQAZMNAFHIWTZQSUUPHXNVOPFGLXAYMZIFQWXNGWJWABADMAZJLDPGRARUGSQNBAGBGHZ', props),
compute('m_11_19/14: ${c} KOFJIJLBTMRUJUJQKZAEGGZIRRHBDTRDDMWRYKUQPXEDWAKPYQAYKJDKWFBQPQNMJYTVUOUYTYVEQFIJDPMZFLXKLXHBHWYOEQNB', props),
compute('m_11_19/15: ${c} NOLLJJDTLCOUREVYCLTUUDQKZSFGVLOJLQIUJOGOQMUTJBZYMCPLNRUXMQQCZYJYJMRCXIMSQPMRWXAKUVIHEQNJYCXAGLWMXVDM', props)
        ].join('\n');
      }
    