
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_5/1: ${c} ZDARRYIOUMURHLPNCNWRECVERFYBXKHXBIJVQMKEQUDXYDZEVAXDPYQXDTIOOVEOXMPOCRQLCGHUZYSTCUDHZIARQLCLEGVWORRX', props),
compute('m_11_5/2: ${c} GXQGDQDYHVKMXUVSBNZQRNSMRQBYVZKDNPRCXIRUBRQKFJUOYMEXUCQQGUYEPKKTGLPIPHPDZLINBANTDKTLUOVDSOJCCYBUFHIW', props),
compute('m_11_5/3: ${c} MQCVMYBODBLTIQCJWBQRERWTDPAWKPSTQXCWDDRRCBMTJGQJAOGUILREOTVLTVLVRPODYRKRKVHHYNXOIFWRFZYWZMSWNRNHBAFS', props),
compute('m_11_5/4: ${c} SCCZWCRWZATUMKXOSNOZLRQVCEFWJKWRGWUEFIKXXUPNIZNQGIONHIXXAYZYICASGYQAMBWJJASAYPQAIBLKMPYKIYHZIFDZFLVI', props),
compute('m_11_5/5: ${c} IWCOFRURQSJWTLAHKPRHVYNVCFJAQKSRKJBYCMOMVFXQDWWKPTKCHOCEVFOKRARKBIPORPKUWTRFJQCGGTAHBOWHTIFLUYKIMSDC', props),
compute('m_11_5/6: ${c} SKEOZBFIQCXOOHIXPXQECQLDARWHYSVOLTZZWFZZTTYHIINPYBKBQECBUSZVUPNAHOFFRMMMOVZKIZXZDJVIHSEAGRTBFMZWKWNM', props),
compute('m_11_5/7: ${c} CQIAIPKPJSHTGLPUEKYIWBIGLAWRJPJWNCPOHCHRXIZMYXDNILQSBXZBPRZPUJPSTRKNWYNQKCWDMCGJHDESMIBZNEGJYRKGFBZF', props),
compute('m_11_5/8: ${c} UZZFAHTSTVFPTSNVIQGDKDBXJZKEOJJTRXVVPRROYRKFMDHFOYUVPWJIIAXUFJZSFBPJUPPLAFCCFQHOBRAAZVBVUDMTXIVNTXLC', props),
compute('m_11_5/9: ${c} LGFWDRKOOVCVEXCXSRDDYDOYZINOAWSQOACNFXLZNBVTNYGIRYUUIHJZNRXWZLHFVKBTCOXYSBUZFBUGRHMFZISVKUJQAMDKLAAM', props),
compute('m_11_5/10: ${c} FDNNDASQWMJXZBZPSTGJRLRXBYFJANMRTLCBJXFTDPGFPVRODEULUDONHKANUPQTAQHGJKNOXKKYLJIQHTUZSCUDHSMMYOZWXEIR', props),
compute('m_11_5/11: ${c} WLVBIHULSSYLSFEOQHLPAZVTFQTVFHSYHDCWPGSPMQIJKSHSWAKLCDVLBYGGKXCIMPCDVDXPGURULDEWDFHFILFHMXCASXGPGLLM', props),
compute('m_11_5/12: ${c} SWXRTIUEGFJHPWKAMSHRZLVBZEBGZVPVCGCIAKPCJEIEFBRZJEDIYLDNRYNPLNUUSRJNCICAWIVTQINXIZMXPPNQDLXFRRTGUKCN', props),
compute('m_11_5/13: ${c} JSOCQGVKBHTZODGQPILKQLOXLDPBTXRNOFCXFSEXEIPIOZIEXDGUQZIICXYGYXILVCERYMWUDRKBYMFZITAOHJOIYSCEDPGZYXBU', props),
compute('m_11_5/14: ${c} IRTDCQSJZDJSPPQMDLIYGOHKLJKRNOAEXREAWRCMWWYQUSSMMSHFQSQEOKRBTRSLTOSMHHNOPCYBOPELJRTWVZWRULMNYCNFVMJT', props),
compute('m_11_5/15: ${c} LUITTUIPAKXVVDOUEGRRTOZKOJNXQBJUBREDDHPZGNQAGCBABTVBWIWYICVMFGCJEYVOSMLLTSNSGYVMKEREDOFSZAXDHMVVNQYP', props)
        ].join('\n');
      }
    