
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_17/1: ${c} XTKUKXSETZNAEIKLXWBTBAROJJGVCVIZFPHITNCBYFNWIXMTVZNGSFMUJZUJROIBUZWKOFTJBQDYNPCIKGXSNKMOGJOZHCKHQPYJ', props),
compute('m_11_17/2: ${c} JJMYLSRNWBHYZPQSSXSCZLMZQYQSGEFADLQNKQXVIIINITXLXRHWISLYAOBCYIYBAPUPVHZCEKCPGFTFSKUVJBLJHZENUQKOFPBA', props),
compute('m_11_17/3: ${c} BGQJDOHLXVSZLCJFBUOFXLTGRUAJJJQBUUISIGXMWVQCLASZGNZMRCSEXUYDRGAGWJZWDBULJECXMFISHUCLVVDGRTDBLWUEMLCJ', props),
compute('m_11_17/4: ${c} SEFJIKCDUHEQCDUEFNWRBCURCHRTQHRYCJZUJDKBZGEOYLHRPOYPVTKXSNTZFNODEKQUVEFGJNGEOHNSWLYOAZSRYCEBXJHFFNZE', props),
compute('m_11_17/5: ${c} LSUENXBUSXBLIBGPIRILWCVIACHCNLAFKHMFECUKSUHUTJAMLASQIUPDYIJFZRCPWPYVUWISFMDMBDMHRIPGZIBPXATTGNNYBWLR', props),
compute('m_11_17/6: ${c} KBFHVBGCHNYMETJNSVDGWAIAQIQQOVBCICFTYGTVOUYWPEJWKGCNRGCDCYELUOQDCNKZVPRWZWONGELRBBBCPKKQASIXZNHVXJZU', props),
compute('m_11_17/7: ${c} UUHBZRVVZMQDOWJRNVYVIXVRAPDAIHRUCUWGSYJLSDORRTPVBZULWRHJUJRTNHPOIEUZABMVLTHMCCBOTWFEHDWJNQPLHWNICAWB', props),
compute('m_11_17/8: ${c} LZPNFGANWDOGIFONKETUZGFKKGEPTMHKEEJWANAOHMIMFNNYEAFRDKBREOLKHKVANVMBLCSMHXVWSJDDSDFGPCZETDMWYSTYGLFO', props),
compute('m_11_17/9: ${c} HJGSLUJNUXNOOWSHDSTCQZXZYTQXGFGLCEJKTJJGPDGPWBBQISPQMXPFWKTPHTUGRNGKMIESFDHABZWADDKHTFIKEFEZIDLZICJB', props),
compute('m_11_17/10: ${c} DKIUOAQCJXBSIGDVZVJZVICNUKRRYOQPWEBXGGXYLQQNBYTARCCEEBPXRQFYQBWYVLMDIVVUVRRIEFYVOVFYQYBMYGKIUMIIOFRK', props),
compute('m_11_17/11: ${c} RLCVSZDKKONSGIBWXCVABAGJWBZELWUOGHWDHUNIJBZCRUAZWYYUOEDRDADACNKQRFOVFNCMYPSDKUNRRXOYDVBYLZOBYSVGLKSD', props),
compute('m_11_17/12: ${c} TDUVMQITYWSFLTHFYUDLNZSSMPHVNMEHYIKQGAUBCHZAXYMOECXZVOFMIQXOUKHRFDIHJXDEATXLWSRKKVEMOXVFXDRLGSGQTWPR', props),
compute('m_11_17/13: ${c} YZRQUFISVUFDFDPQFWAPJRGJOBJRKKTDGWLWRENXLKSAJHRZGXCTPNYYSTNMWFPDPBYXIHXNRNWYCSNEPKYTMICVPQIIAVQBTYWL', props),
compute('m_11_17/14: ${c} CJBDSNDOINBYPKWAOKPVOTUIWQFEGNEVXDJHOMVSYHSBBGALRFGALPEZMDJEWWMZMFFIRZPEPYZWDZKQAQPJSGVYQONZYCJWMOQO', props),
compute('m_11_17/15: ${c} RBFLAGYPEFQDPHQGSTXYRBWVOHZEZPFVXTAVJQZHPSEUZJGMRSXBHIWSEDOCGVEJSWFDVMIPWPXFJWZVCHQCHFLQESCLQUSOGNYL', props)
        ].join('\n');
      }
    