
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_4/1: ${c} BAAXCTILNDPIXUWYWBIAOIKOWIJYQQPSLYEKWWZVONNJQLUIYCDNTGEWFYIHNMNTOPHNXJGMXWPHEGZEGAYJGRRAQYWEMRVUUTKJ', props),
compute('m_11_4/2: ${c} LRNHLFSOWONOVKGHFYYXXUKYQUISNRDBLOBNYYTIHKRWHTVKDIOXOOPNXJRUCOMURWQRGRUGCWNUFNQGSVPAWEBZESFXBLCOYTGR', props),
compute('m_11_4/3: ${c} TCHYLRMWPEDUJGUSAAZPIATRAMNQFJLGVTWXUVSMIJRFZFAQPCUGJXLQYEDMVNORKDMAZUXNMPVIIKDBXYDJQTKWGCYJUDMOFMWG', props),
compute('m_11_4/4: ${c} XOBIMTILJUTZAXHOFMFYPZPILWPFZBZYQMJAZDEANQPBLHLXUBZFXXWUHWRIAWPVYTEMQWYHAQBLUZYMSXDGYBJHRNWSZMZLLCCX', props),
compute('m_11_4/5: ${c} YLBGUVFBZLULWDLWEXDEYZMKWUBLWUDGIYBCTEEROAMIKFWJXLCBYGELRAHUMLFMPVYDFNQBHUXPWSPJTCHLOJTLVFODOCQCYRBB', props),
compute('m_11_4/6: ${c} NVMGKLGTOIOJXBWCJVEQNDJQLOMYFAJWJSIUJYBZTZPLMTVGOFSWUTCTHSDBRJGHIXCOREVLJKSOGGZIBCHZPTPLXFUIGPKRJQPP', props),
compute('m_11_4/7: ${c} ULZOVSEZWZZEPWZTDLBWGMVEQPMJDUPEZFSZFWZXWUWMWRCFAIGVYHGDCQHBOAMVMKSMFKMOHQSTDZTTCOWXXDGCQIVBZVVQAIAN', props),
compute('m_11_4/8: ${c} OQJMTTHSYGFIHPZYUPGURIHSRJRUVSOTLFFSMAFJZGTIKNPDSFULEVBTKTWLRXETDFIURQBZETQXNUOYPHMQTZRHBWXVRXUYPIDP', props),
compute('m_11_4/9: ${c} NRBZVHXZULDQQWSKKZTNJRTHTNWFJZJBZEHDSVEAMGMAYCEXMYUSUYHEKTQQRGBSQQIWNZAPOJQJCJAOLOYORIBBWTZNSNVSFWFR', props),
compute('m_11_4/10: ${c} ZZOSZOSCVBPUJHAYSVWYCPHXZNNUGFVUCBWLVJYIEASENPDALRREHNMJPJUFKYAMKLJLPQLCJRFHGVCRTWTIIDUUXQNQACQBRUFY', props),
compute('m_11_4/11: ${c} TKEJAEDWCSDMTGDONTDOTRUKBRDIKHBQMHBGPKJVSIUPJDPAJHHXGYMHKUPGVJXBIDIRJTFYOSZHVQGCGMPPXQWYJCLCRUZMFBAW', props),
compute('m_11_4/12: ${c} BPIAWTQLLNSDOTSFJXTXGGLLYVUZOXUFQBTMBCELPUVNXWVTCEIXPCAEATZDATKNMMWDBORPKFBLILXEWCJGEPRYRIJPLXMIWMXC', props),
compute('m_11_4/13: ${c} WQRONTPVTXSHPFJLUXKGNJRPSVECEAKXOJBNUJOCFGCMKAZMMWWMPUWAMZLZBHXRNQWQFORDMLRCDMVMKLDQSHIYYSGMHJTBEXXY', props),
compute('m_11_4/14: ${c} VKEDUQCDAIDMTUHBIDZOCXCSPQMJKTAHLWKEZTCFJAHJZBZYSMWDLDKEIUVSUTBNQEGOGADUVVREQXIHUEQVTABSKMZGMWXVKOLY', props),
compute('m_11_4/15: ${c} ULEAULHIQAMAQPBRDRAQINOXUHIEGPIAAATYFXPEWJXPNVRGGMQTIFVHTLOMLPEPUZNFDOBJJTOXUTGSWVNATMHUGNBMXYAMNHWX', props)
        ].join('\n');
      }
    