
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_10/1: ${c} RWOJFATHCFYANOQDQONGWOZEQEPSXLAABGIDQYFKTHGGZMCEVBKDVSRAZJRSOOUUFFWRSNYIKATONAXWZHUQKWBJPPNANCTGSMIB', props),
compute('m_11_10/2: ${c} GYFAPXEZNADPUPZTGVFLQWOSUHYPPRXSTKRRTPKWRYOZEBOGPCKKBTHRPFHHOXOFDRMJNXCTIQATNGNKXNSOXHEZXBIUFYZUYMWE', props),
compute('m_11_10/3: ${c} NIBFCKAAONRKPPUEFLHTWSSVSRFHZWAZDWVVJCJSRJGCKDIFNYZVOBKWOZYBEKYDWMLALCFPPODNSSEZMKVNXWQVMKFHUTSLSQCJ', props),
compute('m_11_10/4: ${c} JMZANBRCBEWBGOJNAAYWDMGJOEIDQYEPEDFBBGCCVCRKOUBLYMEJXAJVDSIYBUYLXRFGKFHXGDKUQMVQLNEICLMYGLZLOGTGHONC', props),
compute('m_11_10/5: ${c} RPAICORJDAFPGTFCIINNVTIPQRTUKWFZQAHMLEVSMODRLRAJLGEBEMDUXPJDBTAVWNTYXEZOHDSTXIACINKTVCIXWCURSUEFBDBV', props),
compute('m_11_10/6: ${c} CYDLWZPIOKNGWSCARYQTPYNSCKJPNDQVBYUUCTJEWKDXQUDFDVKVNUISZZWSYCTXWQHSLNLFGRKODUXSIYULGCEMEKFCIWLOZBDT', props),
compute('m_11_10/7: ${c} VCGEUPFWLWXKAQNETJAUSTYTSFTFGZWZYWJZCALKWCONXNUGZDPGXIZXLABNMFRSQSNUITGLGLDIFIEMJCQEHWZTJUQEXANRWANX', props),
compute('m_11_10/8: ${c} RUIATMNOYDOOUTAJRALSTOLPHWMHBDKIFRJIHODCDZRYZAVRQBEZRPEMALLQQOTKAQFLJTHCYXKGLCIIMCLQWDORYIFDUBJIRKPD', props),
compute('m_11_10/9: ${c} CKCKAZLVMGAQXHNJHGMZZFWQKZYVSCKHQUDWOHXEAPPWOGXURXUACGLMCQTIBQZBJIUWIJTFPJXCYIZTOPAYKXERSJTKRMTDAKYD', props),
compute('m_11_10/10: ${c} PCVEZJIJFZQCUYBNXEDZHXWHBVVTSDPPZWBBEAJZLBRLASFQFLWVOMQGRYZSZXUXCVVOAOOOOLEBNCLUQCILISIAABGNJESWTRZO', props),
compute('m_11_10/11: ${c} XLLMMEQAEOOFIKUWZRTGVMQTUWNUWSHNJOQMGOYNZELNKGRBTTNYSDUBUONENMXYRGMLJZFRFFQISGPBWDYTHSSNYTNMSBZPETUE', props),
compute('m_11_10/12: ${c} GASWRIZYJTYEJXNCBUHJKDSERURSIJEROUTRIMYPRMLWTEGUMITOSYTCAOGYMYVRKGQBCZZQSWGICBYKMLXUZVSOIOSQYSGKNXTU', props),
compute('m_11_10/13: ${c} KLCCROCAKHZIVNDQWSOSZIBBPILOVSWYYBPJXQYMPZMPMTMEAEVWPFSVQYEBLTQGMDDVZUGRGWCYQGJVWRNAIGKUHMRBKGSCUSKE', props),
compute('m_11_10/14: ${c} YDFYJTRHVEMQCJSVVFVBGDOYDOSQLLXEAWYRVTBJZDGFLZOEWZGKRKIORQQNERGYXIMUVPUXFSZLYAXTDYKYPVWHSQEWOLGNABVT', props),
compute('m_11_10/15: ${c} ZSTKPBOCXXIGQBOECSUIOVBVRYEGYHSWNWFJSXGAIIUDGZJNBPMSFFPYAQDNOZMPBCXFPBNNXAWWSKKCOVAIXPLSZSYSKSIVWVKE', props)
        ].join('\n');
      }
    