
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_12/1: ${c} LSJTFAGUJFTJVQCINSNDGJJITSSVFOIRHYSTLEFVKKUIWDXIUSHDIHXQGBSFSKCAEOMPKBSTHRPSRQFWVCSGOXKCTWRUYOACTNQB', props),
compute('m_11_12/2: ${c} JABMEQCWBGTRGFQZYHTMMCKPGLJSVLFMDDQBZEAVRXINBLNMDVHUWLKEVINCMEFNVDWWVAYYBTKPBPMQUPOQLTVDUISYBSCWJHRM', props),
compute('m_11_12/3: ${c} RLGBNFFFHQFJLZNVJIEKOHKSPRCTRQNIZNFOWIQDPQFQZLEEEMWGRPRLTTNHAZZLOFKQTQYWEGEOCGGAKZEAWHVATAGKIKXWNYDL', props),
compute('m_11_12/4: ${c} XKCUMHGPNEEKXRFIUNXFYSEIRQVKROKKQPDNTQKHVWIDIVSEBZIDOZNNPSLWYLHASVNEKWOJKCSLTZNSYGARCZAQBGTPRXKSLTVJ', props),
compute('m_11_12/5: ${c} SJIQKRYYJCGGEKKIQDUFMZIUTKXBCGUVYIUJSAFDUQZMIFVCCDIOAXSCYVFSOFPZOQOORYBLSQJUTNHZWHYATDLWOPFPMKFNHXDN', props),
compute('m_11_12/6: ${c} ENDMXHLGKPTBHHRPYCNZUURNFQZUGIHURWKBBLXRJSJYSHBWEBLGIPJQJPSJEIBALPNTOMVFGHKRSWTAZSMISQXTFHTFXOZWZBYH', props),
compute('m_11_12/7: ${c} SRMMTEOUZPDZGXIYEIQZILNIMIDHWSDLXGLLSLIOUZBUKKKBOEYLHDCOIMJPIXXQEDFGSSLJZGUSBHHOSFEZYNVRJNDHOINXJXEH', props),
compute('m_11_12/8: ${c} RDINPDFVXCRUCYKBTFFBXALAPOFDEPYYXAXYXUWWUHRPQWRSSBGTIWSDZYGFQKMHJULIBKLQEGLPTGBGJUVRCNTPMVVCKFGVALEZ', props),
compute('m_11_12/9: ${c} EPXZXEAWCZLXAKYQWWIEFSUEAKORGYVKSVJOUJZVEOUUMBSBENUFTXBGEJSQLGXIMZHXSGWWUXCIELZVXZLONXIPUZQGDUJSDOAT', props),
compute('m_11_12/10: ${c} ZAKQLXNMFNZOJADOJDQXMMBSIMIMYOZFLQHNKCAWAYXAHTCVOCCJNSUKWVQCUFKRPFDUEJKDUASVJXQMRLRHCKEHMHLPWUCICWRL', props),
compute('m_11_12/11: ${c} WFBAIZGNTMBRIRCACWUVQKZIQCOKQQMBINRGTNRJANWYWNYVEGXHRKNVOQHPCZPCHEASJTYZSFCFRXEEEPCZWYHWIDNKLWLRKUFJ', props),
compute('m_11_12/12: ${c} QGVCBWNJOYYNPJSPBTWAXPPSQJWRMTNSLABGPBRSPDKXAAYYTYGJZFVEJMWHOZCIPLVQLBBZATIHFSJAHCJMYFMZYESIMJLFDHFV', props),
compute('m_11_12/13: ${c} AACQZCKXPYSAYEVIHMCHRPHJFSBAIYMCUZQZBIMYRXLTSILFMOGJWOPMIRYPCXRYYZLQHPSKHLZCLCLLQLFFVLWWHKZWSEPZIKTQ', props),
compute('m_11_12/14: ${c} HSEWGGVNYFPNXLYTRWYJVYNFYFOENDRMDHHONJPKJYQQDVLOMGPVQGOULOQBVOHMZRNNXDJULOBTRCAGVKVVPDUTSNXTHMVEMKBN', props),
compute('m_11_12/15: ${c} CBLLKVLVFVRNCJWCAPWNBUPIYRYOUUPGXUEEAXBYSRCSGOTKFZMMXZAULJKJAXFRVRWPNSPTUPSXGMFZTMBIQFRDFZFUOYATHZEW', props)
        ].join('\n');
      }
    