
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_15/1: ${c} CIXLOEDMLYOBDFVIAYTVQNCNMRSSLGIVNDWZBEZQJOMHOKTBCLJOTJOVSPKHMMGXMGBJIPZQURXNTLTAKCIVSFAPRKKPGTQZEHRT', props),
compute('m_11_15/2: ${c} OTSZLKLACEZGKNWBQHXRFYSZLWEQIWAAHGYNTKDPCIZLXDVUWOOFZNSWBVMVFPZXKTELHLNJLHIMKHYFDOTYFSBPSVSOHJXLCMOE', props),
compute('m_11_15/3: ${c} GUQOTCTAPJOBXVMMYEJTHAPIBIYZQURWSAEKOGELMLPIGDHXGUBPAATNVZPKAJDKBEXBVFHMYHOMGGZBCYFXDNCKPNSQZAWKDTTH', props),
compute('m_11_15/4: ${c} VNTMAFLDRZQZRLGRQJSCPLITANAULWRCFXEJWGVJJSYPCDGVNJPNWUXTITSMZWUOQSHHLCYERREFJFCMNWVCCXHBHOCAJOQKFAEF', props),
compute('m_11_15/5: ${c} UVJHSJAMOVYFOJLDATHLBJKCHJHZOXIRSXKJEUWRWJSXLKRXXMYXETXRTMAGHTWFLSANGPDFBLICUDKCUBTYZXGJEFWLVFEXBREF', props),
compute('m_11_15/6: ${c} GIXWUNUFQPLIYQGKJBUPXXIPARJVUOCLYVVCWNFVUBGKMEWAVXMSPNUDENPOOSAEMCWNYYQWERVIPDSGILNVXZPIQFLJYVPHNKLC', props),
compute('m_11_15/7: ${c} XMCCEHAWLTJWZSAPRXWJRTPVTRCMTKAZFQWFLUCBIUMFQEDQZHXNCQAIWNPPFYBTYYKGGBMESRJLIVYUWBWNKGTNBCHVNDEEVOWG', props),
compute('m_11_15/8: ${c} MMLXBRWLSGSUFHMDTDFYFBYUDJKZVLNNQZMJGRQOBMQHZXSGQTOUKMUOHEZYKCXDGTSUDLAOBJFTVPOENWUDOYIUGSMWTUGOHOLA', props),
compute('m_11_15/9: ${c} KOZPYTAWRDRJQDKXIKCKZCNFAEWHNPLYEUSDXHEATJCSLWGWKIDYPQCBZRUWZSHROEWPQZEKWAJUFYHUQLQDKQFZVKDYFJCQNITI', props),
compute('m_11_15/10: ${c} MLHPIEDXGBKPOWTQLSGRFYETDIQAQQVFBQYJDFASVJOUQUGZSWHDNBDNQVRGZQKKWOAWVPBNIOMENUODBGMLSUYISGVYQJYRIZHS', props),
compute('m_11_15/11: ${c} ZYGZCAYSJUSDFYHZMNHDQIWESGZTKMSUWOVZCCIOUKKZXXFHLRJQALLYTMWQLILDULSMNENLAWESQBWMUYULCIHNCSOGLHHODYZE', props),
compute('m_11_15/12: ${c} NWYRGICFGSYIZEVQHNHEPFWEIDFFONYGEUOOZSKVRBCAHYUNOQNCWLSCYLDSCQYCNGPUXPBLLYGAFVCJHPBDUJMLOPKZFXRDRDZS', props),
compute('m_11_15/13: ${c} UCZMVKFRMHTVMHHYSTTFBPIJSAVISBKBBNRZWQONCPWRHWFCAIWLSICSBEGCSLRAMSFFFSNWNBDIRARBHIIUUOBONEZUCRQJECVF', props),
compute('m_11_15/14: ${c} LMFGBYYOABRKJYNUTPGNUCRZVNNYKBXFHVASRNWQGKRQNYTQRJRGCKQAEAWOYVRSHVSQMLUUKPOSONVIJMGEHIUHZMHTCZMXLOMU', props),
compute('m_11_15/15: ${c} YDQHBMIANKTMZMFOOCNNCCHRFZROETQJAEBEOSMJZUZRDORTACPPNVYNVQRZTVHGYRKPEHWTGIORTODNFHGFSBWZRGRNUQPUQHBP', props)
        ].join('\n');
      }
    