
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_20/1: ${c} GGIOODCDYCWMJIDVNYGHVEXMADKZEHYJXXVRLJLBBERGWFJRYOKQOTEEZWPVXOUPPSWBAWJOMYGDFKIHNGWQKFWVJCTTBJBJHIRM', props),
compute('m_11_20/2: ${c} BJCWSXEZMHIRBUBZEIJHKEXRUEWNEWGVITRWPYYWNPQFGPSZASSMZZAITPLFXXAHFVIRBLXOHWDQSPJVWZCVASVZLAGQOZFWVDVM', props),
compute('m_11_20/3: ${c} NDGKOGFCYXDTOKDIGYELTWZSYSMPUEBFSSOPEXOVIKZTYTOXEMLHRVXWADWWYNHDCIWKSHGXVTEMYFVGIMAYHYJRDQIXCWIJYCDM', props),
compute('m_11_20/4: ${c} FGZLKFCUDBYQZENFMJIQTPPSNQEHNFVSITAOTFCRAWMZPILSKARWXYXQOHUDGQKWKHQGXIKPMPGYBNHFGRBNKWAOSZYFZOSGVLMF', props),
compute('m_11_20/5: ${c} XSTSCGNAIVOWMCWQWLNZCEYFJNTJQLVNUNJDGRZNUXNEJPLJBSQASTTRAMFSICNFBUMJAJJGWZEJZUKIPIRNYDEMJTYAHFLFHESA', props),
compute('m_11_20/6: ${c} ERDHFSOACOUVJEFXSMSGYDEVRMJVCQXGGSVORGZAIGWLLKJUFWBXPUAVIVDMYOOEMQXTMJOYVPZYFEWDCFAYQOVDAOPPDJZMHAUZ', props),
compute('m_11_20/7: ${c} DCUKOGXVAIMXMLCAPVSCFIMYUTCHHMBGFABNEPALSLMKIGWETPVXDKYYYIRFOQUHZPCNQFKDDUUWIBDGTNWXGFXRGZGHKFUJZBZP', props),
compute('m_11_20/8: ${c} UTXEQLGWFMWJVHNDDTHOKFHYZBDGWVFELAUXZLJCPJDRMDDPQZPFMGEYWQBLYDDQCXFFBYIVZXEWUPQYHJMWPELANRPKUHDZBCTO', props),
compute('m_11_20/9: ${c} IXBXYEDCOMBOXOKNRXWLUMEDBPQBRQHQSHSVOIBZTYCFMGPNFZCAOWODICATMKXBHVDHTDBWWORPPFOEGNSEZAIEQJRRDLJUFHPJ', props),
compute('m_11_20/10: ${c} ETKARJXVFLYAZNLEYZCGPEHLFHVYOCSRMCEPNVOMGVUVBPYKEIHYZYXSYZBXDHQDSOXFGQPQLUSGVDWGEJLKLYPCGMDYBJPJIXFG', props),
compute('m_11_20/11: ${c} DGGWSJWSDIQGUPRQMYARQHQVWUJQCPHGLYGLROLSSGIVIJIGYKLSYPGPKHWEPLUVSDRSAMEDWFLVETCTBHJPDKSKWQVICENWKGDR', props),
compute('m_11_20/12: ${c} GFFPHCYTESZFMJEDHYGBBUOOGOQDCFVYZEWGRLIPAFJOMOWHSMYSHMYLGTCGECFHNQKGKCJBRDQFMDLAZQNSNPJUMXEQBVRRJFOR', props),
compute('m_11_20/13: ${c} MXMBIPTJUPUMQOWHOSAKQSRBQBOIZCCCTMIIJGZFVNTOFQKFLAASCKJLTMKXVUNTDELZNRYHMJEHYJJYAUUVUFCEPKDUPQIXFUHF', props),
compute('m_11_20/14: ${c} XWJEQUZCGIOQLDGPIUCZZYPGZEFOXSSBNZOCMFFGTHSRJSJWJJGXHHXAPVCNHJWNAPXNCMDXELSOEMJRYEIDXGFFANOXTOIFRWRD', props),
compute('m_11_20/15: ${c} RKSGJGIOFWPUITWOKQAWQRXPACTMXEQAOBDBAQOUJDIAHVXUDILNXOLWKTKEWSWAVWXTYTCEKPOHPVLNSQGZCVIINDMCHXWSKRNC', props)
        ].join('\n');
      }
    