
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_7/1: ${c} UXSUIXAKYFUTPXINHGAMICOZMRBEJDFJNOHNJQNNDCDTSBCPJVFMHQQSWJYDTWELXUKJGBWSSCQERDSRLYBIYAUFIWNJRSZMLYGG', props),
compute('m_11_7/2: ${c} FZVHJQVYWANCQMCNXZLTGNQLZRQVGNEUHUJFMYCLAATNJAQZJNMLZHABKVKQPYVQHKSSTEUWLBQDGILJMSOWXNEVQPETNPYZRXOJ', props),
compute('m_11_7/3: ${c} PCXWGICRLQODCWHITDPEAJZZHDODDTYFVZGQEPKJJCIHAILIGNIVWZIMOJNSAKISVDACPGAXPMEJBSOSQALNXNNFZYPITVYVSPKV', props),
compute('m_11_7/4: ${c} BZPWOLGAROVTQWFRZCVSECFUITLTUCAGWMMHOYUCQGXKCSIYYBVLVNXMBOEYXXXDTTIYJUNVQEGCKNJLKYWINEGIPQUTGLVTLPRQ', props),
compute('m_11_7/5: ${c} VURAECTLFIYGUVAAORTGLWDCZRTTNVZXGICFOJVLVNKWXAZWWSUQMPXSEWEGSIJHORCNPRMUJMJPUSTYIXKZZQEKSKBGPCCDOFWV', props),
compute('m_11_7/6: ${c} QZWZQRWNCOABIVLCTKYVKLTNVNSRGABCAARWREXEOUIRHWGGYZLRWHCLHFIRUIXHLWTIZBXWWGCIZITRXZVYADZEKOTOWAPEZIOP', props),
compute('m_11_7/7: ${c} OUAKAUHHUOOYOJMVPCIKPMDCTWCMPEPOBSODQVEYEJXNSITIRQHKRPDFKWIPLSIZXXXGSFGYRBZQFMEFKHSMOMOMPDHUERVFBRXX', props),
compute('m_11_7/8: ${c} CINSVBIPLLQHYMPINHGKRWJGCYJPYXOKNLFLIJHBWHMXQUQKEOLAODIKMQDULMNJOMCQXPCFKAYXECIUIZEUIBKFNUWWXSAOSKWZ', props),
compute('m_11_7/9: ${c} VIOFHIYJNHCRSOCRDZFADZYKVTIDKCFAVHWJXLBMPQFPLICMSUMXIBOTBGNDDYNZUNMKEDDXPFSPVJDQHOONVBEMTLXKOCKPRJSX', props),
compute('m_11_7/10: ${c} QHTXIZNPRWPPPRCEYWJUPSWJSRTWIIEBNNIDXZZRKOYPGBWPIXCAUMMHXZWLHIBWZVANNNSOMXDMMUAUCFWCLCBSCDUUFDMTZAOW', props),
compute('m_11_7/11: ${c} HTZYQSSOWMANGHSXKSUAXXMXAUPIVNVNQJKQTWZCOPSHMFFXLUWLXJVDJOFRMOMGGZDCTZTAGHPJUMSWQVSDOWKAMDQPQGIBGMYD', props),
compute('m_11_7/12: ${c} SJZXEEXBUGXJMYTUSNXRUXLXNMFSORFZGZWRRFYVHOXZCXGOGTZEMDPLUJAARRJLIKTFIJSMNFDBNOZSDXXXWJYVJXAHQRPUTKBQ', props),
compute('m_11_7/13: ${c} NDEMJWHKKJDQJOLMGMYSIZRDQADWOZHDDKCBHVCNOBOGYAWEMYNYGZBRMARZKDJUTVQEYJRXUFREXJTJULDOSDFOQZBQTHMJRLLG', props),
compute('m_11_7/14: ${c} AENLOZAFMHOGDNSWBMCEYTAYWARYKXEPWFQBUSSRXFMSZWUPVJHFTNBIMWPJISVEIXTVNXHCCMOHWUZPOTTIGRYLPQSRQRCCLICX', props),
compute('m_11_7/15: ${c} YRPEKZDLMXGXOZDKRBYYBZBPURNDHBCPTWZKZLZGLFHHDUPXLTHFRFPIGZEDMJFMLNVRGSJCXOHDWTTSMDLBRKNGAAJQYFJIZQTJ', props)
        ].join('\n');
      }
    