
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_13/1: ${c} SVDDAGVEIMQKJVDJFVFEKKRQTMSTSMVTAAGDFNNBVPISTOEUTTBPPKODVOHXHSMDHNMHZMFHRSVTEKAJBMTDDGWBUUNWDJEDYZIZ', props),
compute('m_11_13/2: ${c} FQXILMPMSMGXKLCCIEDSCCYELAFISSOMKPKWOZTFMJJYALZMEQNKETFQIJFKSAHMCRYYCEJWDSHDTFAQWQOEBMFZRFYMXVNCVDYR', props),
compute('m_11_13/3: ${c} BUPUMKUOPUXCJDLWYDGIAHVAINKYUJKCCAVBWAUFFXVRENNLQQYAVZHCEKGIINKSBUONEXHQZQSCBRJKSHVFSLGOBHJRGULSVTVA', props),
compute('m_11_13/4: ${c} OCCLSOMAJREFWCPRAHFFJWMTUMEIIOCLDPSVOMTBTIIBDWVROOCNTCMKKOFWADBIKKCHXWPGGHPMBNXTADTTCUKEPHXMEEZJQROC', props),
compute('m_11_13/5: ${c} DCSTWRRRWOBUHKNKACARSCLZKLHLCEDNXLPXCAZKKOUWYXLXLZTQLZFJYKSSWLMUHNTXNHWTRIEMGYVBPYHNIBZFEUVSKPGMQGWJ', props),
compute('m_11_13/6: ${c} YZQAMMHMAAHSYBDTEIASFECVJPXDPTPWMMTNFTKXLTSXDTUBFJKRDBCJQXPNSDTSOOWADCOLLWMXXLBGHCRGAZMYFKMUCZMXGQIH', props),
compute('m_11_13/7: ${c} XEPTRLUFQLDFMFPHUCHAXJYREMLSIEFRPQABHBUICTNWTWGFKLIBTUAWGKKXHMCIMJFVMWXTQMJCTJJDXEITQIFOKSVIXZTOFDRS', props),
compute('m_11_13/8: ${c} NSXBDUKUFBWHIRTBAIXTUKDKHCPFHWMGPUZURYNLDMCXQJXBWQGMLTNFGGEIDWPLNLXHDFRMHBDEKKTRNPXYXLZLFBCOYQVCKFLP', props),
compute('m_11_13/9: ${c} WFDTKQCHVVEWPUDHMLWAQRVCDANRJDGJBLKXDRFUQUENDIDKBWYOBXRBTREBMWMLIVAPAOVSAATXSZMZWSFJVPXCSFMIWSSTLHYY', props),
compute('m_11_13/10: ${c} BKFUKABYSUTCYYWFNIRXXOSGIVHJNIMVJRCIWLOXVPSDLRQWLQAPXBRVSVYFPNABAPWTXXOSFSKYEGBTWUGUWUEILJYKIFQGELQD', props),
compute('m_11_13/11: ${c} UVSPNUSQPJAMEGKCYGRQPRCCYRLNDWYNMVVVZMNDJCGGKNQYGZHUIOVNHQQJFMXWCHNOBOWZKWGORYECWLJPKATUGHERAZTAYAJM', props),
compute('m_11_13/12: ${c} HXSUKGLGGHSMGDCWGHXRSXPYRUZKFFYGMDBJBWDXLGFMBWMSMMPQXILYYGCXYIKXITKLJNPPDDMKZVMCMAGXGMVVGOLDUIRQVHAP', props),
compute('m_11_13/13: ${c} ZMOSWAJWJUQQETGRDWUECXACXNDPAOCVWFQDRWSPOEXSMBILEEHPSOMEJRNKGMIKDWFBPFQNEBCNNAIDVMSMZLQCRNPQNJACWIFS', props),
compute('m_11_13/14: ${c} FTMTMPSGJSMPEBKDTDROMQFTULUOVXFCQUPSKRZQMBJCIQHBBJVADSVLPWVOFIYATYXKJRTXYWBQZNRGBXNTMKGVCAHWJXIFXXEV', props),
compute('m_11_13/15: ${c} FUVRUFORQYGLGNRXHRIEHOWHRDSVOBHOSRAKCCHIWPOQGYXONATRAWHHSBBWVZHMGFHLYQHYIHHJGZIACTIFRENBTCRQJGEHANDD', props)
        ].join('\n');
      }
    