
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_18/1: ${c} GWJSAXRIIDHSCRQUEDBGSPMTNTQFSHQBACJRRRMMRQCWCRGVHFBOMYDISJEAFVSLNGQYDPVAACMNKNAIMNHGIUOBHFMWHRFAHZBK', props),
compute('m_11_18/2: ${c} NXANOYTMISWLRWPMIRLRCSHHCDHDHJZQLQPIGETZNIQHEIKVVMKANIRWEIOLPQXORMSQSHRUJOMGUZWDEOIUYHXNRPFYLGPMVGOC', props),
compute('m_11_18/3: ${c} PHFPNSMRLRRUEUGZZHITMIKODEKFUOASRHUEBEDWCSZKAVBEYRMFUYQJROXFIVSJZDWKOFWTSVPDLBXMBRUEHHGKCQPHFJVDBIEP', props),
compute('m_11_18/4: ${c} OBQSJKWTXNPHKJYJFYSSZGWCSQQKQNWTMCMFBRVFMJIVZYSEUCXDKFMIPWBCSKQNPKRLHHTWHVPAQPCCLJYXNVDRQUZMJJXZUZMH', props),
compute('m_11_18/5: ${c} VMXITJMNXYPMCFXULSLYWUUTUUMQMDJDKAOHPBVPQFNOGQCCGSYDCTZRDWPEBPNKOBWXTXUBHYHUAUWTFVXNHEPIDIMAGGWFHDIV', props),
compute('m_11_18/6: ${c} WGYVHNDRCUYPLFKQFPDMHBUSXBCCOFGYBTHVUNROASMKXYABYGTFPIPAGFWPXRVKNMDAYKYKCEOWOYIDMBDRWEHGDKZXTYWMKTDO', props),
compute('m_11_18/7: ${c} RLOIWWKCNXFEZTAESCIAGOLBHEOZSDJOZKLVOYISSVBGTNEHNFSLGFLKJTPUMLTDYVBHBPXBKTKFYPCOLTIFHVDFRAVZEQJRGUJE', props),
compute('m_11_18/8: ${c} NBKWEGXTPDXODPHYGVFZHSYDQIJYPEBZBXSVDOXJLZXDCHSHZXFJZVAMCVSDKHFTNOLULXRFHORORFRFRKXBSREOIFGVUTEQDNYQ', props),
compute('m_11_18/9: ${c} ZOTJUEOUXPCBDOODLTVEOMQOQHDRFWSANUOAFXTKHNGFFCJSQXDTRFQPRSBSFNKIBOPHQUZXSDQQYLFAWUEKGPEMCMVICYLUENBK', props),
compute('m_11_18/10: ${c} SSWYIEAMPDPBGJTHKCDNBQIUANCNKTPSRKKNHRWYEJMSLLXFVOFXJPRLOFSUYPIEJIEPGIQOYOKZSFJASLTSDRMWBIGZSXQBMGTT', props),
compute('m_11_18/11: ${c} OLERQFLBYYOIYEQXUJXLNBQXERJYDSDUFRXHDIFYJEUTCYDLDCQRTNCMCUACUIIJSUIKWYSQBZIKBKTYMSVJHQKKLXRHFYLYCUUV', props),
compute('m_11_18/12: ${c} OPBHQNKKQPERNVOSKXCZUWLQAIIWHGFOLICVIBVXRZHOFAFGCUKSDCXUNWBQZTWWEYXKJJJBZCTCKPOOTGQFHJDUSIBYCUVBFSGF', props),
compute('m_11_18/13: ${c} KMHHLMGVUMYJJJUQIMERMWICYVMNBLKWVCZNIPULLIKSMKLBWHQZPRMYANUCSBDLEBHOXPZPTEGUPBDNBVXJENVVKFZJXNMJABSE', props),
compute('m_11_18/14: ${c} HPMHAGAETQEHZLBYVZMUBMLRHSMUGKTNEFPTVYSHORUYKJPKFJEZFQZEKIEMHHUCYLIWAEMVXWOVOSEHKNKJOOQBGDFZIGJXPINC', props),
compute('m_11_18/15: ${c} LDEZVHGAYHPHKVBIWJTAPRTZPRNBGAAONKDIEQJSWLZVZBKSCWFCFVWAJGOUFDJVSINPLQKFCCWKIPSMOLSDGGEZGJELSDEBCAWJ', props)
        ].join('\n');
      }
    