
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_2/1: ${c} KYYVKWSVPNUSCNLXOTYTLYSIDOPWGGQRKAXBDRMIPSWOBNGGUBQRDZFMKKNVQMUHDAKOXCIUIKOOBFZXNEGNJRJCUAPUWMVRDUOR', props),
compute('m_11_2/2: ${c} RGBPVTIRRQMNWNZOJYJQNYZRKYLCUXIZYAPUPTUOHVEZCKRRDMRVKYJGSMQMIOLNRILANTKYODCTEMRFNBZJNSJULOKZKEUIECBU', props),
compute('m_11_2/3: ${c} QVCTNPHPIEKDSADPMVJHVAIZAHEYGULIYMYYILNBRBKHNWCFOOFYLJHSOZMREPGMEHGBVYHBYGOYOBVVWLEJUZOEYZSCSXPGHRDU', props),
compute('m_11_2/4: ${c} XXSPSUFCKKOXSEYLIZUBHQJQONLKXTUXSKPQXYPDOJXPFXUZLMRSLPZMFQFDJDWICGACTHHDXQZQCDXMIHYLZAWMKCUOCWXZFKPW', props),
compute('m_11_2/5: ${c} CLRLAJDOALFICJUICUYDEOMFSVZQAHTNOBHWYGKHGPVNISXCYOESIXKHGIFEHLJMFWPJHBDOQRHDHTLLZNPUCIJJAYBGVWFQTHKP', props),
compute('m_11_2/6: ${c} DMRDTJHKKYGAXQLHTSXTYMGDNNQUQAIQMISXBUDRTBQPNBFKURAADEBLAGPQSGGJCPHCFTLDZFZXGHJPSQBAVGXHRANNSLXSEQNZ', props),
compute('m_11_2/7: ${c} PASBKTMMQCZUFAAJKZQTAIMBUGLAMCFEPANVOWQGORWSSGDXNRHUCOSREXRTNIWBJTCDAFJAXRSIRIHQWYZMCEJJUHCHQZVWVQIK', props),
compute('m_11_2/8: ${c} AFILGPYPLNURQIOHSQICFXQVHANOTYUANGINJYBXXBGOOECBZFHXZABVYIZOXUVGBJDMQDDEICTNTEDZSSYUDYTAFWZVXRCEGERP', props),
compute('m_11_2/9: ${c} WCFMLLLRPXPTFPVXQWEZUBTMRUWONKIZBWOWAWXSTCJJGAEJBESEYYIWQIANMBBAYCWUCTATXRLJKCMIHCXPLCSCKHKQEDICJZOV', props),
compute('m_11_2/10: ${c} SBCRBJIKJICDTDOHOBFWSCFSJNTFBLQJCTGARAXCOCYCPWQWBNIFTOZASICTHYQUHYDPGHMNLSYIFOVZIGSKUZSWBUFWUIZGYHRQ', props),
compute('m_11_2/11: ${c} XZJNRSORIAGOWOXPJSLFOMTQPUFWTWFAPXOEHMVEJCNTXIPSPWRHUXFXDYCIIUHIYIXJBXUKWMPGBWHVSXJHZFHOZQHNCTDUFGHN', props),
compute('m_11_2/12: ${c} WBSGVBWFUTRWINFUCRLBUAPVGIBWAZGJJBZGAQGYFWYCMXBARAOSYZCQUBWNLPLORTGMLAWNSLYTEIBDBHFEOOVTHXVSJWTVUKTS', props),
compute('m_11_2/13: ${c} NUQTRIFHEGKHLPJMLEMAVQUEAXHVXSRNVIQVVPKLKOXSWLRQQHGPHRUUHADRFEQMOHGJMRGCDFCJGZBAEVGMVCGTXNJQOMOEDCID', props),
compute('m_11_2/14: ${c} ACKWTNZYYBQHRLUWGAREUXMWAHZIKEHMWYRTRMPUSAYKOYXCMNPVJDYDXSBXFUDHNGJJUTTMDYHLCVQNYYFXNBCHRMIOOOVTIISB', props),
compute('m_11_2/15: ${c} EMGYSFKPUDSFRXWOGIYJRNFNJXVKTSEPZPPBUCTMRXKMRGOSLLVGNOKDABKEVOXVFOHNDWVTENOWGYGXTZPNFCXZGJLTKOZNRITI', props)
        ].join('\n');
      }
    