
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_11_8/1: ${c} AEOBXYYPTMWDJQAQLRMVAJOSFSXEOBGUXIVXPPJLNVGCZSUWGZFTTJJPOMOEIVQVHGZBCALGQJFFVKXRXRTCOSGHOPLYFGCBVUKS', props),
compute('m_11_8/2: ${c} EMFXRMSMKFTMXHZIGRRNNKYSJZFYVCONCQZBIHRSFWEPVMLZRXXKKYLYSXHUNBVXVERHNRROHRRPGPRVMRBKZNDWPTFRZGWIZQWO', props),
compute('m_11_8/3: ${c} ZVRNUNMGIVEGZJBFYAMEWCPKQSKDYSGEXCGMLSYAXFGJEXVYURFEBTGDIRJHRJTIJIKDFOZBYNNYJDVQTJQXLNZXJGULLMJJFGYW', props),
compute('m_11_8/4: ${c} OJQNJEYUWPCSVPTLRMFYVFRWLTQSUBPKBGYNCBAAUNUFWOKETNJIXFCYSMRZXUHRQXSNNCXXEFQWURAOQKDGEXMSVXWRICTMIUCP', props),
compute('m_11_8/5: ${c} SNBZDCRLRXPBJZLYRXYWTUDZWUZETQYSVGISDXOARWEFQFPMMJMIAWWVSONPJZIGBHRRFOXIGXFBXIFABPQRIRSQQSPATCPRYPVI', props),
compute('m_11_8/6: ${c} OUESSUZSBPTTICFVMZNEYHJXHOGACFHUBQYNOMIEUXZQULKYRFFRJBEBTVOTMKEHVXPLPQTJFVENQLCWZOYGRNEYSHKEZMNNLKGZ', props),
compute('m_11_8/7: ${c} XPDJMEFAVKAROEAPTBMAUOECINNGZSWGQCSQNJOSSRKUCNQHXMILXUJKNUTJOMYIWWVIGRVXETYCCBMUUKQSUJAJQIEFIWZASIUR', props),
compute('m_11_8/8: ${c} GJYNNPQPYUSKQPBKRIHVRLLAVZXBBUBEOABYZKYPCAASAVGVKOZMSCDAXACWVILTEFVHGGVYPOQHMBCTGEDISGYQNBDLWHBGXFMF', props),
compute('m_11_8/9: ${c} ULHLUXCOQTBNXQLZZREUCCZRYKZPAPATSDOLIXSKUMMKBQXHWIECVNCATENAFSTTPQPCBIPWVVQNPWFRESEFMDGNURSQMDMLQLVB', props),
compute('m_11_8/10: ${c} HXESOYZNSQMNSIHQJRTALUJOWHLMZSHSUSLXZLAFLOPNFZEJMOXCLSOTQYSPJBRFUXLDCGAXUOKMTYWJEIXWGYJGZATMYSHHTXGU', props),
compute('m_11_8/11: ${c} KYOAYECMBZZILYGMVOCIFWHKIDSFWNKYLKAYOQPEKMZSCKOAZRJOSYNXAXBMVHQGTBJCLHWVZOOUNCUFBHUBNTXEWTIMCNGDKSES', props),
compute('m_11_8/12: ${c} FUPAWGNGZXKVLCSORLYBPYCUQDXWQGQUIUNZCEQLHNSQYNYMKHKMODVHUGSOOWIEUVQGGJJQIKGULVNSCTAKVHJAOKEDTXEKVOFC', props),
compute('m_11_8/13: ${c} KMIFUOPWDUKUBEBRWFICLQRLMJYALTPGCDZAUDTRZXVDDMITUYCSGYQQRQSNANOPXFXHLNGDTREWTPAWVDWFGHVFTNAIPSIIFVXO', props),
compute('m_11_8/14: ${c} LIHGZJASYPGZVMXFRMZQZDLFJKBXICAFTYKUFAVWDRWRLLPUIDSBKFZGSMIEPPRPRUVRGJHKVPXCPLWNMPKJVZFAVODMRHRYTGML', props),
compute('m_11_8/15: ${c} BTSDFQQRAEUPTHSSHAGZCXNNFVYSTFYQONPIBNRQYAXNSFJSJZLLCJPHLUXDJWWQPLILNIOJTTLZTVTYXMZLTMAHEMVJKXNYJLLJ', props)
        ].join('\n');
      }
    