
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_16/1: ${c} XAAMSPPSBISXSQZYCITLOPDUMKYLWFJEZCXVOBWQJNTCUGQJARTXAKLSJUVDDALRLMOCUZISKHWRCSVEEJAESZNVOYKAVYIHELWC', props),
compute('m_12_16/2: ${c} MJPLQWLDRDOEIHBTDNGLMNXFVTAOJDKYWIRUUNZTQEMXYYZOVQQHAIIWXOJELKRAJFNBBBQJZFDZUZIQFRBVAEOPUVSVVOVMUFZL', props),
compute('m_12_16/3: ${c} PDLKRSPLFFNYBLGQJCNCAFWNGLOGYTYPTWSFZHRADGUQNCQZRNDDYNZWCQTJKDDSXBMYPHWEOUKXFZSJTBHNJYGIDKEGITNWNIMH', props),
compute('m_12_16/4: ${c} IGXZMPJVBDKJIULZZCNBREBTFFWCIDENFPKWFSNIWNUTKGISKAFUEWCIVOVRWTBCWNCQUAJPFVPTMZCEMHTMNINRTOBCAWHVUQWN', props),
compute('m_12_16/5: ${c} LSGLEQIHFTFSFHHMHGUJUGJXASWJWQMUHDEUYUBLGRPKKTIUNOTIRAXZNFUQADPWXOBMNYDRMOFZDUZQTFDBPXOVMGBWWJNRITNN', props),
compute('m_12_16/6: ${c} DSPAGNDSJDBHKAGXHKQMZIKSHISDPUFMGHBLPJCSRCIAQOGWVFGNTAHEHOSBQWLZVOLZSIPDSQXEIXTPHMGJVIVOAURZQXKSOKOR', props),
compute('m_12_16/7: ${c} QZECEESQSQZISDAPSXDNFDGJSDADZXISOIYZMKHIFSTERITFHLIVGVEKFMXFBBIANWBONTTNVAPGHUXNTFJEUUPZXZUTGVTSCAVY', props),
compute('m_12_16/8: ${c} EJHAQXCYELYTPMINKDLDERITBHZMJQDHOWRNUQQNRVERLRFEGOHXYVICHYJVHPMPSBVKRIHONUMIRVETUZTHDWXEYWNGHTXLQDAZ', props),
compute('m_12_16/9: ${c} NUTFNOGOFJUHWASYZHCPBVPOTRUZYVFDFFFDFASGZBJDNDGJROCFVCGRALMEZSPLKJWIEBLTVVIELJLGKFZGSBKZIYOIALLOTSHU', props),
compute('m_12_16/10: ${c} VPZQLYPYPKAJSFCJSUVXGNTMIJVNFMYUHVJWHLSZIBTIFGXQUWUCQHREBKSDIOIEQLPSGULUSSFSMFWAPSECQSMKXCYAVJSODFXV', props),
compute('m_12_16/11: ${c} QDJOELMFULGQNVXSKUFDQZNUVXGPYOAJOFJRYUJTUCADJIVURLPFKAIWGBROSYPIXWKLEHKNXFKIDUSEOYZCCCQJPLGTDGIUKYSQ', props),
compute('m_12_16/12: ${c} MARBSXPAEXRKYBJHYOQNTMMVBGZHWCUGYXKVQZSSJEJAXHUNCGIQYFLPACZLLEEOMTXLYNTKVMXAUTLQIDUMLXKNCZEGICZEADPM', props),
compute('m_12_16/13: ${c} QQHQVJOFCSJRAFCAMQPTYIDSHVBQNYDPSWWSPZZVPOEDEJRDYNUBCPWQLSVBMVLOFPGVKSXLBHKUCNPAMXAQQZLQBGQQHDUNIJLH', props),
compute('m_12_16/14: ${c} WLQJBQLZPAXNJGXUCLRTXOSJHYOBLKTGFZKOQCSPQOGBAKAXJSRGCJADCDNAATFTWDHHPBXIIKKTIDEHNWFNTWUFFUGASNYMFOKI', props),
compute('m_12_16/15: ${c} QTMIBDXWHBOCWJRZYJXCXIXQJHJIIEMSPZDTFXYVGOXPUJHOIWYBHQGEBBDOPMVWGPNPIEETHREHJQXTSHNTIWOWXSGHABSMMYRE', props)
        ].join('\n');
      }
    