
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_20/1: ${c} NUNWEPGGZTAHMIQVSDVMCRFRSBWBXOTRBBSISJAANRANRRVICAAVQWVLYIKPKZLFFEPFHTPDCDZYJTXITWSZPSSLTFEZTBSLYKRM', props),
compute('m_12_20/2: ${c} HJMQYDMJTQGPEKKHWJUROAWESVTGFFNTTZCNAHLDCGDRZFMRPYTLZMCHXJLZFTQEDIQLUBMPPFHNCHFEMRTTWWJMWRLZBCZFJPCD', props),
compute('m_12_20/3: ${c} BQJOQQTPSNIITHGRJHYASDNEYSTNGXVUHHTRDVHZJWGGXXHWBEUZZMHZMBSALJEAUOKBRWZDSNIADWRVIGDPEZTJIGYGJKAWTFWA', props),
compute('m_12_20/4: ${c} EJBUVASKMXSQPMPDJFVMBELTHVZJROCXGPWYXMXBNNBCAJVCXZIBBLGARTRPVSVKEOKVYCCJFPQKGCNVMLTXREUDKFEIDHSZEVSJ', props),
compute('m_12_20/5: ${c} MRVLDEHPACVIBAKDNPMOQYLRTOIREOAOECMJRROQONXBXFPTKWCFEIDZJABYOXNIPOEZMACGWQYABCYXEURTBNQFAGPYTMIRAPVF', props),
compute('m_12_20/6: ${c} MAUWLZRSUFRKWRGUSJZMSTTGIPBSPSHOSNTWARHSEVPVHTOLLEFKISXHKQIXKLTIYMLZORUQORIUZQTEIEYUUDAQDINJVUOCFIBC', props),
compute('m_12_20/7: ${c} JYXTLLHOWHANGTFLSYTFBQMMJBEFRZEUNGMFKKXSVJYZFHTGIZUHOLUAQSAQZCJYATFLFOFZJOPJQTFPQRRZHIPVOSHVJZXZKTAX', props),
compute('m_12_20/8: ${c} VBHKRGYRFHZIMTTMOXNHPFNYFPHKBHYQWHXXFIIYMBHKIESIUTRAQIATCLQKBYIUBHBDCIZYHBLXFBRHQGNIQGVEGZBGUJNPFAIP', props),
compute('m_12_20/9: ${c} BURNBUWLXXMHRLZVSOZZQOVYEESCHEKLRVRLBGNDWBTTHQQUPUJJCSOJWGFXYJWIRSOTAKXVSULBSYQNDHLRVTGIJXABUSUOXIRR', props),
compute('m_12_20/10: ${c} DBPTMUZMQTIFUZEYGXMHXSXCGHXIDHAFJKRPYEUMYTZMSGATHURPMVGXFWGFRBJRCGQJUCHJFVVKTFFOIPYMTHGOPFAGTMINWTAF', props),
compute('m_12_20/11: ${c} WPPCKBLQICHQOHEGTCXBLVXJGDFOUCHGBFRUJJANQMAZKGOELWCOIMVDUJGKCGYTTYFBLSHCXCRUFQOZLNWVCYNOFJAUASFWAFWK', props),
compute('m_12_20/12: ${c} OTFJQLFHRJWNHQBNYGCHQAQLBEAKWJOBGYFYZDHZQPDUDUSJCFHWKLEDXKUVGHYFZJYDRVROCHCSEZNOJAFXFJECXVKTGBAEDJTS', props),
compute('m_12_20/13: ${c} XTSWRUZZBFQNWJMWXMOFSHTDPSEMPRHOFDQNJQRQEJTOVXGZVROVKEGROQFFOLIQRHADIGWJBIQLFLUJXFOCEVSWUPJDPCNFPNAX', props),
compute('m_12_20/14: ${c} ARIDDQLDYUTAXUVMEQVLBUDEJBAKASIAGYWICCEUYVRPZLLXNFIJYFGAZHMZAEBXUVQYNWEKMSFMCFKOIMUVOJFWBEMCNIGFPCED', props),
compute('m_12_20/15: ${c} UYIAOBXZRPIHRRQKUXWABDWAEIJPNCOITVXPDWBWWPVACMLTKEUGBJODXZVXXDNXLMCWUSIBZTNTRDTYUFDPLTDTAORNQJQIHBAK', props)
        ].join('\n');
      }
    