
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_1/1: ${c} GKTKSDUVZXLTXHFARNIIBRCFGZSYYKHTTGCKLVMLZYUUNKREDDYKCBIYHFQJUTYPBDBVQINSZVSHPPSDFVQCBEJLIWLIMZZTDESI', props),
compute('m_12_1/2: ${c} OYBEHMEFSZMGHGHBNZHKMQJFRGQCGLOSMLSJPBUWXTISEEJBGIWDXQYQTFMKFVZHMWFGLWTIQMFWVDPDNXSHUHABBRRFLCUWFREN', props),
compute('m_12_1/3: ${c} JRPVFDBJUCJZJDINYKFMZWUPTYETWUKXVZYBTYJGJJWJTNNSNQDYLXPBLHBDPMWUWQNLYKKJBUUPUFRSOKULCHZMLZMDVTPXGBBX', props),
compute('m_12_1/4: ${c} OVEKGLOTROWQUZFMTQGAODXBZZHOXUIUKFLMJRRWLVBFFSDQWAWZUHUFZGHUFWQTVDJTKYQNTAGSWCACIXFVHJSCUQCYBGNNQOBU', props),
compute('m_12_1/5: ${c} LPATSAZKOOTIITIANCOTSMSOYELVJXVRUVHUXFXZKOZMROPETDMJOQXMIXHNCZZBURIZBHVIHQXVJIEMBDZVUTEKXBVUKYRMVTCL', props),
compute('m_12_1/6: ${c} TKHSKOXJIJIDJUJVFDHMIIZKGSMKVJIZWWUAWDXPRPCVMGNTBORFEFBXSWFPYPDNCBDQBWEGTDLPYXMFAZSAMGAMXIIYVBDTDCPC', props),
compute('m_12_1/7: ${c} SGLFMKMYQYIQEFLQPHMSUURJGFUWAYORIVCZRCGMUCCPBFNAENAXSVQUAOIZCWGQFINIVFZKUFZCZODVPXAIRUQSVLVVFMKUKIYG', props),
compute('m_12_1/8: ${c} YQXSSIBGPDYNGTYLSZLPOCEEVGCNOKUHSXVSODLJXHFVVJVBYODHJYWLZQOEVWMLCWSUBYYCSFCIBWEUXIJKEDXWWQGARDUFFNXU', props),
compute('m_12_1/9: ${c} SLXRLOBXBLBPBDCVOODBNAOUBBVJFIAKHPIQHXOYMEKRRFCVTOBXGLZUKRRTLWXOHSZRPLDTCOFEQOSLMVJKUBJKLGALZIDNUAOI', props),
compute('m_12_1/10: ${c} URXRBRKWEXVJKXEQROUNNDBGMAGOLYXVQYCPHNBDDRPACFJOKBEOLPANLNGWWXBXOAQZYXBYNOUIZDWSBBQHOWMZZDPTTPRYNPNM', props),
compute('m_12_1/11: ${c} KHAHBVIHWKJGBUUVXRUKAMSVJKOUUPKHIDSAOQSKASMRCSMJQKAIIBTUKTKACJQKGTZRLVMSBJCJFXIRSYOPRHVCYZRZHNADAPSD', props),
compute('m_12_1/12: ${c} GVKUIWMGAUHNFNPVBPNKCRLJQGUQCQDQJGFWMLSDTXNNJUYKTHTMTENCLXMXRSCRSCSWLAFMQNFHJLIZNIPTSTKHLDVTGEBJARRD', props),
compute('m_12_1/13: ${c} DDPQHRJRQQPQKCWGXGPIAUSIXOUZZIGFLSZFVDQSYEHECQJIECFTVPGJPDPXVMPAGTVWJSFHFLGJUXBIZTOOXYYLVPZOWBOKGIHV', props),
compute('m_12_1/14: ${c} EGGFQFCDRQYTVIDYGTUIYBVCQHFKOOUHBDBZKKQKPRZWQJUNUBMWSQSEROXMKEPZNDNNGIJWDSWQLNHIWEFXFRTJYPGUVSULCHAE', props),
compute('m_12_1/15: ${c} FXQHYJIWNOHVBURBLGQWIOZRZPLEPJSHKGNNQHJMNVULWICJRDLOEDIKDQPRTXEBQELNZCORPCUMUIBTKQRQGTQFMLPHBPCNYOGX', props)
        ].join('\n');
      }
    