
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_2/1: ${c} ZFTBAPLKRWMSPZNSRENPJWMXXGZTWAGXDQUSEHOSQPHXQCCDUKHHBKRHDIUZPVBSKKWZLNRQUVKAIXDLDCWMPSKIQYOWFJVDAKGE', props),
compute('m_12_2/2: ${c} VNUQKGVFDCHRNKNFIJAVHGNAVOQNYHZSGKTSRCKOZJDFRTYNASPBSCTEYZVFTKSSVRFPDMJOJCUHCREYBXMDISVCSGNNLYKSXNDQ', props),
compute('m_12_2/3: ${c} MYHKDWEKJCBPWQLQNCAOIPZOVSFVQMNGDUOIEGJNKZGVVZHQRJWOMIIXLNIPAWPZYCOCTNXBXAMQSXJKIEBYSZXWLFXNCXOHKILT', props),
compute('m_12_2/4: ${c} IADWDKMRLCCLLPFSPSOGCXJULESPNHKCCTAICISOPBNLFCCERCDZFRWUIAEBVXZQMDKDVTHTQFOWMCGKNXDGXGVQAGOLXGMVWVIX', props),
compute('m_12_2/5: ${c} VOGKVNAYSOUNUEHEQYLIMIQKPDUCDAQIGSOEXSPBFPDCIWQTDQHXHHEMJQTQZSAFCHIDOPWCYLARIWBWBLPSFMZBLTSQYGBPWWOB', props),
compute('m_12_2/6: ${c} DLWWCITZAAQCKPWSXFGWKSPOLBLRDCVWSMCRXBPUMVHENHRLIXOHMAMHAOIKQQYRLBHNBPHTGQOOHWISAUPPSZHSKAYTPDAEMJVT', props),
compute('m_12_2/7: ${c} LDBSFWHHJYLARFQVIOMZGXUPAGFZXLOIYUYCPUUDLZBAJGFQMEFQLELHJVFKLLZSTGNPTFNYXYEZZLMRWPENMQKOYGZRSHFEQREK', props),
compute('m_12_2/8: ${c} SLYVPGHCEFXBDZFHFNRNSDGJSFFSOODDAJAPRIOCHNVOIMKXCQRBTNZARVUMRMJLZESYISXMVBDCQOJDAQRXEUPPQDVNRKHPLKTQ', props),
compute('m_12_2/9: ${c} DFFQIZFUUUWZBADFXCKJOYMZPEEUNDYIPPFXNKXEHSTUGDVBEHXZWVNXABRUMQWRPFYVIMGFQSXBHXQQQLINZRTQHLNBKBKSYZMZ', props),
compute('m_12_2/10: ${c} DVVKTQJYNABOBKFOTULLQSXWJKUEMGYTFEFZUOHEXIKQFYREHOWVGUSRWYAJRQUNFNANSIDUUNOQCBADOYRNNAPGTEVYEOLJGOUL', props),
compute('m_12_2/11: ${c} NIHOOOGBZFPMRTFNLWSBWBAUNWDOVFMDEMAENBYWZCLUOHQBWCHCABHKLOGAKPMCSOPTAKOJFQDILDBABHGFRMLLRRQHCSOFCWLH', props),
compute('m_12_2/12: ${c} FDAKKDINHRVWVIUDAFBLXMCXYYJRFYBJZXREHBNWLVZRWIUGUDLEDPCBEUEJXHRBBKSGOPBWEOSWBDVZRBHXNDVISVJFRIZBYFZQ', props),
compute('m_12_2/13: ${c} XVYJJEELRGXPMJZZRDNRQOJGLDYHHSNIVLIMVWPPRYEVUSSVLWALLGJYIFTTPCWWVEXBGEQMXEEDXINDFQMBHXUQKCGNLMHUBYDR', props),
compute('m_12_2/14: ${c} YDUXMLDBJMOFBIKWWTBTVJITOTRHKELKBOOEBRAZRKDXSGGVMQJJNEGVKQOLRXIRODQZRDRCWQAJDBCSIVUOEXDXTSGQTVUDMBIE', props),
compute('m_12_2/15: ${c} DJWTEGMFQWIUNZYPCFQSFHYRPBKSCSHNYXTIYKAWMVPQBZDMZZZEGUGTMWUFFOKLCXUAKLWKNBQWISDORNJWIIFKFLJTCPWUFYFB', props)
        ].join('\n');
      }
    