
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_4/1: ${c} UMEPFSUUBXTVDGYXPDYACLGXUNDFIWENQPBHJTPNDRKIWWYKNZWWSYJXJPPFDASKIZKIQAGDOAMXPZCZLBYDASXVTYZHPCRCMGCG', props),
compute('m_12_4/2: ${c} BREDNSOINHZZCDQUFUXEOTHVAHNMAZRXAUNUIQZJDIYZBBUTJXPAILUXPFIIOEVRFJEHVNFXAUGVDGOZWEPXARPTXVOTWQWPREZU', props),
compute('m_12_4/3: ${c} MGJDGRQCIFHWYEYPXNMLMOGTBOZUWVRXMHTIVQDGRLKPJDUKQUNERIEYBYHVMDODBQYHSSFBLQYWKAWDLGIZPJVMCBMWUNIHEFVC', props),
compute('m_12_4/4: ${c} OTKZQZTPZMHIOYCWDSUDETMXMGBWVDWQUFVYJSWTJADKVCSIDZRSEKTDTXLYDSFCDOANAHKKECUXOHAZXPBLOPKUPFQODKPOXSJB', props),
compute('m_12_4/5: ${c} XSIHFYZLBNHVBCIFYURENRHGPHLCYPFMEDZMULAZDDZQFXUPORDXDBNMUFEQYLFPZWMHPEAXQNPLTGKQVSEHDMNLEWXKTYNJQIQJ', props),
compute('m_12_4/6: ${c} FIMMYMIXURQBJARMXDRUJGUAUTKHDDNTWAQUIBASNPBMEWKBITNXTILRTDQFTIEALCVXYAXEJFOVQHFEFOJGGUJMBFWOIIEJRBIM', props),
compute('m_12_4/7: ${c} RWHZHMOKSCWEKVEWNUEBWTYLKCDDXNZUOUWXDUBLWXKJTVJICSSNZQGYHHNRNHNESOODMETTUJRMYAETWGMHZSRLYNOYYTIZMCCQ', props),
compute('m_12_4/8: ${c} PZURESPPTRLLBKGYHMQBECHSTNNBQTBTPXHXPCTNEIXTEGGSFBIPEYVAIMNCBQTMHMJZVOAINNCWSXVSXWUBCJWMPXXFMHCZWWEZ', props),
compute('m_12_4/9: ${c} BOHOUZEPDZKIKJAIBDCAIIQZLPDORQDZJBNDJCHKOJLKPBEWIGONQBYLYLIQSYTUTZWJYPFYFWWSCYZKKCGSMWLLZWDNBKUTENZQ', props),
compute('m_12_4/10: ${c} XMGQMINBDGKBQIBFFXSUYOWVVXFGEORKOVIENPOWVAFPSOCCJEPMDKXSVGMLBHDDJZFVMMCEACUHIZNOFUJJENQVVYTHSYAUJTGD', props),
compute('m_12_4/11: ${c} YZCIBPVMUZPESSCFKIJNGSXEWPBPLBCMCFPRVCBSGJHXYZLIGMQARXAQSRIPBJNWSZRBLSCYLNYNKEGKRMXXJEYRSWIGOHBSMLRB', props),
compute('m_12_4/12: ${c} PKCNSTKOEYPQFTVVIKWTJNXRYMNNDNEBAWEJRFNVOYXHDFMNVGJRYDOQUYTOUNFKEPBHWUUURWPECIVDNDNWKUYABHGXBVVPOJVN', props),
compute('m_12_4/13: ${c} XLQLABZMRQSZFHPYYXZYEJECYLUNPKZORIJWAQSXWAJXPGJHECVIUVIYGPLYLUQDVNRTAAWESYMKQSZCSPQHGRNETRMSNATADMIA', props),
compute('m_12_4/14: ${c} YPADSBYGDONXHXRNWVUSKEQJJODAJWEPVBFHDZODPHAEXZPSUSHHPGNFNCGQFPUESSGKOFRJLUAIQOCCWADXDWZDYNCWGCPXZJEB', props),
compute('m_12_4/15: ${c} URLHLTWEMHGXBKIJUONDXEFXWEXJZNJRQXUAJABEZEIVSULVFLLHNGODYLVWVCPSBHPEXINDTTFLNXHOPUAAYYRKVOZGILUJVMOZ', props)
        ].join('\n');
      }
    