
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_5/1: ${c} GRTRJTHPKTTCPEXPQMXDTTUTFQOROVQFOGTILKYDWYYVHHKACTQRAZVXYFKHLTUUYSQRWAWVYGPAELEEWVLOPACVQHXZIGUWSWSK', props),
compute('m_12_5/2: ${c} TGHWTQLWZVPVNHZXCYCUMLLHHOJYWBGOOZPEEZJMELRPMLIEFZZZBYQQLTAAQVSCTWAREIVIBJJDRSIZPZEETWMIXLQRKFSEQWMG', props),
compute('m_12_5/3: ${c} RYTDZAZRGVMEBZMXVOSBCBOUFIJWBEVKGTRXNHOMTRYPRAAFSQWMDJUGYALFJLVCVTSJEZGGYFUAXJYBKLPXPUSCXIGBMTVIDRKX', props),
compute('m_12_5/4: ${c} AFQEUMXBISLGYETEFBKKTRCUJESWVVUQOSLKEZZAMARCFZUYODLKTAIAALTHVNRMOCBVRUJGILWZEWYVDBBJAYSOZVRFMQDEGWRH', props),
compute('m_12_5/5: ${c} TSAFIJNHEYJRRXAAFJSBWVWYEDUQDHNAJRPTSKSSTYZYVVUTXHMBYQMWRTTAGDJSLUWXJPETVNHPAOLHCEZMHHIMDUZOZAJDBJJI', props),
compute('m_12_5/6: ${c} CDANUJDBDTAOBWAHGIZEVFIASGKQVSNQOXEHMOIDGUVSMXWSZWSCSGOOJSFUGPRPKRQZYSIUFGDTXUWVSQSBDRDXYAZDKNSROOAG', props),
compute('m_12_5/7: ${c} SCFHNUBDTHORUXECBGQCOGEZXPWMWNYJNTBWSPGBZDSIHUWBQTFWDJGTJNINOPCAPWMRXBWPHYFSDMBPHBBUDRBFTZSOVXPEFKEB', props),
compute('m_12_5/8: ${c} TSDDJXWAPXFIQYCQWHXQQTHULFLNEOWENNINHPZJPCTRLDQESFHOBUUPDMBXSWQANIKHTAQCXVBMJZXKNBUNJKQAVHDAQGEOWNQE', props),
compute('m_12_5/9: ${c} IFYEQHFONUQJJRIYAKJVNTLLPTKOWBXGREEBAUXHGYOTTETCVTQWSCPYXYXCIBVSINWDMWDZLEDIUGMFPETCSJDRLRMWYNAFKAOZ', props),
compute('m_12_5/10: ${c} LLYLTLJDUETCQUIRWOHWVWNDKUBFNATSOWUTZYOVZKACZPHYILUAZTMMHXFQNREWTXJZCSCISRRZYOUGQXBIMCBGKTCBXGKPUGLR', props),
compute('m_12_5/11: ${c} VQXKGNFNKXZIEMJRFEZYOGKVDIACJMCOYNCZCZRCQTZDCFEDLPSVJQOCPDWYIUIASVOZRGGDXMXMBCWNLOQNMNQSEGVHGXVUJRZN', props),
compute('m_12_5/12: ${c} UFFKLFHEUUEPCFVHMVEJJCUOYVYHCNRMXTRFWCROBTHFBMIVVUVCHWKCAROGGVGIRUGIOWUJMILLOIXKGMDNJVJKZUTOEXMOEKZH', props),
compute('m_12_5/13: ${c} TBPFDNANUFIRQHZZDILNHRYSTTSPIUIWGAMYTGYUOUGRQYDIGUNLBJENAFMBAFHKCVBEWSZILJWWTMTUALOEWSERKEUSHHGXHXJV', props),
compute('m_12_5/14: ${c} XBDNLCSQUYWHNBGBGCDVKATFYCUJBLZDSZLRZWUTFSYJLGQYTCPAHRJYVQIKVBAUYLHOZTDDFLZZURNQBQYSCOWGAEDMWDHHLHHQ', props),
compute('m_12_5/15: ${c} HHDAIBPGYPRCWGCFLIXXLVYJHXXJNXPXUCLRLEVVWRPESYCQDFQXNGCNVPTESFDYLZGOSGQCEIKXFJWVECMXYQMAXGORIJSBJYOT', props)
        ].join('\n');
      }
    