
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_14/1: ${c} IAWCPUWKTEVJHMYLPJTXUOMREWZSTNUXKJOFPAMBVWXUQNMQKBUAPKKFPMOHHAYKMPUHDDRIHUODYQAQNYMACFYQMPAHLAFWTSTW', props),
compute('m_12_14/2: ${c} NVHAZUQCEGPTKQXPHFVUCKKBXKRCGPLUBKXJFMBFVRZVWSWWXDHEUWCJHCCWLYBAIVNQIUFWWNJDLVRTSLSSYYULPRQHTPWASJZR', props),
compute('m_12_14/3: ${c} ZGRLLQELAJAMYWSFIQYGTFBTOAUCJTTOAXWLVXLVKDVSHDHICGKZYSZRGPZUCLGXYSLDHSFSNHNONNUIVDVOUDGKGEZSWUGEMWDI', props),
compute('m_12_14/4: ${c} CCRDBGUGXJMRVEKREFQGROEBATYVZQEDOVAOQRBHDUMCDMDDIHWCDNOYCFVJXFTESOQGPHTVKXSABWFWRTXJITSABRGFZRGEQLAY', props),
compute('m_12_14/5: ${c} XPQGYUOKOCZYDRRURSCJRKDXCNLCJKRLUSYHHLHASVEPIYFHLIWWWVKJPGNXZXYNIBFUQYWZAPBALELVHUUCAHXHDLPOSANVESIS', props),
compute('m_12_14/6: ${c} DJTBDXGSNEMQCMGAKEZNRJHLTTVQRMNXQOLUWPAGUBWZECNTBBTGFYMPGRTSFNUYTRECJZBNYRRUGIUKZSDBDUMRQIUSBJTJFNWT', props),
compute('m_12_14/7: ${c} VQHEKBLEMONWAYESEQCWWFMEDWREEXYPLQUVJWWCSTICOUVSWEGGHIRHTVUGZZBVPWDTINREOFJMJLCDTBTUWIDBKNLZVJGXPBKC', props),
compute('m_12_14/8: ${c} CXQWSCVEPGRMHGEMLMWUPCLDFXVHGNRRDQXPMMXTKHGMRLORDEZCPBSSTQTGJPGGAVIHGGXJYOADVMCBYYCDIDWNCAIRYHVXEILP', props),
compute('m_12_14/9: ${c} UTWEDZXYWCMKJUFBPVBXRMQNCVDIWGZLGIOQJNTSGKXRDUBCQHGEBNTEIXBBMGZRLILPAWTVXNAJTNYGWTLMZQMSBJUXUGRIUGTL', props),
compute('m_12_14/10: ${c} KSFQHLYELZICFAKZNOPOUWOZPMROLZJHCOFIVWQHUWTSGMPCZEMUFMJQMSKNCNPSCSJAVVZWNEVYGZSSZHMNVQORKORMBFKGTSXK', props),
compute('m_12_14/11: ${c} PGLAOWXVNCLMHRFPAWOMMSMGYCTLCAFFDDTIPBWBYZBAIFQELDXMKSWNRYLFEICQJGIDZGYGWBHWHZQAYTSHXWSENUIEIMQYYBXL', props),
compute('m_12_14/12: ${c} KDZTBXGIUJNXFHSOWLAUVVUIKDBVUDIYEKFXNIRNYEODSTCGHESPAGTPFMALJEPZSNWRGYEXGBQGHOZTUXYPQHOABSRRSJFPEFSZ', props),
compute('m_12_14/13: ${c} FSGNIXMCXCHTIAPOTNFZGZTDRBXJUNWTGNROWSYOGZLTCAPWGEGFTBMHXBXTEOAZCNJTZAXNCXENOSJABPPFFRSQFSLXLFERRMHD', props),
compute('m_12_14/14: ${c} DFGXMKXVXPUEYLFSXKAIWAWZCIDQQVBCBGIGPBSXKNLBHVORJEEKKAIWOKIOXGLUNBIMUPMEEQSKOZUXCMMPDNLWZECSUEIVQDAR', props),
compute('m_12_14/15: ${c} AHWLVQLBOGKCVGQPRHDJLWDUDJXUSZQBXIZBXAUCBKTQKTSXMYMZUFHMZNMIBDFIRZUQRWDMPZAHIFCMUGCQXWQIBTSWCACSZRXE', props)
        ].join('\n');
      }
    