
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_15/1: ${c} IIMNYWMGBFVHOWTUUDFFFMJCUMQARJQXATLWDSBOFTYOFAPSNEFEZNOSOEUINBXLWDTKUWEKPWAKOVMPGHLCEBEUEUOJTLGVOCUM', props),
compute('m_12_15/2: ${c} CZETIQTQAJNNPHKDVNJKUPIJAYASZKNJRUFAVNWOUDNFQNNSAJKCACLOYCUVPYAPCWFHDHDYGLAZDYOCKTAQIPOPFTACYLGTJFQA', props),
compute('m_12_15/3: ${c} FTTOAJGZKYLYVKFATHEVAVTKOEPSMZENICNAKPBYOOTQFYJAALFLVALOACSUMASJGZIQEKEDNVVQOYGSCUMUBDXWLCJEDBTTMIQY', props),
compute('m_12_15/4: ${c} JMWGMUSGKDVWHIVHHASZQTCGQFWFJORMSCKXOGIQTIXUUFTVFGMEWZQSQTQXDLBSJSNUVVASBEZBISKAVLDMUGCHATAYSGPHRJPT', props),
compute('m_12_15/5: ${c} IRMGRRDLRLMTNYVWPHBOSGWTXWJZCTQNUNQALLLCBSUTUYEHEOHMUFHMEKSIEAFSBSNFUUEBFINULQUECMJMFMQSBFGVPLRUJQEX', props),
compute('m_12_15/6: ${c} YRGXQMYOJPQEKSQUPQTREDIGRSKBHXPKFGTWCRFYKNQIGEIPKCIGFVDETBMVAHROJYLBAYNAALGCXZUFSTJSZCIZQXOKTFARYFQA', props),
compute('m_12_15/7: ${c} DPWDURBMPGZGCYZITRQWXGRORMQXZAUMVWEYMSNTUVFTBMAYWHAEIORALQKWRBWWAYBBBPCYAYNOMCQHOMFLJAEKNTNFFUYXQPHG', props),
compute('m_12_15/8: ${c} FFVSBKQPTXDPFQWGAMDDATVNWBTNTBYFTTSBGCWOZGTAABITIUPQURIWLFZWCODJOUJTYYLWHSAWJPXCFIYCDAKMPJXTYHLGCDNX', props),
compute('m_12_15/9: ${c} XLOHQJCIEVJPPIOLTRJJHFCWBGYCIRZENZNDXJHZCCQAFXPYEABSCNOEQBGHVYARCARWQQTJBJVJTFBHQUJXZUZGWBRXPTSRHKQL', props),
compute('m_12_15/10: ${c} NAZKHQDNLKOOKSSYXUNBNCSMXNPSLHMWESMZMLSAMXXDDIGHRCOYWSTYEZABPRRHWWUBRUBHWQFCPYDACTNBSXQLEDCSXDQGORVA', props),
compute('m_12_15/11: ${c} OAUHURILTUGGFGJAXOTCPXUIILWAADLGJNBVBYEVYXNTTFYZVAYAKKMCPXNUOGXPLVAJFNLMHOIDLOIXONIBWUIJZBYTMAVDIDQN', props),
compute('m_12_15/12: ${c} CWLRJSNSVIITSWVEEDARKTXLJSXZEXRGCWHQUHQIFVSGZJGZTLSIQDQVDCBVLOCTGSCGAGMYHXZQCCNSZHUKCSWVOVMHXFNWUWGI', props),
compute('m_12_15/13: ${c} AEXNMGFUGXEKHBZUEHDHWUKHQUPETZABMUMLFSYQWYKVYXXPQCZBMWBSBFENLWBAQEGMVOBONBLKDFKAGFSTYBPLBNNWRHFJSIVV', props),
compute('m_12_15/14: ${c} OUXCWRFOBEEBKIDGBYXXJYUHREQMZMWAHSGWUQLJODYKUBVNMGBNWWGETQQRGJLQNKCDDYCKOJCBCLKYCWXOASOYNMMIWXUMJLMN', props),
compute('m_12_15/15: ${c} KZCXFFIWUPLZXPOYOBJUCDAEHSNOJFKEWHPJXUBQLCKUONYSZCVLDSITVGZXKZPYLZVVPDQCVENAJVMOBONTXUOUKKOSDBKKPJKJ', props)
        ].join('\n');
      }
    