
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_13/1: ${c} YQICEVNYPOQMKWMWMQHLZKEQYNAAFYFLBPCZBFFMKABYOGABLXNSEYWKJUONNFSBSOPQCKAVBZIUJOGXJCXXAMNJEJWYPPRFFVDO', props),
compute('m_12_13/2: ${c} PUDOSKUBICOQVLQDVWGBGAWZPHPKXNFNAXEVYLCIALBOJMFIUXOWXSGNQJUWBVQFGPRRLKJNMIXMKYDEIZNNBASDXOHQXDYTYLNU', props),
compute('m_12_13/3: ${c} QLMAKYHWOBDFWOBITAXTKMRZUIVDZLYLRSKZBAUAUTWDGBTOXQZOMUCIUCZTVFPLETNJESILKCKBZLGBPXSVGGSRANDRNIELZHRX', props),
compute('m_12_13/4: ${c} KOMMFTKOHVFZTYNVXUICHQBKDVYRHKAVPVCNISQKUKVLJPYBZARMEGATZHKQSECVZMUJEQWPOFBZYQEGHCRNDTMLVSAAQVSDQVXW', props),
compute('m_12_13/5: ${c} QRPOWEEBPDLTIAWWZRFJKDZHMANKLOUIABKCOZKWDAMBIYEGIMGGMAZVWDXFQMHBMBRMWURNVXQRQYAOUVMMUOVEKDNPPPGGORWW', props),
compute('m_12_13/6: ${c} RKKZKDWPVODVKWBQMMBWGGVZERBZXZDVDNBNIRRHIYIOEUUIMBKTWARJLSCGDDUJFPUZBMLRJYREBVRKBNYFJMRKJURKFEQVCGRU', props),
compute('m_12_13/7: ${c} RRFTBMORFZLCYCPICZULNRMXZBNTWTEWQPJHZRHZZGAFMYGRDDCUITPLJWLNXJERXGYUZWAUVTIRBJSXSSRIKBMIYNDTOYQEFTEQ', props),
compute('m_12_13/8: ${c} KJEUAGEDDXQFIHCELFNAPRSXRIPWAJKSARPJNLWRKZFDTGCAGMSPBICLMASRIWLWTNAJDIOXKSKVIPLJAHUEVHJVOFTMIIMCZVDH', props),
compute('m_12_13/9: ${c} KSMJICEEPWBKDOUBOJCMKKZAROIKNKDTIOJKDMJTDJHADTDAUIBNPIWTVZLRKWIZUYZAJUCJHXEMNHZYYFJEUIUWGEOKKVWAYIBV', props),
compute('m_12_13/10: ${c} EEFIKYCSOOWSKIBZJLIGEVJQHBUMAAGZYEADBEIKBDFCZNRHLGVGLQAWPBKRMECGHWSAWJELLEOHVKAWTXVREZOPKTYIHGFYAOKJ', props),
compute('m_12_13/11: ${c} GRWTTKXSELLAWZXXLJJGDDAJVJORIKNVOBGUIECSLOQMYWVBUIMZGDSSYBNOTITGVXLVCJVSTUHIXFHOAUXMDMWJEKGFQHUCTBSJ', props),
compute('m_12_13/12: ${c} GVEJIPYTKVOJBPKCHLWIRMGPPVXNTMUJPYOETRIXARUPIGWIMQZHCDPMPBCBWEJFVHEQYKCNAHIEQGDPAJHULUHSXTWFEZJWVFVU', props),
compute('m_12_13/13: ${c} AAOYCDUXXADYBHHACJZBZTTKANNLWBTRZRURISYACRSDFRVJUCSOXZTUTORYAGEHKNCROXAXQXUBKVMDXPWKQSDJSEMRFWKYCYSH', props),
compute('m_12_13/14: ${c} YUBXSLHRPSVOTODWLDOVWLIILFNYZVPDOCMEDOVJFTVDDACKUQHPKVKTRYTOLUZDIGAYKHDXOXYPZAVIEIPUGPOOTGRRVOZDNPMU', props),
compute('m_12_13/15: ${c} WKFOHZGYIZMNOZFWTNQZOBVTFQEMGNCZUVASHAVSKCJDIQHQTCCMQPHFJATHAMBPJTBNSXOSOBVYBKOABRVBLYKCYBMQAGLBNGZQ', props)
        ].join('\n');
      }
    