
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_7/1: ${c} UDHJBMXOHMKFBVPCEIYTSKXQBHGCYSJLBPMMPHOWSKKTDKBYGLSUEIVOLUBTXOQEEJSUWNKKQFTUVGCILHZSJMHMMPBHYGMHQVJX', props),
compute('m_12_7/2: ${c} OFNHQGXDMTHIAVVXVYIRWUPNCXVOWUOMNKJFAXCRSPOMUDXSWSBWRUIYNTDVXEKHDGGDGXETOGUXKFGVNPONRULDBCXRFDNVJRRK', props),
compute('m_12_7/3: ${c} JMWKCYUAJGSWTLROWJRNBJQAKQYTCIXDRLOZGQVGEISVPHCAMCUGJOUFCKEALSYQBPXRZTEVVMTHAFHPMTVMQHTOUMYJLCNEMSOV', props),
compute('m_12_7/4: ${c} ATQMXGHENHRBSSOMWYALBARTKZGHUFZGSABNCKBRSDCXUPGLXMYQTTOJCJGUSSYMXYMGXVHDIDDZWFRAGNGBWXDHOJRUVLRAEOCM', props),
compute('m_12_7/5: ${c} GLRHLOOARLPFTKLIXDFZNMQQYSAORNXUNSEXBPETDVPQOINVHGPIFKLVAJCAMBMDQRYBNXZUJUJQGKOTNSDRAHNSUCNZFRSPVYCQ', props),
compute('m_12_7/6: ${c} YEIGBYJJOLSFFOASEYSWNBQSPZZEIHDSGHUJIYFQJMPWGEPEQHNQFAKZVDPYYNJIXJJNKUGATIWINGEMKYNKQNFBBRYDIDIZPNAZ', props),
compute('m_12_7/7: ${c} RTQSFBOCEZNXHPTNKQWIBCRPMENUZAXQBEDUXDQUKWUWLDRYGIULTXEOLIHMBPJGUTSOBCBPIUMIACTFEHFJMDGQCHNGHIXSQWIU', props),
compute('m_12_7/8: ${c} POXIAQOBDDCWKPLUXEMEFBSNBLMYEAJYPFKYUUTLTPEOILRTTCKGBFRPKWQPUOUFTRCFGVGIBEBAGTELUJTTAYPZMXAEIFZBAAMV', props),
compute('m_12_7/9: ${c} ZTADMKEXMQEUWDTWQCWTMPTGYARWMAPFRSIBLPXDBTWBSWKKIVKQNVTPCITKBJFBOHKTIYSSSJBCOLLNWOCKBJQWYUMDXURSBSEB', props),
compute('m_12_7/10: ${c} TBITFAWKLAIDHFLUPNTVXASHBXFDSDLNKCOKRDSFTFYEMXYMMAJKDYQJJMRIZQZUFLPJYELBVLLHVILEPOFFQYVDANMLMRVLZHUZ', props),
compute('m_12_7/11: ${c} DUQCYIZMDTKVANOPHSXYTQPDIFKIZNKSRWDVFANWOXMHUIDOZCOVAEATABLKYJZCEDMBTMGXVZHVNOMVQIWTAXJCOKRURVKDQTMP', props),
compute('m_12_7/12: ${c} UHQRENWZTFTOOSFNVKACKARKFIBMBARFBMEBCTGNOJIFTDVGZSGJYQNDQZJQWSCPZEENWCDFHJCQNTHLLADUNXSLDQNNORGLCTQD', props),
compute('m_12_7/13: ${c} DMRDRMODOJXYHZCMWMDDUQIWVZNGUCFNFGBSDWDKCQCYNEJOSNCTSXDGMZBNPAIWIVGQFGYSQIQNMVOWCEHUFISTWOKHRISBACYA', props),
compute('m_12_7/14: ${c} XREBGNWJUANYZWYDKCCQVSYSAMCDPDBPFECCFHKQMRXDBBCIDIPJSWASQMVVXRSZBUSGQUDJZKRSQNDHGRQDINQAUZTLMEYZYMJH', props),
compute('m_12_7/15: ${c} QYENHFEBUQRRCBVVNGKHZXANACJOXYIRUWFPUKKURMMJMASMEBJJOXDLIWEGUZMNXKCAMEDXOFDDIBYVAKYYXRZNIVGKUMUSBHEB', props)
        ].join('\n');
      }
    