
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_6/1: ${c} OJFBSLKJWGDQKECMBJFMTHZJKIXZVNVEMHRPGMOEVLEYEIWBRDAIKDBGBSTYIYWGHLOFSEHNQXAZLUTTLEJMHZZIAMXVDSXQCTEI', props),
compute('m_12_6/2: ${c} MSGRVVBFICDZXJXVPVZGLZCTEEJTUIFCYFHYESJLKNBAXVRUAXCXVEKVQZCLCIACFFLJNYAHXGJCMOQCKAXLXAGANERLOIIKJZXN', props),
compute('m_12_6/3: ${c} FUTNQHGYCVHILJIOMWTPUWSRMOGDDXPDDFTETZEGRRGLQIUJKTQXXSBPBVOYZVMZFQYHUKQVBJIWGYHEBJIYUIIRMCQSYNZCAYEN', props),
compute('m_12_6/4: ${c} RVVLTGRZMTFPKWDXSXYQYEUZUJZIHLXCGHZINQEXWVZZNKOVAZQXKDMHPZEAYAEJGGRMPVTYUULSKXLHZXTVYSRDRHXCEZWSNQWG', props),
compute('m_12_6/5: ${c} VXZOEDZOFCJJJMIZLEMPLRUUXZTYVQCFHAWOMWZBBTLAWWHKAFANOLWTLIQFGMYMMHUXUFTWKJBRYFLLBXHURHTVOWBXQZOWWNVS', props),
compute('m_12_6/6: ${c} BDYRNBQNGXJZGQEQJFLVFIEGGTORTDFVOBCCIIKOIJCXKADPSMKLBXEKHJYORMHUTFHZCRNDOCOYZKSPXPREOCOZHKNMJSBUAWUD', props),
compute('m_12_6/7: ${c} KDWZAVWREOIRKLNCZCBKXYRURLNIKXCCSCZRSPSRSWIOSHMQNQILZHZBESSTFZGPJHHQFGAMGLBFVMOGWDPSQCQUNXTCDHVGAIXX', props),
compute('m_12_6/8: ${c} CIESBHQNMLCTXRCZAUYGWDFBZAHFOGQZJAVGOCKGAHXERZFBPATRUXALSDEUJGEODXCSAGOADIQCTXWNMAKWLUMAIWFDJKEFEFSQ', props),
compute('m_12_6/9: ${c} LHBKPLIJXDDGQUUBBLDFIZFCPCWOSFLHGLPJFESODAJGXKASPHPZKRUDVTOHDRLKQQXKESCVQOWABMLYTBQVXSPIPTVGDHMPIZIC', props),
compute('m_12_6/10: ${c} TTIXFKULDPOVSPEYCYWOOKNNSIVVDFUOPUWQQYSXMLNAUKEJDPQIPKKWPOMFGPIYHBAGIEPPAIPPNWYUIIIPDNCSAYNWNOIEKIHG', props),
compute('m_12_6/11: ${c} XACVNQBSODMJJEUUJRTOAQQTSVCXDLQITJXOJJJLORUXVNLBIMEYBUWCLHMUNLIDDWONOIGFHZJWPFAPPLKBJTSUPSPRYOVQSNZR', props),
compute('m_12_6/12: ${c} QNRTDQXPXUSYOWRXARHNCFFWOYELNPDZLPRXNICNDVQISSJBSSHIJRDFKEPPNGDOMLDOSBDIBDRNCQXLZDLDDCTSSWBIQPSIHTMZ', props),
compute('m_12_6/13: ${c} FTZCGGFDHFZEYAAQREDJEUGHDYQZUOUPQEZVUQDRWBHNBHLYTUNMVHDUTDGYHUBBWKXVBASKHNSWSLUKYMDZTTWHKFZSGNJCFOBS', props),
compute('m_12_6/14: ${c} FDFYSXHATUARINQDPYXFTCHKJORQFQWSETFQSPYODRTTFSLWNXMDNWWDSHKGJPZYSUDCPDMJPXSTQJEBFCHQRMJZBUJWXRLWFGGH', props),
compute('m_12_6/15: ${c} IKUUDCKBDFCQVBDPWCCPNNQOKYIRXIUMHMAXOVOOZWXSOILYXFNAUTWNPVECCPVCLPELZKTBAIBGVBUVOZXFBNDYOWRJMYWANJXO', props)
        ].join('\n');
      }
    