
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_12/1: ${c} VQOTRJCQJBZBDRAKRMIENQGXMNUVHOVKZRCHJVXQXFSASUUVZUDOVGFBYHGUOFXBBPEKEVCNKCSMVPRPXUQVVAYZUGNMDWCIOQKX', props),
compute('m_12_12/2: ${c} TIZHHQUBACWTUUFROYSPSZNILOPCHMLYVIIWYYGLLZPCXSZTLKUNBLPJMXDAYLKKWLNFATFPLCPYGWAAWDSPFGNITGVQFUVKXUKA', props),
compute('m_12_12/3: ${c} PCNIBDAGYQWFIQJQZSANCLHBFSQVSCOPLYHMMAJAJOGKWXGKFJROVJHTELSHHOIETENEPAJVIHRKQTSNKQTGSHEQAKNDOJKPFPKI', props),
compute('m_12_12/4: ${c} UMZIFUDBXBNSGFSLCADNAXBWBHZLDRBGVGHDYVZTIKQXAKXJWCPACTKRXCDWIPWWYRKNPWYXNHSONTBCVVGAIYTIJSOTGSMCALUM', props),
compute('m_12_12/5: ${c} LQQUGYBCPUAUECYEXTCXZPZFYWNTXKSDHBSFBEAEFOXRTPLQVXTVWEPBZRLFFONSAUJXZCHQRKJTNPMYHEXUAWFDTLAYOWKGKAWS', props),
compute('m_12_12/6: ${c} LXAVOKLOYQWYPSTDKZUJMDXKAQXBBTQVUEJYFCMMMZSXYSKOWEXPFTPLZXNDZZWESIFPORMZHEQUGXIQMNYANUWMQUECODDSLYUC', props),
compute('m_12_12/7: ${c} SZAEMUCSZQSJBVMKLRXPSHBBYQRDMOECRAPUNFIAXWERRYCSFSISLBZLMFPYBKVKRWHAQNHSRNFXPFRCCYWAOOCCXIVDLMTTIMOZ', props),
compute('m_12_12/8: ${c} HSKCYFXCEVHBDXBEQNPDXEWEZOOYWENILIUSRDCQNGMCWWBGPWABHLEPSGIKEFTSHIFYLAQOKGJZECJMBGPFEGJAEQXTBGQZGBKE', props),
compute('m_12_12/9: ${c} CYTVJZTRKCMVZBXNLLUHHNTSICJWTMEHGYFCLGIHRUFZDZGIZQDBJJQTYMLAAJQRJLOOZMOTPBRRQITATWMQWXOVVUGSGJXPLQBR', props),
compute('m_12_12/10: ${c} FPXTXLXJILVIOJOLKHWTBDFTCGSOQSDPETKXLPGGMQPODPGADADPINVRYQBNFQOHIGDCHUOTLTJFMUIMOIXWJNBMNTIROUXCQSNN', props),
compute('m_12_12/11: ${c} UMGNVDDCSIHAOJLXTCJSQFXUOBTEITFVFBXUDNZLQSNDTYUAXOCQGYSRHWOILPIAIXDPIHVDSMWEURCLXJPKQGRRDRVRCYERXXPC', props),
compute('m_12_12/12: ${c} ULSGPJLRSXQCXSQMBFXPJMCOQYBZVCJGACHXBFAIPYCLBTVZXCMKTRCTNPZKDBFTLQYTAGCPQJCSMVATWAACCVJYNDQSHCBTMQJS', props),
compute('m_12_12/13: ${c} ICZEIJMHAGHCFGZTUIOSYKLEPOJORKJVYETYLOFWTBKQCWWWYSUAQQSCYLGJSYMQAQWYOFANHTCKWBVPHYCCTGPWPZGUZXHUTJFJ', props),
compute('m_12_12/14: ${c} ZKGEEPVVCPCLDJXYGWUFZCVOOTNOKEUBDJKZDVKCXBUAYUITAGJDLACRGHZPGUHJTUJGWOKTPGFXTUAWCVMMTBSQGLMONKICPASD', props),
compute('m_12_12/15: ${c} BPXENLMNGGXXXWXRMQDZNFOSFXOPQHFMTFHTIHXNBICREZFXNPDVLZDICZAEFNTCJBAVXIEXHWNPJHOGBMKWWUIDMIFZVUIGISJU', props)
        ].join('\n');
      }
    