
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_19/1: ${c} WBOOBYFAMREISYYFNUVAXKSBFLUCEACQYZYMFUQNFPMLIBKEECGMPHDYVHDZVXMSZZCTHQWUABCFXLFLEPNRYLFYBWREFKFZULEH', props),
compute('m_12_19/2: ${c} FNGTJRMYZSHHJYTBURDTNPVEWWCZURYRNNCIRUBUVUJHFSRACBTSVCRHWGMUFNGJCZQZPCDMAFWBLICJAGUBILNGDBMKMBIJPHSR', props),
compute('m_12_19/3: ${c} CNKDLPPWYKXYFTSGCIMOXCYGCJSGJGRYFJOKUPRFYLZEZEBJNNFHQPYCHXWUHDPGXEWJQUZPWMVVNANUPXPCAIAJUFLTUOVHSSIS', props),
compute('m_12_19/4: ${c} WLBMPKUODYBHMFTJKMNDNFGUAGSXBTGHZTQNJTAQLDPIWGGCTPRRYJBPNPHHFJXYOEWIFVSLIKIPAXVAATITEZCAILWXNFGMDUYV', props),
compute('m_12_19/5: ${c} CUBRGTOOXATYJUTEIBGWQIQSXJHIOPMITNQNVECSYJAAMJGELFFFPBUTLJTOJLRCGKRZUPRAQTQFXGEGXIWILFHHSELQONEOCWUJ', props),
compute('m_12_19/6: ${c} CACDNFQLDCTJUOWRWABFEMLQNVBJEUVOWUKTOBFTFHXFKGRFPBBIJLHMOUEZBPXNJOSDTHFJPJRYPNJZREPIRQBGBTZSJQXWLYQA', props),
compute('m_12_19/7: ${c} CYZLAOHYILSBHZUPWONTYSDKZVEKEOTERWQNFNABRZMQRHYDBCNLFMCQSROBIWPQLUTBVFSUWUVSFIKVHRDBAYNQUDEJAJJZPZND', props),
compute('m_12_19/8: ${c} JRBZXXMCTAVSRHLFTTNDMBKOIRKYQXKTHUVRTXXFSJFWDDEYOLXWBYMMJGMJDOKRLKHUWZXCVTCNWHAFTXEGBHFMBVFZDXSGNWFM', props),
compute('m_12_19/9: ${c} QPLVGPGPGJDXXWCRPATFIETQBGWCYTCCUFUWKSCMVIPTOMALBHOWAAYQGPHFSELXMXWIOWJGAFDMBEDAJGPAIZSGLLNQCTHDWAOK', props),
compute('m_12_19/10: ${c} YEWIBECJBGRNPEPQFHIGRGIOUKZXVOSNBQQUIWIRQAQLOLYCZXOFJMMSKDHCYGYOGQBXGQBLWQCPVYVOOBDLTFIMJHHPGRLZZMKM', props),
compute('m_12_19/11: ${c} TIBSMVEQEZGOZXKYKKDEONGVHWXUHXDVUXTLWJHAZJZWFUPSYNAOEPMYKOPLNQNVMWSUXXRYNXGAAYQZPRSTYRLWTVAKINGDLJUJ', props),
compute('m_12_19/12: ${c} CEPHJMDRPKACAMDCQOWTXAROIFDQMTFQYIMIOFFRZVUHVWEAXMUPHICFWTLPBFLXHVBSAWVGNBHQNPEQFHTGMLMBSHVAZGVAUEJS', props),
compute('m_12_19/13: ${c} CMLBECOJXTNDPXITWFZWRMAPIFADUTDMLFYQBAKHAZHKJKVMEHEGEECXBMQPBQKVHVXIGJOMDHDTWURCSEANYXGFJVERMBYAMLDG', props),
compute('m_12_19/14: ${c} TDOULUCTTPWEXEKPBYJJQGFWHEECQABAESTYLFBZOSDJLAWBYUNBLPVTNZMVQIAUZYJKZQALSBUQZLXMVLLKGBORZXUDJVYHWPZE', props),
compute('m_12_19/15: ${c} HKLJFVOKIUIAXQMJGYRWNSUDWKICFBVNGRSUPIWRYHDZSDZUCWISSEOBJKAYZRWOWFLPVLKARMHMNSTHXBZUYBHQDYHMAUQFNFMI', props)
        ].join('\n');
      }
    