
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_18/1: ${c} RMHGPQDHMAXMQXHDQNCCDNLJPHXZTVDEMOECTHFBSSQEEUOFEZYKGUSXEMYCXGOBYREHLPONTLFILBBDSPYWJRXHQKOKNZZRJHWM', props),
compute('m_12_18/2: ${c} WYDBRBJGGONJOVVBYPUCSRRKOINUIOTVGOKUWQGDEXNYRYBQZVAWOMJNXGOYPOCSFTCGIWVOYIZRZGFPDGTTTUJFYIWAHHZJBYFT', props),
compute('m_12_18/3: ${c} YFOTFCJFKEGXGSHUAGAGFUZKVLGRSHRAZVXIUFBZKGFZJPKJFPHSRTUGAJQJDXLAZYWVYXTBCCYKELQYPORSHCXRPIEVOEVKVVJA', props),
compute('m_12_18/4: ${c} FGDWTETYXGFYZFAPHXGATYNXPPKEAPUEMHMREUTGKMXTEWYMXWYMRMUDXQXTMUSVSEEZJKDSJZEOUQTZIWNQESQUFQDODFMOPYGW', props),
compute('m_12_18/5: ${c} QEIAJMXAKMHBQPWQWZFRVCERXQAYPXDZPWWLKAXQTPXLVSUGAJQWOHCZNSJFXKOZAVUTWTGCJLEJQZNJYYJWLHFNDZRDNKKJZASS', props),
compute('m_12_18/6: ${c} NVBICMRSZFONTZVVHWBGHIBIOWKVRMXBBSGWHRGIEKWRNLLJEOUNHXAOLRVUJXERLELMQJKXYIIVAKRSBKGSBCNTKBGSHDZRPKXT', props),
compute('m_12_18/7: ${c} HXSYATBBVTJHMKKOHVYEWZCKIOVDSXHUFLGCODYMNOQBUUQBHFDSNPMXXRMOZGHZIHRGOMSTLVVHTBIWTQYNHVPAXTWHNVFRYLVJ', props),
compute('m_12_18/8: ${c} VJFGDIAFJSQARZYTZZRTTOMAJVJJEOOWEOJFHLLUUUOAYKOSVXDSTNKPXYPRRMHWVPMXTLAWDQTMYLFRZSESYYWEHLFOHIMRBLRP', props),
compute('m_12_18/9: ${c} HKQJTVIVLCSCYCQKJEPIYTSRFVGBTNNOHUFIJHDNKUKZEVXCLUOKYNCQJTLCCLIGCLHTRIJWNQKTCWAMRSBJQRSHYNTEZGKLLXBV', props),
compute('m_12_18/10: ${c} EPXTJOEIQGYLOPXJTENPWBDILADKRPQWHJETRLDMEIZMBWRYDUUOZPVHZRTKCGDSSTSIEPLNOFLYREQBDUBDNPEIIPEVZLCXCEYT', props),
compute('m_12_18/11: ${c} ITGRGWIZWIAOOBEQHCXCOBPYKGIKIHUAOGNXTYVKZNKDDNTNGNSOMBAYLBSGUDUVNHMBHUQJZBUVNRFRPCEGREUTGYSPXSTPWKCV', props),
compute('m_12_18/12: ${c} NDFFUIDRAMOAHLNXNONDQHOXVZKOYDWTRDPGCCBBNLOSUSAVKKKTGXCEIHIDDPHTAUWIUPRTTBREHVIIGPACZSRRTZIKAODNIBCC', props),
compute('m_12_18/13: ${c} YVENTUFYAXYUSBWPUMOTTHDRKRVJGXALJJBHIQPLWURWXWRICKULZHULFHSEXNMHSWOAVPRAJGYQDIJTZXFHBSAMUPLAIGOAQUWR', props),
compute('m_12_18/14: ${c} JFMTLVFYOLTJGAGIDOSAAJLGHWRTWTBYZXUKPBNCFHAILQYGEVELRIVYPHIBJDURSRGUXILPKOMHJRGJAHPPIKJKPFYJOKWJGAYL', props),
compute('m_12_18/15: ${c} IIPJJHSECLBPZMZJWQRNVNGPFHNZECQMYRWOOTRVQTFLRMWKEEUCIRZFAUPNZBNGMTQAVWIFBLLVZHZRXULLCQNSUXPCXTTILBTC', props)
        ].join('\n');
      }
    