
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_8/1: ${c} PVJFKARPWYMIAATZYINXIFNNANZMHDAUHPRCBYIPHRNGXQIJUBRMVSFXWWNRIXBYJZCMDFDUPZRLTXJSBUMAQDZMEFCQKNEGCNTU', props),
compute('m_12_8/2: ${c} XURLNLMURLVGNSZBVVEKGBCQCZGIGYCNKGZEVWTMZVQOOBUIVWRUFJAKKRSROHODSIXDOFLOLPBRINIXOWQTPGIGCHLCGLSUEJAO', props),
compute('m_12_8/3: ${c} NUGYGIPYYCPEQHUAIPIOREWOUHXFEOOABDXFPNQUKFXYKTCNTMKZTPDEJCOOUJFZAWIGBHVINKGEBKUYMTPXSKKTWVGNZYZFMVXF', props),
compute('m_12_8/4: ${c} UFBUKNKOEOBGEIOIFXUOSZMEMLCWUHMRHEZRLGQDWYGYWLWFNIFMLWXUOTJHLWZXPDOVDCNQZSGXARMFMPUAQSTBKDWSVXKTLUFH', props),
compute('m_12_8/5: ${c} ZKUOXDRMBSJMUPTGQCLBVBBKZPVZDVUEYWNNGIVKOYZORWSZRJBCMNFOTCVUFSOAXKJVGWFDPPRDOXPMDLTBABMEBWSNFQHGZNXD', props),
compute('m_12_8/6: ${c} KQIZNZODXIIZATZZUEGLKVAEMGCDHLXHLRVUTIGUYCVRJIGZIYGVLLCFULUIHMTKIGYUGQZSBGRQLRTMJTXFHUPCHMGJGSTZOLQR', props),
compute('m_12_8/7: ${c} MWIHNJHZXXLYMKTUKFBTHRXYOTOHTNUTSWAZYRHMBHUKRYDUNHZMBKPLRHDARPNABCXPMZWQSWEHHBTEPHXPAEHYVLOIVBYWNFUW', props),
compute('m_12_8/8: ${c} FUXCHULQRAIUJOHFEHUUUAXDWJZDPVSOGIQICNGFNIGSCFUYUVKERHAASPYBDKUNKXCJWWVDNCIZGSHTZFBJOYWOLONGRTKUNMEG', props),
compute('m_12_8/9: ${c} VMCTDAMMVESWUIVOMFDBOKTBIFNCCTVAEAKQNHRJUGFCMHNUWDAXLWINFRIZLSITPNNRFJWKRKRKHXLOXTZAZUDOWBLVUAYUIXDN', props),
compute('m_12_8/10: ${c} GIEUQBETDSWVFTXWWCYCRRXSHOBFZYQQWPKBRPIOEUFWRMITMPLYWMODCQFRPYYBOZUGKOIIXPTVKGVJAFJHFRELTWZUTKWEVWJP', props),
compute('m_12_8/11: ${c} EUNJIMZSMOTOOOOQKGVQLYRXMWETTGCPVGLZHTIDSNDRDXPSOQHCFAQTDFTGLOZNDYDWCOUSSIJOGBQOPWRWLNJUHCGQHYTQYVCV', props),
compute('m_12_8/12: ${c} ZINJACPNLHSNYQMSRBITYONPTSSXDKWAVXLGKQHLZHQIAWDNQPLSMERNASFTRXWDFYZFMYHJWCBMUQFDODFSTGTMOEFJIHWHKBSU', props),
compute('m_12_8/13: ${c} XFFFSCANBZCKRWWXQBCLMRXTQGSPFUTOSGMFGRPCHZYHKBSGTZYHDVOMLGEJSISVXATMAOOZBPJXPXKQVEGSRIZQFSBZIWLWFCEE', props),
compute('m_12_8/14: ${c} JTAJBMCNRNSVNSITRJEZSLVSAIBRVAMQJISUQCPOUUXCUDESABDXKQERNMZKGVEUNCDCVAPKSECUMOGASWSCJCOTQFHIBWTQDBRJ', props),
compute('m_12_8/15: ${c} ELPEFDZLPDBLNLVNSPHTMTDLRIFAUGGYQHGHOLDJCIMBOOSWACTPBPYLFHFMAXNFEMWFEDQANNJRCOPMHVHDNEOEMKIILHMIMZOD', props)
        ].join('\n');
      }
    