
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_10/1: ${c} TUFPJEAUQYPOXUDSQJTEETIIPPXGIYJNHCPVWVGBNNGGPPERJKIVSEJQNGGLNHZUHVHUKAKFHBFQZIDCNASNDXWQUJZWGPDDLGME', props),
compute('m_12_10/2: ${c} CQDYKWVEQMREZDXNDHTDPLIZGSEQBURYJAYMPLHJQGEKSNJTDXFIYYPEGYRRZBBINWJAUQBWAFGHOVOXNAENLWAMXIJTOVHYWMXN', props),
compute('m_12_10/3: ${c} NXMIWGDRKOXSKIWMLZLTTIKZPLVOSAVEKZWJZVJSDMYZEFLHTHRMDOXKOCGFGDPKJVBNEHRXZGWTLZPILDVSCLDEGEZLUREKORXM', props),
compute('m_12_10/4: ${c} PXDEWNBSONWKINZURUXVYJPCFKKMVXJSVTWZTYATHDLAQEDUPQXWARPOUUHVTFBOGBTUUGTMPXAGAARIVMVDUSQRNFPCFVLTAHCL', props),
compute('m_12_10/5: ${c} TFJTAICUACCLJKZGPUSQLABZWJVBMRAKGUWRKUYQHTDRTZLWNLYAFJPLFNUUGVQSIFBUKWBRAGJHIGZDJYPMGDHGUXRXSUWZXDOI', props),
compute('m_12_10/6: ${c} NFXXCXTLWRUYYLXVAGOOVVYXOAHPLXHZQXNBJTSSGRVARZRIEEBZJGVNOFMMSRFWSNMAPZYFYTXUWIUKIDXQSJCNOKJEVKMVAOQJ', props),
compute('m_12_10/7: ${c} VEPWQVPTGOZFBWBAPDOOSODMPBJPHCMRMTVNGOSORRNNEQTACBGMLAMJXHFTNTLWBIDXWSJHLZBFLUQYFJKFFQQBODCQQAITNNFW', props),
compute('m_12_10/8: ${c} MPXKWLKUMQQVEUTLUVKGKYUKIGSRSCYEJYQENYXWLCCXJNKTYLPKVETAFLRISUYSHCJZKEQCJXSYIUOIJIKKUEMEGOGOFHNHDUEX', props),
compute('m_12_10/9: ${c} QWDPSOERASMCBCLFMDRVCMDCGFRAKPUVQXKUKARDLSHCBNDINCIWHVTCEPCKSOCIKNFQSRLDOVUWDNLPYNNVCNRKABZMQEYAWRQB', props),
compute('m_12_10/10: ${c} PRCWJMXKCXQPHKFOFGFNLHVXGCCEMFEFSUGKEYRADWMQLGIVQFBXHLIGQWATYDOQTQBZRZTFXGBYIJHKVZYOCOSPOEICSZFKFIZU', props),
compute('m_12_10/11: ${c} YQAXTUDDSSRZYDVJBJTZVJQLYQVJQPHATRLRSDIAHLCEDOVLRYUALIEABTHBMGKSYQGORNUBEKXMMIHRFPEYMFIYBLNPXCBGZBCQ', props),
compute('m_12_10/12: ${c} ZBHFOHHYMIEKKZBPDKUBADVNIVNIRVOAITPFUSGKFXQEDKGTSPLYWGGUMRXLTVJJHNYAQPWNCUBWWDZAMDJBKIBWNPNVLSBUGQFZ', props),
compute('m_12_10/13: ${c} IYDOYDOMZQJXVYRGBTJGUCWWUFAHZBAHKUOVPNRATTUELVKVZHELPWAQKRJFWJYJRBUMGRKOMPTAOANXRWIVIPZANWLLMIPDCOVS', props),
compute('m_12_10/14: ${c} EJDAJQNGDUYDOVCZIEATUDYWKUHSOPAEVAKKJTJUUBMBLELKFBBGBOYHVFOPOCMIJBBCDLLWHJJNLLGCSQZVFGPNUWETDQMIGCJL', props),
compute('m_12_10/15: ${c} OPDOREMTKOEJHNZZBLHMSBEMSVIUDTXLTOGWEMBTJDJEEGPUZXWOLYPJAYWMRXJYGQPTMYPGHWITDMBSKNEGCRAHMLPAEFKWOAEM', props)
        ].join('\n');
      }
    