
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_9/1: ${c} KBUFKIPUFUDBECICTPZWIOZGSNFABFUBQSXHYHWIAGDKCTSEXJEASDXQUOTDLMMGUGYRUQWQFFNGZOYJHYNXPLLQAPILWDIMCJPI', props),
compute('m_12_9/2: ${c} QKOBXKLYMHQIIYVALZDBEMFWGBMLOBUTSLPIJZKTKTIXJPZCKYGUSKZLBYVBSZLYLSGLYSGQINFAUTHDUXRHPTUEWDPGXLBYBEYO', props),
compute('m_12_9/3: ${c} GISTXEQNVFFWJHHKBOFMGIEKTXRHWKOVUPCDPUBQQNPCNXEJFHKWFVVDEIKKYLFIWYRQVFTGZJYRVHAGPTKXYERTHBNEJDVKPQGI', props),
compute('m_12_9/4: ${c} YHFZHZUXGURLXXJLFXJCHGRIQQTMWKDPCNOZSRPJGPSFRCQZUNGDMUHXDIGVSWSNCWFBHQSGPKOVJFKPCKOXBLZDXSGYKQKKKZPA', props),
compute('m_12_9/5: ${c} GSSIBAPJMXRIIHVCLDRLDCURIJBBPFQHFMEIETUJUTFWLMUVOHBHMKTJWYEIGQPKHIOEALUXDMTFHTMNLBOENAFBAVXKFLCRSHCW', props),
compute('m_12_9/6: ${c} EDJDDRVZJWIZZOVEJLJKIQLFWMHOQXQXKIRDJNDXJXBYYRSXJCKUOCGDWCGDOZXEDHCCENJWGDCMDYQYETOLYWTJGFEVROXSQJBY', props),
compute('m_12_9/7: ${c} MFFJWGRKKZZNWCQHUEDNFAHLHCHDEDQNPTJQFMMJXXXHMTCXWUHBHMNGDPWDKGFCVDURVFTBMCMIXHFXLTWQJIDUODYSSXJFTFIH', props),
compute('m_12_9/8: ${c} HQTXAFXEBUHXVOPCICHSRFMZNMSBRUQOHEELOMRQSQUMWFLRJOBWATNFNUBIPNFKGVRYQXBFGPWVEKNXNNQBFMRUSNWGPVUFNHXA', props),
compute('m_12_9/9: ${c} BIXTALABFXXXKAVOHMSGLGXBMYMJACCBKJSSAWTRBEIYNLZAUAYEJJGCJQNTPOUFFYSFKVDQBOQLALYCEERZYCZBPUDIKCNWVGHG', props),
compute('m_12_9/10: ${c} AEQSEEKNOUVYJPKLACYVDNCNVMDIDXDLMWXJCIMEFWZMFUIXBYIBVLPOAZJZFQVJICZSWAUFJSHELUTRJPJSZKJEQNXJJEKLPNXC', props),
compute('m_12_9/11: ${c} LWECFGZFWWXUGGPDQYMYVHVWKVJOHUKHLUIISLZHHVUDVYTFWDKIVFHTTDCKMWRGYCBFKDYGBZQQBBSKQXNAYHCSLYRLAGOSNQPK', props),
compute('m_12_9/12: ${c} QNZXAEOGHJEMJEBXLICHJIVONFPLFQZZUGMFHETPVUCNSWYRFMKMFDRXFQPRUQXBLLEYZVHRREAZNCTDJGFOGMXPTBZTWPJYVAOQ', props),
compute('m_12_9/13: ${c} FZZJCVKKRNKDRUDBSGUWOGUJMHFKPYJSNWILKNCCPXXSVMYBIAHZMAOUJFPLYVWFTVDEGMPYWLHXPXNFYIEHBRRTDVZRXHHTGQUJ', props),
compute('m_12_9/14: ${c} QQKPUSBYAHSTQMGRWWMIRAPBUTTPOGNOTYXMDWVCNUCOFAWHPAFJEIOKMGTMAORAOHOUOIIYGLLIQWQHGJXBDDICCWUEHWVYUSNS', props),
compute('m_12_9/15: ${c} ZPCTWFXGUDHBAFISXOQYPLMTSLCOQRHLFLCSURMNKNCOWLZHBYTSYOSJMHLKSSPKJBFTCHAGOYVULYCKAUCZJUTJDHOMRLUUTGVP', props)
        ].join('\n');
      }
    