
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_3/1: ${c} DDTWSTXJGRIVRCGOFMWNPATXEDEQBDGVLJLBHTYOSZJBDFKXQDWYHCGBFEMHSQWPXMCDAXPGSQBHLAVFTCHOOSOKNJDBAPZKEDYQ', props),
compute('m_12_3/2: ${c} QLRDXSFZOMIKJRQTGNRLKZTVVSCRMGWMHWOTCVMOYZQNCLRHAQSAYYNTMJLOYSBVUBXIMSUMWIBYTHXNQFIXSOGCCVJBIYJXDRCQ', props),
compute('m_12_3/3: ${c} BGAZEOPITJRGIJPVVLVYEMGMOZVKJIHFJBVPVYTXHELRFZQYTADJZUCJELWWTEUFCMDRMGETIIBMIAXMEFELDBRXKGHXXEVKANIP', props),
compute('m_12_3/4: ${c} QMWVIBGWREXAMECJFHIWYXBPAZVUOJWSIYQJQXGAXTQCMSPTISJDUJABWMKQKSWHDBVADMRQKMLYPIGLLVBXOWEPHSYGSUCLQLQB', props),
compute('m_12_3/5: ${c} FCPSSNTUZHTFSBMSEOPPOTPSAAIYLMHTWASRPPDUZKOOTDGDXOVSNNZKKKBAEPCUDSCLSQBBHOUBJDXQVKWQNEARKUFXMAKTLZSN', props),
compute('m_12_3/6: ${c} MELIGZTCTHQIIXWCJZJUNUKSDLPQHJGSVHLFKPGLCAIMXGAHLUUAIRYYYJDEBSTWFETMQQXPMMEVKVDZRNMVJIVSWLKGHPARGYOJ', props),
compute('m_12_3/7: ${c} DWIRASZIETYUGSWSXSFAJXDDKOOPHHCTMGZVQREEREYMSSEAZFLKJKPJQFUXMGCAZZHSHQVCNYESTIDEIBLQRFRQIHDQWMVKQWTN', props),
compute('m_12_3/8: ${c} VRMIKNFSAXTDCXUZFSSGLOGPFGCTYTDDKUWHIFUEOCTUIQJHTYSXCITINGVHOZJADODGAZVWZCSGPUYWJQOCGQRPOBOLRMFLVWYH', props),
compute('m_12_3/9: ${c} BXNDOLBKXDJVGABFJKZOSZIFOLKUOFUIQIEAHDRBKGIUIGGAHYCHHZISIGZGCZBIGOLQCQGTNPQUJXJDGJLYKXDOECLAFYDZIUKC', props),
compute('m_12_3/10: ${c} NFSEKKINWDXRZINFNUEEJMDKUAKEYKQPCOMKQOPHXJEHEFMKJOHMGKTZKPNXLULMHKFFVZRWXPPWIEGIJJXPVKPQBFMAAOBOVOSF', props),
compute('m_12_3/11: ${c} BJHZYOJNQXWWXLRDIBKMYWBUZZCQTCEUUIWYMOLHJJAQSGLMKZGFPXMVDFSQZEINNRUBLDEIUZKVZQVSYGIXXRPPXIJFALCQZYLH', props),
compute('m_12_3/12: ${c} FLOINWFDCJDFNMAWHXCSSHXXBAWVNNIOXDLQSTSXORKIJCUPXAXJEVOMRUPATEPUUUNFMMUMNGOGZSISXWCPYCBHXNWSYQVVTRHO', props),
compute('m_12_3/13: ${c} JGPNQURCMSOCDPYHUMJGNZOFRZCNIGXQJYPGQOXTEPUCNAYCCTENVWGQKDBDVYRHXPAPNYNEOVGQIPRZIBTWFNKVDPJMDCJOCBMQ', props),
compute('m_12_3/14: ${c} YEZZFCUWNQXMCLWYNLAPCPXKNTJDTLXRMSJDYSXIFPYRBVEGWVIZIJTLJSETILQFXMQFKZBJWSPGDVPBFYZBYWMDMYWIRLZFZTHI', props),
compute('m_12_3/15: ${c} HCTGLMARELXDHXXABOVDZDOQGHCUDZIYQGAHHAYRCDYPVCOFXBGWRPVKJWYXPIMJRODWXJEHHGJMLOWIXOGHPVRHHIRZIVRDRKLJ', props)
        ].join('\n');
      }
    