
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_17/1: ${c} PWHKHLGMJFRGQQBERFUNYFJPNHLBQKSSHGRPWWOMVVXOTWSYAMONQOQJFMQQRDTQPZWBJBTYMZLPJAJQWCNDMAWCGFGTKVWVHGQF', props),
compute('m_12_17/2: ${c} QRWFWGJALYNNBUHNZIMJHVBNZFOFCPENCEWXYEBKMCBWKWXUOZSNEDKMLIBSHLJMBHAHPKZIXNGCBBMNIADVGMWMQQLYXJCXFXUM', props),
compute('m_12_17/3: ${c} XEDLYGVPOANHIDYXXYCRFTJXWUGADRKAHAOWYJJYOARYFURUXZFVZFFWJKTPUUKVLTFDDBAZVPOLDEOWGSURJPEEUUFPUHEFJVZT', props),
compute('m_12_17/4: ${c} KCSZTGCHQVJWSEBZAPSZMWJJTUCRQXITJESYJTYGGWFFFZJENMOIGHYZLUCYWDSCFLZOFDWEVJVDEJXASQGSNDJFSXKGWFXVMMAQ', props),
compute('m_12_17/5: ${c} WYMQKNXRKIMPJCXTCQDTBVNJUHPVSXXWQDKFMIKDYLRNHEXLIRDVSZJFWTPXYNDSQVTOGZPYKBYWWZSKBVFVWYXHSDMJXPJVMBOL', props),
compute('m_12_17/6: ${c} RQGHLHTMJBDHQCQZSDFIPRKKHXSYZQAUNUCTCKMHAAONRZMTQGZMRBYKUXJTFYJOYRFDCPSCAVHGVHVXGNFKGVURHNRMJESQPYZJ', props),
compute('m_12_17/7: ${c} WCIDEWSWPQLMTOFSAKWBZDWPCCSACPGZVJEATLUKFLFCGBWRADXRTRXBEZFVRXPUJCQRIDGFGHSJIYUPHQWJCNIHROVQHOBGYBMQ', props),
compute('m_12_17/8: ${c} MQNMMVRFXWWGQMOUHQORATWRSCXPMDEHGIIDXOYTSEXCPNXPLYZDVHAWBWIYLCDFXZJBCZKPEUMXVQNKFFNQPCTHLYLPAQDZXJST', props),
compute('m_12_17/9: ${c} VSQZGJTXOJCQWFLYKHXMNGRMWZOBGPHWGDLFEQIQUHKIBUYAUDRFFYIWWNWAJYZHYORNDXTUOPCGOYDSHPDEUGNAPWOXLJUEBJQP', props),
compute('m_12_17/10: ${c} ORXSXEHETQSOUZPJLILWVYNPHPKADARMATNNVDQWBTNUDBEPQQBOWZAVNJRRFWSBQKUFNICOHELPPRNOGZJZIMWPNTACCFLVDYOR', props),
compute('m_12_17/11: ${c} UKYMGASXHBXNZYFJSNRVOWAEKPIWMPIAGSRQUEGJXYUDGFOULEFOPNGRYPESFZHLAWNHSVTBXTBLHRZAABPAUYANXEJXYOPJLERS', props),
compute('m_12_17/12: ${c} GIUAPICSMQOUMUBXXMSIQJQRXLLILIKWUSKBYOACRARMUUOFJINPBIOVURNFYNYLATXIPOVLZPMXGDPPIHUTYCMARDLCZIGIHNHA', props),
compute('m_12_17/13: ${c} ARRIUEAIQQHZALQANZOUUCDEIINRRIZNAXUVNIYJJDLNPSHBHRUGDUYZUAVSATTAFUBRHHGRXZENGFIXRPVQBZESAJTPFQNTNNBE', props),
compute('m_12_17/14: ${c} AODLRLAASTYWHQLAKHCCDMZBWTFHZIIFECNJDWTCEBFPMRELHAEDMEZQILIMHXHSTRKONOJOOZAFUZEIJNIPTCCIOWZQKJIRWCCL', props),
compute('m_12_17/15: ${c} EQAPPHBUKOQINONRRQFRXKNVDLMOPGZRMGCZNLRZLLAJGEAUGWUGUONHGWBWBFUOLRKXGEQWTMTAIPSCVZYDVSIWYIPQLATWZBZN', props)
        ].join('\n');
      }
    