
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_12_11/1: ${c} WIBCXCNBMEFUIRPBULBVJUGMLFKEDVYXGMURYZXOWAJUWYVNUDOHVEUYTNAOCESMDTFBNSUFBBTKFMNKLVBKJRCFNANTFOFNRWNN', props),
compute('m_12_11/2: ${c} LENHAESWAELVHBUOIDJFLOYBFQBSCPCUMNNRZUVHBLSEKYIWZZJXQVJNHMNWXYIFQENMAVAHUQYOGVRNHQXAFHBGYQRIWNKSEEAX', props),
compute('m_12_11/3: ${c} ZPXPLWYSPNXLVJBGPLJXCXMAWFPLFJQSOULQEIXTIRDLSOLIPAKUUJPHGBJMNDPPPDPERDEUPHHAIEBPXTMHSZIMLSMVXYDNDGBR', props),
compute('m_12_11/4: ${c} XQETSPUJPNCHADXOKWXOORFVDCJXZHCKPUJGRDTKGQKMFBHYRCMHHYZOSLMJOEBTNNVYISMCGEDTQFYPZUTTBUTRZNUCWTVDCDZS', props),
compute('m_12_11/5: ${c} OEDASIZPHCBTTZOMLYIOONSSBEDBHMMSMRZHLDXDMTYIOGRTTJVEFLGITURVFCWORSRUVWOPHTBRYBOEQBVSKQFIXPCYLUNOVWMY', props),
compute('m_12_11/6: ${c} ZPNMQXJEPYEEMXNQDPHIKWMUMWTTOOQIEEZRRQLUNWVMLJGMMNNMRKAIVUTIYYGMZHKICEREBIBCPBGHFZNGZMSVACCDKHJTFUOM', props),
compute('m_12_11/7: ${c} OOBBILYCTCDERJVCIDTVQNLFUWQWFRYSSWFMHWCFETYCAFAHCIZFAFLRXZPGKPXHSOQHRUMDDHUJVIZUPRUJFMHMKWWVYHNVVRJZ', props),
compute('m_12_11/8: ${c} VKSJTKXCPITBIBZMQJJRJBSQQNDWXJYBLNBORQXWYFIMDDQCRBRMVBUVAYFOGYBXVVATCWDQLLZXHUBQJCRVFLREEBRHAFUZPENI', props),
compute('m_12_11/9: ${c} ZABQDOXNVWHAGFZRUEHDTFTYCHAKLTUMARDEAEACBZLFGRXCBKBBJAOKNKJOWLNENABQHDKNMDAMORABPWMXVQNXYYROLMUUJYPC', props),
compute('m_12_11/10: ${c} OJWRBFPWEWWMQYYOBQAEPTUNKHSNNFPXDXIITVNJRUNRSDRHRGZIYXAEHBZFCKZEKLHSVMEJRQQAGHNXWUYDJHTBKWXZZXSBMYXQ', props),
compute('m_12_11/11: ${c} UETAXSDKDCNVHLVNVEIXKUWPXLZDWTHHDTLKHLFLTGAYAVQZNWQRWXQRKHGWXXKPFDFKWWXLTURBSXYASAJZACUFATBLXWDMCVCE', props),
compute('m_12_11/12: ${c} WFZXCMZKXWQJFOYGVMJVEOMGWHRMUCAFFXTAYZWWTUEGSBTPYVKULMPCAOGDKHMRBDLDHPHXDUPBTAQZCEWGITXVHYMMCFKFAOTT', props),
compute('m_12_11/13: ${c} JQVZICHWNCVBEWWMARJCJWCEQRQNZCUGHHLHKCTAVNACDRZAPUUPSQUSBRJEIFOKBJOWFWZUFCSYQZLCRTDXHFEVNETSGITQNTXS', props),
compute('m_12_11/14: ${c} DYDQILEITQNWXOCSIXEPYBYOQQENQQVJROZKQCIIXSWJNCDLBRMLICUAKUXZHAXORQYANGJBLBJPBOZRNTUHBTVGYBJHGRKNNSGS', props),
compute('m_12_11/15: ${c} FITTQTBXRSRSNVKJMCDPDMXUHNAFKGBPNLOROPVIHTLTZZCPPGVPQFSGJPVYPHXUGZHJZBUQLDDYWVCGRGCJKVUGNKXRBGCNSZDZ', props)
        ].join('\n');
      }
    