
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_8/1: ${c} HEIAOMGJURTLWLTNGQNGJDLOPDTFCMZTRTMNLGBJMOAVCLCLMKWDJGZIDCLUJCRUMMTIBZFLLFYZVDRFCHOMSUEVUUSRUSMAERAG', props),
compute('m_13_8/2: ${c} LJHYUJFBCSBITLQLRESYCWTAPRAGSHBRSOAQAIEOZAKDFBJJPPQVQQUHKMXNOPKJKAQGMDTGTNBECKBKZIHDFTXPBWOQGFCEKYCD', props),
compute('m_13_8/3: ${c} RUVBRXRBECPHUATMJEAOIKLIFNHNLPOHMBSKLMLUOPYNFTVLUKAWIPJZYGYNKUKEJRLQYWVWPYALFYZVDKXHYVMWKGMXZQBFCGNF', props),
compute('m_13_8/4: ${c} PVYFLNHTEOWFVMTASFFTRZHPTSYNKRISZWEJFWUAIHUKPXTVEISDYRMTKKSDAFGZHWDYDQFDXUTQQEDEAMXJNLTTNTIRPPICBNZX', props),
compute('m_13_8/5: ${c} BMIFXHGNDJBAGHDWQNKQULEUVRKDPDJEGEVEVSAHXCDPJEMXZPZDLFXQPZEEPOTBCBXMPQFEQRVFICYFAIYNCACMHCHIDBUTRPRK', props),
compute('m_13_8/6: ${c} ZHHMJHDXGHGQZXMQYRILQYOGKKISMBZZOOZSVUBWSUKUYBIBUAODDHPVMCFVTTXEEQFKLUTAJAQWKKTNQLOLKFPGMMGREJLSYLGC', props),
compute('m_13_8/7: ${c} VPZKWNKUHDVUUABPVRCAMDRSCEWJMBJJXRNCJALPTXJXCHZZIFLFBFNBJWGNQRXWQBNRYIFERJJXBFXXPKJDFTTPHGVVOJEQUAZB', props),
compute('m_13_8/8: ${c} TKRIEWTVUYSXCAIHFYLMSUUAOQQXCECWWBLWGILTXDMJECOFWMKSACDETEZDIJFCRJTRNAWFDXZLSNZRPFAKUQQLLAFCQNOATYUU', props),
compute('m_13_8/9: ${c} MMVKUIQVPHBFZCVBJKQZXCDPUXKWHJTKHELQJEHJEXODTQTSHYJGHAACUPCGBQFPVGRRDKABGYMDTAUHIOKQGDXZKEOCZKHFUEOJ', props),
compute('m_13_8/10: ${c} GGOIZIKNVFZDOPDZJFNBUBSHNTDRHHFJHZXSOJQVXOFTPPHRZGRNQVPNGYBYMESIFPXLUYLTPJKPBYANLNNLSNWQPZJXXHIOXBIN', props),
compute('m_13_8/11: ${c} REAHUWIMETUZJZDMEPUHXNCIOZWIHXKLAVSWSMHUUHTYCQUAUDALUKDIZSPPSHHHDZYCQABCBZCEUHYJMCRPBYGKIHQUUXOFEFJD', props),
compute('m_13_8/12: ${c} CFVFHRTHZMMMIXZXZCOESXGAZJYOBRIYFTVEBUSMLZBWFRYTDPRGPBTLQMUVECEEASMJSAZBNGYVEISCFSWXOEYKPTETGVTRAQMU', props),
compute('m_13_8/13: ${c} EJZHPINDEADCUUMUYZNXYUINFLPLGRHHLYWFZVPSLYWEFXNAOOWBVIPBADDABAVJCISWMZPVFJWAXWLIOWDBRUZVKPBIDUNRXFTG', props),
compute('m_13_8/14: ${c} YKIUMQTIEOOZARPIODXSVJFPDEGURMGHKQPGWIRKLFQYSUBKYJWJYGMOINYCZDSOFHQQRRSHKXYYBEEOSFMKMWSJAFUSALTEVDUF', props),
compute('m_13_8/15: ${c} NZBZZTSOLRBDUDWEOSJYKSZSQRBHDLIYGVYHLSBTJFJGDZFERHETNPSFEXZJZRJMSGJEVKLLOMJNHFOJWZPNVZBNRPLBTGNFBVJB', props)
        ].join('\n');
      }
    