
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_17/1: ${c} YVHFRLDJIMOYTXURGZZQSPPSOEMTBICBBVXKTSWTXNHLYEYMIFWKJGIFSFJESFABKHWZANZWKYZZZTKXLIMLTFEGYJKBEOUUFFWO', props),
compute('m_13_17/2: ${c} BQSFNNAWVUIKJWHBSJRRBAYEEUIELJORVWMIFEWEKYVVGVHLWLLYHYAZSDKHQWOOWTEQWGYDIUCFZPCEXSBFZZEKPQUCNANMYUYZ', props),
compute('m_13_17/3: ${c} AGABUMDMNLDHPUAZDXWPIICULAYNCTMWYFGNLHPCJWQWKGAVLOZLAUKVRIUZUPPEKIIWBUYYHLSMTIONUSLSWDJRGPMKRNBBZRJZ', props),
compute('m_13_17/4: ${c} OJUISTDLWVXNFJYKGOBLGOWXCPSXQTDMINMGNOGCYWWHUTLLIXARCKFEFRMNFRETYULLMKDDGOBHNSPEUQWQSSAAREHXAWLGFJMZ', props),
compute('m_13_17/5: ${c} SLLYFQCCQENVLGKHWXEOWWXLVLIHCVHBZIZBAFEYDXVWDJZGMYFDCEHGNKZFDCZGOYUDNPWWINNLIKOZXTLSSASNMHCMVJNQIFQE', props),
compute('m_13_17/6: ${c} JBOLTRLJWPSFVEWWEBNCZNJLZALBMXISJOJAUEZTXUKUBOSPPLVGLSCRKPNTTMUJTIXGIMSXNWHITALVPKHINUGWTJNKXYYQOKUQ', props),
compute('m_13_17/7: ${c} XOMQPAJWLPHQQFOXOCCKMMFLBYMDLUMGNNEKGGONHKBNQWNJWYAHPPAYHIWZJPMQGOLDQXLDXXXZYHYKHYDKZYEHDQNZOINUPILY', props),
compute('m_13_17/8: ${c} ZTPLZCWZBOQGYQNCYWDKELXAIQOHEJNLEAPTUJURMRPZCTFXLANUYIVJECDHKOHCBBSYGTCAKYWBUOSIBFVPIGLQIDMCAWBBZZCJ', props),
compute('m_13_17/9: ${c} KYEWMSEPUEZFDTYJOECNGVSHPWVVHZBEGGDDDHSSOLZWXWWWSJBNIKUNZMPOCLCAQOVBBPRWQUDGTSPAWHCBIKWQETTKNFRLAKFD', props),
compute('m_13_17/10: ${c} HFTOHMHBICKYTUEHDCDPIQEBTTRJRLQFGWQUWVAZGQQCOPKLWBKHCXKGOMMQXQOEPEYISNDXEVRVQZZTKMPOOWOPXUTQRVOOESLF', props),
compute('m_13_17/11: ${c} SWTNBDILCXAXXEMLLCOSGQHOTOJHGJANZFCPKLVVEGNFDWJSTRBUWJGXMNFKPNFWFKLRZYTONKQLGQLCNAEGGWNGVOJKUYQQRJAS', props),
compute('m_13_17/12: ${c} HQQUIZFBYFZXJGZUZQBVLIJDSAFAHOBBTJLVDMBHCADFWUCBMNUMHZFCZEWVKTHCGZGGEMDDBSQKEDIPWQPASCBIQFURKVXPPCCI', props),
compute('m_13_17/13: ${c} SLAITPIEJOOPBFLDFIDKVKEBMKXMNFFCPEKXOPDPAIKYVJETLKJGOBIKMDKFZHOXJXVFOKEYLGCJPTQSPVBBAFLAUERQGRVRSRBF', props),
compute('m_13_17/14: ${c} RFOHDFRIKRCDGGGRMUKNRUEEIVFSEGQVQQMIGJNLEHWSPPGXSLNOYXYYRNSMAMYVKYBYRACSSXKTOEQPHMVJHTSXJQCSNHWLAVQF', props),
compute('m_13_17/15: ${c} MKEXBNBCTMHWJGAODVCRXEQMZBGMUBJULYDOCGXIHJQJLJWNUUJLSLNKEYMWSEXOEQAWSPTYUHULUBZXXRLYEKHRENXFVNOEIXOD', props)
        ].join('\n');
      }
    