
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_9/1: ${c} SHBCLLEFTWPMGUIIDRXXPNGORLMBFJABRZMJCVBKBBFPUYMXDAVMOKBSMMLZPWYIPCIFWHETZECDQZMZUKLLRIPVYWSIFDVKVVXE', props),
compute('m_13_9/2: ${c} URXLDIFLUBCCTCVDHDWSPKLSQTGTMYXAHIESZOEQNCGPTYZQHUFBSQBLSSYUZMPXTNBEVTMETLLXJSLZOGBSAQFNXRNHPPSNIJRS', props),
compute('m_13_9/3: ${c} BDMUHWLYPISYKELZGZQTLESAWWNCEIJZMZDKTDXTZDIJBDAIPNBHPFRKKZNFCNMBGCEJZBQYFHADIGOCBPOENOGNGVXJXVTBBEJP', props),
compute('m_13_9/4: ${c} TVINRBCFJHHFNOCLUJUQMKSHGKFIJZMKIOVDFADLICOBUUUYGXTNGQFJUSATUJYHEAZVLCXOZAKUHOBXGDCDPJYRWHXNRBJISWJR', props),
compute('m_13_9/5: ${c} HMQTTOHZGBLSIEYKPUFQHGQKDERLJSQPSOUHWYQZZGCRRTBXMSLSOQUXFUERCREYIAOXAUGBPUSAZXNNFRIRZEHFRXZFKNORJIQZ', props),
compute('m_13_9/6: ${c} JBOQUHJURKIILDAMIPJONQCWQNYTRIWUMBBMVIZZYCIAFGIRZIEJISMJOJIWAGTKPZHKXOFWXWUMBXTGINCBUEORDZNLHNQNUZMY', props),
compute('m_13_9/7: ${c} GOLUYCUBKTVDVTBQUOLHSFDDKQCNRPRROWZVGLOQUMPSXBCSNELZYUAGXNTJKLZOFVBWVKRSJFFMZQYRHXVBESTAZGHFODLCJLNY', props),
compute('m_13_9/8: ${c} BFKCEOFLOZSIWAOSIYVLXKTTBCKICLXIMHVSASSHQRSTUGRWWYYBWGWTCZSEAGBHKPJCUCJNLOSTUGOVUCHZCHQKGYXQUQZLFJDK', props),
compute('m_13_9/9: ${c} FUZJJWTEGMCHACYETUYCTWWFZKBKSPIZBAAFFCDWLDWBPYUWWCKAJYTQZAZCQDREEURJGEGVRSXBWWUFDRHFJDHXXDNILNDGAAPG', props),
compute('m_13_9/10: ${c} SLMIIKXOKWYYAEUILLQZAZBFFLDGWNQVQUHBNTJRIGVYOWXENJQFNCYTIXXPQTEAOPNUVPUCPJGZRTVGHAORDRBXXUHQWXJNLOZK', props),
compute('m_13_9/11: ${c} HFMDWVYNFJKIFUYKLHJSXRZIMQZPGZYICMFUXIZJCZZFCDDJWLTZDIGXDAJYKDOUUEQWVCIRATIPMKSHWZXHRRMFMWVDPISJSDNA', props),
compute('m_13_9/12: ${c} XXRKOXXITCLULGSPTOGJAEJUSQVLNDBVDMFOKGVJUXQBDWPJHYJLEOUUNKKWVTPTNKBDUCOKGMINQFBCJRJNGYMWQWPOWDNKUCQW', props),
compute('m_13_9/13: ${c} QEAUAMXFXROMWCYLZIGQFZNXBZNURCNDQBGMZDYVGDPNPSLAQDGZMXCQSWIIAOXYWLQEPMSRTYYTIQIWJHVZABPSSJWWYQQEKRWB', props),
compute('m_13_9/14: ${c} ISCWAAFOZTTPNYDSZMZJOKTZSOFOGXKZNABYDRIJVWULQOMRQXQTFTGYEFTVYGIJJMKHIPQFULUPIEYCDRYKXFIZSIPQASWMRNQP', props),
compute('m_13_9/15: ${c} WPPJSJCVGREOOZSTTBPOSAKJQCALCMPCCBASGBYICPMBJMGTTWEQVTKUSYJGJCEONVLETNTMTHZXTIJTCKEAMWURYUZNLJLETRYO', props)
        ].join('\n');
      }
    