
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_20/1: ${c} UHYQONRRUANBIMPUGAKCIZWGTNYUXNWIBGQXLLGMFAXYVXALYBLWRVMNGYEVESWDETPXZFETKXLPGQNYUOPNDZMWNPLRTUIFEWQI', props),
compute('m_13_20/2: ${c} JFSETSIDULKJNHAODYGSDKUIATUHGJDYYZSYOMVEICIBIEHXNDVFPHESWDHLWRGINFNUUJHCXWOSKCUEDXNQNYGABVCBNIUXSOMI', props),
compute('m_13_20/3: ${c} GNTCTCFMMQHXZMHHRPVNNLXJQOYBKAMMORCQACZQKRLEDQZHHUNHGXAPHPLHDTFVAEJNLKWCKQNJGXBXJUEUCBFTFLZJWZDDEJYK', props),
compute('m_13_20/4: ${c} OXQDGFUVTWJIYPCRASDJLHFCUNCQGKZBBANUKVBVELEKXZVMRYJFOWRMEMNLZXGOMCWQBMNBWTOUCQCQQSIASBAXFKAOBQHYOSON', props),
compute('m_13_20/5: ${c} NDIGHFDYFPNEAYBQLOUUNWWDIXHRXLJTFCFWVKROJGEZXBYWUQQKWELZXBCMKTXBZIDRNABSPEKJFPCMRRFRMIWTPCZFRKBRSOQW', props),
compute('m_13_20/6: ${c} ELPYKZIYFLSMOBTZRYHHREOBIXSQQTGBSDKIUWNGEUQKVFJNLRTUTVHITHDBPTZQSNAPTUCPRROMHIDYLXAPWTCCCQNRLONIFIWM', props),
compute('m_13_20/7: ${c} GFUWFCNMDIURBOXFAYZHFDHJIWAFDSXBNUBDKFDHMIKBODUDUPMRJJECZFWPKLRXZYHYOYIKIRKXGAFYTMIIVSQPLEPIXTCQPSFP', props),
compute('m_13_20/8: ${c} IOMHMZLRCEITVSHHCKUQQORRKPAUOGMOOHOWMHCIQJCHTDHRIELPPUHBIOPPWGLAWYVANOLECZQHWXUFLSHVWKZKQZAOHOUJGQBO', props),
compute('m_13_20/9: ${c} NZHGNHNGAMNBPSYROZEDVNKVXZAPXSFHZYLRZTZHYLWJJVCMFHKLGMDVYQXOUGCYVDGPPJZRWSCURGLXREIDAUPUBZXFFSEMDPOY', props),
compute('m_13_20/10: ${c} OZWAGMQFHLRUHNVDIYHCWBTUKHGSUFHPGJZACIGCCFWGZPKFDXTUNWKLFVZRFQYKPQIRPUJNFXJVTJOUXIBOEFYDWYUNKSBWHQHP', props),
compute('m_13_20/11: ${c} PCTIEXOIGCGPXIUWMZTMJHPZGVXAGFAVIGNJJLIGUVMDPPFOIZRHCGGEKPXPGHYGLHXAOGRSSDUAYBFWDRBQOIROPUQMHQLHZWKH', props),
compute('m_13_20/12: ${c} DVAOUUJNRRFTCSESXURQRLIYIWTTLLRNHGCJWJTVVBGPXAFVNPFSEOFGHKNGGVCLISSKKLCBSLGVDOSKNWZSDTJOPRFKMPHSSABM', props),
compute('m_13_20/13: ${c} WZSNUZVHBFGCCLCYQQIVTTKRYSMPDNFSYOBCUNKHAULBUTXEPJTMLXFQQYYNQUWOFKHZBUGVQUDMJVNLALTRJDRKBSZCFHPYMPWM', props),
compute('m_13_20/14: ${c} KBSCQTDGKBIYYIHATNSZOLUKXJDLNCORGYLQIEEQOAGYETEJUJPBQWMNVTQUOFEDCNLOUWHDSDDFUAEVDTYUKMKTIBWNRBNTMHGA', props),
compute('m_13_20/15: ${c} FBUSQYFGICEVHNHDEDPVZKJFAHNCNAVDVRVIYATYEVHIRFHYRGQTOWWYMWHJYWUAOXHDVKUNFMDOKVUPDHACANCQTNYIEWURVUBN', props)
        ].join('\n');
      }
    