
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_5/1: ${c} DJUULVECTTOLDQBWVDINKSIMNCNBNLYFQZZPLRTPGPEGTDXVYSXQDYDYYSAZBSZQCHYGRCNJOZIVUUPKBNVUFOJDWDZHKBETPFVZ', props),
compute('m_13_5/2: ${c} HJTKEPDZTEGZJKAOSRVGEGUBJMIIIRLHTNFAHKOZCQOLAGTSPMHYPNMNVPPQRZASWLJSTXFAKNMIBLGHHHEEMVGZNITECUTBSXNC', props),
compute('m_13_5/3: ${c} XQLRCJEIOVCFYHQYGUDYCEBQLTVVNQEUBVGDXBMNJOQQBGDBMWINHYYEQVWIXPMMISCLHQJTFUIGKNXPHJEPPRVUNZDZGLPZLIAS', props),
compute('m_13_5/4: ${c} VCVMLOATKKQBZUXUENVTWLBZEZGZXRLNXUUZUUKXTBTMIOYRSSLTEPFCMZUBLSKZFPPKQMLXOFJUHZCQDZLOHOWWKQPJHQBYGHLY', props),
compute('m_13_5/5: ${c} NETKLTJEGDQIIDTITGVIQGRIDPBDBUYNEEPXWOQCQZQOQUETNXMLFWZWFWAKKMHVCTBHWSEPSCRHAXKACRAPGALMVJCWURPZYMVB', props),
compute('m_13_5/6: ${c} JCWVENIENGKHCLDLFMEXEIPELICUICVVQARIFNSSIBUNMVLPCDEVQXNWKRWGPKHKODNNJNRFYWZUVMHDQXNMJYQUDXNQSVAURLNW', props),
compute('m_13_5/7: ${c} WAHJBSTZSBSFAUKPITKXWEDMLNTMENAHEVIDIDZTKYHKRZYKRFFBAHTGLWLPMFSLXMAUCOLYKOHSVBLWMISOGRBDXQOYXFHEPACX', props),
compute('m_13_5/8: ${c} DYDVSDBDUGVNVABJUKWXLEUNKLSATSHNECLXFYGCQONVMNCZQWCMXRVVDKFBDMCCVXVGSWSWBPKRLIYIAZHBOMCOBLBNLHUHMNXE', props),
compute('m_13_5/9: ${c} FKREOFKGHJVGGOVQPZNENUUECBGHINULJSEAYHWJMOILINZQQSHYKWIXTARUJEFICYRHSJHOMHOATNFOCYMGSADTRQOSFYXXLEFF', props),
compute('m_13_5/10: ${c} LKVOKAAACXUVJIRVEZUCMOXBHILMCSGILGQBWQVQPMISDMSPBKMFNYMZIRXVEGXEPHTRIZJVSCLKUPQXAPSFPVJONOIBNSSABOSJ', props),
compute('m_13_5/11: ${c} REBLMXSUZPNAVJFZQMRUBOQQAGBUUSQOSVPIFOPGJCGZVWAORWMHCRUAADUYOQUJYLEFUSGGYBSDLGORPMQJXTNXVXJTTKBJNVLR', props),
compute('m_13_5/12: ${c} IRTZIITTJEGQMAUIZDIQZOWVOCHCLZEZWQOSOWKTFBYVNEYXCSMXNPVYUJJAZGGUEFIFYSERZGORRNJGPEXQGBLFSPAGIZSQXXGL', props),
compute('m_13_5/13: ${c} PGUIKMPQQOEIICPCHUMATUWMRBGLVGRQFVLEIHRVVAXNVFRRBQRJIJFVUTFRQHBEMGQFRNUMNDSAGEKHDVESUSVNNAKAMLYPRMYM', props),
compute('m_13_5/14: ${c} HUVQFXCCXNPJVKUVZYWLSMUVHKJNAASGMFONTMJTVBYMIMAQDZTFMOFFETGWSQPTTGLMTOQDXOZHWFNMSPBUJRKTXMVEJQJCCIFV', props),
compute('m_13_5/15: ${c} YYSDQBEHVSFLHWJSYZZCLZVDJYSEVWMCQPEPWVCVDUWHBWXHMXEWWCMSORRHVJCKZATGZICXWUIPNGDXCJTZCAUXCEFOXTTPVQLB', props)
        ].join('\n');
      }
    