
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_10/1: ${c} SAFUJOQVGXGSGNREOEKVHWXPVXRLOSKWWMKWGSPXGLNETSDFNZSUCNTWPHYGUVOWBRLTAIQPGAONWBKMXDHMBNRLIUPQXCCFPJDN', props),
compute('m_13_10/2: ${c} QPKHPNYYKFOFRQSNVBAUHJSSMNEINNWAOXXGYXLBHGJFHBPGEJUGOJINBORVLYRPEGMGCSVNWLUIACGEBHEGYFNKRNCVEKPTSIWS', props),
compute('m_13_10/3: ${c} RYFBQVELLKQZVPXUYCEVAQZDPDKESMGIMOOXAJYKBDTAULCSEEUXWJTJRKFXSHCTCBQJMAGGKPFMCVBPYFAQSPPMBTZAWJZIKWQF', props),
compute('m_13_10/4: ${c} RGCPNHNTHXUWMDLZWCVOJKYQIZIKSTIXMXDIMPFAJHMKHJSPYFTDNHVCAZNKYRWOQXNVNVQPPOMONBBLSLKTPBHLQYQXTSBNFDYF', props),
compute('m_13_10/5: ${c} KUYDKWDRZRJSTHQXAKQQSEVXLYVSEHHBCUTEVKGKVCEUYYXOHCBJADGCISVNRHPLCVFWXLRSHULLXVKXGGNUUVEJTAWMEHZVLJXL', props),
compute('m_13_10/6: ${c} HMPXQJGXZBPJCBUJATBQGMVCJVSHADMJTAZOLVPADEOMPNCLVMCSIHOMEYDBSVZTGXOWRSPTHVTRJJSGYRTKONSULRJKOKEXERZV', props),
compute('m_13_10/7: ${c} HJUOOMDEPQAAMHVWLMNVDZQCUMRJGCFOJOBNICJQSONNIIPAAECSVBNKZBDSPFBCLGCCOVKZYPOYHNFFYZMHQPCSEPKUCAQKXZNH', props),
compute('m_13_10/8: ${c} CWSLRAHPWVTUOSLORQTSWBGBMSLIPHKSHTGDIYTBIMTAWKIDQZBHCNSCILMGPLKKRSEUGLJJDAQSGYYUZZYUUHDHMIYIERALMIZX', props),
compute('m_13_10/9: ${c} DOUHSAWBQSMDOSCSHBHTSCNEYCXINBWDQSEGFWLBGGUQOBCQNOLUPUWGEQLGHOHZPJROOHRHROPOFZYVFZCNPZFLAWFGAPVYHPBU', props),
compute('m_13_10/10: ${c} MXTCKRTHIPYSJMXQXWPWHWBQGLBPRYRVHTDGPCNOYGHGGSQTBCYWYYEIXNVIUGIDCZJQQDHHBBDDVHYHKXDJWULJDWIWWNGFHWLB', props),
compute('m_13_10/11: ${c} QVESHJCMXJOCWZBKILJGOMWWJZBIKWISOBIFSRELELOXXTIPVDXWWEVUAJWFFWMXUFHPPFIGXZIUZUDBHAEIJIRUYZLXOWGPIQBD', props),
compute('m_13_10/12: ${c} FYLNXTKEFTCTRFJBWHGKNPTXCVPJELIENKSTQKLCFZFSGEMAXUIVZAJZMTXFLBCVXNARCEXLEJXBLZTBOLLRQBPEDBVJPMANNYRU', props),
compute('m_13_10/13: ${c} CLFNHJIIBRKFCXBCKOECSEGSTPDXQKNMAUBQFJCVWABNVPVYJXBITXWWSOMGZMCSJUFCUSFMEWUJUCKXNXSEFENKZVJMWOHZJRQB', props),
compute('m_13_10/14: ${c} KLYTASRJWJYUCHHBLBUBZCFGJRZBLPLUWHQZTVQSQRTYDESTDWNLUGSXLVAISJRGYNJMQEQLKWZVGYWKVELAOJBGTEMUSLBFVLNJ', props),
compute('m_13_10/15: ${c} DWMBKLYMQDZEQJHRKXNCGWWVTEIHSGSISCRRKABRBZEBXKGKYMWWEWWEOZPMOJYUWHFXWEMCJEORQDOUKOOBRAVWFAMSXCQKPBQZ', props)
        ].join('\n');
      }
    