
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_2/1: ${c} KJHAELNLWZDKSUSVGASQQCNQBCQAJDVAPWLWRQNXZIDYJVYCYUBLMTDIEPRRUXTHJRZXJLRFPKGPPLICKQOKPQCYOJSQCQCGYLWG', props),
compute('m_13_2/2: ${c} BXDYQEHJYZZZMSWFKGBLDUOPVSCQJNSCMWNTPGCATRSRSFBXRKWGLBBQPUBCWDRYMITWODUWHVJTNJTMIRFCHLOVHTLDJSYYHQHN', props),
compute('m_13_2/3: ${c} VWYDMISYYSIPABMGMTQHTTUKIEKAMSNXHTIVPBXTTONDXYMWOLGCQMROUVYEMGOFSUAKUOKQNFNHFPHUETDBCJIQFQSHKFXRKSNG', props),
compute('m_13_2/4: ${c} PKKYLUVHIHMCDDFJWHRQCHQYNCPRUWDXOYYAUKZZCAWVOQTOZYMUVXVYKVCVMVCJNFDMREJOVDNYXGTWWWRNGREVNVTAWRCMNBNF', props),
compute('m_13_2/5: ${c} VUVUGVMBPTJTEYBNAEIETIQNKUSPJKUVXWPGBFBZOMJRAEVBYQQZGBLDYYNYNYOBEQIYQSQHBSVXLCEVEWOAILKVNGBYBXBNZNFN', props),
compute('m_13_2/6: ${c} IXOKYPPNAHKFTNSTEBMHRUYYSUQHTMBFXOPVHIAGCRLGLGDJXNYPFKAEITKHIWQHYJRXURWNQGBIWOJNYKVNVCKFZMXVQLLISMCA', props),
compute('m_13_2/7: ${c} PSPNILNWIDJAKCNUBCZIJYJPSTYYOYHXQVPERSTYWOKXEHAVFWHTVEWZEYHIONASDHIOBLVEKYYRKMTNFHJAPOMAPRRMOAMKWFZX', props),
compute('m_13_2/8: ${c} XEWJWUFCDFLSKCVMGNUVBDTIQOIYUYHBZDHDRNEKZTOVUISVAQHCZODUZIGBTRPMYJLIJMIZVKAKTQMDCEJIKMRHWBGMXSCUHNGR', props),
compute('m_13_2/9: ${c} SPHCGEWIPENMDRUVADKZENFXPICZJVMGFGNDVZAUTGGLUFLOJNEKIKIBILYMOESMSCVRXFBMHMPTSRQFAYNJYFRRXAMSTIJFIQAP', props),
compute('m_13_2/10: ${c} KOXRXKKVFCYOPMYDNFDDYWMSNLBZDXYFKBJDJHFCTQXUILQKYTWQMYGDXJBZVEDECBGFPRZMHEVVBLFEFDBOMBXVMOKAZOVIHYEE', props),
compute('m_13_2/11: ${c} FISFRZUANYUZRBJQVDOXSYETMFYLJHXNGOLNBJTBNTFDGPJAZXARVDQWFFNBDVRSRTQYNMKPTMVPFLFLJSGUCFMNIAVVPUUUBHCL', props),
compute('m_13_2/12: ${c} PNUAUEXCUFFGGTPVOBQYBHEVSJFPLOZRDJQGHKYJMMKQUGXFZJDTRHENANYZJLQMFFCGZMWVGGLFYFIEDEWGVOMKEYGYNDXHBCBJ', props),
compute('m_13_2/13: ${c} JGRKGEHNTHHNQUUNMNSNBNWPEBLFZSOASDVZPPORGZUSORZXLKKQIDYVHOTYKBFBCXMKHNYXWJBVWRMLPYNCKKFNSXYUJUOLKMDC', props),
compute('m_13_2/14: ${c} HUQCEUFKXNVEQPCMCVWOGNGULXZNKJYGHGNLWTZNFBVFFPIAGIGFTSVIXOPPCNLBWMQUETDURMFVXQTLUGEJJMLMYHRORLEJESRB', props),
compute('m_13_2/15: ${c} WSWULSBJYRRGMECXYWNKSGMFFXFUOVZHFJJYDFWKKLKQZEXFSIYHXVRSKDYHDCKBHMRUELDGDFAXNSFOVRTPGRYSVUTOKSNXPNVJ', props)
        ].join('\n');
      }
    