
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_15/1: ${c} AUEVZJMIMCDFVTZOHTEKTLTLDVIGBYEUKHXUOZGUEVMFDANBYBNABFDYYDUWYXJEJLDFRGVJTGDUNNQDDDTLSKSZBKYTNJMWMMUM', props),
compute('m_13_15/2: ${c} HHWJOQNOEQROKVWQEXEZUZRKWPKQEWXUXUGGATABQTFAFVAQGCZXBHNFZDOYNDZCFBOCFKVOFVHOGEKGOELVVIUGDHBYSFEAEJMZ', props),
compute('m_13_15/3: ${c} UTWWCFKGENEFDLZQQUTWYZPJGHGSHGKGKIHQBXNIQAZLHSZRHCJEOZTHCMOMRGEREVJPJWHJVYPKLZCPZDCWVVMQFDKFNUEIJZKU', props),
compute('m_13_15/4: ${c} NOZBLBIUARQQFVZNZVNDVDAQPCVOSXMQMURGKUSXXDEFKTLENCCCYIARZYOTAEAXEWNEKEUPLVITCGYJQZBEFDWRAEYAFXADWLOD', props),
compute('m_13_15/5: ${c} MFKYNJPFZVGPHMAWAGVIKSETVNVZISHHYTMHIBIOEHZIOOGVXWCTKKKGJSPQQVFMUJEAXWQUBNFKWAOVROIHDXOBHYQIMUXPYKLA', props),
compute('m_13_15/6: ${c} FMLOZOLHGODKXROPKSWVJJWSWYXAOPKEGTSOFSRMRGBELHLKXSOAQMNQSPWAIVJQFFGBGFDUIVSLUNPSBVESVOFTNZCIHXOIZKWF', props),
compute('m_13_15/7: ${c} IYLPPUQYCTVAUXOAAVTIINAQZBGTMEFMTLAUXIYHAVRMPIHDSZAORKYWWVIBGZVCITSYHHPZIZUKSXRCUIPMBBMJJBCYXPGGZCBB', props),
compute('m_13_15/8: ${c} YEFZKANTEKVIKCUMYOGYBNHGIQSBPCQDQUYDSAICPLJHWQCMEADSRMVRWXOIEXNWYIZSYAMZCHLCLXKRJFYSMPKUJKRMAYSCTWUG', props),
compute('m_13_15/9: ${c} DNNXVMQNCCNGPFDSALEKVGTCTMSNSUEZNSTZSSXRDOWKFYAQMRCPBOGTXFFCJWQXHJPMOFPGFZYTHRDCLITTGGUDSNBIAMCUULLP', props),
compute('m_13_15/10: ${c} LDKKNVHKBDVZJNNHWFXEKHKRGYSXQJKNVEMXEUTSMDMHUCNLDBJBGTLAARXAYEKESFOYDDNLOJNYFCABAJGTMLWMHBLHGSLVQGPU', props),
compute('m_13_15/11: ${c} IIDXGBGJTQOIBXGDYHRSOUSYJNJECHFUFQRPKGFIULWHFINUOYYJRNGSZMXLLXBBHJNAJTLKBKPROLMWQLPOFNUJURMQVAMAWLGB', props),
compute('m_13_15/12: ${c} WIOMIVDAHYWIJQUPRGUVPKGPFNGNRICUUUOUKZURJXBMOTCMAVQVFLJLZWBLKSPEOGVYEMNEGXFVEDLWUHHDBAIZWMQGEBYGQOAZ', props),
compute('m_13_15/13: ${c} PULNSGZPRGZYKTOHQQVNNRCMUCMAFDDGSDGOLAIYXCKQVSWTIPCKTCWOVGMRIXYLPOOOPVLNWWLWSUDYTPHTJLMSDELNJLMNCLXR', props),
compute('m_13_15/14: ${c} EFMQBGBORDLNTIAMZTDNLSTQQPQKLDJUZUKKGFFFWLPROSQVGSWPSIDEQXNOJUICBVYKNRUEDQGQOWJMMYAMXDOGHWNGNDMELQMJ', props),
compute('m_13_15/15: ${c} SEXLMTXIODTZENOIWBENHWSXYTUCKAKJAPYYVZTQFJSLKMJWDPTMBFWEIARHNSQKVIDGTWRTDMCXFBUCDQYGJEUAXFQVCPCWRBWA', props)
        ].join('\n');
      }
    