
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_4/1: ${c} RGZPPLUXJYQJVQJSUFXFCACHUCGYESWTAAZCCMPYMWKLRVUSHNNTYCIHFHFEYQXLRKLQFNCHRFTYKOIWEPLRHDGFACQNYURFEEWD', props),
compute('m_13_4/2: ${c} CTKKTQPYRVEWSKZXDPEMUAUJPIYGRVAQDHOWICBHXKRMHELIHJZMPASAMMFYQAOXCJHSVDRFDBIKJWBANINCSJFEHZZNKPEKFPHG', props),
compute('m_13_4/3: ${c} IIFIJBVJRQPJKBZSOBJJQIOALXRGEHDDKUQPVLUNFUVYVMJOMCJUAWRAFSXLFUWRQFVTFAAGWYRJTMCLSHLCLMZDGRLNTTCJHWOC', props),
compute('m_13_4/4: ${c} SIZFBVXZIHEKMMGRJUUDEBOMIOSDBEOMHSWONUCBAYIXSKVACCLLFWPAKQCWJYSSQMJXMYQVPXINEJXTUNVSWOHPHLIYURRSBCGG', props),
compute('m_13_4/5: ${c} BJBVFKNBUWBXNPACELBTKSBZOXVXLYEDAGOIJPUJKMTIDISMWLWIKEQEZCSHZWLLRZRQFPPHOWYEKKBRUNSATVHTHIBPJDWPCXDO', props),
compute('m_13_4/6: ${c} BUXTQWCCGGBPZSFJFYSCSARGOGDTDVXIDRDMGXBOKQEXCJTKWGDRTWVOWPVTWEPABONFCLSHMKFRFLFXYZRGUBJMXKZOBOUWCCJI', props),
compute('m_13_4/7: ${c} BWINRFFSEXKAFDZXVYZZLBDSIAYGBPQPFRCLIHIDWZINPWUPJMTHGIIYTGMWZTSXNYOHYGIKNWPXILVODPCGOUVVIDCHEOFCJICO', props),
compute('m_13_4/8: ${c} YLFOCSWATLYUVWTXJLRVSZSSEFFWTDAHIJGDOVTALNHVTMMXNAJXASQZWKDNRGJEYOIYSVKSFTIHSMTAMWLWQTCSQUDLAAPLGICS', props),
compute('m_13_4/9: ${c} AOSNWDBIBVIURHLRGDIXVPAWKJXTOUUFJKSMRHTPNEGBIPNQTOQMELDSUUXXUZZOJDGSYEJOVASBBDDYBNWNHCWWZKBJXGCQIEGA', props),
compute('m_13_4/10: ${c} WEEPUXBCHOWUARDTTYEIFIDNZEZANKTFPCOWLYZTIITYXYIXLCSPROGICJABIIQOFAHNUBPJCSFEBTIAAOVAZSYSPCGRCWDUGYTW', props),
compute('m_13_4/11: ${c} NMOMZLCWSPNRTIVKQZIWDRQNUWVVDYXYTIADQSWEDUGNRFCRPKDJTHCWZABFQNZJGJYKJRSWDBWNGAKYYHYKKWCGOZEVOYJQWUVW', props),
compute('m_13_4/12: ${c} FYLJLTRPMDYIHJDMILKJATZGAXBCPIQIKSJUGHQBYXZZPNSZENXLKMJHQGHQUPJMHNGMQXHQLASMQFSGWTMXAVWFDBZCHEOBUXQZ', props),
compute('m_13_4/13: ${c} OPTFRWRWPXYDKWLCSDGZIKCLDLLIIMNFCWKBDTZHBBFJBMWPBNBOZJERXBFKKKGDMYQLAAXMUYRQDWXGJHZALCETWUDYYCNRYEQM', props),
compute('m_13_4/14: ${c} TOJFPUXKZCLTBYXCJOCHKPKVQXFXGGZXFEKOLMCMSLCFABAFDXWNLRJAUFRORYYCTIVXEYBSDMLJLFCFPIPWGEEKICDTYYVCMQHN', props),
compute('m_13_4/15: ${c} KTIFALOHFXDOSUBMCFKUOVCUAMENHTLPPWMJWMTMJVNUGNOLWZZGCVPFTHMTJZGYVJDOUVQBQXSSRIWMYNSVUKPIVGVMEFXKNLRQ', props)
        ].join('\n');
      }
    