
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_7/1: ${c} OEUIJAXJLZJGIIZMXAIPHZCJJGQIHWYBFEWPATSIJDBINYCBAINYCAIVCUGMYHVTPERDMYCNVUMCLYCEKJWIWOYZMCBZUIBNGDJO', props),
compute('m_13_7/2: ${c} DALRDOFIYKSDSVCDKGSKCLVSOGGGMHTNKXBSYTYTWTFJZXFLBQPBFCKZPJLXOQGRPYUTRZPMSCMBMIGMDCCALKTIMMWBSWDCNOTN', props),
compute('m_13_7/3: ${c} WJTQNTWDUKCMVMFXLUGVOCCHPWAMGIEWKSIBGJRKKAINWYRNFHBYWDZTFUXPMEFCVRVLJZUCMMKWJVIXWMFFZKCRMOWJBBPAISXO', props),
compute('m_13_7/4: ${c} UXTEZZUPRNWDORAMICQXQEGXFIUFCOFQUHVHGDNEBMXUARZVLBLWARYZCBZSGCYXMUZUYJAUWROIDEDLGQJGWDILDBWOIGDNSJHB', props),
compute('m_13_7/5: ${c} FRQLGQODPBRUARHVQGUHGJAWDTGMKOFBXZCQIPXGNDLDZYMOWDADHDZXZBAEEANTJMUEUFWQXLXZKALZOYDAMICYKVWTNRTRTZYJ', props),
compute('m_13_7/6: ${c} QIDFAATREYMGPNGPRINBMWVMJGJCIIPVIGGNVRHQGPWUJCLBARGLKQYBNEHYLILJPARHEBMAUVTOEWQYJFTVGXJUZPEFSQACHIEX', props),
compute('m_13_7/7: ${c} MEMOQLGTIEQGFTHPCQEABXWRIMXXJQGTHANMTHIZMXZJUWRUAZMCDCPFQQGYFGTCRHEFCFCHZOBBZUUKPQDYFQHISZLBWKEEAPFJ', props),
compute('m_13_7/8: ${c} UMWPTUGGJCEEKQWENOOPZOKGAVCJCYRJWXDMLYDYOWIXYFMNPPWMWSDZJJDVSMHQGHFZRBESCODNXXRBXAUFTJIZRXPGTLAEYVLO', props),
compute('m_13_7/9: ${c} FUHGBCPOSVMNWENIWUXDERISYELHQKTUXPHAQYXIVTGFWZXUHEJBXMMQGTDKBYFZPNJPQZLHXCYABROBOLLUSMKVTKMVPOAMFTGD', props),
compute('m_13_7/10: ${c} EYYLEXXOXOZFKVEGCGOTIPYFWPNFYVRDGUSPKOVXZFUYOBCFBKZRRYUKRFSMNXFBJFDAKOUZPIVMELSVFGPMQGIGNTCJYPLQZNSJ', props),
compute('m_13_7/11: ${c} ZODGAEFQSNWJRPTWQKYGARCQFEUCFEXHKQYMASJJSUVKNLAYFHGVJYTQWDIGGLOPYQFUDPECWKZIXSBNKAUMRRTVNMRMRFBLLMVW', props),
compute('m_13_7/12: ${c} MWYQXAVONKIKSEHRPGCOETSGLJUJOXUZWOBSRGICVRMIEMQIFTRYMSBMJKBCFUPMVSKIYUIRLYYGISJUEIHYZSJKOWVYBXLBXOZZ', props),
compute('m_13_7/13: ${c} LTEGVUGDLPFLOVXZNOYDMOKUZAYVTBHRJQUNBLXGOYOWLYMMJFWGNJEVNZFGNRSPCONOTKWJLTXOHCURMOYJEHTDWEUECGBIXXAE', props),
compute('m_13_7/14: ${c} GYNRNHTEOKSWDDIPXJIZSISINRYJUJOIULXUXNZUDGVWSOTJZBYSLMQXFXOWOEAWTFNHNGZBCDHBFSFTBLYNTVFZKFEKYCSVOCYT', props),
compute('m_13_7/15: ${c} YYYEDZJZALMDTMQKYSCUAIIWXMUCLLEESQLETFCQJFZNDJVXTVPAYYSLILHRBLTCLWRBSYPNNIYIETEGYMISECSMOPAAGOXSTIRJ', props)
        ].join('\n');
      }
    