
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_13/1: ${c} SODHDNVLTOZDWPEXLWALMZOJELPDBIRNDWQHPDDDZAFKZDHEOOFJKLNSAAPCECMOCBCKKLTWMLXSRWNVAZROVQFBUFBUOHHBZCWU', props),
compute('m_13_13/2: ${c} ZIPHAYMCHMXZRSPJDOCRXFOYVLTAJZRYNHISEZGYDPMGSLLXVNFSPFNOFKJZZRNTVQKGACAYJLAKXYAUDNWGMGNCWMOZIWACFURO', props),
compute('m_13_13/3: ${c} XGNSXNALGZYWUCDNRXVUKYITWQYSUKWMXSRKVSPRIGQTIQPIEBBACBABSSSDCCLQIBTTZWWQECCTTLEGDGNVJPIHJFZGEKBSGKBC', props),
compute('m_13_13/4: ${c} LLYYTMHICROOXONNLRKUNWCPJGFXQHRVWLKVEERSSGWOEMJIPMLAMGGSNSDBNLYXEUURYBKSMWDERSEVOLFLATNJGHNXLVLCGBAN', props),
compute('m_13_13/5: ${c} BFWTZORXCSQFTJKOBSBWAODMMNOLWJHNRNJTLQCJIBTBXCGQQVJDWEJZQPZQYGNTPUPXQZGYLEOMYLVDXVIDCTNYYNSWKWOGIQRD', props),
compute('m_13_13/6: ${c} PSHSKLSMMRVYIBTXOAYWIQGZNQROWBXRVUBEXVRLYLLESXTLMBZCXBPMMJGOGACAVZKWETTGTKVKOJODAJUFIIRDBZYNHVSGZJYW', props),
compute('m_13_13/7: ${c} LHFYGPBMKFBBSMSFTJIFSQEMEEMZGOWJFWFIZZLTDSVNETUCYBJFFSNKIXOUWTWKFLOXUISPNFMWWZAFVNXHFURJHOGXGDCVMSLY', props),
compute('m_13_13/8: ${c} TKGOTFWGYHVGGDDFOFVAOGRCINTCBVBOKNFXSVIVJRIVBANSEDNIQRZXMOHAJWBXCUQEOSSMCFFBSBAYYAAZPOJGBUPMMEKIHEQA', props),
compute('m_13_13/9: ${c} HTTCRUHQMUIUXIFLGCYTOGHCRWYJQZEJOJIIZWLJEBFTLKXQBJKMCEXZLCYZZKBQKGHZWAWEXOHJBUDTXABJQXSYUNGHGITYACDJ', props),
compute('m_13_13/10: ${c} XVJQFWVSGIMVXXLHFEXUKAXZITDHASOGXPNZUYSDQWDBCDXYNZHKHVAXKAJVTGOBRYGDJEHPKMRFLUEVTMMDINBLWZKGXCXZRZZX', props),
compute('m_13_13/11: ${c} LEZKUPSSLWJOWRFVDKXTKZYZXPCPYVSMTYSPQSVUPMEXWNBVWNPDWJISFTCUGGLOPIONNDYSFXEUAETYMEHZPJEBLINNSXWLOMOS', props),
compute('m_13_13/12: ${c} UGKELEDQQKXTKMANQCMCMQBAXAJQOAPTYAHUDOBWTSPWSKSRRXYRVDOKBLBKEMVQXRMHDDKZRKQSGTGPXRQVMLRFCEXJDMOVQSRM', props),
compute('m_13_13/13: ${c} LPMSVSMMIYGPOIRVLUGKUSFFBVRFOMWLINKVHMPHRQTYEXCNOVWLGYQTFXKFDBCUZXUTCXAUWRSCDRAEFBUKIBWRCQGFVGMFHCLK', props),
compute('m_13_13/14: ${c} MHPIHYUGLKLIYIDIUWXWXVWHDLONSPQPGLLGLMXTEXRYJQDVRVWLUMXEOMLIYZQEFYRAKUXLGATSSCUBWETGWVWFYXTLWNEZNFNV', props),
compute('m_13_13/15: ${c} IWBVZQXYCNUBLTVZPONTXXULZGNQQAHZEFPUJGKAOHKFGJJCWTLLADXVYRJRKKCFMMHESPEJFFZYHSDMJRNAPMYGATRBGYIFKWHW', props)
        ].join('\n');
      }
    