
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_6/1: ${c} VAAVDYANGBKRGVSFAIUGKCSMWFCGGNNPYDSDMINSNGRVIQOLEUTHSLODEAAPNCGLKYVWYHFHBDFXGGOTABZEULKZTOZAJBDKNPFK', props),
compute('m_13_6/2: ${c} KPZIAUIKOGWYSXTGTFIRPUNVSFDJEOBIWGEPLMXFPWTFFTRDFUIYBZCPGJSZEFWRKLLRXQQFLXLEEPPQFNTCFNAWRIYDPLGBBXRR', props),
compute('m_13_6/3: ${c} GPLYBTTXZBOVNLWUIYBCHPOENCDURJZIQYMKGBJJGMXDHRDQMWMJGHRVJAQYUUXAUABMNFQKVGRLSEVMYUJIJQNAMSXDZSEWZMRR', props),
compute('m_13_6/4: ${c} QTNYALHGTFWIWUSJGKCBQCAHGEISEGEFICEHWTPLDWOXVDTVSFFQBVMWFFXQVUFCGYAAJPGZNFWRPCAGQBICIQZRISWXZGZCBEEG', props),
compute('m_13_6/5: ${c} HQNEDRYQZCCPHUQPEDUOYBOAULIKSTLNJFLAXKOTHEPTHNRMRKDUBMTSOZCDHSUOGUWVDCUQQOWJMUGUGPGCSDXVCLTVXKTMINBO', props),
compute('m_13_6/6: ${c} LKROIWXJFEKUSMFXOFAMESCFECFYEMIEKSNUKHNHURLRZPIQUWYJCPXMZGTYEZAHJLPAXUIAYVRZWZUMCTAFTESIMEUTAVQTJBOE', props),
compute('m_13_6/7: ${c} RSGUOFRKWLQWFXPWBCUDKYFURTMQWDWXDSNEJZAYGHSNFQKAXXVHAPLMYWGPPKUSCUUUBNOVBOBNWTHGOXYCBCEJOLQCBCPASETK', props),
compute('m_13_6/8: ${c} RQQCGNYLIQSXZKVOQXOUMSZDHZSTCBSHZDNIVLUIXPSDLDSKPLZEZHHPOTEHNOCDZBYUKMANUAECOCLDKLJIJJRDKEPUWQXLWSVB', props),
compute('m_13_6/9: ${c} JSOVQVERYOANQDMPSDMZUOROGHZFTGCVEFRZZVUGNYHPXBFUVXGOROVEMMZJXRXMYRCNGTOUWIQUOYAIQRBBXRWCXUJYLNYLIMBH', props),
compute('m_13_6/10: ${c} EWGVDDZXBNQYULTLJLOQPFKZLTEXWFOBNVDVHNXWMHWBHFTVJNLRLPBGBZVSXODDCSMMCYYPQGVWYRQIDHOLFQQGITPYYKKYUQXU', props),
compute('m_13_6/11: ${c} TNCRUJAVPWROCYWPQSDSVEPYXRKPTAWLNPVRKGLGMOOYMJQDFLKSTMKMPFJPSUSRFAEHKGGTDGONLKISOYCORJISFFCXPQHIYVOT', props),
compute('m_13_6/12: ${c} ZBEVOUUVWPIAMKOSUZXZYNYHUYUGSJOSECPVOKSUOIOYATDFTOMNEZCOILIBSYNMRESEAERLOLNUXVLYMALISAGHTROKWMEGBPYK', props),
compute('m_13_6/13: ${c} YMBKATJCROAWEUOFMNAOQTGVFLGHCWTJVPJQPSHMRXHIOCXKCFPXEWNOQJEGPIXSESLRKPJPQBCKZPSDKLIXVRXXXYSVPCDWOUMG', props),
compute('m_13_6/14: ${c} RFQNIEJRDUQCYNHMANRZTERWSLRDRXXXBMGXNADSBMBDNGMRYIKWPUDTLZUYJBIXVCELJJUOGPROCRJIDGCYVPXZTYNNRTSUEEUA', props),
compute('m_13_6/15: ${c} RTVBXZROFODZSNBQHNZRCVDCQFXNJTRSYSLPRTOHZADRMKQSJMZTIAQKNKWPNPLBJJZLKIMAVKVRMTHSZVMHIWMZBVYMEHNZAZUE', props)
        ].join('\n');
      }
    