
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_12/1: ${c} NICIYAFAYWDJQCOUPWKPWEFRMSHBESKIFORPKYNLZZGJBHXOUVNGCUUVTMAHLXLEILHBQUYLJYFHFLSXIHPDMDVQGOLARDQQATMO', props),
compute('m_13_12/2: ${c} PJYUXNBOVSENTJDQQYBTUESIRMEBCFBLPIPLVZSHPGBNZBMNDPFJKQNPTJGNKUQVBWTREJKVOXWBPLFTVSTUHAVOBAPMKBHWTWPK', props),
compute('m_13_12/3: ${c} LGLXFWTQHSAWGWRXAQIXSJGRWJGJUTWSBVZKQESKDFUUXKQMHAHQOZPKTRHBZYQIIMBWLBJNEANWLEOISYGKJSZBADJYQNRATTBI', props),
compute('m_13_12/4: ${c} NRTNANJLVUEMJEUCVYSQKBMIPXEMVESKHBAGMRGKIIFMUEHXZJNPPFELDMUAEZUOWNJISHXCHABNDJTHWGSDDMNORAKLHIUMTETD', props),
compute('m_13_12/5: ${c} FTTLYTSYNZPLHJTBMMJABPWOABJZLXYZWIRRXQLXTEUYWSLWLQOEVORINJWSCIZPAKAGQHKLOEZCIHVYWFJRXVAUQPQQOACBPTQL', props),
compute('m_13_12/6: ${c} SVVLUBFXCKVPFAZIWUKCFVLRPQZCWRSQNLOZKEKAPSZEDDHDQIMHLTNMICYLNOKVFQWLRUSQZSIHGWHZRZWVDVRWKBJWHTPWJUBQ', props),
compute('m_13_12/7: ${c} ANERVTGQCZMTHBVDLLXOELRBKTGAUAEVZROHMYHVJWMBTROGCAFEMFDPGJJYRNAUFUUOZQEDNYYDMVXJOMZASTINMPNOVPGTCHAI', props),
compute('m_13_12/8: ${c} FJCVWGYDSRXHEDTOEDXHBFPMJTXOLSFOMSMHQYBGCWFGOURHOGHLIZJGRUZUZVBMENEXTNZFMVDYAPEPUQWGPIBLUBDABUHXCQSZ', props),
compute('m_13_12/9: ${c} IFCWNVLROUSABCKEFKFAZPPSGTAREZRMLRROZIJDJBFFIMCPRZEOHLJFQXGPERBAXICGRICBBAYFHXJLDZYDWCCZKLXMLIBYNXBJ', props),
compute('m_13_12/10: ${c} EOCIGDHMALKZYCEBFVNKHSZWDXFRIMFRQSKYBMSRDCLVVYRYDHWRZVTFMWCYWVNHFSMJURCDZNGZVZQJOMHSFEBKIEZIHQYYPQNE', props),
compute('m_13_12/11: ${c} BEIUQGKNFJDSPJFAJTQHDCSHSYXFRMDMMSIUVRYKUQOKRATUKVBKQREJGSYZDVTQABTJHVFYFKNJDKLSSPRFGTKRENVWWZUETIMA', props),
compute('m_13_12/12: ${c} WRCMPGKDSTWRLYVICMKRPONLJJIEMJITHCOACUTLEGTGBMHOMMLOWUNUALAAMHDKFCMEZINIDGVXRPNYDZQMSHKXKFJGYIBSQAPI', props),
compute('m_13_12/13: ${c} CGEPTYEBPPJGMEAOAYZSMHYEEEEQGFDLDGMEGDHSNCQWEYSQMOFJKCHXQIUAPUVCWVDDYKZTVOQTRTBIGFKPOWUXUOEHWKKIOMVY', props),
compute('m_13_12/14: ${c} MNBQFJVGAXVJLOIHGVLCPNUVBTMEIITHZOORMMOHDWZLLBNIKDDNYZYZCAHEWOMMOUMKWIJJMIGWRKCZKPFVCGVJRZEDZNUHOYWC', props),
compute('m_13_12/15: ${c} XCEZXJRVPODGZBKFCJVWOSUOAXYQAQMFAMADHEYAKCTVZTCAMYEEBJMTKPZZSOTNSFWVHCPINWFBDRFCLVEGOGSHCQJXJPTCILUS', props)
        ].join('\n');
      }
    