
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_3/1: ${c} BLPUHVFVYQZXPCCIHTSODIGMFALEJMMMRTYOJUBDIBQCWTGOLLOYEQEBHKNJOBNGPNWSYFOJHEHBSFBLWPAHNUWXRIZLGXOYKQHM', props),
compute('m_13_3/2: ${c} SYCJDVBDGXRFGQWSWSEDWAIKHLOBYTJLHYIFJSFVLJWOGUTRRQZDGYZWBCQRBNGTHGZJDGYPZQMYAGILHMXEJVCPUTQMJARKDFRY', props),
compute('m_13_3/3: ${c} JYOSUNPUOYNEVWEQPMQPBQFVUSBQFVJYQWDEATWHKAFDVLEWFJLSUXZNWTGGWXOLBJWCTQLIOUUPUDHRQYVKQYDKHFZFIIMGPCUP', props),
compute('m_13_3/4: ${c} CZFVSZGFKAYBHTIGXFTWBVVQHPIXRZWBVEGCPHAQFSICDJWNHFSNREYEQNAKLIVNWFPNOWQBDZIWMIPTFGCHHCIFMIXCCAPVJPSF', props),
compute('m_13_3/5: ${c} ACKVHAKKSWOPTGPJOLREQYHRQXKWWNQOOHIJCIIYZLZGIXWWPTMSQXEDEVPWQVAQNNHJIRMAJZQEOWAVMOTMJNAANZMQZUKWAQTY', props),
compute('m_13_3/6: ${c} WNTGKKBTQIYDQDUISIXUGVHUUBQMBOIVAQJXTSPKIOHYAVHLKDLVAOJKHCEDYNRAFSTQVVZVPZEDMBJYALPVZXAVXTYEBTHNZPOQ', props),
compute('m_13_3/7: ${c} AQYLZETELSFERIZWZYUKKANRRHHMXISAWHVKTKBARLCXEFQDAMFSGGJZXWCDISPZGNUEGIXUKYZPAVBVLZGSGRONQXNYMVRSGMLM', props),
compute('m_13_3/8: ${c} NQCMNONVVCYHTQDIZHAGFAQBJVIVSMRYEOJZFUEVOJIEMPFPINDDQZLIZXUDNQCPLMHAWWEIUIOHPGPBYBYAKLHTFVMAKJXILOVZ', props),
compute('m_13_3/9: ${c} SMVMDAQXCNYJXFQNSGGHQTCYCAQTIJSKZXVVLUMHKSNSFVOYTIWQTKEDIXTTDQANCAPTTEKCNTXHMTZPPIRSRPRMQIFLQRNKHYMI', props),
compute('m_13_3/10: ${c} FVHPRBURACPYVAPDMYDYGXTQADWDGPPYCDCJRWTRQMFGCVKVDQQQZXCFHABJVIHKDHOBLTABJHDTFEFPYEZLRXUOAQOYFDBALTUR', props),
compute('m_13_3/11: ${c} CMJVASNOFPKAAYWQGODWKLJEJKQOONJEVDVXHEXBENTOYOARGVTYTEYLRGCRUZIFDLVETDJQSHKOWMHCNWRPZTSRMQPWZSGZTSIT', props),
compute('m_13_3/12: ${c} EKSNWPYYFTQKBNGONEXQIQWNVCRDUPZOYFLBBJTOMQPHYBBEHZCBIBHAFTXKTGATWCTBXXFGEKKKRLTEOXNAJQKUKEWRMMHRWFRQ', props),
compute('m_13_3/13: ${c} ZTKZWUJBTAABMOHSLLFMDTYODJALCUZUGJKCLZOWXUFOOPLFDRTRFTMUZTOVTRZZUGFKFDDXXWSANNTXHRXXWBKTAMYCHFHFITWJ', props),
compute('m_13_3/14: ${c} VBERSXFWBSYRUOMMFWTVUGVYTVIRYTYVFLFZWGJMYIJJBIAJBSNVGAYMPCRWTOFVKBMJATTRHCWRYGPDJKVNYAEJQQSSOSWVDLKG', props),
compute('m_13_3/15: ${c} HUHOYLVGSGFQYXUEFMHVWFMHEAQQMPRIMWEZJZVBCNYPZMKHEKCUPGSHEOJYJEKKSVNGTEIAUCPZEQKESKUHVOGJOHEPPDZRXLXV', props)
        ].join('\n');
      }
    