
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_18/1: ${c} TFYIBLGLWZNYXZOKZIJVMSDETSSTWZKPFCDMHYVMYDDEGRFAJCGTKVRUGQOHBYKMPSHVWDJNMPGLPSDEMDBOYWXFWIFYRRPBXFXG', props),
compute('m_13_18/2: ${c} EAXNBCINZQXQVDCCXQTXVVIXALYLRESXGBQAGJCBQIHPCUXAWXEDBGMINAYLWFEMVWYNKERCGLHMJKGOBYQCUMFLBHKOEWIPKKRX', props),
compute('m_13_18/3: ${c} MDBZWQJBWEWVSXUKBQYOBGVODSOCPIFGQRQXJYCXRCIRCPLXYGQUWWTNDHFSAAQHFAPHVRSHIWGSDBFYEKIQKGUDGJICVFAFIPOL', props),
compute('m_13_18/4: ${c} RZKMJFAEBCLOLNNFXRHJDEGGLTHOZLLQVMPSRYWBMJWMFOWBHLUBFCOALIHGZGUVVVMNDNRZHMCVWOFNWGGUTXRXLNINXMPIOIJB', props),
compute('m_13_18/5: ${c} OVIHSIYYFXDKWTXWYDOKFCVBEXTEWYGNFDYFOZICIBAMHHUAVIFHWPZWICEJZBMOWIYONSPSKVZQKRJTMYHPUEAQWGLNXBAZHPWL', props),
compute('m_13_18/6: ${c} VUCHEJLZWDZUNXAOMPZVDSGBKNGRUNSHUEYKRBEZDOKTPCOSDFPWHVHQPHFQXLJZWSPVWQDINKCGLQCUFRBPMJNIYTXETRNEXDXQ', props),
compute('m_13_18/7: ${c} NZXHBFWYAHETYOZUWPSMUHRNNBEVZQPBLNVRNRHHLZPJDLKKUPQJEXGULHVNEGXKGAIZSENQFAXNPXJJTVBIBILTGGJEHBLDFMED', props),
compute('m_13_18/8: ${c} OUNQYOGPBPANDILRTXGNEBNVXOUMYNPQIQLSNTZHQILRNXDTAJIEMSSKMPGQJQYTZGGJNAOWFICKPBLRELQQJBFQYTHEXCWMWDMU', props),
compute('m_13_18/9: ${c} YWCFAYGVYLQTJPCJHOAOMZRUFJHHWWCKUWFSKGXXBQGXHMCFHDDJVOAQZZOJKRCMOAQMOZPEBQALHUGCSMXHNEAAQVSOXDXEOPJZ', props),
compute('m_13_18/10: ${c} LUOOPIGKVRVEVWISBSYGPUTAFCEXAAACGTEGBZUNLGQENWRSZOJJDKQCTMCPRCLOJWEXHQLOYZZVODPRJSJNSVNZMBYIGBVGYRAF', props),
compute('m_13_18/11: ${c} BTHCBMOYUKEQMRRMZWQFLKPCRBLCPASQEWZCUCBVCADIUNVHVPUUSLKUSPXJVSCWTHVXHQVKWJYYEQEZHWCSKLIJAYVHSSYOJAWE', props),
compute('m_13_18/12: ${c} UIHQPJOTANRAVBEGCJFGYLILFNWUMGQTIOJNOFALKAAVWPAYWNJMRKZKSVKGYGBVZSLVIGULGHSLEZVOVNHXTRRATIUNPKJZAHPV', props),
compute('m_13_18/13: ${c} SSFPZWFHPKGFRZUQXTUZRKGVWGUESOSTHVBVDMYFTDEOTBRIQFHTZLCFZTUERBTYBNKAFZQGGVBZTETEBFKBRHJXXOLBGPQQWFPF', props),
compute('m_13_18/14: ${c} OJVFLWFYFTUXKFFPRTVXSBYHTBNZVUBSWDTEFGMYXWAAHDQTAWQCHOYLKJRADPDGAFBYTZNKJRTWANAVAJWMPOFUWODFJAIHVTOI', props),
compute('m_13_18/15: ${c} LLALMBNNAZLYOXWWPNZIFIITBCFVDJKQYGMTAXSDNRZTCAUXSKRVNTVVRSSPKWQFQJRLWGHVPAMFJJBKJSHNYYUKQDMUKUMJLSZG', props)
        ].join('\n');
      }
    