
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_13_14/1: ${c} FMNVEXMBYSHHJHXASSWOKBIMXVDYPJJXHWTPPWYLYPADKGHTEMUDPNWYFHXRBAOPVANRTMFAJQMXDGLRZWYHGMPROAWJAULZUORQ', props),
compute('m_13_14/2: ${c} SOBLYNSIGWNWXTOMQBJWPAWXYMZTPFWEHRQSTYDUSPKHLZVXDAQPVAEAYUZZCXUTAZLGWXXNUBUBRSTQUUOJOVRSAQJXJCPCFWSX', props),
compute('m_13_14/3: ${c} PKCPDIUSYQMQQFIUOZNNTIROTOALKZEMUMQLFYHZTBBPWIPFUICHLJCUNYRQJAHXWVVBLCMRRHLIMGZJNKCFYOUYEQICCAEYBCGP', props),
compute('m_13_14/4: ${c} WSVLPHPGLYQRAXIXFOXUPAQMSURKYEUOZGSOZWLHAIMVGZQGRKJBBHEXOPPNUINUYVVAYFVLNQKSSJFRQMCDMVTTUTHIGLGPNWTY', props),
compute('m_13_14/5: ${c} KZHJZAEGEHHVDRMSCVFUAZGQWCCMHQGWWPQRRVJKSZYCQTJDBXJEAIWXAFUTZSCLCQKBZKIYZUSNGNVVIJQQCNCLSMTHGNEYKCFK', props),
compute('m_13_14/6: ${c} KHKQQQAKUYMJWWIVXQJDOEJFOEQGVFYRKLPCJEZGHVPNAQPJCYAAZRVXWVGIPFOAYADHODVHZJNNDHKFLQAAGNYNGPLDTSYTEHCC', props),
compute('m_13_14/7: ${c} PBTXEJKPEBQSVNJOSMUMCPPSQYOJUIIXTFUJUHSIEQJRHKUVHUVLMANNMGHBALBBQZYMQFLUTADOZYMJTMULJMHWUAFFXRQPWYIH', props),
compute('m_13_14/8: ${c} QZAKKDEQFBZTSPGGVBOBKQDPNGPTXNVWKDIVVULALQTURHBYHMOGOCGWUNNKSYJKKBTYYAESNYDBADDZYBOXELIPNGLJMRZEYESY', props),
compute('m_13_14/9: ${c} CQETAVPYYAAOUJTUDPJEJGPSRPZDQKWCWTFRZOEYBNVQDPJZAASNBFPEGOVEXTBLGNUZJTIZIKOSVSXNIVFSNTYFLLTDBRTLZAHA', props),
compute('m_13_14/10: ${c} OWUUMMNDDTVEMZSAUIVNHQIJVDNRCCVKAHFRNWYEQMOHEWHFKVIBAPTITUYSQLSAMNBHRJUEZOZNEDTEAACWTEKOXDWTGODHZYCF', props),
compute('m_13_14/11: ${c} KAMGHNPIKCTFZQDVPYCGVUXIDRORHEIXPPPIOOTEJQUAJHKNLGJFDHONYDZOZIYCOIHBNGTMKGAUDITKETIYQMEJMWLIROVRPWIQ', props),
compute('m_13_14/12: ${c} ZPKUFAIHICPVRDPPZJOBCAHPOAQYTNQCQXJACHDYFHJYMEXFHXAOJTGEDPENPQXAFNTUTJBIZQSLVNRFKZOXBIAUSBSQQWMSBUMY', props),
compute('m_13_14/13: ${c} ZRFOXSGUNROKYSASBLQKLZYUNIEBQWCWPZQJMMXBRSXNRNNJZYVYEVFNSUXACTROBNWDIOBJGKSQRHATUZWIEVCPOCFAAWUEUSCJ', props),
compute('m_13_14/14: ${c} JCGYHJMBKBTNLNKDOVJXISUKLBYHOYDDPGFBVOINWOPTGGCGTUERWIXZGVSZIZLPCIZEHECDIYLIVVFFEOAZPMVKBYIVDLRKANHV', props),
compute('m_13_14/15: ${c} XEFBCNFYTFRTCVAPTHVWRLTFKBFQRGLBYEWQMTZRKVEUIRAGRCTKVALOLTIKMTAQQVNCGKMOPDDWCQGHUQZGLRHXTEICZERINMWG', props)
        ].join('\n');
      }
    