
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_14_12/1: ${c} PWUCVEFPDPIOVIQFMXRVEAQDXEWBHTPSQBCLTOZWRSBJKSIRYMHVDNRGZOSLBGISSEIHUEFUPHHLIHICHOFINCEMPAMPOPWEDSLH', props),
compute('m_14_12/2: ${c} IZTTQQOVPROYKAVVFELLOCOIAQESBDKQJENIORSMSAOOMQRGPPZRJJLOAFTTCYMMZCTARHDOVSOQYMLJNAMOEROIKQVHIILDLFAI', props),
compute('m_14_12/3: ${c} MASUQJMJIKCMITNPURIXIYXWAOQEPBJDAOHMTJFEXUUFANWHKYBHZPVKKZCKWSLWCKTUJMSOJPPFUQRBIESPTGKJUFEQTHLQTXQF', props),
compute('m_14_12/4: ${c} ABKYSYDMNEWYNTXMYJNIKMIFIRJNMPWWVZQYSRXGAAHBBPOEILXZTWBUXNGGSMWWKWENDSFCXEWGUCPLVLOCMLTFODKNDJJCUUTM', props),
compute('m_14_12/5: ${c} TZBHHAQUZHOBCZZHQOWKDVGCYYACZJRTGGXXSEASFIHZQWSTRSYNSIJIWYMQTQBPDQIJKWKDYEALSTVTJOPZLRFYAZYWHTNNOYAF', props),
compute('m_14_12/6: ${c} HBEKMIUTWAJWZFNYGEQHSPVJYDMMZYAXOJHIMSJEAQLCHYKXEHUICTVDRBMTVHPWVRIOEFJUXBRIDYEXJDXPXRZGCXJUXSESRTEP', props),
compute('m_14_12/7: ${c} XCXUXUZAEDVBYMLLKJSFISSDMXRISVDCKQPZMMLXICHSNDGEJJIPVDXJCCYCBYFAPRIUTVCQHGKNZPXVPDOMCBAGSMKHXWPPVDYU', props),
compute('m_14_12/8: ${c} MZUNXRMNYRYVGBHHFRSHXWDXQDRVVKJNFGXRZTMRIGPXDQRFFXXGCNOVQBNYBOJOWMZOACLHLQNQMOXJLKDVSYMDMQPQMJNBTHOT', props),
compute('m_14_12/9: ${c} RMEWVTCQXOGYWEOVVTNFHXKKHEWCAMGSYOOPEVECTSJUWWLMMQCFLQHKNXVBCXAJMZVPZFWCSRWYAZMWLQBJBRLTVWXZDCIWCGIP', props),
compute('m_14_12/10: ${c} FMUXKRPUEVOCIWFEWBJITXCROGQBNNFZGUKJGHYETKWVZJGBTURSWKOSBQOAOEGFPSVOGZXSDCUTOAAANRFLWCSVURUMPCDZQAQJ', props),
compute('m_14_12/11: ${c} HGFZMZMIFQSOAVNXJLQESCEPONUKTNBFBHGAGQFELPDRLAXYZWRXGKMRWGWBYABHGJSDLVGWZFKBWPOXHRDOUWACETJTITPFWUPF', props),
compute('m_14_12/12: ${c} KDDQGTBQWMSPABBIQHFLEFUCCYDQQMEJMJBOTBLAMWLRQTRAAXTKCMGLCQYPMFPTQIUDTBHIISNDVTBJPMBAIXDBAJEXCYFIPYDF', props),
compute('m_14_12/13: ${c} IWSOKBARNJTVLCEGLMOLIHUGXXCTGCLNULKEVYQWDTDFUSHZUWIGVBEAZGLTFNHHQNOBUFURYHYBFMVZZNLMGDESPRSXFOELYOBL', props),
compute('m_14_12/14: ${c} EGFSFHGMGUYRMEVCNREAJWYLSTIMDFBKUBEWZYILVENXWNNEIMNMSQZOPARHOZLCDVTLPNPJIRMPFQUUGLJATDUDSFRHOCKPDXFI', props),
compute('m_14_12/15: ${c} VXNARGNRHKVMYNBRPJRWECRGCYFBSTWDFKTEOOVGPCTXNYLBDXYWQYPBTBLCHGYONDHUHBZZYNMGUBRTJQFQMYLGRCUADVDKUPTA', props)
        ].join('\n');
      }
    