
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_14_19/1: ${c} HDGPICNNADOVFQKPQQTYIVCLFTJTAXTKHGYNPOLPQTXOVORAHZPOCVFSCEJBZBNLSWRHNOISOIJCVFLYDMAGNUYSJVAPTWDLNJPN', props),
compute('m_14_19/2: ${c} UTTNJXFOAMWYCAIRWSWROKHFGXOXFOEKEIFCZESCXRKFKNKGIOGUBENDDGUOTTQRVYKBBFYLTPTCAYSSMLKPZAHAZPLBRNALCHJF', props),
compute('m_14_19/3: ${c} PIKRRZXYAQELMWTPALPPXWHHJYDQMDEYTENEWWRHQMJCVEEMMOKYARCCSVJSNHWVXAKXENGDQSGSFWPRDKVBBPAVLHFGYQUYNCWJ', props),
compute('m_14_19/4: ${c} QGYAWXVTNEYUQGEKLKUQJCQWELTPORJVZBYHCDQFOXMTRHRUSQZJDEFBIQFXYZYVOQWZNJYYTTZQBAJVBMKLDDMBMRMQTVFSDUND', props),
compute('m_14_19/5: ${c} BVSLRCMHQKBKSTEMFMCQRTDBKXLSVZHEGLLYWPQMTDXVZBYXTHOTEVNMLZZHJGHIJLCNXOGWFBWDOIGWBAXOKLTZDLTKYRPXVFKO', props),
compute('m_14_19/6: ${c} PXNPUTTMZDGJKOXPCLYJEFXVBWSFSSTAPKLRKQLQQHBNKERJOGDUJBVFAKDDNTFENYSUNSUCJCYDPIWGYGWNXBOIUXBHQHUWSWHO', props),
compute('m_14_19/7: ${c} LLBNMAXCZJOMINBTZDUPROGAGEZPIIIOGJGFBRCDZRRQZGWURTZXFPABSZPACHQPUENECDQJAMVXMDGXFBDHFEANYMELXKSNCRSS', props),
compute('m_14_19/8: ${c} RTWEAAPBMGTQMQRGAHEZCEMOGEKISFANBPZOPIJFFRUNPXJSYGEFBADCWARADRMVAUNKXWPTJSEMSSCYEUNHCTPJSDKGEQBRPIBK', props),
compute('m_14_19/9: ${c} CDOZQPRHVXBXRSVCJKHFBKHPKIYXSZRUTGULQHLVXOXAJGUZQUFCLKHDGBHCREZTMEAJBWQZLIOXUBIBNDIONLLRCKFRPOZVRBGU', props),
compute('m_14_19/10: ${c} UDWTCFXILIVXSMTSGKACXUIOIRKBJYFSMXYZWKKPEKCZDKVDKKHZVOKELNDYGUJZUYPQDXHNFEJVOBTDGYJBJDXUDURRMUAPRMVC', props),
compute('m_14_19/11: ${c} VLRKCOGWGNPHYNLROZEKOBPJYIGPINRLAPICMOWLMUYPMJJFJPEUTDZORWNTZTUPDGULLXBTYLZQVQXVGPCZNPYLNWVZPBDTOGXU', props),
compute('m_14_19/12: ${c} KHFTFEEURYHAOVNCAGEZVKJLMGVORYOXAJFIPSOZYNGNXXICHNTUIDDJUENZACRUBOCFWHVHDJIZPRBMCVEHLMHSNTHLSPANNSNO', props),
compute('m_14_19/13: ${c} TWISJBHGLKHCPAGMWYCFUBEJBRDJJRJWKLBWNZXGPXMILNMINDKVHQMHNJTMHIHZAPPPDMHRFYIWEILWVAAKWMMABBVEYLDDNTOD', props),
compute('m_14_19/14: ${c} IFTBRPYDOHYIVMEPUXFLELJSSGIFJHOKGKTZCMLWDCPCQYUJXRCDNRGRKIMJUMOQTWRWGBXANFUOZXKJXLADGFHSJCTXAQQVRSPM', props),
compute('m_14_19/15: ${c} YTAIBQQZNPHYWCOCOUAUJVHHJWDKEEYDAFASTRDMNBTWWWEBKVVFFZIIYJMSRQJXRDCMDDQRGMTSNZJCZCPFJIVVHCUJQONLIEBP', props)
        ].join('\n');
      }
    