
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_14_10/1: ${c} GTQYGKGCPEGTMYUEWLCJCOZNCXWGGEBKQLLCTEDIPWFZBMZEUMRODORPEDVICXDERMCGXWZNLYWZTYNUZWVRTXYXFXWBOUPFGDLL', props),
compute('m_14_10/2: ${c} XDEIOWFTEEKCIXFSDENEYINAXCRFIPWLBUCMAPVZGDVHGYVCCKNWJTCDTMRILTYGVSNCQWRWXCCZJTCPJSZITYIFSYXXCHDLHNVK', props),
compute('m_14_10/3: ${c} HFVYLRYLJVDFDRSVNHSGNZQRYKQAESIIBXWPLNRAYURMXOQTMNTYVRLTRCVUIPDTWAEBVQHVCUVTLDIVSIVIAJMCTWSYIPMMWOEH', props),
compute('m_14_10/4: ${c} JTZPFEGPQLEGERVPBLKBZAOJBVMPRKYOCTOXLDSJOGIZWWGUMJCFOOCMKRWYVRGQHIEAQMHCPRAHNPSPBIHTXWFZMSBYCMNHLXKI', props),
compute('m_14_10/5: ${c} UZNLKMLXLAOPSACEYWSUTVJHSSBGGJFHZGNZKGQQPECWVTZQAVADHMJCCSJKIVNPVFJJWISMOEHOKMAASSZQGAYMMRSZHQMSUCBR', props),
compute('m_14_10/6: ${c} ABZZVNNGLWYQPGBNLQBYUVYHVUKGUPWAUNOFDOVWGKREEQXDBUVZRIOXEEQEBOBWHSOOWLDYPXTPCUPVXPROWISDQWCSNCMWVHVC', props),
compute('m_14_10/7: ${c} QZFFPVOKPMBPAWLPGBOYQWYFFGCJZQEVHDLMIRGUWWXZRYFQRYOMOFWIXJXWUQZGBFXZVWAPUYNHTYVUGHUYDOCKPQFNDZMLCLFV', props),
compute('m_14_10/8: ${c} DNBMVDTFSOVFTYKDTKOSVDIDGWJNEWWNZJPHZPLNPZBJRMQXCSNPTJNREGNIIESTQYMAPPSKOFHRUBTWMVPHCRDDSLXIJNNTELIJ', props),
compute('m_14_10/9: ${c} ICNGJKXUQPOXXWIWLQMMVPTIOUJEBTBVIRVBGCMVPGLZRQOPZWMOSMZWMXQHLNFXSGSABBYKAAQXPGSFCCUYTCQMBEFKROOVECHQ', props),
compute('m_14_10/10: ${c} MMMIAGWREQERUCAZMXNXGGILNUDIDWECKPYNTCNJCYMZRXAQJPROFKNKAOLWKUBLQYKUFLTAXJAQNDYACWMKFRTEYCKOQYGKZHJH', props),
compute('m_14_10/11: ${c} TCOXIJFQUBFLFTBVXFIRJJFHXZHAFNVGVWRFRAFSQANAESZHXASEEFMSQKCEJAVPDUNMLWHXHWWDJTGIWSELTCFDHXQURHSENDUZ', props),
compute('m_14_10/12: ${c} LMJAHJVMTRYAYQZAFROHXNXYALLRPKRIRYLHWKCPOYKSGWLNGZRBYMVHXJNHHGGBFCINZOUFAPENBVZMPOCRZOSONAYZARUNXNYH', props),
compute('m_14_10/13: ${c} VBYKITFIQPJAWOEWGNXEOVTQEJPFCINWTNPXIUEEBWRQJHGNBWNJAVWXRBJJJPSZFKZANQBVQUYEGGJMEOYGIBDKXKFHWHQMPHZI', props),
compute('m_14_10/14: ${c} NMPACCIDRSIHLDAYMZMNAWSRWNSMYPQPSSYZAEAOWMTJTYSCSLUSRKJJCKQIXZKATQGXRWTMRADZPIYLBRPXMUDLUWTKNVHMYHIS', props),
compute('m_14_10/15: ${c} GVAOBYFMNXXNPFUIDXUWJEUWXSSGSIBGILEKGHMCWUYELQJLVHAVLDDYFFAQSUODYHRRNVCMYRJNFQPRQIVPSEIDBCXHEYJHQUBH', props)
        ].join('\n');
      }
    