
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_14_8/1: ${c} PAHEWGSBMZPISFPDMCIHDQKNHLNFPMRMUESSWTFOVQMPYWLPTWCTCZJOHKDGZXICPVGWJSNKKLQTXQAOAIOSSCXETOQACKLYTXEN', props),
compute('m_14_8/2: ${c} AHAIBTWBOUMQHWPZPBPCTNVDSPNKEHNEMHULKCNHZVGDVVDNEYEQPQWVMSBECDPLMYBUYGUORYDURAJIGSPNNHXYELERYTSVYLUI', props),
compute('m_14_8/3: ${c} TJGNWFWRPSCPCXCNLJYOFHXCEEBHBIPFFDQIHYQZNVAPQLCNBZLGAYYBFOHIANIDEXMBYHEXPWWFANIOJLPNRUUXZQUTVQDSJCQJ', props),
compute('m_14_8/4: ${c} RBHPLBMQWWBWWQZEWSXGIOTXGQRTIGKOQQGWETRWITLGNEGRPASMBKVHLIDECTUDXGKSZHAVBQDMPRVOXMFOSSVAAGAYUBMLSMLY', props),
compute('m_14_8/5: ${c} URYXLWDJEVYSDWRVGHVYQFDWRDTYANFQEDLGMVOBMYGDIYFZZLVIJGWMSJUJIUYGGBSNZWNFMTDBXJLNQPSXTXGPRRNJEKALDDXZ', props),
compute('m_14_8/6: ${c} JZNIDYRKDKROXAATJTGULPZMCTZQTKWEOOKQHDJTFLRZODFTPDNHCMRRHGDHZXNNIGVDMTVYARQMFFFGTIXVSYFVXXLNSBWHPEBM', props),
compute('m_14_8/7: ${c} JKEFHVPYZSJRDHFCHVDYKMNTQMDDVNZPZMULWJIDUSHTZUIQSASUNLHQCHEJKUXYCBMDRDKNMNAGNZTDHGKCPCCRQSKRMTHWKWYF', props),
compute('m_14_8/8: ${c} ZIKYAGDEQQKNPTIZUDJJBMTFKZATEVMVUGGJUQUUPKXEMNPLPKTGOKBTMZSSQRDVQDFEPLEGNUOMRHVDLCKKZRKOUYMKWWYFEWWN', props),
compute('m_14_8/9: ${c} YGMXIPHNONIWSNYJEVBMBUAHOCTCBVFSFAETSDQKVMRTGKWQSBACQBSVKLVQVKRVHIPBPZQAYNZESKPYZEGDESYAKXJLTRKVENCC', props),
compute('m_14_8/10: ${c} GVXIHPQSVDIZFPVHBHRFLEGWNSHRIRRAAFTUBRKTHEFKAYAQKZMPITCMEYVIBXTNNARSCJZOLQEHLOIMGKQJHZHAHSTOTLMLHAXL', props),
compute('m_14_8/11: ${c} KCMEDSDQCYWHBUNLFAYYGVTMHZWHNSMXUQWBLRJQRTJUIKKREXSOYLOFZUNHTUTWSXYNLUBJMCBLMEQHFKNJWGEDNIVPTKQFRRBU', props),
compute('m_14_8/12: ${c} CTVWJITXXVDHBZFOFSTFHFEZEHLWPPYBIAJZQUGRVDCRTWHDEVISLIRYYBCNKVOGKUWVHIXGAIOBJZKYUQNXLKWVOSYDUWZGQUDK', props),
compute('m_14_8/13: ${c} TQQLEZNCLGSRNMZJOALAWMFSNLABNZPOBDTIXSYITDHFWDXSOPHURDVQOHVSRCMBECZWTNZVYRYGHFXUDNNFYEPLJHAKIUMXCMQM', props),
compute('m_14_8/14: ${c} DTBKFREOITAMFVLMXKXVFTBMJYXEAQTAPCZJTCOMBGXMSNGEZFXULXQJCMCFFCHZNNDFFNDEOCCUZESQYPQHRHIMZEVFOVCXRJRR', props),
compute('m_14_8/15: ${c} UALDFCANWVIZSBOEEXQEGLVGZZMZDAAJNICEYJLLKDVCFBGKOAMUGRYUHEDMPNCPLEHRWJEMSNQXSLPBAXCFFMEYGOBPIHQJYWYI', props)
        ].join('\n');
      }
    