
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_14_18/1: ${c} AYOHXJIGSXFRIGXOOMUJIQTRXCXARMJQGYYMKEJGCQVPUJYSLRUONKHKICORKYKGCDTXZQUZOJGPFVQFODCCYDXMGCUYTZOSPMOB', props),
compute('m_14_18/2: ${c} MLVJZIXVGHYZSQCAANQDNQNKZKVMRJBKMLTSPRZJZEJKGLQXFZRFSSRJPDWSDYMBNNNEYVTQFWQUGNRFIUYERBWWOLUYJHOBVUME', props),
compute('m_14_18/3: ${c} XJTGQAIZWIUZQHRMBPQIKXTDXGUAIJRIAUSSMUQXSOZDVLIDNHJBWRIJIKALADBDUOUJMLBFBMLLMOSZCSMQCJFFVXNIZZNDXBKF', props),
compute('m_14_18/4: ${c} GIJMSEHOUALPEXYKDBWNZEPUJLULPKEFIUXYCZEMGFOFOTQWISXHKTPECSZAPVGMKXRLPDGMYPQDQALWBZHBFWIDCZAHBXENHEYK', props),
compute('m_14_18/5: ${c} LVJHIVOMILIPTSSDYCDLSBJBOTIZRMGXPUSYEBQCXLZEVVYDFJGPWPOMPROHIARRKXPWTFRGIHUNPJKMFVBEBQFTYUECBLRHHMWD', props),
compute('m_14_18/6: ${c} JICCTOUXGEOIVTUAPDSPUTKNHSRNLWYDNOZRGZGBWVDFUZLTUVROPHYFCQMCWEHXBIWIQIYIOQGIGVZEUUHKPPEVDKBNIEETWAMS', props),
compute('m_14_18/7: ${c} ECCVNZKLITPBPYFSORQUQVOIJOZQLWKEWDBTGVELUBKHJBALREKCYHLNSCJCGSWCEFGCFFUIMAQVCYSKFKJBNVFIWIDNGSTPDRTD', props),
compute('m_14_18/8: ${c} TWNTBLVKCWRHWYEINONWPAKZCAAZEDTUDMNOQZPHPGSDDTNPIUSFVJKQQTQMOSOZTVUQZIOEUZTTRZIFBRFPFSJGFBMKGNAXFGSM', props),
compute('m_14_18/9: ${c} JBBLNWAWJYLDUYEVMQOOFXTVNKRRKNRUKIIRPXRBAKRBSCWKREGIVNDSGFNZCUSRYLPPMFBXTRZVCEJFZPSXYGTGALBSPUPZQIUI', props),
compute('m_14_18/10: ${c} UBGBPYEEXTZJXSJVUIYUOBFILZMNPIHCUTPUHHZOPDEHYUTRVUBAGHZHHKBVMVFQOZZEDJIIQJWPJEYPGAJTWGLFKBWJZHPSRJSK', props),
compute('m_14_18/11: ${c} FDGKDWPGBIVEUQMUGZLNWWRMACTZEFRWJZHOTJLAWJGGWHWUYYLQFEEZAHGKATBAUXULGNRZJWFYQOXTOVLZCZUPWUCUOURKLKQZ', props),
compute('m_14_18/12: ${c} KGHTIBOTVWVJOUUGWREPSLSUMDZQLCWCKLHEQROBZDKBQLDWFLHOZDSSRHCNYXTLSZYLSKYHXWCXGRBSQBCFTURIKOQBWFKOCEXR', props),
compute('m_14_18/13: ${c} PUGDZIUVXCNZAAYLXOFZXSEAXJZPXBKIOBCTBKWTAQICGSFEJYDRENDWRIUPAPTEYNYUJEZIDODGDEUIINZAKVKSAARJHWOLLMLW', props),
compute('m_14_18/14: ${c} CAUSZDBIHDZRQUTJVDLTZUHDTXMSLBQKULBJWPGHKOFILUZTWDAFPGRPUOOBSHEUWLKZNJPPIAVLZJRKRJSRFIMOFXLOOQQYYCJG', props),
compute('m_14_18/15: ${c} BLWCYZZBTCBJOXZWERSEKBSQXREASNQSTCZCVMRCWQYJHUXJZDMMKFHWKUHCCOEYYEQANSJPKDJVAGCRQNWVNSCBYRDTEOWVYFPU', props)
        ].join('\n');
      }
    