
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_14_20/1: ${c} JPPYZMONVCINJPWTBMHMQCFEMRBBLJIYTUWGBLZILZVCWJKSVCBXLYCCCFCPMLECSQRCSXMOTXXQQVIGFFWFDLPVNWGTNFVJIPGB', props),
compute('m_14_20/2: ${c} XTDIVBFONSXFBANAKNSRTPLYMFJYPIHRXYMTZGGOZSQHJRUTECXTBIMKFKORUBBGBRQBTLFBYSZXYXPHBNBUSYPPYETCUKWQEZYS', props),
compute('m_14_20/3: ${c} WLJTIVDRLFJPUZZOLSDINKSDNXIWYHCBYBAFTLLZSYFBYWTYYVEUVKFLUSFHAEETDMOFUCHTIUPILPWMNNUWICGAYBXCLGGSCHWD', props),
compute('m_14_20/4: ${c} CLXUIAHJFLAEZBNMLQUJWGWKUAWBHPJRCIOQKOOUGLENSQHEDBRDCAXBMOXRESIDZHJLYNJILSOQXRYGBPYUUITWGVQMHCZKOGQC', props),
compute('m_14_20/5: ${c} WRKIZIKBNJAPKWCBARFBJSRVUSMDAGNNRCWPEMPIAHFJTANXIEORBBPQVBIJKKDJNPTTLBVFHERVNDNXHFWDTXHAOCMJZOVEIQIY', props),
compute('m_14_20/6: ${c} UNAWHLUMSWPZCXGVHUDSNLAQXCBRYJXGKCTRGYPYZUUDLYRZXLXUZAFKFECBFKWYCTEEFLYMUHLDYSCEJJDUGIVZHEGGMKKOXVUO', props),
compute('m_14_20/7: ${c} RMGOQOSKRAFXEODWXHSZWEIYQAEIHOBUAZCQEBESYVHYXTDUARHBSDEPORMPQURXFMUJHLWCCUPKEQEKGJSGHFFHLSDOWHJKXDEB', props),
compute('m_14_20/8: ${c} YPTEMSFMYEGITIIVPCQIPKTGQMZXKTSGCYUJBELIRYUJGBGFUOQVVLJLZYLWHFDSRVCGNYIQHOZHFOVXONIOHOMPSBAPBPQBMITV', props),
compute('m_14_20/9: ${c} BWEEKEHAVQSYHBOZDTVHJGLZWIYKRRRSXFXYPRNVAEYFEIKKAYYNDYPZWJLJQBSZYIVFNWDUMJGFCRRINRTYJJMCEXPGWBPRVQMC', props),
compute('m_14_20/10: ${c} YHYMBEEXSDNPTPFBVLTXBCLJDAXLDHOOVEJEJWFXWNZWGDEYBVVBZUPESEACVHTRAZXKCLMXZMBXQXFGCLAWMEVEWNORVSBZZYFI', props),
compute('m_14_20/11: ${c} XBRRUAQTHOCFAGALNLTSKUIOWIRWIUUTTNCYTLSUXAGQXAVECAXUZSAOIKXLFUXFZLEZVZOYSJXVUGPGRTWLJUTDFMNQYKTFDSCS', props),
compute('m_14_20/12: ${c} TLAJQNVTNJEOQPSWAQIAWBBCACTKTUSCNMPGDEFCRUIEEMQYRPMXHKFNKXVTFGLMKLYORMBLNPNITHDNLIKXGLWCMENGLWEOWLGO', props),
compute('m_14_20/13: ${c} QTDUUZENSPNHKRWIMBQTSXWGILMOLCGJCFDBOLILNOEGTZSIBFDSNYOGLHGRHQNJBKVWFRSSIODFGDXXPUUTUSOMEABESLUOHBZQ', props),
compute('m_14_20/14: ${c} JCSDUOQIIWGPYLJEMKERIYBDCWJPWKDFMAIVSGOPBPSRQWOADMPGUJHSTJFJQVOYERBIXLHYJZILCSSHBEAQICOZBLIQIKWJBSRO', props),
compute('m_14_20/15: ${c} BLQJFLISERIOPWAZKMNGRKVENVNJWYMMPTLEUURQGJCFKIGIJOVVMEZXJGFDXWGPUXXVLSTDREDGHKKOFFFCCSORNKPYBPLEFKOO', props)
        ].join('\n');
      }
    