
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_14_3/1: ${c} BRXNSRCWYJBOTETNNRGANOSBGQYESEQHTGZHYORQGZGBORORLDEKHJPNMJDFRTCBMUPQLXIHNBKUFTMUGTNLXASQSYDBYIURUCNG', props),
compute('m_14_3/2: ${c} ZXNOSJXNIOZAXNVRGUUCZPYJIRIZJESILCIMSGNERPSUXDBVNACLJKDDSYHTCRRDXQKZLEWDPRFVNBHQEJYZWPCJVAGTZVHBVUNN', props),
compute('m_14_3/3: ${c} CHASQACVCFRUEFBTOAWPVHACKLVNCTPRXICJWCLCZZFNIMDGULSTYUCGDZIZISXRRBLDKHTAAGDMWRPTNNBLNTBZKQXAHPSHFZTZ', props),
compute('m_14_3/4: ${c} ACFLQCCGMJMTVLVHIGZTSGRPIGQMXANIYKYEEFAAEXTKPLAUBBYGYDKFJJINSNEKOCDGLVYZOOVCVXHOKGUWDDOISXVFBBDDFGRS', props),
compute('m_14_3/5: ${c} TXGGOIOXARGLYZKJVKSZTFHZAWCPWYLAMOGTDUQJUBWDQONCMSLAKWKBZXUYRMLNKEPVYJEQNTVSNXAAEKITODQEYARVGMOSNALE', props),
compute('m_14_3/6: ${c} IWOMMEDYCYFHJOBVOOBQNLUULUIKZKSJDSLWVUUODMUONTPRJTBCBANQWDKULQUYRZONJXLHRLPOWKYSRZBTUSOSTBTGLJTJXGPH', props),
compute('m_14_3/7: ${c} QJDXSDEAXRNNIVGMDUIUVHUQBHPPSKNFRONTCKMIWPGWQRXZCDMEQNDUMOYTKXGJGUYKVBSKTXIPCKZQWLIZZRRRHSGRCAJXBOVX', props),
compute('m_14_3/8: ${c} RQRKXMMCRTJRPFCTLNUUFJSJAMKARNCNUNKUXUASKJZBEEUHPRFYXEMFKIURBFHQRKWHAYEVLOOCVUOGNEWITEJWEESRBJDEVOLR', props),
compute('m_14_3/9: ${c} NKCLKEQGMEZJJLCBPKMHNTPENLLVOOZVPUQHRJABJYHYVARCPYIADEZCAIWFETXUBBOBWODTKANWEDDVEJMWFVQXVCSRUNPEMAIE', props),
compute('m_14_3/10: ${c} WZXPQZKRYOWMSNPRNWLENEJXSCBEGDVAGYOJROFWJHEGZVYMELTVUSEITKKBDSHVVRGVPLPQDWCOJKQANYXIXNFIESWUPNPFGXKK', props),
compute('m_14_3/11: ${c} IMDEMWWPPYFZRKYLKQBARAUUXERDKOFWXOZUWUNMCGPDGUFDRVGLZCXEMPLYLYLZDCBKZWIXWBIGLQOBNHPCSTSQSPYMJPYCNYGH', props),
compute('m_14_3/12: ${c} ZIOFTXCUUGFVPSVWBCBCGMRFTUAJJLSEYIOIIVKSHDBVVUVKEBRXAGJVSHNPCYTNDOXEXXZQLZHJPWQJODRMMRPOFYRTKFMWOLFX', props),
compute('m_14_3/13: ${c} ELZEZRCCSWYMBNIVEDSFTYSLLKZLQVFYDGZWFPUEXONIKXSVIBXJRKZQCLCXSSOTXMVVHZBOITJAJBIXSROMOVOVOYMILTRGWMLN', props),
compute('m_14_3/14: ${c} YJBLCESEYTIXHEVUCAGUCYRDYTAXSNMXTBRDHUFYPPFTEXORCRKLWGBXLOXUTTMHVOCJAIUNVCJTPMPZSBCMFBCABIAFBROQQRYG', props),
compute('m_14_3/15: ${c} QFTWWKNXKSSCOWDJBRDVVHZVJYPXZAYIJQNWSOXMAYTUDLESRPDRFVWWDWIQDALWITQLEABDPHABDBKAXXVIYANQCUSKLDQFVSAY', props)
        ].join('\n');
      }
    