
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_14_16/1: ${c} BRMUZCTOJETNLNUFBWXZLQVNVRWZEJQFUQDFOTKERQVFRMCMUYHSSWMJZTLPGXXZUASRHLFZTHLRUDDVNBMFFRSCJNBSKMZRTHMJ', props),
compute('m_14_16/2: ${c} RCPAVTFRGPFEPFFANAYHYMEJIXCFWYTFXNALZSCFHZPYTKULTHJSDBHHEPNNMAFFXQHJXPKPILXTOKVOGQRVSCBPYIDSJUWKOTYM', props),
compute('m_14_16/3: ${c} TMHGWBSXVRBSMJTIHKNNBGNACIUYLGAOHMQKCICSMZPADJXIKUBTEEQNQRSBVOLRNOZXIDEGQLGXXCDULZOIUTELZMILXFHWVGBB', props),
compute('m_14_16/4: ${c} XNPBVOTCWRMNSCFMAFYPZEXNIOMSCKLCEIVTXJTJPCRXOVZCTOGUZVOOPTBYSOFKMSORDXAVEQFVAORVESQIWMPWOYFJZVOQFVVN', props),
compute('m_14_16/5: ${c} XMZWEUZWGQMAOORUPAZVUCRUGCLUMWBSWQXZXLEWGDGEGVSYGYOIUFQXQMLDUHHVRWSMHGYOZIJJULVBBBQJGZIAUPSNFGOZZRJC', props),
compute('m_14_16/6: ${c} THXHNNLFMSPGEMICZDGDGDEYQMHPKGHRHBDWPMCULXMQAZJZPTXBDQVKLRLQOFOFATRDEMKJTEKTRJPUDLSGKOCNTJDDYILVIGCE', props),
compute('m_14_16/7: ${c} AHRZOVEABXHKRMCFQOSTEMTTCZKWNZLLYATIKRBZLNUBIFVSZTQQHOQLIJNZKZRYTCUUQANUZZSLKFNKHEWIOWLPYTENDIYKDIRJ', props),
compute('m_14_16/8: ${c} FWSRYSPYAASACZMZJGONCAOTCMYNFWFKLYDZSFJWSEUZLFZZZCLDIKDIIJSEHHIDXTGPVFKCOBJRCRJBKGPDUSYWOQSSIFALCGJU', props),
compute('m_14_16/9: ${c} NDRZVXIAOIXCJFKZNRYTGDCRRFTMFLAPEGJCLTPBRNYJKGQXIVESYINQUZGRJOJTGYPFOBINWVPFITQQLOJGRYXBFLBESPPFHWWH', props),
compute('m_14_16/10: ${c} TXBDHIONTRDQRQEAEKMLLIJPFYDROFZOREOYMEATCNMBHKPSPQUELZCPHLDSOYMONKXCDYCQXYKFOLQEQTPQIFGAFMVUEOMNHUNS', props),
compute('m_14_16/11: ${c} ZZCQXEXKSWAOVVRCYOIBSYVPXGPROSNDDUKJGPWEMZWSOOBSSUAFCEQHIMQEIOMZCXVGLDMRCBAFRKXSPIXNFLCWSTPNIJEIMIQA', props),
compute('m_14_16/12: ${c} LVOMXGQIKTTCDLSINTSHSOZQHIZIEEBIEYHBHONNKBBDWPFAXSCIYUITSWCPHXFNIWYHEXSSXCAKFWBZSGGXVJCBNLNAIGSAOVUV', props),
compute('m_14_16/13: ${c} ICNTRMMRHTBGKQTLGZRDPNTUEEDPPXQECTIBMJHLJHTRRYLVWHZXSQZWMNWICYPYRHMTRYQVEWLIZZFXDCJPADMFKHFLPLFWVXEI', props),
compute('m_14_16/14: ${c} BWOMEXIZNYBBUKVICKPAKHUDZBZEDQZQSKFNPZGXGMWFUTRNNXJVNXIUJICSTAUWVVOCMTIQCDVHVAMCERSPUAZBLQKRQEXGIIKT', props),
compute('m_14_16/15: ${c} YKKISFACPOGDNHJSBZDGKNOWXIVIKKGGYVTGKZVKTKSJQVTPEHXMCQPEZESTHRMRXVCIUUXHHEGSNBFILQYMOVSYCRPZQPDAPZFL', props)
        ].join('\n');
      }
    