
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_14_17/1: ${c} OOMZGCIBYSBIXDSPBKCZJTKDWJJAHBGWFJSMTLBTPBENWATIGOIWCWRRTGHBVDBDINMJUYOJUSFEGKWVJCRBDGKSHBOABYSBAGUW', props),
compute('m_14_17/2: ${c} ATMXFXYZNMSASQWPQPDSACAGOWSARITNNTJCLFBWWJCOJLDYXOHJJYBYBXNNODXYHAGDBFTWQQOBXZUJOQZKWGVDJTMQCPQHKHWX', props),
compute('m_14_17/3: ${c} OMVRKQXPXPEZWBPUCHBSUMNTXZCBRPQEYDSXZGIYATRPPOJSIWGBBCTQIVMFURUINEAFHASOAUKZLAQWIMVJBNLZGZHACXNBAJBI', props),
compute('m_14_17/4: ${c} OGTAWTQQWRQCYRPRMFEFBOUUYPLJLMTELFHBDCDSSJZQNYJLTXGGMQTSCAXYWEBPLHJFFFFXWHFYKZMCHXMREDGZRJYFUUMYRBVY', props),
compute('m_14_17/5: ${c} BKNHSANPPMMBZQKXBKPBFAUPCKMKFIWWMVQJXRGYYCYQGGSJZNTDUVZSECSMGTIYLHGEDYKZAEOKNPAXSOWIWUSSFAMRKTQJQGFO', props),
compute('m_14_17/6: ${c} IZKEGMDCCYHNCEDIAKPKPTNGRHDIYKNBXPOMMGNVXRFWVHETFZYRICWBSDQVZUUKUPTNAENPLBNJXWNQRUTPLJGTNNBKXWBZNBZC', props),
compute('m_14_17/7: ${c} WPOUJFJMEOUOAYOKLUPFFERBCLRNCTNUSDNZTBVAGZWXJLDXXBYUWPJVHFIDMVPAGXCNFEWGNLNMGPCJJWYVQAOCNETAHUSXYJFF', props),
compute('m_14_17/8: ${c} VNVQZCJGRMBCEYAIWQMQQGYXACIVYFVFIVNKFMVRSTSRQMQHWNAGJHBLFJBIQBWUGALOWJDXGMVITESFIQKFMDXPBFESWODFPKLY', props),
compute('m_14_17/9: ${c} GEPBVUSUCDHVBXKPQUTVFFIMDOHQHHFWGUBJLHWGMWHRBQHPPOTMGKJPITNWPIMJXBISETXNFTPFODHEBXFVEBAVVQYCTWZHIMMR', props),
compute('m_14_17/10: ${c} VWSMQXKTVHTAQVNHMYTDEXCDULWMUHVZJNKUCBXNOLGAGIEERUJOGWCTFNPWHCFQYXPOAMOXVUWOCDVFMVQUPNQQZHCTNURXHCAR', props),
compute('m_14_17/11: ${c} CZTHZVZXQOKGIGHGEXNMLCIXJLRRQJAHBUHGWIOFJVBDRFMMRQPCOAVQXTEIUTFXSSYXVLGDBYVUSJTFBUQVCAMNSWGAFXJMERTT', props),
compute('m_14_17/12: ${c} JFSCNUMOOGQZMWRNLYDVRQNQLTHTUPETPTLAPZLLGTNLPKWJNEMBEXYYRADGXQEMBHHINCSRBKWDDUPMZCQDOIMOUGGVLFTNYILV', props),
compute('m_14_17/13: ${c} KNUFPLWZVGAPSYCBRCUZOUYSWWXXNKARTYCYHHNSOMCWAFYLQILBDLCBZFNAFZNOVQZLLZSADPHMDQDWPLUOYKBESYTJUGJHCSHQ', props),
compute('m_14_17/14: ${c} VKLSIHSGZXMBYPNFSEVLPAJMQEQTDAGZDCRRIZHDMMGFIFCKPRTWQGLGSMHNVPYTCEUYBTOHJTPIDIFFFIYPLTBDQGHUMIWMYZTS', props),
compute('m_14_17/15: ${c} QQNRBMHUGYJBSWIDNBLAOJOCXZEYMIIGKWEFZVBMGIQFBFWSFUINPPVMXQBGYKFVWKAMCWOXQTIMGZPADTGJQQADQWQEGLQHCNRO', props)
        ].join('\n');
      }
    