
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_10/1: ${c} MAIPVDRXPZOJNRFRYPWPDQVPTTEHLXDPKUQVNGUBVGFERLEBBAXEGIOHVMHCLCNQAWEQPMPBTUFGQTFYQBJSBGNHTXGBMUEIBODF', props),
compute('m_15_10/2: ${c} HNDRUAYZBNSICLDYJGLFUQVACWWOIUMGFGSJTTWTNDCIVNBQULJUDUITCQYHLCGHGFLEQKNQOASMARDJNRMLXKUFXCGQWAIDCQAT', props),
compute('m_15_10/3: ${c} TXWMOOPKYGDFZBSNLNSRUGZYHAFNGWZHSAIEBWDHRLCCHTBPKXGODZSTXZCOCHKJBEBVONNYRAHOZASMSCAETWBJNQILSTPJTNPY', props),
compute('m_15_10/4: ${c} MZXEFIMBMEUJRLFCFEZTWOZSMLOKVCKPLWTOLDJQMEANYOCFKDPEUAZMAZSQRUDTJTJYDBWDTHYDMGOGGEOHKHYWZKGFXOFFNJPC', props),
compute('m_15_10/5: ${c} YSCSAEWYOMNKXYFLTTUVBPQWXEXGFBLDYEWZVEAYYOKLSNHQCWRKPFIZJUFSGXNVALFRHCHGXEMALDUQFUAFILJMWSZAZGNPTXWL', props),
compute('m_15_10/6: ${c} BYHVITRZFDSFPBJTOLIXKXKGYNWFWLJUMOYEDKEKOQGIJPOFKBYVIXWKTPZZALZCYNSJLZHGOBQTIMLNTUHPNKJRFDIJHQRNNQDP', props),
compute('m_15_10/7: ${c} OPKVERBOKXLIBIYLWJIRTFMLRNFATAPIMZMEJGDOFPDUCRTDHCMHVHTJIABIRBJPOVWSUOJWKOHWAXYRAVBQGLUAVQTFEBGAFDFX', props),
compute('m_15_10/8: ${c} JCBEAVXRYNFJQIAOFQEVBRZCVVCMDPJANGMRZQFNTDDJCCHZEPPAWVOMSYIGWKAJRCQSTXUYDJNDUKSYYNXYKLPLPLWBTQDWNQQE', props),
compute('m_15_10/9: ${c} ENNCXUKAIDWVTOGAGKMICGAHDSUOOCQWCYZISWJTAGMRAISGDVROFFYYXEIPKIMLAVNDFIZIKTQMMQOHQIYXNCVLVTOEFANINCAG', props),
compute('m_15_10/10: ${c} QRZGYCUVSLNWXEGLPORMYPSHLQAJLDMGNKVBXYKWZIVALNFVCHIVBEWQPACSBSDZFMDUGUOIUSFEFNOJUGZCFNRLFJVLUIPURUIB', props),
compute('m_15_10/11: ${c} XWJSBLVJHHGXVBGHMOZXHSGWSOMACFHYNRRZQSOCJMKMWWMTSAZMHGZWSKCKHFAUIPBMWPCILUKCJSOGXWJQWCKYVYLCJYIHVMHT', props),
compute('m_15_10/12: ${c} EFXAGYMJDIEPOSIAISIYGSCEKEPHSMTGQVAOEDDSVTOTRYJSHEAZPHELMBDIUNJDQBBMRLYIWYPHCMPLRSZETWRRBSHEZJDAMDTP', props),
compute('m_15_10/13: ${c} USCFBSJFDMRBXQRMKJCMZBJTLBDRTDMYGGHCRXVBEAEULNTICENZZSNHPOUWTFIHUJKOHPGNUTNUOGHDZJWAUXQHTQLSNNYVIUAW', props),
compute('m_15_10/14: ${c} CTUZMBIXTUMFTCZQVQRMPKDUSCEUXIKYLZKSWVHRMCYBDGCBSBMUQQABTEFTBBFHNKFWQQFSSMCYODLIQBSEWRGQNTVGVTEVOXFE', props),
compute('m_15_10/15: ${c} JJITVBJAXGFAGXHLMJPYOSVICUJCQWAUKDSAHLTWLSDWQOKUDOSYGSKEQWBBRMSIHDLIBSIFRHOTRDKZTWPMAAQLLOFVAQZVADGX', props)
        ].join('\n');
      }
    