
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_2/1: ${c} ZTKGSKVOIVKJRIBMEZSQKBAJSPULVHDFASCXMVDCFWCRULNAEBSJAELMLWHNYWYNCTGZDULJHOKCFAELFTAVJSPFABZDOUNCMKNL', props),
compute('m_15_2/2: ${c} ARZIJUTWTEDNDDIRVLWZUCDECDKOJASJIYSNIDPKBYOPNYLBIIBAUXTPBXJOQBEIFHHKMQRQGVDBQFNALLSEMMICIZWPARXGQWQB', props),
compute('m_15_2/3: ${c} STWOQKCXPNTTFIXZSZYQLZKOXFBHTFMTOCWBUISLIGRRWZXKJABBRYAGAIBUOJTMYNKBAEEGWYUZNGSFRUBIWLESQFKOXZVZHASP', props),
compute('m_15_2/4: ${c} JHRNRGHPNAIJXKPDLGGMGNMJFDWBHWIFGKUEHKITHHQJZYBJNXWXCLYSJTJZGVAKYDVXPJELBCLQMJRVKBLIVCAZJNPQOXCCUQAM', props),
compute('m_15_2/5: ${c} JQARDZIZHBSRBHRXUBMPYSKEUSXOAQPCLCVUHJKPGBKJANRTSIBPZWOAOCTLMVLWHWTHIEMAOOPEGJOWPLTXJTCETALAZBCBYAYS', props),
compute('m_15_2/6: ${c} QBOTCJFAHMUUXRTHAHQYCDCGCDYCMZONOEUXRMXUUFBLZQHTLBYZUCTPNJXTHBNQXTRLUOAHIQJHLCMKBXDFMCWGVHONSNCFKPLL', props),
compute('m_15_2/7: ${c} JOHWJGJYKRNDLEZVOIFIFWXVUQCOMHPNBVUROXOMTMXBFGSUQZEDJNDLZCRSDIXXHYCOSLZJCYLIDAHFSOMCYDHIQSRNPJFZZGKL', props),
compute('m_15_2/8: ${c} PZSJMEJZHQHNKYABXLBDKFLDMZWDXYIFTBWVAOCAYKSMJQWCEAWJUJXEKFUJZGEUMXWSWXWVBNCSUBSUTCXSLCNUEHQFUKVFFWCT', props),
compute('m_15_2/9: ${c} BOWXZSEEPEKZIXOPYMBGDJACDQUBWUJUKTFXNRCXXLTUPKVGIIXCRLBBLHRRBMYCGDLAZGIPTXDBXWMBORWMYNGIYWSNAQTTANGG', props),
compute('m_15_2/10: ${c} BVHPFZYECZAWFVKGBZBABRVLPCGVXMVWYDWPDOXJMAAFSPONRKLJZOUDZZJYPUZTPZLMNIGLDYGJJDGRDXAWDWLQETQDKZPMFCDT', props),
compute('m_15_2/11: ${c} XEYQOZKCJXEPWGZAAIXBXRCTHAYOPECFPGLZJNPFBBFHISFZTCNNLAISITKETHYQOOORHUGEKBOALHEFAJUZAGMHCVZKDAETOHTT', props),
compute('m_15_2/12: ${c} VOSUHBDPWTTIBNAXCDTVXZKSFVEQFZTDJFCOTIFFQPNNWVFARFDXIQKDGKOSICASGMNETZYHSHBTDPEALXETLLNIJZAGAUEXBMCZ', props),
compute('m_15_2/13: ${c} RYFASZCRJYDVYQKRDMCGBFEMHEQZSDCVXLPGVTXGXKBTCXPJFJWPPZBACARDALIMMMPCFVSTBDHWXTMDXCEUJFNVWASCIRJDOJHF', props),
compute('m_15_2/14: ${c} PQKMRRDUNLEPTFRNXKTLJPELIFJZSHSDXUNGMUTMPLJHBPQVWCYKGBMOPVNYKRODBMYZXPIPQMCUTXTCRUKMUVXKQBMFILQVKKTB', props),
compute('m_15_2/15: ${c} SQQHTTMYVCGDVUVIJVWGJPBLSNTWOBAFUUHCERZJMFSQJAHDYIPZNXHYIDHZUUTCSDPJXSQEACCDPZPQGZVXOQDEYZDNVGBPOZRJ', props)
        ].join('\n');
      }
    