
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_17/1: ${c} CWKFQGADOTYTJYVSVDAJQNVWCCXXADBOLGKSJDSKGCCVEURAKILJSFRVYBYBRAHCUGIQMOVAICECULZALSRXPVYYVRHKQOBWACJI', props),
compute('m_15_17/2: ${c} HMBKFHDFTCSTLKEOQANLQUJAILUSBUKSJETNFXDQJUGNKWYUYVAOOCDJOBTDPAZIEZSGEIOJVYQKLVBOGZYIMQNQPDIUHHUGNSML', props),
compute('m_15_17/3: ${c} VEDGQFUWKXCZTORCOZENUCIIYFXRLVYBBFMVFKNRVEXYSQJZYQNODKOXERWIUNSDKKMZZBKXFGCZWPUXYNZIWREVZDYXFXZCYUJW', props),
compute('m_15_17/4: ${c} QOURKUBIYHTLSEBRCNDHHWBTJAXFHHEGNHFZYEWSFXJUPJCSBAYLCNLGPPJIPZQYTVPUKPFFAWDUZHSIEQKAXSBAZNKJKIMMRLPQ', props),
compute('m_15_17/5: ${c} NZDSITIPZEYZRVVKERSMFQWKUQBZAKAKRNANFKJMGQPMHXPDGJVGSQJYOIWNXNSJOWKDQMKNSFRURSFRQQXZALWJLFYSOAIIEJQV', props),
compute('m_15_17/6: ${c} LVNCOTYBWXZKPGSROWDJMHUFGUAYTPMSOPGKBUHKPQYFEANFFNWSHPLRZZSGKTWKSDTFKRYLYUJUQNJAPOVNCGYTBIYMCCZCTPVK', props),
compute('m_15_17/7: ${c} XVKOXYJNXWOAUMTXBPQAFRJDCWFGAETDCSERDXHXXMUPKELEDPJKRXVBMZRCRNFPYKQCYXEXBQOKZFDLOGBIKKEARGEIJROLCWKW', props),
compute('m_15_17/8: ${c} SXPZGMZVSUUKPVJSIBHYUWGEMZGQEDWYSNUVQLBRVYLMWNMCIVBDABMSMTINAVFQRZRQKWSTBQFARCQQRVTTFBXDIPVFPDWMDCCJ', props),
compute('m_15_17/9: ${c} GVWBFPNKIGSJVZRCQARVTVMDAHREMITMSNHDBNEBWGMGRULSGEDLDVTYCKWSKBYGEODTFXSPTTWKPAVXOABNCTPHQVSIMCVWSBCG', props),
compute('m_15_17/10: ${c} YGSNBZAOBIIYBTEMYKZTPSVJXUELNXJRFNRMHHBZKUAFQNFEAPMLYWKSZUCBVDWSVYWJQEOBGVCQWBTLTPIFMFKJXZMDSPERODLR', props),
compute('m_15_17/11: ${c} EEQGNOTZWJLBJLPFQYJWESBUTMEKICFKSCOZJBXXHRTFEOHZCVDMONFOKAMUSNDKUZBCDGBWWSQQYSPLBFTDEYOWQDKBJKBDZIZB', props),
compute('m_15_17/12: ${c} MYGYVQFNTSPIIWINMNGUWCQKVLIHXTHZDGBRYSLVLFOLPVWHKHCJRVUJCZKSPZCABNXLYKBWYNZFFOVPRBYJLSJMYZSWAKBAKGOM', props),
compute('m_15_17/13: ${c} CYBWSUQLZFDMYLCOEHUVQXKKHRILATUOWOIARSEWCDJPDEXQLZXYKSZDIALCZZDLATRINXDCQDYSXGRMNZWAXNNKILXDJDNRPRHN', props),
compute('m_15_17/14: ${c} LFZBEBMAMGJMLJJTFJRPVTPITWLRASVVHZWYZRFDQDZKHWDOWPPZBESWHSOGTKVQUYOOGBZSGXUNJAHLSUGJERJHATLZSXIKARXC', props),
compute('m_15_17/15: ${c} MZKANJKIBUVUWXZCXVZTDSZNWRUIQLGHDREVMOWENFQFTFHVWBCJRGHPAOMPMSAKYAZHTWBJXCHLEOPATBZADIIWAXJSAGTRJXJY', props)
        ].join('\n');
      }
    