
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_13/1: ${c} FFNOPQXZFSARITZCIMBFBYBLVHYNIJEAMVOOMTILXUKXABZUOVYCAVOKSPGRKXWVVFRVEQBXJTGZCUTYVXQLPVOCQFJCRZSUHMJS', props),
compute('m_15_13/2: ${c} IJGOMMCDXDUILSNSNTZGQOZTKSIYJLSEGYPTGQZQWFWUCHMHUEKTWGAIASZEFUORTQQLHVGXVBHCDKGEBPVGBSWZBXPTCMIGIZQC', props),
compute('m_15_13/3: ${c} SGWCTXBMKNQYPHEBTIRWXPYYKDUZCQEOLGJPTSHWCCJORALPXFBPMAUOPAAUMTOVJQWSKVJKOGBXSTEMQZWLTGVJHYXAMXCRAJPJ', props),
compute('m_15_13/4: ${c} NTKXZPVOVCGHOCXSNWMNUPKQQNPQTEPHVBWDKUQRSOTLFNYNTDIDOIHQDTBAAOKVWQXHVSRLLSONRMTAHGLDEVYAECFBXKVOEIZY', props),
compute('m_15_13/5: ${c} KRNHNYVHNEEECITBHYPRESQXJZLQRQKPZMECUMYPFSPJXYPOIARUYHYPSOQIVSDVWKVNYDHAFHRPYVPUOLOCASMBSTKLDCUILKNJ', props),
compute('m_15_13/6: ${c} HXROBFFDHRZWFMDCOTVJNGQRFCOLHGUHLPOFRAEZTXVFYDDLSYSBKMPESZJJPSCNCKZNOERXNSBAYPUOIKWRYLFZRACQVYFMXBFP', props),
compute('m_15_13/7: ${c} NEJDOCGRYYOOEAIUJRNNOCBYTJMTENYXNIVOOLGOQSSPKDAYWVZLBYVSMSDCTOEECVOLBOPMPIPRWTLRTDAPJQTJFLODIYZKSWOZ', props),
compute('m_15_13/8: ${c} JTXVGIXXWTZMQPQJSQEHGYUADTHEEAOFKIYLMUHXUPFYAMTZLQJIRRUVGEMRFGRMMATFRWTJPBFOFYLBVHELJQCXAPWMVLFHFEXB', props),
compute('m_15_13/9: ${c} CRCDFZHJFLBQXNALUHNCZXBTCMLHPEMGMCOOTICLXMHNYMDKSWLJHHWUZARBFXZFGIOCDMLPZKMJHTTIMGJYJZDTAUQGOYIXAEQQ', props),
compute('m_15_13/10: ${c} HUHBPRIXNIBEYVKPJADWZWMXYQJSFCXIAGFZAFEMHWUWJRZJPFFDCUHSFFRVXOYQNBNRSUBSFZANBRSOLTPPCOYRXDYDNTWUXJIZ', props),
compute('m_15_13/11: ${c} YYLWFOKQDITOLVCTOPSOJOPCVRBNTUWMPYBWQVBQHWSWXCOCWQMZUCJNODMTHZQCDORHQMBSFFFGQLLCMSYAZTAUVBIPHJBLCLMM', props),
compute('m_15_13/12: ${c} LKLVHVOEUDEHVJKCPJGWVGVOZUTZCQWFQEEJTGBMWFNGHWVJHEQTSLVOAIFGMJTMYMCWXHPGDRMTZCTLYPGNBNUKMUYEPATEAQAF', props),
compute('m_15_13/13: ${c} DAVCBOGZSUFIWTBSIXNDRWWTXEHXSAXZOPSXBRAPJYLLFTTNRWBBXECJGDOIEIMFBUMFIWVHNAYOBNZEBSLKTJEAKEMCQBOZQWRE', props),
compute('m_15_13/14: ${c} NIDAOZQDFKQKUYFLCRAQHPZIOWAVWAPLZANXKQJDVFMNAFBNFFESURWNIBWDOPQZNMYCIVFTSQNHKCPKUKSAVUSJKLSYXHKPQTMC', props),
compute('m_15_13/15: ${c} AQRDYWOAPIJZDSJABILTZDUTQPHVPCNUANVYIEPWJDTULELMTLXSIFTKPSJURBDEKWRFUZNZMNNKNZMTZOTVKLJXLEVJHYPLFXLN', props)
        ].join('\n');
      }
    