
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_9/1: ${c} DNLGJGLSMVQXARAJMKWXCSBOERSWFJIKLEQJFWGVOGJHRZYPMFJNJQCDEWSKAMMXDXOYVYEHDULDXRUGJTUMTPVHICRHIDGFSSOO', props),
compute('m_15_9/2: ${c} IGZPSPOCDOAGSTUBBGBOMBIFJSZUMCPSMNZIEPBPDGEPDPOOAOGCQEGHPTNTKYHQCACYJJSAAWGINZAKTUJABWAIMTQIRMAITUTQ', props),
compute('m_15_9/3: ${c} BGGDLHGGMGAAZSMJUIDIFYGRROHFQBZCJICAQRPBYOHAMPOBXBNZTGRGHHCIYOPMJCITVOWNFLLNGOAKFBHCWMTERILIREIGTMJG', props),
compute('m_15_9/4: ${c} SQASRCSHHRWJIICAGZOPQRHEFLGFKKQZCVLNIXPMOYMBHJTEVTSYUENSWOZCSNPXUQJYVGBHPSRGGIKSPYRYCTHVSFYENOBJOUMF', props),
compute('m_15_9/5: ${c} SOYJCUOJNEUYJARZYDUDFYXJXHARKLJCPUFZRCFBGBMIGQJNVMRQBUQBYTMZEPEGVSIVFNPUYKISCOSSTKVTXEPYSRJXXRPCKWCC', props),
compute('m_15_9/6: ${c} QUBIXIYQNWTEGOBAMCYJCVKKTIZWADOIYUHFMZXAQNZDTZOMVNDMLKOMBPAYAZLPXCDGKOPYPGOZLQQGVFSXXHJTQHZMCPWLJGLS', props),
compute('m_15_9/7: ${c} PKREDJMEFYKVQMWRRIOBEFTZFAFGXJBROZCFSKCZZSZDZOLSORTUJSNRRRNSXOJIKWZFAHDJTVNHOTLOAKFELUUVJWUKKAMNOYIU', props),
compute('m_15_9/8: ${c} JVRLSKBSJFHGVWYZUJXRGFLFDILHRHHHNMRCJQYGFOYDSTSINZCKZFXJYHOVCQIQXTFLMHBQTRZJLLXEXRKMLPVOWRYRERWVGMBE', props),
compute('m_15_9/9: ${c} HWPYDTUKCLHWBTIFTQYKATLYWNAFZKKWZDMGDSLLMQDCZSNDEJPARODFFWMOSOTDYDFUTQRVWJBWRSTTYYIHXIWOPKXJRLKHDYMD', props),
compute('m_15_9/10: ${c} VQCMRHNWPCJYYRPIXMBVYJGJCBYXRZNTMTKJFTSRCLSFLJPDNMCJCBXKGUKJCOBTCEJFLRTOHSBQBPAOPWJYQJNAVVFYKOCNNFOE', props),
compute('m_15_9/11: ${c} AQZEJLWTQBYXGHRHTUWXTUUTPNNTJWUSJUOKBSZQORMMNNPRATCUWHBKKZTATOVMADCTEXDLTPECUGOYFGGMAAAHFTPORFKMUOXT', props),
compute('m_15_9/12: ${c} LODQSRIMFIVFSOEMLQLBZQAUGVDBLSKERVIWWLBWXQTCXVATITGBGICIZWMBBCISENXITVGNPRSPMMQDTHIPGJCQBILFQSJWTXRN', props),
compute('m_15_9/13: ${c} LALWYMKWIFFMAPERKJUIYHMSMVDIXCLNWCGELHBYPARLAJYKTJYQEKFCGWILINHDQHCHVRDPXYVHTCCKBCDMSJIDUFMQNEMZFMVA', props),
compute('m_15_9/14: ${c} LPVIKNPDHYHEAFCPVTPAJLVAYXNHVJTLXGMYSRNAYTLXFWZBRRXXCPGOTIHQJIPCYTRLXORQEQHGFOCMLTPGVJQPGJYVVDZDLMNW', props),
compute('m_15_9/15: ${c} MISJRRBWCJBAPYIIVCUKWMSAEGVCHYOQLUBYYCFDFIRDLHKMHWWAYFOWZEURERPYFNKWSGACVDEOKVZQYRMEMOGTABXBKJCFFZQH', props)
        ].join('\n');
      }
    