
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_8/1: ${c} ORHTCJBBEOZZQWUDLFNIUYOHOAUMYQPHPDZFQSVFRMDDGLYVKRYJIRJSZYCAZKVOYBNLODZLBJYULGKHZEYYYJUZFBFHETBVOCJH', props),
compute('m_15_8/2: ${c} MDKKKSEZCDCKBNBIGUYROOCGYBOSFUFGDGUPWJGCRGKJRALQYBJRTZPCBQDCWOEQDFTNQTZWQBKYVZKEJFCLCSGSPREZIFEAZASA', props),
compute('m_15_8/3: ${c} TBDNHJHGFMQRURCCLXNCPQXIZOIYNRKEGDWXSNUGWMNPGZJXNFZZCMYFXRHIOOQUKHCTYPUWHUYAPJCKHADTIKEGZCJMFORFGJVV', props),
compute('m_15_8/4: ${c} BBNDRMSUIIOHAKAEBWPNTWJQHPRPMNSUMCJFGKHHSMBZTXXGOWOCEGWBYNFHJHXPXYDDJEFPSMFDMGDNQIUTCLXALUAWMSOVDZMM', props),
compute('m_15_8/5: ${c} OAUQHXBXKLLRVUQNMEXJHOGSKVRRVTOZGMKOYUXEOLESPMFMXOHEFFQVTDKQSPTSIDPXTPDQAOGSKVPRCOVVNXQXSUNCIVPJTUJR', props),
compute('m_15_8/6: ${c} TZAPTUGQDOFTNNRTJELHOPBUIRVSHVAIVGIVCUHDJKSEGHPCAPUVACFLMIRGMAZUWSHKLPUVWINOSEHOUBOPCHTXFLBIDCGYWMNC', props),
compute('m_15_8/7: ${c} IRQCKHPQGZLMGXCFEUJHNNCICROYWNKDRZJJPPXGKLBETHDMQVETCIVNCYFJDDVAGQPJCERHPVMUPWMAQBXCMTUSFUJAEWSTHUMF', props),
compute('m_15_8/8: ${c} CDZKHFNYVZONXWSCGJLJEXFTHLEDMJLQFEENNOCIJRMDSWPIDFMMVLQGVDBATXRAHIBAPRXQWMJEFJGOSXRFIQZUECUUUTXVFJZO', props),
compute('m_15_8/9: ${c} PTLQIYBNAKKNOKHRTMJCQRYGANIMVHXQMKYWSIQBIUSMFUQUAWADXQVCRJAVAXEFHCLNXELLKXMZWWPNDJAONKSZGOAXUGKJAYQN', props),
compute('m_15_8/10: ${c} IATLFBWNYOVQOTUZJWQTVMGYYTTUMKYEXUJAFVBKXPVVMOCMMVLXOEHLPSNEEVDASLDDZYFTTOFCTHBMSDFJFKTRFPWYPIBSAJJF', props),
compute('m_15_8/11: ${c} FJODVZWUZMWELROVHGTIGHXBTRLRHGQHLZYPWTXIIGBDUJUVDVQKWMWBNLELNMYVXVAGXJRGUBRQVEWIUCXVECBIIFVMHOOETVUS', props),
compute('m_15_8/12: ${c} TSVNKIFVGOQYCCVGLNVZINKSGVPRYKWBYVKUCIPSBJOIDQLFUUBKIFALFOHRFCTOKHWLCEBIROHROVHISHQKIOJBQINNDTSWBVQX', props),
compute('m_15_8/13: ${c} SGEDTUFBQJKSHVEMJENJWWELXUZBFMHKUVVAPESWMXMLUOSJHAUPBEOCPNYUVFCUDCSGYVFRKLOUUVRMEOBNKTJFDRDOWFRBCJJR', props),
compute('m_15_8/14: ${c} ESJVNHUHYMOBVUVSETUYOTKOCFVJIALCUDNKOJVMBKCVNNKECENIDONGBEPRNGOVUNXZVGOKNPLPDYOZKVOZOWDHUPCVGNBWVHPD', props),
compute('m_15_8/15: ${c} YLANPJLJMQAZBGCVHGWBNSXAGZTOWFZFHHLCQHYRCZSFDZZDWNWETQQSICRHYZSYXLQWSPXCFASFVGCLVYGPWMMHXGIHIDIMMFEG', props)
        ].join('\n');
      }
    