
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_3/1: ${c} AKYWUVLRSHDWWRFUCCGNMRJVOUZFQKMFXJRSBMVYGQMKLRMTLDSAKBNDUQKXDRZVIPVMYBQHKLSKMBLNRLYJOQDNSMBDJZFFFKWV', props),
compute('m_15_3/2: ${c} DGNSBVSVJLAHXKNNAMWDTZKCUSBFFTASUPAPOTCVDJPAWMZXMJYHTLIUDMLBBFHLSHWNHEYXKSMUUQIINSWLPSNFARFTJHCFBCHT', props),
compute('m_15_3/3: ${c} RJRYIJHBHRUNRPLZVWSVCMUPZYPAIMJJGVRLUTRGUDYITUQXWPIUGEQFQNBLOTKPIRLPXKVFEQXQUOBNNZAFGYMVNMRLEELJBSMM', props),
compute('m_15_3/4: ${c} AKSPNPXKYKDMNFMEZEDMPZEJVIEDNFRRJDQBKIUVZMXFGBWYMMVRYBEWQXOQFUFFCFSAQYVEZHXRYCQQCKXQMEAKVZCEUYIDZTAL', props),
compute('m_15_3/5: ${c} KQQWOLOBEMZKJVFUWHTXDYZMTECOWWBRCZIXAOHZXKPBEIBVPVBERASUQQHLXANUGDVIIEKPOSHRBWOOJLPEQAHCRRQLBJGTWJBC', props),
compute('m_15_3/6: ${c} KPKTXADHLHPPYSRQDEYKCASJPUMFYMJNEERSPVHEYZZINEMHACNZPZGEYDNTAVLPKCBFXDJEFIPZEXUGVAHPILBZCVLBVBVDWJOM', props),
compute('m_15_3/7: ${c} GNSZJBORCOULXGYSVSUBKOMWCENVXOVBBLBOTKARTQTXCVWOQSYCRVZPGSSNKGVHZCKIKFJSWQHHSCLHLNGICTOXICKFPQIGYJEN', props),
compute('m_15_3/8: ${c} LBGHLXHVFUBXNHZROOVLLAXVEZNFDXUXFZLCEGDIWXDALLETSQJZSPMNCEIVEHBQPMWDSPINHJJZNCNSNYKZXVJLCOAAOSGSIEFA', props),
compute('m_15_3/9: ${c} HOXQAXWRUSXDHQPRVQGDIERKHQVINDJMHQJXONCGLYREUTKZJKKUNADRHVBRCHQGEOZXVLBRCQDYQIWDPNNWSPNNHUFBDNNMYIOZ', props),
compute('m_15_3/10: ${c} JYZPALGNYHQBCJMKIWRHMOXYTANUNJUYQWSMFCWLIZOMTEKAJXNFRXGOZBFLUNKCPLPCFEKYDLBEWZWUSRZHQCXDYKNVPGAZPFMF', props),
compute('m_15_3/11: ${c} XVLYAZCYWRALLUAWAVSSQSGCKLRQRAFFBUSZUJKOJIASYXEFWKEWRGSAVKIQBBBPOJKVPAFHQWLILRQEQOKGAVLAZZVPBESFWLUC', props),
compute('m_15_3/12: ${c} LXQNXOELQYWYPGNBRNPMIFIKNWYIIUELVGQTOPLQECMPOVZLCHFBCOQYAPVZTNFLGOKMLEXHIKRGSPTVMWSWQTLDXGCJLHHHHVGC', props),
compute('m_15_3/13: ${c} TSPZDUYNKXGWJCCMSEICJRVLLFTZGHXZYESLUIHUCIDPSRTSNBSCRJRQFMVLUDGSACBTKBSGHUAHJGMXGEZIZQHRNSHFVUAJXFHX', props),
compute('m_15_3/14: ${c} GNRVYYMNJWRDFFOYSTTZLYJLXDZLZYCJVSGBFLUTUJMOHNGGBNGCXEGQNZEFWHQSJRHCTJXZZJMIONFYFTFOZUEEHIIYBSLSDPNQ', props),
compute('m_15_3/15: ${c} YCDKXBPMVMFNWXUNEZXATIAPEFJCGLGEOJVXRCLWXNWLHQMKKCNTYYXLCFAPXMOWXZPSWGQKBLJWZTHKZXDBGFSFFLPKIEUAUYNO', props)
        ].join('\n');
      }
    