
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_11/1: ${c} KNGORESRCHTRLEDZRWHBDHQQMDPCYMGDSNOLPEBPZDPPIAICNMBLCEMACQMUHGGXAUYQQFGFFCXUDQNQJINNZIGJSEYFNBCQKMFI', props),
compute('m_15_11/2: ${c} LZRCNXPJSQZYGZIABYTBWAHOUXJEJEEXTQKRUPAFCJFIWBCZQROSILBKFPDWYSMSSRXUGVOTKWMJBYNDPNBSTUFFGMJULDMXAGOP', props),
compute('m_15_11/3: ${c} UAVGWEITJXZUXPNKCHVXJMYWWNJGVIHEFFXOFBIYCJHKXXYSYFJNIMZIOZMKNUZETLRDGOXYDUIXIRVMBQNXTEVEMFGTKIHXREML', props),
compute('m_15_11/4: ${c} ZUXVGPJLZJRQSVEDHMHUQILRAOAAYSAMYJQYCILIBJIULVWKUJTGQHEKNOORPIHTDJAIWHHQGCUICIYWFFYPMHNAZKAORHCPPQKR', props),
compute('m_15_11/5: ${c} CEYTHUGRWYKCSSFELDTCYWFWUIUXKGBUBATGTKOFDBREBXNCMEXTSUPQESVITVDDYZSCZFOIKUGGBZKTNAKWPNIEDNEFITTTTGVA', props),
compute('m_15_11/6: ${c} UDSLVZRWXPLCTHLDWOINMYETALWFBBUMUTCQAJZGDULRBEIDFNEEBYIKELLTYKTELQBSVQFGNUGAPQMLYOFDHDMTEXXBKFLMQRNF', props),
compute('m_15_11/7: ${c} UVKVTPZLQTQBTFKSLNXXIZZNLPEOLMPHSMUROOYLVAEVHNBINQZTPYFYBUXIERPEBKHELVXCJJDHJRMZFDXNGVEZCDZLIKWHNPII', props),
compute('m_15_11/8: ${c} WLVPPQKIZHFTETWLREWOCWCIVPVMAVMNJBZIXJWLWAESUIOHJCLEJZCVLRAYWALCJQIUPUAJYXUSWCJMZDFCMPAJQMXOVNIQEZNU', props),
compute('m_15_11/9: ${c} UQCCFSDZFXNDYJFNICUPVEJTORVKQJEXQZHIVUSGQTZAZOXJLCEKJMZQNEZIAUETERXWGNSYEGXOJVYXPBVTEESFCYLIVGJNDUBP', props),
compute('m_15_11/10: ${c} GYGFGTNTEWFPKTYCLKNWNCERAHURVEMDMLLUZSSWXOUOJELUHQHLELHGKWPWATUXEJOOTXPDMSRRMEBAYDDSOTNBXORRLIIRJESY', props),
compute('m_15_11/11: ${c} IYUIIXBIVJEEJGXOWQJOEZMQCOYORKZQKPWBFLEFVZAHLGUCVHEWJMCGXQAKZAILUOGPUJUTCWSRUPCJROARZTUPTDIMDQNCUOXT', props),
compute('m_15_11/12: ${c} OZPMNXWVQFBJHCOLCAWKLCKCPKOQWNGHYAICDULCLDBDMUTERIPHXZTQGNZDLSRSYAAZJSPKAICXFWDQBVZQLUAPWGXTZSQYUQAT', props),
compute('m_15_11/13: ${c} VTMIQJQOYBRIPWHOYCOJBEHCALVSNDVFPHLGRLKUKFJTAOTGRUOCURMHNSWFDIPSOXTWIYBFELAUQNYQOAZNYPUQYSPJBZPGHKLZ', props),
compute('m_15_11/14: ${c} WRPVCYZZUCFXERIDNXFVMPWDLXKHPOWAUEJCMDKJIWHIZWXXYUJUCJSAXDBOUYCHXLNFEKWFTKSIOUECSKRUDZVPPEKBEFINYIPL', props),
compute('m_15_11/15: ${c} FTAMFVAPINMLGPRLKNSPYGPDWVCOULZEOYOIVQKCSRHPISWVFQBCJFJRWCVZUGGFCUCOENVDOFZTXJXHUVRAHXIEAMFFXOTDPSWZ', props)
        ].join('\n');
      }
    