
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_6/1: ${c} OVQMYZHUKZPHPHJNAGHFOBGNDJKJRIYHQHATAYUIFSWLYFDRIONEMPRGFGTNMJWKVZUHDDCIZPMXNHRIXIVNODBJIIUMOTOINMYK', props),
compute('m_15_6/2: ${c} UWAGJCQFICPCSMEQUTCMJXWXNBTCSJBBYQFABXQNMKCDSYFYKXAJOHIJFRPXJJYYZRMTMKFBSWZFKLANCNWWFBDIQNMQSTHBQFKB', props),
compute('m_15_6/3: ${c} ZZWRUAHULHDRVMIIIFRIVVOGEXTIANKCNPPKWOCUBJGECBHDSJCKWCLGSZVXOSHCDOGLPGXSSKTNTHFXFVPXLWOVKMLQDGFZBFOF', props),
compute('m_15_6/4: ${c} GHNUHGLQTSPFDVONKNQVKLLSCQUILYBBODAPSWSVADVBUKHPQAPIYZSCAWJYIVFEAILNZIDMVBINZTSDXSQPYIWMCUINPOHPHXBI', props),
compute('m_15_6/5: ${c} BFJILDGRNBITFOGIQBJWKCCYRJDXDCWCPGFJDYGBKPLYLZUPECUNLJQEMJDTQCIYEBRJNNCXQOXPIYGPMGDQBNRBUCVLYSFWVMTK', props),
compute('m_15_6/6: ${c} UCEWQYWRAYVZXWEGNTLCATNWYXZFSFIQMDJVNCGPEBVYFBBNKVFUVJJOGMWXYCXNKLXRUUMOKTPSYQYICZVWUHPHLOLXTYQZERIQ', props),
compute('m_15_6/7: ${c} BSLTKCTRQMDAUGGCUGHBHEOGXBEVUDHQIOIJROANYURYZSQXRMHMLGMZEWYTYPPGWMOGNPZDLAKNKQNEGOJQAUBIRDHQMIHIXCWP', props),
compute('m_15_6/8: ${c} ACUEJDIKINAGBFEHIVIOOPUEXKQLDDZLJSNSNUDUKMSSLVNDGQEQHRNNFJYZCDNLZQXWHUYTQAYKZFQNETUVCJBXPIMNSLAONSCF', props),
compute('m_15_6/9: ${c} ZSAIZCEGVBPYRSQHRDGNSJCYUWTNDXDLIJTELSYXTDTZILDKOEHJZMXEWJNTCVIGEEHSPSCIUAOJMEXOLAQYZDMKTYJSSCGDMWMG', props),
compute('m_15_6/10: ${c} PPRVVOHZUEGPUXFZUWMWKLRJFFOFIVKRQQTLRMVRHWLWLSKPAAFVXSOALASOSXYGYGGDHVBRDASAVJMLEWZWHVTXYCWMQDPOMJZT', props),
compute('m_15_6/11: ${c} CLAXZBXEEEGTHXMPYCYXEQGKORCUZLNMHWPLNTLLPTDAEQCHENSZSOGDWXZMNZXRTYEGLCRIXAWXGNLLWKAIWHYIALWFFINYBMPF', props),
compute('m_15_6/12: ${c} UAOFPDWFSJRDUEHIQUZBTKSVHMBTVWFILWHNSCZTCFUCKLZECWVXPHUADOQWSOGEQNQAYNYTJJFWBSHDKGQLAKJUXFMDKGQCWMOF', props),
compute('m_15_6/13: ${c} YMVYDZCXGFWORSBEVWNMKBEFRXOQUYWJLVNTYDPGDCLYDFDIOOCALMVGXWVKFYKFFXFRZJNVAKNVZSHNMRGZTVNUIIAEUGCFBGPW', props),
compute('m_15_6/14: ${c} MWUIQQZWBJDYUCVXBRDORPRJYWOSOPRZSBGFCTACYRVINJCWPXTROXWEMBTFNZYRCRBBKSHBQLVXRFZPKQKDRXEPYECKJSDMZJHY', props),
compute('m_15_6/15: ${c} ZNOLMMNMVADJVWOQVJSWWCQFIQBBDTVHLDJWPGGXYPXUISZTRWDXPCZIQQWIJTISCFFGIPKQSOPHVXNODAJFRDKMFGLSYKZICSRD', props)
        ].join('\n');
      }
    