
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_12/1: ${c} DMZELWAQWCFHICTDKPGUIJJQWJABWHBMLZESORIKDGOGJGXZXZJGOPPORZPIKNFBHLVWYNJFZLIXDLFQTFOGEZAQVMBFPZBNXXED', props),
compute('m_15_12/2: ${c} RHEVKHCCFUMBNOEPBCSDGFCPSNWOSSOHPZXBYAEWVKJTJRFRXOVNIYEYWFCVANSYSCBEZPXODDNFSEUHYOFSNSGNXXHGKGMDRVRR', props),
compute('m_15_12/3: ${c} PIMITLBAWQOTFCPVSQYXCEQSRKWEJQHVWLXZLGBQMOQFRQFOIMQKOPYIGBHHSGULIVVGAIWTMCLJIYUYEGOYSFPWVMSMRKFUHSUP', props),
compute('m_15_12/4: ${c} FILVAYJRPZFLHHYIQRBOVNUHVAWVNDWZARFKTYLMNUJBARBGIFOZVIOOGPMQDEYXWYSJIKHEPGEORCUNZNEQEQICFWAYGSZEYYRJ', props),
compute('m_15_12/5: ${c} AKJUBXOOPWSAVLDCLWKSWQWCOXTIHAAPEQWBULLQRSYEMFPCCIFHWHYHUAPRASQDXTYGARQNPASLZGVYZJOSZNURLPWBMPNNFFTS', props),
compute('m_15_12/6: ${c} LTLAZOBGOJQJNUVUWQRIKOUDNJXPYMDRAHCYNRETONNLTWPMBLNZRICAKEIRCZYNLKOKUTVBRMNAHBIDKOEPVRNRJSBLGGBTDHLS', props),
compute('m_15_12/7: ${c} SBSOTFJJAADACUTSOLYBYDCNALWTOQNMYVPMNQTTCZVQSLSZJUNNLCIRYFRUFHGXRRCWDJKHFZAEGGDPKXVLYRRTZGHHPXDAOZCQ', props),
compute('m_15_12/8: ${c} KXCISCXNBKYMKQZQIFNVVGPHSNDBLZJUALWJBKPKVWYUJJVGCIFBETEROHDDNAAJFGTYPTKURLPOZGMSYPIBFUQZMIYNQXYEGHJA', props),
compute('m_15_12/9: ${c} DIUXQISRVYYPKWYILTXGDTABNPURXYWMZOAVJRBGFWBGOQKZOHGXXDBWZVZQEFMCOPXFGGPGJVLISPSAVRCFNWRDFVWVNWEMVRZL', props),
compute('m_15_12/10: ${c} IYVCJJQIMHUTZUZKJGMZRDPJHNIKXAUHCULFKGYYCFNDNNKMWUCGIWJUMEBNQIIZQSERVKPEIUXEGRNDHNOUEJVERFBUQZITKGRI', props),
compute('m_15_12/11: ${c} MMKHTBANREOOALMCMQRGKTYQZQESUSTNJPKWUAADQKSCDVCEFZQIOBDIJHJOIHISXQFEVOHNNNFUAXBQKICWIRNBGGBZFGKOUEYS', props),
compute('m_15_12/12: ${c} MJLKHULXRPAIBXDAOXFXIRMFXAXVLGWLALZGDGYZVHNMCWRACBEWAHEMHTOMWVREZVZBTWEPXVYIQJKOQUOPJEFQVSESQMCLJBGH', props),
compute('m_15_12/13: ${c} EHFDRXISCQKHNFHOYPSQWZRHUOVKPXFRYVGPCFQPLWWUUCCCJTCHIIHQJMSXOGGBJZQWWEYOEFLZDWKANVQFBIXOPUEYWOJDWKRA', props),
compute('m_15_12/14: ${c} LZFMJXCAGLDRREOPGWKJBLTWZGPLTBTCIZBWDOQBQCMYMVFNYMSQGNWKSUTHONSTNDJUXWKAENLAUXOZNIEALXOCFYGRIOTOXHCP', props),
compute('m_15_12/15: ${c} UKWVLMOYFJGXFIEYRYYLJBUSPPBGUNZVSBGCRBNBZVQOWEUCHABNGFELKMGBVVVPRJJUZSFXMOQAZTZQPAHDQFNREAVVDKAYGGAA', props)
        ].join('\n');
      }
    