
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_7/1: ${c} JOGXVXCBRSJEHUSKLZSIZIMQMQICRMCZPAOKXYWELIAPCGHAHOLEWTEGKKFXCJJDLYAQDSBPZJDFWGTWHLABQMCWXMQNFZERYALY', props),
compute('m_15_7/2: ${c} HBNXYTQYTCXWPIZGIIBKSIVWDWDXKHACAOUHUUUICWVUSVRPNALAHIUIJMUEADPFEDVJYTGMVZARYWFNOXNWNVRAGGNFMYEPUVQK', props),
compute('m_15_7/3: ${c} VXXKGDBLKMSLSQRQLVEDHXDIISHPMRDSICYEPVIMHNVWZBTYHSQSUYKBXSEBEHCUSBJZTLIMNTMOYFIXILDKVZCQQWMWTGCIQRGE', props),
compute('m_15_7/4: ${c} AKCLVIFOIQQMRNYEKUEFVYRBVJTRWLEDOQTEQCJQGSIHWBAAOGDXQDJPYGKOAWLFEPIJWHMSFFXMHFYBDLUGNOBPZQWYNZJEIMNO', props),
compute('m_15_7/5: ${c} PGOWDSRBXGVGKQKDKJOFUWLUEIDLPHNNFKFMXPEBDPELTCXWZEOHBZDTQTKOLLORHRAOUTBBBBOUXODIGGCWGQERZAGDTVFWOMYV', props),
compute('m_15_7/6: ${c} XMILQJSNTXPMZKQRNHSFOLRXQQOLPNANUSDXJOYHGMJPDHOJXDOQYSKUNTCEKSRNOSESSNQSAORNYMRULEYCHGQWFDXQSYISZIPU', props),
compute('m_15_7/7: ${c} FSXBIDBTLJBCIVWNPRMCNBKMPJLDOTVHTVBQUMABHYLTKNRADRKAGXOEDDBHARVXZMWIEHZRCKPJPFGWCCTMSAJOIATASUTHSOXW', props),
compute('m_15_7/8: ${c} UHBAGJHUNUNJABQWERMBMFQGDCUJCLHXFYBKRCSSLRCAQFKCSIARMJOLZAXZNFAXUEODFDZKGMFGUUTIPDRCJXMZEFMJYENXHHOB', props),
compute('m_15_7/9: ${c} DRKKHTWJGMBZMQQBOLIKMIFTJZOUIVFBODTHFDNWLEJQJEKHZYNOGPIVHQJNXMHDVOBZWNGDZADUHBZXUAYHQLCUFTYNSMJSCIWX', props),
compute('m_15_7/10: ${c} LSRLDIJXINAYDZFNZTXQRBVDKKLXPRUONVWYWDDZJUEFELBCHPWWWDCFZZDTQMQHSEYDSYBWSXWMBSDGYLXXKEZAPQXZCLFIVHXU', props),
compute('m_15_7/11: ${c} MPCWVZONRGRJPLLORBKKYCNPGAAGSQDJNZRHLFXSHGMNJKYVJTGSJSIHOOLNTASONYGVMUDCICTKVGKTVLLPUDJVWUCEMMTGNJLS', props),
compute('m_15_7/12: ${c} FUMNLQQLVMHYWKHNKCFRHUPVFLRTKGLILKJYMOYNXCHYCTYWZGBTOMETUDNHONHOSWYCCNOFKJWEBKGUSAUVYFZXCUYUJGXIWKSB', props),
compute('m_15_7/13: ${c} HYTKNTXXDUJHYRGPVRENEAMRVLPRVQVCEWBASDAJSHBZCCULYKIRDNKGRWRUSAFRILABWGWKGMGHNKJPBFCCPISUEBTQZUPKDGWM', props),
compute('m_15_7/14: ${c} YWLXUCGFIHSOJCNJCASPJYQTQXWVCSCJVCXVESSIHGSJQAWTPHXBWJTMCEKECVRUXQNDIAHMNZUQPFZRHAMGPURCORYSCTIXXCTI', props),
compute('m_15_7/15: ${c} QCRKXKTORIVKQDNDPPNYMSOEQVGEOEDEGQHWOAXPDULBLLTOXMYCBKJOIFLIFYGBQRSHDRISAJUTMVUMUMLKSNHCGHQOHWCVBVHK', props)
        ].join('\n');
      }
    