
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_14/1: ${c} AKAEYEQABCWRDLQYUHCBLPTQPZBETVTMMGMQLDVDLCEZUVZOYESIVQRJFTXCWWUBKWUYJEDGVAVWBOJWKWLQGRAENTZWSFKKOEPV', props),
compute('m_15_14/2: ${c} OKCWPSEGEJEHAIPZZRFLFOKYEFJNACGQWXUDZTRBMWHCPOCKJPAKVHPOHILWWXFABXWEOIKWVSCCPVZHEODSAKMEIPZCZUKFZUYW', props),
compute('m_15_14/3: ${c} IPKWMBYSTMLSAKVYWELTXSOPDNZPAPPDHJMCYKIXYAENANVXNLIHAEXRKYCBPBHQMARCQNRRXKCJFGBGGNQJZAQYNFHJMTTKIUMU', props),
compute('m_15_14/4: ${c} PZGYGODSIWIVGGOENOPQPUWMPBDCDZMXQHMBTPFCGZVEOPDKNOTNLDMEXFUPKHHJDXHCMONZNMITNWHCPMANTSMRZJYNJHHMGJTS', props),
compute('m_15_14/5: ${c} HWXZBJGOMTYOGRCGIGHNQIDHTWNFLGMOEITSMUXQRXKJDGNQELQUOFSGQRBQIPEHUFMWOGOJJPKXTEFISOLLXZOBOUXDKYIZMDDV', props),
compute('m_15_14/6: ${c} SKPVSLVUWAVJDNZCABJPHXNSRVOBSFHONOXOMZAHCXWMFJRGHURAFAEBIZSDQLNVHVRADDBQGFBSTTHAFLMPQXWNVJXQKMNLQGLT', props),
compute('m_15_14/7: ${c} GUMHPDSSCNFBWZTHTXBDFEUASSCPSSKWERXFHPJABDXBPRCIIGEHZSGRVXRFGMVWIUTQSFMXELMYPVOQUQHOIMNHLGDNROFEDZEJ', props),
compute('m_15_14/8: ${c} HDQWZGCLYXAQPBZKNEDGCJJQCQNBDNTFLNODPLZAATYKGLYISRELALIQOTNZMHFLUVOBSDWEBHQJBUJBPWWLZZZKMSQKYXEEMUEH', props),
compute('m_15_14/9: ${c} KTHUWHKZFJNEKRZOBUILJKJMXRNCHXKPNLDCIZVAQCDFLSVHTLSBDODJSKDNTNYNVEHYXBFYKZDMOCJBBCNONBSCGXEMQGSSNPZR', props),
compute('m_15_14/10: ${c} BUGNRNSBYKTXMWEXBDOBXJLSRPXGAKXOEZWPFAKTYZCHYAUGJXMDWEEQOYLQXAKASYONUVZWYIXXNSJYYPOSLELZHEPDMLOWDNDH', props),
compute('m_15_14/11: ${c} SVCAZQWURTFGCEZZCMNSQXFJMAZGFTPWYLSMEPTOAMESTXFEGDXZPCEZOULDXWAUVZSGIASXLADWILTLUXVLGGOMTRRJJXIQJAUU', props),
compute('m_15_14/12: ${c} RUAFZNPZOMIRBOTDEYKMQNDYWDHXYQPWXYBQEBKGJPOVTTSCZRBAJWALCYLEFZBRDNCMQJFTLNVQRQILHYURVIMZYHGXCUZQMIAM', props),
compute('m_15_14/13: ${c} TICVUGWCOKLITOQLIWWDSYWLIBJTBRDZNHLFLWSSIFRQHYPNWKXZGDLZPCRBUWBSVWORSQDMEPFMZURAJZVYWWTKFZGEOGGOOQBB', props),
compute('m_15_14/14: ${c} XJSRAIMAWDFEZFOVKPNXZWHPQZPBZYQEIGFGXYFUPOYBXIWUFUUUBYYIIQDPHWXNMUKLCYYMRVTCUEEWZQBGNDAPJTNFQRYLOCYZ', props),
compute('m_15_14/15: ${c} VPNXBAFZDFUXUVATRKJXBCENMWXKRABNECEIRDTDZYYDJRHPTVXINRYSGSFSFTRFFIEAHSMNNRTWSMCHTYLBYNCCMLFUGPJXPCHG', props)
        ].join('\n');
      }
    