
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_18/1: ${c} PMWGULPHPFYSSEDIHVPJAMGWIKCJJUDQVYJBBDULKOIDEPFMYTTZLVXTOUBRUXDNOIESKHTHBXMJTTWURCLDHUTSPNLMGOJCFPYV', props),
compute('m_15_18/2: ${c} LWLXLLPSXHTTMKZBEUWWLYPXJSATYRWLJMWPWXVUDAUOWGHMPHOKTZXNKGHBFNKARHLHGFQXQUQGULIFLZRSANIFKEXDSZDPSWOD', props),
compute('m_15_18/3: ${c} FWJOARMHGREIRITEGARTJTWEQUQNFXPEPIQBLWQWPPHKUALAXPRRXNXDBRRTXFOMLTTYQGORRBEWKFPHZVJPDDLXMIMYUVCKJRCD', props),
compute('m_15_18/4: ${c} CDUPPXTHGYXPEKOQLTJFQVSKKLWOELZUKQLWCSNSCTYSTTQBEHKFGJSIIZHFEPKXUOJHUCKFXOQFOOETJVZFPCRUIIQWYPXDUGEU', props),
compute('m_15_18/5: ${c} TVEMKJFRMGHAUCWGRAPLFYCVSHBTMJOHQASKBQBJDIOKRHIKOOXEUQSPGPLESQTHFEOODDSTUTHBCCYUPEGGKLGYZPKQYCSDHMPD', props),
compute('m_15_18/6: ${c} LQOAFKYIIVDYRUBWGAOFEDYAMSPFBGFWZXIYPRZVNMHTSJZFXBPGZAWGKURPEKUBPERHYJTTXIDOQCSWESCHWIVPCYTGBIXGJOIO', props),
compute('m_15_18/7: ${c} JIWQVGDRVZMDCRQDZHVPVRACHPRTCESSIKDHNJCXXZRBFKKWYQXTRYRQEDWEVGZHQGIANSXJKBSNJOHYIJSZLDMIFZZHBDSKLIIH', props),
compute('m_15_18/8: ${c} MSXBNZLVZUTUAYRAAJPTICLELJGIRTTLWLVEHWGXLMQLPESFGADEBNGTJKBUITYSQKZDLCXFAYZOFHDJUJGSYNSNXZCUXYHDRXDJ', props),
compute('m_15_18/9: ${c} LGITYQFPHJXQCATPMRXLXUYUJCAZRATLVQWYIOKGQXPQVUMBYSXOPMGXURWPLVEBVGJIRYRBSMKQYFMFCQFFGULLMQPDZHWSLBEA', props),
compute('m_15_18/10: ${c} NNXOOCKDTHGAMZHWZAMLXEYKOOVERFWPRJJRDJJXSGUGUSKYJLPKPWCHMQKXGREEBUDRANXUYEUHZELFUVLDJMGFUPWGPTHYGTDW', props),
compute('m_15_18/11: ${c} HSNSVLXBPBEEAAOOLDYAKGHNFXKZLFWBWTWLAWGFERZOZSMDGLPQHLLUVHIIVANHVJFQJPCTAUZIIPXZAREPLFDQGZNYREQKXNSQ', props),
compute('m_15_18/12: ${c} YPWMXCJJAXTYHYLSVDASDRJXDXPMQYRIXYXNYKYFHYPTORBJRZBSYCSMRETBRPDXVTODKTOEMEMSDNBHLSGRXANULDTGNOGKDCEY', props),
compute('m_15_18/13: ${c} JXCUAJLLNYSVKMBZHELOIKJYJCLGBCGBWNWOYCZDLLTDRWWKUNDNWSYDITHTBCIYXAZGOGKOYQZXZQTYLICUONLMTIKTBCVPSZYM', props),
compute('m_15_18/14: ${c} VMSNBGJTRYYODRYTYAIVZQYMSHTPIFKVWHCBSAMRNBSLHEDYPRMTTSTAPWFQYLPVRNJZNDHFGLSVZIHCPFKZFSLWPIFNQDNANEJJ', props),
compute('m_15_18/15: ${c} NZQZYREOQYVRPYRWBFNXYVFKAYVCZCUUZBYCGVYUCRJCDHFJYJSAFMCINDQSJZAOEWEEYLNPGCXZIUMLQYFKWJAXANIZRTBWSYQG', props)
        ].join('\n');
      }
    