
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_1/1: ${c} DCCVPMDXJMKJPRJPGEMRJXUKFERSETWUEDUQIARJFLNOFTQVDYCWVPBDLYRQDXSTJTTNGIAMFPIBJDMYMEODJFCZTTTDFGMDAYGN', props),
compute('m_15_1/2: ${c} NTEKRPJOFHJQVXLASGPZDSOREJTXVKUQIKYKCDRJRKRTVAJALUTOYMGRUQBREZXMJADEFWNJZZYFQQQJJEQKRYSBMOCAPLWEGTKY', props),
compute('m_15_1/3: ${c} JUDTQRAIRJWWPJTDBDUEVKVNNTYQDDEOCBRKBRHPTUBXNMTAUERPUEEYKEVQEHAXWOEYXBIXCTZHEABGQOOVCKWVRKJTYHDRXIZF', props),
compute('m_15_1/4: ${c} XUHLNQKYXGFSFNJFFPITUXZRMURWYALHYLZATVACOFJZDJQNGLEEYYXXCQHNAFUEDOKUYHMHSCFDOTYEIZIHVPWSFIXRNKNWAMQH', props),
compute('m_15_1/5: ${c} NHCQWUBXWRERXZTOFROCATSXFTHSIREZRRMLPCBLZUINNKGCZLHBVWPBWSWLSGSQWQRFXNQUOGVBKRIRAYYHNOGFWLGZNKAAPKGE', props),
compute('m_15_1/6: ${c} FNSBYWEQROIFIUFPUAIIVHEUXSVMTFEXANZGHYNPBGGZSWLYRSYEEUSAMZATRBLDJPKAGWPROZDXXMBLNBGDALWQGZUAQGCFZEAX', props),
compute('m_15_1/7: ${c} SIROUMSRYCWOQQAARPKLDVCULMWZMOLCRUQBRDELYTMYPJMFWALAOXUIWRWRJBABEHGZRSLDWMDHSTLRIDKUJDAVGGBLUMMSSOGV', props),
compute('m_15_1/8: ${c} NTIAWFCMVOSWIAEQLANEQJHZWJWLOJTQQHOXXVSLLJGYKWYXAZSOLGXTHRIDKLSXWIDXLMKYTLBCAGDVPHTOHPVMLRMZNYFDNAFO', props),
compute('m_15_1/9: ${c} ETZKXHXOYJCWWZMOSEUJEQXWMLJCJXWUNKHUEMXFZAJYFAHRIAPVQJMJTETCZCDFACSLOWDBKOVHFMKHVDHAKGCAEODNYPSMVVWF', props),
compute('m_15_1/10: ${c} FBINNVJCPHZUZOEVEADCHFCWTWBSLXKAPTULGDKHUWYQAZPRVWUBJHGAGELWQBOYUKDDAUVTTDBUOWFQEUZDAOYNDGXHBGYUMDLD', props),
compute('m_15_1/11: ${c} VUBNRCSFKHNHXJHUXYIKCWZWMXFGWUYQSHRPDLPZSODUAGKJFHUHDEUDHDTUVEDCFZBNRIGQKTUZWNMDKHTNTVXHBUTUKWDHWXRW', props),
compute('m_15_1/12: ${c} KCLXVMXTCSKNDGCAUDRCYUGLYWUBASZBONMDVGDICBNVKJNCDTYKEYVTVOBLGOPFXXUCHBFBSWRZNPGKKNSBGGZVITFXMVQMWCQV', props),
compute('m_15_1/13: ${c} UUIJFPCGDCJGKWGOOCNNPKZWCFFFXAMJGWLYKYELTDRWGBSMOZOJLPOWOOHXVMIFGDOYPRBIIUPPNMEMCLODQABHHJIBSNOMWXYF', props),
compute('m_15_1/14: ${c} WKFBHOPLCRGFZJRZAIURRFNMJXJAPWCQMSSMXPHYPXNFYMGWHEGZOHQDHIZGEATZZSNECAVCAXGPNBICSGVHBRPQIKUFUYSFIXJB', props),
compute('m_15_1/15: ${c} LQMTQOWRQITKLZZVKPBEXFLOGSQICZOWSJLMPAOKVCWEQLQHQEAVHOYMEUVUZQNFUGWBHISKUKXPPJQOFRLSOYVKMWHWRRUZKXFD', props)
        ].join('\n');
      }
    