
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_4/1: ${c} LFOYXSHZZQJKUOSMMDVAVTSLKXULTHAAKHTCKLJASDVCUDMRDUMANRMVMPOQNZWQJKPJEQDKHPOOKWJPTYTHUYHSAXOSFPCXNIDF', props),
compute('m_15_4/2: ${c} JDCLBMBKDAMGASWGEQCEQBSPGMQFCCTRXMIYTLRPEOSXXAPXVQFMBQOGYPSZHZAQKGNWXQAAMOWGXIYXZSIMXEALXTLJAHHQRCMD', props),
compute('m_15_4/3: ${c} VIKPLWSWAYMEAHQUFKDEJQBPSSJZYXPIZQANQKEZRYUSDIYUIPPCAODYIVZBGLDPMNAKQQLMMZOUCYLMZDEOTLVMDLHMLQABTBJT', props),
compute('m_15_4/4: ${c} EAPYXEIXRNMBMLARWSALAMMEXEUFEPSVRXULWIVEMTSTXHDNGCSHBVPDDYEBZSZMDXRYPIXRUNJTWQXYICHPNFIXTUJZOIKCKVTP', props),
compute('m_15_4/5: ${c} MTSJWENIZNMOGPYBHZBMTVJNBJPLIMHQKZPOBQEKWDLJPSOGTBNVCQTLKBWHCDZMXDJEVLQZDTPHTUFEEJOWMWGQFVYUIXBLXUML', props),
compute('m_15_4/6: ${c} ZQNICASGDKTAHHBWIGDRWOMMGJZUSHAAHBOUMJYFTTPDECIVXALUQJNCPDFJUHEEFVIREAIKNLJNJZPIJVHPVQNJOGEDASYTSZFM', props),
compute('m_15_4/7: ${c} QYIGDJKHVHRLTSDDPMFUCFJSZHIKOZVWABLSTOPRRFLZIFEEIPQVQYBPHCTSDWGQNEBHLYATGRQIDJDGUZPLVCQXFLOCCYFDNXBK', props),
compute('m_15_4/8: ${c} LJALUTGUTUZPYVXGLFUBQWPFBYDVILEGGUNMDEONNQHZATYFNKRPWNFAUWBBCWGHBSHAVOACZUSGIQEONJRIXXRCUEOQKEJSTEVG', props),
compute('m_15_4/9: ${c} ITSKZWHYLTWFLVHUFTWTUSPHMIIXNETPFFTKJOPPNVLLRBTBMPLHOJTBWDPJICKDHELPGWWJLPBVEOFJEIQPNVYBWEUODMKLWBEU', props),
compute('m_15_4/10: ${c} OGPSCINLWJFNFNYJYODQRXITIADJSVFDLFJPENRNPZOJEVTWHDNSSIGFSAHUBSKQPEEPPRGANNRPNLETGLCHLGBCGAJSKJVEKQRT', props),
compute('m_15_4/11: ${c} RCZGQCSPGYYYDXKPTOTSWIHUNJABZNWQDZAXJPKSCMIWKKFOISRFTQOCZQWAQSRACHBUTOQZPTXKISUONHTNMVRDDPXZSRGKPWWE', props),
compute('m_15_4/12: ${c} KDNARWQFSAOFUOBGCAYDLRKKXARALRCTDXQUFVKLOUNLOYJPXUQSRXEIYQOZBHPNBPGIEGBPXYIENEDSUOFBOALBDXTMZITGKQZD', props),
compute('m_15_4/13: ${c} YPCIKAQSOIHBUTOPSDKYFGERSXXEUTBDQNSDXDAZWUFEVMNVHICFYQMGBXUZFNNNWOSWPZQBZBPPVJFHEYZJUQHQTQGWJETKHHVZ', props),
compute('m_15_4/14: ${c} MMYVWRHEHSCXNUPDARRLTMAQHFUIPMUKNXLCCZURAORRBZEVGDMAAOMYSLHCAUOXMYVRPGERJFDDSGFBTYPRCUQFNQEBRKXYYMVV', props),
compute('m_15_4/15: ${c} GPSBRLUIEQYZWKLGRALRBWNMPBPMFHYPQWGAOJBVPYJQGLYUZXRSAFWRSEGJMWIMPMXVCQVKPNAYYFWWRAPCEXRSJKJWEMDTTDMZ', props)
        ].join('\n');
      }
    