
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_16/1: ${c} JPNPWXUXLYDGGUMZXSQVGWSOUEIXHEGBVBVMFSEQRELCVAOZEUJZNVUJAHLYKNKFRGQIHQKWNFGGBONHFLXKTKAARMPJHEXISGFY', props),
compute('m_15_16/2: ${c} PBRRQAPMZUZUHGQGIRHTQDGFDYXQZJWCHVRLDZHUVFTSNQINOCAZRNNBNLZTTTNKTLZJJWKEFTQVOWOMQJNPCCXCNFORSPXRXDUU', props),
compute('m_15_16/3: ${c} PSFJMRQXESYLOLIIGKRVZBFIPRGVGHNSZRHVDXUZAQJMTBFCSYMINPSYEGANXFBHJUJFYWNCTQVAJHTVYTHGZEODSIYZOAEMZELX', props),
compute('m_15_16/4: ${c} FLJWJPLDOKKRXRFWSSXTEDOAIMEHNLXGCHAKEZBYNONKIULYRRDJKCQALFOVWWNNMTYKLJQQQDHIXWEBNAKCYFRDPYHOBOMVGQKJ', props),
compute('m_15_16/5: ${c} SQTAXXSVIYAAQCLVXNAXFBMEKGZHZCHDMHIQLTJGTOBIMPHJBCITMQARVIEDKADRFYMWITQKXNMGBDKVXINGTJJKDFNJYMXLRBRC', props),
compute('m_15_16/6: ${c} FNOWISBJTGEWPHYSZVHMRQRSQBCMNXRXIQKZCZTXMJHJLVYXMQTZKLZDBQEDWFPDANTRXHNIAYTQBUFNYNRRVHEUVERMXYRFRGCE', props),
compute('m_15_16/7: ${c} GALGWHLUUPUGCTDFITDGGNDUVCIWNFNLHEQVUTKBTRPSJZUYNONCPAZMXAOJCWSIGABXILHXGQPCVOKGOKJDYUVKTTYHSSSFIZFF', props),
compute('m_15_16/8: ${c} PWKABCGNZYLDTKJABRKCWRRJVHBCONHCGYEQJAZLPELTUWUALQOXRXTHSEBSZOTPPKEUBWQARPMTXDKMSDAZMLDQOESVPZATFWWM', props),
compute('m_15_16/9: ${c} CFNOVHKPXVQULHFKQJCINDFZCPSNYLGVMQKNOAIHCMQUPLWAOWNIGVYTKNCDKZXHLRWWYGAVXBUUDRGNGVSYNHWSAMPYXDTCIIEY', props),
compute('m_15_16/10: ${c} REZBSUMPZVUVXVDTMNEPEQYYQQLCKHSRFKNMSKFTFYCATVAVKCQBQMYCREPFACCNCHNTXNSEGCTLVGIJYDGQMMQBGFMPGIEQGWRV', props),
compute('m_15_16/11: ${c} CQENKLJOEJJKBZNQOZRULLNYKYSFPAMZGPUMJROJNPHDNFBCAWENMRZTDCSUBHLFAMZBHEOAUTCLLMUMWMRQHAPRZFNPHVIVAFUL', props),
compute('m_15_16/12: ${c} FPXLGTUNGJGYLKLANZGTVJSSXPIKYQUYZOMLLJJOHOGYSWNIQCJMXDWPPASTZBHBDOTCTUEXRFUOAETXYHBZDIGBBTOORSZALQBO', props),
compute('m_15_16/13: ${c} KZGBKUKANTXJNQAATTSRNIAWBSAGERCQYZQSRDQMMRLENITAMMOAXVSNSIQHWCPNHKFQDFDCHQOJHNOFFQSNHZRBRVPGEZRWIKXX', props),
compute('m_15_16/14: ${c} MPYJGFFHGWEDREYZLETDWSUBNKYUOPAXXHFRGWTLRJIWEZLLFLKQZFXUEAOVOYAQJNVDUWECQEBJWWCZYVNWQIEWBMSVVUIPSJWR', props),
compute('m_15_16/15: ${c} PNWJMRTZMHIGEGQXXKIVLLNGGPPAQVLETDQIKTPVKUWVCPOBOONEPXMOTLNFDMLIEBIZVNRSEZTAUHJDBDHROBNHUSUBQJYFEYDX', props)
        ].join('\n');
      }
    