
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_19/1: ${c} JPOEYCIYIBQPHBMBCZWNEGSKQJTIRMXVIKLEWXPMVIXITDWKJHVNKTKKBHODHXEYRCHLGASUHIPXVKWTKQMTHKTLOWELINJIHDWT', props),
compute('m_15_19/2: ${c} GIXIROKOBSQKWKLCNGPNJKCQSRBWSPRYLVADAHXZZMOWJLDCIXQKUXDNFEVNGPPQFCQEYVQLPCKOFVCZTPIXODTAELBVNFEXIQER', props),
compute('m_15_19/3: ${c} EMTUGYNSTZTVLHFDFDXIXMRLNRKPSBGVJXVAEHGSGVLQOMNNTCWOJJTEOVNXYGQTHAYRFKUOQHECZWDKFVPEQPYAMQZOPUUEGGQY', props),
compute('m_15_19/4: ${c} WYFQVNAQLTQZJDNJNIKHGKTJRJVRJSNKMBTKBTDKFNTJMLYZADWJWRYXKUVMXAIDUTQJUSBHFUMZUWQPNKVWGTEPHVCZGLRBBZMR', props),
compute('m_15_19/5: ${c} UEBYSTOCIXJDAOSEMHDVPNRRHJICSISVHMZTJZQICLHXLTYORHJQVACPCEKAZNYMSMSNVDCFFRRWGZHANJFCVGLIAPGDAXTIRDIG', props),
compute('m_15_19/6: ${c} AYTZVEGBOPYDNGPRMZSWUWXJMQDGHYWFVJALIHUFHYPRBEXLLQFRZLTBSQSWSAPWUPEDMRYEOHHIFTTNLDZCLXMVEGOPRQXVRIMQ', props),
compute('m_15_19/7: ${c} BOXRWBYSECUKMELVGYNEMBPCFPOZSMKOJJKOGJVJANWZXHZCKDDBUQLOXVZNVUDVPFWOSRMGGJUIWZBVUNVOFWYIGEMPGOKNDWWI', props),
compute('m_15_19/8: ${c} KCOBUBKEQKJSNRAHCZVEQADPIMKJREBTCECHQESZHGMLMFXAGDBCDHLDYLRPKYPWOKWLYBTGDKBMVCKAIZUOACCLMZWCJZCGWDND', props),
compute('m_15_19/9: ${c} KTEGISEHYYCPOGAMZQFYLSRZBENAIEFQNJZAABFNDNJSGKJLPCSYNXENSXBBHOCMGEQTRPTUQYCORLZWEWWVJKFWODMZZTUDHWAM', props),
compute('m_15_19/10: ${c} ETROPMFXPGWRADQTAJCNRPGUXFOLIQGNNDIBRZRSFPNKNFTCOXFNQLOHBKDQQCZIYAHYVEENHCRBBXFVUVEJIRQWCWSUQCNLEPFG', props),
compute('m_15_19/11: ${c} PDOEDYHYXMJWXGUDRSHSDNBRLGLCBAJBIUBNLITLNGKJHPCZTRZTLOPRVMHQVRYNLNGSUTLGQVKQVJJGANHVFYGVULFAVBYTEOVG', props),
compute('m_15_19/12: ${c} VPOBUWRYNOFVRQZQHNRVAFMHZEGUXZQERFRQMROKKYMNCGUQQTYIXCOODVVOKVNVUNNRDPWMWUGLVOXDPJIUCCGPPDYXATODMGUA', props),
compute('m_15_19/13: ${c} DPSUCGHCZXZZKCVNTIUQIGXOMBHOJYIAVANBTLIXBIDAWCGKKGJTXQMHJQBYYNAJMCOGPJXCYADPTGGPLPLXDGSFZMWHMIPWNSYC', props),
compute('m_15_19/14: ${c} YQFJHTQVMXCSVHKGZPYSUOEXZZHGVRYPEEIKJDRNFFRUXXSKMKBJSBGWLVEIMWYZDMLBMWVGOXBLBCULMWWCWHVRMBZJYFOXYIRU', props),
compute('m_15_19/15: ${c} ALCWRCVVLOBWYDXWJTWWCNURJGQXJSFGJBCNPRWYQCDWSSSVWTPSXCPAGFYRLSNQXDEWXXTSIQMGIPEBINOVIUVKXBPFOLQRYQDX', props)
        ].join('\n');
      }
    