
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_20/1: ${c} IWHHBXHHBVRIAELGVZDAGJPUJFWIBFDQSZRWYRCLPZVKQOUEFOAUJJARQKPMXITCTMERCQYWXUPOWZEOECOAASBIGTHRRFVTZEEX', props),
compute('m_15_20/2: ${c} URVBKOSNHTRLOCEUDNDIFEMDGGBOPTUNPKWNNJPVBMPAKQRZYUCHAGCXOMTAGNDXYCCUTVUWPZFREYOXSGBQMEMALBUZVTKMWKWQ', props),
compute('m_15_20/3: ${c} BAEKJOFWAOLPMVSUPBPFXOPSDGJULSROMFNTZVWVMWPVCQMPXTPXDEHJMICROXIJFRMAOSCGHKLVPQUMVKXHYYKWSYBCNZVOWLQH', props),
compute('m_15_20/4: ${c} UXKAKXGPOUYANYMEKOVROLCRZCDRKRPIWABIPADHTIFLCBESWXSRRSBXMHALRMKXROSMHIKHCUCVGJCGOIGWBEZKNZFONSNJZUYG', props),
compute('m_15_20/5: ${c} DCOBPNEMBRIEUZDVNFACWRITIPGBFPXQXCFNMBYSQJRMGRGYNAGQUSOQPKYRVQBLYNIDWYSLQMQSDRRXQJTFFGJBNHPEATLHHWHP', props),
compute('m_15_20/6: ${c} WQHHTURYHFQVEPSBQZEKQYFFMDDTFIPLTVBHCPJJDDKMDMZTBFLEFDHDLFBSUQRRKYUBFYWDRXGGVGIBDJUMGMBTQZUCQCPDPIWD', props),
compute('m_15_20/7: ${c} QWZPUXPCWFVZBQMSCJOTEWUPOIRESLWWDAHZDSFXONXWKMQNGVHBLKKXZKBCPBANVWCWLKUGFUEWLLIJYTSUJDZTWQPPYHNNQZXI', props),
compute('m_15_20/8: ${c} GADRJHZNECWFDDJVOPIWVPZGOPQYKOUJSKEJIJWDWUWDVSWYLVRARKGCEUHCXEBBDDCABKXFQJWSNCJWONLVVZSCIHSWDBTUHNCC', props),
compute('m_15_20/9: ${c} ZTAYKQASIJQBGBUPSZPXTQFVBDCPOSMBROJKGWCPNFXIPSZLTBFGYRYQMIWQGKJSTKKZCIASNZOLFJIGDHHTXTGZUOMUYOUPEHQN', props),
compute('m_15_20/10: ${c} ARARGATCYUORUCHXZFPCCOGJGEDLCCSHSZFOSVGYJVSBQIUKMPVOWSJWWRKYEAYNYZTFESDCDQRCCMPLDAVZZEGAXGDKRDHJBIFK', props),
compute('m_15_20/11: ${c} PEZDMOLDMYEKHHUIZGIWPWEMHFYMIUNJWTWRHHUBQCIFUAKIIZDKTZEHMPUEIPNGZZZHTBOIXDAMEMOCTSEAOVQUNLITHOSAGOYY', props),
compute('m_15_20/12: ${c} BCZGJSYSDQJIDSBIYBCUUDIQJLKOZRYFXXRJYHNCZUHOCDPZAOLJGDFQLOAKAIKQJJAJQZLQZGVINKZJGKLJKFPLCBNCKUZYOCNN', props),
compute('m_15_20/13: ${c} XTHXKEVGKRSOLBHRROIHBLOTQDEFQRSMAKXLKUVVSADXPWCLMMXUMXEGHHMIMEPJQLKHPMFBBPQBIYVEWXBZKWGDCJEXTBMXSAXM', props),
compute('m_15_20/14: ${c} HKWPKYWLXCDPPOGBRIHRRXTRGEGYBMVVJJLUBICSEMACIDVUYIMICHRKDKKGGNFTTGYCHRZWPCTZPDENOVCLHCJNUVRGRCPYPZNE', props),
compute('m_15_20/15: ${c} LXLNXQRJAMIEJRFTUPAUJZMXTMSDFFBGUCKRZGOUZHMBBNHSFOQGRRXKSMZNUQQVWBJGHDUTXWJLAVROXPNUBJCFJITNDSYVZWHP', props)
        ].join('\n');
      }
    