
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_15/1: ${c} NBFMPLFVTYRTHKUPQKPTEORKGNZAMVXKKOHKGTUIESDTPGEXJSHLWUVDOVQARQMBKVWGQVWFMISIDFZTMOOEOKPYIZRNLAVXEZFQ', props),
compute('m_15_15/2: ${c} XVIZKIXZJUWBXXEMDRIFCGLPTLRDRQNJSBWPJQLOZYEBAPSDZMPLOEWUISXADLFTGXIETSXZDRSZVUJRSSGUNASHVUTKTYGULOIA', props),
compute('m_15_15/3: ${c} TQIZENYAPIKMGQHRSIETJSESOUOSLZGKVWFRNWQWTZLWWNREPHLISKYNSQJEQJHCMZQVRBGDZRIOZATHTKRBYCJDBYCOMBCTSGKN', props),
compute('m_15_15/4: ${c} SYJONEYLRAVHDISTZUXWKENTCNZAVNSJLPPQUCNJTXTZWYIBBLUVJWUQRUQQYULMTATCTATTCZLVBHZRNQNEFOSMYMACJLAGFVUO', props),
compute('m_15_15/5: ${c} HDXONOQIUSCDQPCCZANXJYJRLCUWRBRONHKTFCCRVHGXMMJBNUMDAXXFGPSRRYBNLBZWJLTJMLDCKMFKKSLEQEWVVMNKOXGOAKEQ', props),
compute('m_15_15/6: ${c} QPVISMLVDYWRWILARMBFKUECAERQDGMNTTTJNYJTMMHLHXQFCAGJFKFUJCNYSMKSSWEEMVURNIRRIEYCFYCIXGVFXNFRWAEFJIEW', props),
compute('m_15_15/7: ${c} PLLQELILOJUAUBHLOINLQCPSCCLEDXLZHYZVCCOCOYTNCOFQBQRVBJAABXNTNJHZSPXYAGWJCNLAARDOOQGYTURXKTHBMMNYJKOT', props),
compute('m_15_15/8: ${c} QRJLYXYGYLNMCVXUVGCLOTLVKVNPKSJBKKZSAPYOYWVXYBUPRUZDSRFYUSGXAWWRETZCENYIRUAYHDWDUKQMZKDNKJDZJIURSZKP', props),
compute('m_15_15/9: ${c} UBUAFSTQYTIGYICSSDMIHLSJZGHHDGSUNMVMVMEFOJZPIDSQCUUHJNHVNTSOLKZMSPJYIPCILNTPBYDXVIOMPYALNHXFLIXHYUVO', props),
compute('m_15_15/10: ${c} GYCHBUWKBXSOGHFROZYJAUQNOHNTOMJNUZXMPQHXVOARSVZTZXMUBUJAPAQIFKYLTIHELKOSUNJLPANLHRIWIXTOGVLDRVJIYDWZ', props),
compute('m_15_15/11: ${c} VHFVFOPUFFXLVWCPHAGGZJXPWZXRCHBHOBOMFPYZNNXBLJAFVUQYNIFUKPVFUYKEQKHRMYBVFQLDWNTQIGSTUVRCLQJGQMJDHHOY', props),
compute('m_15_15/12: ${c} FSSJVBRDNKIMZVRSNNXXPKBLCXKOGBWSJUZIDRZMNKLYXGLLUIPCGFOLXMAQJVNHSIDIHYUYEHUNOGUVEBGEYIRKOKSENJNKYVHD', props),
compute('m_15_15/13: ${c} XFYMQWVAWYCOFZYVVAMJVJZTMKAXYNLDTBLAWTQBIPECJLHOWRWGODUILNKWKMTHVZDKDXJCDGVZGDIQRSKRTAUHEYCVRSPJNPAA', props),
compute('m_15_15/14: ${c} NLBLQQTCFESQJJXPZPQCHHURISJGEASNLWKSGAICLVCYVVYMSHHMTWLMAXSTHDKTEXKVOTKAOICQAQTRNSUKYUPRFKJDWROPBLAY', props),
compute('m_15_15/15: ${c} JHUMATNPPVGNKRCKVGGTHVGOAPPMQTHCWVCIFGNZPOYPCQHOAYDCEZSHIAOUUCTIHXEDMMWGNQFQMOOOJNIZKNLHXDPKLGNRXSOH', props)
        ].join('\n');
      }
    