
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_15_5/1: ${c} LAVONJGKQSAAECFXOLNJVKVAINWRFVIRINENVURTMBSSXOMQAURAIBSWJYMUOXZQGNIEIMUXZITWIOYZYGMNCUGJMHJLQRKMDECH', props),
compute('m_15_5/2: ${c} RYOGDVXCIYLOAANQJTUBAZQYQTETECLDIUPRTHWZELZKENEHGZAPDNKECYHRIQLBEFTJEHSFWPSNRUXTKCZUKMBKKQCUDGSOXNQJ', props),
compute('m_15_5/3: ${c} YAGZNBHENVIUDXUPOWDMKOMCMPQCVTRNHTSNTNRVDSIAFYSQOYOKHZTQLFVYEJQBMNBYQVMSCYAIYNLYOZGAPNYAVOJFSNEGLLWW', props),
compute('m_15_5/4: ${c} IHULTZKRDVETAUCUBHQZELOFBAJTEDDSYRIGBQEEALOGBFIUROPOIKDBIWAQHBTIPEDEUBTRILQWTLMNGNQETYEDUUKUWWAIGIFN', props),
compute('m_15_5/5: ${c} FTWCACVXODCKJARPCBLKMREKJMOJTDXHEXHVWIJCARQDZCAXQXBVFYGNCPPVLFEBWDCVFBKROSRPMIFEVRXXRQEKLDIFPTVRCKGJ', props),
compute('m_15_5/6: ${c} DIKCXPRWNNQRBKAFLHQCMABQXMHLSCPQUJUNVCOWXUXAVJBRIAFNHHZSLLYILMXJDDIULIAVTPFLOIIOSLDRPALEHGJGXFPBIFWI', props),
compute('m_15_5/7: ${c} RTCVKQWQKWILAVEZOVOGJIJDJSHETJORKDUBWUJFPAYADEHUMCLUZVXONPCUHGSGTLGSSHGSXTLFSXQBVIYGYTCNAGVEQTYDOBLR', props),
compute('m_15_5/8: ${c} GKSHOPZTIQHUFAUROIELPTIWUBKGGEBKLELPWYWKLWTFXRADUOTTLRXEFJKHLDKDKOOQCQEEAXQYJJXMOUBJHATBLEPQPWMZDXTL', props),
compute('m_15_5/9: ${c} TWUYDTJPWLECFVMNZKITGLFUDFGKZEPSLXLQHIQRJUWPJPXZKGYLPQTWJJZSTHLZAZPKOIAZLENTEHSHAODVAXFMNYHVJTFGCOCR', props),
compute('m_15_5/10: ${c} SRMJETTNHTBYDQMRRGEBFFYAFYFIYSHVFNVHQWOYAVVNAOYLBOXYBRNFBVWAHBQJDGRKKJBZNXWKXVTMVMRRIZULJINQUFVHMEVV', props),
compute('m_15_5/11: ${c} OSYTPRXOAWOSDZRAVBLBCFIRLMGVUZIPWHTVVKWNCXVUNGSNAPUVNQLHOQAMHIODIYLEZCWISIKIVEEEEESQGCAEXQQOWYUURTOZ', props),
compute('m_15_5/12: ${c} CKNSANJEBQLQOKSESMETVKAQFDKCUDGJJBKKBGCTCRQHLPMARXDHDZPJEWADNIICJQRGQNDYHJDBVMBAUSPOXSIQAJPXFYYNWWIQ', props),
compute('m_15_5/13: ${c} YGEXXEOQSRPJFUCILYYHHWIILSISHSDVPYDQJFQXZDBSLSLPIFQEDRQRHXJJSKRQBQWEKMCIMVIRVMAOCAYTYSIKHGDWEBXNOIHC', props),
compute('m_15_5/14: ${c} YRIHMJYGIDTWUULEHEPUBZOKYPWBAHAWVQDOZQGJZJZPMTMJWGNLBBBNNVGHDUVOQTAFNJYYBMEAPKMOYIINROSOORSYPVBTIWXY', props),
compute('m_15_5/15: ${c} AMVNBUWOXIOEDYIVKHNDOLSNSTLUHZHZZHPGKBSIHZFHOLOVFGWGPCKIOEBKZVYHFLRGEMBJMPCCIUDCAPZDPJNDQSXFAMEUEXDQ', props)
        ].join('\n');
      }
    