
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_16_15/1: ${c} BRGJSHKQEDSJBTVEVFCUXRPXEWYNPZNXWGFBPHKTVVEJJRMARCMYRTMQUGCFZFLJIRIASZMTANYSTYJTUBDUUABHPWXDKVAPALUR', props),
compute('m_16_15/2: ${c} QBBHDLPPZKDGBQOAMEQDDLNHUVQQWDUVIXPQPKPVVEZPSALZZTRLZJZNAXWMDXBFHYBOSIAWUMGMTCKKOHVWQYSFRSAVYAMQXCHA', props),
compute('m_16_15/3: ${c} CBPXRBSFGFCULMMESENSIWRQSBKXCKDLEAJXRCKSOUMZJLFTUOOHSLNOCFKYYPIJSKIJJJWNDYGTZSNPJGSIQIRETUOVPOSBBHPT', props),
compute('m_16_15/4: ${c} LAHBXZFVYQMIEUFCWZOEQYHOOFBUHHQFBFCZFKAPDDIEMYNUIIWEOCHAUZIEWHWTXWYJFTROJJOUBMEZBNOBTQLDRCAUZVYEZATG', props),
compute('m_16_15/5: ${c} KETPBRXUIXEEGDUATJJRRDPRQOWKOXYCWKZQSHNQOOFUFNFGPQUTXAQSHBGDYWAHDFUASGJJGZHDIBZKBBBANVHHCROXMRVBTMSX', props),
compute('m_16_15/6: ${c} UOXRNBBLXCVDIBFTGVXMMTGVGTFKYFVZNRNGZHRARLHMMLWKYWOWFPVGJQZGREWQNUBMXPPONAFOOWQDJZIDHGFRUERZETVKDLRR', props),
compute('m_16_15/7: ${c} EGWDVZHNMFHMXMMGUAHAZIBBOBOKHWJWLWVJQEUNOCQSTQHVOSYFEVSRWCYWQQRSJFMSQGJHDYJTBSQISNFWPNPJNNJTNGXHTUUK', props),
compute('m_16_15/8: ${c} RRMCLELIQYESXYMAGNSPDVZSGWOPXRLSJMMAPCKXXEOUXGKTICPYTZDVTIRTOPIVXOLAHULBBTSYVSAXETBGXXRAXBVRTTAFHFDG', props),
compute('m_16_15/9: ${c} SAFOHPUJYAIBMBDIGENFNTFSJTUROQMVSRPJYMXKIPEDBBKEVVYBATCFFPZPGRGSOOZRUZTLFPBNNHTRCULSFZLPLFWWZQCFVSYC', props),
compute('m_16_15/10: ${c} OUNDMQPLIVQLMWBPSKOKFLKRVKRVJGRROQPJCGPYKVKLIQZRNKTOXTXHDACNHTIOPFDVHGFQAXNGTODEDTOQWAUPCEUZWROCUJJU', props),
compute('m_16_15/11: ${c} BTEOCNWCJTEJKXJZGZNCFQITGFRIRJUNVHKMKTPCWFFSCBLJNMFMNPAYKBVWSMDMUKBDTRHMQEBZRONDFXXEVWBPBUKGKJRYBZED', props),
compute('m_16_15/12: ${c} XTINWAZAKNGRNXEOWIFHMGJNQXKOFSGOPBNMYRYSAOEQFLPXHYKPFXIUXDHZPYAGZAIDAYQOKFXYSRIICRINUMSINIRICJMPRMPL', props),
compute('m_16_15/13: ${c} AXJUQAKEKKFTLHYMIDPOTRSCVYAEHLOCABNGEEZPIORHOZGRWYWVWKUCKAUIIOGXSXNJOWVKLKLKRQYMURJQRHNBZEFXBQANFBUL', props),
compute('m_16_15/14: ${c} BBGVIUIYKSNZQHZYHGDAKACLHSWOGBNEWKUCTGUOVUNUXXGLBQNQYCNQFNMAIBSCVCTAQFFMROFWGYXGDUJFDWLMVSJPNTJHRZOY', props),
compute('m_16_15/15: ${c} AYGKNMOIXCVXJXSZJULRXCFGXWQCCYLVVULIVIHEPKHAVPKIGYTQCJSMRSHDBCNBOINCTQZTVSPKOSKXYGOXQWVIJHFUKFHXWPGK', props)
        ].join('\n');
      }
    