
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_16_8/1: ${c} MZTWIPLEEBFLSMOIANVBLIVSWIKEALNSIJRDNGXOTHSTGGZDQXESXRXTBBUAYMVBUGODMAOAWYMXJUYMEVBPFTXTTYGHWMMUSBQQ', props),
compute('m_16_8/2: ${c} JKVJJBNFUTFAUUYVEFEBUCDOAMZFSEXQWTJHPOHJUBCHWGGTXLGRLOPMHSVKJJIYLTLEGDJMDHMCVBUVLHLCNDDSBRBIPICBBRUL', props),
compute('m_16_8/3: ${c} SBSTYDYIIBGEKTRBQUIFPJZXVUKWNUEIQOEAXGEFDPTGQUZKHJXSOBGZRVFGSJZHFKUCTCEVRABICBOIDWEQNSUSDZJOSZDVXQED', props),
compute('m_16_8/4: ${c} GSPCVZPVMRIGQNGYSIFHOWLZSFKAZUOWOCHUHQFRYSKDNNTELGJNQMOHLBJVRGVJSAXSKPJIWLPCYOIPGALKJCFRTMUMOJIZIDYM', props),
compute('m_16_8/5: ${c} AUWYLTAEKQAQUAEQUJPGIHXQXZLQCZWMNFFNWTCIHUKUCDCJRGYKCRFSFZZUNTFVKHIEYACZMIIMEJQKPODHFDVCTFCXANPMSSKC', props),
compute('m_16_8/6: ${c} QLRSLVSKROXCMKPABSMTYHVCJLAHNBYTQQRELPZJCVLQOBOYWPRMIKSDMYIBGDNLUGDAWSZGQISXHZXEDKOWWXVQVHJEENCAGQLB', props),
compute('m_16_8/7: ${c} XRKBSCWRJPJXJAKFCBWQLLEZZBLIBBDTKSDYEFTOWSYAJMISMPUTVBHVZXRQJRCQVKHJSPCZQCRZOTEYANOHLULQASVLGKVDYGJC', props),
compute('m_16_8/8: ${c} RAOXKXCHPWFWFGUQBZGNLEPNUIYVUZNHSRVVPYHPUSXLZATLIRWGTPWDODEKYIOEEFNQVZVJGAKHDWHVLDKRYITXCBDSJELYUMGX', props),
compute('m_16_8/9: ${c} QPZEZFFCEJXLQTOOAKNWSADBABDZZCVBYHHCIHJFHZANLSCZWMWWTZMAPNIFPRUHKLMXPDXYPJYDQJTEGSOYDQPYAVRVAUBXDOUG', props),
compute('m_16_8/10: ${c} OZENLZEPHPASEUXUQLGCVFLZUPYHYOJBOECKCIXDHJTGBXPTPDYXIJSWNXNGHGAYXVRLKVMUCOLHXSYLLWPBCCFOQBCFAFSQZOHX', props),
compute('m_16_8/11: ${c} ZAZROUTXUNQPLWCXIXEEYJYQBFPCNALHPQAIEUGWNVCJZMIEUPUOLOUZXXESYBWBLKQPSNEVCIDBDLQDOHTIEFTAIGRJWHUMFTDQ', props),
compute('m_16_8/12: ${c} LJDWMGXGBCBSQRXGIKRBFRVGWXNBIQCSZCVCKJNPCHDALERIKSOKCKTHKPSBELPYWXFWBLOHTQKGPEBREUBDGAKJLDPJOZVDCGZP', props),
compute('m_16_8/13: ${c} OITOPZSUFSTRXNNJSBWHEPXBZWCWQYPFKFRUQRWCLDTUQZIRAQKIVZVUDDGNMPZEGNCULWZETNQUCRSTVCWCNSXUCKWVMNJSQXFO', props),
compute('m_16_8/14: ${c} RQLWITUNBQPUZYJKGTCZILDQGICUVKOAJVHVNPBWGOCYNRODPLFABFXNDCCESZKSKKJRPOBQIWISJVBXHCMACBENVHTWPFWZEGJJ', props),
compute('m_16_8/15: ${c} TKIWLAYPVCUMTUMVCYZXNCPJXYXKPBGOYBWIGIMWDIWVTFIFZXBIFZQMOVSZZUNIAQCVGJJBFDPFWOFRDMSPOVCPIWVCKGDAQLPU', props)
        ].join('\n');
      }
    