
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_16_17/1: ${c} EYTUZKYBYOCCJHOBQSUSDGNFSDEJPHJZGGZWSTNBXPLGJDZLMZYTVWITIUSZDZPHFMBBJFHWFNFMQXKANPBANJZGWKOCZPZEJFZJ', props),
compute('m_16_17/2: ${c} FAIKBYTOOFOOBSHWWOIHKKJOFVUQVZDWXLVLQGISJHQYZZKVWCVQYAIWTQDXXNLCOGXVATUQKNPHZHCOLGSAAVZAFSIKDNQXBZWI', props),
compute('m_16_17/3: ${c} YTBFCQCIRBZZOMBRBDGBMCXBKHGAWNZJDEXSJKTXRTINWWZEBCPKFJYDCMPWTCWRFPHJOBXTYEVNQRILCCFIFBNVFSOWHXOJMMGW', props),
compute('m_16_17/4: ${c} KWBQKSFZIATBBRXTUJFXTWNTZTBNJISRDKVKUDZEALOMWZXMCYYWWDGYQZNDJHLAJSZFDBBMHQEGHTKGZDUXHQSDZHMIPTTCYQAW', props),
compute('m_16_17/5: ${c} SNYRWQKEBNPXEAIUFZMNACPXWRUJGOBFIENVTMVFBOWRJYRMXWFHBBANJTLOPINOGTHIBJJWBMOXHTVWJKUMWILELHLALBDSTRUT', props),
compute('m_16_17/6: ${c} ZLPYNTQIMOAKTTMNAFKGEMVBZAVLYYSTMQNAKAXHMJAGWBVUZSKMOUXZGPQMZEMELVELLQAKYFDDCKQGQLILLFAGUVFKILTBITXO', props),
compute('m_16_17/7: ${c} QRIHNZKQKMHXOXAMQIXYCFPQFLDJIAAKRFXTOEUQZJVEVTPKKCQEEXZYXQBRXQLFOQVKAYGEIRBSXTGZNZRAHLDHPSOZKDFSUEPY', props),
compute('m_16_17/8: ${c} QHAPUGGJKTOMHZLHXYEYXEUWXOFVWNWAUEVMDKNCDAFDDOICXLDKYAAEBGAJDQOWLVJQQBIVZSXLNJLQMYKZRUSKCQQSEFOJDKQN', props),
compute('m_16_17/9: ${c} PGPZNBEYGKQRKZBKJCQNMKRUMBOOHMHDYSHMQNWNBLVXFGJWXLNXFGMRDIFCFFFVUCFBHOLMFASMZGZDKSLXOMISHZCCXPNZTWWS', props),
compute('m_16_17/10: ${c} UZBRNGEIOUQHANSSFFBIAJBTJCFGUQKOKKYXHNGAWANIZEOTUIIVTHCSPMTWGMIAQHIRQYNPRAGDGOCCELIALAJQOMCKWGNLOJAV', props),
compute('m_16_17/11: ${c} CLBPKZSWBAPYFBHTETIVAFXJYFHUVFEUOQLCPFAXZDIULQLKEMJYPAGOVWNQNQEIMZZVOXMTXSMCCMBAMOIPBUDAFCYJPSLLRZSE', props),
compute('m_16_17/12: ${c} IDTCCYPOSZMHANIVDFSGUDJXIGVMRZNUVIPFMBOYMVNXNCMWREBYPWXGHFDXOERIBBLCDAHNRTTWUQXZLHYQDCKPOIWQQVBGJEIM', props),
compute('m_16_17/13: ${c} CFQDFRBIZGNPKHEVPODRIMANFYNWCPBCHPWHFPRVPRIUKBOYGPGHRYIMONHADHYFNZHMWBQPXTZTLZCCFTBYXCHTUGZNALUAHFGE', props),
compute('m_16_17/14: ${c} WITUIEDMRROUKIOBOMGWBJCQITPQLZJEADGTKGPSDSXLARPZJLYPQCVJKHPSXOZARCWCOOLJHMGIYGNCANWCDENVDNQANABGWRSA', props),
compute('m_16_17/15: ${c} PFXHONPFGSCGDYQICAEOMYHNNXEEPLJMXSBJOHNDQPUDQDBQCHQSBFNFGUVOLKHXUFNBTHYZZEOUHYYYKODUKOKRUJWRCPLPLHBE', props)
        ].join('\n');
      }
    