
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_16_16/1: ${c} EZLMDUWDEFRGZJLYSKDWLBARXNDYKRUWNPGIJRTQBSFEGHULFSUJLUACTTBLVLPSZUWTLUFKYJAPCWLYUYOWMEDSAKRCRVDMUGFA', props),
compute('m_16_16/2: ${c} NXQAJVTVSOWOGLOVAKNSJKFXZVLRDAVGERESWXTYGCWLWUUQLHOKKMXFMAEFXNNXOWBRUBFWEHNFWLMMNESOTMPLZKRAYOUOXWKA', props),
compute('m_16_16/3: ${c} PJJNBSDIQPXAYFIGNGUGYQIJXMNTEWHQTEXBLOJXKAECATNGMZWZBXDQPDVVLMOUNFXKAGMZKYGXIKBCHUZUCTCQSRTQNPNEOUPQ', props),
compute('m_16_16/4: ${c} WLMJHBIIGNJVOSQGPKXFCMNSYZITWRFAEBBWIJTQSUXSXYFBSEFTVWWWJEOIHFXEVWKFSCSZVZDWOUMARHDYPMEEBTMQMJESKNCA', props),
compute('m_16_16/5: ${c} JJRWPHCGGYWNTBYIPCGSOAJSCCPSGKWGADBVURUJMNPFTOHISOUAQUEWLQHNPKXDKJCWNFFEBLJDXZUOCCUJPPCBEUQUESXBONQZ', props),
compute('m_16_16/6: ${c} TAXOYJNFVXAMGMNTSEWEHDVCLDMNAYRLSODRVULCFZQZXWXXLETGQJRPIZIHKNZUGGVCDGROSWHWCQVIGEYIQWXFNTPPAHVSNZBZ', props),
compute('m_16_16/7: ${c} QRZQHSMRRPTERKGLDNTMLGFYBXFUKLINZNGDTRRUAASVEAHNUCQJRCPMIYQJECQHYFVCFDFFVEOVLIRDOONGAXQRHUJCCPNREFBG', props),
compute('m_16_16/8: ${c} CQWBWCXPLKEZJAOWVWTZPHILAELMSHQPLIYIRPLRLVHUCDVLOXUGBWPVCZEBIPHSBAOSVNRXBGJXRMMWYVBTUBRMNIGQLSSUWUSA', props),
compute('m_16_16/9: ${c} UTHGDXXGDHKEHXJUFYSFYKMPWVKEZFICOPSYIJDNVGGKJTOOXBWBAPTRMMUNAEHVBAZXKLUFIZTWSBMLUGGGAIXKSSLRPNEOZBWX', props),
compute('m_16_16/10: ${c} VAOBEQEOHQDDMSOTWHVXVBJQTJIZBEEPWNUNIZVBNFTNKPFVLEIBIQZRUWBRYAODTVRFWMPILBBGMIOEJCQSUBGCAFDGLVLDFRID', props),
compute('m_16_16/11: ${c} RNMNJYSGVAPXBQUKSUIJQLBOXKWVRBHTNOERFCBALOOIJITUFDMHUUHGGCLQCMDCEQGIOVKUENPMSAZTTCHCTEPYLQPMHVQVPWRY', props),
compute('m_16_16/12: ${c} JQVFBRWWHQBJKLFANQLORKNLNEEHRRATLHNIDTDTAYXHVKKZKDYRDMKAVHLMAQKREACMAZKYFQXQNZYTMUKSCIKZMTKYMOFYKAMB', props),
compute('m_16_16/13: ${c} WUFUHMVISGADYOWOSIUVFJFDLHDEGOVOMSJNBNYFRHIOWSUNVZDRGOWPLVEXCCIOWERIJPCVJNWXWBNSYKZXHREDUAHYPKXPGFYP', props),
compute('m_16_16/14: ${c} JPHKRZBHAPMKSOQYRKMXHRNKRHFHUDBAZSHATPAPRORBDAYNXFCHZXGQWDBWWQAORCTKMXIONJTZSORGBXTDOXHMNFKXYSWJULLH', props),
compute('m_16_16/15: ${c} JPDEFMBWPCTQLMDIHWKIXXNLGEVPGOSKZYIWCUXXJWDHBSPJWQUGTSKKSWPNOEXLRBVUCWGQVDRMYZISVQMUERADCTZPIOZZUZAT', props)
        ].join('\n');
      }
    