
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_16_12/1: ${c} OQKDRZTRFNIGZWFRWQWGPYYDJPDJWMKQYAWPRWCBFJNLOCEKJHWXFUKPDZPJENQHDCZMLZDYBGLFVVRITLMPUBLUQHFLJWTQSZOL', props),
compute('m_16_12/2: ${c} TBBPCEOPHATMHVUSLOGDOBOSLGZZYYQTCPAZMYXWRWNHYTTSUYNAQTRWNNBLPPJLVOAYMEZEOKSTQAELXASHXFUHBJHZCAWPSUGV', props),
compute('m_16_12/3: ${c} NVALYDTGJGIXDABDETJKNHNGFYPPOTKWMTLRFOLHKSFXDJVDMCFEIQQIBYEQXYWOCCIKWKQJRFYQVSHIKWPUZLVTNHMGZAABQERD', props),
compute('m_16_12/4: ${c} XDLCHIGKJZOYLOOHAUPXJSNLGOUIJONHYMYZTPCXOGBZWOOENDQZSNVJJHHLVMYQTAMMRCNPMDZRRGATLOTXLHLRJDNNZWUMZLXN', props),
compute('m_16_12/5: ${c} NKNUQTJFKVXHZQPWRESPWMPLVFQJQSFBWZAUAFDTSMBHDBWUIUOPQQCWLMXOOEVYJWUTHUUBHSDGQRLXAYAJJGTDGIIFUWICAYPS', props),
compute('m_16_12/6: ${c} TGWTIIULYUROGJUVSINSUQPQCBJTGUKOUDQASSGCDTYTMXLQNSQHEECUXCDKXASZTGECQMCSCBCSWXYPVDYSNZMERTHAERFZIERK', props),
compute('m_16_12/7: ${c} FNPVXIIRWMHFZGXVYDBHEPDGQUJLBIIXNXNKAWSLMRRUJQSFLGEWZTJIMQXUUPFLEIGYOYLDRUOJFEAHHRHTAEBRAXPEMJBXUENQ', props),
compute('m_16_12/8: ${c} RNPXAMFLVDADVBZMOFGTENZCTWKRFNTDHMCRVCXWWBYWCQELGHSHJWETCCJMLZFFKKVKGANKOMYIKIHWYXZUGSEZODOLKXNLJANX', props),
compute('m_16_12/9: ${c} HXEQWXSEHAJPUZITYHHZBRGBXIKMXRIFVGFEFCFVDPOUYBKYTLGOQXHMLIOSKLITYNHGEFJAARTQABOTEGSWLQITEUXZBECDKIJQ', props),
compute('m_16_12/10: ${c} OFKHALHTQZQZLONWNNMQHQGPZURABBFTDPLHBOGCQYCQMNRROTONJUOAZWHVBOVCJJCTWQPSMILXDXSNOSFFUNRFTSRAVYCOZPEN', props),
compute('m_16_12/11: ${c} YHNVAUBNAAJPRSXCJSEVIBZAFLSBNYPNOWUTCYTEUOMKFJZQIBCDPQOOFYPXZFYPEJSNWFPAEMGSREPWTQPATYZBMFEEGARDBOUM', props),
compute('m_16_12/12: ${c} JKYTRGOZNZKULLVVFLJXSWFAOQMULZJHYHZJOKBOFLYCPZBSFALTVJVVPFMXHPQSYHKJAEEXBBJDVIEYJTSHWWQNGBIBRLHABCZR', props),
compute('m_16_12/13: ${c} EALOFEPUGBQHGRZYVMOCVHZXROXHYUIEOAPVWFJXIPDVCDDQFAJCANCRYLQIIUFOOSHKSQUPAAALEFGVVSLLIWVYPLTHCEWGCYHW', props),
compute('m_16_12/14: ${c} OBIEYFEMVLENVSXHUINDKDUMFDGVENNEVBPAPLPZMAXOWJEBVQIPBYOQJCWPFZDDRSGOUKPKFNPXYLEYFKJFVOFQZODKFZHXLLTL', props),
compute('m_16_12/15: ${c} LTKVAYTVQFNZSQVLLUDMVVAPHLTZFPRKILDMDJEVBUGVHCZQSYQUVKEZCPMVQJKFJMAGCJTRXBFXBIQMOYYNGLERIEMFDASBRJGO', props)
        ].join('\n');
      }
    