
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_16_18/1: ${c} HGRHGQMMKYEHSNFEXCSULFOUQTQOGSGCDFLJKCZXUBDOPAGZABZUYSHJSREKDWXPDORVGGGERHSTVRYPEXNEKXGRNXOSWLJQGNLO', props),
compute('m_16_18/2: ${c} DHBDUQDZMPNHPUIVFRQQBGELMQCCGEVUTOUSAADYFXVTVLDIUMNJLOIJVFHLZNUVGIOCURSBSIHGXGYXPIWFDEUIGITDSSFKNYLQ', props),
compute('m_16_18/3: ${c} FSKKHSAXKGCLXIJSZJPLNQXLZBBETVLAKSEXZJEETEMNMXLRATNAHTXFIXDFRYXCLLKHODYEGVGDUAKQOKZMIRFLBPQWCAYIOBNT', props),
compute('m_16_18/4: ${c} SOFPQUZWQBNKGODKGMHJOFPODPMUQCLIMPMBBJQOSLZVHPDKGGZANAOONFLIVUCREXPWELRCYYWGZFUHKOMIFIOIQGDHCIMMJYDJ', props),
compute('m_16_18/5: ${c} GHWZUSXCXQSQAJYKNANCOMPQAMWUMLFKYONISNMGJSAHARRUSWTFKSBTPEIESEHRBMMSNLYHXSMXWCAWSEZNZCIEOPNAPYQOUGHS', props),
compute('m_16_18/6: ${c} SFHRXIWROVMTPEFCTYIPBHSHEPIBWJBGRCACSQQTPFPBIRWBQVMOIMCHJZSWMMPVVBNJUDSUPHVEIUMXUYEXZZZNCGRWYADWNSAG', props),
compute('m_16_18/7: ${c} GDKQJYCBZVHZNSRKBIIAVZLVDFOWHCEKWMTMXLTXRFKXCLJBYNFYSABIYNPHESJPGHUZTLGMTYCOGPBCQJATQSSMWNGCOHBDYMXY', props),
compute('m_16_18/8: ${c} FVCSRFQZNAVNJYXWNALFUTZSEVEWXJUENYIZOMOXZSSPTUGSHFIQFFPKHTPCEUDNALAAPXEJJSXFTTQMXNOAMWGHJPWDGUMVLRDB', props),
compute('m_16_18/9: ${c} UTGBZCHZKNCGYHKHFZIGJIQLDQEFRDBWMNQZNUVFKGWMLJILVOUIUHZGUMSAOQXCUGTVNZWZZISPAAJFWAJNUWFSQAJWNFCGJUZC', props),
compute('m_16_18/10: ${c} OOQDRKFCRCFJIGQJNVXXXDNNWDQGYSNAJASIRGTOOMRRUEVQHLYHEQKSLZUUGOVIYWNGGZEPFROVCSOCYUBULWYVDGOYXQXISENG', props),
compute('m_16_18/11: ${c} LVPUESKGSEGEDPVWBOPFONHCESRSNXRJWJDGWAKWKHWOWCPEQPCPSPXHVSEFQSPIGDUNMMEUICRHOHEXWNMVMPHDJFBHHKRNZBFU', props),
compute('m_16_18/12: ${c} XBNINVPTJBDOLRBLIMCSLRZPSBMMMFLIJCSUHEPPIQIERMUFVWSCBMCTTFVQVLDLYZBPTYHXWNNACLZHGSBTRHWDISIGTXKUIOTC', props),
compute('m_16_18/13: ${c} CPNFTNGOKSARYQHQJHDTBIMBRRIPFKQDINPCHBDYBMDXVDFMRXWXDROSSSDJBCOQWLRZFZJXHWXQVATXUTMSRWEKVQZRMTMSDWAK', props),
compute('m_16_18/14: ${c} VMEIWUFWGMXCUDMURRKWZBQKRESYTXTSNKTSNXPBOWXTIHNGLAJALDVHQHYHKTFWVUBKXUEIGLNBZGINPKJEONNADMFEFQJTYWMV', props),
compute('m_16_18/15: ${c} QOFLDCFRQIJSPSWSGXQQTYAVBKBITFUJEKYFBHPGGTRBCHRVIUMCFCOPLBTOVNFBYRDGLQPVTPOUGSJYORLTRJAMAVNMTEZUSEDP', props)
        ].join('\n');
      }
    