
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_16_20/1: ${c} SDCQMEGCVWJGRTBFZDDHHQTGPNXDPSMETIYQEODJAYFJFAQDNLAGJANLIRRDHAERYEJQHKZZJHWPEJKMATIDTZKLDNOJGPJVSMQD', props),
compute('m_16_20/2: ${c} VEGEZTTBMIVGQCNEWVFTYYYTTZYOXMHYWULLOCZWUUUUYCWZIOQALPLUNLVKZVUGASCYYRXNECLUUPTQOHXVPZCVCXIDBAZIQHRH', props),
compute('m_16_20/3: ${c} XKDYJFCVWOHCQUFGJWDUIWKLYABQBLPXFRWFODHIWKLNYDSDQIYJCAZFWERHUUGCBGRXCIYNMWJJYFPFXSSTIPBGLCBNAOJOYGWH', props),
compute('m_16_20/4: ${c} YFBAVVHTPDJAGOQGKWCOPZMWUDBREHLVDLJHIVAVARGGGXLVUYBWYLHFQDMKQCOFWPTDYHOCBZNIVFQJLFZMHVACSZBCARNMMFIL', props),
compute('m_16_20/5: ${c} NTWPNTLDJBJUTBAHWLAPRGPLXUCUVNEUVGRFFUEJQFCHXRCWRVUUGZXFOZGPFBOODWPEJNDIRGPZBYCOVRILZASOELXXCIJKFPND', props),
compute('m_16_20/6: ${c} YETZLEUEPNAFSBBUIMSSHASMMJUUHKSORITKALYBTGVPUXOOVUGKMCCBXVTLOGJLCBNFZHITZXNVOUUUPRWXFFKZEXRFJBJQBMOM', props),
compute('m_16_20/7: ${c} YPEOBTTGDMNBADOFPTXJOMTBHFOFXGJZZCVBIFBILYGSFUEWEWTHIENMTLXVHLYDDXEBRWLAHHJESHETIZJIJAISNSUHUTTFFEZL', props),
compute('m_16_20/8: ${c} ICVJIGPBLAEGAPRDKAOQRIFSZKIMJVGAHTXGFONWVXXKTWALHOARJQDYQHIBUSNNYBFRROMEPJXGSDKUCFKAJSNROLSMHDBOALZT', props),
compute('m_16_20/9: ${c} VXSBPKPLGNRRQVMZWNFEYMDCPQTRDFDTVHJKJCAHJAPKUHJXSRMLLZSBDPTKJVCDEVJABPXQSMPDTMEZJTFYOFDVRMCEVXQRWWQT', props),
compute('m_16_20/10: ${c} ZWCDXIGCZPRWXEKYXSXJRBHIZLSPCDNZLZDNKQUCVZSPSWJGSZRWQENHOKBPLRRTXHRCAIOKGGZUIVUDAYNNCPOEOKIGEEWQDOUP', props),
compute('m_16_20/11: ${c} BNNNQHVCNCFEGLRLHMMNSKYTSYCZIVHVUHLHSBGMZONGNXQGUGPIRHSEZQSEIYHTXKGLITGKPTFDLZQWPDNLXYTPWLPKOMBVFWMY', props),
compute('m_16_20/12: ${c} MTYFZIJAXSXAPHJPUXKRYUROPKEQOAAJXZPTVJWVXBRSXNUCFBTNSVCGIHXGHZYXJZVPIZGTWCOYPZPPWRZXJNUBTUQSHJGKDLKH', props),
compute('m_16_20/13: ${c} OABVWSGMJSYWADVDDFLMQMWIONXLYAQXORPZJJSGTCOCGEMCPXVGFFCGNCFWDKGWROKFOUMTRYFSFIJIFXVUKZXPINYJFFBBUJKR', props),
compute('m_16_20/14: ${c} ICTLFKLYPUPVURZIWGQPEWLOKTSQFWMFUBLRLQIBYDXZFYVAAJSHQJVQHUQXOBMUWMOVTZCCIHWIHMQAYYYCZDAIQVXZKZJUIUXU', props),
compute('m_16_20/15: ${c} YOFWWLRXQLYXQHAOACZDDRNNJBWUBJBQJHXNPTWJXFDCQXXYYBCAYTLRKOPDSVICUPUGZJRDCZBYLBXDAXVTPDUDKARBGAIYPALK', props)
        ].join('\n');
      }
    