
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_13/1: ${c} CCNHVWEBXNCAPJUEVTCLNBHRDWCRWYRXLETIBJFBPHLMXJVJADBFZDWAFHISXBSSOKCJLUNLTXYQDIRQABVHYMBPEWPXCQAJHUCK', props),
compute('m_17_13/2: ${c} GOGUBQHASKPUSCIROJPVODARTCDULXDKDAKLFZKIIQBHDLEEQSYCCAOGIECFGJKYSQGBBRZEURSBNGXWHGDCXRXCAOEONLYPNOVA', props),
compute('m_17_13/3: ${c} NMCBAAYPOKLPJXMALRKADNRCPCQJGGAPGMEJBJQOBVVTIZLWLMXUSWKJBUOFLGHCDLDEZZHFZWJBUCTKQGFQJMKDRLGNSFNYRRBA', props),
compute('m_17_13/4: ${c} BXVXTRPYKPJWKISZPTGVGDSYRICAXLZEKWSODMXVCTXDTMMQCIKPAEPYYGTPIUJDENRHYQNHWOKHCKRCQRMLGLOIIMBGQPUATMDM', props),
compute('m_17_13/5: ${c} KDNGDUCLVWYDOQWOEWWFIVQMKLVOGTENWQKOESHCBVTSZUNHMXZTNKLWSXRYXIDWCBMFKYZFISGLIENDMAGMYVLYLNNSICSAMLJE', props),
compute('m_17_13/6: ${c} RDAIHYVTQBABZYTVXHXYMSRMHVVQFSSOWTEJBEFXWWOPKQDYCGAJOQNVGJIZEEGSBQTAVDVYNYICDEIIDSGESHGLOAQJCQNCKIYH', props),
compute('m_17_13/7: ${c} SJCRPDYSENVULYXCBZJGGAJKRMKKARTXXPVVJUOQYVKSCAXBDCYHXXRAIPBNZIUTYYRNCVMCICESYICPXBNZBVLRHTPCNXBHCLFG', props),
compute('m_17_13/8: ${c} DATQSZREGPIFUOMKLDYAKEHFTBDRYVEAZLWUKQIPPAXZITPYOXUTTGBCLAQONSAQFLUCHNXUFUBSUBRXRLQNOFZVTDQEQJRUWNFE', props),
compute('m_17_13/9: ${c} BUDXSXJWXYGCAWVGFCGBSPLUNXYKFPLOSMXSOOZXHRJFEMLCEHSXDRVLDWHMNPVAUVDYJEXJSXOLQPYTNLLYEMGNCRYDWQQSFNEU', props),
compute('m_17_13/10: ${c} PQNQSXSXJZLAYKRGROEKVWFCFKIDXGBKUZFYIMPHRDSFOIGOONNURTKKJQBHKGOFPUPNCBDWPNQIWQIATCLLJYLJUPVJTTRDMPKL', props),
compute('m_17_13/11: ${c} LZYDKQHGEKBKGBDVVODUVYARLWDHWTPWEXVYCEXETSWWEGDASDLZOVNXSQSOLEOKIMJRWMKKLTVBAWEBFMUZVSJMFRACWGGPOLON', props),
compute('m_17_13/12: ${c} IOMZWEKFFWQXZKNMJNFLAJKISPQHYTSKMZMAPYAZAQOODTLCAZBLCKSFRDTQSNXXVIOYITBMMEUQBLLLPCZSSVWTYCEWDVTLDJDO', props),
compute('m_17_13/13: ${c} TWMWFWOAMYCBSCZNJMWLAJLLBIMWIRAGLMENBFQKIABFSEAQLXBHUIOWSWEPLYASVELXSLBXXRFUUXDGNONGDGJBPOWURJMQVAIK', props),
compute('m_17_13/14: ${c} IVZVNZEAQSWUBOLRMWAILSYFJDNMUSYJHBDPHLFKLASKGYWGOWRPFRPSLTIEXIMIZUAHCBXBHBHWGKRZBPEKSITDBUVUXSGXWUPU', props),
compute('m_17_13/15: ${c} XMNVXJCBMLGUMHUILFMQAMBPYDGIEBIXJIZHUOEEAHSDLGWXYQMGCHYYMKMZQSOROYYAMOWBSYEADJOHJXLUWVOXZVBAVVPMMYGW', props)
        ].join('\n');
      }
    