
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_18/1: ${c} ECJRVQQAXJVUXHNVBWUJYRUDNVIOGUMHCZCDUHDGOVWATVKNTUUVOYQJZBXFURCHAPMDFHWPYCHGEVWVFPRQXNWPFLXECEIROSPJ', props),
compute('m_17_18/2: ${c} BIIPLWXVPQVYEYQEFCQIZKCOTVRHPQHSSPZABTKCSDFDLBMELWWKAEOBMGXPEXKRHDOBPNEQJASOWZBIFBRXUKNESMMFQFPXJHOJ', props),
compute('m_17_18/3: ${c} XGGZMWBFRYYBSMIFMWSMOTDHTEMWWLNOKOPXFYULZFGVXLMKOAWCUPDGOSCQKGNSTKQNNHDFRDQGRFATAZDXFMBALQGKPMQXLMUN', props),
compute('m_17_18/4: ${c} WICLSPFVZZLYVWNTOYDOIOTQTMCEKENMLXRKGWGHEAODLMESTMCNRCZYPZYLMGDKGQCNQZGNTBLULJOEESDCEYVSRBWAXOTGFQDJ', props),
compute('m_17_18/5: ${c} HQBJIKYHYLRRYMRURQFJLFGYPHZBPRTSLKORMMBKYTHCLEJPCLGVHESAEJPDJRQWXACGREQTQCMPCXMRKFBOMDIYZCTLBMUEADTE', props),
compute('m_17_18/6: ${c} DPFAZEFVAFWPCGNQXKVQWZXHZGAPJAOXZHWWDUQAHVJRTXQUEICITXQHABQYFMLUJGMMFHCCXJCXCLUOBBBIXCICRBZQVKAOKNAH', props),
compute('m_17_18/7: ${c} XMXSBNQGKSSNYPAUJBPFUVJRFBWYBFPHPRMOLKVKYIWWJGQXHAVOMKCMORYHTIFLURLJEVKYGVFCGOFLESEPVMESOMCHRLDIMONM', props),
compute('m_17_18/8: ${c} XFPSTOWOOKJNHNJUPFHEIKQTHQQNTEPASGBSIGHMUOUMQSNJQEAEFSSEPPTNQDHXAGVSHCDEDLCZPMQMVNDTCOEGGOZYSADFTDPX', props),
compute('m_17_18/9: ${c} JLMDMUIKAYKDYUHBWTVXQLUWWNXZMOYZCNVJHZBOXKZQDMFMVCYAFTFRJKHWFXQVOUUIVLXFLUMJDIXHMQTOFQWARNHRRWQRSOZK', props),
compute('m_17_18/10: ${c} KMDUZGMQYJBCCHJDBDAWOBZSTYEGLSGPVVOGBZCKHVMHBZVYRIMFSDUMABKOWYSXMKATDFMXCWGFHNTHFOBAWHDLSTUTKECTCTRA', props),
compute('m_17_18/11: ${c} YXSUOQKNNSCQBMHRHPGNGDPPJLUGQQKJHFESKKYJZOHGJSDYTVMSYEFELFKBDREKDWJOXHDLUNWLFRLWAKXLLFVABCMETVOAKNTJ', props),
compute('m_17_18/12: ${c} DSYMNWKUVMSATMLFTCIVTDRLLHYRDMYVYJEFIXJOYXADLMLFHWBNXPEYPKPMZDFCLTVSWHFQWXSGVDMQSJFWCWRQTXXWYGODOGXP', props),
compute('m_17_18/13: ${c} MNCEOKFDSKEWLBNKULZADVBWKOMWWUEMJXQJYEVQQZWUFNYALSHBRHDZALQBRIPOZQQLGDUIBHDNIWOTNBVCOVHBVXEKDLMIOEON', props),
compute('m_17_18/14: ${c} CJNJMGJNBHXOXRBLZVVCQTIOQJOHEZRPNWUYCCOXODANNOBMLNJXZCGZJGUUTWDRJJGMRBHORNGQDNXYEDLKVIYJHIXBNYTCOGHL', props),
compute('m_17_18/15: ${c} ZQCCWJWSJLAEDKFYICHAEKGXVDXSRGEUVLTDBLYHSUGCPSCHBUHCFMOGZRJFKXWJXHCNDQOBNIVMDGPMHLLEUEIIXAOWHRDNAMBX', props)
        ].join('\n');
      }
    