
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_4/1: ${c} AFMENKCPSLILSOHGROVJUYUPXPMSLPVIJLJGGDIYRSHNHOBNLRGSWLDJODHUGVSLYYIVYODFNPPIEUUDNOLHGJXAOJBZOLAOONQE', props),
compute('m_17_4/2: ${c} WTIXYWZIMMTXRPIDEBWBJZAUBHKAXUIAGKJIJENBSHKUIMWMYDLVQOHDBYTKLUIJDQBNFAVEHVNKABVBMZPWECKUZVTXQMAYNUYO', props),
compute('m_17_4/3: ${c} OUVPRLMUFOQYMKMKCFLDZIUCIIVLEXCKVYQPWWBJDTZHIUWBVNJIZHWUESHNWWOPZRXDNORJVYGAHFYARZVVQWBWRMFOHYLOQYVZ', props),
compute('m_17_4/4: ${c} FPKHZYKTSSICJCOUZMDOGMYNBQQHWLYNWJXHIEUXMYNJZRTUXVLBSEWLJZQZELQPZBFKEQXOXKTMBWAENOEVGRZRGIGNIFENKLXK', props),
compute('m_17_4/5: ${c} GOSRAKJJVIPTUTHJSNYFNHOCXCTTDWRYUNBZOKJLEVODAVSQFWUOVIJOQCDCWWOQFXZPGKXDSJXWVWNVTMMFSBRSREZFYUHNXINN', props),
compute('m_17_4/6: ${c} KQFOGHYTHZKUNWDTYWDPNVODJFAQFXVVTUNNWZCPZFJWYYUONQSASHKVNIYESYIGAACOXEFNYTZXCSSECQXETNBCCUMWOIFSRCTP', props),
compute('m_17_4/7: ${c} DJPQRNVIXSOVZBMIXTQEVPMIDDBFVAXMRIWVELNKZBSTXIJOSAISGZDHODPDMTIHMDSZYJNPOPQIBWFLTEXPAJYKJGWVKBPNOJUQ', props),
compute('m_17_4/8: ${c} UVMTRYCJRGWLRIKGKVLTTSPZCOHKFQXJMGITJGZDXJQUFBWYIXHUFHDJFMTBZDYXDBGHQBCOHHWPWOZTSOSBLRLFLGPYEEMJMIUR', props),
compute('m_17_4/9: ${c} YBDRPUJLNOGVUQOBDOPSGIIWVJTIZSRWWEYMWTQTAZMCYMVCVNGGVZNWJMWQYFIHMJCXMOUXEROVMFUBNGUOTLYUUZONQMBKOGWD', props),
compute('m_17_4/10: ${c} BPKXIXSMVJBJQNPAAAUYHROFGUTIHFFAZUMLLUOVGKBLHDAHNKXZCDKMGPYGXQWJWAKYSOGWRENLCIORHXHDSYUQJCBPHNSRSDXQ', props),
compute('m_17_4/11: ${c} ATWTFGCHBGWQQLBEKOUGOOLZKPNGSTHQBKBRHDJBYJSMDYJTPZKSYEPPLUHUBGNZIIGJYMBKBYDVORFCBUIILDQPOYMTMXUUHMWL', props),
compute('m_17_4/12: ${c} ASWYYVTKEWQQOFRMFHZGBDSSGXYPYPHAFPYGIXWVFSERDCMBIOMYFWUOXJMCDITRPRFZIXPOGORXWBNADWJGFQCKLUUSXWZDFDZT', props),
compute('m_17_4/13: ${c} INVRCEWKIXGYESOZANQDCKBDLNVICIAOPLGTOYNIHVQIRIQICTFGKUTHOPWCMXHEQLSUZMSDHJBDCAHZGVVLSQMVYHSLHXWGIAVO', props),
compute('m_17_4/14: ${c} KUSAACWLSXOYLEFIEMFJDFLRKFPBXKTGMRTEJMGWTHEWQHEKVYUBLZQERPGIDFDSISOEOSXQSTETLLHJBICTOIHOOXXZDVJPYUXH', props),
compute('m_17_4/15: ${c} DMQEHIXRRARSXZLANYPHKSKFQRRZMLCOLMUZBDXYFZOEGRAKYRHRZHMUFYHUMQGIXGCQMWVXBOERLLDNBLEKWKDNFBOZYTJDXNXG', props)
        ].join('\n');
      }
    