
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_7/1: ${c} OROOIMEPJWFBJHKFNQIURDPEFYJAWELIEJKPUDSFUVXDWYBVEKBTUQJTDUDMUHDOLVPECEQEYJZMTRZZWABTCMZTOCPLHXYWOAFO', props),
compute('m_17_7/2: ${c} PCXQTCUMQFIXBZMEYGRHNDRBPLWZSHHPNGYNQBSVJOOUBPMQGEJCPXZMVZRAUXBRUSDZVOJSPRCMWKINAHJKNAKHIJHVGAQYEEMC', props),
compute('m_17_7/3: ${c} VHKNVGLXVXRSDZBKNDWDFNWPWHQXERVURFRSTRSPAGHFHGKOHLSRTNDDOCBULBRGWXDCNEARTSXLVDTIJIWQZOZESAIKDCYXDYDV', props),
compute('m_17_7/4: ${c} RELPHMTWDLFYIQKIVEDCZURNRDOZYFFESOOZVZANISQFYFHLZUIEJSIHHQHBURSISUJIFQMONOSGBDQAVOVPXYHOHXLWGFNUTXCE', props),
compute('m_17_7/5: ${c} VUHUNRTLTXTVIZIOZSSBNQRCXINVXNWXOBHQMBIMJIQYRQGDRMKCWDIGJUCIVQTBSFDRHLUTPLYTNZYUWIPLERGUGYOVENKJZBGN', props),
compute('m_17_7/6: ${c} VGDWISURDKDRIBFHHLLNUVVFRLPUXBTEZPWVSABGSCULVLZOQFFJRNPDZMQJDRFCOZAGHLXBTWKXWVEMEYCRVLJBOGRBAXAUNJXS', props),
compute('m_17_7/7: ${c} NJSMLEJOZARQUHAXJKFRHXGAXQOUTVAEIRLXFZKLFCQTLVDXEZKSNSQXLMPCBVAYWIRVPKEUBXJBRMKCUQVNKTVMORHJAZKGMJRD', props),
compute('m_17_7/8: ${c} TIUMHVLEAQFFYCZQZTJOQMMGPRLRWYRZUVKTQVBTQFZXULGPZFGTFFGOVJTDKQXDODFGNKMBCFIGTLJQGEPXIGLEQUKNOXETRVYC', props),
compute('m_17_7/9: ${c} ZNHFXBIBCHWMUDTOJNELTXVAHBLCTOPGLTINLNRDIUBJELKHUVYCIPURKEUDFZGPUMALTHQXZKXEVLDCVCOIJKJLBPZXJTFJLUDV', props),
compute('m_17_7/10: ${c} KTCBAIONZEJCGVFDIQZKMTJZCSTWDDSXKTXNUBUHUNLOVFXYHFUBJNLDJHDWLJHTVVGZTWJDMKCYRKJFTTVAUHSRTZFVZFEVOASK', props),
compute('m_17_7/11: ${c} OXWPVVBSANGMRWIQGEXDTGGUULTRLJNUUFUFOJYBYODOTRGQYVDBDYJNTJCMSQLKVKBIIAAMKCBMTKQSKOEMJJPCUXPHSPOUXUUN', props),
compute('m_17_7/12: ${c} RTGGBAOZAPZUYQDNHBFNVLFFZWDUMUKMQUHIPNFGSLOANMTMDZCWCHGZJDOTLIKNJWRFNIYCFMEDVXGNIBVTAHGIWMKBQDFUZZND', props),
compute('m_17_7/13: ${c} FBHPSMBOEVSHYSXVRPWXJLSHNVLKVGXQXHVVTWVMGBHJAVZJJYJZFMPUBQKNTVQFFKKQJADVBBGWZENBEIFUEVYBGCRUTIISKBHR', props),
compute('m_17_7/14: ${c} TBMSTLASEFTZEKHGKTBTOGSUGYMWKQLRGZIWCSBXNZLLXNFXDIECOCGEHLCCYHOHCKIDGMICUAEGEVLWGUYGQPRTFXDNIHVIIFGR', props),
compute('m_17_7/15: ${c} EWBEIJRNCDCFPMSEMVZREPTWOMKEREJWKPFEKDSISALXEODAQVGWRWPSMUJSZYNYHDZLHWQRFUMFFWOHBFURGQRNARPFHHHVOCCP', props)
        ].join('\n');
      }
    