
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_12/1: ${c} BDPTYLLSUQCOUPBWYIIGSVTJAVFNRORPGADMMTCYCXBNKOUNGRIXIVOIHJBVSMJOZHUFQEOTWIFBAGPQLEYMDLBSJVRTJQQDVXSO', props),
compute('m_17_12/2: ${c} UVDEEQVLLVJASPZFSCCFCDWIAPCYYALNOTIJGUZABYUJJJUPDGFSPDXFEMXJJVSVOOVUOOEFJIWAFVVDGFEBUSNOVJDEWXBSDPPG', props),
compute('m_17_12/3: ${c} UBIXQTCQCZEVDREFTNZSUJQWITANLUOXNYLSXTRVRSQAXNYXDKEUJFBLQUHLJSRSFMWNCQMXZGIPAYGQBNNQPHLSURWUZTJYSOIB', props),
compute('m_17_12/4: ${c} VGFVGWAWNRLUORCITHUCWZNSNCWCLDXPATKIEYAGMZIDLUSJKYUHTMBCQTCDWDTJZPHRUNLSBIUIDXKDOWMOIUAXAZJGYOSJOBXH', props),
compute('m_17_12/5: ${c} ZCFRWJMYKJELCJRESDJFTPFZNOBDPKGPLZJNDHHGROPZEPMBSIEPRCTXOBQHVYSQQYXWRYYYZITUHKMXYACLDEOEHKRNJVXSSJUO', props),
compute('m_17_12/6: ${c} JCPFNVXHJAAWQCDERXSMXPLBFJZAEZPMDDRZPSGRRIUNFXUQLAWOTNZYCVWIEZMZBSVLXJVDKMWSKHXDEXKYLXUVFXUFKGXGOETW', props),
compute('m_17_12/7: ${c} YWTZJFTLELNNCEMAEGNFLTCWRPXKHLAVGFNWMJOENREHJWZIPTUMICGMXRSHGIJVQRAMUXTCSZVIPUYZMFUTTBCZSAXDOBCEDZOH', props),
compute('m_17_12/8: ${c} JQFWORBFSKNMIZUBFMTBGJSBXHHLDWYAKVBTIOAGFVRNSKQPMFFODTUVLZDZCQYOTQINRZGXTKQMEROGQSKUVGNDZRIHRCBZBYDL', props),
compute('m_17_12/9: ${c} NOJLNTJYIAKMDPXIGSYQGCQNEPKLPNCBRIYIRRTAMCUCPYPIDNRTLPCDNGITLIEYLKVCINYFTHUTVKFTWHDKTLDUHMKYDCLSRKVH', props),
compute('m_17_12/10: ${c} YQNFAJQFUJINALTECOJWATHSCBXPXZUAVYCVPQJOYEDLPSHMMKYYOZSWCAQQCALJRIQLKMBUNDUBBQYZERQCACJEAHYMRBKAOWHX', props),
compute('m_17_12/11: ${c} JILQQHQLEPHJJCBCMJVZCXFHHQEKWLVLOXVFVVLJYWKFNXBMKWWJGKNYJNLJMCZWTQFABXMELTCCMAHQBYBYZRGEDMPUNTIWZHNZ', props),
compute('m_17_12/12: ${c} WWTYOWUDKEGCFICGTXIVYIAALYOQPAGUHDSRLVJSXEZQFLCQKKEDBIVXRCIJIBHGMBWADTFFUIOQFBQVFSMMFPZFGEMUFXYAEDWB', props),
compute('m_17_12/13: ${c} JBRWVRDQJIUFEXOXLHUNBDCAMFSHIGIRFKOKLSBFXCEGTWLZKAZPIOONWWFXYMNKOPQBBWNWHXVOCAFYEKXPAOWYHWYIYTWRJCIN', props),
compute('m_17_12/14: ${c} DKQBYSQAQDWDFAPQSJPMBZLTJDYLFNFGHKWCMUGNFGFVLACNWMOUZSCSNELQMOVFUKOKBLEAMZBRMBAUPYKJXSONFODRABNFRGID', props),
compute('m_17_12/15: ${c} ZLMHLKPZWZZMVDLXAJQBTCQXDLVESCCKXXAHPEOMBKKVJPRICDKDQDPZOAEUYPEWIIJCQAZMIYBACJQHQNTQUUWKEAAKTCZUYJUR', props)
        ].join('\n');
      }
    