
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_2/1: ${c} SOPIDEUNVVXPCVIEOSOCOMIQTSCFRKLUQGKZKLKNOSQHOZDSSUSRJKANPKJUTVXBYHMCIRZGDSANKHCJUZUZBDNWZUOQYAJIJTAG', props),
compute('m_17_2/2: ${c} HXVVWFKSWUMOBXZRWFTVALMGJOWWNDSXHQQZLZJAOWBVEKGXETCEIHCEHPJTECJSIGZHGDDJJTLUYCPTUPQZIVRUDHJHAHTLKTTM', props),
compute('m_17_2/3: ${c} XHZQNWKYSWYYINTSSRKTBDGEULGPCSDTTSYXDXBHVUWFOVNRKTKZYHHZSNFRXVWYMJOJUKALGEDCKUULGMTCIWNMASNVXTXGTQOH', props),
compute('m_17_2/4: ${c} HMPSCPHYQUMRFVDKYIYRUIKOWTPJAUJKLQGNBELWYEVGXLREVPVPPYQDCPMQLFCGYUUFZEMMXDXAXQRADCCJAEXTNKNJQXUSUPWU', props),
compute('m_17_2/5: ${c} PJSXHNDPQJNVVLADYYPNMLJXPTTOMYZBZKHRRVXOODEPFLSDAANECHVTVTWLMDPTQULLYLMFLUTVAZTIIUUNXSJLEJIXHFUFOMUH', props),
compute('m_17_2/6: ${c} SDPHCKUHDOZWBOGFWXDBFMOODULOCOHYBIAUCMMVOQYBJQCZFSPNFFSOXWGLXBXSKLYFENMKAYALCPYIVKYHNKNTAOCCIQKMXWTT', props),
compute('m_17_2/7: ${c} OPCLPTSIPPLQTWSXRHEELSPWCOHBOMKRFZMOOKCVYPJCFFWFZPPNFSTGDFGMKLBIHZYQYBRZVMNOAWQNDBYXDKDWOLZPUYHEMTML', props),
compute('m_17_2/8: ${c} UTNCZPJDHTDTDFOBNLTPDQJJEJHFQKCYHUMAYFPPDIZLJFUAVYPXUUBRCZSPQTCPJJVLCLQTWSQTDDRDNUUTCDGYMTOIUZZEJTBH', props),
compute('m_17_2/9: ${c} VXTEQZMBTUVYGVAVGCVFAZMYYYRJSNGGWGDQYTWVAWXCNMVNWMEQHDOHCTTLLTTWVPXMELURKPJFLAEGEIELDDJVOQYXXVVSDBBT', props),
compute('m_17_2/10: ${c} XGTTAQYLPAUKXNEKVUESNFSGCZWQTJAHOJZVMZSUTWOHVNJXZSASMGAKOHBLJYNZXIEKHMSQCYUHRPXTWWGWTJBFSKJELRVGXEOA', props),
compute('m_17_2/11: ${c} STTNTZNXJGJQJOLRZVUZYSUZOUOEUSOKMTNSZDUYYVOZVSSFZHEWLGCPNQEBIOOYTVFJONQMKLPHKESWDRAQOFTKEURLKLXKREML', props),
compute('m_17_2/12: ${c} XAXRVWFWSBJREIWYGBUZTBYUISEDYOIKLQFIHCOTAHIBDCSEZYWFKLESETPGXHNKDVLLKQXQPUELSVCSUJGQSLSHMUZLXQSMPYGN', props),
compute('m_17_2/13: ${c} VABVBMKVEHBRNEQVLWXASPOKCGOOLRJPPQPRAYNLIIDNQYDFMDVNOGUUPDDQRZPTHSAFTSGSGQLVBFWNRLQFDXXWPGBILEDOYOMW', props),
compute('m_17_2/14: ${c} JXDQSBSVZUCCSWOFEFIOSLSKDJSZSJQHOMAPIWHITTHKMZZWQYDVKGNKCKJRMIBKDIGRQRXHIKNXWFUKSHLCLSBLPFDGJVKBBRTQ', props),
compute('m_17_2/15: ${c} KNQIAHCWQHHBPAZZEOAUUPUXDHPOMDCUSHMFVBZYDPSSNTRRHTVYIEJUNRJFIJBRASFWOVIGPNGROUQKKLYEQJJTOXRKWPIYPWGV', props)
        ].join('\n');
      }
    