
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_20/1: ${c} WRNHUSLYFDFDXIDNKLGEFTCZOAISOCBRYXCIXANXZMGKHKLDGSWPKIGAMNERMQULELUFGUWRAYIMBSJSWSSUWGDJNUBFYFGJGTAT', props),
compute('m_17_20/2: ${c} GLWFRWFCCSOFUXMUWSHKEQGVJCZHKZBAHAHCCFVQTVCOKBLPNYAKGVYUOIYRTTHESCZFSSEJGYFSQZJMFVNLNRFRFHVDRVUVUKPO', props),
compute('m_17_20/3: ${c} ELAIRVMNIAXCNTASREZVKOFNLZRKDVQJLKGDBESFZGPKWRMTDBNTYELHIEUHZOIZILNNROCCRLLUQXYPQXGKNVTDGMCTIGNTZQZD', props),
compute('m_17_20/4: ${c} BZTRFLAIMHMAUHMAXOWAOKWJHRCVGHPHXVAHDPULLGQHSUMMPYERNVCYQCGVRXPQEUHMCKRWYLPPGBJWNLVMJFVYEYNXRUNGXFNK', props),
compute('m_17_20/5: ${c} EXDLRNWPDMDLBVJATITTEKROWTNQDGGFUCPKFDPZUYNBLCLZZAMVTAODLFAIFFAHPHPGOYOSYKHKSQKFFFAKQHGERYLWPMAGYLQY', props),
compute('m_17_20/6: ${c} VZIVULFJVZXODRKBFABTPLLNPXZDRNWKEFXMLWBZMOQEYISMDZEHSRCCBETZXZMFTZKDZFRQSOIQAYYOLHYEEXITEAIVMSCPEINQ', props),
compute('m_17_20/7: ${c} XCEWXQKKDGUJCSFUQFKJFFFSAKMNPMULUKKXAYMHHEJMEYXVNJMQZEGAHQBVQAGLLXNHDHRTGGTVIEHGQAPNBGKATNVYCXYARLVE', props),
compute('m_17_20/8: ${c} VEUQSMITZNYTOARWUHYQERDDZQQQTNTXQEQHKOSVBXYVFGQADCWJECUPEFWDEPSKARWLIKCKXXKHXYXVVADGNVTHNTCYTABENBBC', props),
compute('m_17_20/9: ${c} MOVNBNXDCMUYLAYRGQTELMAJBIZCRUWYGJECLYTKDMSRYXYNDYNTZUNGPVIZYCYPPWNSFPQBECMCAIGWXGLSLOLAYCRVSUIYYWJX', props),
compute('m_17_20/10: ${c} NVWLMYBCZVANNJAPXIYHJTOEYBQCKQXFJIVATIYLQGIVTBNWTMAALTYDXDXPIVBZUPALDVEQTCUSUJTLZLIRYKEMNWHSRPPNXNUJ', props),
compute('m_17_20/11: ${c} HBAOHXGJXSLLJXXOZELNAJPRZFVOFAVEGXCXPNGUJFJMNIHRMPNMFWZLPVSRPZNHIHMFDYTXKDBSVKLCYWHNKAVCVEZCNHDLJKDJ', props),
compute('m_17_20/12: ${c} ZLZHYLAKYGECFGLWBPDZNNWQNRWJLBTMZJITYXBFZPTDTXTETVPXMAFKNFMYFCJZLDHHMGLUJRTDTBTKFQYPSOVFTCAXEQDDLLRX', props),
compute('m_17_20/13: ${c} QYBXKRQFBGKXVGZJAXSRZQZABFQKGTMOSLIWSFSMNEJNCCVPVIUPZMLWSXHWKCGVJJBCSXMSQJWIDVCRCGNPFGTSQRAUAXBSGZVQ', props),
compute('m_17_20/14: ${c} YLMAAEEWAASZZBDJQCSVVWCECBFOCYTZFYQJNGZOOIQGRMGDNHDSXSPCNJSXWGSFNTMJAAQNOCBUPDENRYNKNJZAWHKZNGIQCZDR', props),
compute('m_17_20/15: ${c} XUWZYSCETVQMKAMUOLDCJPCKBDDXOIDBVVQZNEEZNLXZUHXKYBUPIBIBGGVXCWUZRZSNSFJOLQUDDOIFINVIDKYOKRXPYURFFOBO', props)
        ].join('\n');
      }
    