
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_8/1: ${c} RMCGIDKZLKMLSHPOXWSDNJLKWXQRIEIUXRSXUHJQWWVMLGCXGNVGQNMLNAINLYXGDRSGTNPWRPVYIQBVIRPFZEGIBUGOBRDVSTAL', props),
compute('m_17_8/2: ${c} NWFJAYTBDHPENPTKWIQEAQUVXYAFPUECKDRWRIFYGXHSYYBMSEOJAOIQLMPXOLTWFXTPZLLIXNVXZTIOPOGMSKCIWUHVBCAFAJDW', props),
compute('m_17_8/3: ${c} APZXLVSGJAGIDFGXQALDIPWVRPHVKFEEXHTVMRHTPGARKOWOGURZLMKYZZKUKIMGGQSZLYLNUGALMJZXOZJMRQGUMZYDLYGMRIOB', props),
compute('m_17_8/4: ${c} HCIOUAQNPJYDFWUSYFDCNLNUNQUWHBVLUNXPTWJYILCIMFRISNURTXAXHNHNKLDINNZFPCDRSZFYDCTYJAWLWOSTGBUZIWPTSTYE', props),
compute('m_17_8/5: ${c} UCRVEZDYNJGHQMNNYORBLQNZDXULFDJNZPEPWLYYKPPHCMZAHFMTCIUAJBRJSVBFABHUXWEPASUVTXBAAIAJHRVRTXCDSOOLJRPZ', props),
compute('m_17_8/6: ${c} EFQWLJYHVAUUWZMNCFTTMMWAVAVUDGXHQERURSNIXAAHLYHCYQUHPSXEZENOVNZLBRDNWDKRIVNXTTBSETIZFTZYSBLYDSBHMWKP', props),
compute('m_17_8/7: ${c} JLRAOYJSKFCMFXGUKNXGGZPMIBKSJCSIYJGVBGCDVVWQYYQDQTIRIMOAIZPVDSAHMCECTOVSOGHNURZEDBDUNVWKZQFSDPTEFPVA', props),
compute('m_17_8/8: ${c} PYTHMXIOTLLSOPTRUCPEJUFYKQHENUMCJNJPVUHLIAENUGWKVJFQJQZAUDCPFYEHZHWKAMDMFNRLPXOKCOXEWWEMKSUENJZDMCJQ', props),
compute('m_17_8/9: ${c} TMLXGUNSHGASZMDZRJJDSEBNWPGSJXUDIBOIAUJBFZRRUXUYJURPCTJFUIPKABPNSGCGQLBFFBLDIOHPWYCEGHYWRGRQIMHLFRUM', props),
compute('m_17_8/10: ${c} PBFUANAIYTOEOUBJJFSJEAWPDEWVHGEIUSAUCXFVNOZYAIYGFCXSCPQLMLSVYYXXOALYIBJBSKLWZMMFLPVAUYAAGMHFLJMYQRGG', props),
compute('m_17_8/11: ${c} ILLJBXZPTOHRUGDLGODHNKDMRZFBVXGWHIOVFWYERVRHCWTZUHIJLPZLFJFLHHNYIQVCGPFYCAJBHEMIEYXIINWHFEVHADIUCBJL', props),
compute('m_17_8/12: ${c} JGBVWYQHYINQSSWUYOGENAQFZFQTMFXRTJCXDSYFJNHMHVLNKWFEYIWROJHJZMRDJMQYFHMSIVWOIVKULIKGAESUEWONJHZNRJHQ', props),
compute('m_17_8/13: ${c} TNBFPKOPWDRYLUJQAKIHYBAXEMQQDWUUCDHYKYXIZLFDCWNFZFOVZERTAGLRWHOULOLIDMDAVZHILXXSPGHKFYYPGGEJLJZPFYYZ', props),
compute('m_17_8/14: ${c} QVCHTAALOICPGVDFAEFMBJIHKSEKFDIEDQSCOPXQLDDPCJXQTHXYFZYLPMTFTUVKVJDQQMKDBGKQAYAMMJURGVQDROEHGHPGSVXA', props),
compute('m_17_8/15: ${c} GNCIUMVBKUDGSKSYPJUBDPHPBWXYJXUNCBMCFKRAOFGXTGTNWVFDBIBELYINFYNAPQFLEOODULKRVPHLUCDWBKUDQEDCUFCRUEDT', props)
        ].join('\n');
      }
    