
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_19/1: ${c} KTDFOZZSSOGHQGPTVSDQZZKYVGRDDNNMVRVDPGUYMKCAGSWUUZEFODQKMFNLMOBOGTBTXLUZDBNTSYOUUWYZPNUNPVOOFWMJTIOT', props),
compute('m_17_19/2: ${c} XGRWLYIVHMHWLPXLROFALONUKWLZAQIGRTGACNTOYPXJSAJIVTPCTBARZYQKFHWAFUDQUIOBDYREHOAXITCZPYOQDQCMCFJREXDY', props),
compute('m_17_19/3: ${c} DWKIKPZCCMZOVOXQYPWSMENHXVVEGWGWYPPMHVVYTJQGBFTEJWCZWIUOHAUOEHJQKHTYRMOGOWZYIWGAMPZCAOQSADEYORZERBNJ', props),
compute('m_17_19/4: ${c} MLOMLHFKTRTJNCGMLIUBBESKTXAGUHYGHMUYGRCAPXLYEPIDNWMPEASQWBDQPAVIGOVKSXBWZZELAURLQCLGUIKKAEJTSOLWGIFL', props),
compute('m_17_19/5: ${c} XBLPVEFZSHFDPOUTFDVBRJVQJINGYPEXGJXGPHNCWFKURWVIQYLJUEQOOTSLLQUYOCONXMLLGKUQILQFDPWVEBBOJRPXOEPEMWDZ', props),
compute('m_17_19/6: ${c} VHUQDNRMKOEAWYWRXTFPVBWYKRNQGKQZCPJDJDLZTNYNJMNNWOPTTZIFINFXZFDXPALJCZQAYXEIATKZTLRNPABEXPHFRFDENJIJ', props),
compute('m_17_19/7: ${c} TMSPTXTUCMBPIYQFHRKORWNVXFRXDIBUQDHRIYLLMBEMXBSLNLTRDABENWPMMZXWPPRKBPZFCKHWTHJEZINBLSKLNIIXAFZCQVUQ', props),
compute('m_17_19/8: ${c} MLDFYUAWMBYKYEXYHFGNYBAUOTYQAUTGDSZLBFQUCCCCDPFZKWWMBJFCGCHZPGETLNJCKEHPLWMUQNPNDONTTEDUVNIVNYZQBOWT', props),
compute('m_17_19/9: ${c} FQNZCITPAPGQNGMTEDXFIRFBKYIREXENBIFXQZXWIWQFPSMWNVBXYWZDLRSDIUXOITNDCFEOAFLKKARZEOSNMFYSLZQOPXHNRQBN', props),
compute('m_17_19/10: ${c} QRMBRBWJVHZSFABFJLUIPURMQEDUWYZLQFSIKNDJXYAOGOXMFKUHHYYOMHTNCEYUZWXXQBHMVONDVWKHZTBAPUMWKOBQAKDCOGBE', props),
compute('m_17_19/11: ${c} QAHWFDCLOSPFOYZEZZCCQUUXTINASGVUCKQLZRKFWRVPMZQASGNPYYWDEGJIEWDLFFDEQVXUWRHYCKGGQDJWOFIPOZMGIOYHIRLI', props),
compute('m_17_19/12: ${c} WQFPCQHGLRJMRQWBOJKACEPHUJNKDOWMBJIENMHNXOGXHXYSRHRLZQNCZKXDUQNJTEIDDAFHYSOLACJIYRZDRTSFRQOJRAOLLIMX', props),
compute('m_17_19/13: ${c} UYGTVEIFAFAJMKAURZXTSDBUMDPSEMFBKJBFVEYUQSVUUMXTYNJPRQWMRWHWIPTXNUSNQDYCUXLCVBEEUDZGVTMQOHBUHKKMFPLA', props),
compute('m_17_19/14: ${c} RJJENNYKDYNFXDPEOEHSIYKZECMCVHZXARMUSCTNIRZVTKYIQBNRNZWBNPQFKKIFHUBBWIIEIPKGOSMKHDAGFMXXNNRZEVBWTEBC', props),
compute('m_17_19/15: ${c} ICMSJYTNAEWJTDFRTVBVUJGTVJBWKLRWNUSIKDEFFHVBOENEXOPOWGOEMAOTDMZXHQZUFCQPZQSTGWSTRVGKRVCEBBTVCUMKJNHZ', props)
        ].join('\n');
      }
    