
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_11/1: ${c} XQRMOGJUBURKVLVHKGHWTAVFPVLITYPZFSRPDSWEMGWGLTSRGLYNJSCIAAPCUOSYNMGPLJRICFRHDRCMIIDMJWOJBRHZQXKADWDU', props),
compute('m_17_11/2: ${c} YJFUZDTWYSKXKTJXNEEVXHZLKTOFUZVIAEFUQCJGGQTKFDOWEXJECMJHOOHYLVATPBJNSWPXUNBOMTFMEUMVYFYDRGIVEYNZYBUN', props),
compute('m_17_11/3: ${c} JAQJIAGFZHOPFKAOXGSGROAXWRXADYQZBDMVODTPKAXTAAQBNRVEUXPCDBKIINKPZZMIWHIDSUSHWXXKYLBXCKFULVDICKLGYZSF', props),
compute('m_17_11/4: ${c} BRRBDDKTZDAFMTDNHUGCNORSUKPUKSWDMBONDVWAWQIICKZDSCWPWVCFUUIEEBBPIZVILVDQNHAXQDAMUWPZIMDSBIORXYXKMCIM', props),
compute('m_17_11/5: ${c} ICURLQABMLMPYUXFDUATAATSMQKFHQJGVLUYJUHAUEDEARPYFHRMJBHLPJBPCUSHHUCKGMJLTLYKDUVEKXQZYCQFGBSYHFWNOFGO', props),
compute('m_17_11/6: ${c} YVIUVMEIFNBCILSIVNYYEKMEQCFETQXDUYVBTKRLHOSGHSGHDKYDGDKWSQKDZADYDFONWYGZDDGEGHGUGCZQMBWUKDPWVKHRDUSM', props),
compute('m_17_11/7: ${c} LZQIQIVGJGWLEAFVFSWUHMUDNYHBTWHIMKCTTZSMLLPKENNCFGWHDAWCDGEQWGLPRZEZGJYXROECHVYOSWNPAPQYVZJGMQYNWFYO', props),
compute('m_17_11/8: ${c} ODCTTPBKNFLMVARUDQGJXMKVBERITREFBTTJEMKNBUEHJGNQHSKJTUHCXOTRQZQSSRVPVEGRXCWFZRHJSJJVONVZSWFIHELRVVFZ', props),
compute('m_17_11/9: ${c} MLNRDICMMRONDFXCDQNHRGKDZOEBDTAEQJGEFCGYUWVRZSHXQONPBABVGRUOFRBACQKPRKZGWKMFEKUWGNFFYEZFLECNBMNBPAVJ', props),
compute('m_17_11/10: ${c} AEGLADJQLKDNLNGZPPEGDQHSIMWUSNUJXSKYHDTNQSIMZZDWCQUPHDMLMOCVFMAMSTMRKSBMFWPPDSBJXFUZVTGAHRIIQLBPSHEL', props),
compute('m_17_11/11: ${c} NDVBXLOLZWNXCYCIKKAKPESEIUMWKMUXCOMIDOLCAUFVCLIULEWOGOLRRKVLWCQJADUHOJEQTCSXSCGBFZLIFDOAHZBMXVXQQBHF', props),
compute('m_17_11/12: ${c} MCAZZZTWCWIPATRCXODQYZKPLXUPOJIZVFNYEVDWKVTGXGGTMVWSYJRBFVSKLMXJVMAKCHXUNJQTWUVQDITDJGKVJKXLYVNKTSDS', props),
compute('m_17_11/13: ${c} JOWTJOZYIKCUISPSPCVYNARNBAEBYSXTMHYJTLYMSNZFBEAUPXANFRQGAUNMBEOOADUJMGQWDIKLDGXDCDQROCLGAIVCGXCSSTCY', props),
compute('m_17_11/14: ${c} KRCBKSQKVIFJZNKCOUPPCSCTILBCAYABEJHARBBBBMWTMPAYSSLRLPNMNUFJQBOUNYGCTFVQYVLQEPDDMHLNBWBFRNUNOPSAJHLP', props),
compute('m_17_11/15: ${c} NVJWVVAROPTYKBMNUPDYKKGXHCWHMRWKIWDGPZGQLHPOOZRIQHOCULPZFIMEKFEIOZIPWHRXTQYBBJSKBSRKOJWIIDWRRSHRJODK', props)
        ].join('\n');
      }
    