
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_3/1: ${c} QUYLXTBTFEJPJCRLGLCWCLSYSIWLULSMMLMBULTLFVAVCOTCOFOHLRMQRECVNPLRBGIPUGZFZCMAACYSJLMAJIEUUQKEWDYZXARJ', props),
compute('m_17_3/2: ${c} ZSBZRNIEOYCUVLEWMXCXGZTPNEEXESLXVSFIACABQWKCGRSGHGVKVRXVDDOWATRRNFGYVFWIPFGRRXQDVNVFGAPZZJNPMGLJWYGB', props),
compute('m_17_3/3: ${c} OYTKUNJAIOMKCVJHZWQHTAUPEOKWDDNGTGKQKAIKCSJXKRIUXDSFTBRIXTWOEMUWYUJCJZLYNPJOYPUQEFQAYEGMNBULGRAODJBT', props),
compute('m_17_3/4: ${c} WUZJTGKMVILVQDSMKAKNGHNBVUWUVMJWAXMMHIULBQWEUPCNWVHCVBZBOTTAQWRTJNPDAWBJJAUTEKMDMLEDZVYMVFDAKVIGVZGO', props),
compute('m_17_3/5: ${c} AVVDRJAPQNENJQNXEFIKANLOTYSRGOERHLAQJDWPJEFIJOOPUFACYHGVHPEQSMSBQGQYGLBGSDXDLYUACICUDLFAOEPLICVCYMXM', props),
compute('m_17_3/6: ${c} LYLHIRNGVRDJRZSYNQIHJJGTAVUYADUZBVMEEZYIBBSNHJRWBGRAXJFEYUWKXCLWQEKKJXPYLVSGWPPXRTISGIFCEJNMJLAOTBUT', props),
compute('m_17_3/7: ${c} TNMNSLINXMKPBTWECNZPGZXGWKTNLBLQTTVZZAALZALSAOMVKCPNFETAIXNTHOIKTLTLFDLXNJKAGYTVVBBRNPCBRCBOXFZKZSMI', props),
compute('m_17_3/8: ${c} KUXCAVZLAZZBHEQYTAWVAESKBZSVPGWSVUDENEDACXKNITWPHLEMMQDLDKOETKVHOWXTZHPYUAORMIZLMYAUDQSMRQOWHUDJRMQA', props),
compute('m_17_3/9: ${c} HKLMDZXNBYWHZMDPKPDSGZFSZOAYJMGSNNGUMTMOFEEKRTBCWZKIWOXYYYMBGALKVGXVSHNWDKEXMAHXKNUFPTEHKPLEDDWGNBAG', props),
compute('m_17_3/10: ${c} EBHSOBVESVTBEAWBZNABHJTGTNSKOJXCJYJESOVPRHCBAZOJVAUOXQQCUJEWGQXQOXBSUOSYAKLUBPXBYEFDFDAVKYUCVWHKIROY', props),
compute('m_17_3/11: ${c} DOXUVDGKUFCSWHKUUDKLHLGWIUFGLANVBGNPSRFNNXMRLLMQSZETETMQVDBQEJHMPBCIWVSUNFEVDRXVJJZNDXUORIQBITSYOGZC', props),
compute('m_17_3/12: ${c} ZCDBDHTHQBZKABVWWXNZDCNURYAAAAOQKPEFUQLTFLSDPKUJHFDCXQIZWZZPTASBCBHLAVOAADHBMRTJPYTDPBLKVUOAAWAKWXAP', props),
compute('m_17_3/13: ${c} SXALPVBFISXNCEZJTNIEGVOZKKXBWVRQSSZTPZJOIURHIDFKNBPFUNWSWIXRZQKDBDPIKINMUCBSDNSFMQNACVNGPXRRJXBJHLXL', props),
compute('m_17_3/14: ${c} WIGEDRJGGAQCXFILVZBAWHONACVSXGRVJJUIHBAUIXCRISSDXTMFLMKXPCNSVOHCFSBRPMJSAQFKKONQJQERVUQOQGMATMMUWPXK', props),
compute('m_17_3/15: ${c} CUUVOFMJMCOVNITMKHBPXVTCGHPGWDJQUGZDGVQUJXPMREAILMUTTQEAVWXKOXGLZWPJWBFZWWQOPNIFIGEEUZPZMQQQZABIJWTB', props)
        ].join('\n');
      }
    