
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_6/1: ${c} LTPSYICEHFSKEFHOZUOGISBHVYPAPTZYLYHAOJOHXZRWBNDSUWTGGUTCDESLMNVPXMJTAGQJSVEECBDPOBDEJORHBJJWILQWBAGB', props),
compute('m_17_6/2: ${c} JGXVRLGXQUPZCSXCBPTEUDAJTCOZCFSVYTFSWDCDLQVSBRBWKBGUZEZFMNKWSYXFNXQAGJWVDULHSQUCAKVWYEEXTRLPBLWLKMKI', props),
compute('m_17_6/3: ${c} COBJRNSRIUYCIFCEQAGNTBAGWBWDWMWCFOCWSQERVBHVYNNTSEHROZWFMRZNKXFFKSZRFQGZHOZXLUADFXPCVYRTGXSEAUCRSXSI', props),
compute('m_17_6/4: ${c} TNFBBCZDMFFUUDOTVPENWNAMUNWDDNEBYOSOOGQFGQZRJQLZPLXPOPECTYXWXFZMCJGJYZKYHEAFZEHUWALETYHHKBAKHAOYQYFK', props),
compute('m_17_6/5: ${c} DPGDUEKQWGPREPXJTVHTBXDKSYTBSJFNNVFJQBJIVDFIXIRPRPFFTKPAANZTWEKOOOWHKIKKSMZNQVZUDVKDYTCLWWXDWHUWAIEN', props),
compute('m_17_6/6: ${c} CAOUJUMRETELAPSDAGMARRVYQJANPTQOGOEVUFIZZABRGLYACKSXCWZWKJZDOZWWODQMSVDJZQGVPMVMQTRZHDMLOJAHTPQPZQRL', props),
compute('m_17_6/7: ${c} IIDICDQSUPRRKAOSWDJHXPYBVICHOTFDXPOTGCXEFXFMAWTMCQLOWKSJNSHINQNLFPBIHVYFDZUXCXOVBNUKNBXEQIHQSLMDHOFC', props),
compute('m_17_6/8: ${c} KEBIKGTJAAHRJOTEEYQAVYUIRSXRCWDYVXEBNSKHVMKYLNUPKYDESRAQVWIPXUAEVTKYZFIYGGCGXHLYRMCUVKALMAKHRHBILMQQ', props),
compute('m_17_6/9: ${c} QUOJILNWPXHQZJCAYMHOOIZWBQMTAPAEOFBIQOOKTHIHPJUKLUYUUMTYGTQMNIASPBNCENNEQENAYCLJBXNLWKQYXFRGEDDRZZST', props),
compute('m_17_6/10: ${c} NSCBLXCJJJTLNLWLSDQLWFVJUBFCSSWIUPRFGSPBXBEBKINJTKMPRSBCXQILIPUXIGSKKCDLXQOPPUDNVOCYIPULDKAPAZOUNNNL', props),
compute('m_17_6/11: ${c} VEQZELFZLXOWEDRQUUEKMTOIDINEUMJYMMHDBOXIHNVPPXALEXGRAFXJZGDKHDURTTUYUBWPMVMHHMSQWVDOWWVIVKMGAVOMPYFY', props),
compute('m_17_6/12: ${c} EUQEYDXVCXKDDDLRDCCEVGRBAGGYXHYXUORTJYAQSYNVLBXODTUDCHPUSQXKCVAGJILNJFNOALOGBELYMIBWIVZERMFYNQFJSOQO', props),
compute('m_17_6/13: ${c} ARXLOWHUAMWVMVBJTCNQGHZVGHPDYSSSJBVRTGLWLDRJUUTPMICUBCQBWRREILXLLERXVLXMCCBGUUXARDUFNDPXBRBIWDPXNTRU', props),
compute('m_17_6/14: ${c} STZZMJEQZOJWKFMIQQGZHNNFGUGXVMSWZWGJDDXADNXGEBNFISPGENEJIMTCGBPIBTYTNGVPOUPQHRDRKUXDJGWOIVXXHZXLVKOB', props),
compute('m_17_6/15: ${c} MLFMOXOEXLTTZUFXQNCUOVWKHNNMKSNQUZEUZALXCLUZQSRTEZRVKNFSSABBGHBATBENLSVOZBXNWHSOKKRLBTASZAPQGPGJYYCK', props)
        ].join('\n');
      }
    