
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_15/1: ${c} LHRIVGTQNRKHCADAZPPEKBBIDJPOCOBKTKVREANHCNNXAFYJILHCRIGVZSMCZQATIWIUVIVBQJNZFDNBDCBILHPQWQWOZOQNBJHF', props),
compute('m_17_15/2: ${c} UDKDHDCUJXUHXSKMABYNSAVZMFSNWDIQCIPXYZHVRJAKUHEZLRGESLAHPWGSLWSLDSFAESZCZXUFWXTVFDDIZBBESHNDLEJVGTTM', props),
compute('m_17_15/3: ${c} NQKHDKKTQYOIHTPCIFPIZKIMSOLFRPNMIQIRLTRECCUBJMOAZWLTBWYMXOLHYPRVRAGIEWOABGLFBBSTWQHBSKVCAHRFNFNDQOCF', props),
compute('m_17_15/4: ${c} GAXTUDLORYFWQYTGENWBBJLRAUHPMPCFLBXADRXISKEMOHSUDRZSHJRSSKMTQRWEXKXFLIDHNPZDOKLTPJKTEDVXBJQWOQUYBSOO', props),
compute('m_17_15/5: ${c} ONWXBJRHNLUXNMDRHKYZGMYHOUBCFMMKMAEGKZGPKVJKRIHEGMFDQJMCVZYHOPDKEZOGOCQQUYPGUIPWQELAPXPVIQLFECAAIUTI', props),
compute('m_17_15/6: ${c} HDRGLJIPOPRWAGILBRYDCVEUKAQBEBPOGVPSMBLRZDJCBBLMOMUKPTXMZQCOGOIFQQBTJQFRXEABQBAXDPQIZNBRAXJFEDXFVEIN', props),
compute('m_17_15/7: ${c} CAOWYQCNNOZENTTZZBTOOAJZFULXIKECVPBYUZSMDUCRSLAFXQDRXYDDWEJBCTUMVSAOBNTLJKAVBIEHOKZVPOLPAROOBDWDYYUT', props),
compute('m_17_15/8: ${c} NLZBISPYOZEKITDGAZWRKSESDVPNHRJPGKOBSZPKJIKWYCJGPUDNAKXFBNCKUPJVJVZVAOAWZQQBBKZRFERTBPFKTKHCOZHDKBZP', props),
compute('m_17_15/9: ${c} XNTAUAEMLLKKYIJBWUEBVDLDYWKXLJREMKYJQFJZRUNLRNJHUGXAFJAFNFBRZRTVOQCYYJDOXYLRAUKEPJCIBYYEXECELBREPTFQ', props),
compute('m_17_15/10: ${c} BMXXNAXRKDZBJXIUKOHAWARHXGVXGTJYMBFLHTYPIGKCAXDNBFHVHQXKFEUXSWHJOADQTOCTCMFZQUSBUSKETXIZJMKQWUODQZZL', props),
compute('m_17_15/11: ${c} FPQRBWNUWGXEKWWWNGMQRVYMFYJQCZKDTQCWFQZSLABXRCVGWSOCHZMYHJKWYLKJEPHUFDEQOQMFYRBBHJIUZIVZJSHQMNCDCOYK', props),
compute('m_17_15/12: ${c} OCHVUFTHCEMGYROPIYVLIDOCIWSEBAMQZGXPEZWMBXKLIWSFHMSSLNGHRCBOWGDCWFSHNTDPNOJUMBSBHADIJTTNVTRNDAIWPIAE', props),
compute('m_17_15/13: ${c} OCXAPOVOVDTSWXLSQTHBKYOZEXLZSUNDAOPAJHNRYWMORIFDTRJJZIATMVUDLMXMVVEDHPYTALUBIXTOHKGXRASBXFCXXOTHGRJU', props),
compute('m_17_15/14: ${c} FKHKQPLYFQTHYZLZODFQKIXBISHHIAWGCSQUSBIYFHJWGOZWBQCJOZFTIWOTKEISNRUGEJAPZDZKNKLUVEVFJAETNGXHOWEHINEM', props),
compute('m_17_15/15: ${c} PUJSXJPHDEVPSONMBQDWCSSCHQQGDQVGMHJZQHKXRFMVVYFUHMIAREDJZVLGNVISERAOBMSXQNWNACTBMBSWIDXEQANATFFYBQZT', props)
        ].join('\n');
      }
    