
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_10/1: ${c} GKRAUISNCLUPMFLDUQWCBAPQOYUGRIYZPOVPSJRWMCUKBZGTPUTLSMPZKQMHLKBSEIGURCENHGJWWCMIDBCJITEHVOQLJDIVDELE', props),
compute('m_17_10/2: ${c} ISCVEKDFRDHZDPMELMEHJPQENKCGICMDJKCPRSIRHPCWKRHYSDYHWSTLECHAXKLUZZJVSQCGOECRNUUQJFTFEFBHKVIRPAZKPMXW', props),
compute('m_17_10/3: ${c} TNLERWUDICVTYZJLROULKQDGCMBZJVJXAAXDLDWGKIQALBSVSHIVGAGUAOMIHWKQLBDIQVFJXCXVGAHMTUTVGODXZQYSHIPUBJRE', props),
compute('m_17_10/4: ${c} NWGLVPNODHQNEVDYRPWYOPEYWOHTVMLSRIJASDFEBVKNKTHZVCTNQOPWIBYEJRORNYJWEHBLXGPFMFVTVYMCYBGGCFVKYORSIYUS', props),
compute('m_17_10/5: ${c} LZOSTGVUXNZFMXHGRNFWRHZXKTQYQVZSDEACTJZVSJIGRJVHYELTDJWKTWMLCNXXDFVALPNDJDSVQDPBCKMUWPKRSTTLHXGYVUBJ', props),
compute('m_17_10/6: ${c} XFUDTZXOSQDLFCXDNLQCGSMOALVAVMDFGHIGDNSUNWATJRHZZWSVVMGQRBWGBPEPLFEUELIQRAAZMDBKXANLMNTNAFJFVRXIGVNB', props),
compute('m_17_10/7: ${c} LGMFHDALHGSTWJNTCXTLSUTYYZPHHIMKLQWWRBQIVMFAFCJUWPKBFASXONZGXJKHWPHJOIPARNAUCREVHYGIWBCOYGTKQVMFRAPO', props),
compute('m_17_10/8: ${c} NSCCRLAROKGXPFMRBCAAYWXEOUCJUTKXKRGDUPYGXLUEYBJNKCTIYBYGQRDEOGYLUNGCIFHYBTGEAWOUMUPQWUAGTTDTKDVOZZJQ', props),
compute('m_17_10/9: ${c} AOFNBOCMZOLNRTHGIVJSQACUIXALISSFGDSGOBLAFWAAQTEWYSJCKCMXVZSSMXRYORFXJGLUDUKHPNNCGKXRQCUKGHXEVVPWONFC', props),
compute('m_17_10/10: ${c} MHMCJGNCNZAJKTZZXBHCESPBHJOUKNHRCYTMNGYOTOYDKCRGDVKMXUICBRKEIRRXYVBVAMMQBSLORHEJYTEQPJUJMIPIPJWSFTSD', props),
compute('m_17_10/11: ${c} LTCTHMYZWLLBEPVKCSTMLRVWXEFSTELTOXMMDMZQNYCSWEDHJFTNDLKZWEJRTDCLCCAHIWPBUEKYMVHWOVFMTYGVNNEAPQHJWTMJ', props),
compute('m_17_10/12: ${c} NWMRTYYCZBVFWAPMQGXERRHUQXUVFJYBEAGZHLKCWSOGCXGQEWPDATWKUFBBZBGWRMEQAPRMOHAJSLQQOBVBOLGKADXPDCPHMKPI', props),
compute('m_17_10/13: ${c} DREZWABKHBDLQBFTIEXYUXYNFGIIYMTKRRMORUNMYLNDHVFBXOQZXYICGMINQBHFNYQQEQCERZUUEAFUTFCGBOSTNHSMILAEUUQY', props),
compute('m_17_10/14: ${c} RLCHJOMTJBAKCONFVLGVGIIGIVVSLKIWSJGWHSGQBBCDZRLPNUNGWRMSBCHOJGWPQNNYEYJPSWDBODZGMEIYTBWLIHHJVYEGDFYN', props),
compute('m_17_10/15: ${c} TZYQVLNPLWEARFSLZGLXCEABZVFTYBYAJFUWQTQCVHBVIQXWHDLUNTZSIPQEUBJJYMUEWZMQTQQJFDESOOMBTDKUYOFRUZVLJITL', props)
        ].join('\n');
      }
    