
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_14/1: ${c} KSDHIEGSBHYPIDTUOXJUVETDIWOXYOYQYIYWQJXJJNWQHARATTGLOLPGKQGWMYZEEDGYZCCGJHCWJBFSXTWRJBETUOWEBWSYJCKU', props),
compute('m_17_14/2: ${c} HJEKJLOPOESRQMCJKTPRZYTVIVSSPHKPNBCESPEVDLCHNLCNOSGQTPUTXLBGVYOPYOWGBTHMRUXIHEHSDGTTWLGSFSEHJVEGFKRX', props),
compute('m_17_14/3: ${c} TILECFRUTVFWQGMOMJNXXEEOPLTWCXFDVZEHSVRVXFLIMSJSWTVBHAEOHOXRZPXUZHWQSOVLYQIHJVGJQERFCZDTGXMMGHSBCAPR', props),
compute('m_17_14/4: ${c} TKOEBKTSWCGMVYKKKIPJTVTTWKRRARDBQKKMFGKCSTPXFPKQGETKWNAOSWDWGDPLUWCMMDOTBSRZITFHTBBEHGRCHFRNDNRQGPJE', props),
compute('m_17_14/5: ${c} EIBVKDUEMTATKZODBAQFDTZPSNOMYZKDIHWUJLVFKBXKCYXXNKLIDGUYOGGJXKEKCZBTGMMERHQYJLNOFLAIDWXRCIMPKBRTGNEW', props),
compute('m_17_14/6: ${c} APTLGUARXZZYZFNDORFDHXMQCIEOXHKNIWORRKPLZNAFOPYECQDYFZVTPKCXTFQIZWHBXPXWXGUJERYAFAFCCPMLXXAFKVBPMXUJ', props),
compute('m_17_14/7: ${c} LWZXKLSTIURDPIGSTFUXJDZWOBXHJPHHCYNAIDLMBMOPHVFVCQMVISHYUGFHNZYZCBDJGQPUMCHVUPDUOHLRJOITDFTLCWYPEHKF', props),
compute('m_17_14/8: ${c} YSGEPXUTEXGBTCAYKUCONVCKPZKRXYFERCWEKTZKDLKWJJAVXKSPDHQSRHNKNWFCYHEDHNCSOZHFEFNVTYLGQFUSUOFGBUNOWHFX', props),
compute('m_17_14/9: ${c} XNNWFXULBHLOHNVLUWTWGUWWCHDWKGWWMRHKIZRBZRIWVKBUYOYYPKKXSEZTNFSMPMBBUCRTRJZXUKTWIRDJYDHPOFXLBWWJNELQ', props),
compute('m_17_14/10: ${c} BEGKDSTJVAHGYEIZQPHKFTWHPPIQVSJKOCXCEKCHKGFXTFTMJFDSIWXDZLNWJFOOHDGWOJRVWMLPBFJSHJARLATIBMCXEGAPVSHQ', props),
compute('m_17_14/11: ${c} JODWKXEUNVYPODXMHZPYLFEFAPAQMCIXLKJODAOJANSMPPOKCSZDCOUKLRTAFWGUIBTSMOEMBITZKOPHRZUCNLHAYSORUXBBNRDY', props),
compute('m_17_14/12: ${c} QLWLNNFMVLFWRGJDBZQRISIPFOPZEDELLFGUXPIOHGWMQEDHFHZSZUAYCUBNJTHEGMJARIUAEEJMVAUTXVBZWPANXKSXGAWQIXXS', props),
compute('m_17_14/13: ${c} SJQYUJRKPHXNYBXHLVBHFYTNEBVIZJIEAMPQRVEDJJGTATJRIFHZBEJBUSAXRIWWJOFHCADWHHMRQZFZXNQSWUBYEKBLWKRPOBTX', props),
compute('m_17_14/14: ${c} OETTTBQUAVXGBQKGFYIJVGAUOTICBKZQWLQGLSGMAWUMHDDDITJQZZOKVJITGFMMNXYJWFNLDYZQYOJVZKQIPIOBCUYAHLRBPUUR', props),
compute('m_17_14/15: ${c} XDFULQYAKCXFSZBTLBVEPLVJINACSRZNQJTUVTOTPNOGACEQERXGQINLBMMQTJYRYHLQTGSGAOCMGPURVMSDSHYFIBHOOPDPMZQH', props)
        ].join('\n');
      }
    