
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_5/1: ${c} XJWBKKQSXDQSSBVEHMEZHGMETZHXDGBKQMUVCJFYZXJGRAAPAJHMOLDCGKISUWPFMHIAWAGWUNNWMFMLMRQOGLMRYTJPLRGHMHDJ', props),
compute('m_17_5/2: ${c} JHZYTAGIJNKXZXONBCINJBPPOJGEGQQOZFQDMMZWGPKZGRCKTVMEOHJNSMJEJDPXTUEZSEKQLPVQZPGHXBNXAXWTORULGDXHTYWK', props),
compute('m_17_5/3: ${c} FPSRNXYNPLCZCIYOLHPJIHKIQIPPPSQCSYNCXFLVYKUTPHENVNIEQSJIBQCZYXNIMGWODSHXWCVWCJROUTIMNUPQGGHLZHIDRXYJ', props),
compute('m_17_5/4: ${c} OVKFXCXHGVIYJOGNXBMZFPZQZNAAMTQWNZWMOTAZVVWWHUQPUUSUFBHVJZDUDXOTUXGDQLLVJNUJEEUDHZCJYOPJHWNZIRANYZOT', props),
compute('m_17_5/5: ${c} KIVFXWSYIYZWQLBMUGGEUFQUBWENUSRYXVBGLPWSXEFRGFAHYZXVGHAAHEIDRLGSXGPECFIPQYIRHGWSJQNDOZIGMDKURZPFAGRZ', props),
compute('m_17_5/6: ${c} ZTFFZVFHEGQKDWOROOSAENSEYICFNIQUKTWUHGFOLFGNAEBJDJZYHLNATGNMMJRHZWOHCHBOXXODARFKCWHBWLTXHFMWAZVTHPMH', props),
compute('m_17_5/7: ${c} ZVEEJUPKIXOYWWXMPAEKHEVPGLGUHPVYFHQOJFFQOVNUJRUDRPABKPPRQKTYWUFOREJEDXWYDALRYBCNZGKAKRFCSYXDIWIGBNNM', props),
compute('m_17_5/8: ${c} RKPJKWBMVZOGRNOAQWIEVOHCRHPYCCWNPFDZZDPSEZTHOKSEZZCMHISREKSQOMGJUKJYNUBSBJFMFLTRTBSWXCXWZSUFKXWEUASV', props),
compute('m_17_5/9: ${c} OIXXOMXJXVPMQQBKMXCSOPVSKRSEKPHDTSPTOIZXKCTRRJWRQUVKRODMUOVILZOEYSLFMJVWYASNPGLUICJXXJXMYZKTBFTAYIHR', props),
compute('m_17_5/10: ${c} WWIMUNXYRYUSZFURGHKKPYSPOYPAKESDKGRYFIIQJYIBWBOKNLXHCQQDRBHFMOSIBCLRSCXXPETVQLCZFSMDWSKPAQNLPOVFRGSK', props),
compute('m_17_5/11: ${c} JBJSUXJEKGRGFLYAMXLOLXUVMDAMHOGGHMRNDMYVZGHKCXHHSEZERGQNNEAXGZTFNSKJMMLYAYVNNQFCVBTAGWNYZMGPMLXCSXDG', props),
compute('m_17_5/12: ${c} SSQQOUARATQVOWGGDTBKRRGTFZMANHGYVFAFKLSGACLYJSXIHGBJKXQHMJAUUXHKFTXFCRJIFAAMILJHMIYSADJIWHXGMFTVNKNR', props),
compute('m_17_5/13: ${c} XFBEPQQFXNOVWQDMMRUTTFUKZLVBYAUBWSSVADIRUOYQJYCSAFBTCIXVQNSFWHAZAXENABLGDVQFVITSDIHAXRFZPOWLQLSNTJRV', props),
compute('m_17_5/14: ${c} PZOQGZNKCLKRNWWNBAVHOWFQUFIXPOWATZTPEVOEFQTIZTDODEQDSRRPPLEGBBZVLFWJHROWGKLTNOGZVHGKDQYCUQZCXNHQLTSQ', props),
compute('m_17_5/15: ${c} VULFFGRQRUJTBTOCBLZRSQBFNVTYOXAVWMISQENBXOMWICEQVGGOVIAWOAUVKZBMKJAPDYQENVOUKBUUYQCNSXUHFHHQFUTXYIIQ', props)
        ].join('\n');
      }
    