
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_17_17/1: ${c} XLWMRDGBTLPBZGAWIBJAHLCTBFBFHNHZAXECFNOBZPAIKQQEUSGPFSBDPVHVCGKPPHOAGHGEQHYVOIPFAITJHVWYHNOQCYNOCLHD', props),
compute('m_17_17/2: ${c} YMIUCGQAQXFMXPWFBRDBDCUFSDENBTZFGIDYOCQIYIIQRIDEBSRNLBCOSGLMJIZYLGESOVTRQMQAJRUQTAUOFSUNDADSEWXQITWL', props),
compute('m_17_17/3: ${c} FNBTNNULUHAOZKUEUBPYLNATGADOAKVWQVEECYQLLVCNXRWWZRGSNBQYVHOSSYNZMTNCYBNXGLLEFPYHXRRZIOPTAWEVGQSHXGJH', props),
compute('m_17_17/4: ${c} FVLJHFYKYMCODICNKHYDACKIENASGVOJEDAOVSOFQLUUJCJIMUNJZAFLQWZBJGARCIRUMGVSTVBVYQTAWPIHOVDDPTFPEICARWTQ', props),
compute('m_17_17/5: ${c} WDHQNDPPTQBUGYDLXTYOTIJTDNQKUWBUOCEBWVYMXRRUQZAASCYXIWZQMYRXVKAVKIHDPROCIXEKQINLWKIMYDATTDFAOXNXCGMH', props),
compute('m_17_17/6: ${c} GOJPMVRVEMQYVDUSPFNCRFPAVMFLKBHSJWLKRHXCBLHCUIQOTGZZBSLNJQBCNSCXVVFJGLNEZLIVFEEQQXUGGGJESCRVPVJYJCGI', props),
compute('m_17_17/7: ${c} MPYWRQMOSAJDIFWWCAOBIQETAEVKWNDCZMUJDVFFJOPXCTEVJFDSKTJFAXZZOWFMIMGBXLSKDTRBDLGCTIASEDTJIFEWPMWOVPRI', props),
compute('m_17_17/8: ${c} TLSVBYSMSYWHAQXFJKFLMOSZPQCHHGWCSPTYXBUKELSVIVULVBKMOXASIRKTTIRXPDGABJOKYEKUDTAVZHIQGZYHHIJGSPTAXKPX', props),
compute('m_17_17/9: ${c} IJWCXHDCAZXQQABOMICYHARQEYAIGEXSQSXKISFIQVGTBAUIPXASOQCNRAHOMOAEXUHPVRMDLMVEBWZUSOGZQDTWSNXVLCXWEXWE', props),
compute('m_17_17/10: ${c} UGDBNKKLZZZZPLRDXAKWVFBNDRHYQCGVPVJQABEWZWGSTTSWGTMBWKLNVDDKKUKDTUWDYNFVXTVOTUDENZZWNNXALNHIVCREDZDB', props),
compute('m_17_17/11: ${c} TVLZOOAMRCBPSXMIBQHCOSBVQRRROUZOPHXORMOLDTQMBZGUGDDBUFFKPHUIVUGGGCIEUWJRTFUBKKNVNTUSKCTKDEHSZBYNNPWB', props),
compute('m_17_17/12: ${c} KZPNMVLNKIDULFGGSUWJEKAGCSARHHYUWCSGZEMENDRBFVRHAYKPDDCPKDSDFXIQBYDFSIWTVKADWWDGHOYHBJHHEWGHIWEXVSAV', props),
compute('m_17_17/13: ${c} GCDCYHPXAAZPTBEJMOBCINBXIFAHALPFOUGJULZNUTSEKBQNJMFANFFUUHXKPSYEVWCUPAEFECLJATZTXBCGIMPXFTGDMBTDOGCY', props),
compute('m_17_17/14: ${c} UBEENKORCZIMAYATMXSMOKMIBLGEXQTAIFDPFBNTJDJWDGLWHLSHFCHJTUUILROWZAFEFUZQLFTAPUUWKZKNMRPKOGRDGBAJQMNX', props),
compute('m_17_17/15: ${c} WJUTMKONUUQOUZOUXDQMJVWOBIBWLRSKEPDHQXLRLITPCGONZMVYSIAXLMUOGVAVWOAELLNHRBDYMOCKKDYXNKRXKQOAVKUNEZMM', props)
        ].join('\n');
      }
    