
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_18/1: ${c} EZSVZXQOVAJFLWXCINDRYYJBHYMIOKXGTTDBSAXDSEXKVYCIZAUFUGNUKYXIZWUXDWZYCYIKNBOFHFPUBTHFJTEDUMZCDQTTXIJR', props),
compute('m_18_18/2: ${c} UGVMIBIQWHYDNZMMJYFLGEJCAHRCDQWAJMFHHLHYMLFWHCDPGGKHTDRGRJYFHTUDQDKUDJABXPDCSLCBABRQMWDJDWMQIAIDYQIO', props),
compute('m_18_18/3: ${c} YSGXUABHQDLKHOJHITBKYWLYSXPKOPQZTNXAHDNYRAGRBWWGYBOAXXDBGYJIIUPUWIOWTABJSMUFBHHONCZLYYMYGRXGKEWYWXII', props),
compute('m_18_18/4: ${c} XOWHWZXRITIXUEIVOPKMODGZBFSVHLNXMASUAUVECUXZLNNBTDGMNAKYPXMJAIEXERIQITUPRMWFPNWJXCBZZWKXVHTYHCHMLRRB', props),
compute('m_18_18/5: ${c} MGUONZUECMGWWXHKYHHZPQDGKZVCPIMEBFUFMBWZRSRJBJFRBCKSERDOZOMADJKQXRXJFYKORARFEJHRDCMRLIRPQQIUNFLYTJPO', props),
compute('m_18_18/6: ${c} BJJPEKFKZRMLNAFNBIIOGHZGPBBZZIXCKLVOEYDSVGFOCHNKDCJWCCMWRWDJYGOSNELDJTEEJVAJALLYWXCOLHBUGYGITNWPYRTO', props),
compute('m_18_18/7: ${c} QUTECMERELKYYCVWCMUOOWXXWHTSRXPJPKUQEANQWXNIVNFWHEBUTYAXIYYRSLCFQAAPYMWVLTRBFNKTOYPARQOWLQSBWVLOROHX', props),
compute('m_18_18/8: ${c} SSMRIJOAHTKJGARXVLBWAUNQBLBOKXWRSEHHBUXEWZJMCKNVAJWWNDYSKJYBUEJJHQGXNKAJYWEBMFZGQYYVNEVMFKSTQQSCUHRF', props),
compute('m_18_18/9: ${c} NYJXABMHEAYIAYZGRDSMNHHBMRKXXSXVXUEUCSWCCQKFCCJXWYQKVXCNWXCPXWBFDFYIBPYJOSZORSCXTPVHUCASYHCEWMCMPSEW', props),
compute('m_18_18/10: ${c} ZCDWEYIPFIDADQDOGZNEHJTUOGNUGSPTDNUEFBZOXCITYRUTLZJXTVBPSLDNCFVPYKKSHMPSGUFQELEXUNPQQGGTMMPTCGPWUFGT', props),
compute('m_18_18/11: ${c} PYPUYNIWJUHERDWOLSHSDTAYNASXUHOLLRKNKVNKDOFIHXMFHALZPEEMRUICMNZOYLBGXQYFHHYXYTGHWNAWYRKBFLFBLDMTPOPG', props),
compute('m_18_18/12: ${c} FAIVXKKHGYNIIISIKSIGOBZGTJPTCRGGNJRHIKFFSPTJNNOUVJBCTCJNGURILIYNWOTEFDMJQRRBWQQAUAHMLTJWKRXLXULZHCAK', props),
compute('m_18_18/13: ${c} OXWHHXWDCEJLRXVKWRTPVTEEMXQOLPNXIWGPQKEJSRKHILARLMCBKOZGJWGESALRPGOHFUPKLZPQJPIKTMHKOZJRWICLXOYPPOXX', props),
compute('m_18_18/14: ${c} YREFRXPSQOMWRMAGFZYTXAKYDEZSBOBPMVYYSEWFGQNMPBNJVTUDTZDSMXQXEAJOYYICGDWGCTCLOGFPQGOPDAXLTADZDENONCPQ', props),
compute('m_18_18/15: ${c} BZOREMACUESIPOBNWVKRLOZGXQZTIZLLUUYVCFEJENDRVZDMMENDUIGJYEFCTMMZDGEJCATGVZYFQGLFEAANZVWVDZGGKPJZICYE', props)
        ].join('\n');
      }
    