
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_19/1: ${c} GSJHVUUTERGDSXKSWDGFWNSQDPNVNHQQOZFLMVMSRCDAIZFPMEVDHOJGDIPFEOBDYKIFJRRNHYCHCJGHLETUDHGETYAGVCJPVGFG', props),
compute('m_18_19/2: ${c} YRWYDYFYFVYHNIMKNXEFHUPDLGFAZZEHLNJPKFJQHQWMJWNNVCBDSAJZMTPDITBKWSMOPLSXTLIQPJREFFFUQULSEDICLYSFXWSX', props),
compute('m_18_19/3: ${c} KQZUKGXBOBHPFPFFSWWJXTLTHKXJXBHXXRCMNISAIUONZAENBCOYDUOKARTJEUDWSDLVJECZYDPJFFETGAPWWMUOOURULJTBABHG', props),
compute('m_18_19/4: ${c} KZGZQUUCHIWYYZSWBNDHQKOSPGXWYFEOWJCOMZDGMBNMKJNZBRBYZNYQKTACYDMJGNGPUMNVQEFYVXECQMYRAONMJPALEWPKBZLU', props),
compute('m_18_19/5: ${c} ATMUENFEKRLFPZWLGNBEKVDPILIKYJJIPXNBTJJIDQCPRBIKSVIPKYPROCXUJUAMWPFCLQBUSWHNEKZIYPOAQHTOBTMNFCJMXZOZ', props),
compute('m_18_19/6: ${c} SFVASLEMIXKTSCQIPZLRTEMCGFVFADIYQYMNIGELYAIFOYAZFMFFYNMHFWSEMEMMFSZVVSFKRMAUZXLZXJGJAYORTZEEEFCUKVCM', props),
compute('m_18_19/7: ${c} GRWTGNXJMJHMMXYWHEGNQDMSXIHZAHLGSHSQDPJNTNCBEGBPEXHLPFIPIWMDJKBHNIZGNYNHGWIAYYKSSNQZUFIRGMJLKLDYWKIL', props),
compute('m_18_19/8: ${c} SRZOYYEXVDCVPOHXBBEZUYVEZLLWJKFZBOFJZIGLGQINKKCIUIFWINAGOSGEJXBNYQRKFVSRBLZSLDSDVHNKTAUERJCJKLSFZNVH', props),
compute('m_18_19/9: ${c} JIBVFYYARFINJMPONHICHOPIUHUSSFYZDPWVPILUPYAPGBTHFBDLEGGMOQYUEHXDUHGWWZLRXPEAPQLNQFQFYZSNUNHQIUMWLZBN', props),
compute('m_18_19/10: ${c} DFYIZJAXKZCOJYEJSULBWMLHBNWKHFJLEGFGOLPIMBAEJHOLPRGWQFYZDVEDGBMAGMLSZZGVMSWLSUFFSRCQKDSDOXNLURCLBYNM', props),
compute('m_18_19/11: ${c} CSJKDAXQXHCLWLKMSRKDTTAHDZGPYDVDFEKYRAJGCVHZTEGHNKKYRDQYWAGEXEHUSPPMKBHLFRAVVUQKYNGQMQWJIOOHHZNLGWVD', props),
compute('m_18_19/12: ${c} VNVZNEYGZLCUEEKSPEMONTBXAIWNSRBYYNCTCBPPDGHLFRWEMHUHQQRZDWKSRZGXMIYRWNFNYWBALYFIWBWSPNNVHYDPEQEKIQYT', props),
compute('m_18_19/13: ${c} UJHRVEHKPLPFOBTIPPDXTRPQTTIHRBEYTFHCCSUYNRXKIAWZFJVEBCZFECNMLDQDZNXUHMSJDWEFNLSLOILJRARYWIEBHBOZTWTG', props),
compute('m_18_19/14: ${c} YEECJEPKSJPCPITKXFFNANHGZMUWDZRSHIENWPUSCLRJCOBMMWZQMNEPWUGPGTPWSTCBUZYRCMCMDBYOAWSMSQPNKLMFCSMVNGAM', props),
compute('m_18_19/15: ${c} BCGYJCLQBOFEMARXKAQQRHRHFLWBPAFCPLDLTNTNCUNQGURNGQPQIEJYKTNGKPUUAAPYDYFNOZREPGDHOUGFRLWATPHUAGDAZMYA', props)
        ].join('\n');
      }
    