
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_16/1: ${c} RCDOSHWMSWLSHVDIZFCVITRIUGCADKTEHVBEXNPUTQZVFCSJIOQKZZTOSUKKKQTSSNKNKUQVNZEILRMXOCJWMAIQHPWUKIHNTDTY', props),
compute('m_18_16/2: ${c} UKSTANJWAINJREYHRBZNMYLJDKBCMOSIWKDSCLZZNZXADBWERVHBGKJYMFADYPQXWUHVICMKMHFAMWYINNJTJOCIHNDYCIUNOKAZ', props),
compute('m_18_16/3: ${c} LPFVWNURRYRUAUPCHZQOUFNQYKBZSIETRVXTINHKQKLKOOBCEEDKCGCMSMGXPVLTKDLMEKQUWXBXNUBDRZZWSUJRCAGOHRZAZQMJ', props),
compute('m_18_16/4: ${c} ETALNTMKLNENSSBXCUKZJZSWZCGSLSURRUJCHZMHZKDYFCALHDQEMVRMVQNMWTQOREZMRYCXYHKHSUPIVEBCFSDOGUXFJYCEACWF', props),
compute('m_18_16/5: ${c} VOSZLEXQAZGIFMUIHOZKOOPVLZYVITAJNORDCRSAMCDMFIFGDQRNHPACXWZHXYAXNDXMEXPTXRIIWJSMGXBHUXHDVAWPAUTCGBBF', props),
compute('m_18_16/6: ${c} HETADKUXGYDGWKFAVTJTLOHOBWHFLKBJVDTBXOSCSKCBUSJUOAFCXCSQFOHITWCUTDICIUEWMCLHNBCJIJYCONLUPHEYXPETPFUS', props),
compute('m_18_16/7: ${c} ULPBQDYVIKIOFYJRZRSHOWZAMRRYSSCWUSGTLXRIHISRDBNDSXXDMWQWOHWSLZFXVDFNZKBMSQMAQXTNGRLNNFXWESCXTWIBGLYP', props),
compute('m_18_16/8: ${c} MXMTLBIBRIKMFIXTKKVEVKLLAVKCYADOGYZLTULJXBKNPYTSWSWXBMXBYAGUISNTZWYVXOLSZDBNRWOVLLFNHXSNOHWIIKAVNVZP', props),
compute('m_18_16/9: ${c} WLETONVWPWKUSHEFSYMRJHLPQNKVIGEBHTCUCXHDRURDPEUIFMYDQHDBZYJVEHSNNFELOTVNCWUJEFAQKYTLUZCNSXYZDYHSNVQU', props),
compute('m_18_16/10: ${c} TAQJSKIXMTUDCJDGLZWNLGTOKIYMNNIFPXXFQQOLIKYVJMVHMOXKIPOAADZIZDGMACQSBYHLJXVYYHTHVUAGQFSGFTVJMYRZFUZJ', props),
compute('m_18_16/11: ${c} PCRIRYTTBQTFASCZXBMYHOVNFTWOKIYBMWBJLXLYHKKUNBKSMPARKWXENYBAOEDAYJHNDEWEINWUURXPBKDAHPKMTPTUHZSPNRHF', props),
compute('m_18_16/12: ${c} ROXZFRXTIREGXLQWUECOEKUGDOYZCYOTRTCPFOCHCZJCWDJMQMMYMJGTHOQRYGLGJYDRKSLICGPKEGQPEQOCAUZXFOURYNBGHTTJ', props),
compute('m_18_16/13: ${c} GXVABQPJLPFEZVSEWQRWYLEGSFKGQRQRBIKTFJSBIZRZVBAUTPWEFMXSSRFLZYCCSEIRPSXBINMCKNNOOTJRUHHWCEERXNQGHDFA', props),
compute('m_18_16/14: ${c} FLADUXLGVNAESZTNVGMGYLYEJVXZBZATQBMTFOSWOJQFNXNQCVXNQHOOALVQGTNHFVHEXOSZAWTKTOWWUWOBWCFBNTLQLCLCLCGB', props),
compute('m_18_16/15: ${c} SDWRWOWJMLSLAAGLXHJHAELYPZBIPZTKTTXCWGVALDRWVCEKDTDLVGUGZTFBBHWXXUZYGDNOZQHYDPXVQCTNCZJDUDFEJBEIITML', props)
        ].join('\n');
      }
    