
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_12/1: ${c} JEYWTTRZMUFPQHZKTOHIMKAIXMUHOIASMBHHVHTRMZMDHCHSZZOPBZLKRJZKBBUSYPDOKMROZWQONULSESEZPXHRYLTVNZVSKXHX', props),
compute('m_18_12/2: ${c} XKTQTRKSDANHPFWCMUQAAFKESUVUENGIRYWCDRUBOJGFTPGHVUBAVVFKYDXAYQXHWAZXSUVLNKJQEUADMHEPMCZNFYSULRJUXAXP', props),
compute('m_18_12/3: ${c} PLMIMYCDKLWJVYRTWNZDOQSHAHDUITKDQGOSLEQRZUELZBTXIMCPGXMMPIJTNFRILHVZWTZFSOSIVHPGULYORDVJFKHLDNILGIXB', props),
compute('m_18_12/4: ${c} EIDVYOGKJVOFDFWUYGMAHOXYKMYDRJYKWFFBPSBCUBZQCYRQVDXXJJZAMBJXJOUZYMCKLDJGLQNGNSQWQMSNCTKLLTAPRVJDJFLT', props),
compute('m_18_12/5: ${c} XZANSSYYAVRTSTSOKEAXMBGTTTJNXJFDLILXASIHLKGZHGJMVILUYZZFICRHGWNXVUOADMWIWRPOSPVNHBXGWPLZQEZRFNOPWPWF', props),
compute('m_18_12/6: ${c} LHIPXYMUMICHEQICMTMVXYRLITCQWXPCBLSDUMWAYXXEOFHPRWCDYQLEAARPDFMZMFGNFZLWABNNKZPBNDKMOORIXEUOROKCVXOW', props),
compute('m_18_12/7: ${c} SSJNLIEHAMANKSZJFVQIIVNYZVIDSGZCZVFADPEPMCNJPESHDFEACDLZLRTSVAAYKRSUVVHAUYAHWRVJLGNANVFMPOWJLVJBNWGN', props),
compute('m_18_12/8: ${c} LVZTLEKMSTLGYSHIDUICMILDGJUBEDNQNBGCKTZJFKZVAUIWLZDFYUFAAZKBWQWXECNZEFMFRECDSTPDBAUUPMACBTYELUTKWFDV', props),
compute('m_18_12/9: ${c} WKBBCPVRVFBCCCERCGFVPTWNOFAGQFWTXGDHRLMEQFPLNWCCADJLDYSKLBYDEHBMYEJCEWJIVANALZMURDVWKOCRIAQVNJQZHZCJ', props),
compute('m_18_12/10: ${c} YNHWHBPUPJWZIFPNYRESQKAOILUIFVIAFTTALDZCZZWERWSYAZBYVNJPRNUTWLPCVBFDHKGTNFOHNWJFCEMPRZPJPTVEUECJIGXE', props),
compute('m_18_12/11: ${c} NSEGESSGKBGDSYAAXBXSDGAEVMSJQJCWAYQHUKRKLZEQCKOXYSLXYBNJUUZPTPRLGZXYRARDCNJYUIZDFRDKSNSAJHAFDWEBLTBV', props),
compute('m_18_12/12: ${c} JZQZNTCRDNQIRGPDLTDNKZOVVPMEQEHSRTSFCVFDPQYYJFVHUGAWSVKMIRAKWFBUCZYYMSXHZWUNWRQAHFEBSQUJYLCQZEYWXYYH', props),
compute('m_18_12/13: ${c} EPVNVCNEZKOAIHLQMYIQLGBLCOCMMNJYBERSSTILDNHBYGSKOQVDSEIBYGMMSYFWXGUXXIGMRTXXYOPNPIJJPNQVUKDBAZTIZRRW', props),
compute('m_18_12/14: ${c} DJXTVLLWIVODAYCCTCGIOGOPWAAZGFDBQRJSJLVTRWUKNMEIVCLWPPTPANXFQOOKAZOPBHOQQMOHOEIVKTKPHKDUJDENUHXAXDUY', props),
compute('m_18_12/15: ${c} KIUFFEJJQCINZNAVBIKDOLFXAUSTPDBJKCYMZZLXRGUUESFJEENEQSBXTODBYWODPRJMUZRLCUWHABESRSUTTRUXQEDRWBMIRTCN', props)
        ].join('\n');
      }
    