
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_7/1: ${c} YZYMBYMYNGMLGBXMJDLXNDPQQQBGJZAAVOBDMVTDJCTIQCZKTRSAKIVLZPWVGIJIKOOFSNRKHITFYQFZWEGFTRITAFSPDEXBGUEK', props),
compute('m_18_7/2: ${c} CKSFLTJIORNHQYKZJQULJHTPYTAWSXZIUMARFNMNKRNUVYXDFNDAJAYIUYDSKEUEGAXGTBPZNHUACJEJGIEKVYSHMHULPAHBPHFD', props),
compute('m_18_7/3: ${c} AJWPBTCDUFNDCPFWMHDWJXXDNFMAGBDAQLIWVOPZTARIFHFLRATELHPCTQBWDDGZUHJIPQTAZQVJGMBTMNCWYXVSXDQBVMJNAULJ', props),
compute('m_18_7/4: ${c} WYZXWLKREAQNXVDYAUYAQCUHEKCNTHBIEUSHRUUCMORHFFODMQBYXPTAYJKZOJCXOKMKAZMDXBIZDSZTBFHOEUDQDLKBZBLTSSKA', props),
compute('m_18_7/5: ${c} QQEJCGCSAWFTNHIWWNAYXTIZEHRAWGNPVIKAZWQMRLODSTILGBKYTWWHZWZUOJWVHGIRUPNSBGKNHGNJDWBJUYSRHMCDLBHOPIDE', props),
compute('m_18_7/6: ${c} VSSZTSXVKGSMYDTGHCZEGGYDVLXARPAESGXEUFSLKVLGSSIFORFKTKLTJPZHRMJZQSRYJAAWEGWHGHAMINJDGGSYTJLIKJRRSCAL', props),
compute('m_18_7/7: ${c} DMYONRQJVQIWXNEUPLYYWLSPYYDKXXFRBMPLOAOKLWEAQUPOSNJITYDUIAKNSNHEISBMWFTIBTHYCPRHUGJWRBIGJKUUUIFXZZHU', props),
compute('m_18_7/8: ${c} JLGVBFJORMHVQKDELQOOVEEQBEGOALNUDOYIEBZFIVHKEHGBNUYXGEBGBDQVFOHLEWHCWXDXEVXZGYUKCGBPOEAQVLRECVITPCXE', props),
compute('m_18_7/9: ${c} OBCCQZBQFKIYCYYJASCNXVFCPSQPVBAKRIHNGISHJAIQBSTYGJJZNKGMMHDDCQTCUNECVHPDCMAVJJLQHZCGWCXIUBJWCQAJCEIG', props),
compute('m_18_7/10: ${c} ZUSINGHGMZKLDBOXIZFGRRXEWKQKKMZZBTJMVAXYSSXONRZZWYHCRCIUYCFNONVCNCXSHGHVJDOUAFMZQFMHNTXUHBTOYEQONHTL', props),
compute('m_18_7/11: ${c} ZATCGBCJEQEBSHESYPTARJPIVJXHLCHNJKOJREFBBUFXHQOAHJQWVJSNAZZANFYYFVQITUMYQDNOZJKLNOMPYHAVJSTEFTQPSVGL', props),
compute('m_18_7/12: ${c} OKOACXWMYEGCNOYXLVXZOAUPUORJLAINIZWRBXROGJEBKEIHBNGAQDALXJVEEKEQTTUHDLUIUWESLFVYLGSHDAVYDOCVHLZOAIQM', props),
compute('m_18_7/13: ${c} CROVNJEDTIBOCTGUTCDVEOKCANEPZBLKDJGGHKTRASGRMDZELTHTLVYUISASIUGSVMADHWUQKIVMHNHHKSYSZZTWQJJSTBAMYYJU', props),
compute('m_18_7/14: ${c} APVTKTKVJUKPYGNEBZRYHTFAJQMRPLOCTMXKXHGOUBSOLFDRESQYFBSEQOOEFPIVCHYTOBONVVDJWYXOQUCJKNRXECEEHGPRSCVK', props),
compute('m_18_7/15: ${c} SLXLHBSNLAJXTXVOQSABEMOZQAXVUYLOGNUVBNUFZWDNJVQEHSHHRNTVBYZZARXBTEMFNPRYFRVKQPUYEGDRIKXVGTBQRYYEDMUR', props)
        ].join('\n');
      }
    