
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_13/1: ${c} KYPHDOKPMRPEEQZTNMZGGFNKSXGDYUIQMOUBIMUICRMVIRMGEXKOMHSKLFUCEWWKLVTEKRNJOTWQMGIYEXZSIIOROVIOYSGAUGLX', props),
compute('m_18_13/2: ${c} GUVPSUREJIXMOKPKCXWRGJVBYNJJKALSTPBONNPSHYHFWFHSTGCDGXRNRJKYAJVCRHLHDNPFOBUEZNMPCCFAODFETSVRLVGNIJII', props),
compute('m_18_13/3: ${c} LSBBCOXOLYPUDDNJWUWUBAAAUYDKBYWZMMDTTLQPUFKNOCTVZAXGAEFCFKKSJTFVPRFRGAFBCPEVORUXLFWHVBAWQATMCUGTOKHX', props),
compute('m_18_13/4: ${c} OHLSAYRCYIHNEUHAWGUKVPZKOTYHTFOMCRJVDLMMMEFCBVDUVCANCLPUOSSRRQFWYEQFHXBNAMQGREFWBZWBVBBPNVEJVADEYGKI', props),
compute('m_18_13/5: ${c} HYNYCZVNCGYCEUCFEYYASUXXYMZHNRAGBPOJQGMZUJLNVRWBWZIDVNEKPAFUBPJXQRWUTCYFJZUGTDPPMSUNLNAKRHZQNTWRJUWF', props),
compute('m_18_13/6: ${c} OENBCDTHARXFSQXYOULKNOMMQETBARJSNJOJZKZZPMHTJQMHETNFZAQYQKRVAOPROQOHCPPXMWKBTCYRROURVVYAXBLBVQJPSDAN', props),
compute('m_18_13/7: ${c} AYZQDBHWADBNHVUYMYDTSITNKGHPJYETGVRVTOSKAJGJUJUPYSLLTQKUORYXWDXXYJISZZPOIVABTNMYQSVCIWVAQATPBFQGLRWP', props),
compute('m_18_13/8: ${c} UMNIGMACFQYRJSTJQFKXDKNQIHIBVLDWAOCMDAUUMVUIQPVFQXHWUOFPWCNZVPRZNQJCPVNBNFJCTVJUCLWCBNRESKZITRHLNZRL', props),
compute('m_18_13/9: ${c} CHOJMSILMVILKXKSIDQRGKUCWQEJSUMKBRLPSRUKKBIKBTDJFRPJFJJMDVQQSTGZCWLLFKWYVQXFVWXJCWFDTXMAOGYSBGSKMPQG', props),
compute('m_18_13/10: ${c} IHTKFKJFRYXXIEEJGBNBATRLDSTJGTDQFEHWAFFINGNZMENEZULEALNNUPZXXNOZLOKINHKTHHXLMVALFMSUABHFQMIOYQZYSUFE', props),
compute('m_18_13/11: ${c} QTOIJHAGXKWSUCNAUWZHFKUKKAMBOQATQCZDDGASNWQLIJHZLIJEQXTEYJXHHLMPUMFRFWFYQCHXEOGIPLGXTFUFFGMPNHCVBQOI', props),
compute('m_18_13/12: ${c} BSXQYMYAYLGMEVQAMNHDTQEKELWBWBVTGAJXSGXQKDPAGKOTVGAFKGDYPWDHLSIBNLCQWIEBCRZOQQAZLMTNSRFIFMAZUJFJYBLN', props),
compute('m_18_13/13: ${c} TDBZQQABAVMNZPZVUYIRMJKMGQPOGXOQEXQJTAOWFXUBFTONOLOHNAAIRQCBKHYOLQJXIIKLYATYTIFXCCDXFJMWOJNTAJUCNTTD', props),
compute('m_18_13/14: ${c} UZQUHYWHOTBCYNKPZBVALQNOARPCNHRSTHVFLMTXDSWYWICBJAZTXQLRGMIBYOGFAJYXBLUEJOELCMOFFZEALAQAFOPQKBSSEIEK', props),
compute('m_18_13/15: ${c} HKPUSURTNBQOHEGYZVMGHFXQIAQNNBUVPKRAVBUUBGEIRNUWVQBGKLHVAHDGNFWHXKZBIIHJSMRARBJAQHIXVLGKLDVEHSZEDRWO', props)
        ].join('\n');
      }
    