
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_3/1: ${c} NCVKWUVXWUNVZZMGYZPCNLUSZLRIVQQZSKRMNVYOVWMYQDHFHPUQDUBPKWLONHZFFONQVZDEGSKWOQGXKLTGTHHWRYQIMTMLFIYC', props),
compute('m_18_3/2: ${c} ZAXGZOKCTFTXPCROMOTAVUFQTMAOVRQHOYXUMRPLWXURKNYMFOFBGRKGDKYZHZPNNFPSGSEWAONCVDPUCLWXEKFBJPZTDVNCXLOY', props),
compute('m_18_3/3: ${c} JCNIKZZMTFHWSXLZCXCMPAPZODRNQESORMTEOUTZZPOSBVZMMIWBKUTORAXQJGEYLRQHJSODEMJCHEPCPRPQIWTRNPKJBPXFNJHW', props),
compute('m_18_3/4: ${c} ZEXJHVKUSFFMYCUHVWDEDLQONQPCGRAGWNIRRCZVMLPJGQTCPELBJCOJSBQSVLRMDAXYMBVZIAJBRCNDAMXIBBQVCEUFSZEUTKTJ', props),
compute('m_18_3/5: ${c} UWAGXJDWRFAGXSGFAFIMCPDQBHYLKIVAFSVDYSNXSHAVNIVNCTRLALKMHFZVASEQQZYSWBBUFLDJABEYZQVOUNIYFFEQWRRCNARZ', props),
compute('m_18_3/6: ${c} XTCTFEFRLJOJAUIOPJLPZYXJOZPQBQPNRUBFBTSCYLYDJLCPOZGKWBREWSHIWALYNCLKLYHAQARFWMURLDBLEKNDIKKTHNQMBOEK', props),
compute('m_18_3/7: ${c} LEKTLKSBYNDGXLEWYOVKYYGMBPSXAILWKTGDQFGJHFGIZKDBVKRMQQNCAOVBRNKHHBOZTSLEVYYMLSSTNZYSUHGCFTPCITSKIROV', props),
compute('m_18_3/8: ${c} VIMWFSXHDWMRGKVFTRQTWVMFTYSTIQBHHVGXJEZIPOVXHBHSGFPRAWQGZEJAVDNLTCMIFLMGIWXDRHBCSLLESWOGQVYOMCXVPWKA', props),
compute('m_18_3/9: ${c} UYVJOMEIAZPNYWFNPALQYFXVWERDSIPRZFZMVBPCUGVRNIHMSLXCWWWSJCCLOMWVELRCBAVWGKOKNBSWTXPLFYBZXURZCSBHGFHR', props),
compute('m_18_3/10: ${c} FLSMVGRXOHHPHVGMVISJXJDOZGKIXDYLXCEKIFTADGOUQRIHZDRHEILRIQHERHBMIQBBBPGZAUMSIZENENPXYGRRRNEIPPNLBUOW', props),
compute('m_18_3/11: ${c} SYZWVLRHZKOIXOBDYPLWQIBUKJVMOWHJXFNEMHUZPUEBOANPDKBOLYELQIFDATZFLZWUJOHKIRTGBNNLZVZVRCQZLTIZSDFUEXZE', props),
compute('m_18_3/12: ${c} BSWSUCVKHEAUINHKEPDULIWNDRYHKINLLZQQFVANCWTSHIYHZFSTXELYBDFXCWDDPDWEPUGBIMYFEPTWYQWYDKDWUEAMAMATCCMK', props),
compute('m_18_3/13: ${c} HCPZMDFLAONTRVPTAIILADBUUUJCBUZZYAHJZIYVGNTTXUAVLKAFAYNGTRAZZMFGOCALOSZXYNBVYKUZJJJYBBGXWUNUPHUMLHEG', props),
compute('m_18_3/14: ${c} ZOZHMAUATVARYKOBZRUUNXQJGJPHPUHDTXLMJPQVFAMQVJVAQYZWAUAJVXNFWTSFDMEVOGIXXLZVOWSYWFXCQQQNZMTKWKFLPEZT', props),
compute('m_18_3/15: ${c} IPXILSZUABMSAMEJZXKUAUTQQZLGXFGHBCXELVUVDLSNUQHKXHTHITUZAFKXQECIRAJPOKYLTAMMEATOYNDOIPTLUCIXHECAWCMK', props)
        ].join('\n');
      }
    