
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_4/1: ${c} KUGODUKQPYHJXSKYYKLDQBUKLCVRVOSFJRBAVUODRHKEQRVZCZJJPQXIHUHRJTOVQZQMSNYWQMLOINDPCMCVGQQTKHHMAZWAZPOK', props),
compute('m_18_4/2: ${c} TSEGNRPPOWAFAWMZPTSPICHYQJLUIWUAZFDWTBILNTQDPQPJREFJVLOFCIWNMYFCSBPCINSJAAKNNBLRASHJMEQOUYOVJXTFJHDG', props),
compute('m_18_4/3: ${c} RXZXIGBLUPFKFTUGBPIUGRCMFXOIWDIETWNEYSHGPZPMPRGWJGKKBGVDKOIYELADVTFFCIABZJFVQRZZWQQORBPMAHLXEIYEHHLH', props),
compute('m_18_4/4: ${c} CWPCFCMBXXPPMLEYOGNWQQPKTLFCHSNRQTYRHARJGNMRWELLFYLIFKAFIWFDKNWOGFAUJFEGNNXEBQFWDCFJHTSIQKMMTHBPQYDG', props),
compute('m_18_4/5: ${c} HOVZLJBKJEFSNKYRPAHYEPYGDFWKOVQGWDDPYSPKSZNZPDVGYPTYQCVESAAREWWDWGLMZVYTKCKEVNFWIIMHCQDKJFNMYLFFXIZY', props),
compute('m_18_4/6: ${c} HNANDWUIJOOMJXTDIGLZIZCQBCTSSWLYFUOAELFXNFXSRJZMYGMRIUQJKZVSRUUWMLTYUZWEJTHEGNLBXNEBNAFSSUTOCYWOGOBO', props),
compute('m_18_4/7: ${c} RYEHNRTYLITJFJYTRDNKLATMPOSFUWMOISTCKKMATVELGXIIVZLKYDCOANGLASBWEKVKSTPYGKAITKZFTEOCHTGWUESKNZZTDNOK', props),
compute('m_18_4/8: ${c} SETCJAIGCRRLRSZVBMHMWQPSXSRDLYQUXVTIMMFOSKJXYNVHQLHSQWLOIKEGUNGODGNSACXXMWSEVCQYPYPJIRVYUZSKBJRWCVEZ', props),
compute('m_18_4/9: ${c} WFIIFWMTTOLSDLLHGFLWMOZPPBZZTHFXVITQUFYEGACAWAABRFNHTSRTNFIIAJFSFIWJEAVSBHXPHSGMVVJWCSWLMJTIWQDQCMJF', props),
compute('m_18_4/10: ${c} JUVBPZPZHGEGCRINGYDQKNUZNLAQFHHNBMYVITOQWBFURXDJZITXLEPZORKNCDBLBZLDELQEPETAJYFEBJFWPBRWSZOZSSQJAWBK', props),
compute('m_18_4/11: ${c} RQKORLQPJWEWGKIJGWULNNZXDHQSMAORNMTLYFCYJNGSLMKMZEHLFQXRQVORSIUBALXCGZFQQWATGITVRBTEQAPYDLMXALICZXJV', props),
compute('m_18_4/12: ${c} IQIDFABFSSTQITQPFXCLRSQAPTZPBFAXVEOPUGYZDAONIJCENQIRFMXDYRXDHKCXXWVAKGBGCJDXPSNFEYGIAWVDAGICISBTRUUF', props),
compute('m_18_4/13: ${c} UZEYBKVWGCGICGLGYZQGILPHFWSQHBNEDCHHVWDGLXKGKWRRQDHOGECTDNWZDWWZFNKKGXBDNALHDVMDXJLXVKMYPCUATQABIJZY', props),
compute('m_18_4/14: ${c} TJDAXTEBXMGHBPWGBKEAEOMGZYSLRKTALWKIIXTCZHAONDQZWUMESRUKZIRISPKNTKCLEPZPBASGUFITWGBNULQFDGPCEVFXHLEH', props),
compute('m_18_4/15: ${c} HPBRHAWTOTUOAFJQTUMLRVCQUOSWCGOYFSYBXAZEFVZKEDEATLIDBRMPQXYJOVTWHIYXJGGBHTJWDYBWIKFJWWPOFNFSVWFBQTVH', props)
        ].join('\n');
      }
    