
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_14/1: ${c} YOHUAGUOLYZVRHHRMCBFOWSHWKNUZBMGPQZLCIVXYKLWXYTTJPFXUKRLUDIFRXPQDLZDDEOTPXUPDDMYJWWUASMQBNTVUPEJWZGI', props),
compute('m_18_14/2: ${c} ILTFVCYDGTTNISRXICGZSSBWTVGUIEWJOICJVHQMADYMRTNQOJICLKMEDTNQBFDGIZFRQNTWUIHGYBANANQUTKOJPOPENWNOAYFJ', props),
compute('m_18_14/3: ${c} NVFTYWAXGKBFMSOKSSZVMWLXQLVQZCHQGORZDUQBILDGYRHPTNRPNEYFYFHOJSMMISULEYUYUMYARUCZTRZRSCEDHSVZNXOSDHGR', props),
compute('m_18_14/4: ${c} MBZXAMIQNDHJFJMGUZIFFRPUBWDCWFPQKLONCUAGWMZCGOKJSPBZRLXTCDVXRCRKRKSYDQUDHTAVPGGIVFQABJOTULHDYQNKYGVK', props),
compute('m_18_14/5: ${c} PAQHLVIEZDUULCUEBZDLJBDHLVSPYXCHAPCXTJWIEAGOPPBUKDMVQYVJMZMLLWMPEBKRRBFTAAPWIXBYRGDDLGHXULPTSTOCRIGB', props),
compute('m_18_14/6: ${c} WBUDHANLTHRUWZUZAUXIXUUFOCLRLXSZLVCUJLIKWTZNLVZVHOVMBDFNGGQEDXAQAEWAMESLPSHGPTXZVHHFKDURWFPNKPFVDPNJ', props),
compute('m_18_14/7: ${c} IJEEEESXDSDLOIEELOOCJRVOXEFOJJNSHKWASGCJSXJIOLDKAGJAPUNWTHADRSPQEPAFZTPMXARSQJEFJLFIDFNNAWWCRGYXBCFF', props),
compute('m_18_14/8: ${c} KMKYTRSORZJGPVQUMAONCTZVHLIPNXYNHBVJYTWMDEFTZBYQEFPACJIQOPLQGLWAIYCECCILOBJXQQJWPHDSDOXFPHJMDTWJQIDP', props),
compute('m_18_14/9: ${c} DSVHSFZOZNAIXQONGRQALPEMBNRYDZJZNNAKMNKIREILNYXNLFKNZAFVSFKAQCVZAWGBBHURDACYHCKBOXZYDLOISHPRBCTPXOOC', props),
compute('m_18_14/10: ${c} LNTKAONMLPTKESEDBVGZSQURVTMOTFXLJMSCEOJUMJOCMGSIKARSPFUWCUPOOTAACQIYJYECYKUSRBPFZASBMUTSTGWZMTXUKWKB', props),
compute('m_18_14/11: ${c} ROIKHJWZHSRUTJLYDNAOWNPRJPJXQSIFCWDBMQPEWYPBCTFYAYWVGGACCNUZLYRLRYHVIWHMNRVWGBYBNYSELTGQQYOBMBNXEJFG', props),
compute('m_18_14/12: ${c} GJFVYFFJVDLEFHGMFNLYMNLEMTIGBFTPEGUASKRUHZNABHPOZNHHLOVICTVDXGOPUVJLHYESAXWOFAKDUYMQWSPOMRXLZVMZDQIX', props),
compute('m_18_14/13: ${c} ZQWGHAZTVVICUETOCJDUUFMKKWHRIKCERRETSSUJTNKAMVTBNAIOOMPCMTUPMZVVLZMMGBLSKQLRCEVOMXWTOFADSWAHYHZYSWJI', props),
compute('m_18_14/14: ${c} FEPQIECYPVMRHPTWWGHIKSFYPIRENAHOSREDMHHRELNIKMCZAYOWCDLFVVNJFKHQVEMSQJPTLVZJVZWFZYWXRXUDWUWKPHFFGFXV', props),
compute('m_18_14/15: ${c} MRUGSHMEOSUXTPHYGMFWSPAMQNWIDECPMEKQUVVNIGEILJUGJZLYZZTCWIFELEGNWMRLDTWXVVIONNSAPCFYXBLAAKKHEVZPAWLQ', props)
        ].join('\n');
      }
    