
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_20/1: ${c} KUAGYZIDXNDKJTWMEPNZYUUJAQXUEMHQTNOKMXWAMBJFGIHJAKTVTCOMMFTRBLIULPLCOEYKYCXCONAPLLSAYOBHUXCVTTDBDSWV', props),
compute('m_18_20/2: ${c} EJXMQNFNSSWIFBSKPKWAYWFLIKGWKQMKWKRLBPORWYYXOYAKFHBGGKYGLSYVTKXFITFXEOLCQMQSZNGQPRGQTYEVAWFHLZMYLHXY', props),
compute('m_18_20/3: ${c} XXBTRPMHENTMQJHCGRZKNBWVLUQNAEDJGORFNKRQCZFVFMVPSPUEAZYQKERQILRXXHDYCOFQVUHTLDGZGOECLYHVZCPDAFJVBGVD', props),
compute('m_18_20/4: ${c} QMGEIWIADNNOOKCMSABAPEGYNHJZWYQAYOIAHVFFYTTKHKYRYTUABPVWWCPAKUEBALCGJOOMNMCGHPZKFHIXAQYZIKWOGKEVSHYS', props),
compute('m_18_20/5: ${c} HPTSPKLNOQBRBWSIOUSYOJLIYHEVJPWMARPAULLRMSVZOQPBNGTYBHMAEKIISZKQADOARDLRMIOSTZOPELSHNQQSCRDEPZDZKGSN', props),
compute('m_18_20/6: ${c} PXUVIWVXRWBNJMVSZIGBSUARPOFVJSNSPMEEZWNVEEIKARIJWCWFTHFWOXJFJXHROXYXDFVELLBBOJWXITBNOZWEDQQECQJHSHNI', props),
compute('m_18_20/7: ${c} YXONMFEHIIHYIDGITLKROITWBVFMDTGOAJJPELMYBOSXRQBCNOCOQAFPSDRXLXEAADFFKQFHPFSTIOFYDNNLJUGCZOIWHCJBFAME', props),
compute('m_18_20/8: ${c} SEHHXFCOPAHROMRMYKKKGKNAUEPEIFWPJDFQIFIXOTYCQCHZFORBUYUFGWAHSJAUCIFFYILUGJWGZPHVDMASHAVEWDLZQDTUPIHA', props),
compute('m_18_20/9: ${c} RUBGPFAOZRODRBFVYRZWNFPDIDXDDDRJGTISIHNHQUSWKHBELATVHZTMUVKFNLRKJSAYVQILJQZGDRSPXSTYRKMABVIMGDGFBKAQ', props),
compute('m_18_20/10: ${c} NYFDKAAJASPKUJOANPTIAZEJBUQDQPHJAHXBJBRJTIMVGDBCMIWZXZKSQFGEPVNUDDWGPLETWWNDAYBSHCMSNYXZMLDSKJMYPPBT', props),
compute('m_18_20/11: ${c} UEOBROBGUROCQYWECDFYQABUXODQYCBUBWDBCKVNKPCRUQBWGUQNWWECUGBWFDUCPYBWMMUSICYBLWGEQLJGBGCKWQXIDKWNJQUW', props),
compute('m_18_20/12: ${c} WJFKGYYLQBHEAUPTDWWWELOPWMQBCVKIINLIUVOBPUWHYYVKQCGQPSMYEIQXSWJQKVGDVXRNLXOSHMQAEVENTOBLXLIWGCDQSJCR', props),
compute('m_18_20/13: ${c} MMAJAXDFYVURCINAHBMMAIQYZYPBYANSNDGYKOVAWFXLBHPKOAUJJJZPLLSKZABEOBOUZNTTMXGFLSZEMLEYUGGNUTUANSKRZQXX', props),
compute('m_18_20/14: ${c} DYYEZAXSTHUTOEPXDZBJDFKGBRJUPPEFQQAEJEEHCJCLYXPUVZOZWMXDFWKXWRTAJCBSEXMGMEHEQAYXMCWOSINTCYLDMIJDPHTT', props),
compute('m_18_20/15: ${c} KQPIGUFXVNFUBSPYVQOVNWGMKYRLBHZVWIUYIIDKMFCAGVFLGUPJLJZDTHWHUNJRLMOCTDWJUOOKCPGCDOMDKMIRVRPHKJNKZSBW', props)
        ].join('\n');
      }
    