
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_2/1: ${c} BBHDMXUVRKOSUWZUVACWVQZVRQPZBTLHFNKXZJQKSTBXEMKULQYFPBDUVRBNXBREYKFIJGNCSZHPFUYFOJRGSHKNHVPTBCDBTEEE', props),
compute('m_18_2/2: ${c} ASUYMAOTRTRAQCEEEDOWQQFQPUORGUDKVBGESIQEJEWVUBFXVKKAONUDAFKZMIOBREMFPZOOMBWYPGHSLXVHRRSHKITIDZCXCKLG', props),
compute('m_18_2/3: ${c} TDPDKPRXTTWTSVHGWDIMHIPUKURCJNZEBFUVEVEXBLWGUZHHMAAXGNLKKVOOJBOKYQEQFCONRHCXTNJHXPZICQULLNQHRIZJSRFE', props),
compute('m_18_2/4: ${c} TMJGRJYPNAVPRKZPTNZBBHFDONALJTXYKTISYQZEOWXUYCJFFTFNCDYPPZKMNHFPFGUTYVEHATOWIEDMDWKTWIZRZYQGICBISODG', props),
compute('m_18_2/5: ${c} ULPCGDMMEASGGRXHGBWAFDQCTDUXSPQQHSUDCGNPHZPWGNRJWCOHFCQSIOHYJMIRHNTRGPROIKGHIXSIQESNPBZFMMNNVKLNNROI', props),
compute('m_18_2/6: ${c} RADLPWZYSRXWAWEWYREAMECYLWTLHOVBTKUCJKRSHPLLYDLRAVFDENHKKMYJEXBGVPROTCBXEYSYSAAEGCGBXODPCBKJAKONHWPC', props),
compute('m_18_2/7: ${c} EETJXFYXODGJWCFUACVNMDJXRDAQLYUSFQTRXKCBCRWFBXMXBAYQQGGDYABLHOLMKKAUVDHJELXFBQSDEMUJPWIENXANMOFTBDSE', props),
compute('m_18_2/8: ${c} HUMBUCLKSABEIOXSCKUCKWIRTCWACCQAOWEDWZLAIBFWAUNTJVRNFCZPHWKNXHYKUSYULBSUIWZEDHMGBKYEVNFTXMAXFNPEFFVW', props),
compute('m_18_2/9: ${c} BNFTDUIEENVRAAGFXHXGEHKWTPBQMHLMYMFNUSVLGFRRRWZQYRUUVBCBWLMSXUDKLBBCRNXMBMPUQOLZPAWSFFANLQQKXPHIFHBL', props),
compute('m_18_2/10: ${c} YTLCIPCQQQSJIHJKQFJOWPZTLNGWRCRPDOIFMBSJXDHLAXRBQHQFJEAHGYCCFCASNZKLJSVBEGJFZLAJFDPOLAQLVJYFDQRSISEJ', props),
compute('m_18_2/11: ${c} AIVMOFSBFSXUGKAHCKAPZQGKNIQQCXVIGLLSZKRBUZKNOWAJITTVFJKSGBTWVHJYFEGPBSCAZXROXJBNNQQSCVSJAZLUXVXQFWDZ', props),
compute('m_18_2/12: ${c} JTGMAFUBEJXKJFEBHLBZQLRQYXSPMWJHNMFHAIGWZPAOPZUYWNDBIUOYFWWWTYMFRYPZTOVPBCJTOKHDTXYEZYGWKVJPCEKFMZHH', props),
compute('m_18_2/13: ${c} NXRHOGBCXMLCDJCBFORKAUFUTIYDHSRYJRCHMDATVHBDJYGPUZDQZLBXYOQLEQCYGHXZJYOVEOGNJTXGWQEBCGBRYHSXYIQORNYW', props),
compute('m_18_2/14: ${c} RMHJMQBCBEBGHCOHHEENVLDTCAXPMOCCLJZMCRRTNKPLJRLUINUIHEHTLPXGQFRSLTURVAAXSGZUIDOTADHADIZLKOKOWOZCHKEZ', props),
compute('m_18_2/15: ${c} JQXATJKNBKKHCUGFYLDFMRUHSMGAUSLMVTPBBEHJUFCRZGTXTJXGDYLCSIYACTTJOZXNWUMCUXYZGSRFUROGJYVTHIWROFWAJOOU', props)
        ].join('\n');
      }
    