
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_15/1: ${c} IYAEDSYDCUXMSISAUMVUKMCFLQDKSDVHBSUIUJMCBWKPDCSJYFCSHSISHQILUCTKUPRAHBUCDGIOMYNTCKOVBSNMHOXTERYITKLG', props),
compute('m_18_15/2: ${c} SBZVHPYQQRPPTTWKCVUYZIYWHNTEUFFAHJDEHNZOPFMHEXKYLDHNKLWNNTFXPWNXIZLGVYERLXNCJVNGFVUNVJEDEFXHGEBXFQTN', props),
compute('m_18_15/3: ${c} UDATQPZRGUEMYBQREXIXRDVHOHMQDSLNBXPKODZBTFPIPARYLQGDNMFFSOCXKGPGSVQDFBZMZKHJALUZOTSXUZSYQKKEVUUAYKVV', props),
compute('m_18_15/4: ${c} KZOAZIOJEPXJOKZCWOHZPQHHGIESVLBODIMQKABJNRCVLFYHCHMPIVSZITLRKDFZKGZLTVUWAQMFCPMENTZVCKUUIETFBEBJCCQS', props),
compute('m_18_15/5: ${c} PSKQAVLLGYLBIFKJPNLHAGEUKGBAILYGDUMXVWOSKPMVKIXOPLYKXTADAYCYIUUXLRUOBDATGYBJLFLFZZBXPBSYVQDLXDWTMWPM', props),
compute('m_18_15/6: ${c} NYXEOJNCRNUEZQNKIXBELIYJEXAKWOYDLBGVNFRBKDHUYGOWPUVKRMMTVZIRUXFLAXTMPSXFGQHPGKZABVYQOVJMZFJSJNYSNKDV', props),
compute('m_18_15/7: ${c} BZQPPHOFBGRTRELNZRGNTJWFGMXLAITVNYRIBYVGPFEVRJRPEWZQPRNZOLFIREHHSDOZNUAJVXLFPEEZDKBFZULFKFJSWJZELJBI', props),
compute('m_18_15/8: ${c} VEOMEKFJJEYAAIZYKOZQMIUPMRSTXSYMKKKTQZKYVFXFJOVNDKYKPXLIKNAPBIQSTUVTPUAQJIUZKRRNYTORMIHVDGGPFIDAYPDT', props),
compute('m_18_15/9: ${c} ZYWLHUOUDYHZBRWJGIGILJWTDPEONNVQNEPCIFAZWXZJBZJOZLJOGVKNLCJKHSCKWFLKCNCJXUIFQWQQVZBFDRQYJKELSCVUBKFG', props),
compute('m_18_15/10: ${c} PZMTSPJQZZFJIPTEYHFGDPRKVCGIINBFDRGMJUKOOLXGPENRGMFODWUAKVVPWGDAQMINPZIOQUNOJKAPPAUKBFLFMMQSOHTGVOBM', props),
compute('m_18_15/11: ${c} OZKDOFBJXJLSADFJHCSMFYOCWCXNDLKGWHNNXRZNGQNUYAKESEHFAYFOXNFUSFHIHTOQIORYXYRHZHGFOUFGNIWMCOHBOCPEWJEY', props),
compute('m_18_15/12: ${c} CODCHOVUYOSCKCTWRBJHQUXBWXQXQXUSDVBJYXEWHZIAROONKUJWSPRSUNVBFDZDIGCQYSBMIBBQANBUVWSMGNWBCLUZHEJUDPSS', props),
compute('m_18_15/13: ${c} ZZBDBZOWYBXXPLINXJJOJFZKYZXHKJAQMDLGGNBKLVEKMIAILCWPVVWHIRDFCJTXOKCZEEFRJEXNHCYRSAKCMMRUJJSSVSJCBHWQ', props),
compute('m_18_15/14: ${c} RHBGQEVAKAOAKKPKGLPYVQTDRGUQFDCVIRJUNMPPTMOOZSRARLDNSQPYXWGWLCOSMCCMEHWFUZJNLGWTZRLAFVWQCZUNRKUHFXRA', props),
compute('m_18_15/15: ${c} GJDRPKQBEVXMLWPFSYRUOOLVHKXPUBCRKQYKATSIKFTMROAQHPENJJARHPWHEIXOCHPJZSPRWEYXWUTDISXXUPNVFHAMYEHJBGYM', props)
        ].join('\n');
      }
    