
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_8/1: ${c} DCEXKYMPZALHFMEAGVPDXPEFGSYFXWVCLNVEMSSXRQOOCOSMHLBSOMDERFFMAXWTXAZZZPXXRXCVDCGFPQAKSBRVBTOFFFQVWWFJ', props),
compute('m_18_8/2: ${c} UDYGVJINERAAPQBJQBRSCNPIAEQFPQHKOULFVOIIDNYRRVXIMLNOTQKGGXQMXUNONEUFLHEAYKGQDFOQCECHCJSIJQXHYOMNUKEG', props),
compute('m_18_8/3: ${c} XTLVITPNBFVQLDSECSZROJPIDRGIPADEZIBJNRUDANFOPIKDISYLRQPFAZFJQQUUNSIVOHVYBTDZFPKDKDMPSUYGLVMCQLWFELPC', props),
compute('m_18_8/4: ${c} IQJTPEKLFIDBHXKLOEZTNLXLWKSJXKLSWKFNHZCONLJUPLEPCQFQLHHRZEZBXLZWDRRSLSVUKYMQXFZLOSAHFCLJMDDMPXNIZHFY', props),
compute('m_18_8/5: ${c} OWCJMJPBJTSURHUBGKKGONYDHWWOVLRXNOVNNZKAAYCZPRQFJERYVPITYVUIYNUSNIESHQZQTFRSGZQJWTHQTONADCJTQPXVHNPT', props),
compute('m_18_8/6: ${c} OMTZNFZTDFMRNRXOQVPNNPDBOICQPYOWVGQDSOPLVSJTJGAKZHVRQNKPAZNLYGGGZYSQMLMJYQWOYPYXMGZFLMOWHGOHTJJUYGIL', props),
compute('m_18_8/7: ${c} CWWZCLDMZKAMTLYETHXXNXLGDVEIOYGTMVSUXJKXZYCGRIBXSNAGZLVBQSNWWFIEWAGADWYZZCQEDCOFWGABNKZIJKSSWJTICEJS', props),
compute('m_18_8/8: ${c} LDPYIZGWAGKKJBUZXSAUQJEEPTBZTGUESPBZUNDYTSPPJDUCLMLDFOEAWMNWCVVUPEVDBIFUORACWAZQSALYRECQYCPSMDVXORTS', props),
compute('m_18_8/9: ${c} RXWNGOFTFJZTMRMNFVUGFFTCURFKVKTBQLJVUODKZAWCSWXNPQRGTMNHKBTRNUCWOKETQQLPGEOCEIPUWMRXFGXDZOGLYXYBGLFI', props),
compute('m_18_8/10: ${c} KBGEGLPXWRKTQNRVJESAEBYZOJXVYCULUFWXCTORDKLPVCUATDMYCRWNYFFLSCIKBCVWXFYOXJBXAYUNFMVPQCJXMJPTCODPLMBH', props),
compute('m_18_8/11: ${c} CATNKXHPBCFTWMEHGHCVAUBEKNMVLQHRAILTMEDEBYFWWYYIBXCEIDWUHUFIJSZEDETEPDWNBVPDIPYSZLFLYZRVLANTTVXJSOPQ', props),
compute('m_18_8/12: ${c} EXMSKJKGGUMWTXLBNAHJYKNIWYJCUYFAJXQCYCQTUFLSMZSMIUFZDAYKZLDBMRUHCEQEQUMGSJNFDVIRGGHFTCFOZXQGIUSAYUXG', props),
compute('m_18_8/13: ${c} LZEUFAMQZHIRAESCLELCNIOUVFBUHGJJBBPHJHWFDHUFMFSMRRNLYITARKLNJQVQLXQGUQKLPLELRMTAYFREHMJSNJNWVKSRDEIQ', props),
compute('m_18_8/14: ${c} FBZSHQXDHUSECTEWPIXGCYDIUMVIGISTOLVPAFDQTCYIFJKVCDCSVFJATFPHVHYJKTJWRISZTJNJVOZMVAHBVUVESWCDHBIQRRTE', props),
compute('m_18_8/15: ${c} TQJWBEVQJTUBKWNORJPBSMJTTOSVIGJTAJESZZXRVSYEQFZCTYRBNCHSKGKTWVTPISBCNIYPWBONZAPJQUQQLKJQQSTSJTTZGROR', props)
        ].join('\n');
      }
    