
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_10/1: ${c} KMUJZWFYBGGVYYCZHKFRZZZTFXJEVFYGCEGUHCCPNNARBOGMJQOUVUUNXLRORODWNBPKEMPQGDFFZBHQHOPWEYJFEICRDNMKQZOX', props),
compute('m_18_10/2: ${c} YSMKHUKYEDNYEOZTFWEJHSMMFROCVPABPOXQSBQGCAXUWHQFRMTBTBQXZBCLUPZPTGPLNTQIZJMBQRUFVCGEEXPFWRHEYHRNGFBC', props),
compute('m_18_10/3: ${c} MFAYLEYQEEMVDINFAKAVSSXNNMDEXUIUMIHIYPDIJTJCJUDRXWFWGJLYQBEZRANDWMDPXHTYXCFBCIEIOSSXGWQONZBCYLCXKRYZ', props),
compute('m_18_10/4: ${c} PGCSWODPVVYCFYOZZWEOSGJFAJTVOWDZVYHRGKDEVEODGJGLBQGLLEQRSLVEDITOXIXKNEQZOQXJJDCAFZEPYWMODXJEKVAOLJNF', props),
compute('m_18_10/5: ${c} FKKLLYBBJOEGFKHPGNMCUWATRAHJWSNRTRGHDDMGJLXVSZJTBGZAZAKHDSOOEJKBVKLTZCBXLIVXAYIHYEBRXKPIQNTQEPKVAKVY', props),
compute('m_18_10/6: ${c} HWUYDMRCZYGXHVWMUNXKLBBDSQDGLCXRTLHEYLAUKWIQVPEAFMFUHWBVGXCXJYHYGFTJFMTBBCOGWNQMGPCODLOXKWSHZUMZVKIH', props),
compute('m_18_10/7: ${c} TNVQZZKHPPUPAJSTQHYZTEKVEXIGLYPAJRCOJCNWJERVWAXWVYUDWJMMPTUJXCUNGYHLUVVFFJWKVZGARVVVTQNJAZKVBHPIWOYL', props),
compute('m_18_10/8: ${c} FVJRFKGNHBHYMMQITHNUFHJXCQLJGZIUSRCMWGWHIDPXSKKRHKNEULZTUFLOVJIOAQLJGJIOMAVBWSKSVFCDATNBYBXLWVTOHNMU', props),
compute('m_18_10/9: ${c} TJWJDZGJTFSRTDGPYXJNPQMYVECDBNVKEZRBZTMVHSWFSWVTKWLUWCACZCBSEKJSLGPDUHUDDJGUKYZQRLZBLESOZPGANITRCFSY', props),
compute('m_18_10/10: ${c} YJFMIRKFBVTQOFOQJGTDAEZGPONAKWHLFLJTJOOYMOYZXODAVNDQGYBZXFKHHJGIRVJLRLYIIZMBYMRJRLWIBOJBRUPVBKMTTJWM', props),
compute('m_18_10/11: ${c} GWTASOHDDNRQRXOPCYNEVZXQUIEPAXAURIAYWKHZSKLVTPDDTFJWWOIRCATVGOMNHDKWBOBQKBAEUMNGQGVTIOBSNNPYRJGPTTVW', props),
compute('m_18_10/12: ${c} PGTWAJTVCWIPDRXPYLUHXENDPHARHKIDMTKLSERRQNFYPNWZVFDKEZAAPRXWNKRNLXUQRJTPCKKBZPHWQGZWHLNRWRGCSYICMMFA', props),
compute('m_18_10/13: ${c} BRKYJZWQUWJCRHMMNXQKTLDTFJIZZJNAVJDMTYARYKWTJZWLZCGBYDRMDOYPAZYBZYOTNEWVZAYCPMPPNLCHHIBBTLXXEYMJEGZK', props),
compute('m_18_10/14: ${c} XCXAIAETDCITRHWVDJECMCZZRFOHVEIGZKKRYJITOUSMEAJIWKEHOJCACKYPJJJMMQRVUVVMEDZBJDIBZFXDFOCFFQBFPMAYUILS', props),
compute('m_18_10/15: ${c} DAYUXUAAPTVUWFRLIRDAGJWVXMNZFLCZUFOBIPQJVQXLDMCUTAHMYSTUHTLCJZPSHFUQTAADJDZZVOLEGTOQLAUCAUOFCKCLAPHM', props)
        ].join('\n');
      }
    