
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_9/1: ${c} TEXCLCMIAVMGXNQJQYNWHXHXXNTACZIZDYUDYOPGDTFHQVZVUSOUNIHCTIZRFERBAGJJPPXWNMZBYLSLPVGWSQYYKRWBZIJVKPVZ', props),
compute('m_18_9/2: ${c} HFVTOXAJFKUKIJCJJBFGWVMOKWOLDPXOBJCQBUQYEMPEGVMDYIHYHYARBIYHZAQSSULQXVDSFLDSFENPUMSUJWXIKWPMXCKILWQY', props),
compute('m_18_9/3: ${c} EYBQRSZBEOAYEZWDNGFMFOTSBBEMLVUQLRBRJVMPPSVPPRWOFSMWVPJFJPCTXXYXRRKKDNGCDZGCIFLCBCGUTYOSTRWSFRVUZLER', props),
compute('m_18_9/4: ${c} ECRCDOAAOMAXIEVORGSQQVQZQLDDMQUBPIAZRFJOLHDOJKTAJLBBECBDZHWRKAKCCXJKYLAUAMIDYODABVNTELLSRVWWORTQGLSN', props),
compute('m_18_9/5: ${c} HCRPPXFGMZJTELYOGTURWZHSUDSFNLBUAWCKWUMJIWWJLJCBRWPRFBCFDHAHQVLWRDRJGJPQSJYXOIDHBTEXXPLEXTNZXNPBKONZ', props),
compute('m_18_9/6: ${c} RKJDNDVUWUXXYFNZQTAPKBBJDAYVZISKVFFWNMCIWMUTFEJOCNWOYKONOJMBUNOITACNJCOGTASAINJOUSYQNSZSTOVFEFYWOOCF', props),
compute('m_18_9/7: ${c} MCEIPCHHCZJKDJQDBDARJADOKXFNKICFFWYCIWCEVAEGNSMYZQJBGATENJCBHHPIXGBHZWFUYTZXMEFIRZBBVGFNMNMGZGHDIBWH', props),
compute('m_18_9/8: ${c} SXQZBZRQFUXQXREPDYFFKGORRNMVRNHDFMQXFAQUTFZFWALNQZCMDNDSBKTNEAUOYXOFZGGVSRUVPFNVFMAVEPOXIFLQGFVVSVIN', props),
compute('m_18_9/9: ${c} UEZPIIDJBCGWRHSLUCRGRRGDNJPLHWRYEUHYMILZVTJIXJMWEPNEXXVPMBLJBTTCDKJSSEGQNECRAPLBQUMSVKKQWALGIOVVNPVY', props),
compute('m_18_9/10: ${c} ZLGKYACGFRLJYTKNXNYYBDYZQRHSSPKPFCOAAOJSXNTLODWLJMCAIYHYLRVCLZGVYEKABBJBPSIOHCUGAVCYSFLMFPCJFOEHQDBC', props),
compute('m_18_9/11: ${c} SFBCOHNQZOFJRGFVLWJIJFROVBFFNNDEIJBJUYIRBIJEYBCNFISXPCKPDTCQJXYNICUFMFECQIBKIYLONQLXNDKQYABYPZMJIRXO', props),
compute('m_18_9/12: ${c} UDORZOLQXGSBERWIHOTVGSMJWELCOELKSCUTIEWEDCXBFTYTEFEGYJVXEQGFPCZIKRDQKYGLQBBGSDIOLVPXLMWZFRTMTIXCRMDU', props),
compute('m_18_9/13: ${c} FZFYCWVYBUZNIMVWOSNDCSGAZAUSRSNTVIQGDMKMWJDDOEVKGDBMOOVLJEXHRHRYCCLOGLJGXPFLTEPLKPFZUKZZRVLDNPJAOAXO', props),
compute('m_18_9/14: ${c} MJVTGJKTUTUAQDAXNBFCZFRMRMAISZNAUACRFYSWXPNTWPXIXLPHWJZRNOXLGITYFYKAWPYUSQYJVSNIRYIJGIMIKHPXMVTNFWVH', props),
compute('m_18_9/15: ${c} NVTWBOIYNVTZTACNVVGCRTXHGAYAUETGUAAJOAMCGMZWQJRPOGVDONOATVMSSAKKPWNCYDYYKTXZIFCDYLNHROTRIUIPFWNLXXWC', props)
        ].join('\n');
      }
    