
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_5/1: ${c} ZPCIMVIRHPMJADFBULYBHQXTGTUCDYDDXRAMPOHECLIRSGFYBQMZQUSRIXJEFXDVJSZFVMBVVPUMJIWSKJWFCJCHIJMOXVLHDANK', props),
compute('m_18_5/2: ${c} WEMEWOEMCMAEIWHKFTQQRRSJIRYISCUATPGRWRIFBZXFXDTJFQPAEKMAVNLZMDRKJSOFBRYCFBLTWZULMNYIUVYGYSBMPGFTPGKF', props),
compute('m_18_5/3: ${c} QSIKJBDUFIYIZLIACGWXEBEGBKFEJIRDPTDEUKJXBXIKWYNOHXNUGBSEAGBXENBCGINUYMVJFIWWTTXSYQKCWDEADBZPTTSFMZQT', props),
compute('m_18_5/4: ${c} RJTZPONWLSITINGYTGILMKYHBWZQFMOJOOBATFFSBRFKVGYNJELVHQANNXBGWEOYQFQLLHVXISTNMTYEYFVFMJIVROBECJQZCHIJ', props),
compute('m_18_5/5: ${c} XURNVUROHJNDXXKGZREQDNJZVZVPDIUFLAGPUQDIDHLLBTASMHGPWIDPLVGGOXNDBURPLUJKNCOPLEDAABRDIXFMIZTLRPYQJNGP', props),
compute('m_18_5/6: ${c} FEZFUNDANDMMAZWDSCHRLOUZANOIRRJWAZTYNRVLKPGPLANQVTEOWKEJCUOMMZRKJVZSPLZAJRTDWCVPXEYORKJCRWZJKAQVYJVQ', props),
compute('m_18_5/7: ${c} PXAVCNUXYJGXPQIWGDQFFCKDAHBVNQAMNXKMDLAQIOKQYNZZMCDHKMHNGIESRYSOGWOGUXAWPPXXWQRQBVYQLUVMTARRNFAIODDD', props),
compute('m_18_5/8: ${c} PIXQWZIBGADGBHDPTZZBGPLIKEGBLKFVLYBCNNDSTHZFBESFHRUTORZEFDXAICCNNDFYIJGARUBCNISIRSJKNCZREYQSIGIIOEGW', props),
compute('m_18_5/9: ${c} VVTFTNWPUYLKBSXHKIVUQKFIFIZEAZRWLYGOZJRAWRCBYAWLGVFCFETKURKFEEUYPIYGQUEWXMRQOFWRLVGVCNYFYRIQOAEJAJHI', props),
compute('m_18_5/10: ${c} YSMFAWOQKIABWVUWMVOUTIFTBRCATQKRPLYPHBQIERJFHHFRCSHXXHEBZCAJWWJYIEFNFMHHLJZJWMHQCWADAYLHBLEPNBJCPEFC', props),
compute('m_18_5/11: ${c} JOPNIPPGVMMVTCQVGWUXBFQZQFJVCQWUVECJWHRJCBYXMFKHNQTYYCYHPDCYVNRYNBBRBEYSEXFYKDZSEXMQWWQXSXBCAQPSOJKW', props),
compute('m_18_5/12: ${c} GAZFIKWDXPERUAFXTZDNJTXOJKZUVBAQVYTGQEBDHNXAYMQRVZYHSYFAJGTITOUWYEJAWPEUMXFRXHQOHCCPGAGVOYTZFKDWIXMY', props),
compute('m_18_5/13: ${c} INUOOBQYURBQMXUBDMGWYGDBOLQSIGADNHHTUMSRILITMMDQAFYJKHHNUHWXIKPJKOPFXRSPDKXAIVTXTDHONKBRHVGSFPZKAZZE', props),
compute('m_18_5/14: ${c} WMFDQFAIDXRXESXPWNUJQXSECXIMLPQSVYAXGEXOUVQHFLDDZWOKHAEDMQKHGUKGRYGXJLWRVFWIKXSMQSAPMSZHNDCYCSFUYIHK', props),
compute('m_18_5/15: ${c} MHOMFDELRSWVMUVKOJOFDQMINHYLSDVUSHDQUIQEKWIPYKCFJEVNVVVFTHNABMIZFLGIXBNHAMRUXRGDVEJEIERLXFYBDIIPLSLH', props)
        ].join('\n');
      }
    