
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_6/1: ${c} IFHUCMSFUWGHCBUHPPKHMEMCOMTBFDELMJMZDUBPYLADFIBBLYMEJOKXZYRHBPYCYNMCRBHVFQPBMLKTPJRFKEKQUDSOEMURVYEW', props),
compute('m_18_6/2: ${c} FZEDRUGBGVOGEBMGTGPFKGCAPZVRVKOTBHCTMKPHQHYQBPVLOPVTNQMVVWMHSRQSVUMZAXJYQPSVVTNSABHFERKBMTPXLLDGJSAR', props),
compute('m_18_6/3: ${c} TRNQMKFFSJTJOAMMHNIPUECNLLMNYFOZSQWEKRUGKIGCUHVWFRFXJGTJTCYAZIDQFRWYAUZZZNKMWUBAZQTCCAHPTCKWVQKJFYMB', props),
compute('m_18_6/4: ${c} MKOJVOJJBXLTSPLDBZXOUDAASEOAFBKNVHDZSBLGGMVMOHDHRGNHNAYVMRONTFPYBBAXYSMJTWQYDKWLHTBBOHYXHVXVJMLZJZVO', props),
compute('m_18_6/5: ${c} UAIPRARWTRNUTJMLMYHTOAGVGSDUEODUSMEFFCZYMUNMXFLXWBYWBZHQJQAGVFQUJPRVIJIHDXAJGWYVRKPWQETABTNRISCGDPPV', props),
compute('m_18_6/6: ${c} CIZBEVJUVUCQVCJNNSIESDMCEJASTGQTRMRLGHDSESTSBMQGVJLDVYEKYVEMGGVWJTGXIDEQSZGKLVCMQRPKTPKGUKSYRMHKFAHT', props),
compute('m_18_6/7: ${c} VSNBIYBGNCNRZZNKWXQIIIOROEBMVDDQRHEAIFBQPLLAIGUUFRTSQMBMBKVUFKWAYZHPJCVWUCFPQTIGVOQVDJWTQYMJDGHVYTML', props),
compute('m_18_6/8: ${c} FEZXYUKFBREDRJQFQFLJLKATXJHKQIVAHFZFTGKUBRYFGDIPTAOISBTWEKYVRCROPGDQWIWBLIXJVSYEZWALENKLRFPHLRMRTMVC', props),
compute('m_18_6/9: ${c} RSVIZPZCNINCKJCQJQIMAXUZPWSVKMWQXOTFAUIFVRWHPEGWEIKUHPHRVUYXIOUWMZYJMEPNHPLDKRQZHSZQULRYBWNHVIAGJYSP', props),
compute('m_18_6/10: ${c} TUJBQBBXDVKHRXMJEDWNDPFWLYPJMBAUWKPGBMFHKMSWMWEFRQJPGJABBLEQAJBQZJOKNUTHXRVIONHVEXTAOIOLFREILQNVFAUE', props),
compute('m_18_6/11: ${c} QZGPYZXBZVBZPQYCRQFSJLBJWSQLUPNHXLETYGLIDCAFEJMYVAXLHXKYFQWKEQCNVYIXVKLLSJIXOFJHSYFCFGCBBMIYMAFBHMUB', props),
compute('m_18_6/12: ${c} KLBGSHSRWDBYSCMTIEVSZXDIJDJPQWCIRGYHSTPYAMVDPUGHIGVSQFKCNSVYMCDLPFAXAWBDNWGIGOAPXNMKXJNDGDDSOQUXXCGS', props),
compute('m_18_6/13: ${c} DWOPUHJQMXEWZODYCHETWYQVBLNIPYHJVEOQSXBEYUJAAUHWSURYOXTWHIGRZHEGLKKXSPSPXZOUCBNTISCZKJGPDFSSCPCGHVOF', props),
compute('m_18_6/14: ${c} GSTXNZYNLYJEYHWNNWICBEZCMRYMFTJSPADOMUCTTIYFACUQHGKBAWQBVVWJMFBLJESQKMQSSAWRHFBTPLGPZSJFGECYLQJSETEF', props),
compute('m_18_6/15: ${c} NKWNLYMCSSCGONKADOPUWZSUHHICWBLWCBSVBMHESRXZPUHPSXXJDSJFBTURCGNWCHEZDRTYBXEYKCMVRNDJACPKOLQTYSWEUBRH', props)
        ].join('\n');
      }
    