
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_17/1: ${c} EJSVYGCQOUNWXXNMPYSMIGZUKJQCQFHFWFMFUNFCZOQFYDPBNDUDYKZLISWHRXKPTJSAVGTZSATUSUTVQUKBBLODUNKXVCDLCKJY', props),
compute('m_18_17/2: ${c} KAQHQRNYYKGTFTRLMAUUDBFDBDHCSLIKRZLWRIMTOICCCOCAZTGXBBUMUUHDJAOSKEYEQNGHSKQRUMBEBFAOUFKRVZECJSZVJAFK', props),
compute('m_18_17/3: ${c} NRRXZTJPWXRKIRYWZHPXIKMALKGHVTZQDUUMHDVDKCOUHCBHEYXBPMMSHDYPRXFCGZUTMWMXFPDNOVTOUSZHIKXKPDXUFPMVNDUX', props),
compute('m_18_17/4: ${c} IPCIQYYBGQJIJGEETPHAAQYWLBMKDOKJGVYRJBZJQMCDRITFPCLKWSUVDZMRGHRSQPFRZIZTGOHDEBUBGPUHOCBWFWQPWQZIOCSJ', props),
compute('m_18_17/5: ${c} IXMHBBCZQRBJPPMNPAIFEVDRSUCCBOWCAUFOVCFVYZQUJEWUANTGKRXRUPSPVQYRNOQXTHYKHHYJWLUNTPDYSEQUEYZLCGQUPMMG', props),
compute('m_18_17/6: ${c} IOMEYJGQWGZAAZJBYRUUETOMHOCGWEPVAAHBMIHFBJYAAYRJSDAMBOUHVNKCSHRIVFARAAEAPWZGKHZNGYFHNQBOIEGFQNJJJWXN', props),
compute('m_18_17/7: ${c} RFQWNMSYFAZXFZLTDRTGQTWNTANEDHDXDAULKDYEJRDLVBZYXOHCFBONFIQUPKZZDRHYQVAVMQHZVFWWFTARBNDPTEZCWOLNPNBL', props),
compute('m_18_17/8: ${c} HYIVEEFCMMBOUBTIQIPFJPREIKXYDQVALGTODDAXQLLOGTGZNMHBUTZVGQOOUCZEOWATVRDEHWCTDOTTISMLLERBVBVNQWZGIBDP', props),
compute('m_18_17/9: ${c} SGOLNFXAMMBTQXCQYBKNFRLHEKGJDPOSWVTLLRJZUXCATXAELAYKUCTNKSPFSEAKJGDKKKNWFHDAGUCMZZAVETOOBFPUJDKNLSFB', props),
compute('m_18_17/10: ${c} ELYOFXEFBMDPCREXGQFIYADEVRDKRWJNCQDTGONLMEENBHHZXZBMFCQDSOKZWGZRDNTLVXKXBJARRNXMYBBWZUOIPLJPADXSVGVQ', props),
compute('m_18_17/11: ${c} HLYHZFFAVGVLVIAJRKSKQKGSXICKCCFQSLZRVCGHRUBBTMFUOODNHCXDDXQWHRCMFHMVBKXIABLDCNHZQVVJNJDSOEYCHSMKWKQE', props),
compute('m_18_17/12: ${c} OYJTLBCTDFAATXDANLCQOQQJNGFXNLXMCTZVNYFJTXAFWHKNSASIYOPZTVCARIHNPKXNHTXZGREIEVEVUROZVWOFJZLOHZJECPEE', props),
compute('m_18_17/13: ${c} STVGRFNFDQZEBFSPVYAQTIAULEMJEXSTLKOKGEIAJYFPCLCQNDDLRPBKSURGCJJBWLPAIPBMHZEZNKKSXNBEDZBUMUCYYRQXYVKX', props),
compute('m_18_17/14: ${c} QNXAKYNQEKUNPLQOAJRSOHQRKSNOYYHXIIVTXYHRSJZRDZXERATQRZZUWBHZLTWUULWFEJJRBQNNOUSOPJFWTWSQFDKGJNWICRCF', props),
compute('m_18_17/15: ${c} ZEDYLIVCRVKYQLHWYKNEVNYVBXVVJLFJDNVQOZMPOEDDNWDCIJAPWDDFFQGXATSACYQDVHYIFYARRMZKMAIZNXZPWTYKKMLNQKZE', props)
        ].join('\n');
      }
    