
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_1/1: ${c} BQSUTNTDLLOZDKKPJRZVUNOUZIBPGUETYPQTICSBBKNLUQYWQNCJRNDXDIDMCPLAYJEXKJRUTRIKELDGXDJZHOFARPTBEJDOUNAZ', props),
compute('m_18_1/2: ${c} PMUZQHKSKVCFQCVPJZBEVKRQAAPSXPRNKJKSQIWKPABIVTBLMHIBAPATMYGRWNAJTLNLALWJZOLETIIKXLPUQLXIQRMWYFNDUNFG', props),
compute('m_18_1/3: ${c} UYKOQRDKLBQMEHQASMDSXTJPVPKGBNSABFSDMEDPOPCGEDVVAGEPOGDYERBIKLGFTVIYUSFOZLIWMABMLWMBIZVWHIXNFBVEWIWW', props),
compute('m_18_1/4: ${c} CDEDFJJNFMGSURIKPPBSQLJJJFNMFCZBRZUKIDGUSBZWEEQTBWLCJGSEZXWSHOLWNNGTQMBZHBZGSFKSHLZLOLWUESAOQWVZMAST', props),
compute('m_18_1/5: ${c} IVWPYRHARXMZIYNFIIWWFVUUNPTFPWDHWGWPHIZRWZLWXATEWGCWOIAHJTDSWCXFYHBSZJIDKZKPMXVHUMFTHAIFUNXQLWYMJORB', props),
compute('m_18_1/6: ${c} TWIYUARICBTKDOXDTVZICUVOGTPNWAHYWJSKHSPAEIDFGOWNOXJLDWWCXTTOKASIYPCXMDLUMUAYKUKGOJYBCWRZGGATSBAZITMQ', props),
compute('m_18_1/7: ${c} KHJXYRYKBMRHZLQDTTYUTEUAHOLOIYTEAPFDPYFXKQDSOGSHXTIEECODAWSMYUXCGDVHCGNIUVDABHKHJUNXSEFYZGSRBEUCRVSJ', props),
compute('m_18_1/8: ${c} UQDKHUAVANCYUSRVCPGXMXMDKEVRWULTHPHBVLXNGZRXGWYPWELEUYIHQIWSCNGCPNZMUNMHCKXFSJVTNEESIEUGUCIURVIPTNKM', props),
compute('m_18_1/9: ${c} JDXFNEPFYXPMVMRKHXXRRKABXYKLOEOHESWHWEOAUZVWQBXFHLRRIRCGXEVQZKMLFBRCZNCFGZIUZBISVAOWNVRUQSCHFGXQQDHB', props),
compute('m_18_1/10: ${c} XNFKWPQTATAQGBSDHPYCJIEPTVFDUEFCDRXYBNDEZXHACWVPYOZQARYQXWZWJKKQXVDIOAJVLVKVXVEZDUWKGNQEJNLTCXSTBZHH', props),
compute('m_18_1/11: ${c} QABGFTWUDNALCITBKIBTTUCNVGTUNUODHNDAYECWMASEDEPDZBBRCEDYHIMUOOPLVVVECPSYXQOKSLPBPXEZNDIQOMJCMDHOAJFM', props),
compute('m_18_1/12: ${c} SIOCFRUDOSIKRXJGAFUNORXTXBAYWHSOHAQRREQUVDZDOXCYSLEVPHASEVBJCDWTBCVEIKTKKWITEUCEPYZVUZZFFVVHTCJPUAZE', props),
compute('m_18_1/13: ${c} YBDZSJEADMOMTQMORFOAIVYAVZZWTGCTTWGRHTBHDBALNTQQHKQEMAJHXTQUDSPWEMLSBOTXDWQNKQFQURGYRFTYQZRRZGSBJUUG', props),
compute('m_18_1/14: ${c} ZWVBUOQCSWFCVOXBQAXTFIJUUZIENLICOHSRJFGNGDVJWBOYDCZNHITUOVORKGTMCHTSJVODHHCOKXCTEWHUIDPAHBZDAZIEVHAB', props),
compute('m_18_1/15: ${c} YNSZLIADPXOZHHTDTCYPVDCMSQATORKSAAAPVTGZTQNVRWTLBUOFKRPRAVWCJBFRLLJKQPMRZTVXTTDTRKFEBPRAGIAURQISQDUT', props)
        ].join('\n');
      }
    