
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_18_11/1: ${c} CDGBDJKDOMGSASMOFXBGTBWCQOGGMVMLPACMMDOULUYIZYPSFDWGZPHHPONTAIPZGPSLUTUCFPPCQOJSSGPZSELKHQDNZYETNBCW', props),
compute('m_18_11/2: ${c} JWJXCQZGZMKZNGNCAVZWYEGPRPPFZTMJIQNSQUQEXAVRLWKCKPGUHANBUIEORTLAZHMDTYPDMGRECPHFGNZJSKFXSGBIFSHWTGJL', props),
compute('m_18_11/3: ${c} CLAZCNXHTIRDZGXZYPHKFHQCMANDNWKPDAVUJVEFYBIUCPSDEUIWTPMWGCZNKUVCYQCVIJOGDZUQKOJJVRZSYTGKSEOJBYTZWIDQ', props),
compute('m_18_11/4: ${c} MRAEHEFPTSIZOFXAAXJUZZVSOISPOPIJVNZVLAPFWXDPBGDKLLLYPWCVFPHQYRQSGRDLUYYGJPCMKTBJIPZYJDDULBJZKPSFURQK', props),
compute('m_18_11/5: ${c} XYDYBCFYEFDZLFWQTEBFKSAOTOJUTLFFEZKXUWEIZKIHXFNVGIJTGHEVFBEEOHVCHZBENTKXGCASLQQWASEPLYEDTWENQLIHNHBH', props),
compute('m_18_11/6: ${c} PTETJYMYQWGKTBNFOKCKXHJNRYLNIGPUJRQVCMNPOWFAPQNOFGWYLPXMHVLUZEDVZHDIZMXDEVWRZDSCECMADIZFERMNXPLFBGLL', props),
compute('m_18_11/7: ${c} TCNHYSFZMXWNVXIIWVYUSZAQUVTYIEBVCNXZQXCKSUYCXELEJMVTCRBJQCWRVFJEYWYFMNVPIEQKYYXRISPTXWFHJSMXZGBOKOMR', props),
compute('m_18_11/8: ${c} XLEZBLJQMPQMTIEGWUPWGGVTZIXSQVBCKBSPNNJLQVUDAECPIJCGGQXQLAQZSQFLQIJAIPVTVRMAYIAGLFMMIELJFUYOMKDYPSSR', props),
compute('m_18_11/9: ${c} BBLFGTVYLVJLUZHPONTZRQVWBNTKFAFABFONNDWBEXKOGXFIZGSHDBUOIEMTTUJVEZBHIVJHBRZPMAUROIDVMNERWXRUTDWNYGAX', props),
compute('m_18_11/10: ${c} FFWJBIPBGXAKZMLLPPTEEYTMZFRJVABEPFCOKVKSARBHFAWTVJJKGDDUNBEJZDDUZUDUBWQJHUBKFQITRPOKAZVYGMNEAXMPRWXK', props),
compute('m_18_11/11: ${c} MNRZHWSENXSKRKCPESIMJCXAAFJAKUCFLACJKRAEAHIALTUDLKUQPQPRPPWABSGGIDYKYPFQUZYSLJOAYKQKYVRNNQUVXCVFTNUR', props),
compute('m_18_11/12: ${c} NJGSHECUTSPUCLUMBNZOTJVMZBFCUQZSZEKJFRZUEZRTOLLXKWXTNJNRDSBSBPFOATCLIVGFZKDNUJJUKCXNANBWPMWGSZMCQEPD', props),
compute('m_18_11/13: ${c} WZBXMLFSAZKOURCSOEMMJHNVGXLTDKEKCXUSKAINKEFQTFWLMZKWGGPRZERSEGPAHEMGKKXMSHCSFWAJDAJEUHBKNCSHELZIGUCQ', props),
compute('m_18_11/14: ${c} YTCCQNFPKPPXDKIGBYKRRUZZZWLODCZOBGJSHOMFEDTSHWWOBFIKVESNJNLOCSRCYHVDIWKENYROTCFSMASZPEHGYKAVBDPMSOZY', props),
compute('m_18_11/15: ${c} ASQXKHVZTAICXZVXZTTJXJESEYOCZKPYJAGLGGFBABJCRDVIPQDIMHCYETFEIYUZKXIJMDBWIPILVNQFABBZXQTAZNHJBDQGTCIU', props)
        ].join('\n');
      }
    