
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_13/1: ${c} UYVAWUSTDFDLTBTNMXLRJZOJSKGMBFLLACGUAEJBJWOUFOBSHWCBRRSLPOIYODCIINTVARMFUUAGDINGBEXJIPEOYEFVGBKRIWXH', props),
compute('m_19_13/2: ${c} QBBQCLQITGRQNJQZIKPRTBNOMWVGLCNFXNTCMBXMNPSZVJHMBMGUFCUQYAFQRUNEVRRAHOPOXDSMHOUOEPXTRMSXNZFPYVGZJTMB', props),
compute('m_19_13/3: ${c} WAHVKUUATWLBHDGADPOKTNSOQDSYFWSESVHSNNPNHXWEKWJNKZWGUGRMGCGCQJFDVSSBSAPVDPYBMKXSDUPAWRYHWOXGKOHIIFOV', props),
compute('m_19_13/4: ${c} GJDRASWHIHUALSRXGUCAFGTJOXNMMJKHDELAMQUXJVNICGQLJAKXEJEBZZAEBVCIXUHCEQJNMNMWFCAFURGJKRFZIOBTQMSQFWSK', props),
compute('m_19_13/5: ${c} HKWNIZGIDPSCTOLGBOVCLKNSGOFCEPRKGDADJREHFOTVRBGHKPWZJCCQWSKCLNWEUVDPOFGQWRWFVSVAEWFFENZMCEQWFAOXMHHA', props),
compute('m_19_13/6: ${c} DPQMTPGKPKQRBCAIHPHKRZQIKVARDWNSXQBSWNDPRRMOZTEGPUFBHZJNSHCVBGZZEEUZNVFSHMVMKHWHBWAHQTMLCLOMJPHCECYO', props),
compute('m_19_13/7: ${c} AOTJXITUJZFQNTQNKQOCOLYVNKIYIOQSVINKRLZUPUMEMZEICCVQCCXTLFVWZXLXRDRCHADGYMAZOEHAJKGSDPSDTNJLGKLEYIMC', props),
compute('m_19_13/8: ${c} AVDESTRFJQIUYZUFLVDNZJYLPXPQQDZVXHXYHNJVHNPHGXJILJNUTFJJYQJTWSBXPEJZVJFMYXIFESSJHZTRKHMVMSBOHSFJICQV', props),
compute('m_19_13/9: ${c} ODHTXNXZBGYAJKZWQGVFLSBPCOHDTTMHOINOOGVJIDCJCBSYONNQEFISJGTWPBEJZIUPMRSMTZIQNDXSNZTAYRVVJGCFLSTDEQMX', props),
compute('m_19_13/10: ${c} IIQCJHSUOKNITLFUSGSSGICHPFNCCMJZXPGUPFGLRMHPRAHYMMDBEMPOZYIKZXXDZMGIHVDEBPDYJYWWGIMHZVWQONSTTBPQBHXP', props),
compute('m_19_13/11: ${c} LNRXPKUOLPAFXRXYHDYKEYAYWDWUHUCPUUOSWLCQWPSNIMPKOUKKUGSZKRZBDQKOSJZOWRUSRGYQEITNOWOWINTADAPKEHPSKFWF', props),
compute('m_19_13/12: ${c} JVVMUVAAFPFUCTJSFYOXXSLDPYWCHQWLBOTWEIROBYHPYGUMTGGXPWVTNPFEIYLRWFKDJWXVHTDGVVHFWVZMUFHPJNFBIHSCNONM', props),
compute('m_19_13/13: ${c} TLSZWQFBUEMASKJIGIXCFDENYUDFXJZRALQUCMZBPATJNQEGQGEYVXNUOTPTFGHMYBLDBHZEWZDVUUCKQFUKLGXTTGANXDSRDAYX', props),
compute('m_19_13/14: ${c} RWKZFCFIEMILQIQXTPYQFZJYQNSENAPZJJNNZGOJYYBOZPLQLOVDSUTZCLEVVDKZZQEXFRSFOBSZIXCKYHSRUTGRHVOIVARTSBIO', props),
compute('m_19_13/15: ${c} AJDGCJAEDYQEIXMSWUAEMRZZZOVBLTDYNUQAKBLJJLNKYOIFPKYSYPABHLXDUTGXFDIOEJZDQJXKLVLFBDNIWWRRLWEYCKTTTDCY', props)
        ].join('\n');
      }
    