
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_5/1: ${c} RKHARHATXOZKNZODMZJDHPCTWRHOVBXQEAYEJLPVDYGUJNYISJQIRLMJCMAJAMEVXQHYUUNLAEVNGCLWBWTRJDMBICPGNIPNOXXN', props),
compute('m_19_5/2: ${c} LGAXSAKYRELTSLASDULLFPGEPVSMMBDPJWOPMSIVYUAEYOHKFSNSQQADWECMVRQWEEAHWDNIGICMMBJXHNLBBNFZXNCRLDAQRQLY', props),
compute('m_19_5/3: ${c} JYSVWJSHJWLMFQSBHLKXMHSVOKASHVGAQFRGWYYZMDTGXOMTVZMRNJHGWWGRASWMUBZIFRKVQLXLOJGYCOSRHOBMFHEFODRXZOXT', props),
compute('m_19_5/4: ${c} RVJTXZTPKBCVRUNXZWFRSINAKVJYAPIORYQWONTDUZWDXKBRYUZAASQPOCUTSIVIYRRKIOFZKXUXLEDWEKSBHELKRWOAQKKBIRAA', props),
compute('m_19_5/5: ${c} DTAVWTIUKQGHBYGQHXMNOHADTUJTQNKEQOJJPPIYCLWJOSEPNXFWUHEKYHGSUTWLDMHSIOSGLFMWJNHGBFLSKOAZUKSRMFLSVOLE', props),
compute('m_19_5/6: ${c} VDDDDOJCUBJPWTIQMCSABHAMKHIVYFEKADWPPSMINGTKYRIOFOJNFSTCEDJZRHWYOFCMBWNHITKGNFSALPZWGPICLOIFPUPUUQEB', props),
compute('m_19_5/7: ${c} JVNQAGVQIMPHVFMSENOPWGGXSPABZNBXINHXVSGTIHASSAOOOFFPXWENCTLMRNEABVFWPTXTWMKWKXARVKGBYQICPTFKCKTUOQVC', props),
compute('m_19_5/8: ${c} GONJFFQNEATYFCXLMRGLUCTAEHUAMPOUBODIKZMTDZTVRRAOIYHJVHELKOQGXXAWDUSZFZTMUFWMGVJZUATVWMFHHBUWVVVQNGPP', props),
compute('m_19_5/9: ${c} TNRJTELUEOYKNNQJZZFLUXJEIDTNAZOFXJVDKNRHONNQEXODZETVHTKYTCGMDJQBSSEKTSDTKDRWGHWGLELOZLXOFPJIVOSTBUVZ', props),
compute('m_19_5/10: ${c} AXAYFNSKVZZJPGJNCQCIQGPOYQOZFQPGRQIJZIIWQPVACXJANTLRFVEQODULOWBVDEPUVFATWZPCDLAHNLRGWVKMACHIKVFZECKL', props),
compute('m_19_5/11: ${c} VWDKNAXGIZXDVZPZAEUKXWKQHHRVYTSZWUPNIYRPSZANLIUWSBNDVOEWMLWHQLYRYKCDEKIQZNRCXPUSDTFGUXMTFUULZQIPXNJN', props),
compute('m_19_5/12: ${c} QHYIVBDMFZQVMBBLEOWTRTDZSNGIFHUNNEDHVQYBVERNTWMDEOKFRJDYKJWDNADKFJKJHMDIYGGBQDSPPBRKSWKHOQCUFFABUMIU', props),
compute('m_19_5/13: ${c} CNESJXGLGCYLXPNFQTASKAFMQXLHWJEZYNAWZHEYPJFBDUNFRLANHJHHZHZRVRNPQMCKCVFWJAINOZDXYUGOCKPXWUIHREZQVLFM', props),
compute('m_19_5/14: ${c} ISRRNVGQZCOJYTRKIGQJRCQKERENIJPHWLMOJWYPUNBJERHHQJBDHLWDTZGNEZOQOAMZUWRETVSKTQWMKDRXPSRKVSFWYWVPZMGK', props),
compute('m_19_5/15: ${c} EBFTDYKRNBATQJBASWTUHFOQUULDEMNBFUBFHLGXMQKUWHOJAKTSDDMOITQUYRDDDNDZFMACGSWEWUOCAHOFPIDCCIMBQBUFESVB', props)
        ].join('\n');
      }
    