
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_10/1: ${c} QLPDVMPGLFRKKFNXATQYEBIEXYXKVNIKMJKGCXOMEUHOHWKBLLSBSSQHFENNZVHWQDITGXCFVBCHXUERSENGSZASWHZNKWXLIGLN', props),
compute('m_19_10/2: ${c} KCPCBKOTSGPMFRUSUQYFJDYSWTLDEQODZBHOOILYSXCCNZCIWKMZXXCWIEJINCTAVVSJVDGKHXAYKPQYSPDFZIAHLKNUIVUEZHXD', props),
compute('m_19_10/3: ${c} ESJJUKHUQIZDMAKJOHBXRGDCOEYFCQLXQLKZLCBGYNWIGNJTEELHSBCGXOVRQSVYCXZNSODQIYEQYZSGKSZSGCOROYASUEFNIUXV', props),
compute('m_19_10/4: ${c} XRMEYGHOWRUZSUWTCNWBCZLFNFMBYHERRNTIBZZMAJIASVFJMEGBJSFWRSYCXUTVMDRRWELRWIVUMEDWPWAYHPYRGESLAWJZNBES', props),
compute('m_19_10/5: ${c} FATAAGKQRJOWOLPCEQLHLAXGSBLHHOMLGPOYONWLGFRPVTKPVMBLGLPCJBZKWDLJMYSKQIUWIHEQQKONKTJYWWFGTCAGSURDCKLT', props),
compute('m_19_10/6: ${c} RFHGSXVCNXNJANYVXSOTQRCBHUNPIUSTOLHDKVRGYHEIUBKYJXCLDZLUCAMLYEQXNNHECPLSMHBCWHQOFPRXOWYRIXYKDEMOJDOC', props),
compute('m_19_10/7: ${c} BQYAIPIQCHUCGIXQNEXCMVJPKRPTPUBFIECXHSZLXBDNBXSZKEYSZXQQTUCXQLQNOIBPVTWHOHQHRMJAEKTIRINVCXKISXCDXTEV', props),
compute('m_19_10/8: ${c} KXMYWDGMLVXBTSXKZAUBDTUDQKCUZATURGRFXLMJZGUHMCRKJZQQHGBOMTLRCTCWOTNYHGZFUCXJIWABNETNVKIWQSTGKMLXKWSO', props),
compute('m_19_10/9: ${c} ZKACSFHMGICKTJQJTFRFHHRUKGBZJMTQZAWSRQGADKHBXRJTEDGSVCHMKOYQISPKZGLKHRZAIUMRWEGKPDGHUVYJAGRFRIQZJUNT', props),
compute('m_19_10/10: ${c} AUULHNBYFOMTVNLQMXSQOXSQLBBZDVVXHWFFNWNNMOUHXDIXNFZHSCRWDKOWGHTHXOCEAFRUDYOUKDJEHMCYHAVDVOHGTAWRYHHY', props),
compute('m_19_10/11: ${c} QOFSNQNFNSSIUQIFUPTMMKMOOFVVRYMAJFIZGFGRXYKTZMJGZNGMOIESOGEGLEKPAAKIAAMXVLQBSBRSHZYFWGCWFSGTHPJHQADC', props),
compute('m_19_10/12: ${c} HUAEIWXYOBJVFBXFHGRDUTGPEEEULBILHEMPVISQSOTZSJLYRHYMHICHWDOIROVXPTTNXUAGFMTOQXCZZNWEBURIVZNVBAMHPVKQ', props),
compute('m_19_10/13: ${c} BBXPTINQCTZJCSCURTKZZWMSPEYHSATGQUVNFLMPPJUJOIWOVXLXABQPSXTGWGEICCLTWTROPLHJKXQMEBMVZPHAVEZXIISXJRYP', props),
compute('m_19_10/14: ${c} ALOJRRRAZFEXARZQTFIXMGPRBJMVEGHTAXINEQTOIFQYGRNSJXNYUEZKEFJLMLNCIJGYSOQKDPPELERANYJCUDPHWMCVDTVXBRSK', props),
compute('m_19_10/15: ${c} NGFCETCRCXPYTQKAJMGCKKZQCHYERMXVCLSODNOSUSSXLNTGWLTVCNILPKEQPLEUWJARYJBPJOEQPWUYJKAJYVHDNZIIBUBFRRJH', props)
        ].join('\n');
      }
    