
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_1/1: ${c} GBDPQXMFLKGUGZSYZUMQPQRMEHGROWBFWFKCMAKHFUCMPGKLRXAQMRAUFDKXLEMXQJYBWISVABMWFENKHMGHQWTAJGJYOSCSFXSA', props),
compute('m_19_1/2: ${c} EXNYJQKHEAFASKYXBAWDIKWAEYCUUPNNYETNHENAZSILBQLVLZWAZVPBNWUEGBNEKTXSQMONMBCOHEBZSAPYBGRGLDYHNGEKKWJT', props),
compute('m_19_1/3: ${c} WBXOGZMXGKQUAUQCLLVNGBKTZCMZEWHRFHBKXIORZRUWMKUKQBOVRPQAKMDMOGELZNTIJICDIBDKTHTDRVBVCFLMPFYECFUJZOUQ', props),
compute('m_19_1/4: ${c} AFEXYGEUMXMKNTLXBYDLVRDLYSRKJLKCXWUQFDOVYDPQFLSWCWHCOMMVPDQRJLFJAOQXKUQBBQOIYECHOGXSMRUPANQOBGEGVYAG', props),
compute('m_19_1/5: ${c} VHJBHLXJHPJKEXKUENMNRHZDMKETMAZMZBIWMTFSDYJFCVACOLYNEUYEIOHZTWVHJYZGAMWQBNTOODWAZZDRXJACAYDBWJFBSPOA', props),
compute('m_19_1/6: ${c} KUMTFZNPQWWRYMDXUOPNETLFDJBZNFDHSOPFFKKWVGESJNPYKTKOLWXALLASNOWFAWQWOSHLGAWDPCLORWIVSNNQMRPQQXQUKNDE', props),
compute('m_19_1/7: ${c} GXXRNJLAKFUHZREQUXVTHFSQKTIHAHDWVPPRTRZWSXNQDUQJGIEWDAOJGBFKUCLJFWBWIQKEWSJBXEOCHUBPUJHQJGDWVLVLNVVH', props),
compute('m_19_1/8: ${c} RNVHQJKJSHBLVDKUZSVSVWXTHZBBCPMIDCLRZHMAOLIBZZBQSMGDINEIBXPARNWSLEZGBSYEWCLXLFIRAATVCWEUJZCGNFWFEXQB', props),
compute('m_19_1/9: ${c} KUYVLRIPTRWHMHBLOHKJAAFADUQOXERRPNFCIJXZJTIGYOVBNTGUASSTSDYAYDUAZNOZQXZSVDKDLWWKUANPMGWVSKKOZJAAXSUJ', props),
compute('m_19_1/10: ${c} FMCWXXCFJMDPMIQWPHZDNQDPVVQMAOOSLADNEUYJIPXXPFEBLNVCSZXLXKRVUTXGYTWTRNJLPOUAGJYTGMOMQYCPLVCUYKZEZEDG', props),
compute('m_19_1/11: ${c} EOCSARPMVOPFADSZCCGLUBDUOVHFTETORAASNWKDNQMNEINOTFCYZIPSHGPNMNCAWKOVHQVQTOYYWTRLWOHBASNZYBDLWTRLORFT', props),
compute('m_19_1/12: ${c} DZDGAOEYMDULZHUBVACKLTNGERCQRDQTMMEMUZCWTENGGJKNQLLITNVCVPERKGXLZYGCWQJYPIJDYDMFPGRJKYBWXVXXWZMDTKNG', props),
compute('m_19_1/13: ${c} ZDMSQOJKEUIJEQIRRMVYLNECMCJTUPLVWIRGYVLTHPDPMWMEBANUATDUHEZNUHPPKCIHVNZTUIWKRMNFADYAZUMENISQFNGWBLAF', props),
compute('m_19_1/14: ${c} ZJZFBXGAGBNHAAOOGNEHNYEDTUSOGHXSFFIWMQHMLZTNJCEIKLDFRCUVZQFFXSLUMIDKOCTQVBDJZDOPNZRGYGOJGBHGQYSGMCMW', props),
compute('m_19_1/15: ${c} YZSEKROHEZGRFKTCBXTKTHDFTNWAPCVWCELSMFUDTFFIBDMSOUHQNWPQFHFPMWPIRXMZPPQSWORGPVNPQPVCFYDRSCXSSJMALLYL', props)
        ].join('\n');
      }
    