
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_9/1: ${c} LPREDBLKFTNOSTZBZVZVDFSUNFMVXUYTFPHOYWPZLZYUJDVKPVLMFOBKGFZVFQOVYOLXQDRLQYIXLSMQQZPXIAHPTTLVDXLMTJJN', props),
compute('m_19_9/2: ${c} HOEDWCWYLFCJEHEGZPLBPTRCTLIXXPOUROOTTRSKBLYRTXGYNDJYUJEYOOFICLADCOSDGZALXKJQIKTPYMEJCLNQMOTQNZCEDNMX', props),
compute('m_19_9/3: ${c} WROIOAMANZLCLNIVPOXMGZODSSACEFKFCYKWWIZDESNRNFCTEWIQPILDVDCIKBOMOTMSVTHMUJSVWGPFEUVDEFIWMZRRFUGJOOTZ', props),
compute('m_19_9/4: ${c} ESQYSODDBYUQBAHZBMDNJVBMJAJHHRHYCXTOFQIPMBOREOYEZYMHPPIYNPQRKUKDJVQMODCDCDOOCTGCWPNGFEWRYFCGXGEVSYQA', props),
compute('m_19_9/5: ${c} ZNGJGUKNHCIBPLIDAECJFULSXDDAONHWOCUHTYQIUEBQZPUJNIPYIPKQTDLHVZYYOAQXAUEWHEFNIKYSQVMESKHPBRDHDPFXNNGZ', props),
compute('m_19_9/6: ${c} HGUCKSJOIBZHCBUNLYAYNHJFAXQZTXPGRHPIUKUHRVJRPASESLNOKMCMPAZUUWUWHNCXFWXWNWXNVJGASZYETRMVCNFQJTXZLXQH', props),
compute('m_19_9/7: ${c} GJSKNPOSFLRMJCGJFKRHHOBFKFUJKIHTQOMBAQHESHRKCQRRAPFDEHNZPVYFFCPUSYQXDRYXIDMBCJAOTFHWRSNYVMHTNTCNLYYB', props),
compute('m_19_9/8: ${c} CZOUDLJENBDWLAJLELRGDULCNIDQYGHWIYLDORFNZIXFXJQNDWTAPZOOHWIWAUIHKITNWLYTBLTLOUEBPEDPTQVAWZRJHEMASRPO', props),
compute('m_19_9/9: ${c} OPQBABFSYBTILUEWLPWKJPDGEMZSYUWQADXZDTUKQHUHOYTPAFCLTXLQJGQKYYFUUNFVKOQFGQNDYLVVNUWWRDYUTVXDXGPUXYZC', props),
compute('m_19_9/10: ${c} VLBLSDQEALCZIYZQBQREFTADLJQCHIHNPWWQQDTNZJIACJGUSXQHYHVDHMPMSILALFYCQBREMXJCWUZYMCHMJGYWHEIBJSOAYRWU', props),
compute('m_19_9/11: ${c} IGWBXJAQRCZNYUJDMZQMPJEUDERJYUAKRTMSTPTCIWRLJHQHEZNBYUFTTBYZWQCXZUKGBECCJWQFDVWOGHOHHAOUAJKICLGZEFGB', props),
compute('m_19_9/12: ${c} KRNCGGABCTETHFJUJQVFBOFCRCIAWSYGKUPWNEDQXTGEQPTGALWFLLQQHOHSWYJNUKXOXUHCEMBYJRHCGJOWKCZKIGAFOBQVYHFV', props),
compute('m_19_9/13: ${c} VBGWILFUFTSWMSSZRYLYBECROZDYBAJWKOSZKFRUMFNZGOKGHEANZYAYNMBZZRYGBQDEGUKEGKEPOHQFVDDUUXLBYZIWYCJNARQJ', props),
compute('m_19_9/14: ${c} AYBDHAECUNDYPQXQZGALQEMILHXWUWPADPYXBYYGRCAEJKPGCZCYFSUPAKJWJBSHIWJFKFCEJIILHRPYIGNVOMFKNPCJCOWJMLIL', props),
compute('m_19_9/15: ${c} DDYDQKQMWXMFJYNFNBOYYXMNSQBFVHWHDEOZBTTELCIEDGNESDPYKDOJESZXRXLDZCWZWFFUJCSFXZYNWCRVFVUOWCDWXDZKIGDB', props)
        ].join('\n');
      }
    