
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_11/1: ${c} ATHUDVVCMNBPPSZUOTKWCDTBZMSCBQVKTAGGUVTKFDYTKJRZZQBYQTDSPGJTMTIUJHJIFKPLPXTYZOHZBGEOIBVFATGOFIIWIEVO', props),
compute('m_19_11/2: ${c} QHUDKZVXXESOVWJGHVWGVORZNADOUMHNPMTIMFVPPCTXJFSTXWIBLHJFYOKQXMNGUNJIQJHYMJMVWOSCWFASYNDGMXEDMSCJQVMA', props),
compute('m_19_11/3: ${c} CJINKLACFDOWWPDFIEIEPJCYTYFQXODBTASIMXGWJULXPPFGFBVSAKTCSFQQYGLLXQSEXETMPHELQICTWGCTPZJPZTQMGTZQRWGF', props),
compute('m_19_11/4: ${c} NEFCVXRABMLUBPEOHVUSAZJWVSKSRRLDJCWCWNJDKZDHHICWXDCGTTFNCPBZFKDVLCDYZBMTCUOKYGZZJKNFFQLABKSZXVXLQXJT', props),
compute('m_19_11/5: ${c} JZTKKUKFJKGWHSWMKNEIWJBKANETFMZMYFDNWMVDEXWKXQFCKPOMWQWXFHMTGMQOKGGEZMLTIQEAMDVWTYMIWFCVUXRYAIYSRRTN', props),
compute('m_19_11/6: ${c} VVTZTEXQDRCZBCYGZVWZKNJECAFNHTQHRWLWTXHXUTCVNLNLJZNMNJPCHNNBNCFMRGPEKYTSRFYDKZVKIYUBIFIOAPDGOLUKJDSW', props),
compute('m_19_11/7: ${c} THCXTEOJQJZYSPXXFZLVHOLUGZVUGPDSZFIUFQELEABIJLTKDMHTFFMUCWISBPNRMRGGVMGQQKYQGTDWLVLGLLVAKGZMXCXBSXFK', props),
compute('m_19_11/8: ${c} ALJTMVYQUUNXBNDGCDNAOBAFRBWUBPITTDZIGCVIAHHXGWXTEPIUMACATGBDOLVAAECZWYCDHBNVLCFVBQNNINDCETHVUPFYCYFD', props),
compute('m_19_11/9: ${c} BLKCIIIGOPLKGUKAFTHOZBPBAJKBDHBBTEBINKBFKOVFPYMRUAACDUSIOGDOLRUVVTGAOGKTKRLUBZEWUMECFCVSOIUMMFIZRDJL', props),
compute('m_19_11/10: ${c} UQOTOYBAHXRKIZECOBINXRYYNMVFBVMTETIHXBDMJNISXAKEYCUPQBDUNTUTJEZWYSMNKNGQVKKTJMFBXNQPTPIWPJRRCXZOHVLW', props),
compute('m_19_11/11: ${c} IUAZKKKVAXLWLTKCVWFKDLUNIKMXSGOOIHBLTDYSRDFKAQYARBYKIHLRBEEUSFIMNWFYUHOZKRKYAGUCUUHUZAFWPHUPASUVBZPM', props),
compute('m_19_11/12: ${c} HPDZIYXNIABAVFDEZCHUXUNIKBNHUMSFGORRJMUOLVGALUJRULWCIUGRGARJOVLHELWGRZFCRBAVKQFRNAXYTMQKZFNLKGRGKDVL', props),
compute('m_19_11/13: ${c} KGUTWAGQYYBNXFKJDJXYTYEAFQIBHJTHANNTTCECRQUYXAYURMAUKEYETHVRDXQTSMTOTYRXWVZYOEDGENCZBADQFYRWRBQUTUMF', props),
compute('m_19_11/14: ${c} CVDLGXYDMNSFALVMUJDXCDJSOGOBFMEDZJTIEQXICDSPJFPNEWPBRJSBSDDIWPSQUIKYCDHGKISPXPZOLTSKHXOBPFNJBURZVIZF', props),
compute('m_19_11/15: ${c} JOAMEMSMJJMHJJRTJKMBNRUXFYJBKCMDNBDLJUVLEIXVTOHAMBZPOINMELBRXHUAGCSDZGUUKPKTBLIVCFEBIPMBTCVHIEQJRHVQ', props)
        ].join('\n');
      }
    