
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_7/1: ${c} IEWONPEXAIHMXONMASIELVQFONEDHDKVDSZADIFQVCWQYAIPZRGZGUFPUXUIZEMCDPDTHREZPEZZJTJJRQUBNHHICNLBLIEVYMEF', props),
compute('m_19_7/2: ${c} PAJHVTQLLTFQDSWULXKDCXTQOYDUVLQCFYVURGODQRYBXSSAMEZYFCTIGJIKDEFVLINWFMKBEKAWBFNGLNWMMUECVEVUZOIFIPOO', props),
compute('m_19_7/3: ${c} TNPSLAPSIWXNCTVCEJPWHGOCAMLETPBFRFJNXWTZXUUHPQSFLIFADUPSHGIAWMELIMXCGJBSLCNNEEWOPFCEJEEUONDUBAQQNRRS', props),
compute('m_19_7/4: ${c} UHTPCWJFJCHJIPSLTUWKRFLRAZIDBSSEQNNLUSHWTSUGFQMZAHAWXIRYBYZQYWBGSYUPISQCBFDBXVYOOPWKYDRSVYTZHDDIZHCU', props),
compute('m_19_7/5: ${c} CSHKDWASDCIITEBALVHOVTSHJGEJNSAEYPYMLOLVYLCYGVOJPTYWNYYUBILOPFXLCXBWKXBTOSZMCWWBJSKZCMNNLZZLDUEQKWIR', props),
compute('m_19_7/6: ${c} CTHENCEJDRVZAMBYPZAXRJMBKMEXUQCXCMDJSTUPWMQWNXNZWMUEHZDIJYBAOBJQVXXXUWZLAMQEKMECQFXKODJFMOVUZQWWJYWC', props),
compute('m_19_7/7: ${c} SGMAIPXEQYJFOVKURTGNSKPDKVHUNVCQFJLJTIGVOYLOTYFLEVWLPGUEUBLTAEBAQKIMZVBERSAKXQRRNQSFLMXRUNFUHGCUJCIJ', props),
compute('m_19_7/8: ${c} VOJOXWSCKJRGPJSOOWNCSTUYYDLSBTJJWYAVPNVFDBTZZCFXNOASDFKYMDCJLTAJHUHGUCZEDMWGFUGIEQSZKZTOQSNJMLVUXJYA', props),
compute('m_19_7/9: ${c} QYKSGICSPFWXCTACOPDJALOWTWVJHFPLQJJYMBAADBLMSHKFHMKTIIGGEJSQNIGGJXKWYVVFIHRZHDWCAIMBFOPNMGJDHRJEEYRP', props),
compute('m_19_7/10: ${c} AJZOKUPZXLQRVTUHYHDFJVDNBMAYFMFGBXJBFAVEXWDVXEMYJPWDPQBJRLCWJLXSYUNTQEGZZFYEODDNTMMPHSTXQGOOZGLJQUVT', props),
compute('m_19_7/11: ${c} TROBLCLFERIYXDUGBEGCROXTIAEIWFWHMQPGZMNPFATVJKAFNBWYPKJXEGRPJDOREHCHWBSIERTNRRMLBLVTXMXNURKMPTVVHTQM', props),
compute('m_19_7/12: ${c} KOCLKPOXUUWROOKKONNEBCLUXYPBQSOZOXWIBMJGSICXJWJYGUFGUAZOTUXFOZZOOCCFEEECUIXSIXZLPTQIIRELCEUVENTVONZN', props),
compute('m_19_7/13: ${c} PHGJNLZPFSQZPQVQCTTTFNVYBEKXAGPWRJLCLJCRHYDXZUQKRBZIUGIXLXWOLTFBPOJYNFNSFOPMCFBDZMMWRZWVHLAUBOJMIHLF', props),
compute('m_19_7/14: ${c} YPOPCVGJWPDJKQSSIDVRXHCQUUJININFDTQJNOVGTPSYVYCQXZYLQTCYICDNLOJLVXVUKXRRTNUSJSWTJYPVOSDEGAULDZFYSAGL', props),
compute('m_19_7/15: ${c} GXCRBEHBFJBXKODLGAOWXUTQMZLDNOEVAONYPBRKRBNNSAYNIPPUOFRBNLAOKDPVHZKFLDAXTCGBXCEKIRQMOAURSOSETXJCAPQX', props)
        ].join('\n');
      }
    