
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_6/1: ${c} PRIQZYPZDCTPMHIFVJKYOKSAHWPMFWPRDDDPZYHRKABLABIYJRPJRKJAVJAJIVFZRFURPKOXNIZIYLTRPLFOYBRCRTJFOOVRYUXF', props),
compute('m_19_6/2: ${c} NKMDTBDHONEWOJBTMMOERBWVMZMMKMCZPZZKHSMFVKWJORCREGWSXGHIPMDWJCQVLSQOADLEBECAWNXDJXIBFRDHCASXQZVMVNHH', props),
compute('m_19_6/3: ${c} PWNQUUSYBEEWSTLIUFFXKJBYEKGKNRINFQMJWBPFIEFSXISWDYEMYVUIZKQHVLBSNZOZSORXLTQDQEJPCEYJNRWMYMRCHTIZNURJ', props),
compute('m_19_6/4: ${c} IFYWONRRZFWNQJBHVJKPWTGYFGXWQWGDEMXRXRZPNUUHQBUNZXQUFMGAQOJCFAUVZFGFNOPALBFZBIWPBHXXWZOIBIDKATRCWHEM', props),
compute('m_19_6/5: ${c} HAIOTTHXNFDXNDDYUMHMYODAPXAPJANVPENFXMGMLEIJWGTYMIGDDMLWJBXWZPIJLEROKYABSQUBHDOWMHITHHMYPTQHPYBYQIWU', props),
compute('m_19_6/6: ${c} PDLNKZIDKSPACUHKMVELJNRFRLFMGZDQBKIGOPPAKRBEGBYZLJOJBLJXSQXIABVHYXYPUCHIRAVADGMURUPDPGVVJDPHTSRXWXMP', props),
compute('m_19_6/7: ${c} WNSEDFHMXHLDDMBMXDUPUXLTQBPLPHDXHDQUULHWITORPFUMSMGZSKJERRYWBJWAEICJAUTDWLYCNRGSDVBYCVOCKUWRFYSJPGBJ', props),
compute('m_19_6/8: ${c} BLRSIUWSENZMTBWYFRQUNYGQOFJQGCRJIDISDUYHEVXBTONJPCWQSBKCQHTAVXZQMKVJBLFBVBJSXRPDVHSIYQDWVABNMVKHROFB', props),
compute('m_19_6/9: ${c} GLHVOGFNYXSBUWNBHUZOWKJRKWXLPURWGITCTHDEGIUCGIXYUELZNGTMHFNXLGCEAZMGWSOYLAEEYLUCECIVIQXNTBHECACIYZNU', props),
compute('m_19_6/10: ${c} MYACPHBCBUUMEESODSJRRPNJVVNWDFRNPULMTHCTQGZBUOMZXIDDDBDCHVEOXGOLDNEELWVVCQHSGNQBSKOCNBDQETAPKDQKXRXE', props),
compute('m_19_6/11: ${c} HRQQSGAIAOXHIMCRAMWCCXZNZYMLAGWZGMWAHFAHHKQQZOHNHAEWYMQVORWKDNRRAOXRQGWGHQMDKGVKHNLPGXTUYILGPFNBDYXA', props),
compute('m_19_6/12: ${c} QTIXSQXQVNWGGMZVAHEDSLVGZIMJPLHZAGMJZBDNMLVOOFCYUEJUZYWDKSWJSYMLEFPONRGIQNOTTXOWSYNFDQDKGXZUVUOFWSZJ', props),
compute('m_19_6/13: ${c} YTYGAZXTUKTNSKICFHANOOPCFJQUFMCNKMKNDZSDWNBGSRVXCZDBBKDQXVCQZNEIATVGOFNECYIZCOAJIEHAQZMZEIZPEPUFXNYF', props),
compute('m_19_6/14: ${c} LGHTBBTTBRJRVYURLXKLQWMEXGVTJZYZKFOIOEMAGXQDBMDHNLJBLZFAMUPRWUZIQSEDNRDNQKNMBDGRCGDRIWHBUGGXWYJAJGFH', props),
compute('m_19_6/15: ${c} FMJKNWTOJNFJMLJHXHXMZLHUTFDJKOJJFBMAVWYVHYEDECKKLQMLBLKHPGPTABIDIJPVPRQXYBQXFLWLKDPJUQLOQJIGWSIANDHM', props)
        ].join('\n');
      }
    