
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_18/1: ${c} HCJVKSHHIZNKNWJZNKYHRPTWONZNRPFNYEHMSGYAYBWBPDJYDDHGPHLZCKPDWBNFHCDQVATICCJVDSYLQPXOTCLMINWBIXBFQERC', props),
compute('m_19_18/2: ${c} TVBUBMCVRKNUYYMDSBTGAPOOBIPXINEJXJDWWCWACGTXHTRRVWHVBDLHZMPUWLFBZVWVWTIVLWJPSLLQSIUOHTOWLCPINYVPMPGC', props),
compute('m_19_18/3: ${c} UCQSPZHYBAVRGLKIXFSJDFNLBMUHKBEEFGZFIRVNPONWXEOWKOZYLSOEJHUCKDSEEXOPKWHEXDUYGBTPXLRKILWNJDCXKSLAIPBJ', props),
compute('m_19_18/4: ${c} HHAZMHZPCOVPSOPDDBOXBVSKIPSBSEUUURYPBTOYCJMTHIGWZOMEMBDKBFVRRTUXRXZXAKZMVPESPOPFSFYEGSFGQEAEDQRVBEBA', props),
compute('m_19_18/5: ${c} MLADAADGZJBHAWDJUSNRVKQKDGZHEZMZPCPLFWLMDWCITAYOOAOSMWCZNREHGQRYDQLMAXGHGORNKHHFSCOUYKSJFRIPGQUAFYTJ', props),
compute('m_19_18/6: ${c} LKFCFHUSSJTXXXOKSDZPDRRGGGYPZUQTJNJYSWLHWNPZNCVGVFMWOBNQZXWKULTWWBSBDVQWLDLFSXBIFJFIINIQNKTSSLRSEJOZ', props),
compute('m_19_18/7: ${c} IDDXGKQQZBUGLYJSUJJLFUOXTCPSAODVTRXWGOERWUUKYNECRQTFOFBTZDBBAMKVQBYLUPZNRXFZYCDWAVBRSCGUHVZLSQRTQQQU', props),
compute('m_19_18/8: ${c} HWHDJCZGKCEDPVJEWMNQVZMUCDBGQTTDIOMEUFTNAPRLZUAZYULGRRBRQOKKUJMJEZQBAEUWMCFKOXKZOOIUKSSAASHAKMTJFRIY', props),
compute('m_19_18/9: ${c} USGKXWFOPSZJXGZMXQDBLOAYNCBNVUOGOQEWJDCATXFTVDHDSMOJYQKZNUCESYQEAGEZUWONYSSKMYVTPICACUQWLYFVWMCJUNSN', props),
compute('m_19_18/10: ${c} WBKPGVDIQLOECFASJSDORVJHKNZBUUHFFJHVHOIWHLXPSLKVKELDRQGFBBZJAMNAOVXFVIUGGVGZPQJTZGZUJSKFTXXMPIFZRMXN', props),
compute('m_19_18/11: ${c} BQZUJOCTGRNPQGJKMXTOJNICGDGJWBGAWXXQWCKDUSGSPXIDVOHROOYXYERVGWIPQLUQWUWJYSAEKOVGKCOMBZFZWEXXDXGXLXNS', props),
compute('m_19_18/12: ${c} VYFLLPSSMRGWRCCFWYQHBRKMHYMNDIEGBMCNPBETZVRSEFNDZIWLQTXXNQOBWTLDGNUFAOYUYWIKDNLNEXJFSVXVEELEFDUAILYR', props),
compute('m_19_18/13: ${c} PIHQYRTSHSGEFIICRYACOOLVWSMDAAHQRSRNDQWBHQYIWRZIPOWIKIPUQUBUOQGSHMLIXLVCJBMNDSCWIBCCXPGSGNTBMURPXRIB', props),
compute('m_19_18/14: ${c} JUWSTFVVPGMHSRLXVPWKBDHIUITPIFPVYQWTPIPYQZFGRMOYZWGMPUETHLQCLUWXFVJCNWFKMWAEYFZGSAUMGMRAQFGNQKTTHDHR', props),
compute('m_19_18/15: ${c} QZKULAWREUCEBZEPTAPGUOPKKJPHNOYEGYZTEJMODVHNBDFVFYVJOADWRAEOQKKWMOAAPJZMWMCOLGKODSLTOOKFUCLOYOMNQJPK', props)
        ].join('\n');
      }
    