
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_15/1: ${c} ECXIEZKJLDPPLGYQJMLIUJRSDZDDFGTBNTFTPYHNXTZOZTKNWPAKWPCXAIREIBWUKNGPSVTQGHADZEPOELYVJGYAVDKQCEVEKRLF', props),
compute('m_19_15/2: ${c} OAAHYCSCGCKNEYGCWMBHSCGUAWQHRIFEWNQPKTYBSDHHRPVUIBTWLFXYEFWIYDUPEURSNQNNKAYPJZFNVLDYSZQVJLFETRSFFHKM', props),
compute('m_19_15/3: ${c} IHYWVHHZDSKSNHFBHYYWOCUEBNIDVOOEQAYPUDIATKBLGLNUXXZGKECUXWQBZDWSPSBGMHPWVMYMDRGBULOFNDKFNRXXDJAWVTNR', props),
compute('m_19_15/4: ${c} CJYIQXZMPGJTFWNIAGRJBBKNMQVLCLAZFRBAUEDHZPPMEVHOQXAVMVIMCIWAMSFRHEVMTAEPZPPXKOLUIGUFGFBYDUSQGNEYCNND', props),
compute('m_19_15/5: ${c} SKCVZEVCYJWTSCRVCVOLLFCFVOJMFMYDOLXULJJWLDVZFUBNYIAHMTKISOQJHWHYNEOGDZGXLDWKCQBGJAPKOZOFVGVACLSKKYLA', props),
compute('m_19_15/6: ${c} TTZPPHFTMWAXCUBCAFWJYALVCAOSDHRMPNGAWMNQIQOWKVOVOQJJPBMMRJZAROLUKNDFPCMCCGIJNCBUDJMHYQHUDLXMMMLCRNPT', props),
compute('m_19_15/7: ${c} WGJGKWPEOXMVRGOZXQEHIZDKWWIBMQUCYZUUMKKLRORCHIUMXFBYULCJFUEHEHIDAIKOAKTJLSZJBZDYZSBSWRFTTGIEWQNZLRGI', props),
compute('m_19_15/8: ${c} LWECUUNWTMUCIKUKTPLBWSHAEJJNCHJMXGQDHNBHKGYBBBMSRRUVUYWKGFDPINDSQAJMTZEMUUITXBOOZSWUDKQCDGEHNBQLXORU', props),
compute('m_19_15/9: ${c} RVSGBTHNMXRAVNYYICDLBCUSTVRETATHABDLJWEBFLRUBGOGRKZKTXTPDOOJUIBNAQIAUXRGLEKJVYTRCZOQNSTGUXDBSEXEYMAY', props),
compute('m_19_15/10: ${c} YSFFMOMETCUPEWMZYRUZGINBLGXQVFFQLACRKHVDHSGEDOLRAUPNGIHJAMGQQDATJWQYYXOXRDVSUGCOTPRKNKVFZMGETUURMGZE', props),
compute('m_19_15/11: ${c} OKHVQWRDFWIBPTGCFWRFNMHNGVAZHCBFJSVZKLEQLOOYQCKNVYZUEEWOSNMGFGWSDNEBZEYCYRJRKUQZMLHSPRZOWNTORYRKUHNS', props),
compute('m_19_15/12: ${c} AGBVSYRQVHOGZBRATSDHPVHQIFUZMZBMLRTCBWKNDGPYMRXHYJVRKEKNZTRFCQTHQHHUXINNSKMYMXIIXPBEYIMZQAOSSLOYKRDE', props),
compute('m_19_15/13: ${c} MQSEXUNEVUVLTSMEQPNYQQDLVUSCSXXOUSQBUMUMRDCTFUAPWUJKYXBVINHWXYCGUISSMDEIRLCBMCDJDVAPYXZALHDJVKWIFPGS', props),
compute('m_19_15/14: ${c} ABCTKBRNXSJZUBONFYWKPKAAPVOTJTATLYGSESBNTICUWHQMDOVBTUJPXWWAAFYSHXWXOEQMGCGCWSIKOAPFVCAOQNYRLEVYPMWM', props),
compute('m_19_15/15: ${c} DXQZUWWMSKXFSFFHUGRGYSGKQWLVMAAWIQPNKBFWYGNKJHJFYFUUVAAOMGNFEPJQRCFWLFBCWNKGRYYLICVMLPOCZVLVBEHYVWIQ', props)
        ].join('\n');
      }
    