
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_2/1: ${c} ZEZEIARZHZZRWXMYFRAVWCONDWKCZKWMQSWXJDJOYTXCTOFBOLBBNGTSEOFSDTFWREPUNXHKPWGEKDICFNBMGAUTPFCBWRCZSBCZ', props),
compute('m_19_2/2: ${c} PBIMCKFFOLPEZQMPSQTVJORHHLGVOBRRPUDSZCBBREZJQRFDAIWNUATFYQRYEBYLZOUYTLONTLDLYMFNHMUDLOXKIQSQHFFTOUML', props),
compute('m_19_2/3: ${c} KXPYKIYHWSOZCGSILCMWBDQAFINKKTBGIIVDOSSCBKSBRBSASRFAMKAWSXPCSGZJXBPRPCWFQEEBXRCTBBUTLJMDQLTPITCIBGXQ', props),
compute('m_19_2/4: ${c} EFLQSIUIMOXCLEHXWHSYAWUYOKSVWDYXQZPFTBYYQUVSJMLVIPPKFRNWFYOUOOGBVCMHEAEBCEXCSVHQQGNVVRASXPAQDTXLRXOI', props),
compute('m_19_2/5: ${c} MDIAFVXEOMUWKIDPSOYHBCEZHSIADZLZHGKCQDTFWQQMZMJNYSVBWWAHJHWTJNPAXHUAVNXLAOTDLZSVQBWXQEAKIXFTONHIPKTP', props),
compute('m_19_2/6: ${c} GRXAWZOWKFULMLKEYRDGICSWLANBYCRFSVGPKBQQRMHXHXAZFPCZSWLHTEBVGTXYCFTHRKWCNXPFLSGXVWFZFWFWYVSTZVTQKXGI', props),
compute('m_19_2/7: ${c} BLIDIMIBXELVXNSWSZSNENTCVEKXPFAVKTBADQWCEYXLIIZNZNZDAVXJXYFDFCLGATCOCHNMWKOVMISNKDWORCEHHMIDQSSQFTFR', props),
compute('m_19_2/8: ${c} ATUBYITBYRBZVRNIANOEXMCFNNALETCWQFWXHRWXVMZEAWTDUDAGBWXTJHFLIYTOBHSPOCCRMGWKDBDRNYSHNQAFAUVXPVHANUPU', props),
compute('m_19_2/9: ${c} QHBDJJXIRSAHFWDPUNFSSRSGKVMXGTEIUNHYBTRWUYSRJCUGVBDPJSDCTEVKBFSUEQHXIAHRWYLVJGTLRZRWERBKFPLKFRKSJYSK', props),
compute('m_19_2/10: ${c} SVJQWEPABVGGSHJSAEUMWGMZPIWDXYIKCZBBOOHDNWLIYNDIPFXPNQPEKMMMIKYTMGOMHJMSAGELTGMCDBOAHHCGLADKEQMHEEKE', props),
compute('m_19_2/11: ${c} QPCHFPCRCBWGCHHADIFYOQWSHCDXBMNLUUSTHKUNZBHPIZRGKFETGEHGUTTOXMXCMPFPHWTATJVQAXCPPJWVRUTAMRDSKAWVOFEK', props),
compute('m_19_2/12: ${c} LDJKNUCJVPQIEHZITAIJDOBZDUDIZDVOJTVBPHIIGAEPEWVZRIVNNDXBHVIKCHTLNYVZNEIHPCWTWWPBASAMZENVECKKWICMTUBE', props),
compute('m_19_2/13: ${c} MHWGILVXEEABWYVVRZBPRNTFUVJDNSWFBQBZVTSPGYKSATCSTVSIUOUCAHIBPBHHJHGAWLSYLJPGYHXQBKRSIVCPTFGJKPYZWJTF', props),
compute('m_19_2/14: ${c} LQWTQTQMMZJDWXLRXOBKEVWGRDDIYCVWQVCGHHMJPCMEAWDGZDLSVPUENJJNEAMODXUZVLPLGANFQKAYXLEFIDYLMJLJGEMNXPSU', props),
compute('m_19_2/15: ${c} WKDBRCCOOICMFCXPXDDZKVNGDYLLIEYNHNUUQREBWNTFBDRNMRQVQYYZDLNOTTECFQBSSTJPLAXASEFBZLQYUVLIIEDCDRGIUCER', props)
        ].join('\n');
      }
    