
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_4/1: ${c} ZXADYYSIKYIOTFAFSGPXKJDSNSEUXJBAWZTJVFOVILLHGKIKCHMTMWSEJDKAHTOSOHSEUCYRCILPFHBQQEGKMJVTYUUSKYSZEXZY', props),
compute('m_19_4/2: ${c} MFIIEMIHUYCSKFQUUIKSMHLYMFHFQRIBARFKXDMNIYLBZTPTOCOCSXJHNYGAPROBEXEDFIXHUIJKJJMJXYBQVLYNENLRFXSKJCWU', props),
compute('m_19_4/3: ${c} STASCGOETLZAHGANOZNMVITJOZASVAOXDLNWWOGSESEPFOBCUDIDTTPFKUHMRPJWNWVLJAGIYRWLOEEXHOFAAZAGMCVSRDKJKIJQ', props),
compute('m_19_4/4: ${c} QMLWHHLAAYSOASEZPODVBBTMSAWXEDVVGMYWHJIRNMKQBFZZXBMSNJELCIVUMCLNWQYVVLKVIMYFOXBHADNUCCGWORCDONMMSHRS', props),
compute('m_19_4/5: ${c} ZJMIBPEFSNUDUJBXNGZMRPHPCKALUSLBILGZQIWALFIRAGRDYIUAEZNGEMRSONBSYEBGTWNNGBHJUGFSAWSKZCPXCMWOOWROMCMI', props),
compute('m_19_4/6: ${c} GNBMLBPIDCKNJJCCTCNATRCYAWKLEJDPLINBVKWWRRXPZFWQQMSVQHTTBSMOUIEAVLNMAFKFVBLLAWIIJVHQEKRJSVUUTZIVFYSJ', props),
compute('m_19_4/7: ${c} XIQFIJHHVSZZFKRABXPUGLLSNXPWTOSFFOWFSSTSXGWASYMPDWDZQAKSJCFBRMWGKCAYTCXXOKNSFGBDHUUTWEJIURLJMTVJKMJS', props),
compute('m_19_4/8: ${c} YCGNBHNTMWETRWPBGNGFYFYUKXGRLCWSTOFPZNDCRTCVCWZYSPSWLANCNGAOFYPKYSVBTPHXMJEWQBNRKKQDGZGXWCKKMUWMFIPS', props),
compute('m_19_4/9: ${c} XWPRHCCLBRUFVJGSXZADUEGFBTIYXPFVYLQNBMEXCAMZBMOEEOJSSVWDQKXJHPSBMAWDXIMPFSCQLBNAICUWXCVADHOOFCKULTFO', props),
compute('m_19_4/10: ${c} XOAOODPXGTCNQCDXUBTDUYVNNXDXEUJSLHZIQUQYUSMCYPIQIAHNQNWFRNTURMQZKNQDHJJGREXNBCBKDXZUJQNWOPDRVTKSYEHI', props),
compute('m_19_4/11: ${c} KVRMAWYNBLPXKNHZMJJIGXQTWSEHLJFXHEBPERBHFYMSCWGGRJXQERFUPOIASYAOIJINMNIJKJRVIMRFXDIENZUGETWHRLZVUUMH', props),
compute('m_19_4/12: ${c} EJXWPYNYLPHCZZXXNDNLJXSKJTONFEVIWWXKCXROVOJQAWSATFVWSSNYHGWMISHGVGOSCBXUFYDETGFJMWXHFQLKERFJNIKVQVWS', props),
compute('m_19_4/13: ${c} MMXTOEFIJCAYQJOAHEQRQVGZLKOTYRFYEEBFRKGPGLRXEHELXIBRPIGCEITIHNAHTZHTEVOLDUROOQYSGHPDMKEKHQVAKJYJMBXH', props),
compute('m_19_4/14: ${c} GBQFFKIOKDWMNXPHIFIEJPZJFYZPDJLEYVBFAQFWPUDOBKVHFVUKNZOUVLMDAAXWWHVOGCOXQGBWVHTBQPEYXLSTCPOSQDSVAWFO', props),
compute('m_19_4/15: ${c} NBSUOFGXNGZZVRJVFBYARCLRUHHBGKGWOVZLHUNDHGZSDTIGXFISCWDFLREFNHLWLDYFUWPADBUAMUMJJSQMPNMCVWFGWAYJYZAQ', props)
        ].join('\n');
      }
    