
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_8/1: ${c} MALKCJVFWIIAGPCHIZJPFIKCKNWOTPCHMMSVDMIKWUDQPBVXHBVEUHCLDHEZWNNUXTNWRXUKIPLQSTWAVCXTZQHZEWYGAGSURFTY', props),
compute('m_19_8/2: ${c} JFFXPTVDCMOPMSIGKYSLJPDYMBVKRASWJUEAPGCMUDPNTOSPBUWOOSXJKOADUJBMJYWCIDFDADMXHEGVPGOTZCVRQWMSULANDJBI', props),
compute('m_19_8/3: ${c} IGHCADNTFYJVMJHRCJNLMPFDWLEWVEHFIILIMTNRKSORCACGZFDJQFHKUOWVBELPIGMPBSPSUTYXDXUXCVSMNVYWVWVQLKXLCZZL', props),
compute('m_19_8/4: ${c} XUMOGORLCRFBJSJOGDBFJLYRNYSBDJYVZDVYVDNLEMAMFJAYUQUKVGAKJLQMRIHPGPDWBVYBODDBGTGIARSODKROGVUTNFTXJCWD', props),
compute('m_19_8/5: ${c} ZNZFPUFERLWRUBNRBDZNAIJFKBKSMYZIFSUGFFIOPLBXJBDQWNOSCPHLPKMZZIVUGIAMMTPARQMUMIJDSXIUCGKKICHVCBVZZBYP', props),
compute('m_19_8/6: ${c} RYHZAHYGJGKRIILFNFNZQYTKPWCJOWQFOKVHAWRDBFIVKWXIKYWUGOPCAPHEWZTTUUUSGOPJOSBMGBNTQXLLJPIEWUUIFRODUGZG', props),
compute('m_19_8/7: ${c} FFKKHBHCJEHCKECGLQJCZICNVCQDXUIJOOMIIHKIBXDSQAYVRWVHYIAQMYPWXWOGKNYRGTSCTJZNTPELELUPLGLVHJEKTOEZEFKZ', props),
compute('m_19_8/8: ${c} LOOMZQJGQXPPNSOEZVIAWQORVAASLJFCAHMHTQRPWYFXRTCJINFXQYYPSGOCLUJIEYVPBBUCINBUJXHHMOJZKPCCBNORZTWTJVGP', props),
compute('m_19_8/9: ${c} RVQNWUURJBQJZKLLYIFWZXWHQQAMHEHKNRPXXAIDNUOSRNTTMJIQCFXBVQHWHGFTPFHZJISOMEYVVNWGQTNTSXYYFIYQUHDEOZLS', props),
compute('m_19_8/10: ${c} ISOURWSJLESDRRFQFMBJWRSVOKSLXVXOSCFJKRGYQSDVBLFBFGXFGWSVAZIBLVEXERFYKEBNXBKXGVSBIKHEWQKZVUBPPHXIRIUZ', props),
compute('m_19_8/11: ${c} LBAXNICDSIMMMASHILNAJMYZOUTQTBMPKPYHUIDYSHZWDQHUPWFNIDZKCHIIBMUPJHWHMWPSNHMPMTAXZCBXDPYVMNEVKPWTQTQK', props),
compute('m_19_8/12: ${c} UXYRXCEZYIBMHKGEYAPBQSAMQKGORXPVEZUZIATYVVIZKLQOQWBUTNVBBHBIRBZKSOBVAKWVADOVYBSMTUXMISFSRFUAEAURREGR', props),
compute('m_19_8/13: ${c} HBYOBWVINGOBNDONZJYZWAIODEVSCDCLASBHGSRNFHPHFUMJOQXUKTONFBYOHPOGVBCOBWWUBGQZMELVIOYWYURALFZSYVREILMU', props),
compute('m_19_8/14: ${c} CQLGAYECBJVVMWAUEIENVEBCBKBSHBIMIKYXYOIHPGSLIJBDITUOCTTRAZWNJPTMAFMWZIUHLSVDELQPMQOMKRUYBYFCWMGOFJHN', props),
compute('m_19_8/15: ${c} NQNSGEEPFBCNEJSTZEBTJZRHXOFEPVPBSCPERPCHPQBJNTXDBHGJRNSNQEIXAIJHXRJGESXUIAZWFPPYZQWASLFZLECCHSQSCSLX', props)
        ].join('\n');
      }
    