
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_3/1: ${c} OFMBGTPCYXSNWBKVXFTCMHGJLSDAJJUYJOKFCTVHIVIYMTQCPCFZWIOVSSISXGLKLVARQMNGHSWHIUSESGYNLUXEARZJORHWKREM', props),
compute('m_19_3/2: ${c} FVQZCGHRIFDUYCNETDRUHSOUKEJLLWGWRRIXMWWLADTICNHUXIHDYWEXIHXEBATTEWPVRWPBHTJXRFKLNVDFMWLNBIRBKRNDDWZR', props),
compute('m_19_3/3: ${c} RVGWTESUBBZEXCEUOGVAQMLDVKMVGUDWAGXQYOFFPRSGDVHENIGLILXWGCKUGKAPAOPXICPQGONMATSWIJQYRYRFDMVCCYZBAEUY', props),
compute('m_19_3/4: ${c} KRMGGDHGVXUIFEJKOUIGKZLWTULMFULCOOWKVNKVZESBBUJRAJUKMBDVFUTDLTGZKBLAOVSMUXTYRRKWXUIIJTBWKIYPGZBERAUY', props),
compute('m_19_3/5: ${c} HCATIFQQISXMABBHHJWNNQKTXLYETINAVREWZRXOHBUIIFTLGDPYQHTIIYIQNTUCSNSWEIJWHLNUZLWTAEGUHDBDTMNVVFVTHJNS', props),
compute('m_19_3/6: ${c} GZWYUVLTQNWEDTIXLYFIKKNVDHRWGVDKRERDLAWYCCJJOFNTCLFHHHRNIFUIFZXZJBXQHMCDKGCDQSSANBEJRLAJOXOPDZMFITYS', props),
compute('m_19_3/7: ${c} FMGXFVDDPUFHCBANQHJLJHGIYQHRVQWTGYRQOVOUMVGOCEXBIKLBWSZOJKTQBRIDGQGALNWERIFIELPFAMQSKOWIGFQGOIGQENIO', props),
compute('m_19_3/8: ${c} SFIFAUKVXNORCOSEVSJMPENGKVSNBQTMCPPJWEYBCBIUOECDBOUWTCMYFZSLJMGZRPLQTVYWGICPHEYHUWDBPTHXKIBKASZRYOMK', props),
compute('m_19_3/9: ${c} PSNCWCFEMBIWSPDBXNGCVJCIAUOXEWRKNIJDCLKXUSEAPIWDINWLZXEEFXFCQOJFOYRWBFEOCAKGPCRTKMWIOJPNPHGVOIIDQOYG', props),
compute('m_19_3/10: ${c} AFEDDRAXWBFZJFBAGMVALXCJAKBGWJZSRNSDBEVGRGEYWAOICOLPNGESPBXFOEJXWYFVINSRAGJLVACUEYKYTPRQBWCQECEPKFPE', props),
compute('m_19_3/11: ${c} IYHBJDSXGVDPIPDOQUBWYTINKLRQPRHUNOEPBWFWVTGTAKZVVYJWSDEUBFZQEDCPPWAKCDADMRWZIKPPQBAQTSGPRGSSCNUOIDPH', props),
compute('m_19_3/12: ${c} UEDAETWTNIYJHIGLWCHFADEGBSYRDHKWCPOKTWTPSPRANXVCBHBQWLPCTBEXKXOICLANKPWLVLVVVQPZCBLZUEUHUSEOJADYASPU', props),
compute('m_19_3/13: ${c} HMCWGQWDBXMSJFZFTISHMHSRZLYLIUHPKZAZTZZTZBUDVUJYCXFGKAXHJIVJWYOFGESFUXSEDGQZPERTHPOFRTXCPELWOLIEMODA', props),
compute('m_19_3/14: ${c} NRCNONLKPQHBWATAOWHORUMCVERXFOLKMWGMHVPPQKTQIBOODJEFKAJHBHQLDGBPZWAURAAWVGTYCBTYCBZVWORGWATOEJPBMVEM', props),
compute('m_19_3/15: ${c} WPCNRRNGQQHCLTUMQVXBJZVJPHNHJGLYJVPAPRQJIYKRRHBEBEAJXCKJSBDVTJGSWHIZPARTYEXNUKFLSMNIYETAUNBLAYVYGIHI', props)
        ].join('\n');
      }
    