
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_12/1: ${c} ZPIMDPPCHQQNUGPWKUAUVTNCJZVFQMYIDRAKEABSFWNLBFGFQTBGMUVFHXRGFXAUNVQDFXVTUXSNXXZQJDCVNPDFQDQLIZOZCVXS', props),
compute('m_19_12/2: ${c} EVRKQGMGTTCNMPYLOFTWBLEFHELWEAXMOXVEKGOGBTHXTULHXOAGQMILJGWMQSAPPKTZTVXYHNGJZDRQCRQBEQFIJBCRGMJVNSDT', props),
compute('m_19_12/3: ${c} GDSZCMDZOPYITLAAOYBZQHMTTRGTHBDULNFLPURCLXDGLHDABGVASWAFWYUAHGEVBTDAMNRFBQCSILHRTNLANXEEAXVSFJURJWQI', props),
compute('m_19_12/4: ${c} VAVJWOMLQJZABLAVNGNELPDTRPEQYEXSIEARNDZXMGPCYARTRZLGSSCTYIPYJWCPNYAFVHWIVORJSHFPJGNPLPYFCDOSKKJAGSDY', props),
compute('m_19_12/5: ${c} SZJVVSIZBYZVERXNMCMYCROYSNCVOXJLOIQUWAHBJLSJXQJIGOQBSLMDYXQZAJJJHIOJBIHEDTVLPBOWJLLZNFGRCVJRJVJZEUYZ', props),
compute('m_19_12/6: ${c} OQPZYSIBRKBMHRMJHFACIBEXJWPJMAJLEAODJCSEUZLBZODWEQAUWOBYRMIQFDUJQOSRXOJJZQAUKXNVIQKUFXIIHKTOEIIPTKGR', props),
compute('m_19_12/7: ${c} EBZZADCBKZZEEXCBBIIJWUYFSGXDGFJXJHAOZSRXSQWJTCDVHBAQXCVSVOGVCNHJPMONLGTYEZKHIAZLIQOLISIPZHIZXIRILMAG', props),
compute('m_19_12/8: ${c} FAYCSUSCMDXOANITRINAOURZRQDDNIKGPIUNYONBDMZVENMPUNPQLFIGQCGPRLPKRANEOLPGWVVPQGDQAGQBXZQDDBRAUUIEYCLE', props),
compute('m_19_12/9: ${c} HSUMXSPNZKXGCZXGPWUZLVSAPTKEPYPIVXZGQUHWLUZSKXSCAEQVYXVIGVEZYYYJMOJYQYGDJQEGCGJOYDRMTEXDWBVQKVXBLWTU', props),
compute('m_19_12/10: ${c} RCPEBZRLAFBAHQCIUYXAHQJIKWWKILRXBSONGBTAGVDORIZXWQXJAIOQZVEAZUTCVVQUHSUEKSZPEOPTYFJNFLGJJQSRENAWRIQS', props),
compute('m_19_12/11: ${c} ZCFOUAWDMPNKFWFSFYHSEEQKXGDDLFFNFKGBEMMTIPGISASZRIKINOLXCWSJNXBUOUXZNSYGLPZLFRDWUBMVPGRFVMULUSKWNUCF', props),
compute('m_19_12/12: ${c} HSPFCAYXYFOFKCFPTVVCRCJIUOYETPKCASSAHTDXZPJCCBPVINHYQNPDWBUUZAEBNETCRPELCTOIBWJEVPEMMGDNTAVKLESXIHVI', props),
compute('m_19_12/13: ${c} HLZUGLMXELSSYFIJFFINZWIEBRUFBAHVDUJQRDMWLUSNYJTIYDUMHIAOZWANFKVYDCZNPJEBPRYABXPWJOKSHYFSCCWALSAHBAXT', props),
compute('m_19_12/14: ${c} DIEHIOBFPZRDOLWTUSBDQWVWOFQWRWSQNXDJQKSREPNUNXVKWTSLQLYGCKDTFHIROZYWTQICGOXDNEHCBTLLZZITZCXXDGALFFDX', props),
compute('m_19_12/15: ${c} TGHAAFFTPNSKQYFXHLCMWUQKAOMEQXGCOSGAUGTFRDLGZDLSZUSYRCDQSZVFDZJXATPVJYGEDQASIZMVNABHIANTMBJRDSWVGPGY', props)
        ].join('\n');
      }
    