
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_19/1: ${c} BOIEOJUSVFSJHBDDDHCONMZVWHCJEQSTJTVGYYDONAQQWYOPVRQXDSIRNHDLAJBUEMZZZDNAUIJMEQDBHJZSFVAVWYGXRVBPGCCM', props),
compute('m_19_19/2: ${c} QTRBSLLTJGSQGYKYRTJMXQGYBGYWYPMWIUTZZRMVJODGGNWIGJONGOJXJCKQNFZTZOWDIDEYNAELZVAHXPZLIMCVVMHOIYNRRHDJ', props),
compute('m_19_19/3: ${c} LGXNSATCLPQPFARPAUHVNHQAXJPVXFEVLNABQBYZOAOLREZZAXEXWIGSIWIYLFEVZOXAKRDUCBLGPIKPUITRROKDBMVQIPXFOJEM', props),
compute('m_19_19/4: ${c} JEMONYIWXWQURXBHZYBDLLZXGPIRWFWCDMTDYRZBQGKXMQTHQNCTJGFOHKBJWLJFGOEZFNJFTIOIHHKBMWWFBABTSMCVWKYFOPEQ', props),
compute('m_19_19/5: ${c} KAZMYXBMWUKSHYRATVDDHURHZFXSLJGVYIVROXIUTXISHSVECSCOIIZFUNUSWZWANPKYQPJVXDHCHQWXKVZWRBXGLVURSAIVHRAK', props),
compute('m_19_19/6: ${c} HISTDIKUAVUJCABVVWSZYKKIWMWSOITHMDUIZQLYDCUDGEBWLIJAFDMAPGPXCTNUIGCFKXUOIURBCDUJGJXQIZCODKTTWBJHUSJZ', props),
compute('m_19_19/7: ${c} JWTBHYVDUYMKYMMJRVLGMQBEAXHIGPVBUPWTHNEDXSPJSJNJVEAQFXTDKAQOKDFBBAERDCRFIUTZGSMJDFJINCRFSTYDDMBLRIAW', props),
compute('m_19_19/8: ${c} OOSMUGQKTKWBGEQKBKIRTWOBJKNLAMKEJYIFHHVMFPAQWPJDETYWLGIXOOULYGNRWXZUAKVRVGVCFHTPQTSQIOUDNJIFZAUONUHG', props),
compute('m_19_19/9: ${c} LGPTFYTVHYYUPBVROZYZZFZMPSDULUZUHMCQUXESKNPXTKBTGELXPNETQDYFSWLFUMDBIDDSDMQDQBARTIOWCRPIRKNAOWYKYONW', props),
compute('m_19_19/10: ${c} OVYCYGHTGJUZEWHSQWNIAQBXNSBOSCMOHXUKJKCJCFULMNVZLHWEKZFNDEXXKYFJTWKDLTOPJMXURMEFQSOZGJHGILYAXMDUAAKP', props),
compute('m_19_19/11: ${c} QHMVNZOLBDYMXZUQAXTOQJORWXODFTUVJPOASBHTEAEWRKURXMLYWIUIMDCEMDXHXRKRLNJXPDRTHETKJOWDDNWMYEXABWLYWAXM', props),
compute('m_19_19/12: ${c} KKSYUQDGXCDSRXSSREOSXCIABIHKLXRLCNNSZDOXAYPQEOPSEPXLTECUQYVUNPYZFIHADUPRYESOFGOWMCQHRYAMZIPKZRPZVKTY', props),
compute('m_19_19/13: ${c} DNCHCSWLJLUTZDHAWQUSFKJHBGQPBNQCYJAJGFQMBHLASKRXXQRQOOHPJPEACOFKXONXXZHCUUNNYPFZDETHSYEZUTWBFNZMQLUP', props),
compute('m_19_19/14: ${c} VUWBNMMSVRZVEKLAMZVPHWVAQCCQDHYPERBXXBDYQIRCBSRFXYYBJCIRHFISOAQPCNZUCJIPPIRWEHIIJPQZCFMUKVDJQHLQYGTZ', props),
compute('m_19_19/15: ${c} WCBFZRBCYXYUYKGGMIVFKNVSNYVVWOSGOSPUFAWJXADXHQCCAGSWKGSDSAIBSFMPCNVNNOKSFGWEJCNHOMPGJGEHDNCWXJYYIDHF', props)
        ].join('\n');
      }
    