
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_19_20/1: ${c} NUUUHJHGBBCAIMAPTVSXSYCXTKEMALRHSQMVVHZOVVWKHPKSUUDNCSQKUFFHBFVKLTITOSOBFGURCGRBBWVEMLSZLCOFJHPFYECD', props),
compute('m_19_20/2: ${c} DJHDVYALGZRYVMZJUVKOZJDXXBYWNCMMCURCEEQEMNANZTHXOVYZXNEWOQJDRYPDQSRPWHJILWQCAFBFDPDZJAHEHXNRDCUXTWVA', props),
compute('m_19_20/3: ${c} WFQFOGMKSTFRIBZEMQCSJABYMUAYGLADBNNNJCAUVYLZQYTMTCRLFUZDXLGJTGCGGRJSHHDBBZWYVMEBGVKRXDVGNUXGXJPYFXFA', props),
compute('m_19_20/4: ${c} JYYRXFHUKIZLHLHIDTIKVGPAEJRADHCVUJVKLDRNJEWVGKXHUOLZEUGMLXEMGYTJSVSPWMUVQKQSYQTKOGBXAPTFKEHIWWQWXGDQ', props),
compute('m_19_20/5: ${c} RPMWQZKOQUWJEQJZTZLPKRGUIGUNBQEMNZXGEAWUHKDQGKZUXQPBBXIHDOTBAWNKOIUJFEAUYFWZZOQTNVSMBVLQBTYBTOLKMGQK', props),
compute('m_19_20/6: ${c} RNFQLOKLLOTSPEKKQBUEOXRXYAAHUHMMHUBOPMZQRHHJGQKBSXNLQTRGVHHXNKJRKTADXZWUSEZOIKKTMMRLGJOEABZUBVAAEYOC', props),
compute('m_19_20/7: ${c} YVXSCNECSFEAEKBFXWWGFUZEOSVQFVDUIFFXYWJTZNUIODZVWMYNXMJFGXLORRVHMHNRNVOEEYTLAMWJASEGZGVEXNIMKGRXPLIS', props),
compute('m_19_20/8: ${c} DCMJXFWXUIANBLEPYSOYFSOCIDBGLLCTKNWPZZYAKMXLYVHYIRRHOGUQJQIRJBNEIDUUERAKSWMACOOUSGPFTTFRMJQCBAYDRKSW', props),
compute('m_19_20/9: ${c} ZMZEAOHTUXBZDTRYDODZGNKCUGUZMWBDPXMCQNVXBODFLABXRQDBTRTSAYOCUZXAQBVZNJOVTRURUXQKGHXOJLTWVAKHEUTLVFAL', props),
compute('m_19_20/10: ${c} YOMVWYSGFJEGLPDWLCSPZQHNXAOIKQYQUETSXUYNQXNVJPPIDNIHAUWVTYBZAQZXIGHBVNVCXZZGLAKJXQMBZDNZADFLOBWTSRHR', props),
compute('m_19_20/11: ${c} EDSFUVCZVPSRZFIPTLAUXTFPSQAVJZJKVCTUYRNKMKANHGTTJFGWSFDWHJSDGWNWVOKHXGMTITKVTPRPPTFVFNAYVATQTROOAMBN', props),
compute('m_19_20/12: ${c} OCPLSDTTPNRLSKBTMRZUBSDSBZDOVYMTSWKOWZRQRLMAQRDOXKRQPMFLSFKFUQTSLWTPXAVPJKRXYTBCXDIUIBQEUNZCHFJAEYBD', props),
compute('m_19_20/13: ${c} ABWGNPZQSBUJTSMDMFQSLTQRLDTRREMGWUUISPVRFUYSFYVFSUCKQPXUFRXGEDMLOJMCEKWGQXWBAILKINLOXFPGOASIFNHTGJCI', props),
compute('m_19_20/14: ${c} MXHBWKBITJJHCGSUMNPMGICFZCRSWRABEGJYZDCSHDTXWHHWPHMVFSURZOXWEUMPSGNRWZBKWMOAVAQGZUMUVXBDTHXSGHDMWCJT', props),
compute('m_19_20/15: ${c} WBNNKUEJPZJTLVNVRWUOXPHEWEHOEBSATQIURBYYTYJMWUZSXFAZJNBDFDGRBEZJNHJACSIOGTAWBOASNEPGFOMSGBDZGDNXRSBY', props)
        ].join('\n');
      }
    