
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_20/1: ${c} VYDMNKZYEOHVKEGPQCINGEAUBINEHIMXJQQFGSCLAWVNBHDJJWLHWLTXTRXCGNOFBPNKZRVGDNNFNBSXDJPHZPYZLBSHSAJLXHKN', props),
compute('m_1_20/2: ${c} DJKGMCSVKYWJRRNNIRMHNTALSXIIKNDPAPIHYIQCBTORJVBMVRCBSSMKSNTQBGCXWUHDOESLWJRRLZBRJEDKKKDOTUDABBYAFUPP', props),
compute('m_1_20/3: ${c} TDPVCPWSJQDEWSAFOCITRPOHDCCFRFXFUNNYJWTUARITFJSQQVFAUREUTGZXRMMTKKACFKINCSDFMLYAHAEMALRLWHTOIFOKJSPM', props),
compute('m_1_20/4: ${c} UYDNUYTBALIYPXVRCEACTHKQHKCMVSBGBBBFXVBGSOJECAMGXLCFPXXLEWCLUWVVOCKMHFHYXQNDNIJRQGPMBPQYAFLPCGFRXXWF', props),
compute('m_1_20/5: ${c} AGYMHZPRIUFEAREHKFOFINZYKVXSXNXSSWXIQWVFNXKPQLXAXLKWEGPESVXIJKTNEBMBAUGSHCFXAMYWZYWBXIPERXICDNIMZBVR', props),
compute('m_1_20/6: ${c} WDLLVGADPGJWJBMWSLWIEKOWSXWBVCHOUWLPMTPHNQSEQQCCNTGSKNVRQCUFGNFIQLMPOFCSCPHXFLZYYTLLEVPIQOVZJRJIZZHQ', props),
compute('m_1_20/7: ${c} IVANCLXIOIKVCNOLCMQTDGYTBJSHJHLOXKOUTORLVMFZXJUMMZJHXFWBCIKJMGSZFROOVBXEDSQAVGXPLWAPRSXILILKMLZCEODD', props),
compute('m_1_20/8: ${c} TYUYXBCEUUXMPVTPQMBGNRYPCHHHNPOUDYGUXYXZHMUMHNUOSBAWGEWVHUNJXCGZGGEKJSBPFWQDBSHHMOVNLPQKSAJMGSDKDPHU', props),
compute('m_1_20/9: ${c} NMHRYVKQVFZCVOLBOJIZJPVRKCWBGALYBIZUJOOPXDZRCIAYIDDUASMQOJGAGMMSZNGWSFGZYHSLWGRLORDUZDTFZRFCJPVPBMQV', props),
compute('m_1_20/10: ${c} AXBZEKTMUCVUPXGLOWISGQQPMSYKKTBUYURUNQMNGRYSNLXTHEPHIXIUVXKSCLKMTPZXOKPKDHCVWHTSNRSXSSAJZJCXSSIONFZI', props),
compute('m_1_20/11: ${c} UXGXTAASIFXZNIDMCVPTFDMDNBJXCUKVHFXLVLPDELOTHOJGRYNLEMQVTDHPNGXWYNAHKAWLZWMNHUGFDYOEBUXVYVFZLSVFIMFS', props),
compute('m_1_20/12: ${c} MNNYQSKZFCYHLWQNVEPCQXMOZNCHHZUILDEWBNEVADILHQTVFHJPUBRQPUNZRFUULHZGZPVYFVMOLRMHNDQZDOVEWJOISOKYXSUD', props),
compute('m_1_20/13: ${c} PDJQMWWZWLJGFTOLKCAJWJWLSFKBDRVUEAEOAPTATONJJPCWHLSRIXCCNFIOIUCVWDBWWDHDOILJSAZPRVPCNEYUHLPIQBIPTAJQ', props),
compute('m_1_20/14: ${c} YGBKUGGHSLSCFBVHNTLVKVHKLEYQSXLMKHTKKVNYANSSWHCVVJILRNCCTSCDVOJFIUWGZRWJBKRAOLRQAFYWVUYPUFSWCHUYEYFU', props),
compute('m_1_20/15: ${c} FSMLACPZCGJQOALCLPPJCWMNNUOPETXBQPUATDLAUTUCTHQRFLBQRMMPPOXHZPTWPWKKZLZNQIBCOEBXCBROUQBUZQWIKZXBOELH', props)
        ].join('\n');
      }
    