
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_3/1: ${c} SYYOGMFAWZCKNDNJZKTROHWUKBDWZYSVDQCEFWIWSBHDALGNVCTKBQDGTQQZDWNMPHRGZBHALQIWABOEYDGSZSUZRXHSUKSMKFUP', props),
compute('m_1_3/2: ${c} LPWUIHJLVVVWEFTMLVDYBWFSYXGTUHQWXQWTEXADMAYHAAMPZFHJPNIMGERNWUBURVFXNGJUZEPBSMJDKTFMPMIBVZKVAEFFACNP', props),
compute('m_1_3/3: ${c} XXJERJKJKJNHPNQNGXSHPZKGBJSBDVJJMCIUQIYPVNADEDWZNSRLCMQXQQJMWZSNBJAEJCBKQTQLNTVMIIPASDAVICHEYIGQCPEW', props),
compute('m_1_3/4: ${c} NNZVEYBQYUTSTRLEQPSAYPBSSXXIDFRVFTZUCOGNUGQENJSTNEKHNUQADNUIWNLCVVRWBBQWRUQIHBFMDAMQYFWUQMZTVZHCJNYG', props),
compute('m_1_3/5: ${c} ZSQCCEKJGFVZIVORHNVODEONSDCTOQOOXDISNNEMLLKMRYFOATFLTIZRGKGDXYQQWCXRCNZMFDUFDALSVTVOPLEGGDZXFWPCZDSN', props),
compute('m_1_3/6: ${c} VPXOVNNVKTXJEPMUTZOWYZWVUPHBYHPZYPBMKUQGEGSJLLUYHVVRSBQWMKYJIWGLMNHXULQRVEPAVFJOXYBUPBHQNAQIEBFEVTUN', props),
compute('m_1_3/7: ${c} DRSRIWFUEYTKCKYCKMWYYYHFNZVBRBDACZKTTNTVWCJJNFSDBUNDPBKOASIERCUFGUGFDYLMQXBDOIMRVSSOUAJMZFALAXQOKWMO', props),
compute('m_1_3/8: ${c} MLQLEYRGRZRDTGNCXNNOWLWQOYOKBDDATDSAPGFQWTAEEDTNBMCIZWSZQKJWLZYOYEJXKXMIJNFWMMIDXUMXTPCEBCRELUVGPJSU', props),
compute('m_1_3/9: ${c} HAMBPCVFYTSZCXVPEFSZXOTNFWQAGMUEVYRTFFVRNXYURCBUYPUBFIRPSLOWSBSIDKSOIJTAIPJHZGTSWWPLPFSXGZFIKRDKDHSM', props),
compute('m_1_3/10: ${c} NYNCJCAKPBAXFUPWYYJGBVRWYTIMBGBIIIZIZSNJBTVQTQXGGXDHPIOZGXKDUYYBTVHOSPXYWUQFGLUNWBROMTYKKGGUVMZFFTGD', props),
compute('m_1_3/11: ${c} FXTKXXJNWOLOKQUBXCDJWTJWQCGCZADBGMUVXGNFXNPCZJLXNNYQTDLQUPYDXJXZYLFAOUEPMQJOQBRKGHGPLJFSYHDCUNMRRAXH', props),
compute('m_1_3/12: ${c} CHMYNVOXOEHJWLBTFGFTQLOPJEEIUWNVBWMMVOFSQTBJQLTGFYQLLQCOSPQAEVAILUZQSSOEHVMGXTKJQNFNAQJPIYETWNSELBOI', props),
compute('m_1_3/13: ${c} IKLJQQEEPLACAYBGJGVMYKUFYZLVIQZWQXZDISNOLLQYDHKTAGFCDAXTNVMCDKZIMSSBCIRZYJXMFRXPZBNJWIJRSMUZWZUISKXF', props),
compute('m_1_3/14: ${c} LQOARXIXPWXSFVQOLTBYUKUFBTHNGKANGHQKOACZSGHKOXGXNHQPHIAHUTXAIZVMQRRBGSDXIPCUNVHVEBEZWSKDEJFIYXUQRPIL', props),
compute('m_1_3/15: ${c} YJHLQBTCSVXPAFSHCNUGGFHXZULMUDZFMCUDKRWLFNUMDCVMGIKPUBZJVZKTAHFNXKGKVYQXWCYEYJSFJWIZRMXHPIIWMHSCSCNT', props)
        ].join('\n');
      }
    