
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_2/1: ${c} TAHEPEJPGQQRAWQCVKOBTQCMHPMDMRKPXKBHOTYGIKXQLOEMKNBXLSKYRKWNCDCYZVNMPFGKMEHUWWDVKGSUVBJSUWBVGEAEROMM', props),
compute('m_1_2/2: ${c} YIMIVEYOIRDTZCKYDYVTPSIOJBJPNDOKNLMMIVDAZVLNKGUBEULSAZKWKXUGNJGCBZSMOQNGHQIRPWAQLDFOWMHSWRXRVHFTBUOZ', props),
compute('m_1_2/3: ${c} JBJMDBRHSEOMADOLSFICASMDILCGLDASWATWMWJFDZXPNQWDFOATSGGABIHXKQDEHYMNPSVLIAEGVBERMMEOPJFTKTRKILWFOYBB', props),
compute('m_1_2/4: ${c} JYXJQWOIYYTPFTVIWUEVHWZPBLDAHHOXNNYIPIRZVATKOPRSPIPWOSWGXJCEASRVYYDQDWZOLPIHMZFZASVNIYPTOAIWPCJWLHLH', props),
compute('m_1_2/5: ${c} BNVRVPFFZPKEDRVTUMWLSCPYWTXGPIITZRGMUTPOJIRDNUDMRKOJCUVFWDLWLBNPCXTNUKYFKRMBQSIZNYTLTOEGEONQKNSMNGYB', props),
compute('m_1_2/6: ${c} RNJLKFVLNUTTEWHNPXEUSLHMNSWRWOAPETTSTQBZBNDZHFCSLBYCSUBRXIQMFSYVSWJLNXRMHPFKXJRFZAXCHPEEWRRHMTTNTXLB', props),
compute('m_1_2/7: ${c} ONRZXEDZCSPGCIMLDOJSAIKOALBMGOELANOITZBDUDLVLICQGTIISQKPXTEBRJBIRHJHCKEFOANAQZUGYKWBIUNCRGTUBZVDYRGR', props),
compute('m_1_2/8: ${c} PRNRQCAIPQYVINLCUMDRGGJUKXFZDGMTSRGKXOZMDFFJFIGMYDDHDIVGKTPUHGSSILSIYXPULTIPJOBKRUZDZSKKFDZTQTMZXENI', props),
compute('m_1_2/9: ${c} EXKQSEWXWHLYERRAYAXUOYWAWEIRRSBJOCWXJYKPSFLPEKCMMXSZJEIERRVNVQPINBGQEKYZSWNFNDTZOYUFARYSUBCQDAXGNVKB', props),
compute('m_1_2/10: ${c} KPHZMQUBGOMFOJFXVENBUTPBPNMMEKCVXZMZYNKKAGAWAPPDEZHFKMZTLNLSWVIIXLGEMQAMFFZZYYXCDWNUOENDLCZYUOZTVUNI', props),
compute('m_1_2/11: ${c} PMDBHBIJFCAUAMEUYHBOEUIEATVGJEINGWFEESVSAJBELJQVNDDVDZTZICJOVUORTLRQGWJZAMWRFKWHLAMEZRIQTKTCYCZVURLA', props),
compute('m_1_2/12: ${c} EHSQNJSSLRBLQXOMDOSQPDQUISQNGZJVDTCSTRJETYKYYTZRAYEAUPWUMJMQNMBYUEAASQFFGGXKSQUGAEOQOBOWWKPZYQJWKDNI', props),
compute('m_1_2/13: ${c} YWRSMQPUXAMKRDEQOHSXDYRTINRLAYYCSNNAXQTSCSVNSYJMLPVPXLNKRVMQWVRLYNFWESFHYCSWSVSPICRGWCSCEQXSIDFPACQB', props),
compute('m_1_2/14: ${c} UKNZXTFYFHIXAUTJCZGDGJWLGLUQYHOSOOJUGZRDBTRYBGYGGOHGGAKHWUMGNJCXQXKYKASNODCAYIHMTHNYPACDFXCVZODUFIPQ', props),
compute('m_1_2/15: ${c} KUVVUXMGYJFVKAVFVILVLRINNWCPKESHCOPEIREZXMVXLKOJWFKHEFTPPFKNVGTNRJWEZWTECOYFVINFEYGYHHLRBRLSDCSBIPJH', props)
        ].join('\n');
      }
    