
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_8/1: ${c} JCSVBBZGDHZKFARTFRCYUMOSJRSFYHKJIAJEAAOIROLXFDTHTEINOWPLPLSMDZHEFMXNGEPNOGOZHEXBAQRUQHQGJNCLHUWMWNLD', props),
compute('m_1_8/2: ${c} HPDQOLPCPBDJNRGVDAMTPIZXFYXTGPCHNRIWZWACECTFBEXMRVCATNKDZOYSXCYKFSRLDEDLZHCQBBWLPSAQWGBVLMYHBDQUMTHS', props),
compute('m_1_8/3: ${c} GRFBOAJMOFVQPJFJZEGXCLALFZMXVKDMMJPIAKZRWJHCUKYHULZRWSFQXMHARRFYDSNCZOOXQMULIHKLPLOJCFDKQJTKWUJNANUU', props),
compute('m_1_8/4: ${c} PKUTIJPYTQJCEAWXLHPUXFVRPXYMULLAYLANAKEACUEODELXKHVQIVHMZJSSQKYOYFRJTHYEMPNYYMGNLOGFGFXRAWGSHBMLYKDI', props),
compute('m_1_8/5: ${c} LKZARLWEZAJWPBIGQOTUEYREWOUTCDOUDGYMTWRGKQYSDJRFBFTKMHJLQCWHWBMCHAEVLBHMOWPSMRVGVXVZXELGBYITISXKPSUA', props),
compute('m_1_8/6: ${c} PBMYGNSGQCXJVCGYPJBXQZBIPWLTSWVQISTWZVMDXCDFHAZWPPAWTLBYXPOEHGWRMGQBXYSMIVNXQXOMCPRISXBKSMNJKYAJZMEF', props),
compute('m_1_8/7: ${c} LDBSIFFCSIKZOLKUKNVXVSXVSRNRYJJRYAVPEGWAOBGPOROMJSSAGMHWXGONLQCEKQZONQUJAYOIDSXGOWSGVWSVYOEQZWYMPZBY', props),
compute('m_1_8/8: ${c} WRXRULOCLLUTCCLRTOOLRHSRBIELOIBCHOYGJEMTXQLPVNIHMOPESNCUMVCJBHUZUFGKRQFSMZBCNLADFMCLQURPBPEGRZKSWSFQ', props),
compute('m_1_8/9: ${c} ZFKDQVYENEIXCJHMSCJBLFMNWOHZFQULBDVOFRMFDZJVJSEXTMNJUZFGZHFDMGOHXRFQTZUJUHGJQOKHUSUAGWBZTWONESXBIVLR', props),
compute('m_1_8/10: ${c} OJODETZRKCHBETHVMHKJPIWBJNOGNRPCRPVVHPKYCBYFCGHOGAGILDFJSLZPJGGEDLDDICPVFUHCQWXPZFGECFEPNCJPBWLWCOWC', props),
compute('m_1_8/11: ${c} RRBWHHQJMDXPLTFLXOJUDDMYTDQHCVBQZPPJJBWBBDGIXOHYKCPOFKHURREQYAQUJVSYFWVOUXWHMSFSIGIMKVXZDTXCTWWDCQZC', props),
compute('m_1_8/12: ${c} JYPAOTELDJVINKFBCWOTMPPRPJCQVTRWGLNYTRVEOENABYDGQUSDDNTYZKKCOUTCRNSTRQUWHEMDYJJMIQWABENJXQCKIPKMHBVA', props),
compute('m_1_8/13: ${c} UJXTBIGTFGJKIUCFIUNXOBQVQHLGSJKNZOVHMAJCWRCIULBUXPIASKKFLPEMIDBOWUCHPKTMRURFCJVLYAMLNBOSRYDTNTFPZKBW', props),
compute('m_1_8/14: ${c} NWZXXPRPPQWMGCMJRNIJQLZXDOALPLUKEEGSZWGTNAUHOARHNWTLSXWYXJMLKWJOHBLFFXDDMDXQTKEWCLQRWIIQZAEURQEEMGVC', props),
compute('m_1_8/15: ${c} TKGJWOXBZVWGMESCNFHZJJCMXMNZDSMEBNOXLHJYGWGXHJNLASLIJBXQYPIBMVUIFFKLKDLNZAPRXOKKAAYHIEJDVTQHXKGKWYTP', props)
        ].join('\n');
      }
    