
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_7/1: ${c} JHGOQCRSUQNOULRHHOOJRYWHTPRUZSEGNXZAWUOTJVCCAPBLZSCHXNTFBZLBJKODYFXBQBYGJMZPZVYXYSOAJKYPMELELTIUMSNL', props),
compute('m_1_7/2: ${c} QRZGHGAGIECNODRTKRNKQUAKQTHSCYEAIGBUNHRAKNTGCEAJLDCGQRGFDOFZAAENQESMNUHDLOLWJSVCJTHKBRXQPOFUFAIPORUA', props),
compute('m_1_7/3: ${c} TYXJLAYOSUCAMSZRDGCMQASNEFXTXWTWJRBVXIHUKVRYVBDSSSAXTGDWFJGKQDRYBJJQUYFLMMBBOMRNKLUFXJMLNUFYWXILGWBG', props),
compute('m_1_7/4: ${c} OOOLUPJGMUQYVZIGKNLZGXBQXIXAEALFEKGZRNMIXRJZYCXZTSVZGRNUMVNTMCFYHHPHTQJJWYHUDAANNMLNWBPDKMVAGQVMYTSV', props),
compute('m_1_7/5: ${c} SHHOMSJCAAIIXVQKKBZFXEHUILWHMOJEFKHCQTHSTNLTZJTDSDKDUDEQLJDQJUWVLLDPDHOQENRXMCIFPIFRRDPSMAYTHLNPXBEI', props),
compute('m_1_7/6: ${c} JFPAHJXOBJARDAQYWFFRQYPACYFZDEUDGXQHLBWQFAJGQEEQJLMQUJPZFDALXDJQXTCYFEWYZPZQTGFWMQKRHPSZBODWVUEKKMTL', props),
compute('m_1_7/7: ${c} LERIKZRMYRJIHAXHZDAVUTBNWQSVGMECOARRYTKSDETRGEDUFZSDFNTYSFVEDEWEWAJTXYAFXVNQDZPJMKCYHAJHSXFRKVNJIPRC', props),
compute('m_1_7/8: ${c} VNQHRIFYIHOMGKRPWYKLYDEKEEEQEMUQAJPCPEARDXZHWZRLOGZDQSSONSAJSXRKVWSQMLRXHGWOAFKHYRGULUDFOEQSHUZPSWVZ', props),
compute('m_1_7/9: ${c} EKFWLMXFHBLWFNOOTCGOGWHEZWDJALDJAUDOSACJWGAXYIHXWIEGZQVRUDRIWCTSNPZBYHLWSKLWQFFNMXIWEURCQDCSEWCBUBTJ', props),
compute('m_1_7/10: ${c} OKDHKYYRWYLFTFGTSNVAUADXDWSNMUUYEBSHAXDJMMMCUEDJVUPZXHGNUBGPCBQSMICYKGGEBRHCHTZAXXAIIOBKWQVYMMJRDWHJ', props),
compute('m_1_7/11: ${c} RTVLKXBMFEYDSIHXFXBOMYYBQSHBKNXMCSYGHAMXBHKGWDSDMMNKEONAAPORCCGZAHIDCFQDVXAWUALGRMHTHPOYVHPHVBOSZLOK', props),
compute('m_1_7/12: ${c} ITQJGKSFDJRMAVNJFVIHYUPFAYBHADMLPCTQADQZOYHOICQHGEHUVTNIHSGPHHJIKEILJIMXKKZDBLKGSSHNKSRANQUOUGKIICIQ', props),
compute('m_1_7/13: ${c} AXTMNGCETLVLXFUUJRWJJASKOUIQYZBFBCEVGMAHCWOJIEFXQMOWYDHHCQXNULYKKIHCIUYQOCSBQJFIHWHMPRNNLMBFXSNCETMZ', props),
compute('m_1_7/14: ${c} GSFZJNPUPDTGGGPATTRDNBHPHDXDXECDRUMBIIWUALJNBPZFUVUSUDYVMAXWWWQVHJXVVAYVXVVHGSUWIDWHSYPVUXPZOEPSTYFU', props),
compute('m_1_7/15: ${c} QAAJHKSPONMFQRXHWLQMXWCOHRRJHFFAWFXUUUGIETBLYMFUESVCPORPUHBGIVNFBERDIPPMVSBEFGQLCCWUAMFQVRYYBXNHOQFF', props)
        ].join('\n');
      }
    