
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_9/1: ${c} PTCZEVENDUJUWATQKNCSIHTGSFMZWFJOVBBPDACIDOFGNHCQRDJXMSKEPYBXEAAQICMAJCKWKFPUWOAQBLFCNTVNLWZBMJCDGKFZ', props),
compute('m_1_9/2: ${c} ITLQKSNICDFUIKLLCFTEPWYMXXEGESRZMZTJFEUDLTFKYAKJAIUMITHQSDJGAITIJHTPYCDFMFELUVDYRMASBQHMOOGIFNYJPNZG', props),
compute('m_1_9/3: ${c} TDKFRQOGBROQLOGDXWZGAFVAIZIEZWSBKPVTZXCWUDMMAHRVUVVUYVLOGXQKNANKRHRBXLVKSPTMDHXEBPOKHZIGMTYILBZYOBSG', props),
compute('m_1_9/4: ${c} EAHLSSSZKHCQALIZWQEJQBQZSVCLEUJDCGMJCUPBIPUGJZUPJYISTQVORKEWVYPCJRXRKRLQAVJETZUCGXGBWZLVUVPUGITZUYNP', props),
compute('m_1_9/5: ${c} KHRXVMFAZUMBIFTDRNXFUWCLGRDCULZCSGSTXHIRZUXLSJVOPWWEKXDHXXBJCIJUSWVBADKVAQALRYQYDIJJEUVWWRELLJIPPMDV', props),
compute('m_1_9/6: ${c} IUOGVZSXKGLKAONBHKUBGDSWJTBULXARAEVLKADCLAQILVJXELSBMHTGTHDJISGEPOIKFXEPYUGQRERFEPCLYUTFDENHXTBQLVJW', props),
compute('m_1_9/7: ${c} DCCEPVRCUJLZLJJOWITUHJGNYPLWIEPSMQFQNKTTLWTVPRVZOEYCRDRJDEHKUMTZIMLAGDJRWQWIWDQTYXTGQOZBUBFTPVWILULQ', props),
compute('m_1_9/8: ${c} YMTMFIJYFPBAYJYECTRENSMXCZGGPEGNHTTOHDWSMQWORMLEHAEZHRKMMYYWPKJYNXEWHENYNQMDDVBFLIEQQSMPSXVKHMAUGFKC', props),
compute('m_1_9/9: ${c} BGSUBLAEUXADMURPHDECKBPBWLVTLTEHPGRVWUATBYEMDBPSPTUDVDBDMDRMNXFGEVIPWADQIPUHYSFWXWVKDFLGLSOZRPJBAFXQ', props),
compute('m_1_9/10: ${c} DIWCCKRWFHMEMCWDKCXCNTSABUXKXWIWSBGSTRIUACKJOOILINWRTSKRQHDBGVHUHMXGMFFFRTIPJHWYUNUJZJVNKTEVIPMYAMLX', props),
compute('m_1_9/11: ${c} JJSNSCPHVMCFZKOXOGZPNQQBNUNQCFZOOCZGWTHBVTAVIVTWVFKKTEKTQBRRRGFWJXCYABPPZUDGXTHFXNINBKPQMSYVGNUXXBMP', props),
compute('m_1_9/12: ${c} RXFKWDSOPPPDZIIWDEEHGITUVMXYKJQZSWHCTYCWNSQRLGCYLGLOXCTXNQBGSLHOPBWHDJWXKBHQSEZLVXBSZUSNESFOUFEFWPRZ', props),
compute('m_1_9/13: ${c} MEEDGGUIHONDIZULXBHIKFTYTELAFPDUZYGAYCNZGJHZSSYUUQFCVYRHUACGERAWHPRQQBZEQYMFLVMMFUHEWIUZXVYCXVNQDEVV', props),
compute('m_1_9/14: ${c} YLLIWSGQJCKUHFXIJPLTYSOWKLZAUIVDADTHYPXZCCOIEOHOVTQACZLKBFIDLTXAPUOAAETSORPAOECPMYWMKXHUHEQYOXBNRCMO', props),
compute('m_1_9/15: ${c} LGYJEKGGVZCACLJRTRVQAILPLMYFPPJWZHLBFDSTWLRFBGJYJKTKUKUSZVCZOLZZWSUJSKRCROXORHQRUEPGNXIHBEVYKICOZQFE', props)
        ].join('\n');
      }
    