
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_5/1: ${c} WELANYWHCLYJFOKFOYNBORHKJWNGDLSVEXELGDAQTPLDQLGQXHKBACZFGKNFITKCKSRAFCNFNEPTAJSCLVACDELGMUFITJJMCGRI', props),
compute('m_1_5/2: ${c} AAIXFXKWKKDLLKBRNLYMZJYWHYOODKTCBPVVSWYSXQGPTCHFNSCVRVMCYHODKHMEJBYHLZVHEBLEBCKRIPYFKBPZJXFZMANYQZVJ', props),
compute('m_1_5/3: ${c} EUPFNWTYIDWUQMRMAGPAXUKAPTGRTJFERJVXZBEXZPNVFCZFIJLFWCOQEIDZDLUZJZICVEGKPFIBPGNJTHXJZDOQRIZDBJBKJUKX', props),
compute('m_1_5/4: ${c} JWRPURRSFUCEVKZPLRKODSSMJBMYLUYAFMYURWXEQZQSRCFPMZYZTLAWFUWHGYAGWZCOMPJOXDDAXDVTKGQCDIPMZAPNMKOBYZLM', props),
compute('m_1_5/5: ${c} AGLNUNAMVGPSBUQUEVOKDGPMGMOBRTXQLYERFGPUDMNIJPZFSJEWZIMABJBQTGRCKDMHWLTVQOOCLYCKXFHLLJUOVLKNJZPXAUYY', props),
compute('m_1_5/6: ${c} OKEPWJICCWRYNYTTJIQINVLSJAOUGBUDCHBUAGMXVTOCVWIQSAQJDYENGXTPJVAUKEBGUDNZSIJRYMZOKVWYAQDPEPHXLWGOCWSX', props),
compute('m_1_5/7: ${c} TBOUIIXZRZXAWWHLCXDWQKSSYBXYWLBFBYWJGWHDDSMAUJAQAMUXGLQHIJSQNMUQBAPDAJLZNFAHXPQPCQRHZVESOXANWUELLAIA', props),
compute('m_1_5/8: ${c} UIYTFJQFJKVOBRUDQPEQSUVLZHEDWSLMSVCVCVIYTNESBDRLLYELZXMUOTLOZFUQSLLMMBTXOBKQNELEAATWHLRYXREHLCCWCHLO', props),
compute('m_1_5/9: ${c} HMWRBLFIXBOYMKHQVQKEQAKWRZAEHKPCZXYXGDROLJBUPEKADXNXJPOEVVEMQECIXQPDRIDTJTRTTOXIQVZJLKXCVKQYOFCRHIXK', props),
compute('m_1_5/10: ${c} OAINIQBFVSDTCYSYOWBQQLTZNRMQKRORHKMDECGSPBUOQXAFMHRKXEETVLYJRBERBSFYJSAZQOXLAGYCUEEJAGIJTIVNWDIPXDMP', props),
compute('m_1_5/11: ${c} WNRZEWCOEODJRAVXHFMKKCVCXQWDXRBKZZQSSGNZQOQRFNGMQFICEETCSKIGRLMWSJDCRIEIVINXVHNPONBETYQBRAJOGIXVGVAX', props),
compute('m_1_5/12: ${c} MBRAKQECOCGEVJAAIIPSWRILMDZAGTVXINTJKGNDWOULUQRYJRGZHYZVZFLTHYUVUMAQCAPBEGPZFHGJZYPNCRATCSVYBSHINBMT', props),
compute('m_1_5/13: ${c} TTAERTSVNYYPZNDLWSSCSMSSQUVXOHTNYLLSGTKWURHQXTZYIOKKLOVRZJSQUNHAIMFDXRSKATBAAPHGVWEEDFSYXWRTKDVIEJUH', props),
compute('m_1_5/14: ${c} WWVEFIINBGBIAHXAHICTOMFBYDKKLQOEGPVFVLZDICETEFKOKWALHGBMQSOLTSFHNZACFPCXHPYZQZOBUSXEEOVIMAPOOJVBQIHB', props),
compute('m_1_5/15: ${c} VVCVVSTXKFCDFMCMDDXVRKOBXKJLWZOBYGWDSAZXIFRQQKQEKADXXBZGJEONUQEPJRIWQMUDANPHRLSXNCKXZCUJUSZVROFADQIC', props)
        ].join('\n');
      }
    