
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_18/1: ${c} DOGWJKKLSGRVCFWXJLKXZMAVMVOLTCGCYTGRQIFUCJVKVROCSCIJVEJTFKPYVZLCBTJIGZQEQEHUMRVCDYBJUSZZNQMIRWTUFIDG', props),
compute('m_1_18/2: ${c} PKJGHJDZJPJMHFDYEGOKTKNZNMWGSTRXJQQYLZZNYHGOMPFQYUAQPHZIZUJDEPDYQDBEWAKWCYCGXLXBLQEMOOGWVDRHQDVSXLFX', props),
compute('m_1_18/3: ${c} ETWEVDLDLWMMAWABGIBMPOUEDGJHSHNFURPSWHAYDSMRSLUKOVIUZIGYHDWWGRVFMIMHBKYLWPBRPPTWUNDZCPUKQOKVQWQFOWTZ', props),
compute('m_1_18/4: ${c} QWCSSQQPGCSBFSHPNWHVXQIYLQTSZFNCGCVMKPDGFFOXUOKSZMHPOVABPOWQROOABPFBZKXXHXVITCJDZHXUNOBPEVSCITVKQTUE', props),
compute('m_1_18/5: ${c} KZNTJJHCLCOLIGAIJKUEMKHFANFLBZMTRXEHTUIUIKEZVRPNPEVXGXOFHGBFEKLCOOCYACFYCMLEUOIKAVXTKOXKNWBGCIAAFJJS', props),
compute('m_1_18/6: ${c} BUZPUVCVMWFQVELFBEYLTHQVKGJXGVDYEIEBAFPNOMLTXMYZMMYLZTIRSQUTSFZSVBZCFLDQVCIPVKPTAOXEXLHRUJBVPNKLRYCB', props),
compute('m_1_18/7: ${c} XBVXLNNKZBVTQDGFGCHQXCSFVZDOXHADEKIEXMHXSASVHZDBHWZTUGBMLDAKMGMGIGBTVPKBESJQIVVYPRXDIHZNTPBPDLKWXQIO', props),
compute('m_1_18/8: ${c} VMGYMXGJCGSEVSOMXSWDRWOBVMFKQBMDHULOVDVRSIPFBEUIOGUEKYBZKLTOLFYHEZQGAMQHEDGQPOWBLXFHLRCMVBHHPOLJLTFX', props),
compute('m_1_18/9: ${c} JHQAILNGKNIHDMYDQOBVHHMWPCLYTERRAOJPFTDZXOMGPRJJRKJZDLWMDEXOGSSLFYLFMXUOLRVWSCKXZQEXCIYWPZVHRDJCTITO', props),
compute('m_1_18/10: ${c} CEVASGEBANPMWUEGJUUWBSGPMEQWUQUMOYCUMCVDCSCVXGUJBCZCAOGSVACNHOWIHDEEEYDQCVPVLGRVIRDYBWRKXMCGUSADMPCI', props),
compute('m_1_18/11: ${c} KVTDIYARTFWJFLUFIBJNSEYPCAISZDPEXBWQTTDGWCOXJTLMXUFGDZIDXHJUNWGGWETWXHYRZIMAOOJWZCXUUIXXPRCWQUYQEAQC', props),
compute('m_1_18/12: ${c} HXKEBCZMBNKGSHELHEJZANJOTGSYUFOCJMLIVQYMOAQZANHVWLGMOLFVHZSYLZRJETWTZPPXJBYCTAMXDQQIWFKHQODZFHNWBIMM', props),
compute('m_1_18/13: ${c} BEKLEDXFLXKITRIZQGTPRQVJJOGZFEQQSDPPMDJFXHBPQSBLJAJJRVHJDLWLTUWGRIPSJANQMVUPBVCHTSKIAQRTIWRQOJGZITAS', props),
compute('m_1_18/14: ${c} WJSUQGPHQGUJDKGGQKAMWNNGVJZOQLNKNYEOORRNPHMYPXBYTXMSGVXRHLSMZVZWAGGECGYCHUDKUZHSLWEEIBRBYLYUPOLTYVVW', props),
compute('m_1_18/15: ${c} GHJDDSZUHNRZEGNHFXZYJUJOKYDTLLIYLIBPIFRICEALCCLLQTUDHSLZVFBMZCULUJYULQERYDYFIWBNNQHXVLKWJLFRFAHPXAWL', props)
        ].join('\n');
      }
    