
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_6/1: ${c} GUTMXHUDHHRRZIJNDWGBMGBCNWYSFWJYPLXXEGFARJBMKRELCKRNZKNQADOINGKOMJBMVSWTWAAMLWUDOORUBLDNXCBWUKWKEAUB', props),
compute('m_1_6/2: ${c} ADUPDYIVAASNYBTHHMMGFBNNIBKWGIWALAQYONSOGWQOIWUGAXHCHIFJDSGDHTYWEPKZPLALYKWWIIBNSFDATCMJTPCTJFQHWDPV', props),
compute('m_1_6/3: ${c} AAIAXWHHOFNYOKNWZVPODQWDYOYQDMKXBUASUEBJTBQNUWCRUEFODIKJPWWMEFMUSQNCGOPSIQLWWIWELIUZWMPATUXTBXMCGFQY', props),
compute('m_1_6/4: ${c} QECLSDOEOIHWLFOLDCWMVPOIJLIVWODNHAFXLWTMYMNRANCUPRZHBZZFTVLXZORLDMHGDKLFNDDSBVANMSRQKDMITSINQEOAUEAD', props),
compute('m_1_6/5: ${c} JVTRXDSEUTUCEBKDDJRKFFDVFLRJXICUJRUGAZMTRCNPEHGLXHWQGPKEJEVKSCTYOVRTBCPKKVRPXFILBNSORCFAHYXVLFVYRRUP', props),
compute('m_1_6/6: ${c} JFRFYUGXQUHRGTYEHDURMLFESNQRDRMOLBFQTXUASGCNXFXQYOKWDLNYOYNWTQFUQVBEVGZOKEUQDGIDQKRHOSESPLDRHAACFGKO', props),
compute('m_1_6/7: ${c} KUHAXPYWNPHQQUWSMYSWANEDKEAKEBTADNBIPDHMFGXIOZELDFBEKHZYJUUUZWKCHXHICWDDUNMGQDYGRMQAIBHOUSSLYSUSYFIT', props),
compute('m_1_6/8: ${c} RPTOOWETLBQCCUVSXASUGWUGUEHBDLTZKNUFDVNVZRLBONQLOXENMIPAMZTCMNETXNBMKISIIOODYCVRGGDACJNVMJYHUGLBEUNY', props),
compute('m_1_6/9: ${c} MZBVQWAVDGDFXAWIRAPHNDCXLUFXIGUFMHMGYSSSIIBEVECOPFHTIJIBOYZOBQRRBXLTTGLWPJIOTVBJKMXVJWZKXNCVXPNOQCLS', props),
compute('m_1_6/10: ${c} DKYNKAARGGSOOWJBRKMUPEGSVZTBCNYMPEOMCPBIITNOJCWCJWSCDTDTZLGIZWLHASZBHGEDLGHGAXZJWQXKVYZCGEDSXUFVMQXV', props),
compute('m_1_6/11: ${c} NEFLGPVGLMURPDLCNFVZSYLMVILZFXTDFMLKQEKLIIFPUKGSXGJKYAPNBDJCJIOQUXUYJWOIIPBVQUITCECUYIEWKZMJPNCMAKFH', props),
compute('m_1_6/12: ${c} EBAATITSJYEMULSQTCTCELCLBMWQQWYCXVTMZQTCVKXIUYMRDARCSALENSYSTLFDIUAAVXMLRIJOHVWSXTCEFMFVFVIMGJPCQPNN', props),
compute('m_1_6/13: ${c} UNXRZHHBGYPELBKVZUZFBIVKRIDDHSWYLQJXSMIQRDUIXMUYDUSMVKQHGVABTBRKKTATSCHBXXFQMNKRLGUONJMJBMZRVFMXXXFT', props),
compute('m_1_6/14: ${c} KZWDEXUJHPDLIJHOGVLIYEEZPCJCQGBMVZGTNNQPMYUSQCNXNPXEPBZDQFYBWMFHDSFVJPJQOGVHQEOHLTWTVBFCLJXBFNCFOSMS', props),
compute('m_1_6/15: ${c} RBEWKCTTCZPHOQKADOPWAIUYGGHHULRFBQDEIOZZYMQSOZASVOHUGGTGDXWENONHFSCTPDOJXCEVJVQMPMCKUQNTWQGLADYVLAPI', props)
        ].join('\n');
      }
    