
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_4/1: ${c} BDYRHIYSSRJOVDLYTJSIYKHJDBSZTPRCFOBVIMQLIFWOTVCYELUQMVIBSQEWLHISJMQCXFRRZDENKOGOHZGBMYPEDEBFTRQFJWJR', props),
compute('m_1_4/2: ${c} QYIDWHBQQZZRDTCSGQQFMBYORRHJPRXVAPSTMTVTSUMZBONWUMNJFIGZJSIUCIKQVARGJYDWGDDGUKGFSBKOCXVDDZHKTQDOVWFM', props),
compute('m_1_4/3: ${c} CWEQIXBIGQKTRCIYTAESCGZQFHJPOWPVUQUOYLWJASTGITJTDKWJHGLCHHNKPGPUDSYXARZBSRKKRYXPZQEQTYOVMGVWXQPWWHCV', props),
compute('m_1_4/4: ${c} HXYTSYYINAYZUXMMXEDJKVLUBVZMPBUYSAMHBYBCEGMTPZOFFUPOYZPSIWDQHNFXUIMOFAZPLZPYHZEOQCEFVIBIWZAPROKXWEWE', props),
compute('m_1_4/5: ${c} IFCJGZVYSVVUJCQATCPJATSWVRRWIBQWSHFJZBLMPWMMPLSWSFAKXCBIFKDTYZYRLFKYYAWHHCVHOBIADTBWYVXRIKTGGBYAYLWZ', props),
compute('m_1_4/6: ${c} PFDAREZFNOECAWMEBJRCADKPNARXRCRICJWVSGBYFNQGNKGTUKDHDZEUQLOIKZSVYWAGOKZOFZOFBQEKDTUDOVEWEUBPSJXSYYNS', props),
compute('m_1_4/7: ${c} WGGGKKNVGWAFOGKYGBRVRZSQLSVEKWQEDALBVPGNIATKCCQBBSDUGTIWZLXWFNBRWUHBAMWHNKLPNSULJBZVYSOUQHTXIDEUCNNZ', props),
compute('m_1_4/8: ${c} EQZHCDILDQTCWUUCRESSJMETYWEHHROWIRGNNUSRLDCCJIMUWDRNRUBOAXYSVOGMNQLBLDRYFNUOWIXSLYVYFWMLHHRLWJKXQTHN', props),
compute('m_1_4/9: ${c} JMVGTSVFBJAYKBLKJIROMBXRMMMZOKDXRDKHNXFGOLYFPVNHSYMDRIYVANSNGHHAVBRVSYRCKYKKLZHXLKGTHHZHOUCSXZGAOUIE', props),
compute('m_1_4/10: ${c} NTXXNJKJGOPLGRQQCMGECUFUVQMDZGCUVAGIAQYYHMRXQYETFBIJHIWQILFYEECOZNQCGKUYQWCJHDKOZUSACBCVSABKGCVGEWJF', props),
compute('m_1_4/11: ${c} QNNQNQCGPTQDIKYSOQYZFOWXILMJDUPTODDHCOPAEPVCELTYGZQEESOUPHWRNTKJOKCJHRAPYVRDBJAVCNBQOIUDEQXEPVYRDLFT', props),
compute('m_1_4/12: ${c} NKVVBCOSUHSCPLKKABYHWAFDKWPESGHUGRUXGUFNCJOPBBBUIUABUUVAVUKWUQDMGUKQSYPGEHUTICTZAGXUZHHLGSTQCKUZTSGV', props),
compute('m_1_4/13: ${c} UQBHEXWYBEZUJKWFXRMISUCLTSLZXDCWOMHXJPDQWVHLJBYBLUSLYBJJXFUBJABJJFVFPYHROOHHVYLVAUTKDVQONPVKJKARNMBU', props),
compute('m_1_4/14: ${c} TDYQIXBNMZZPXZQVVTZLMNAXCFLXFGPTWUCXXQUCAXOIJVHRFYKRVJEREMESWDPNFJVEOSPIHLONBQMFXARFJMDOVJMVLQXWPZGJ', props),
compute('m_1_4/15: ${c} EBUVGAHSOKSMRBQLWEPONNTKCYPTJVUJLLSDCUKTGQUPCNQGJMGQGBVEGAJUZUBHJPHFXXOTWSJPIEJJOYBTPHNHNRRDEFGPFRDP', props)
        ].join('\n');
      }
    