
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_12/1: ${c} HXOENRKBLEYQJRYYHGKOYVIGLOAFFLUQIKATMOROBNFAMNDUKFIMKQGLGQMVNSNEQMPASQCKVORLNCARGQFDDOLQLXDZSJXGZDEB', props),
compute('m_1_12/2: ${c} GAXTKLAUWUILEMNESRWYXCDSUQGBJQVJWFLMOLNNAOFKTSHGJMIWJKVHLHSMQHHTZOUBOEGQMVTXFTYNRJRLCNPGFXWADKSNIPJO', props),
compute('m_1_12/3: ${c} KBHYNORLPSEPNJLTXWEPAQTUWRZOGYPNKBOCUDPBLWPSFLNAPBDECSFGPIDXORWAUGBJEJPRILHUWQOWURPSCWJHEQRKNNCLLFQM', props),
compute('m_1_12/4: ${c} ZUBMGPZTREUVTPAVSWLNAFOQZTULPRNMMWXCBUZWSHUIGHTDKOCIVHCQRLWJJKRCWVRRDNHCKBHJSNEBDZBARRZCHAGEKLHOQPVN', props),
compute('m_1_12/5: ${c} WBXRVDIVZKJEEXRAIKCGSFMSIQWXTJKRSCMNXEIEVSTFZGQVIUWQRVHOPPBJFYRBCHAGPAHMGECDMONFRVRIAGULHDNLTLPKPOIY', props),
compute('m_1_12/6: ${c} JOEAVCNEIZCLTXVTZFUTLSHENAQLVROVIWXLMRAYIXQMSDIUAVXKYDISZDFBTAWAZTHGNZBHGPUIQBTLGUETYTABOSFVIMAPNYQY', props),
compute('m_1_12/7: ${c} QANTTYYNDUAPMFFBCRIKCJOGCTHWPVYCOFGXBBYJWORXGOYPRNGLWIZISXHVTSTSMHAEHANAQZHVZIAICGQWPCODPQXVILAZCWUW', props),
compute('m_1_12/8: ${c} BKEBUXDCAVDCIKJCMHBXQUBHGKKPEDMKALZMYAXUYDYRHCSOLWOTMILGPPQSIHYMQANNQYQLMXGZABMWLHCQQFHSNXHIWEAFXPYM', props),
compute('m_1_12/9: ${c} JHXUXNINHEJBETJWFEECODZCZQMYFYDRFZQDSABWQJJQBZRJXATHKWJKWNNXPFQSHKWFGKSSLERCXVKJNGPOSLMGXSEXBVKVUVUN', props),
compute('m_1_12/10: ${c} RDCZURTDDDHEJGXHXCVDOSDEWRUONITKGLAGMGKLTFRDUUPNJDYMJFPWKUWUJHXRSOFAFFPUZDOCQKNWDIAHECSJNHGDXOAPOJCK', props),
compute('m_1_12/11: ${c} HGBOQIWIVPOUEVQZUQURLGIVHQPMCZEOOQQZEXLBLDUFNUVUZRQZWRZJZPLPQHUKFNOADKPHULOYCQJFGVVFFTIMENYVVIARBFCV', props),
compute('m_1_12/12: ${c} ICWHVULBSDOTCCTFSNIURUZUVWTPQMJWDYYPSLGSCWLQCECZBBLXFZZHZPCGTGSKKYSZQEJDAZAANHYPEOOJWGPYMMWADXNXPLMF', props),
compute('m_1_12/13: ${c} MKPYLQQUYVQVWKXMIWEWDURVBXSHXYQCWLGKPTSXIAHENTVEUGAOQFBYXLTFQZICWTZSQGXGCWAKJOESTBUXMUMRVHBECCYMSPDP', props),
compute('m_1_12/14: ${c} HMCVFNZRICDOZLQLPZBQJHCYFVUIHNHVVDDRYXJQNYWBAWPTFNMEAEAKLZIWRVZSFAVGXORISLLRVWRUNLIIHEWPRWSWNVESFQLD', props),
compute('m_1_12/15: ${c} KNWZJONXKFTYPOBHHYIJYOQSGFFAVJQZEUEHEKZRPUQYEGLBPFAQMFJZCEAUIPTHPIGLGNBUFWZMPELCAFCWHUEKMWPTAPPEAFIS', props)
        ].join('\n');
      }
    