
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_1_10/1: ${c} DFTFZEBFCEKBVFGRYDEGQOZHMYFQENIZFFJDREJHVVETSDJAZXMDMVWDLZIZLQDFSNNBGJQSXCJPAZHWXDJXFXQZAUHXFEMXFLTG', props),
compute('m_1_10/2: ${c} PEFPOUPNOBMDTCYMGAHWIGOHZWYEURVHZEPSBVXADABQCWIOESPAGHDJPLXYFLSGLBUBDKWFHTKYBZBFDRZFGGNCWSICGCQRRMBN', props),
compute('m_1_10/3: ${c} IZIPILIOQBWEQZRMRLJEXCCDUFNAUECNGZEXBZMNSQAYTKBVTUHWIPLOSXXLLQOXXUZCBRPIUHWRSKIHJIXLENWJYMQYIUJMZLVI', props),
compute('m_1_10/4: ${c} PILCSCKKTMIMATXNEXNULRWJPCYBPOKZCIAILJXUIKIVOZTBFEHZQWHQBJAXROWECDXSUKZGLELQTWDNVOEUJYRKCKRLYGBTAXUZ', props),
compute('m_1_10/5: ${c} NXZWXJHWVARRYMCQYMZOLHLFRKNLEHWZTWBBJCKCXFSBLHPSJORMNXPVOAIWEYJCFLAVMSNCHWUBAEZHLADVLPKIDDODSKNIANFD', props),
compute('m_1_10/6: ${c} JPPVSYHRINEPDRGQAHWRICCYIMGQUNDGCCBHPRXUCXTAACOUNHBXPHNKQSJNUCRXFGOZCNZNUFLKAOWFFGIEDZAHSOVGKIGZCETV', props),
compute('m_1_10/7: ${c} BDYVTSEYWCQECRYSDSPZFOXNPRRRYWIYVIMGVJIQKYBZPOFLRRFATWGTVERKAXVFPQLLTTEICAKFGIBDJRWYFZBOGKTFZUOEEGND', props),
compute('m_1_10/8: ${c} YCEUMFATIYFOCZSDBAUUDZFDKOQERSOCTEZFDIWUFUGXWGKUOGMEJHMLZJGPYKLETEUSCSIUJYAKTDOYLOJDGWJVZMTPNMVHYUZW', props),
compute('m_1_10/9: ${c} NIYAEISYOBSHWSPXZNHVIEPTXIORPHGIOAPXMRJZBNVRKLSJMNVQHKDSMNNPVAINNGPACJUQZFRAGUPIHVNQODCVZETLIXAHPNPV', props),
compute('m_1_10/10: ${c} TGFOAJCWHKDRSPAKQNEYTVNXCHKZVTSSJIXZRBQMHWWUMAAIBZBFPDXGHATKGPJCHQSQQLHMNILDBMZKPGPXBZVQPMYOCYYOORVX', props),
compute('m_1_10/11: ${c} VNPKILNYPYBDNCISYMYSFHNSFZXOEGYCXJQWEIMDDOTZABMSYSPNQEPHSOVCTBZZJKRLHQHVNUSAXHNOABVZDLLTYGQBXBVLUNLV', props),
compute('m_1_10/12: ${c} VSGRLREIGPXNCCTFQISIUSANSPSLOBDHYHLOVJELWIDOFFLCUGCNZRZXTTGIGCRAOMHSJWSZHIEYZUXLCRFSHTDNJUUCQQFMERPN', props),
compute('m_1_10/13: ${c} TYGCFTZXVGQYRHCPEUQAPIELFPEPOYHFXRDTUDVJWVLVPWKLDGSSRBYOZRSGZQKFHFVJTXFXMBEZFFSNPHOHFSOTYDMBVYCIGTGW', props),
compute('m_1_10/14: ${c} IDEBHZPPAKFCRXHTNDVHTUKNTHRXBWYAPOYAALOSTLOFNXAXYULCRLNHQOCPJAPHBUUHZMQFAIQRVYIRPKQQMSOBTRKISABMNWYI', props),
compute('m_1_10/15: ${c} RACLXLLTCYPKDDPSABNAZREHVDWKJHUCSIKTZCZIKPJGZOHUINMZKOKVNINFAQLQJPBVDBBMSUCNRXWNVUHGDAPLQZYVAPTWYTTV', props)
        ].join('\n');
      }
    