
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_19/1: ${c} EFKHDZPOMXZWSXEVLTQBXXSPWIIHYHFWKAPTSUZNQTKQILYBZDYOTTKSZHELNFSRGISMLLBBZGBKJNCCMFRSMZUNEOHFHXMIVXPK', props),
compute('m_20_19/2: ${c} IJRDOZUHAGLGZUUOOLXVIUAWLFRGSXNVNCGACBIWHLLKACDIYXKJDAONYTPAYFJORHMRDZGONSTBHXAYRVBLEBBUAUICUNZFFHFX', props),
compute('m_20_19/3: ${c} WAMROAYXTFBSPEQKSGASPZMNZUFUPZAFMGYBRCZMTAQYSMBAYNAMVATKPPLXIBIMVMHREAZYAPSTFKSSVGSYJQUMEEPFZIJWALHD', props),
compute('m_20_19/4: ${c} NWTYFVUCDDZJHUJSZMMYUSRKAAVRSZPPRXNRXBVLXJNJMGKLRJFGKJESOSOQNQFPVSJTUOQBIVOODXYAWXTXXHYRBHAEBZHWLVSY', props),
compute('m_20_19/5: ${c} UGZMYMAXYMYBOGSKLAVLAJAEHUAYHCMSVISAXBCUQCFBWNFTAQNNYWNHWDBCDDEJABHIWUUIUKCHASGZXYFBCLGAMRDAYFORHMVH', props),
compute('m_20_19/6: ${c} ANBGHVTSSSBTAPWDDJWQIKUTDPLJAJHGANNCWBBSFYHHGUSDSKMKVPPXCQPZXQJTOQFBDMBNJIFZDDYYGQXZCRQVZUIGYUBERUCP', props),
compute('m_20_19/7: ${c} MYOQPVVAFPKBHKEFJYPSLCVKSCDHKHUPMKFUMQGTHFWPEQZDFMOOIMNITYCNFCJNNYZXTTZKAHVHJRIYZVSSRJYMBTQUYJFBFYDT', props),
compute('m_20_19/8: ${c} IGZZTBOJNDASYRMEWKJONKNCGZEPOPLYFZOXJMBYSWYMKMWITRBAZHQLNVIESFOQRWPYYNYBLZZNNIEYFJMJYLBFAHHIQCUGNOOU', props),
compute('m_20_19/9: ${c} JMZVRJTHWUAAMVBYAPAOXIYOMZGLULUFAWGQBVRHBZFEOOCCBGGCNLZODCSAACPLRYYKGESMAPOAWQARLXBIJMUBZNMCVZMAHEZP', props),
compute('m_20_19/10: ${c} TKEEYWWOVTFSIEOKCVVJAQGDYOVCODPXSZHETTXBTRSXEQSYJPHKBMGXHIKKAUXPKXGOJFSFARIMUCUXSNQTFZUFMJLSKGRMSVLC', props),
compute('m_20_19/11: ${c} DDXGRGWRWKLYXDSDTDCMLKKYFKVUXFQNCSCSBTOOOQNLAFLZXZLWNFOSDZHORSWBUTYYKKDCKCPYDWQQLUXTHGIWXMTNKLMJTHMX', props),
compute('m_20_19/12: ${c} QOZUDUIRCDGKUNDORGDEAXQVYNHTGVVBLHMOEZLYTHEOLEEMQQWTYIZLXHWRKVZXDRRCKFOMZAHJRRAUYBUHOKOZHYTUKAMHUGZD', props),
compute('m_20_19/13: ${c} RDZHCSUKKBHBHOSVKUUBDQZSHDUYKFMNFUKABWEKPHNXQSYAQRLVBOEEZDYXWUZMXFLVEFUIKOWAVPRIBECTEADNOISRHVNDUPUI', props),
compute('m_20_19/14: ${c} FEYLSPOWFJIQBDRISEJYDLRKMZTHQCTVHKHBIILXASZJHACVPNVDRJFYNZTUCOBDWXCMSBYTPLPCCETTLYMOJHTSQDJZEKUIMZWS', props),
compute('m_20_19/15: ${c} CEUAISNDNXZJOQWYKKSKAPWFAFYLBLMPCXASJPXWNTHGNEVHMPOKKTILZVCMPCXNJQDYQDJWJYUXPDAEPNRTYJXSJONNGOUMVPLB', props)
        ].join('\n');
      }
    