
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_3/1: ${c} OBWYOKLEBYNMXXBBFNYNJQBWCNQJAOUZDEYQPNAOOCVWRPIIGWRETODPXSFYAKLTGVFOMODLARIISXYTDONTQXARBYJTXMTBHLZS', props),
compute('m_20_3/2: ${c} FYDXZKJCVQRZDCFAMEFEWXULVKILIFGSBFZRBGVMUHWRYCRFPBKWKZWJJYTSRAJPATGHJGKWTTTUPHRZDRQCYMWEIUFPCPFIJIOH', props),
compute('m_20_3/3: ${c} UDFSMYXBMWOZNSAQWIYISZTXMYORPEJFKDRINFSBYFJAPRMMXSGAQBXHBXORDCPDQBRDRMQDUWQZFMHKATWHWCKQGOLFARQVPVCW', props),
compute('m_20_3/4: ${c} LYAXFHVDTMSMGHJQKVPNOXNCHPVLPHMVQLKDJDEGQTCAMHPBQBAGXFIQQYPQOJMQSYMJZVHCSBGOYJWQWOQGIRFAXDYYYXAZGKFY', props),
compute('m_20_3/5: ${c} AALBVUTAAXXMGQQIGZGGAUAITUOHGNPREWKAWUHBHJZKCTGBGGQLYPTHCLTQUCPNMMUARKSVDHETNNPNUIDZPTJEEDVPOQNZEJNA', props),
compute('m_20_3/6: ${c} LZXQMNBMASOKXACMJKEBRGTHCSZUSFPMTYCAGTESEHSUZGSEUBVYWDLXAOLBWTWXFFVQBWADJLPYMEBGDRBMNIMTGBAVDCUOCZBB', props),
compute('m_20_3/7: ${c} GOXROSNRULQLYBQGCPXAPQWYARSBOQHQORLJFJLALGJGFHWMPBKHARWCKPJVKOXKOQCKRIUQMBWLUBLSWYXZOONDGZUWOZNZABVN', props),
compute('m_20_3/8: ${c} HUPJKJXCWUHEMDWCSOYJLPAODXKXYBUYCTIMRNARYJXJNVZERMZUOVUNZCRWTDWUFCWTGSQURVIFCVIRBCOVDVRBQOVDAFZWAEAA', props),
compute('m_20_3/9: ${c} PVIFGUDBGPBULFOXBVHYVAXTPWCALMBCUMUHAXROJYIVBVWYPYPROIPGUEKUNUHKOKWZPSRXLAYCQSQLZCQLAGODDVCOXGNIGKQO', props),
compute('m_20_3/10: ${c} FUZENICZLNLMXMMOKKVFRWFGNEEQYSYCURFAADIGQOTPIDOHBMHBFMMLVADAKWCLUUKJRFHXPXEGLTNYNSNJVRMIGTNGIAPGYVYT', props),
compute('m_20_3/11: ${c} AFDYZMXDAVNXRITXWYGTXZRAETFGDRWETVGPTRAHHRBUPHWKHJHZUEWBMTATQKKAWFSZWLBQMJNKDWMYTAMMXJRYOATYBKYMVFSY', props),
compute('m_20_3/12: ${c} HVTPVHRUQQKTQHJCKQEIRAXZDGQCMMAWBHXXUIJJESSTWBMYANDUPPVMPGBSNRNOCNWSUCBMRNHMSANQTYZOMGSRAABBJCOQZDHY', props),
compute('m_20_3/13: ${c} NJTCMVZCBDFHCWYHZZIPSKZYXEIRXUUVZZZHODWBLGKWITWOEOGHHISHPXAQXYMPFGQKMGYHJYNRDFYTHGQEBAIDKFEZXORCBFZP', props),
compute('m_20_3/14: ${c} OZOIUCXRKKYAIRSRFJKJODDZGQXBMOOELTUABBRZSKNQUIHFHLAPVUUGEIZAEGKGKPRHAJSKFYDPDMXKJEMUBNYYYTGYEYGJPLTN', props),
compute('m_20_3/15: ${c} TLKJPJNAAYLVRUXPRFYLQCBECDZOREFAGPKLDSMLCLJXMSETCBTKRCUBGTLLAEQXXMELZWCSKCXFMPJBFLELRIBVMYAKLYHPMJEE', props)
        ].join('\n');
      }
    