
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_1/1: ${c} CAGFHFTEFENNJDXSVVPRWCRNWHGKJHTOHHRXVBFLHMKBEDCMXOQEZOQQUVHLGSASGNVYBLDEJCSNISZOQZKUQXEWNVDDWPDENYFY', props),
compute('m_20_1/2: ${c} SWTNOKZCTEAYQVFWFIZBGPATHTTRLNKUMGDOVDVTCBSLPRAASCEXXVDSCOVCDYBHRILPFNSZSTLQSLRPBGFYXCTWLUTLERHTLFLD', props),
compute('m_20_1/3: ${c} XVZAOCPBKGOAJWKUXMZASQUTPWQSAUCIKCTDICPFZHQCHMOKHHMRRMVTBZJGZESYBPRRXMKRJCRRRMQLSQFGDVATNLPKMOVJIYOV', props),
compute('m_20_1/4: ${c} SFZOKBIZIPEVLBAENKTBFREKCMQVNIYHMWRXDXFHFWQPQQXNOBTNCTMNVSKYDJWIDULOHULIBWIDSBVVXUAYVCORBESUEWPRSDNR', props),
compute('m_20_1/5: ${c} YURLVDIOHESIQDXODGYHIOQQWNMZMKKSHPGHMZNAPOLNYYISPAYFGRLWVHLBCZSJKVDISRJLNRKXTJLWCRATHKLNAQYPIPXGYDNG', props),
compute('m_20_1/6: ${c} PHLKABFQSKIMTRDBMMQQRXELEEYFAWGCHYKHRMCDAJLULNQNVEYBCYKMMALCQSPGNEAGGNINKPJMTWATOCAUDYECCVSWXAFDJVGQ', props),
compute('m_20_1/7: ${c} AOAOPJJTGAWNXCQQXIRLXTGYSWGKYAMUHGJLLZJKFRMHIKITOCDIYSOAPEXATTBRSRQTEIGFWZSQAJGHKLWXFRMUXKDIFJBAPUDQ', props),
compute('m_20_1/8: ${c} QOQOEJTYIVLKTHLDXSURAFORDTUUFKYXQMHXEMJIVZDMFZDSWTABYMLAYCYHGGNJJZXLASHMIDLWKUGLHXRFCKOTVAHKWUYLOOBP', props),
compute('m_20_1/9: ${c} METUULAQRCIJTVHZNPDCMUFLWGCKSUDOTBFVYAVKLADGVSWFLQQZJFVHZZZZAEROGQRUKHPRMSULKMYBFWRNQRUSJGUYDIXLGIZX', props),
compute('m_20_1/10: ${c} RCOGBKUJMFCRUCTKEXNNCDKTNRIAZLOIHYSBGUOOFABXJSOPUMMNIDMEATSBAEXXWFAXLLXMZQGYDMMHZLAPZJIATGBTMOMEVZGX', props),
compute('m_20_1/11: ${c} KLIYIAYHUSPTWAFVTFVPJGYLICAUBZIIASHFJIFJWKMUUDAZFJHPMEVDEIJXHARPMZFXYOVPCHXLUUNVYJHXGFGFWUFKANLIEVYB', props),
compute('m_20_1/12: ${c} HDPNNMAHXEDCCZNCGZYNBJCKZKXLRWIPGOUZIOSRUHGWPODTQIPRDJCSANQGCGOYLCRKSKFZAFDMJYUJUAAZZWLCEMFJHGNTXVSX', props),
compute('m_20_1/13: ${c} FAXMRJAXSIWJBSTFYJAQCCARAPBEINAGJCNCAVRNVJSVXVIOSHSECBAERDWXDQEBFXGXCYGNRAQAQYYHTVLRSLHHGNNZYREHIHDY', props),
compute('m_20_1/14: ${c} SDCQRBHEXFVJFUXLPZDEHBNTSAACWZOKZFQTGAOGXSYEDKIPFGHVYREEKGMNHTPQLFJHCGHRURVDIEHRNIAFFWBOECZDKPOTLWQL', props),
compute('m_20_1/15: ${c} QTOSINFWGBXFGXCMLLZWNPGWZTOMGBIVTRWTPKHSYFQMSLTURHOJUZHWMHGAMXZHGWCTDGMFVNQWPSDLXSFTOPXFMSQSPJTSLWYE', props)
        ].join('\n');
      }
    