
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_11/1: ${c} RBIJRANUBOXPUQIVNMNKQAIPAJMPJSOTIRCLMIKPJKAVACBTJVXFHSUMVMKFBIXKKDBJKKJUCAWYLECIMXHPXGYIDYWQLUAKTRMH', props),
compute('m_20_11/2: ${c} RWGHGKKCECAMZVXSMMMTMRQZBONPPZWKPYDWJLZDOXGSGZEUKJDYXWSKARTVHOAGCSXNOWBWYOIHVDFXFFOYSYNOBEKETECWITEX', props),
compute('m_20_11/3: ${c} ZWCFYUPWLFVJRQMTGGTBJPORCLRGRIXFHVQELSDUTTUWFPHLOLHDMOASRFQDZXSWZNZHQJAVVVNHMADEDPVYRZXDEHVWTZCSFXSN', props),
compute('m_20_11/4: ${c} VUSKALVBXQALCIYMTXQUOKRBCWFJLTAUOXUBAFDOPQTCLMMBWEBFZTWJVPDWZRKVVLHAKNCDQOCOLRQLAQYOGZDDSQMMIUHSBYVK', props),
compute('m_20_11/5: ${c} ICSMNHNRACDNPRQBQSXMLQNLGNSIYBDCQRFREAYNWFRPZARMJNEOGCIKIMHUGFMHHVQBLCVJHUDBXDIOODWCMIQOJRIZTSQEHMHO', props),
compute('m_20_11/6: ${c} RQCMJXXEMXHGYCDRZLATLLLZPWCWAUGGJKYRRSKWBHPQBQCGNNBPTKCYOXMEOQXEQGXRZDBJTOEYOLPSJCHHRVXWNXHKYOCAMYGU', props),
compute('m_20_11/7: ${c} UKBWTWZILIHURTHDTRMORZABQDDLNSJANQOBBVCJANQKRECKJFCQZHQAZMYTSUQOAWPONPPXNUFDKKZXJJZZSKPKGWJSGDJGXSDV', props),
compute('m_20_11/8: ${c} NUTKCIXDOYRYUZIRWXMIJKNBTQCYKMXNVNDDPPGUWGZCCALMWPZNQPOVOVUOLNIUOCTGSMZQSBDJETHGBYZYGKBTWJHYTPSMVDBQ', props),
compute('m_20_11/9: ${c} BKKLMCSYHPRQEBXUQPVLTMRVQABWIAYFHJOWKPDBDJPDOMEJHHJULVDSLJMGUTSKZRWICOKHOKYUPEKZHACVHLNJZEDDAKFJTMYT', props),
compute('m_20_11/10: ${c} LZKYEDQZUJRXYMRXDXCLPFPZLMSAPECIPFFANRWVDORMDLRTPSFGIJYQYJKUDYGKGSCOPNQKEHKYXWVDHPWVVONMYJCOVSCOLJXG', props),
compute('m_20_11/11: ${c} DRPHCQUCNFNHRCIBNJFMBYVJKFYUGDYUSYJZIVYOXXXKTOESIGFUTPUUOGJNZVILGFPNEEUORWHZSHNFAWLNPHSRQMNMPJJAKNLM', props),
compute('m_20_11/12: ${c} ISABHAYOMGPPPUUYRXXIHYUNBRIDQGVPFSPHXQTROMCNMTWCFHPKAUZSHOCVXEAINNDTXYIFHRIFLDVSIZYQEIMLNLFLCPXJEHHH', props),
compute('m_20_11/13: ${c} GKEMQKFFIGCXQJEYQRXNITBPOTXVIXYTOQLPXJMZAHGUVGGAFXPJQCVWEFTLRAHVJYVYGPBRVPJGAJGJVXSCBKRJJEKVDPCXYZFZ', props),
compute('m_20_11/14: ${c} CLPSNNTKYKDHRLLJBZTKTOQGYPKIGMTTCWEODLWNLQZCSTESDWVVDGUCITZGYTSPAIQHTXCZLAEULRSCXLDDTOUKSSBUUCWBQNAI', props),
compute('m_20_11/15: ${c} JPXMGHTDHYGYODRYWKEEKYGUJJAJJGTMFJVMLJFAKMXQKISSECDTAMHSVXJKCZGODLDYJQZTEVHWXJKWWKPSATHSHWHENGMTADSG', props)
        ].join('\n');
      }
    