
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_15/1: ${c} ZTCHARSSIJZDRUVISTYJJMTZTEXAYTMTKXIREOLHRXGKHGWKZISHAMYCRCWCMQUTYZCIIDFSDZGCTWSNJVWCHYFGDMKNQDJTLUUW', props),
compute('m_20_15/2: ${c} YGHBIBKLQEGHUKYZEWZYHPGTTAEYJRXOXPEDIOTLKMJMGQMLYTBCDJBAZOCQIFPKIDQXOCKLEYEMLVZJCDYIGHIKKAWXWTSDWQKH', props),
compute('m_20_15/3: ${c} WNVQABOIPSVZISSYOXYFOPAKEXADKHMVPDKNJNEJKFHRTSKRUVZJBIZANZQKXZHFSZMGXCIIPSTATTPFPXBFLMRWPAQZIOABJHQR', props),
compute('m_20_15/4: ${c} XHLKLLWEMNRZMQIGOEHTXKKQRQDZOUMOQMESYFZJZQZKZJDJFNLKSBSPNZGKFMFYPAYVLWDPBVZPTSKELWGVGVSTOUVWBBEMKCOD', props),
compute('m_20_15/5: ${c} XUICAJFAPCZRISGWIMRQCSJVZBEDALEOPSMUUJJKNIIVVPKWGFFNEOPJSTNJKTLOCYVIHKKFRPGRKKZGMUULQPLBHSRPMJRUNKRZ', props),
compute('m_20_15/6: ${c} BMUOZJGMSMTESWDQLXBHUIHFUNMJFPOWZVGQLYUBUMXIKSOVXPHZHZQUAHBBVOOROTZWEPVXMQLVQBIPYTSCZBUCOLPXTJIFOOYH', props),
compute('m_20_15/7: ${c} KXJQDPKZSSRBAEBLMPZAPZGAPIMXRAXCRBTSPQKZLIADLQOHGSLJSQHQCWPQIVXROTCZLYQODOGFPNAMVQJFZZXHRNDGSQJJEWXU', props),
compute('m_20_15/8: ${c} YXVRDBESPTQAKAFWXIPGKFONHQKOXWUVHTKVFBSTUEJITPVXRMBZDYSVSXQHHMJHMCEUQTLNAYCDFNXTQVFNPLBJIULQKSPAXTHL', props),
compute('m_20_15/9: ${c} BEGWXGVBDBYNDZMNXZTBNXAPIUXRKDDFCIOGIOEPKURWESKAQRDAYILEQLBIPEMJYEZWZLEFXLBJKPMROODJLBPKKJISMJXGWZES', props),
compute('m_20_15/10: ${c} XTFDYHNINHGEENWBWYKLVCYKCXNJLXWXXQGUSPFCOZTFIHRZXFMYIDHJYKYJBHVKBVGKBWHRUKUYRAVABTGTXUETAGMVKHWBOGMB', props),
compute('m_20_15/11: ${c} JLKLKWWBPMMBKMHMJCGPNMNBWRPVOTKZKDUOOWLRJPJCHWGMCQYPFWTYROHARWROCQOXRAZVKVHDWMLPCLPPFJAGRXBQJXGKNLFX', props),
compute('m_20_15/12: ${c} FDZGHHVUCLVGWHFDHIAAGRSHXAUSGXGJRCYKBPFVXEXZKCIVLOCAPONZPKJEFWEJPBREVYNBWRFKBVOPVYPBMSPKKLVYQKVTOMAK', props),
compute('m_20_15/13: ${c} SUDVWRRHNZHMSDYPKSUHPRRPZWBTVUNSRBDHEZDKBAVZMMPEIULCGGAKQRDAIVSPTTQOZMLNHRCCARKVYKXZJCHNFVIHSTYDBUGP', props),
compute('m_20_15/14: ${c} JFPLVFLIPZPNAKLUAZRQKXTIOOECKJMDQPXINWGEUQXELMLGLDDXVHDFHEOJVVATYVNVOUJRQRRXFHIINDKEYDJEUAUVFRILAZRN', props),
compute('m_20_15/15: ${c} FAOOANFTYSAASDFNKZPOQIGPYFJLMEXSGEFWWLDLUAUZEXXDGPQMHOUPIYOJTCSGUPYGLQYBJIUIXCGAFICHBXHEZHAZHWQZYLOH', props)
        ].join('\n');
      }
    