
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_2/1: ${c} SDQVTLMZXYKMXGEKYJEIOPGJASJCTPGARTELMCHOKGVYXGVJMLTFCXYKJLEUCIODPRCXITHQTGCTQOPBCECVBIAEOIPSGNQKYGZP', props),
compute('m_20_2/2: ${c} OGPYJPDYNZMFZYZCAPFTOROUTFIGBKXHYAZVXIBINXJVAVKCFLSOBWCBQHESDOBUORIEUDFMLRSWNYTEOVYEOHZXPXZPHZWBXUMR', props),
compute('m_20_2/3: ${c} UVCPGGCJNNPXQKCIYGUDDIDGPKTUMCRAMBFTFFLPZQSEJUGGIVRMRDJTGDSKZZIIJXTNLDHDJPHKXFRIZBEGYITQJZYGXOULEUSA', props),
compute('m_20_2/4: ${c} REDXGBRCGCYDCHJGYEFSQNUPHMAPOSJAIDDVGAKRNJDFIJGQAJRNMOYDIVJXCIUAWSZTTSXPODHAZSORMYRCVFSNGDMIUIGXTSAH', props),
compute('m_20_2/5: ${c} YVPWICOQJKXGNWJNZVXJDJIZPBKRKGKVJKLZRDRBHGBNKOIKGCYNZBYBORWRXDEVRPIFLYACUNSCNALQAMQJTNWEPABZTZTVJCUY', props),
compute('m_20_2/6: ${c} BCRGZHUFFCRCCIKSLBOCMYSGMIYVEOTQUQYCRLRFCFVADKAEQDELIAKJPSLVXQEZUGYKUVKNGSNZTGFGJSSWLBQIWIWJLEJUNTUJ', props),
compute('m_20_2/7: ${c} VDYKZRWTBMLLMYWRVZOLFCXEBSHRRLLUSTSEUCAFSBZJLSWNGCDUKABFFMTQFHMQVJWWDUHMUNTAOXMEQZQYPUZNGWVIOSETOAWW', props),
compute('m_20_2/8: ${c} EVVFNBVFBQRFIWSDQLAAAERGHKJVBCPTTNZWOPEWNTPOIQKKXYPBCDEZDWSLHESYGKKRLJTHEZXZUNPZNJAAJBIMVZEWREBXZYCO', props),
compute('m_20_2/9: ${c} VHDTUXXHCFCMDBVPGNROWHRJWUWDBIKZAQYOWESEKFNJCGBSXSTCAYPBEOHKTSKTZCNGHXITSOCSIALKQPXRHWLOHTUYOGMEWKBS', props),
compute('m_20_2/10: ${c} KJTLLGOLOZWDDHDWOHHAKKIWWTRXWNWRNUCTNSRFALADPCQWYZWWENGTHQXWVQBUJJHJLULBHMLUUDIWCVOCYWBUJFLPJFMWISDZ', props),
compute('m_20_2/11: ${c} KORDNBNVUQPSGDDKZGSUYVUMMOOULAHFQROBENYJBUVPTCLWFEHCFIOBEQLPJNBGEQWEHBYVLCMTUAXHLFPMQCHYHXNKKVNDCMJK', props),
compute('m_20_2/12: ${c} GKFTUNCKCAHBUJYCCQABLLXVDTAUCURUAAXGMYUWLIYBKQIYRXNKLSROZXXUUQSJPNWVESFWCEYYHRIZLFHCWAKIOEVJPLSZYDOM', props),
compute('m_20_2/13: ${c} HUSYBPWQHCQTBEZJDFUAYQPCUWCYFCTNRRCITJURBAPTDATPOGVRVVOFIRUOZJMSFPRCMJHOZEJSTDQSXSHQVWVUGFKLOLGVAOOA', props),
compute('m_20_2/14: ${c} JBDEMLOBOJAHCTACXBPNWHGKQWDYBFCWPCEIGVXNHZIGFGOTDBYYYUFHQKRZBAKFSMMDYUNRWURJBNRVKBLHNLULSHDFZJJYSTIB', props),
compute('m_20_2/15: ${c} OCBCAXJTBIBTHATWNAADUOIWHOVATOHBSNFWXVLYDQRKBYPSMNSEVPUXBHLJGKSKTIQBOJLHSQHCBNUUAVOKRJGCEKGFARXIOEQA', props)
        ].join('\n');
      }
    