
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_8/1: ${c} UCEPYTFCACTGOQPCJHAWJTBOKLOSJSVJHVTWBMWJTCWFTQMHPJTUQMKGPEEVDNWNMDSIKHNAHKDWKADRNOZADXOCZDUIUHFWIGNB', props),
compute('m_20_8/2: ${c} FQUWWZXYGBBDSNFRMAWIPQSINCCHCZQOLTADQKDIRATIUUVUQTMZNTYIJBNXBRXTLTLWDZDZLMUNLVOLXVXRXCERMHHMZLGVBURR', props),
compute('m_20_8/3: ${c} JLDGYBKMXQDGSDOMUPEEJLKDOXPHLRUDFAKJKEONINUDZOJTVUVYRLLDHFNGNMQHURQPVXIVNZZUSADDCCAHKVMIXYZJYPECDSAQ', props),
compute('m_20_8/4: ${c} KASOAOMTIYQJTXJRZGIMSUABARJUSFCXBSXUFJGIDEJBIGBMVESTSNVTHXPSOXVPLOTLQJPRISKEIJXPDBJURMTAYCVNZVOFIHGM', props),
compute('m_20_8/5: ${c} NDDQOBOAQCRIPTBAIPZGDUPYTJKJBYCAUFVYPQCMQSOVXWCWXQNZHZMYBWOTHBKSSQOKHRRDHXRWLBVLQOLSKVNBCAKRPDLUPITI', props),
compute('m_20_8/6: ${c} BHAVUBTZCGKVUJZUSWUDVRIMJHCMOVQXBAIKCEBJNWSQULGMTCNBUZAKENDGHAEYHSCWYFUHHZBKMMTWCPTHTTCAZYTKMEADFCXR', props),
compute('m_20_8/7: ${c} AFXZVRNPIBSFBLKVQYGWBBRKQXYCRHYBJJPFFPOADGAIQJVRIOIZRHYABJXMISKQUAPHJKIVMJVGNBIXSPOKNRTBDWEESWVTFEHV', props),
compute('m_20_8/8: ${c} JTWCZTSINQBRQLNMEHATSJAKDSQMDRJYBKGFHKXTXEKSYMWJFYVBTNXCEDTQZTNZJNUFYSKNAHTYGJPROLHNZXFWOEJBTPQTZFHP', props),
compute('m_20_8/9: ${c} IAZCEGZIKTARVRQEQDIRTTPIUVXYOWSGHGZOFRDOWBSMEIQSPBJNTRHNGPSUUOXSVSAPRGTRYJDTXWYTIVUPWEUIMYIHHYFQVWCE', props),
compute('m_20_8/10: ${c} ZUZQYOSOXYTDQGYJDEJBHVUQVJALERZULZHABSIPDBPLSGYHWLRNZXFHCCVPDBPYHUOKKWMKPWPMBHSTMUJERMVGPSBCYIXBCCHQ', props),
compute('m_20_8/11: ${c} XDNGSYGZTFPFCNUPRRRBITDPNLYCUSJBHREWSOZWXYIPSDXMTQBGQEYNGBZZGECPGYRVVBYPQHSMYMNQTPIXOGOXTHKHSWRGFGZU', props),
compute('m_20_8/12: ${c} HUVQWUKYGIMWWIEEMFIXEZAYVVVHLDGVRXQJCTJJMOKKOHMTCSDFUAULCCNAPTSSAHCFEDIGOTMTEDQNCPZPELKVEOHHXEJQVEHQ', props),
compute('m_20_8/13: ${c} XXJLVOXECAGGUNEPDPBSQTKRBMPAUUROVDNOVMBVDFCQMJOYZHXPHFEIAGTSKBJNLZXGXMUKTDLJVMPNUGBOUYLZJVBQOPAJVZOF', props),
compute('m_20_8/14: ${c} PNDTRAACQHIDHYZGPTXQXNLZSGCWREXISWLRZDQHIZTLXTCIYZAHRCTZFUTXOHAKQKUWIWKNGKMHZECVXYFFPNXMTNROHWXHINPH', props),
compute('m_20_8/15: ${c} YRRSVNKSRZRGLUGEWQCKDLQKDHTLBWFVPZRPVPFQVGHLRCNIKMOHCEJYRJPBPWAUBTXMDHEEWHQOVMNLENVKEXAKJGMLOTMHPXQF', props)
        ].join('\n');
      }
    