
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_17/1: ${c} USWVSDXVMPKRZPFSCLASWLPUCUCOPRNWVGQZJMQPKETDCJATKOPXQHWCJKBNTUGQUAOVAZXCZKYIRTOEAYXZNVNUEPXJFUFQBOTR', props),
compute('m_20_17/2: ${c} AEDUUEPLACRRTPZBCFPICDENUXOLAXGSHTKHBDZUZKTWICSKYIPDVEMKREYSNKHTGAQKRXLQAFSAHMBJDHDGXIRHLVFFRGDBBEXC', props),
compute('m_20_17/3: ${c} XVGKQZDDOULWPVUYAFFQTCYJAMUZSHHAHPBUPUDFLQBMPLESGMTUBKXJQLXTRQOXWKJKMWLSQTGACIPFGQJIDQEDCVFJIHSQMCXL', props),
compute('m_20_17/4: ${c} XZOSGZBTPARYLREWBGRBAVLXMWRBZYYLRAQKRGXBSBWOBSEMEMFEAXPTICCOIYHGNTPMPTNUUKXMEHEOIFZLQMPODYCLONBXKEDM', props),
compute('m_20_17/5: ${c} EYXWKGOGNJQUFBNQDBRYLHKARCYWEOTRJZGGIVYKYURBNCRLSTNOLJYDEHYSMVINVAYAVVDZRKRAJOAILVRMAREWLQJSLCMKFLJT', props),
compute('m_20_17/6: ${c} EKLMCLRRFRYAIKYDGRRWDGRPHQGMNBHVJVPHOSNAWSSWOWPTXWEIZNDYXEBWQFZYXYNRPWQOSYYXIYLNHXXMWUDYANFOXEUWVATR', props),
compute('m_20_17/7: ${c} SEERILFGLKETGQEYOSYUVKPXTZSNPMBMHUHFJEWQZNQQNOKZDLUJCRRMXASQZSGJTAIRKMCFTYXFMFHZSLOREUWROFMCFKZHVTZM', props),
compute('m_20_17/8: ${c} HMZHAVHUDLBJAXQQTZFMSDSECYJYTUXKCFPRHTTXMKIGWDYCUZRSZOPLFZVQARGWXSJUYPRIPVCGUBHJLQGMUBJJRYFKQUZQXEQK', props),
compute('m_20_17/9: ${c} DZPZHTNKFLWWGQPEXYGJKKTHJGUVPZUIEHLSFFEOZDTIEBBKTIOJZEXMDFKBAPKKGWBXEXLVBQQJOBDWMTFMDXBXQIXKMYCXREEC', props),
compute('m_20_17/10: ${c} TNYBEGEKRVWGRYETIRWUUJUJAZOVQNAXFXZSCUHPFQPTHYOBCCHKQNONIDSPHBRCTOUUKUVLXFYHANAXEDZLRHIEYOQAHCIAZVGD', props),
compute('m_20_17/11: ${c} RECGYNWDQBFERRPYCZPUVMAXUYZWIAXKEBLFKGTUVRUTTYBIJTEMOWKFXNRWCLERAOPIKOOFQDSDKIOSVHIPDKJYCONPCDCIUHTN', props),
compute('m_20_17/12: ${c} AEZDOWIAIESMQXBRYMCIXZSTJNALMMMANAZJESQTRIQOWYQBSRRXVIYWECLIAGWXMJPXONYBNUZZTZFDPLVVBALGMGKCKPFNXRXS', props),
compute('m_20_17/13: ${c} DASDQELRACPBBLBQPVRLKJEITKSDIKBHDQGTHSIOFZKFYTKDWCGYWSNDAARMERMIQMUZNRPAFGSVTKDVYRRXGCCHKFQRHRMGXGMX', props),
compute('m_20_17/14: ${c} YEESVYXMYEBIUAUZTDYFWNQXNEPBBCNZZGZCWNCHYDQWROEPPYFXYZTWQUMYSKLIHFNGTQOCJPEJHIZEXNNQBRWCZWUWVWSEMDJJ', props),
compute('m_20_17/15: ${c} LUCENNXANTHVFYVOWTBJQRKBVFHSXYDUMDXRBYHACZBCFJGHEGWPRAEQMQGFHIGDRZEBDUMAHPYGVEWYRCKEVSAFWEPLHHARMGFN', props)
        ].join('\n');
      }
    