
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_12/1: ${c} TDBCSAQCWDWLEKQHHKSUMAJVJJDGUIYZESEGOEZADHNPGTTFLUFESVWPAZLNEJJUVVHKPYHAHYSHLSJULSJTLLCNWQWBCBZXJMKC', props),
compute('m_20_12/2: ${c} XCGZNNODIBKRGUGNCWCYPJFPPZGBFEXLTSMMQUIOOJTRHPSGPWRAWGLTULXITDEQPVXFAKHRMXCTZPDHGTOBBHQDCUIJTPJWAZXF', props),
compute('m_20_12/3: ${c} EQWDVFKZRVIYEVBGSMGQBOJZNEBFNVNWBKFNOHZFSPPWMGKCOBVDXKCGRQGKVHDFSTSPPOPSUVJAXWNJDYSPOQEKCSVKDHPFHGSD', props),
compute('m_20_12/4: ${c} ULIHGLVEOZMCXLCDUSGOEYQMULUGKZVBEVGKMTMEGEDAQIDMACBJLUHVCEIEBYDLNNXPUHNTJMJPQEQSICYZENSDQCRDNJNMKNGY', props),
compute('m_20_12/5: ${c} UZRGUWWNRNAKMVDNAIMEFUXPRYEWJADIQJOOLKEBYELNTNDRZMUBGRMHSYZEQSJDZALRWUSSJKKFTBERYXNKVJVRTTPCWHDVBVWO', props),
compute('m_20_12/6: ${c} ZZNGWPFEJDAVOQMAKVTFTBSXDMETZJDBRVWKGIOWFRFIKHFWLOJWNZNVYJDMNCTDXEULQELJULDKGWFIUFDQXMBFUCDTOLORIVUI', props),
compute('m_20_12/7: ${c} NWPPZKIDKACITLVZXEBMMFCKYBMKHCYROLAVHAHLMJBZAMVGQAXPWJVJALSIZRQAXGAGRRSLXUQRLYXVKXIOOWVLOWIUQDBLWXNS', props),
compute('m_20_12/8: ${c} FTIBCFPTDENJDEZZKBTTXIHGDMRXRGCKOVSMWTORIOOZYIFZGFFPBRWROJRPVAXCZDHNRAKNXSGBFAUQHWSSIYKUOBJFHRXSYBIF', props),
compute('m_20_12/9: ${c} SMBRHPLUJQWVJKEWNWJBZHZPETZCGNNQXOFNZYNJXQLTGUXQXNCUFLINGQQRLLOJBHGDTFPEERRQCSVGXHHKNYIDIIBAUYXBRHUT', props),
compute('m_20_12/10: ${c} JVXYQFPPCJKNDUFCSJVSSZYXJITOQMHEZWFEPTYSSOWRXTPOHQIUHKDRGMVYKLFUKJPMGOHKOHXZMWLODRXUPMKMREEGTHEOUTQQ', props),
compute('m_20_12/11: ${c} YFTVRVELOMIFFSQKJTBQPUHTFPVADINEMWNYNINIYEWFWOTCRTCYSSBMYLHCJNCWAXQYSXPBACRGCKBTYWSGRLOPWQADGGWKVEVQ', props),
compute('m_20_12/12: ${c} NJEVXURLCJCAUWUONTMSWIRDXONJOGNQRGJENMRQVTJGNAKHUQULWEDFNXRIZQYSUALJCNAVUJBCKMBJZFKTBRVZDOJXGBBBGHSX', props),
compute('m_20_12/13: ${c} CIHYVLIGKINPFFMZMATJPQWMZGOLETUHJOPTRITEMMBDADUBDKGIFZNHFQFBNFSLJUEZUIDSMLJHLLZYJHXTPTSBHQCNGRJRSHKG', props),
compute('m_20_12/14: ${c} KFASVISZPDGIIPMDSWJDNFCMFZQTICLBBMXAEGCKFFZEOSHPSFYHOZIXCKBJQKMNWYDEWBSUFYUUYBGCGWDPMRYCZMFZZZOMCFMS', props),
compute('m_20_12/15: ${c} CXEIJDBFQLMUWJQALPIONWCPMCGNEDEWWNMDFSYPYBNJTIHQXGYCJFLJFWPNGWVNFIKSWQTFOPJRINNHRUDIGTWFFSVGXWPGJVCK', props)
        ].join('\n');
      }
    