
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_9/1: ${c} OXXWXYVOJHBLYKVCIIXCDISPQPOXXGXOORFAIGHMOQZNRLUGNONAEBLRJYFATBFKWESYETVSJBGBTHDXVIGGMOJAZUJEMFCRRNLN', props),
compute('m_20_9/2: ${c} DGQSJOVTUEVNYZZHFTCFNOFYSKEDTFPROUCHLGPFSWIPFZTNNJEEHCXNCZBAZNCSTJPHDUJJYQZMCPXGWFLXXDVFMQFFFSVLBZTZ', props),
compute('m_20_9/3: ${c} UOREXEEFALXJJKRVAJWWWPKCXASPLHJIEEXXYICCYAUXKIMMLRSBBNZVUVEMUZCNRQKOASPMUOXOYGVVHNPZOCPHYVBZKFKEHXBL', props),
compute('m_20_9/4: ${c} XRERNXLLBEYIHGRSBACWLLUWZXMWKQKNDUSHLSRXVZTNJIVBILSMJPHUMZMQOYQTQQGEEIWSYNROEJKIMGPFDECKTMARPHRFNTSZ', props),
compute('m_20_9/5: ${c} FPTMSWHUYPQKFBDAVAMYBZDZIYUTABICDRIOOCXDLYTZYQEREZSMNQBFJBVTLSKJACZEXIONIPETSDWMYHARHEXAHNGROWSHUMRU', props),
compute('m_20_9/6: ${c} TRPIGKWAZTHCMERMAIZNRNZXVYCXKCLYXUFCRGXCQOFMIZQHWPRBTPOFSAEQIDFHRKXOMHTPXHQBOHUDGDITELRDVBAHFSHKJWQJ', props),
compute('m_20_9/7: ${c} KNTBGHQIYNVZBEFREURFZGYKMRDXECBSOAXGEXUWVBHZGIJVEZFSQOBRVWCNSISFYFEPAONDWHWKLXNRFJJEKYGVPHEWBLGACMFQ', props),
compute('m_20_9/8: ${c} TKLYHUQWMZATQBCTXDMDZAQQVYYQJIUUIZAUIMWLMTHAYQVTUDRRHFZILOZDUWYRQXKBGDPYSYAMBKUFRGVMHMPLSOZTAEACKHPW', props),
compute('m_20_9/9: ${c} KHOMKLLESBDRCGXXRDDXKBNJKMORCTNGQOJLDEXMSXQJNXGRKKRKEJCKPGSAYPYINGXSXBSOIWCGFDPHGXYDAETBZIKNXOMHETEJ', props),
compute('m_20_9/10: ${c} MYBHFBHMKKXAHFCSIOVLMNULDQHXJVTVFTBNHNNBIIHBOYJFOHTETGAJHDYYDGJZCFKXHPVOFNJTJRWTMIXZBYZROBSLOLPFZOUL', props),
compute('m_20_9/11: ${c} TQMAQLBTKTUBAFMHQFLVNMKQERGFWVSPNSDIMVKXXGCFAKACGMBLOTDKQSTJVDELHWIDHUCBHECIJZATIEFIYEDBWJRHEBVGWEBH', props),
compute('m_20_9/12: ${c} OUGTTZMOLURSMMEXKGYAOXJGZJGAMFQPMNAZUGXMPNUVJNNQOSGUFBWSIXIYKKVGVOCWNPBJHVHOHZYZURLAWJFPTKJXQNGAAVTL', props),
compute('m_20_9/13: ${c} MPIMMWYJZWOKORKSSLXFJJVMRUVZVRNZNDMMDJRVMEMNYCJEVGOYHCNGIYSOWIJNEXUUFBPCMXBXUZNMMJKQHRRGAVFTXUZLYJNZ', props),
compute('m_20_9/14: ${c} VUXDLDTRWXBIKQWDSZWTITVTQZWUIMROFGHZWRPJMTLZPOIZYMJCYSGDAQUZWTSDUVWCXXZLHEUGJMUXWSITPNHAICSZKYIIXJTI', props),
compute('m_20_9/15: ${c} INZSRCEFFHOTESWLVVCNGNTGZYFPAESLVCBPYLNPYHMYIOSRSAZUMRUSFPNOGDWYUANYDDZOTYRQWXNDNBZVVRMNXYEDJQCPXUEP', props)
        ].join('\n');
      }
    