
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_7/1: ${c} RFLOTKZUFCBJDHVSTNJFNWIZQSNHMYZSXBTXMEJVEFIAOELVKHVRQHZDOZBPVCULOOLIMXUKSRGFPUDYXNQDEYGNBFRZTHUCERRG', props),
compute('m_20_7/2: ${c} PINUMQJWJSUXLPRMRQBRTBWRVBJVLVIWRTGWQTROXCTPPFADXXSBUIYOARMWGYZXUVGCJSQOPREVOZXROJRTTZIPRDEZCLBTDRRH', props),
compute('m_20_7/3: ${c} FBHUBSTVMILKZGJOWXNJKUHPZCJIOEYTBJNCSAWYWLHARDWLUFDECFCQLAFXTDJYIHTMKQOSMFMOEQFYPTSFVLOZGUXNDGWMJPVC', props),
compute('m_20_7/4: ${c} JTSCLCWHBQAANFCPUIBZMXXOAAYPKMTFHCGPQTLEXGMQEGIOSHERKUXFTXYYBLHFAYTTWJOLJPMXXTUCCKMXXZUSFZRQLGNVTVSK', props),
compute('m_20_7/5: ${c} ZXWDWQASKAGTTHWHEOPODSZNNBMJMOXEFGVPNZGZTZHAGZQUBHNRPZNSSIZJDVKXAUEUEXTRQAKUVZUOPDXQGZYEVIGFNCWKGTTS', props),
compute('m_20_7/6: ${c} XJXZIRCEXQTWYXCZKOVSTBVXGLFFBCOGIFSYHFRVISOXGYOIYWRALXWVPQIYALWHYHUFDYQIAOXMTIVQHQVBVGFZDITTUUTJVKCU', props),
compute('m_20_7/7: ${c} NRPYIUNPVBWXNNCKWRLWDXVJXZXPRHVPYYGOGSMAZRBYPDXCMAMMRQDHPCLTUMJUXGXTGDRBDQUMHNLJEMEDPALBLFIMGRUNASON', props),
compute('m_20_7/8: ${c} IEMCCBWCCACHBDJVKSJERIHDFIZKBMCURITAWYMFMYLXCGPOGSHLBSNQTFPSXTZSURURFCBFMDWZSMKLVMVELTXRZZVIBTOBYOHU', props),
compute('m_20_7/9: ${c} LMKSDXPPTILMVGFJBHLOMGVFRFYIDNOEVGBLHFEOKWJFYDNPSKIQOCJZDPBXZMBWXNCAPRHZRNUUHCOXTXEBDCRDQODGFDXOTBFX', props),
compute('m_20_7/10: ${c} AHUXLHJOSFIHZZTBBHIAPVFRMUERZSTEPKFNXMWLWVCZQKYEDWYCELIWUPUIWBJTYUTIFPXJAKJDDCMSKVGPZGJQFIBRJJBELQRS', props),
compute('m_20_7/11: ${c} MDMBWBXEAJHYBTIDKBEPMVXQHFHDRTBQPOOAFERSACXDSFRWIYNYMEGGXVIHFLBCXBOCLEYEZQFJQADTNKGKLTYUTPTQBVKIMWDW', props),
compute('m_20_7/12: ${c} DWBLAHCCWWAUHMBTXHJUFOIWQXZIPKOSBZZWVOHZKSEESPSIFRYONSKJFYWYWTTQKDQOPQIUPEPZOPUPZLZLQUKFUDDRCBGIGTQT', props),
compute('m_20_7/13: ${c} AHYRCXBVYKIAHPKZHIQNHIIZZZBLNVQUBZRPSITDYLDCXLEELZWSKVDDRLATMFKBHUBIWMNYAJEPTGZOPXVWAYCYADZDFBAVBHII', props),
compute('m_20_7/14: ${c} PPNRSFCJRFYJETRHOTHNVIUGVQTEUGUFXFIBYRIHMLOJLLRBYEBIGGXBGTJMWPHEIJOXVRUDLVSRXCBXWHPUBAIJWJVQWBAJWBEM', props),
compute('m_20_7/15: ${c} SCFQDFQEAHGQTBXTYMRRCXPZMRDXANCXEZCUNZVNNTUKAXUYIXQLTIXZVPGOZFFGWRGEXAEGPVKQLAMHQGFQQPJHJJRWCRULOHJR', props)
        ].join('\n');
      }
    