
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_14/1: ${c} LKKTHUTFCBPUOARMWCPNMCHHTFPGNYANQETEOKGWUXSTZPNSRNNCWDCBECXCFZKZMGLSTRJWUSVLNXLMXAYZIIOVFTGTIUXLXQJN', props),
compute('m_20_14/2: ${c} XCZEVGBPZIYFKHYTPWGZUTZQKSUJMXYGGKPWKKVVPWWADUJPPJWGKOYVEJKUTWXMKQZGPHEOEYSVIEINMEKVEHMQETGCRWKQIVAY', props),
compute('m_20_14/3: ${c} YSSUJKGSKHAGPZRMUCAMTLQLPPNLWAVAQDPCEBQIXQIKHVIJSBPPIWNUBVEKCXNZMSLWRVAVDWSKPGXXIIPRCGRHASQWIDNNXVKF', props),
compute('m_20_14/4: ${c} ZOKNWJQWKHWZTQLGISABKHHSQGIUFUESYYLUMSJHEQLYGEVTXEMSGHOYVUCHZBHWBZWEHGSWKAVHUNSGKQLFFLHKMSGYARDOVMYI', props),
compute('m_20_14/5: ${c} QWUYARGXSMJFWMHQIWTJZOGHQODFQYUAQYRSMWKTSZGBOQDEAZNGJWQABYFIVRTQMLGOEZTNROROGNZKPYOLDLJDVSNHYVMNVBKJ', props),
compute('m_20_14/6: ${c} RVJXLAIWRQHWUNXGYDQFMBSRAIZAIBYKOYRSYFLCFOMEBJPMFQLLAZFZXFJEXUOWEIZJWWDVIDHREZGGDTEGEHHSVMJOPNYPRUQN', props),
compute('m_20_14/7: ${c} DHMHTGJCYFKCYMBNYIFLUCELGLZWBGEKPWWQQJASVOCGHMRJOSNVYMIDLLZLTNFBAWWBRNYJANVSLMUMIQABAPDSLCCOAXCLULUG', props),
compute('m_20_14/8: ${c} MIQPMDEEKLVWWKSSUERADZYCLJRWAVKXVWVBAAFLMMDIFAYFRWTHECUWDQBXBKLMNFFFWYEFVKSJIPVVGLHHBMZQDIMLVDKIYTQR', props),
compute('m_20_14/9: ${c} YCUBCNPZHHDSOZJVDKPOWJDZTKOSKIGSYQQPOTRGORJOXJSHVZXKIUGUERLHSOOVMMPXRZJVWEIHQHLEBXPGJFEKVWREMZAODFCH', props),
compute('m_20_14/10: ${c} DWHPBLSPJBPSUULYPBVSYZVIJEBRAXDVKZVOYWVTFVDKTTCUENOGTVONCRLDSBTRZLYOVDBIYHJVVAPOEMJWLAXOJTWOXMCNCPER', props),
compute('m_20_14/11: ${c} KFWFEHFHIYLGWAZRIWOTDEDPAKQOCXJVQWRTBWHCIJZCMABUWSLEYZLPFSKXDOJWSLBQZOUQCTOYHUKLOCBUZLHBJTBHNVPLUKYS', props),
compute('m_20_14/12: ${c} IPVJIYHNTCBIGLZFSUAYDKYVYHPRHZKHECVJLQSXTZNBYPGITZWAXNFSCHQLFSVMWOEVVYXOEKCPALTYGGNTWGNIBYLQJSRNIBCS', props),
compute('m_20_14/13: ${c} MRAIEBSDWFENESLVHGREXARJERUAFXPNWVKGCSEDUYJZFZFSXBDCHIFNUXYLCFSDHAKLFNHBQGHLNXNSLIHJCFTXCCIKSZSUWAWM', props),
compute('m_20_14/14: ${c} UWTJRIJGMZGAOCYTPCLCHXJWLAWEVUOKFMXDQJILROJGFZVBFVLRITXRNUBANKHTXCCHHDPZFXHDLPMXVDRHTRJZQWJCZPALJWHB', props),
compute('m_20_14/15: ${c} CKGATSVUXPWFMLIQBJFNMXMNJQWAZIODJEHOEDOQBXIHNTZCIGTFMCLGMKJLJWPSLVZVWKUJVZYIMQRCGAMSAKXAFIIPWULPQARN', props)
        ].join('\n');
      }
    