
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_4/1: ${c} BAFMGKOCTPMCZCSPZDHCZLLPZLUWKJEBCVLIVJIKJFBGMDYVSXWFPTKIEHFLKITNLCUVZBTAOCVNHQGMHRMTATARPDVSTXAMDKGM', props),
compute('m_20_4/2: ${c} GOWKPLQEAHUIGQUKMNGOTQFYILCZHXDGBZZVHHUUNUGDJTDSKZDNJJIOFHOGQDUSJUALMLURZXVDKLDFQRPAJKWRCBHIYSXJTTSM', props),
compute('m_20_4/3: ${c} VAOJTFDQABIBUEAGXPABGILKHFVODIKFYNIRUOREBAMFKPPUOFGBHNDLUIHMRDIKUCJXQRIUNHIOHEJZAGTIFAQGRYJOUPTMVZTW', props),
compute('m_20_4/4: ${c} NHWELSELFPLMNEEFEUNOCPFRSYNUYAFFOWCDHULLHVWIPNJXFSEQFMFXXCYJSEAFYDBLKMKJNGRVLYTHFZANENTQPJTTFOXOOSOO', props),
compute('m_20_4/5: ${c} YZJTAVZUOXDUKVULUAOZBKDZXEWRFYCVSQUZRHNMIWHVGSKDZMOWJIQBPDLJUBBWLESEILHAMIZYXBDRYKWTFNSRGQQZGLJWRWYM', props),
compute('m_20_4/6: ${c} LKNGYHORWBYGMFXVOFJNKZLBMQBJCKIRASISUSYCRAFLMMXEUPDRUQGOTLRPREKTZBWSOTUBVHVNQTPQTBOXTLRCVOUCSKBVRUNP', props),
compute('m_20_4/7: ${c} LOVBXICYYMXYRMHSCCIYVHWTDFSRXAUVQARWEKYNASYOUOHHYZWMWFKUCWRQCEYWNKSNQRFOCIGUCPRAUKZLPLWXZASGIUFJZOKQ', props),
compute('m_20_4/8: ${c} RYAFZRYNQXAIGKBYJMESQJHDUABZGHRIHZQJMWSACSIMZZOAITSWEKJWTEQXPFLQDXAOPBNMZXVIWLDFVFPEJXXWAQOOOYKUMTYJ', props),
compute('m_20_4/9: ${c} DTSBNBXFZSVNFWQQLQFROECMCTMFZZXECNHHPOWTNZDMWLTLQRHUMOXHQIWGOMDMAPBTSXKICYDFWTZNGMAZEXULBXYVHBEAZJKF', props),
compute('m_20_4/10: ${c} WVQPUOJFRPFSFOAUROKSRQHCYGUIBYGMZOWBVLJJBWWLSFJGJNFMXSEWXFNFTBDEQJKMZUAWTEQAIFYJPWCNFQGOXPYRKEGWLDHI', props),
compute('m_20_4/11: ${c} HSUVWPLNBOETDONBWZWOTDEFSYTMCOUUEWLZYYMDCBTHCEJUSVFNKMDGFLOCXPCLFZBCDFRHRGMZQHQIKLJDFYIJXDNAKPNHTLST', props),
compute('m_20_4/12: ${c} HZEXXYZMFYCYKIAXJKAONZWCIAUYLZDUVBMFPJNLMHCOWRHNQWQXQZAIBUZYJDPZLXABCKDINWPLGPRZPPWGPHKBHJQVEZGZFLUA', props),
compute('m_20_4/13: ${c} SGCCPZOPKLYRRTIVIQQGXCSJXUSNIAYKKEKERXGCKIXWYKDDTDZYRSERAIZBISXVOZUKLJUDGSYUBQUMHARSKBTMMLMKLDIAVMZT', props),
compute('m_20_4/14: ${c} NIXHDUKMSVOTTURASERLPVVKPATMSYCQOXPTJDAXLLNXUKCNUSAPQROEMUOGJRXMVLJTPBIOIQZIBFCTTJULCMNQNJBXVHOGUBGM', props),
compute('m_20_4/15: ${c} FICLMTKHCHXCCVNGRQKLDOQEGCLMGTSMYRVNCQUKMWMPVKVKWHFDCRBSPCHLRLRQOPQDOYJJHAKMDXBSAYOMSJLLSGOXLZZYILZL', props)
        ].join('\n');
      }
    