
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_6/1: ${c} GMJTZVNCALTQNFXDOPBAGJGAPGDUKFGVWMBFEZHFSPRMJINHIROGNHKBDLWHPUUTDPSRDKFKCGKJCDEMJJBEIPVKVKPMRHQMAGRQ', props),
compute('m_20_6/2: ${c} WFYZBGQZAKKIGOJHRHIDKAIWEGAACBHMKJXMVTTJPMEQKFTQFGLPDSDHQEHSXXGYDKTRCTTDVMFGYZMZJLZSUTFSSLSCIQYFUEYX', props),
compute('m_20_6/3: ${c} FHWZJCFKYMQJPLJPMMNVRRWQLPLDCRILUOWCCQXJOXRBOHHOOBHFYGNJCIHZAIEPVCAGONKFDPONXALXZPQIICSKXCOFZGYRTJME', props),
compute('m_20_6/4: ${c} TMHQMQOYWFAFNTCGJXWKLXMABXLNSTKALLCLPFVYPYPDEFNWMXCCWFVBFREMUZGFLZOSRKBMXRKBQCDAIVUIJYUQLKORNQKYSRIT', props),
compute('m_20_6/5: ${c} LRLFXSVYZDPTAFWRYRCPIWWWPTOSJCCOKTSLQGIEMLUDBBJNQLJBZOIWWQAIHAYWNJHVLMSHFIEUDZCMLKVUUDUMWZTXLEDRHPFO', props),
compute('m_20_6/6: ${c} RHEQDVESNNCHROCAAHWGZRVFCVTJXVDTBCOBFSACOSESZBDGTWMYDBFXHXJZTZMZSYSJBTYMICBSICPUDNKSXRDCPVKNXUNMJLMQ', props),
compute('m_20_6/7: ${c} MUMBHANEQZDLEMNTGOURMAJKOAHFPRQTDZVSTIOVULRQZDFJKSVEBKEVARFVTOQQLDZMFZCLMTCBHIPTVLJMWEKNTTRLLMSFORLZ', props),
compute('m_20_6/8: ${c} WEACMTSBUAPAQUGANXFQKCGLJQXTLWIKTNOZFPLYJZANJYGYDHELNTSZRYBLJQRQBLYPMZFYPGRFZEKESJWXKCCNKXXTTYXKXUKC', props),
compute('m_20_6/9: ${c} CIOGATDPYBWASPBSHWWVZLMRKAXQUWZECUZAQOXKGHPXQTTFMZBWXBCNKDUKQCOVVWAEKIKRGJKQRZFNSDXRONPMHZUYCNUTMXYX', props),
compute('m_20_6/10: ${c} NRVKTURBTQWTRMKLWUUSIDWKYOHDZCDHKKBYOMFSYANUZUGDGOOZIDYUFAAGNMXUPGPAMIRGASXMQPBVBVSUKGGYEQWPKKFMPSGJ', props),
compute('m_20_6/11: ${c} IQBGCKCIEUEXJIAUZPUMPQGYAFWCYDFLIDJJNOZODGYEJFQVQOQQJARBPRUQRGIWFHFYXAGRYNVFJFEYOPHDLANUCIFUQLCSLCIR', props),
compute('m_20_6/12: ${c} QKMAMGQESIUFMWDNNSRPDLYJAMVKQQJDBDOCJHSCHYSDRDVYEWZIVBBZKEURHVOXZQFMFWBVCLDSSNDJIOETIMXCCNSTIPDMPHJI', props),
compute('m_20_6/13: ${c} OKIBAKXYENWFPEPBERDSTUIOHTPVGKAACWNRVZWMCEMYWJBFQUBSNUQNWMEBSTBELGYXMSNFHTYVATMQSMIMQQPPSYFFAQWEEMCY', props),
compute('m_20_6/14: ${c} TWDOJUJXULYNDXKWGKLOIUIYWTVBEEWPXIAGQEPWBFWJCJNMDGBSXJYRARBDYDLZWQLPENTFCZNKVWTNNUWAPWKTGMHTXIOFBQNV', props),
compute('m_20_6/15: ${c} KZORPIQZWNELADNWDGBVLLZTPJJWVWNDINYTFBLPCJMYRIEGDKDPXIPLCWFYOQJQNYGOZLETEANPTPJPZKTIUZZMHMUEIDZWNZHD', props)
        ].join('\n');
      }
    