
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_20/1: ${c} AZRZANQHLZEBCCLRBHGLPHZLETLDDLXXQIUPKRVEXLRGKGHTBXWSUFVGZAWTFYPMSAQHTQBKHYQRFKVRTQRVDGKCEAWXHZILCOLG', props),
compute('m_20_20/2: ${c} KVXWPEOMFCULFEOZVSJZYKHNIWCCGSRGMIROAAFODBUXVWBFMSWYPGMNKFHKXFRMDRAEYOQQBUYMXYRLCNULQEDVNGVSFEOMWSMQ', props),
compute('m_20_20/3: ${c} ESYIONSBOVUGFNGJSHKABPRXIPHXGHGYXGVQIEEKYICNXMRRFZDOEOLEDYBFEXOZDTZDCWBACKLWLMGBSNERSGASYEMEOYMUUYWP', props),
compute('m_20_20/4: ${c} FMLFGFHVHVRUSBVLALJXKLYJSRDDGONBBRPXMJXZTSUXFREHXTGGGCNHFVUEKONWOQMIDTVPBUJBMXZNSTEDOHTCBXIKMXLUSJXH', props),
compute('m_20_20/5: ${c} RIOONXWORSDXGPZHUGNPMXCZDZESZHZCNJPMMRDATBBZSYIHRDIGBPXYLJMLQYQNYXXDSPVDPEEDNQHHXZMRBQVNZINUGRJDTAMW', props),
compute('m_20_20/6: ${c} JWXWIEYDLHZWXAYXMAFLUDZFXJJWZUHISGJMRGFRUEDVVUGFLJBTGLMYXSUKQEJUDMJZYWNJETYLCGTCBCXKYIQRFIFJGTRGUHOE', props),
compute('m_20_20/7: ${c} GLLCGLYLTDJOKIONWZPDWDOVMJSFQZNWKJNBCZIPJDWDTUGXFPVDQRFJZOJYWDEKVAZFNPGPXGTBMGLBAKHFTQMICFKDCEKTWWHQ', props),
compute('m_20_20/8: ${c} WBPNSFHNWLXCCATOVIUGQJUAOJYGCBQOEMCPGRLIJPELQYCSJMFZVKMHPWWMCJLDZBDAXOBTLPRUZYVTTBNUUNTFTBNRWGYHWJGI', props),
compute('m_20_20/9: ${c} KDOZLESMSNXXANGJMGNWVQECNILFWCGVSUIDJFLZQTXVZVAIBTSOVSSQHDLNFZVGDQVDPVSRZCMYPIGWYQEMWNSVXGUFGAGREUBI', props),
compute('m_20_20/10: ${c} UPTWCWSUGWTYAGFWJLXVORHDCWCSBVBEZDBIHTPOXOLFHTLCYLQVEVDZVJDRFMZAJXNAKLRDFJTCTBLWIEVLDNPSFKHUOQXEPRRG', props),
compute('m_20_20/11: ${c} GXJMDMVGZHUNXTQGDDMZKKHTLMSNWAHQVSWSRTWXWDWJDSOAGUYTXVICLBGTTTFCXAEKGXNEJBNOVGNFOJXAWMUKZTJWNOUHMTUB', props),
compute('m_20_20/12: ${c} SLDNSFCDCDFFHCBSAOPLMMSXIYUJKUQPTERVEMNCCLPMXVRTLDWRCDQAEUKPWARXHROKBOJBRVFVQCPGLJNISYIDFIIBYROBXAEO', props),
compute('m_20_20/13: ${c} SMQQAAHXWWDHJXKTDVCZGWPGKAHPFUBCAWJFMCZKDTXECHTXKSEGOKCMUVKGEBVBWSVMKKKTNCBKZHYWVAVKFDBEQDTBPYZPWGCG', props),
compute('m_20_20/14: ${c} EOSOXMJTACYJNKMXOCMDRBHBCSYEBTCRMOQMHTFCVRYKVASBCDFVEGMKOGQMACZTWYZGLYEIEIJXMWWNBNCXNSNZHQAXTVDPJCCY', props),
compute('m_20_20/15: ${c} ZOLRLEBGNGUROJBCWRSHLXJPRFTNVVAGDRYAWFFIWNDOBXJWDZEOIXMLDVJDUMPAQEVXIYNFRJOOREKSKXEMPLOOQWHPYDQGMOZT', props)
        ].join('\n');
      }
    