
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_5/1: ${c} SYUPACPPMVMQKENFVGAFPFHAGFVMLCTBISICJPCLIWXKXIQPGCBKGBIBZAKHBXKSKPULALXOVMLYFGAQIEKGSVEHQREJLPYSIRYP', props),
compute('m_20_5/2: ${c} VKBJPZTEGQAHOUNFALJZQUCXZUMTCURIGUGLYKUIEBLBMVDYPLYSJAEDVXXOLRVMXZWEKJMLGTOVWNZJRQWAGSSFLUIGYDNSTSFG', props),
compute('m_20_5/3: ${c} BSMZITAKDYQTDKQFGVXTURZABUZYCNGKZOFQOIURQHRCOWYBYEGHFNTYMWMGNOXIYCVURCUNIMYAXUPCEUKAAIIXHATZJCHHYYNW', props),
compute('m_20_5/4: ${c} XAYYYPVSKJQXGAJUDUYHZRBAATEVJHSKLKKRIYRTDYRWJBAZEFRUTHRSTQXKFWKBOFQUOUJUAAMHXQZAMKPDVFCBJQRTXNDXBKMD', props),
compute('m_20_5/5: ${c} DWREHKLCBOBMBKRJMBWYIOTUBMWXNDUXMMMPELIKCSCGWRLYBVLEDTUSLLCKOGRZZDZYAVCZYRGYXRYDFMUWFBRFNLLEJLYCXPZR', props),
compute('m_20_5/6: ${c} HYNCLIEPWNHZCFHIPIJNYKBAZJSBFSWJVJVHEEEIOVPFPYBJTPQHDVMUOVGWBPCPHNHBJAKGUWVTABLFNXMYWQKSCZBMOOZWJCMS', props),
compute('m_20_5/7: ${c} KJXFQLORGZWTUUWAGYGXDRLVDVTXTKPZCPGOKSLDEQGBADPKCQSAXVBGGXUDLJJOWVLFFGOCAPZJYMKEVPROIFRGJVBRTLGQGGUA', props),
compute('m_20_5/8: ${c} VVBEKSLVWHHDWARAUTGXFORZIOUACGRTNAPWKPOHVPKUZYHCUUQCPWVHGLBXJDWNVMXHBNKGFWRGMAJSZXFXMGVCCSLELADLAODF', props),
compute('m_20_5/9: ${c} BMQUIKNVKQXPJCAMRZHNSNTGFBDJNQLITCVXYKKEWWJWGRNHDMIAXZPORBVSCVZZPNWEGDLUZIOWJZQOHVWABYIYHISUCGTFXVXZ', props),
compute('m_20_5/10: ${c} HFYJQBCJSJYXPIZIYQMROSEYEMYUVZEYNVQKRHNRFWTFKKBNSQVBFQZGRYISSDQCMMSDQDIAAWGIOZGPZARMLMUFDJPXBSJIVZRW', props),
compute('m_20_5/11: ${c} ANEVFHMAPOKIYUKZNFVOXAYAQYFXYXJQEKKZKIBLTGMFOQZJILRZYBELSLSTWUJMMLZNYXYKXJCXQAICEWROMCRWDSUASVBPAZLL', props),
compute('m_20_5/12: ${c} PGWRQUUJXBWICCDEBSEMWQFRSHUSARUIQYFDXPQBGQFONXDZAWHAOUDZKKCMGDEFVJOAEBIPEVLRWRXSBZRPAIRRNRTEONLWBIQY', props),
compute('m_20_5/13: ${c} MAWMBBXDRASNILGLLLCMKIQGXHNDRJRGOSTZVTGMWPPUAXKNBWODXOEUMCBHRPTATHTLCQRZHNZJSZIZGXNAMUZCGUYRPADZYLWS', props),
compute('m_20_5/14: ${c} PUOEWPXBKOXTMXIBOUMTPBVFHMCTUHQBFOVBUTWHNNXDEHYQSJJLWCVFWKDRXKFEYSCDEKZHWRRQMHMKKUVYYZCGGQHSFIZSEGYD', props),
compute('m_20_5/15: ${c} DGKISDVXWEHDHJUZHWMSZVOJSTCSLFBHJGTTKATFQGSYZSVVUJYZANEIHAKRGABVLTBYIBXNYXATXBTPQWRTGVXQBIYNLUDSXYYW', props)
        ].join('\n');
      }
    