
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_18/1: ${c} UVGULJXMWJUCUUVUMAWHCXESGCSBKFAYECILPKHPMTVDTSBJQOVZKLXTKDNDZHCDVFIKHBAGNCYNRVAUIQTRHRHXNFRKKVZJUEMN', props),
compute('m_20_18/2: ${c} DIMQCLWCYBUUQGCFSFOMXQXXIRICSCTIBVFVMDBTSWTMEQDAPPDFMJTCIIZVPHBHBEWCLZQIFYRBVGYBPPOQLPCOUIMVXNBEODJJ', props),
compute('m_20_18/3: ${c} EYRJDLWLRYSCPELSDCOGIMFOXQZXWZQWLIGIYPIVQDYHTAOJOUMVPFVRPSOCDCAZJRPOXSBMZWEGBEHWFXINHIWRNQUWCWJSNYIT', props),
compute('m_20_18/4: ${c} IOIXOZVCGHXCEHHVIJISVXKIAQWODWLSZZKQZGMCOCSCEPDAZVKVKWLTTGOQIYRWQWYWZAWTDTCRBKAMDAYHOQSGNGHIHZIWRCHP', props),
compute('m_20_18/5: ${c} ZXUGXRVJMWCDQPCWQETLREKHNLIYGLJJAHVLMKAQWMTAKNBIGXOFQBQZXKRBPBBQWVIURZVKOTXZBNAKLLLSJODSAVLKWYDBQHWT', props),
compute('m_20_18/6: ${c} IVFHVTGZWUVMXHERNKOGKOYTBMRIPYRNWGHRMWYEINUCHHLARNXCMQLTXGXDCJNMCFBQBRWUWPNBODMGEOTARLCSHNEHLDGBAPWK', props),
compute('m_20_18/7: ${c} YNIONEZHMLPIGCZQSHCIOPKVUVBAGXCZNHGUXVXWRKVVFUKBFMIGHMOLZXPOEMLIUHWDLIBBGRKIDMZYDEZBPVTRUGKOZICHTSSK', props),
compute('m_20_18/8: ${c} EMOKJPCCXGEZZJUNQJSQKINQREDHKENECXIWFMLPEUNDRVWQFPATERXXGXIAAYPYJTZRSGOUFKPROQIONMNUUIUWSCSIQRLCSRRR', props),
compute('m_20_18/9: ${c} UCXZTMFIAVHLRQCIOGAMEKVWKSWQZYAFHYZNFQOEFKAWPVGNBNHPOGCMVXAYIRTVUNRPDMHSRFRYHZEIPGFKDTFGFEHSBOHGPHNS', props),
compute('m_20_18/10: ${c} JAHVAMPVHXQWKUXZNEAGZUDXOOUVYBKDWIXCZSNCGUYBVVWYUWMCDWEVBWACDWJDZNIXQRPPXEHPIZZQFFXJZQUDDHWRFMAPNNRT', props),
compute('m_20_18/11: ${c} BVZQNOVQRUAJRGZMHMBHKCBTCIALBOJLZQCDSEFMYZGCLSPOTMCUMUZEFUMYICSBGOFBQWYGBGCBEHUQDODZNJGKIOJLQQBKAZED', props),
compute('m_20_18/12: ${c} DEUXOUARCZRFOSSJJYAJDMPUOIILVVNWQWASKRVXUCOTROIEBLHBCQPFBEUTAWAMVXZEWKVPZWHQWKLQXIHCTLOUGRNMWSJIDQGU', props),
compute('m_20_18/13: ${c} KBYEIXCFLEMEADXSQFXSUCPYMTLRKVFSCWOVJZIXVUQVKHGIMYUNBPWJWXTFSFATGASFYVVYCKGYLOTOODDIXPPTAGSFEYNOFLTY', props),
compute('m_20_18/14: ${c} NJEQOSGSXCBDGNZZATNPNRQMTDJFFLMWEOPMYBYWDFMJQIJEPIYEURAZKEXMOAYEEYSQPHXGTVDYQXLOWLBQHHSVWANABVDYAKKJ', props),
compute('m_20_18/15: ${c} EANVCGWUCFPTKWBQVRXVHDNNUHSGDOLFBYXZHWJEZADUSXXZXEEPWTSPYHZNQGIGGHDJRHSHUUBHORTUPCWZTJIWHYPZGQFLSETM', props)
        ].join('\n');
      }
    