
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_10/1: ${c} ODNZVQTKLNWPKWMBWVUXXFROZOYFQYUDWBZHWQEBGNSBOCOWFLMQMWBQPRSRFCRWKTDORWIWBPRPYDPXRAOXGWCPGVWUVANLFDFW', props),
compute('m_20_10/2: ${c} SOURVYOIFYYTCNDTCOIBIZDBIQIFPHNNJWNGWLAOCYXFQVDBKITJSOQYOWHDBXYLAIJDMOUBXBXBODIESPBEBHFNEZJOQZJLDGZR', props),
compute('m_20_10/3: ${c} PZSJENINVBSYQWAYGVAWTSMKLCROMKFVKLLTEBFGFWRSVADZLSHIMEVQEMXAEVAQJXRMYTSISZUADCXISVNDQGQRYORNLFWSKALH', props),
compute('m_20_10/4: ${c} DODWILUJTIGWMXTRYMNKJCZTFCQKKPNZXWSEMCADQJSBIBQAWHJOIHHNRQJDQZUDNNQSTJFTXYMXOBCEAJIYOWEFGMPQKFMBUYNU', props),
compute('m_20_10/5: ${c} ZDMQZLKRXRZZADMCNERYLTEAKDFKFRJKCXVUMZWFOZEZSOTYZEVWSHNGOKVMXERQWWAAEPUBZSBXYQNILUOGLEKXBJFSWGEOVYCS', props),
compute('m_20_10/6: ${c} LLDTZIFWSSMTERJEWREGBJMIKVXUYTMIARTSWKVILOIEZIQKSMQQIRSSUVAKHXUUQUPYIOKWUTQYRTQTIWEOURXMSQVGVUBRYCUH', props),
compute('m_20_10/7: ${c} UJUNWXMWLJAXQWAECUESQFLYIEYRSZLMMSPLJSDOVMZWJIZECOSRLZRTOZYRAFDLARPNDDUCCRDZOAXSYSBMYJNKKDGNLZYYQYYR', props),
compute('m_20_10/8: ${c} YJEFWPANGWAREIPOIJYGGAZBSQGGGSLAUOIYKSXTSZSCDMOCRTDFUTYWNCUBACRGIUQQUDQHYLYVHSHQHKCQHOIMEXOFSYUNMXXM', props),
compute('m_20_10/9: ${c} KOILKJNQRFNCOQKBLWEIYVNEMIQURSMCVQKDYQIWHZWJQFCIRNXLBXRBDFNFJUFNRLQYMQHCKKTSSDUPCSUWJVSAAEYIYOBSGEHB', props),
compute('m_20_10/10: ${c} FKSMBMUMFPIOMYKVURYBVUUQGETVAFQNDZATYIKTQJRLOCUPIRFGRAXKGXSMKYLTAGMBQLMISKTUTUDXOJVPPDSJEZRIZDEZOAVD', props),
compute('m_20_10/11: ${c} NRXHQFBCMIUHMQBLJRXPXFYAAHDZOKJGIUYXMUPKHBMDPIEOHCOLGBWEMGQUVAARRXFBPBUNEKJUBOJZHIRXGHNYQEOASTSNFBYA', props),
compute('m_20_10/12: ${c} YWQFCBSDVCXBFEPWYLRMBBLOKYNHGRKIATIKNMFNYGNNEWDTTBWGGWPIDSPLSVRXJTNJITYLTTFCTUMGOMTFEYOVZQTRBAJQNUGM', props),
compute('m_20_10/13: ${c} ATEKVCIKBVJCLPIKLHSCAXSQAWMYEVYKSBLGUCDXJIPLSDRASZFCIXGQEFGUXQZOYMHTWHNWMIGEWDLTAOCXUFKJWIUCOXIDBAUR', props),
compute('m_20_10/14: ${c} BTMCQYHQJUILOQBBPGTYNODXVXPOIOZENKYQKRSKTUJOMVSMTWQTMHSDLXRCDVUCDKMVJYKFYOKEFSWUJVHLAPCRQWSTHJKUHJJN', props),
compute('m_20_10/15: ${c} KNFVZGILPJJXMEZJVFMPEAJTKRCRAXJOZJZJKCXFUAJEMSBTEKCCWIUUDNZLJQDCAQVUSFZMDUPRPKUGYQYUQURSOFUUVWCUWFAB', props)
        ].join('\n');
      }
    