
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_20_13/1: ${c} UGRZFAUHTCKLYNEUPDPZNUMDRXCPNHMGRNQALEMHOMIIEIGVXTKUMCPLRGBVYIHODUXUOBVVOZDRTVOUEQJWNBGEDTKSKTLJGKUY', props),
compute('m_20_13/2: ${c} MCJHLAMWBLWEULIUTRBQAWEZFWZUVQOVADQVMWTNZILGNGIDUXIJWTJOZTAEXQXKHQODHLYMSCAPSNFKDPPVEGLWGVQBFZPRKWMB', props),
compute('m_20_13/3: ${c} EHXZKULFVLCFFNGNJWMVDYZDBJYGSJKSVODDEFZVWTUYZDAUHMIOCBHEVJLXIOBDAKWWFOASHPMLWFYWUZESSBDAAXOJEHOXYNIZ', props),
compute('m_20_13/4: ${c} BERLCVSWOQVCXLLFCYNGYWDCOYVOGTWOXSYEASKDUMLBMPFIGPYCIICTZMTHCULFVSPYPFDTLBOFATLFWIBOWEARJKPYPVTYORYP', props),
compute('m_20_13/5: ${c} DLPUWRJZGWTMXERFLFFUOJUJMKKPWBAUYCEVGSPKDHUEEOMSNYFKYKKBIJYQMJNKSGHZGKBYRCLMECHEIVKCXHFOSWGBDRKFSHUI', props),
compute('m_20_13/6: ${c} TCUJBGUGSDKDUZUDVUPKYUIDZHBGVTYPHJFFYGZBMMHXEVKOEGTOWKLMMZGSNXCQBKWHSSPZDCKZZRYXAPRHTWCEKQAFRTTPGIMB', props),
compute('m_20_13/7: ${c} JVZFAMRLEWKDRUAWFUDZTEMOCRNIKOMMXHQFNUGOBYCWRMIAYDCFLFUGCXPZMURAOBGNPMHKMXYIAHTTSQCQIKCZXMMYQZBQYRHB', props),
compute('m_20_13/8: ${c} YIAGSEPAYFJPFERRURYATDMCOCLDFUVCJCGNNERTIVTGYNDVNQUUOVTHINKGXPABFYFLQWXHEYPMKCKSDQLEBKFXCGUPDTPAJUEX', props),
compute('m_20_13/9: ${c} TZNTVPGUKCSBCIOCUHRVZTHIDZRDPYFFPAWTNFKPQKFYSVZUKKXGGPACMRNVQIPLSOHELOOYCOIPUPUJCKVMIWQGWAXDVJQNIIGH', props),
compute('m_20_13/10: ${c} QOQWSEMYTZUKIWHHEODDQDZFAYVKASSBUTHCDLITEVEGXGDCFGIYZHIHKDVYXMKEAFHLJOWENHPAZTXQZOGHBVQRYXDVLUHRJWPG', props),
compute('m_20_13/11: ${c} KAIFNJADVUABFPTUACYPVAIHTEBBBVZHEMPUYJFAAYAZMIBWUMCHWUQLITFVHHGGTFVLBREJTBEMZGNIEPAFJEFNMGGNWKVIJBAI', props),
compute('m_20_13/12: ${c} XVLUPVZFRTKAXNIVLBZUDRJIZVOLIXTSBAXVUYQIPKQZZYVINCLIIIEXHWKJWQUDHJZBEIZMLXSLTIEBFWZTASZAYICSHQWANKUR', props),
compute('m_20_13/13: ${c} ZBNMXODQFERXNDKYPJLTZAQKERSFJTIXKPZITCZAYLTGBZBKTWWFLENRQCJNYXEJSRJXPOPSZLXEZCPENSCLUIQWPRCNEQNZMGEU', props),
compute('m_20_13/14: ${c} PJABUCNIDEFHMYERPLMSGWGYCHRKWUHJFDPZABNSXJRSKRHZMVCJBMSQZIEWEXSYIVPEHAPRETTMCZYLTJWWALNTXIWELIVISORV', props),
compute('m_20_13/15: ${c} VXKZBNAUJEVMEVKBIUGVGLTCIAYTSNSJILIPOPHNNSLIJVWSDCGZOQYJUKYNHULFSBFFDFHERPAPGFVXEGNCZLBRAQJBGUJINADC', props)
        ].join('\n');
      }
    