
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_4/1: ${c} ENZKNGZVBCQNRAUMWMJIQCCWNFQSPHVZYFGXDSLBEEAEJRQQLCQPCYGJBTIUDDCKNKDBPJUKOACDNQRYJQMYNZGPGLBFUWACMJDV', props),
compute('m_2_4/2: ${c} AHCNQPMBLFQLAIBWKLVZRRAVZIHMISJJBLXFSAFBMAJSXDVCZXWTDMYHKDQGCINUGEBVGQYZLWPEAWXFOTJATPWZNHOPMLKBPCSC', props),
compute('m_2_4/3: ${c} DJNPETKGIPFBWKKYOZQZFFVZLVWWBWOQXJFZGIPZCYWOZAVTVAJNKKKAFJJDNSCQLXINZWMCYUDDJFMQWYEQTRQZPUZUTQULRRFJ', props),
compute('m_2_4/4: ${c} ABVHJPKBKXKSWAVGGEQSBZCJAFCOWDURQABQMLPTVUWJOGCAFLYUPRAEQYETKDXUUIXBRLXZWPTZDGVCGLCELKXTEOEDNUSZVTHD', props),
compute('m_2_4/5: ${c} BXDBKFLGGVVABUJHKSEMRFIMLZCKMZSKXNRFMJIFUTGOZWRISNJCZKHVWYGCUPDZHLNTTUNZJLBEPCGUPLBWEGWJGXWLBVGIWYWE', props),
compute('m_2_4/6: ${c} HAZXNWTGBXWRFPFDFOYQXRKWDFHYIGDNWVMJMBUDJDNRGEQRBILQENIEGVVXKDFRRBQRLKAEFABDRGVSOPKOXGIQFUHGWXOIYXHB', props),
compute('m_2_4/7: ${c} GUXVKPLDHYXBJVNFMBMJTUMWNYSXSZQAYROUIGSNNYLCAIDJVMUWWIMIGEXLLREFJNLDJWTSRPFEVDUFXXOSINENOYJMPKMUCGCE', props),
compute('m_2_4/8: ${c} KHUVUUFUJQSICRLEIPESPYASCTMKNBPSRAYMYPEECBFQEMJNXKVFVRLKPSTPFNOFABJJWWZPPZBGRKDUZBIWOGXSTDJEORZGPSAY', props),
compute('m_2_4/9: ${c} RJGPYFSSTOIIAWXDIVWTKMUUKUHWSJOQLTZMDQZAGIDKFYKHBQEYQCPCZSHCIMDWMPLFXBPMMUOPLVKBJKYZTCBXQIAOEYXMZXWB', props),
compute('m_2_4/10: ${c} FGZSLRABBWYSOSINAXSYVZKAFBMNKAYFLHYFTSVGDZBMDVIDSJMJXMEJPJJXPGIISVJRTEOPKEWVHHXGEROEKTZBEPFDHDZPYMZM', props),
compute('m_2_4/11: ${c} SVXBILMAOUXGRCINXENODRWWUIMEZASHQVUHTBFRYFCDKARCELAEDBIPLVVPQXMXBEYOMQPTBZBVVSXYUASLLOMMUHABTEHWFHTR', props),
compute('m_2_4/12: ${c} XVWHDMKNMGZILQNNXWUFLBQMXWRYCDTRZLTERYRYMRKMXCDOFIGJXZNGEDBXYNQGZCDHXNYAOKCRCNROTRRBGSKDOYDTYFZXIFLH', props),
compute('m_2_4/13: ${c} WKELWPDTPKLPEAVAAWYKGEUYJJXNZTTSQUBQAZTCYWCDYCPEZPSLAHTILMOHGNPHCDBENGNNCKWLIRUWWZCYVHHIINUPGRBCWENK', props),
compute('m_2_4/14: ${c} NATJHJVTFVEKOJDHMNDLDCWZPNMUIRQAOTROIPEMMTWYJITMVKGYQCBQLOSYTRGJYNQPHSJKWCIITRVTRWPIKMCITHKVSXSLEERS', props),
compute('m_2_4/15: ${c} WILRHYRZLMMZZWBWPBRNGHJEKPDNXEBBUDRXTPIHKLJOYKMSYBDOZMAOKWRLIJAKYMDQQREUEQOAVMYAOJHSZANNWPVQUDESYIYP', props)
        ].join('\n');
      }
    