
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_6/1: ${c} HAIVOWICMJXJYIUIBQUKDCVYLUWQENYTURMDYWCEOGLWWBCXDWATMCRTTEDIYGNBRGLRIXWXWSETGSJJTKDNPBSDXAVUAPKHNJMH', props),
compute('m_2_6/2: ${c} XDVLOKJGGTAZFCDBWBLLEELGHCOPUGGPVWZKVZPRLYXUQFVPNEXGDMINIZASOXVKAPPXOFFYFJIIYDCHRJAHPSIRJQMBCANHUKKO', props),
compute('m_2_6/3: ${c} MIILENTMPIQYYEHLGGJAFICDVGCRAHSBMFCGHNGNEBFXZCDNCIGKMBVDASQTJZBXZZAXUNXXURPGFZMISVGSKKHNJUHCTEPHCFQQ', props),
compute('m_2_6/4: ${c} WVABKPFXDMIPJUGZOUYVKBMOGORGBNDCLWGQEBQVYDONHVNKHTNYZHSEDTSZAMANCEFBMFSOVCQVSYJQYNCHEUBXPLZCYCNBEJHD', props),
compute('m_2_6/5: ${c} HAQFRCHIHTYYLYNSKQYBWFRKLWFYUKJHCPWOIUHEVUDDKXPICFLTQRDTGHUWYLURTRATUJWNWKAZNWIYNAFJHJQHPNHKIQDCFHOI', props),
compute('m_2_6/6: ${c} NVZNKDEJQMUFGCTEZDBPCAVKSHJDEUHTPVGPZRVPPELHUCDEWNCYENDRDUDPTWSCWXQHGMGOADAREQIDHGRDNUBXEYMVPDYNMRTR', props),
compute('m_2_6/7: ${c} MMQSGSKKTQWTENSYMKRSXWSMWPDOBEDOTTNNKRAKICVZCTGZHBUQDMPHNLABUYDGPIXYCUWPZTPPEBHTGKQVRTOUNQEAWBWFHQHQ', props),
compute('m_2_6/8: ${c} YDRJGSETPIBQQGWADKNFLRLOGCPSOOLHAIQTIRLHRVJVHKIJBICJEXYJDGTJRBIFYBUNGBANSIVIPKZSSOATIEFBLGBPSHSJPCPU', props),
compute('m_2_6/9: ${c} SFLWKGJHMHOLIBVTKECHYGDFGCZZQWYYWQSAWYQKLZHTTLFZHJUWRFRYBAIBUFWISFEXUXCBEDRBZYEEQLEQJBQIGYKFICQNFPBZ', props),
compute('m_2_6/10: ${c} RFZFGGRWGPYXLDKRBFCPLGUHIQVRXOUUDOLDCXNRWJYGEIDBUEKYYZZQPUQLVZNQIWCWQTCGCCQXFZTLLDPLZMATFLURACLUBYSJ', props),
compute('m_2_6/11: ${c} ILQYBTETMQEYBHNICXULKRDYEBKLISWQMGRDAECZVUGNWOASUGYBHPKKGSFSEHVNPKIWUJFHZZPHPKCILCWQQISGAIRRBANXFBIC', props),
compute('m_2_6/12: ${c} QDEOLXMJIAQNHYHFGMTEJITNOPFXXJVVNOAYMUCLVAVRVSCAAMDFZUARJDMZZJDILKQCKCLABRXZLHORVPFSDFRUIMGCRQCGPCZH', props),
compute('m_2_6/13: ${c} COFMKPINOIQSLMWCBKXPCRPYNBAEUJKDTDJVXESJXINUZTCCWTFQCCSNKKGPFQHLQQABZCTDYNSNPKEERQNRCGIGXTGZTHZUHZEP', props),
compute('m_2_6/14: ${c} MGSMZFQXHPLKEZNBQHJBWSSGOJDCHEZTTGNKUWKDHKSMVMOSVCLQWGDNYBEFGOVUPCFMWGFYFQPOMWFYQRHPNZIFPZWDASWLLWSP', props),
compute('m_2_6/15: ${c} CFPIWNXMZDUKXBHTSDQUMHFFJQRTRBQBJVFGNXXXFYARXWGDJKPXVWNBLVFADVVZBHIOEQWXEGTSYSDJENOIHSWCTLETLQUTJNDC', props)
        ].join('\n');
      }
    