
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_7/1: ${c} GZYNDFYXPVFCHMBTNRHGKKAKTPWFWUOOGBDJKTKVFLZCZGIKZOJBSDYCDZXSCYFRDWIIJBJIWWKWSUCVQOJAUFIGDSBEQENADMNI', props),
compute('m_2_7/2: ${c} AUUJZQEULXXJNNOQOIYBKPSARWFTWRXHWLBSHQKSWPAMRDBJYWWDDSVRQPMOFUHXVLRBDPRCHLSWBWVZEXQLEGJQDOXYOBOADQBD', props),
compute('m_2_7/3: ${c} CHOCQDSDDUZAXIAIDIYDUITFYSFYTXGIDUSHJPKSLUYEFBAGNOOWQGWLBFHBLPQYWDUNYEHZZQPNGJKUHKYJZGPYIAOSWIZLOSPB', props),
compute('m_2_7/4: ${c} YBFSYJIHBHOZGHICTZYHTDIYAEUKHCLUZCCIZXKMVOXBZENZRKECOCYZELBQSZURAAFBLXVVTDNTUGIMKIBCCAZGFWCGUSLGDBJA', props),
compute('m_2_7/5: ${c} SDSCXYUIAQIQJXRRXFGSLEGQIDQBVOOUGCLFOTUNPCETCDBNPHNDHOMTUDNZNPAMPRDJKTPFEAEZSEJVJXZDIXKLUWPJRZTQYYIZ', props),
compute('m_2_7/6: ${c} CSUBZDONAEDHPKYBVCPEDKEFRMNTDHBRHRUYEYEVAXSKXJUFAAYCOEKUSYBLNJHJUERAZOZPRGRRQSEWBBIYKHUHXJHONONLXFVS', props),
compute('m_2_7/7: ${c} QPGKWWQMDBDVOVXONWPBCABNTHYGWHMUSLJJDJBOONKEHPAQFGEZWGVAHIWDBTEZZJHFCQRDDDYAUBXNSJPZNNILJYNTMPZRKZDQ', props),
compute('m_2_7/8: ${c} QKMYDFYMZYZYMBZTXDJAGPIEJEDDSBHQEVPDZSFYJBLIWASGHVAHCMGEZKFWOLGZIAGPKMKIGDTRXZDMGKJXPLUPHBYRZQBTLJKI', props),
compute('m_2_7/9: ${c} VKHHJZETXEBOEHSZBNTBYBSXMRHUQHWSYERNNPJHVRELSJVRDEWSCXWGYAKGOTYSPYGXZPNTCZFCLXQJOFTBTOJSWXKPBSMGNWSS', props),
compute('m_2_7/10: ${c} YANSIUAHESVKSQIYRCDXQXOHJMRJMNHMRZXTSIRYUIUALAAQCGHJONPPYHHTTDUKXXFPFMIVUZVKKUSAJTIYYGZURRRJNUHBWDOY', props),
compute('m_2_7/11: ${c} FXELXZYBRBZUKYQTFLEHQZFRHLPHYTIQIYPMETHWEHZOEBATXBBSVVQLBAQKEDNENATCJSMQKDKIGAXEFOFLHSUBKPZVLCEECHHF', props),
compute('m_2_7/12: ${c} IKKZDOVSLIRKMEOXPQNBHKZZQKZLRHORGPJVZLDKWDSXPEZAXMCVGDHIOFLCODAVRHRXEIPUUPOSZJACBPAAGUSDASTLNGKOCXBY', props),
compute('m_2_7/13: ${c} EKNPKCFFRYKAOKKHJLIJXHFUNRNMOIFBPXYDHKDOFCKRAEBECWGQECBFEMOQFDSKNCBUNSMMOILLIOVXEVXIGEISQMFIRTDXYKZC', props),
compute('m_2_7/14: ${c} FMTKSQHGPFVMZNYVNNXTHNXSZDKGKWPPDWPVCSSTUSYUQYBRJCZQNPUWXFIGAQGQXJFDDTGMMDTKTPKUFSFKPQNHATJIGKMAABTY', props),
compute('m_2_7/15: ${c} LHKMOMHVIFTUUCJBRBHDLAAXKRNITCCUWZFZXLWLRORNUTBWYDGKKNOUWWYRIXEOBIVJRZPJAWLVJUXABUIANQJAYWRUKXLIQRWK', props)
        ].join('\n');
      }
    