
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_3/1: ${c} HCEIXFCOPLAPTHOXCELYOKLNBRXNJHXCMWLTNWIUMUVZZLRLKALPAFIPKMWEEIBBAAQDVYFYMBZPFEEUEPJMRWYQFCWDPVTILGQD', props),
compute('m_2_3/2: ${c} XPOKHYMQZUBCRXCIVQOQCOUIPYBDENJLYIGOBBXCBQULECSGIEVZLQRSQQYHWGOOPTRYWXZPKCSOEPEQVHKJGXIDSNLXTHSEBKNO', props),
compute('m_2_3/3: ${c} GPILPPASNJTPVBJLJINSHNVORXIXGEYBIUSDNRJCZSHFVSBOQLFMYESGKOWYCKCSBSVTMEQWYDBWYEKBJTQSANUMRKBJPWBRIDPT', props),
compute('m_2_3/4: ${c} QXYGKNPPHYGWSNRRBULSCKWVEOXMIYUDHBQCGAXEJHDBYOQPLFYKPQUSXTAFTGUESZEYDCPTPVPTLTJVITASPREXIFXCZUIEOQLF', props),
compute('m_2_3/5: ${c} XIISKNZFXPDDCEGCWLAJUZDONFGBJOVKTANADSZMGKPWSOBRFGOGWLLGBRDJERCOBRICYMBDETREOROHKZZEMBDISZSMKOTNHPUM', props),
compute('m_2_3/6: ${c} AHPJXOZVHLTEZGXIDQZKRQXKWNMGDFDJWXBIFZBPQCYJJKCTZAULWESNKAKSJLEOVAXWRKCFGTPVIFVCBGVFKVMWEBCPBDWKUAFY', props),
compute('m_2_3/7: ${c} XCVJHAOXEBFUJFZJUCAIWAQWGIIJYSGYCLPYFQOLJBRPXDFVZSMOHDIQCQKGMKQVEYHWKKVUBGPQOCNXCDHJGHDXYIQCTGINNDKE', props),
compute('m_2_3/8: ${c} VOUICWNOBTFWCLSTFYBCNOQEMNSHUCJBTDZBIKRVUUJHOHLXAKXHEAYGLJEZRPCHOLXVKAGRGMWHZLPJQEGMFCMVLUPFTCVXCTTX', props),
compute('m_2_3/9: ${c} QQMIKKOKUTVZDUMMQKADFEQFDWESXKGRIFOHSLQJZDKGTSVPYFAQVJLGJEJAVLEIBLLSEDHWCFHHYVCDVZVUAYMKYQQTIYXVKEPA', props),
compute('m_2_3/10: ${c} GVWREHIKNEYEMZTTDFVMONXECPRBOZIKEHCXHBPUUJWJXDHZOTJKQACJXPFVDWEQVDFIJJXGOUTBROQZODSLDNIVNCNBTALGDBVF', props),
compute('m_2_3/11: ${c} PKRFTXWDRGZBFJEDQFGQCJLWADALLQXTZMCKYWEPFUDXARLORHIXZKTKFEUVMSSVJODAWXRXZXCNTFUZHBOFXHDMJFPVIKTGBOSY', props),
compute('m_2_3/12: ${c} VWRVRIALCKJKVXGHJLASPOSJGASVGDPNBZNKTSKPUZPUORGRXBZDZLHYNCSTZQWAZVAOYOFHXUPUVODQMCHARVOZAIRXFSURMKRY', props),
compute('m_2_3/13: ${c} CDJULXNNEAGAHKWYWRAORKTYLQNKRCTHJFAWDFUPTHMSDEUVFBCWYXLZOCYOVNPRMFHBXFFYFLTAOPQHFUXSRVOEXBGJBUTHOHSA', props),
compute('m_2_3/14: ${c} VZQIUDOKMQNNYUXELIPYOFMTLNUSGENQSCRKJRDOHDVZJIDBIVYYMFOCTVXKZJMRUCSOWSHJSZZYNUGPXMPSXYBEHOSORDKFNAMB', props),
compute('m_2_3/15: ${c} VPHGNIOXBQMWVKPIEPVKZGTKTENJXWRNBZWPTNXRVXILXEIKRTPQCVCLTJVCCRYQWCLUTCPXEXVMLCBCFUORBQJXGKKUONUPVGBM', props)
        ].join('\n');
      }
    