
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_8/1: ${c} VKBDROOXWRKCIDGDMDCKAKRDSQYWKPSQJIWKAAVHOAFFCUEZGSVGVWCILDYIYYEOMRBKPAFESYHQSCTVACFUDYFCPDCFLEMPOAIS', props),
compute('m_2_8/2: ${c} OCFLXEHOATCJLHDKHYZRFBWRGJVAYOUSJXGMJQGUFGTYTRNCKPYERPVQLIGKKXUEOXPDAUXYMAHNDKLXAVCPEBJHFGUUTQGVZITT', props),
compute('m_2_8/3: ${c} GFXWAOUENWXFMCUSRZTJBOHILJMKLZWWTVVAWGXXCCYBQVQCJLXKPXERNPIHAAFWLQVLVMBLUNGXJQWAJIAPGOTXLOTHVHGBIERG', props),
compute('m_2_8/4: ${c} POPVHHLMCNDSGVTTEXLWVZKNRLPTXCMBLAKZCCRHTBJOFTEXHPEUQFSNORNTFAUOUYGPIBKZWERVEGPXRYXVTJSYMSGSRFTQDBJX', props),
compute('m_2_8/5: ${c} CTLDILFMZEJLLAGNEYVFNMZQHKGPMFAKJVNZAWLLKXIDMIUBWYTVJWATBVXLGIKNRKPYSYHUCXCBDIOSXKDVYZFNSKEXHFAVQJXT', props),
compute('m_2_8/6: ${c} FAFJXSIPRMZZJBMTYBCZYAYCLANVKYVICOXJZZGCIJDVWOQKZBVXCLWDXEJUZIVHJIBPFBBWQOPXVHQVPGBGBYIEITCJCZWLLDGS', props),
compute('m_2_8/7: ${c} RAXKITLRPIOVNKMLHWHBJMCIPIJCQETQLKHREPEGIVMFVLEWRNDXPTDSXQTGMLJYBWWVWTFYUKGCATQKHEAVKRBEUHLUOCNRIBSO', props),
compute('m_2_8/8: ${c} NSAEBURFEVGQIULEWCCXQHCHQEIFEKYAJSIGODDADDZRMGSUQYYAUGTFQJSSLHUEQUIUORVGDEPNGESSVYNARXFMPAPRYOBYHCDQ', props),
compute('m_2_8/9: ${c} NWJXWFYKIQJCZGJLSRMPUPZMIEIYGAAJTESDBDEMRDPCROVOOKHDTOIQLQRDAJEFLGUQSFFKAJALETGJALWNKIGAMEBBGBLWFZDZ', props),
compute('m_2_8/10: ${c} GAJVIJPHMSJLSWVFYFQYXVUDZPGLXSVSIQQAOGSPWKDDZIASIDLTCIYDAHGJNZLQMKJOOEVMKQGDRIQFJKTWLQZYOIDFJNDTDVPK', props),
compute('m_2_8/11: ${c} CKLKGFNOGPEZMQIQEVBBTBQECSALTLKQSCUIYZPGOXPFUJOQXVCZQXHRLYUSAXIDWNEFIYRUXORWUREVUHBDLLASPHPBFZERRJGJ', props),
compute('m_2_8/12: ${c} SMZVJKHKOXSLQLOWCBQXTHYROEWSYGOEAHITEEHHZKQHTYKCKIEBRJUKEEQLHRSASBTBJBFHHBPQIOYBFHRBOJGTCYATOXHXZVMF', props),
compute('m_2_8/13: ${c} KAXJQOCBNYRIMZMMNRJATLTEHYKXCLVILDUAQCIWSGKCKPAYZIPSTDPJGXEOGGSXGJEKOSSGWAAHKXQHIAQAQAPCFGKLMCDTDFOM', props),
compute('m_2_8/14: ${c} TWJTQFTQKMKOKOMFGGAYLJSSVIBENTXGPCOLXLSHFBSKMLQIJDIWBUUEFWJHEDJQOJMGCJXWGNFIWMKHSMCKQKTIFEIALUIPBGQE', props),
compute('m_2_8/15: ${c} IZMMORXWKHLTPKCSWQNDRVWNOVAISBLXGQLYJVQFELGMSQXIWRXFWPTKAHCBEJZLCXKZPHXOPOPXYPNSXOTBKEXMOVUUGCWULYXW', props)
        ].join('\n');
      }
    