
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_20/1: ${c} FHQYAUQATFIUITPXZZUXICPVWNSCEPZBQJEWCTAIAZRAWBTQMGVTHFBZWRQWXALQXQAYGOBYTULEYZKMVQHGSBNYCDEHNYBXDNAN', props),
compute('m_2_20/2: ${c} CILGHQOCWBUKOSUIUEBPEZMSMOYONDQFJDCHDNATYQFKUSZMLZZRAMJBIREPSUBGNTBYVWIGUYQHRDWYJLWRDAWQCPQZIKPFSZEA', props),
compute('m_2_20/3: ${c} YVIXFQJMQBROZMUYZMINGHIIPFWLLGGSCDDCJZOEJNQFPXJGJIHDYSVIJPSNEXJYWWFWJBTXUAQCFAOSCTJOTYZZVLERFNWRUSAY', props),
compute('m_2_20/4: ${c} YWHRTFKTJPAWHZCTZLYKFWWENQHMZZVWONVNHWLUGUCGNDKALBXLGRYHKGPVUUAXHKPVPJTTWEKCAVPKWQLHPJRPIMVBCTLEJBUP', props),
compute('m_2_20/5: ${c} VTMVIPWHYBJLDTPIVAXZRZJAPTJRMFIJIGRBBJRMVJOIEXAVWJYPHVOEIRWSHDNLQIWEUMPLCVEFHNFYKYUKOKMNBORQWUKNLOJE', props),
compute('m_2_20/6: ${c} DQTWNWGREROGJBDDKTJLQBAWJXJAKDYGMIXJBKCGICJECOMMRRSGFBKVFXHFRQPJBHJTUZETFTVOFFGMMSTCJDVXAICWSGFBWVYV', props),
compute('m_2_20/7: ${c} YEXBNGKVIMSHFNZZUUBLLZWVACSSUMLUYCXCEANRRHBIJLEAUDCQSDYVXFHOGVJQVOUDVXPJVHCWUYHXGMWECNYESGNOPJHINTXB', props),
compute('m_2_20/8: ${c} OSIYZMDIJTBJKLQRCFCYTIWAVSFMRYXLYIMPDYYZJMTBGEHTSZETKKELNYOFZIHMNBAUBMMEHXLUPMTWHJDYKDJBNUBFKSKAVNLP', props),
compute('m_2_20/9: ${c} YGVWAFZTXUNCRWNKEVEMBRISZNDQXFALSBQPMMTFIGVWAERIZQWYFMTTPYDSDPLREBYSIDMFNCXSQYKTOGEAPLKRCVQVXQGXZKVQ', props),
compute('m_2_20/10: ${c} CEKBGCXOQCVXYOOKMVGPJCPGSIKWQTSZJRDFSZYVBTSMGEQZZHGSUYUEPAIMUXPBRGZPDTBAYYSFXWFMUGQVJQVJMOJHMCHAKAFS', props),
compute('m_2_20/11: ${c} UKGYBUSIECKYFRYLPSCKCAZVQILTOASZNTOFOPARHWCRGJKZTDFMFBTJOLOAUYXYEQYOIHRHJWJENQRBLDBTMKRYCWZDZLGIDDXN', props),
compute('m_2_20/12: ${c} QNKULRHKADVHXTRRASFGGXGCEQNJPVILFQHGVVMTIAHYXOJURLKUGHVALWJQFDOVTVNICQIHFDKGZGOJSPDDLWLEBQQUZODEEDBP', props),
compute('m_2_20/13: ${c} VYYEQFKBMXIUJDKZUJBSKGRCFWJAAOPDZJISDDUKIZDORTBORLQVBNLFEQZPOKYURASCKZDXRRKODECHHHEKTYPIUWLPPYRFDPAR', props),
compute('m_2_20/14: ${c} WMWLZKLCHJESKKWCQMGVHIVLSJDOBIJSQSFGBURNCKVUJVWBQLGYHJMYHKSTJGWLVRMGTBBAQWXLWKZWUKLVQFOKOSJSVEYYQYMM', props),
compute('m_2_20/15: ${c} VAWSAAHPDVOJSUOZPSXHHJNXCBCPKNLKCXAVAWJITJOMCSVFFTUPYDJDMAGDATMFVDLJOSIGITCNNNAEYVMXWWKPYLXQQAPYEJNJ', props)
        ].join('\n');
      }
    