
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_5/1: ${c} FKSCIALVQUODQXRJTGQUMXHOQVMUYJVSHHXJFVPIIAHSXWELSMTYEKBCWUBBLFIIIUSIEIGJXHBQLHJPUCIEJQPLYVVNIRUEGUKI', props),
compute('m_2_5/2: ${c} AUKDWEQKHVEFAAKBCITJYDBTGCKSBZKTKXJZUIQIQMYHIBMUZIZNXETULQJELFCYTQSDHNWMHFBMWDPOPMIHQXHVRGFWKXWMMOJA', props),
compute('m_2_5/3: ${c} TFHEYWFOOEIMJYXHNOZCLHKUQMUDLFLVIIWONEGZKQTWWKHDGMIFKXRQNUIFMKCKKBBYYUZQKLUKSKDMIKLQGCSTSPFWDNYEPYXT', props),
compute('m_2_5/4: ${c} LDUJYCOUBHDOIEAWVAXRKJPUIZUVFRELHDXMSEGEJIWNSQVIMUZTNEKULYWYQJQVGOFMCOBKTIBIYEGZBPVMQLYIHWIBIIKMPTQH', props),
compute('m_2_5/5: ${c} ADXPUJDFWXOWHTPMLOHBIUNVHEYVBMQVSNFDYRRLIERCDYBBCXQOUJOZZBWTRARXIWORMEDOSGTJNIYHTCPVXVVIDABRPKNZPSQZ', props),
compute('m_2_5/6: ${c} DRIPCLZZYGXMNONUSVSJJXSVWHWARSSNHNVIQGVIOAMUJPFXJLIFFZCYMSWXKREOFENJFJZOPQNQRQSXVCXIXKAGDCWRLNHMGYKW', props),
compute('m_2_5/7: ${c} RBMRYDOJQHFSORINGEGPQFEFFOKIMEHQISDIRRCXQFIEPHCDHSDTXEWWCLHNCSMXBJBCSQCNNMDCMQLMZBGMCNOKUQNROLMFOTLK', props),
compute('m_2_5/8: ${c} LPMDRJJXEXUDPWVJHEZOWBBWQSYMMFHZHVDNCISJPHKDBHGDHMFRUTAJLEDBBELVMQHZEDIKCYIIWAVSTMPCBYJQBLTGEAFXKMRM', props),
compute('m_2_5/9: ${c} ABCSYZZKKOBRYHQUOMNXRFMMBGPCKHIZQRLMTHUETAPQQUMHKTSIKDIFLJMPVFJIWQQDYIVAOECMJXSKLGWCSXJYQOXVBFEGEXGM', props),
compute('m_2_5/10: ${c} EZUMIJXHJRVZHSNGWCXWJGFCMQUYCJJHZZWIMMDEFXGJXEBUCHMODVRKTDCVLBBUDKGBFZWCKEOCOCFZEOFLVBOXLJQESIMQCQVE', props),
compute('m_2_5/11: ${c} PMFJZXKIEJKRIZNMNNKYMBHGLOSBEKJTWMAHEMYRGMOYIIIDURNAETYGSFRKJYOFKPKAKNZQTJPJDUINBKQFCHDVNFMDGURIKVYS', props),
compute('m_2_5/12: ${c} UVKXORWKDXZOFBXFDFNNNQXKFZZJCPOVMYRXGPFOLXCVYCIOGRDMVMLCCSYYERKVVILKVKQNYYQEBIDFHRWCUJCCAROXIZKFWMEK', props),
compute('m_2_5/13: ${c} ROVUCNABQJVIAUKDQCLBRXGREWEVLHZIMLWUIVEKPXBAYRHOGGJUVHOOXHKPJNBLXDXZRTDENHBOWRICHYRSJBHHADYLACFXBWBD', props),
compute('m_2_5/14: ${c} WNAELVMJIEUQZJWCCVVTMPYKSJSIEJJZPQUBZFMERVJESBFQHZSPRIJNUYIKLQXCCHGJEEBPRTPNDYAYUCRCAUQTLHRBJUKCKZGG', props),
compute('m_2_5/15: ${c} IYEPUKDAWMBMKQPCHGHCCVVTVRVGNYATEDSRKROLFUXAKECZTXICMRRFTUYMLSXGRMYLYVSYNODMRPBUQHHJEHHBQHZXINJVLPBR', props)
        ].join('\n');
      }
    