
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_9/1: ${c} NNCAMUTNTLCAAQTBFKLFMWEIHMGGNOYIPIGCEVWEZWLIZWRYJOKLRWHNEVWJCGIEFBGLLLRWRFQHYRXIBXVXKLHUCAGFZJLKDFUJ', props),
compute('m_2_9/2: ${c} QMCGAGKJYWZHPQNOKLUVPGURWYEADJJAVRWSONCUNEHTFSZCLCZEKLGONQEFGNQJXHDZUCJJSXJNBXYROSCQMATZFTIVQJFSAULA', props),
compute('m_2_9/3: ${c} STZQPXUEKIJHXEKNNSXETTACOYVHZOHQIGYRPCQVJDVUPYLTQCHOGXUCZJAWQUMTQBOFYJQQTDFZUUFIQBQBSBVFSWKCLENGDZXY', props),
compute('m_2_9/4: ${c} WJKGLBRNNFLZEEGNCFNMAQHDTKFRJHGYZAWKXALITPNZTTQHJEQHFPETDXHKSWKWHLGLFIRIHMCIHVMFYFXLMDBNFIRDTBUDLWUD', props),
compute('m_2_9/5: ${c} YEWXMTBWBTZHIKCPMULXBMMRSORJSYHCIYIFSQOWFTCYHBUUXNWWUPJVABIDYOUSQFXODNFGZGCKACOFFFLPPASZQHHHRHRGLXTW', props),
compute('m_2_9/6: ${c} IZAYXGAMDXFQJGIVVYJFOTLJHXXZQMYOIAIFIHXEHAMCRSLNJTESTXDUBKQMSQXTJDXABKRLJEGVQLTJGBSYNIBLOQCODYMAAUQC', props),
compute('m_2_9/7: ${c} QLIVHLHVKZJYIPHQMVCVSHQXDXIZFNTVWKYQFZZMYRONKTFILZIRZYDUITCXHVKJYKPGOAKUHXUXGJWQEOFWOKNCDAXGFATWHQDF', props),
compute('m_2_9/8: ${c} WDXKLBBRLWCKLOQLKPUWLWKLUWOXPHMLGVNDRGMAJUBDXRIKWREIENUGCFTPGNNQJAQZKVATHHEOENPRJECTMEPNWWZAJUAUIKXA', props),
compute('m_2_9/9: ${c} BHBDOZCLUWOOMKKMRCWQNABUKBEWWPQBQSUALNMJMSXJXFZOFYSGBXAKLPUFVDYMCRIXMMPSJLKVJAJENNSNHCZCIEMPZCMMPBHU', props),
compute('m_2_9/10: ${c} YUULRYUAOIEKWEIKMZGEQLVTZSBTJVPDFGEEJMCTGMLAGGCJWYECBURICYUSTGOVATPBADORHRRYPBZVHBWFRCOCFBBCNDNBXTRM', props),
compute('m_2_9/11: ${c} XRLMCXPKKUADNRLANNWXCUJXASNTYWQUHUKKIMSCFHIYMAWYLQAOTZSFHJEQUJBBJYSLARXDIQRMMJRZYXPFRIHLDXSWYXHVELOH', props),
compute('m_2_9/12: ${c} ZSJNKIFCKBZAENDCBLIQSBEXAEVTJFSLUOTUYNNJASUXLFJQXFWZEWONUIOHGWWHSEAYVRRVEGNNHMLOEIVMOMPCXSIALZANZAFH', props),
compute('m_2_9/13: ${c} NTVJFUQKFFPJTMCRPTYPUBNQTMRMNFONZHGKMOCBGOROAYSPPUZVETWZAQRIBZJUIXRFXSGPQXIUBFFRNVVQEEHEMYRBHBWFTOIZ', props),
compute('m_2_9/14: ${c} KNBOQKLSTJLHDNJFLZZBPOFNGWQTSBJXZMOKUFNJLXAOGKUWUVYKXLYPWYINYWMVOTFQBGQAFAREOQTVOSWKJECLGQDTHQXIFIHN', props),
compute('m_2_9/15: ${c} JVAFOOWCBMFMNXJTIRLYWXVRQIQCTGLYNOKUXAVHISYULGSPINAPSDDXBVAMPWVGYNBZFIETYWUZJCJQMCTJTWXEPJHFEEXUOQOF', props)
        ].join('\n');
      }
    