
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_18/1: ${c} GENTQFNEUVJCIZMJRHZNREYRDJWBNJZCGSZGSCOHSIFXIFBQYPZBINFONQWBIHRAGNCTSWKGFQBWATIAZRCWAQMLCZLMPEGRMAKF', props),
compute('m_2_18/2: ${c} EEYMDJMALZHTARBHENWZGJXYDHGCPRCDAOTSVOPRYFFBAKBFANIXBOSSXXTNLRUGZRNEJDSJVJAKLIAGRSYNSETXMHKCBMKMSZGI', props),
compute('m_2_18/3: ${c} ORMTCMNKUSGMEOKNRBTHHLSLHETNVRJJJXCVDXRGXJMTRFMKFYFGWGGBQPENFFZWPENZLYZELFFZMFACPQILEVDATHNOKSGZRPVS', props),
compute('m_2_18/4: ${c} UDCZCVGSPCUJLQAFJEMIRJYMMLSHOQXYTYRMLSGMJZVDUUBMNYCCTKGPSHYCTJUGGBIRGRRIENZBUPAXNHHWWELURCXUKNKWKRDB', props),
compute('m_2_18/5: ${c} CDNBRAZDRPMHGVQZJEQDXRMXZOZWNCNCEOQULNSZBRCENBFACDYQAIVJHEBEGRKHZFXKFTDDBXEWJTLMCKNGWDWIEJWQBXSSBJRU', props),
compute('m_2_18/6: ${c} QVDDXERZJLITXQPDXXEUDQSYSDOVWRMNXBWVTHIXVHJHTOXIXJIVWYXCWLLNPBMLSCTTFJIKZVWOYSIVHDCNWPPLCVAAADCTFNXV', props),
compute('m_2_18/7: ${c} SLBUSZPLPEIIVIRNHDVMOCFWAPSCGABHMBKEJTLURFQDSWTAKXFASAWFPXJPZEFDXNEBTYMGAYCNTZBSPJKTTDBEYLRYSLGRQLUH', props),
compute('m_2_18/8: ${c} BKWBVPVDCDVZQAMWNFIYJNDJTPORAODQCYUWTYCFHECKAYTOICCOJNTONUNNRLKXQPMPQTJXSTKARFLNTXTSIIAUHGHMKQOUTSRS', props),
compute('m_2_18/9: ${c} AMOXCBHGNRJDVMXVDMLEDYCCDMGKHCFGVAJWZLVNSQDWFUBMPTBMBCAJOYTFHPNHBNVHWMMWPZERKOSMUUQJKTVCMAFVDDPUPOPV', props),
compute('m_2_18/10: ${c} TWNRWJDXUYIMEEOBTKSIILEUGSAEXLKCGXORSQAXWKSEYHDRHAHRSKWDCSROHMPCSQJOEXWEZILCOSYYKJQGTNBPXMXISAKXKGWY', props),
compute('m_2_18/11: ${c} FDQLLWOCBMSZVLMOWMTNDPQKFYUJMQPSGPLYAXACVPYKIUJQPJBNBETICWFKGXKTJKPBWFVQDPQZHBKQRRXMJUEXNOGLSTOFJWJF', props),
compute('m_2_18/12: ${c} ETFRJIYRPBRRVDSWOLFLATGKAURNLKWRUHUFWMSEWCTPSDQZVYYQUCOBZLYVBZQZNMESWCOTQFZFMPPTSUFHOOFEBDZTXXLMJHBW', props),
compute('m_2_18/13: ${c} FYQZCXYPSCNEQXYAFYXHVAGCUQWZPBCSKNEXYHUKFFDAOHGPYZEFMSDNJKUIXGSKIJVUOAALMCXXTLBPIMWHLAFINISWOZLMJFKY', props),
compute('m_2_18/14: ${c} RWEGMHBXRWZJEWBCCVNPSQNNPVUDIIPGRNMUKJSLCKVXVPOSHOBAVYXSWKRIYGHEUNROXQUCUXGZCMMRKPGGMSGGGUUBIVARBICJ', props),
compute('m_2_18/15: ${c} IDYEGFNWMMPMZJKTITVFBJKOMFAGTHYZOTGGTEMUGOXSZYFPQPEJGEVPXHNSUABGTIFBAXAPDIYMPGUTOAERKYCTCTZMUNVRJZKD', props)
        ].join('\n');
      }
    