
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_2_12/1: ${c} JDEIGGLLOOOETQMVFUHEWXTEZKNBOTUBBDCIKOKYGBAJUYXVRTPYRWNHUYAWMFFZGSTWFQWFOKEIGCFALKOBGWKVSMNWANIBSTGP', props),
compute('m_2_12/2: ${c} TREYENOPFMXSHVXECKEUNNVURAWJCRDNIQSNNWVSMBHHJFQQOUMVYJBYNBDTFKRGZUXDYCLEJOXBNCDDLRZHMPEWBTVKFOHKIJFZ', props),
compute('m_2_12/3: ${c} BSWQJBXKSWPSSCMTETZCSVHECHJENXCEXTCQOOHUCQAPAHPQCDLZBTEICWWUYKDXBSGZQAORUSMOYGCINQMVIVYCYZPGQYEJAZUP', props),
compute('m_2_12/4: ${c} UUEMHNENFZQGOJHOUTRAVQLEINTGXNMJEVYAOFMPSMTTGJLPRHMPRSOFBIRDOAIQBNKTZYVKEFHIFXGNASHXCRUCVZHBNVSKLTDD', props),
compute('m_2_12/5: ${c} DSARQPTZZZCIXCSQVWFHPJTXFRGRXJRYAQUXTHBXGUYVZBXESGNNOPRYMPTUWVNVGHVXUPWNGGQOYQKEPXJEEGKUJKBFOJNUVTGZ', props),
compute('m_2_12/6: ${c} USBZBHMHUAEDRVIADYDICUKBLNDXUDNDHVXVPINROYGGQJQTSJFPVSMBFAAOSZRRNRXXXBHWYPOTYKAHZKKXFTJVZKGSAEJJMNKX', props),
compute('m_2_12/7: ${c} EJMUPJDRFXUGIAJXQFQWJENKVIIUBVLQEHTMPHZXMBGYYBSNINFWYDXPIRXXZUSLVLFINWNDPXUZESXECKPSSZWUNSRTXOJUHEQW', props),
compute('m_2_12/8: ${c} PTAEHNCEMHUXSULERQVQCKQHVESPCYUEYOJCWOYMNNKOKAKHABCRRWJWDUFYFRFGRGCHGNSGAVLHUPZXMCSIOYVQKXASFTVGNNGK', props),
compute('m_2_12/9: ${c} PRVYXXVYHUPUKLYDFPTBYHIPERKOYDDNGOLOPEVZGZIBJCDTOOGASLJTBUSKRAMFJFPVVVQCOTALWBRLOWNYLGRIVDGLYVUEFDDR', props),
compute('m_2_12/10: ${c} DGBQPWWMABOSFRZKUSOUXRUSNRQGRKRAFPYLZAIEJRBWOGEXRMGBNVAYSTJUIBZEQYELFJAQNRAWJIBBVXNWEPXQVVQYVOAFLTXX', props),
compute('m_2_12/11: ${c} NMERYWTLADYKKRNNZPNEGVIQAAORNSATYBFJBTIVEGFDZGYOCUVJKOALDCVITZMLYSWFCGKEMIUJEULWINRDTKBXRDVELDWFXJPQ', props),
compute('m_2_12/12: ${c} ZTUSERHTRFDDSYOVGIQAHQKAVDQGTONVSWPGDGVRJMZUSHUKFVGTIBKJCDHFBPJGTLUQKINAREKMGYFBBXNBPDCXBNSBUZEWXFPI', props),
compute('m_2_12/13: ${c} SELMQXEAKWFRGKNEQSJGXGOQEQZGWKLZKCHJJVHBTEHBHAJVZZAEWKGAWHSJFLPGXBGQCIALZDTVYEAFWMDQUECZAVTBNMDXSBYC', props),
compute('m_2_12/14: ${c} YTYVSCXQQADRUBIUIGTJHAWLHAGZQUDFYWFCHXMOOOFWKSEMBVDKXNSNNJGJUEHYDMMSHSVJMRZEQRFXZYVVZWHZDWIVGTKDFQNH', props),
compute('m_2_12/15: ${c} JNCKZJYRPLMCFGJSOOLDUIQTVFXHJMYWWQMPDMRUQVYFLNVEVJSVFDBDSVWAMMUPRZPVAGNUBPPBFRFVBOPVBHTKYHEXLHXWLWYH', props)
        ].join('\n');
      }
    