
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_13/1: ${c} WTFTWLAPFEUQCKIWOBSMXPHPDYQFVXNBATUWWMIPMWFNLPEKFZRDDCMQUBSKGSUWXCTXAHKZEDAYYSQQWHRBWJMTUQABYADRAQZQ', props),
compute('m_3_13/2: ${c} DOYBRNPKGOMROSCFBLEYZFHYEFAANXGSPHKUDIYKXTWUFSNTHIRWZSJTLYGTFJIQCCZTHJBYIDLSHIAWIYIEQXJZDVUZRQFRPAPF', props),
compute('m_3_13/3: ${c} RJEPKMKMBFDCTLJEEUPRIWVEHHZGFTLHZWQKPPXZZWZMZBUMDYFTFDJGLXZJSJVVBMEYFTKXWYUXRUUNLDZGNWHWMKQAPJBPTQMZ', props),
compute('m_3_13/4: ${c} KLHCXNNHXDWDGRHHSYWBCHTIQZISPZKDOMTWIMAIDFAJHIBWBEZGRLBSFIQUNBKACLTRVMISHUUXQMSZJJFDMMRKNVBIQZEGXXWV', props),
compute('m_3_13/5: ${c} ZJAHRYANDRDGTMMXOEFSODFJGWVGVUSUXZPNFTMIJVSVWZFKVIGTHKJFKBRSNDFRLTAZNDIWNJTCLVESUYVZCZIKSFAZWLHZENZY', props),
compute('m_3_13/6: ${c} BSJSZCCJXVTVOXDPHQEPYQXVDNZOTBEATGODXKPAMUMOZUNUULXKVCBOGYONZWFUCQDUAYLHGZLBVYAYNQKXPQKDCBIVSDIKHULP', props),
compute('m_3_13/7: ${c} SIUQPHUWGRNXSZWRXREIQAHOHZTSOZZVLQUUFJAVZXFOOGEOEVKMTFEHWYZSLOZFHZUJSKZOYPJVYJDUEDWWUZSMNJIVTUVNUZJE', props),
compute('m_3_13/8: ${c} QZEEFQPBDBBZJQVJKPKEUHRVRQZAUYZOOMMSWVOSOTZGTLIXZGXRZAQYGNJVIVBVWWAITGZEDWBAOIAMLRHUDNGPCQFJTTHUNEBV', props),
compute('m_3_13/9: ${c} JNAAJPKPIGNYRWRIDKUDTCXKSBGJYTFVFSKVBMXMDOCMGJOCOIJVHILCGVOJMSADOAIJWEETHJUPBJDKICXXWSNXYBOKXXJPXCOU', props),
compute('m_3_13/10: ${c} YGGOGJZGMBLWLZLSRJIRIWFRGCHCYNDJONSRUJMNJOAMUMAGCLABFMJLRDCTIJEARNURMFEKIKAAVMDAPFIWTENXQVXUSEAINFQP', props),
compute('m_3_13/11: ${c} VDLWKAGHXMRXGQZDUPBNOYUEWPUSVCDMLKENPAGSEJBQMBIHRPXNRAXOZSICMNTLWLGIBTMDOBVMBMJVMMRSKIURYLSPSIBLTHKY', props),
compute('m_3_13/12: ${c} BGWKEVHBILOFNCTRVYIUKNGMWIMGRPWYWBBBEMFQPMEPCXABZNBAJEFZLATCIJRVXGHUBEAEYVJTCYXPZQSXHXEIHOMHDWRIOQWN', props),
compute('m_3_13/13: ${c} HXFKFOCBCFLOBRENYDNGDWCEWQHDFEAEXAFGXWXMCFUPFCLKTFDTIGDFBOROTMTAGRIGEXYBASYDTBCYUTUGTKGGDOVQGWRMHGAL', props),
compute('m_3_13/14: ${c} NXJQNENDTKETZZCFWXUVRLCQJPJVARYQEJANWKJZSXEOMHNUYXWGBJMWXOJIYUIQVTTADMYJXVRUPYMVLJWWRAFPPQRPAOMEKYMA', props),
compute('m_3_13/15: ${c} RMBWJOLNMRZNFTTFUOIPHOXYFHANZWRSHWJYEDICRFDXEPQNWVUANXKWHZHATSBBGIZNOVGONXVQOVAVVPKDGWNZJNAGNGPCOMIT', props)
        ].join('\n');
      }
    