
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_3/1: ${c} SYNHDTPBMMESIWMIYCNHTIZIQHKDYLBEBVRUQQTBDYIFOGDBHJVRAALHAFRZAMBGHJOJGCNJQOSCZWCSWOTKJLBVNWNURYFWTGNZ', props),
compute('m_3_3/2: ${c} LAKVGUGKODQSLJXKDPKLCDSQIMLCQIDFZTQRVBORHEKRGZQHMYQUBSGZBZGFMHDJIDSNOCWNELSONGGSOZUCYIXVHIGOIFHBKZTX', props),
compute('m_3_3/3: ${c} DNIGRCNLCSLBCXITSCXCPNYDXQOTAMRVIIHPGPYODQDRNFRWZMGEDZRYRTUGGIANAGUNMDXFEDNZMYTEWIBCVHLTAMPKKPPAJZCG', props),
compute('m_3_3/4: ${c} JKGXYRLIZZJTSCRBBUPKFGPYEMXAPNVJGOZOBPSETWNQMFWYPKMXYBFEAJTHBHTWRCAJDAFZZDOEDLCVDHIBNSQRAJAEOIWGFXAR', props),
compute('m_3_3/5: ${c} SQDZALHVGUNBYYQDVWDVCLTWSQXYMEJXAYTHLSFSRUEQKXMVIIYWJOALIBYHSFSMDNSEZAUQACSAUWHTKHOUTDSAFUHFEVDIGXET', props),
compute('m_3_3/6: ${c} QGOFBSXKNABJHJRJVZYNIGYDNOQQNQZMMRZPIZPSUTHKVHCWGJKLUPPUPEQXSCIANNQWXRUKDCTNEUKEZJLXAKHTEEGTERHUKXMV', props),
compute('m_3_3/7: ${c} XFHDKIGFTMTDEOYYNYYPDDRYCSSZYCJZXMJFYVKXQNFLWWGPJNLTOXJECZSJIKVAHUYMHSTSQDFMNNIYLENQAVILBSZPZKJTAKHN', props),
compute('m_3_3/8: ${c} IBPWUCCKYIFOWOPJKGNGPRMZDIBGGCMEBUYODICDOHYGENAVIESHCGAAWZZDGSCKXUYSLWXZYYKILLGNOFUBYXXLHIVBGUGRSXSY', props),
compute('m_3_3/9: ${c} NNESXCKCAADLBFDBDJSXOHIHBDJBBRODQMIKZYYMEBBOSJAHHRZKRZDYNSXVVLLXGTPNWISXWFLDSTQOJRAFHCDYVIXLHDPVUTMZ', props),
compute('m_3_3/10: ${c} AUSLLCHYOJXDVWPQGIPWJZHBSGHJYJCAZZSJRHCKKWFYUXZBXKOKPFQGUXUYJYSWIKJKGWDGKCJXVUWNNCBISAWBDPIADOHIWMUM', props),
compute('m_3_3/11: ${c} UBBIFGVFMKRZHGLYRQCYYABOAJZZZMPRPMDYYBZCGSXKIPOCLRGWHEJBZNTTUTNFDKAPERCEJXHZEOAHXDYBSGUXIWHGZTGIYHLM', props),
compute('m_3_3/12: ${c} FYZEFKOZVKGNYXFWGLMPCTZQBHSVBWHKUDOBQUMYEPFCPIUAGIFXXKQRIVJRUEZFUGXJCMLQWSSQXOATJSJZJGVCQHBFSNKSLORB', props),
compute('m_3_3/13: ${c} ODFKBCPULSNNHAUQDSQSEKJIISRDSRSZGZUXDIGLGHBUJJOKXJDUMPHYYHJXWDJMQUHJUBKCTPPPXROHZMEYXUSPFFIAONMXPUKM', props),
compute('m_3_3/14: ${c} EXCTACFXZQZTAOMRDXGCSMSRCIDPZQPUMXPUDCCNCOLHNTBRUYKMPXZSGVTVJEPSMIBUFUZNVKQJCHUNRVVCMCKTUNTEBZXPYZSR', props),
compute('m_3_3/15: ${c} EUCIBXYZQRITRDAMGUIFTDEFXOOWUKAGCPBDOHRAVOYJDKXSOOVWBRMTKLMZUMLLLFKSCEHNIPAHSEYZKEHBDRPOAKCYCXNPMOBU', props)
        ].join('\n');
      }
    