
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_20/1: ${c} CULCJQUARDYMAZCQOGEDLENOKUTYPDCUDSKGQKBRJBQWJUMNZORUXAQUCYCBMPPSCNLDENMAQJSNHTHJSNLAZMKJJIEVPCZWTKMO', props),
compute('m_3_20/2: ${c} TZFLEKNAFCRZQFSSLGMPOYAPRGULWBCQLIDTXLPCPGAMJPBVIZAKLJXDTQYPWMZQJPUBHUTUJGNSGIAGJZWMXUIDDICVLAVJNIGH', props),
compute('m_3_20/3: ${c} ICSOGHJXSKJTKIPGXVKYUYOAKCAJKANUXPFYRDIQPVJUINNHZULWUNGGPJVFTDDHGPHVQXKONAVBAYORHVBGPSBLYTZXFJCVGHZD', props),
compute('m_3_20/4: ${c} BUAFIKNFRHWITSTATROPDVSOHJMZSBKTPELURDRDXMRRNIEJFPPGFBVWWZEFNKWPGZRQRXPEWIFNYKMWLXQFEIMLVEUWYVAQMJEO', props),
compute('m_3_20/5: ${c} DTSHEDUWCZQUDUOTOQRPOBUGZKXHLMWCMFQIOKAWXABWFOHRBMGTBGMZSTBOTSAJAZDKYBWIGMWSFTZNPCHDHNSGRHQEIHOOQQFQ', props),
compute('m_3_20/6: ${c} SOPSKKGTSMFSCLXYGCTBBWPYMJGBCWLIKOPCMBPVYHSGCYXIAZUTEHCRRLKBCJIAJDLJKFTGVOLBYMPZIFQFMKNOYNBBRJZREKPF', props),
compute('m_3_20/7: ${c} FXNYTJTZBFWIVZSVAENXLFBGSSXOXTPPBCNWUKWEVJQVJJEHMMBLRZYYVGZVZJPJFBWFPCFCRIHXDBOCYKFOKGUMPKFCLKYCWSJT', props),
compute('m_3_20/8: ${c} ULJBWQJAJCYBQSHFJQGCBXCCDKZAMNVBOHGLKMEHQLGDGWOXBSMZOVYVWCOAUFEMBMWLYNMMFZWGTBIDZMEAGLCCZYBKBPTCTGFA', props),
compute('m_3_20/9: ${c} GTOAOAYTMSPKKIEIFPLEZEEGEPDPEGQMMWKTBSMVITFHFUSWJGUSAWXXHPGSFUCEVLYJASAVIZWCTRPKAKAJYXMARRAJNICTLJAQ', props),
compute('m_3_20/10: ${c} NJXQLTAEHQIUGMZGCILLTAEOWCOXZBBOYYLSIOKSEDOGVRMYCEUCPSNIXZFYUREYVWZAWIMIDUDJFRCMLNRIPMTBYUTBPQYKOGAY', props),
compute('m_3_20/11: ${c} HICNIJDVTHTROLWARIONSACUHSWXRHRCXFUKVXHLUGSUHWVKUWFVCVJYKTJSZTFQPKANMEVYPPRWBBSYABGGWWANCWMCWMZLJYHY', props),
compute('m_3_20/12: ${c} EJUFLICUFZANMKZENYFVDUEYDCNFQKZGMCCUHFPSSGXXZQNDVEGQPASIAXHEYGYMHWIFVVYQEPUNHQUNTFTQSKHOARRZALYWQQBM', props),
compute('m_3_20/13: ${c} IJZDXIZCEGTOFVFIQUAFCNUUMJDCASPXWENBCHMIOUJFHHXHLYBXLZLTIRUJUDWLFZISDVVOYZOZKMGFPMQUNBFTOYJPSGWRIFSS', props),
compute('m_3_20/14: ${c} FRSDKXZUXZHLINBMZBDZDFNQHNQXILPMJWTGUMIOKSWBPYFVHGFVRWJUGGTDHZPINKLAEEBKDTKKDEDGGPDGDSUTNRMAOTCHPRMW', props),
compute('m_3_20/15: ${c} QYVBALOLWUZZOAIXIBYGVGPYGEPGYPYSXHBOFFTTTVISJMCYDEQSNMRUYPEPTJQMISEHJGXNNRXNAMNRYIVCOWWYNJTSWTVYQMMT', props)
        ].join('\n');
      }
    