
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_2/1: ${c} SKNRXRHAZVYHSVGQOCQJSIWVQXTKUTZPOPZGUJWHCUNNLTSEQIMLJDQIWJUPJKHZBDWEHZOIVKEOFKBXRARJBQJXBWMWPELKCPQW', props),
compute('m_3_2/2: ${c} SXBEFVQEYOPYGZDBXVDQKOIWYANWKMHELHCVGONTOMIETGGNFJTYRXGZWMWSUJWDZUEZDNTKVYPNMPUWKNRZBNFEZCHLHTYHRHLM', props),
compute('m_3_2/3: ${c} TOCBNTVHGDUQLAWKLJKBXOXVWEMSKPJGGMSXEVSGREIZTLNNRZDOHTMAKBCXFVXPMCVNCYUFUPGPTXGKKBLSLRASIRXDOEKMRWJC', props),
compute('m_3_2/4: ${c} PVURVMPFKCPIAXEPIFKRRONMUBQTXXXUOJFLVJGGQWLFHDBJSARSOGYNISWYLNBUEPQWEWHJJSYGMBIZTYGQEMFWNQNGXVKCKOHG', props),
compute('m_3_2/5: ${c} EHMAKERWYACJJMIQAXSXOHEHEDXHNCXVASAVNZRAPNPWXUALRMMPIISWGOXWLPTMDQLUKOKTTKFZIJEHODVPZLJCSRCRKSGMUVCX', props),
compute('m_3_2/6: ${c} VXYVTYUXSEBZWXXLYYAHPJCFWHCVTRYRDGQIIWWADQSYDIXFITFFBOZPNXSGEJSUFTXENGGQTRXDTCMWBWFKPEWZFBOWOUYQAYOL', props),
compute('m_3_2/7: ${c} YMMBQDWVFJPIFZUXHVYNOOQOCCRHSWYPGMNKLLWSGKYBURVWACAPRFFKQQQTZBBKCQBBVRTDFPIJAIUVTIFZTEZKWDEHINUYCZUX', props),
compute('m_3_2/8: ${c} JMVADFQAIXGAQXTZZHRAAFJWFRKDJTUQFVMTVGVUZNGJATWNESGRKPUTFOWSAGUMBXEYJUTFKBVFEDVEZNFMQFEFQDKUTGKJJBEV', props),
compute('m_3_2/9: ${c} MTGRQUKFDIUGXUZGMCZQDSQWSJGQRPWMZOQKLRCVFTTEPGBWWKCVGXJBIUZPKLHATWDBCJVDUDASCBWHHXODGUMDMDKPHKSUQJNH', props),
compute('m_3_2/10: ${c} WUCZBTHGUVEGQDWBKBFPHTXWYVBZPQVYBWQWKOJWDYGWSWJMLFSUTRMYAPIGVLGTBBDCLSRKMVQVEDGZGAXTKKCTIIQILYKVBGLH', props),
compute('m_3_2/11: ${c} HMWZJCIBGKFJKUIUMWOPWQGUDWWGZHGUIXWPJMDPKLKWKLVVQCQYCIIIZCYJJIIRCAULBHBOCIMBTMCNIWHRYNNVDBYCRTVEDGYZ', props),
compute('m_3_2/12: ${c} WYRCLGQLTMHLVGTDPXHHDTRYCQSMRWIATQRIPVZFPARJQIGHUJFYMPDQNIGHJNACXPPYBRISWWSQVBEOKODHOMGYBRNMLGGLXTLA', props),
compute('m_3_2/13: ${c} GQHYQXBJRIQDXRYCKXENCCOPYHCHQGUOGPRJPJNFDGVAESQCTRUKONFKTOUNYTBGIKWAMHZQYDQPPKEHQTTLIVGVJINHQTWQBCBV', props),
compute('m_3_2/14: ${c} DPPBPLDUQXQVMDYIYCPREGRIEQZUZHSTGUQPTZCUGHKYDOKTMNTQHCGFBNBMNDYXPBEFFBBWAVCIHRLZRVQUAYHIJKMJQVXEPMOW', props),
compute('m_3_2/15: ${c} HSJKVCKCVDUNCSMFKREZFQJESQGJGKWWEQMZXVDACDNFLJIVPERFQGNLXIDNSBPUFAHOJJLOCMIEXWLYXRIGWTWEETCNKHTDMYPE', props)
        ].join('\n');
      }
    