
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_10/1: ${c} UGEFLUAYKMYOZZRSFMLCRHQQMTYXFCGXAAMAYMITSSJOTJTXNJGUUVQXKXYWNIBELCSUONWVUJCNXUGGGOYRMXYCVOHWAXRXKVVY', props),
compute('m_3_10/2: ${c} TDDYSCNPKYEGJOGLUYDSWMSHLAOPXEUSREIYTDBXVZOQCPNOTDCAQYTSJTJXCSUROFNYNSWDQFWYVBLOOXPKKGHOZEVUXXBBFLXW', props),
compute('m_3_10/3: ${c} RFTCRQHPYNDWTAYZEXZBWBLLGQZTVUZPOXROEFBGAUNHPEYZWLVQLSRYDYUENXSXFBDEOXSCEGTQXAMLOILBHQPXHPDCKNFLAEPK', props),
compute('m_3_10/4: ${c} LIWBXMXMBNKNXLDTULPNMJFPXDQMHRTEEVXSGUVMIYBSNLETHGRFWKBKDLJODUKNLFCVIEBHEPKIHSMXXONQDIWLILKLKPPIIIDS', props),
compute('m_3_10/5: ${c} OXLTDYPBOFYVYFFOWFFKWFSDXSNYJQLSHGNNTYVUNAMPUETXGFOBIMTSPWWTNIALWWDSKLOXIOSPZBYYQZRTURLFEURSUPIZQRWO', props),
compute('m_3_10/6: ${c} SHKLKOPTTOTBQJJLRTOAGQNUHKUQLCPRNPMMGFEZQQEABLJGNDIUIKWOCSNDXLOLTHLVQFXHSWBDJTFNOIOZLZRSNCQQLVJFZDAD', props),
compute('m_3_10/7: ${c} ZSJYJOQMPNLKBHZCLRDOCJOWYUPKLNPVMAJUUBEPWMSCDMWXOUNJFXQQIGASURQIFQUYFVVTSNPNUPMFNBPCQXLZZSSWLRYIMGWQ', props),
compute('m_3_10/8: ${c} EJZGXZIBBQPBXHIPYQDJGDTJFAYVCJJUAGBPRGWEKBRHXLDEPSYEHTRSACPYVAAOQGYWCGUYDFEQDHGWCDNQHOSULZFTDIOJPDYN', props),
compute('m_3_10/9: ${c} EUFHMQWVXNDJUQJVTLHIJMNRWTGHCYECDKVEQJBXYRIDJEESSGVWGVTVQSFIQXOAOSZTUDVUMDEOQNEHWQBNDJGQBEEDPFTJJYSL', props),
compute('m_3_10/10: ${c} NUBELZNCWXURWXQXEKDNNZHZPYWFVZCWUDVCOCEBVKCDAHUECIPCNNQUEFSLVQAPXTAJOSRUELNNNPVJFWSVJUQQEURMZMAMFMPH', props),
compute('m_3_10/11: ${c} IEYILTZRFDIYMIZKLLNYXNTRFCBEEOJMWGKQNICWEPBPCSAZZAWSQYWVIRFREYSHDTSJGIPJPFWZBXTZMNELBGFYKDQTBHIEAJWS', props),
compute('m_3_10/12: ${c} KKBAVHEETHAAMWSAWDTIIGKVLXURRIQXULREXUHOQMKMBGGOMCOCDXOYNMXKXRRRRJLADYPKEBRJNUAQTIFEBTXLATKITLXKSGFF', props),
compute('m_3_10/13: ${c} YQVDMGFFBCIYSIJHISBTEXCZTHFBXVLHFZCDAREMMLFANKSZGNRDCTAWNISJPKPULCECYKRQPGUNIYAFQICEPVAALEOLURJDHUXE', props),
compute('m_3_10/14: ${c} QHHSXTIHDYSICUXYOYNOVSCVXQXYCUZTZFCIBBUGOGAVKMZAWBYMGURDBBORZVCTEQLITMRNIDBSQKPIDASNWJCETTIGDHAXLAQS', props),
compute('m_3_10/15: ${c} KBVEHNVTRDSAFWGABKQCGJTXQHJRTBRTRTNZRXUPYZOSWLBBWMMVJSTLEPNBUMUPBYCVYSNAFMRNSHUQSFWJEVWRPMZJHOHWHRMF', props)
        ].join('\n');
      }
    