
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_6/1: ${c} LPCLKIASAFMFKZDFTKVLTMXTRHBUYMOETYJBIMKYWBCKDTXFIWYVGDGURTGACGXRMCZNLMNABVDCYNYLMHFORWZOXQDUECGURBQK', props),
compute('m_3_6/2: ${c} KOZLKNJPQUBDMWPZCQYZQPWAGZGHJUNUJOKDQKLBXFKCYNWDAGQNKPIXIPHUAUYIYVNZLMCCSDQJWXJFQSKABNRYLJIQKCLMHHRF', props),
compute('m_3_6/3: ${c} CCWRZRIVMHUWPEMCZPDQUDLAIJTQMJARKAIMUHHVYDHPVHEYDYLFFJSREMQLAABWDQWQIBUXZVXQYIGJPQEREJOHUSGUWVDFDECU', props),
compute('m_3_6/4: ${c} NPCJAUABGMNMCGNTAZQLAALCRRGPFXZCCXVNSNLNPPFCZOSIPMIYSLXZSWMHIGBKNKQXPECLLOHMKRXBJKZCCAGZXGNMPIHTZPIZ', props),
compute('m_3_6/5: ${c} EPTZKUKPVDWJEZLCCDEQMERPCONCDRPRPALJNZMDPXZAFKMKRIXKOYZMIKGYYRCBYAXCDVNTFITDXWXEEZFPIUFHRLBXYAOXKYZV', props),
compute('m_3_6/6: ${c} POVNMXWEXKCHFALAOZEYWMHNCAMZAIVZJIZBSBCAUWRXCOXIQTTFSZPNIBKSIWINLUFKWZTVLPHRQCIXOGAPWUKQAKHLVDHLFPRD', props),
compute('m_3_6/7: ${c} SWDWIDTINJPPVDXBYDKMMHUDEZTWRSKTSDZFYJTVMKVWDHJGUEXPVHEAVRNPFZZCPKQAJCAPSFEIHCETCTPVDYHFVSIKYCRCNQBA', props),
compute('m_3_6/8: ${c} CXTXUSGHFSCEFVNVJMOATPWSSQKPTNAEBCERCHNKDMQDBLYKCKHBYKWDNDIXBTNXSTYDGZVLHIGKJVGHVZUDLWKDONJOCVCJLRHI', props),
compute('m_3_6/9: ${c} OVVKLTCPSNRYBDARTUVJLQTSZVEUBHAAPOUFCTBNFPDLJJOCCXCFZQCPQOLZGZFTANOCJEBZAOOMDAHDZSCECAGPZCLVLNGKUNPV', props),
compute('m_3_6/10: ${c} OBQNFFSDFTDQLRPNQTKMYKXKJNHXKFFUAAXHVRMLFDQRSANQOZBONUXLKGBBIGIHPAXSIZHREQPNZBONLGRDDSEWEMYIPZMSXPSZ', props),
compute('m_3_6/11: ${c} ILQYCPAXZQLQPEWXDEBJQJXVONIHDUPZITEZBGABLAYPMNQOBFSPMDCQOEQJYZSCGPBSXLKFQWLLKGNPDRZDFLSALGSUMYNWBAOR', props),
compute('m_3_6/12: ${c} SJXLCEOYDTAGINJVBNUKFVUDXMDJYEBPTSKJOPCCEXXCWPBZZYAGTFESORUPNWXEHVQRSOKOLEQEEYQFVFWCJMFVNYJYIZGXMOOM', props),
compute('m_3_6/13: ${c} AWJAWONIVKYFCWHNPJJTFGACOGFTLJOCZFYSXVSVFKVYDSTYYBKHOVAYCWKWBOHNKWXFDJYDLXIGDKLNTAJZMVKAQBIZJGANFSBJ', props),
compute('m_3_6/14: ${c} WPTUZYRPDFSGJELBXUPSKPVVOKTNQFEDARTOKAZTPVFVUEFTQMJKCJVTBINEZCXYAYMCCJZEVVKIWLKEWPKYRGQLIVZQCIPXBZOY', props),
compute('m_3_6/15: ${c} SFXLXMSGPNMPBDFDEONMLPCTXLXJLPCDPJBLPBHRWLDGGTELMNWDJHJEJALEBZCYVABBBGHYPQKTRDEYFSMDVYNJYMBAMQSXTHVL', props)
        ].join('\n');
      }
    