
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_8/1: ${c} WOSSMMLJYZFUSBXTAKUDEQOMWAAKOATURDTMBAZPPYGOPZXWRMTBBJEYVVSFKCANDSBSPRPTKTLMCJVHRKCSPUMZGLYTHADSWUAB', props),
compute('m_3_8/2: ${c} VDLOHGPDDOFJTJEUVXCBMWCFKHFPAVBVKNNQMPPBJICIFKBCJVQATWFSIGAPSZGZMJWUESQAORZGQAOHWNQTOTJAOMVKSQEBTYDN', props),
compute('m_3_8/3: ${c} PNLLFJWOEGYCDUYDWBCPURDJUWHTNAZRPHAJDEVTNGWDZJZREZKNBMLHPTJHOTWETIAXYKRVOLHFATZTJPNKBSAZICKIPWTYYDHP', props),
compute('m_3_8/4: ${c} ZVLKSNCBWTGXRBMINUECMTVDOHAGTFZFJEDUWFNXFIVSUGUMGHWZDNEVIGBXIEOLPWUUADKEFMRWRUJWYADFIBJYFQSXZEYSIJKN', props),
compute('m_3_8/5: ${c} MMKDLJGDKBCYJXCUWZCNSPVBUDRIPUVNRJKNFSFEACZBLMKOVHSJIUTNTENKLKENRRJARWEITQVTBXBGQAVAUNLMOUVBNZLIMLRZ', props),
compute('m_3_8/6: ${c} LBUIAMRGMKNTHFJQYYCJMTLZSFNOWZRXLDTSOSPYMSGYKWYLAYQXQKFMKYNYBGVGSXFJVFCQDGAHBSXCFRVIQUMFJBDGLKDJDURG', props),
compute('m_3_8/7: ${c} ESLSQVALJEBTEWWMMEOGVWCXPAFQXQGBQRFWQSJZGFTDUAGBMNZKDVGGGKKXGZATIETRDXVWCAIESVCIFMLVSOXQFMIQSERCALEJ', props),
compute('m_3_8/8: ${c} QCPGABUBQXOROXVJJTMEBRZARTOOGNYUZPBPGSWHRZJVRXHWXOOUYYDMBXKKUSAOBEBHSCNCFQTOUHIWKBAWZGUUPKXAEFVJVZJK', props),
compute('m_3_8/9: ${c} XYDMBBUDEYDZFKKJPUYUWHOBJZXWVMREFUWPGPTQNGBNJUPNTHIFDCWLWWYJSASMOBNGHTSIMEZAKRCWYKEUONSZOMMQSEDQPVRQ', props),
compute('m_3_8/10: ${c} ZIJVNHIWCSGOZGAIFPKLNZGGDBZVSHHGJZVHBLIJELUBMGPVATJOLSCGTGGDEPJCKIXZTITTZIVBJCHSJPENINZYEXVYIXDQAHIK', props),
compute('m_3_8/11: ${c} TYOBSSQTGNRLJEEFNXFYUVUXUXTSEZLVYKQEAMYMQWXIJNVAZNBRMXXBSBPRXCVZCUXZYTWTSGDBEXFGWGLNVJSRVYHNUYDESAVO', props),
compute('m_3_8/12: ${c} EFEOHKEMRFCZMRSSZGHDWOALRJREGUXEQDAUFCCJFSCCBZVGJUDOJFXAHPWZJVSWHZZGZVZMZCXDXHXPPAKKXGQFFOZXKZDDTACB', props),
compute('m_3_8/13: ${c} BVBWGYRCQGGJPGXFMJNQUNDYJZBAPLFZODKOOAYPTYAVKDNCGMPWJXUNZTEBHMYLMJKOVFXUQRXBGGQKMYSLIAUJYGZKAUZGMIRB', props),
compute('m_3_8/14: ${c} XQIYDIFHPNJJBEGMLIFKGTYGULXDWEDZBPYYIXAZLJJKOQOXXIXKHXNDSYUNVYYIBRNQDJQUCEESKBGNXBOJEZCONSIEURMWGARQ', props),
compute('m_3_8/15: ${c} MJDJHYUEXLWPFCTUWXMQZKPQHYOTPURRHOUIEJXDFEYYPNYKMRZXUNDSWEVQRBWGBZWWAXYQQRDDOHCIJVMVACZEDJFCPAHSISSF', props)
        ].join('\n');
      }
    