
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_7/1: ${c} DGSTROVPVGQJNCEJLXJXWENNBDXKUSXQBCYTOQUFJYNLMHZHXJJAFSVRCUAYXURBXFVTTSZQHRFRIBEVZMYJFVCIMDBEWHVBNUBD', props),
compute('m_3_7/2: ${c} IFDINBLOVQOCOJLUFMMWHIMDCCVXULSNXKHOUAPOTDCDKPSOFVFHLTELCXRXHNGUMUBYFERIBMFOPCJUWGBTQWKDVSJAODGQANUU', props),
compute('m_3_7/3: ${c} WNFNZQOCDMYZUPMSGEKVGNSBILFULOFVOAKFZZDIBDCEQHAJQBICKXPKLCBESCGVNPRNHMGIFRLJHQCRZJDIEWNAJXFTHHLJRWCQ', props),
compute('m_3_7/4: ${c} EBYEPNTIMGUYRFPTGCQHKIXEKOZUBGIPZQRBJAHCNNZEKJHGBYYHBAETAMWRLOWMTABYGPKIJQCNOXRHDSVGGOHGJUNIPQDVPAZV', props),
compute('m_3_7/5: ${c} IMTRBTZLRIYDMDPXSNWQVWAURHPRNVOJVGCWVPBBKMHXEYCAXJSQKPLNSXXDTYISNBIJCVACDQSOPKEBIBQUEIWQVDJAWXIBAXSS', props),
compute('m_3_7/6: ${c} WIPVPGJZLESOQPDIQXFTXHJGAVIDOAMFUGQLJAXRIGDCWXTEMNRFKDLJDRYJPFMRZWBQEJUKMZGNFTVCUTPTNSXOZPSVKBFBYMXM', props),
compute('m_3_7/7: ${c} MMXKWETSHIJIOIEGIHOFQZKOOPGYTHUJKSYMXTLVTYIZSHDISFXEKLQZLOREIUVHKDFTNUSOEGUIUFHPHBZYJMVPCBOAZRKPEOFS', props),
compute('m_3_7/8: ${c} QZKZVNGOZAYCYRCHJGWIDFKHPXMFXBFXAKNOJGRFNTGJUVQWTBELXDJTAOFRANKMAHPYJNOMOARHPEIGPFQGSQZTXFCRCFMLQYMD', props),
compute('m_3_7/9: ${c} XJERXCZKDMXKUMEXIYROJZOBOWRLMUNIIVAQUJZOXZNCEQRFWLOPDYEOAMBQWHLCHUEWOVIVWOHSRALEWMEZFWUYQIPAIGSIOGIP', props),
compute('m_3_7/10: ${c} PZUUTHMXWVMZHVMXAHBWXWKJLEOKXGOBYYEGCMCBDGOCDPNFQKWPXAVRRNJEHCLJOTYJPAFYYIELUTJWLDELVWWRLHWCMHIGSHGY', props),
compute('m_3_7/11: ${c} PKXOPQTNIHZTQGSRXBVCVAORCNLYFMIKROGVKTYHLIDDRGWDAWAFFURJHIDCLIZDJFLYMAGUHEAIJLTHGDIUXSSKOXTRERDWYHTF', props),
compute('m_3_7/12: ${c} NODNSQDUZEOSHHIQUWQJHIEEQPSEPTNOVLWVHYQBURMZMXYPDXUADSJFYBVHYIJIMVGPKGNBEKCIRXUXOAOJMSBSHQWSXKWQDQQF', props),
compute('m_3_7/13: ${c} BQDCWYVKYUDQSHZNRUPCSSWWINKHZYVLLPZIHRKRFYABJSWAYOYUBBZMOXHPWQLZLEJYJUPZGKWZKNKFQERVFYNWAJLQDFWVLTCB', props),
compute('m_3_7/14: ${c} LAZKYOYYWVEZWVTDLVSWDKWYOKRTJGZVGBPROYBDWZBYKDAVVSYNYYYOZIXYDTKSSVVCNUQIUZNEVWIUQKSVHRVLRGBLYNVUHTQM', props),
compute('m_3_7/15: ${c} EBLAZOZTPTAWRTLMWHWPNVUWRUEKXXVRXZSCSJWOEPYSZUNZHWZFWBXQLJZBNBQFZEJRPJCMVYPZFQXZHCOGGIVARYUUXGSNMNIF', props)
        ].join('\n');
      }
    