
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_18/1: ${c} BRJZQRWOXXSGXHOQGWGUZLOQLJUPKASLCAEEQYXEBGDTPKCIMKACZKIZYZRHXDQSBLAKOVHTYPQINQKDUMRSPAYPEESOTHMPHPHP', props),
compute('m_3_18/2: ${c} IZOHPAMZQTCFEXWBVTYNOWJQEOFPEGRFFJPKDELSODRREGBQPSXKPISQDPAGSLLLOYVLNMDSVGPXUCUMYJTKWQXDWPRBUGDZSEKT', props),
compute('m_3_18/3: ${c} IFAUEFZRZFNHKVOPRJKGVGNJNSCFXYPVYTUMJRFBKKDHCEQNVDUHHXIQMMKCQALCGTZWKONMMGCZHPSQFKOFJSILNBGMDHINOLRM', props),
compute('m_3_18/4: ${c} HVJIKWSDVPSFCYXJCJGYXCRMIKGUIMTKOAPZSQGCIKKDTPDIZZFUEYFKRGHVGQLEUPWKVZFDYJQJDLZQOAISGBILAAHFCLOVIPJR', props),
compute('m_3_18/5: ${c} UDVDGDAXHQEQQRYOKBJUYYYOIQWVBCMXDYFHJRAGYKRFFTUCTHTRWBFRYNJEYFNCJIOKTFIUSHUJKDBQWCMEZCCJUBBZEDQWAYDT', props),
compute('m_3_18/6: ${c} VDOHJJBDCWZRVAANTIQHKISDTOBCQBEWPJTIZHZXZHVZTSDOHACMEFSQZHIJSHWPVGJPPRKROMSXEZXYROTSGWBBFXMGIEOTVOJR', props),
compute('m_3_18/7: ${c} GFMLXNURKQXLVKGDZHUMFAQTKFMIJWNBIWUBLKSGHNITLHYESGTOJJNOXLAOOMNULAVFHVCGEQPVNRAUDDIBFMCALULQBCRKNPNV', props),
compute('m_3_18/8: ${c} WHPLIKZPCFZTRZXZYZEKDXVYBHHOLUGSJGCYYYHEGEUDOUBWEVFVYWYTIFAWQPQQZDYGDWGQQWQQSJSBVWTIMAHSYQVEMFNAQAZB', props),
compute('m_3_18/9: ${c} RQIMNXJJKUSPARXGRQANLXGMMDNXJFUHQVEJAFWKUQVQFTCXHETFKYLJINBOEIRHEJIIYXGCONLIKLYMCEXRJATBBAMVGMBERBPC', props),
compute('m_3_18/10: ${c} FUYZFGDIFQQUJCTRAHJBDUGDHIHYVHPXKAABYKMEOXBRLKJKGIPNYSRWCGWFKNFKBEAOWKZBYESXAOCNHWXVDDWKMQVUUAQJRIUA', props),
compute('m_3_18/11: ${c} OLPNXNKJHYKUJSLRAZVADAIFJQOJMRMQYUCPJKQCWLEKVWJMWEZNBZBIVWVBPOUEOVUDRAKZPCYXSDIAAZBAMVLULXWJDYVDCOYU', props),
compute('m_3_18/12: ${c} MDXJYXOJGDQLNTQNWOLMJLUZOQOWYCEXUCNVBYOPKTMNBJMUJALRGBFAWLTXADAAOSLFUCPQAOAHYSESVXANJJOZBJOMFDDGDTOX', props),
compute('m_3_18/13: ${c} LRQBSBXMEYLGRQPCHBUZCXUAVYYFYADBOTCHWQLYTTEFYDIWKWPMOVDMHNSRCARNEBTFSQDBTXGMSXCABAATTCCRMKGDXJJITCFA', props),
compute('m_3_18/14: ${c} VAVCAVNJPUDEGJNNRAPRXUJHLPCHWNMGBDRJJKAYRXQGOUXIYHESSNQVOHIQTUXWZWPUFXYFTCGSWYRIEQIQCQOBHYBXGATMLSRB', props),
compute('m_3_18/15: ${c} PCNIGKIUENAFHIXJYESMJUXMEUHSLYAHHAXJHTNKRRYVISBHJDJKNPKWRJYOQPKUXLKXSGKOIXGPPFDDUFXFBPTNEJSMYZWMTKUB', props)
        ].join('\n');
      }
    