
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_4/1: ${c} FILTUWJUZSZDFGNNFXPUKKUHPMJHNBDMHCBWTRFZSLGZJWZUZZHYKUZBZPUXJOZGCCHKBDQATPSSSJQZGTWVYSLXBJYPTCEAVSZC', props),
compute('m_3_4/2: ${c} EILQZIXFRHCVSNUOTPQQWUITNOZXIKNFPXQGTKFLOMHLGMDJTRUVHAJOXZJBFMAQLAQHZFQTNFGWAHPPVIMHXINQCUNLXLXBTOAZ', props),
compute('m_3_4/3: ${c} XCOJRTAJFUCZESCJMGEMMUELDBNGXWARFGSXXETDOVBBGWSYMDCIVEXEJLSBVWUNIZJSOTQLFWDRZYRTPVSQYRFPWXDOEAKKSBSR', props),
compute('m_3_4/4: ${c} ACKQYPQWVALHZXMVNYKDXVJRREVCZRCRTPEMJLKAYECHLSABQLEISYOKNLMCQEWICKKDDJJUAKYSSLPTMUGKUFCZQVZHDDOOGZFE', props),
compute('m_3_4/5: ${c} VRWFEQNZIOCKTINOWHPURJSIECECEOWHMGLIZIJKARYWSGPHHUUUKAEPGJOHGYUBIJIXRBSDAHGVREJEHMGEWBULBDYLHTYCNROD', props),
compute('m_3_4/6: ${c} USLRMSGPZJVRFPWSZBQENGMSBHVKJTQSCWYIEVHQDQLURDFZSMSKTOBBYUHDKSWOQXXBPYXNOEQOVSXLBHPRHFYEUMFXIXBUDTVS', props),
compute('m_3_4/7: ${c} WSFOMEGKFPTBEUKHZPHLEUSJZJSTVCLTDDOXLZAKABRATPRZGRBWSUQRCNISNVSEDVKYYERVTZZMDGHKHFZQRSLQQLBXCISPKOAK', props),
compute('m_3_4/8: ${c} TZHRWFLLHQQABBDFNMVEAFSONVJBOTWYPIQLVQEWJNDOEXCUOUUIHQQKKDGFAWUICEMIDLZMHZPHQAOILMOAYCWTZVOPVIYVLEQH', props),
compute('m_3_4/9: ${c} HABORNYXGUGWVYPXETZGBILNENXVCHUFKCWMEDTRBILAABDWABPJFUHVMBQCYBFJUYMHMRUUPNJTLSBBQAYOGMUCOWQANMQZGTJR', props),
compute('m_3_4/10: ${c} SDEMGEJKPWJKVXNHXZRHYIGXYKBYNNYPETHKVAGVVBBGPKOGUXBOPIMNAIUQSZLPVRPBIXLZDTTHHEYHZTSKASMPOLJEMMYVEGNK', props),
compute('m_3_4/11: ${c} BNPSLFSUERVPRAQFMEXVGNTKGEWKUGZFGUHZVVPOPONRIGSLJPEPJRUSHGDDUNPJGEJEIBAZCOCUXQLNVPOOIACNXCQFPJECJUKT', props),
compute('m_3_4/12: ${c} RSDJTRUQENPZHYIZTKDNQUEEPNXAZOHKEYKOHKFUSNEJKZERYKEWSRHHHZJDEDXAUDGPTGNOTZJYAKJENJXOQVPROATYMLCIQFCC', props),
compute('m_3_4/13: ${c} LRQZJWXYRBJTIBYJYOPXEGHPNGBZWUPVGVUKPWTIUZPXDDTTWJPENTYBJEURSFSYTYHXIAGHKAZUTUWENGNNHSSQMZHLDXMBNNSI', props),
compute('m_3_4/14: ${c} LVSWTMXSIEQBKEABWKEQTODMGNRQPRMULCVTYJXOJCLAPYZZSHYIDBOYIQKQMBGZRWYTKKERYJJFJYHEFJFFMDGGVOWEMWMQSCTW', props),
compute('m_3_4/15: ${c} KAGUEGAOSZPZVIGENKXRNLKNTAQSGSQZEZDJLPIWZFPSSYRDNZBNBQCDXKZJRLFGQWMHCULWJBNDQDGEMWXOUCCUJCJPZAHFXLQT', props)
        ].join('\n');
      }
    