
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_3_12/1: ${c} RXLZRLNQWEUCMQSUQKCBRYFTEWAPCCOARJCYHEXJHQXYYSOGVEFSUXSIVJMATKOMLDIVROPLNEPOIQTYHYNHJWTOVTWSGUMUROYK', props),
compute('m_3_12/2: ${c} VTTNNPLZXDUPOYAZXBIKFMMJYWPNNBLXVSDEUSSSWHWDVLJLPZEBWEQFDBSKEYFOICHJLJFXUOEJRKJICENDTWAWXIYDZWSQQOWM', props),
compute('m_3_12/3: ${c} TVMWNXBDSGNGJQEGNLVLNXYIWHULXUADFIZQZPVNCUQSDDRLPUQDJGNHIKEHTVSAOJXPFXUKGRMNUDCXYWHNYVFJHMFAEKKOFLDD', props),
compute('m_3_12/4: ${c} QFJHOBUAFKDBNGOMUFLLYWZONIKKDXLKQYYKGUNWETXDJQFXREBFWVFSMXSMAQJNKOKOTVPVDAOKLKMWXSJBRFTIBWLDFBRMIAZW', props),
compute('m_3_12/5: ${c} ZUUMEYLMMUJKVBZSBLLQRJLHNXVMZQKYMONNQJGWVDWHZSVFCOIGVVCWJFOHREXJWGZTPTDLPMASBMSLDXKIXCFUIPRTGQRGLOYY', props),
compute('m_3_12/6: ${c} VSBMTEYOAIRBHNDEJTZHQUQOQESUTWSKRGTEAJTSGIDPUPGVNSTTQAOGPSQDRYUGCDSQPQHPEONMZJBZQIODWYBOGKMTZUGYOCCV', props),
compute('m_3_12/7: ${c} TUFGLSJOLODCNNDMDQXKAOTHFEJUHPEFXHCKIYEUDCNHROLOASPQUOJITZTUSPRECPHMJDXBYEOYPEWPDQPULOXZIUDVKLDNCMST', props),
compute('m_3_12/8: ${c} BMVWMIQYYMIXODUVHWPXVJKDWTPBSMJWEBOTBCYKPKEBIKNVMLZHIDJDEIVCCEJWIWCOQCRLSIJGBQVJNTGYIXFZZPGBLFWTKYCO', props),
compute('m_3_12/9: ${c} LISMRWXDUIADLHELZDKLRRPPJWFEFNOKXVBRAFEYVJPGFQVPKRNNVJAPOLUQXOIEFQPDNREABUXOLQLLQWUZTIQJCNCFBOAUCPTN', props),
compute('m_3_12/10: ${c} SMOGIUFPPQOAUFGDFBEDWLCAJCWQTYKLJSXVEFLFCJCQPHCHTFMGNMSCPKRWRHLDOYSOTXOBLEZWOLPQWZUZGKENYMHWHOCCMWVH', props),
compute('m_3_12/11: ${c} HVFIHEVHFEGSKXXUCGJFAOYYXBQVRZHIAOQPSCYTZGFOCPNFIGBUCIDPZWKJPPZBOCYDITXOCLRTWDUTCVUXJJXDNSHIPIHOKFZU', props),
compute('m_3_12/12: ${c} CXTAPBBSPJLZSIOHIFRXRONCBAXFTEFAXDUPNXXXFQIMHLFEAWETLCXACEXXOSNJJSUABVYILESYSCNQBFYXNFAQAPYNDYFDRIZI', props),
compute('m_3_12/13: ${c} FOTRYTFYOWNJIVKPIWNLYXZWDHDUXLTQNZXMIJOTVCIGQGACLVCPVWOBEPCVFYTXGBWIOJTFZSJKGVIXOAFNGNLSBABJKYCOXMHV', props),
compute('m_3_12/14: ${c} NHAHRHUQJFGOMRJUCAZSFTHVMXBPOTJENSWMPXTIZNQANVJIFZHYIYDGGWKJASCOTURKPNLEHWBJVNHOCJMBVBVTYTBLAQSHJLDT', props),
compute('m_3_12/15: ${c} PGZOZHTRQYQKTDYCIIMHLXWXRFWNPPTUYDJMJNPIVLPLOOXYIQFTSWVJTPPMJNPOCLVJUDGCAKXLKBELNJDRMTBZDQZTYDZROISA', props)
        ].join('\n');
      }
    