
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_4/1: ${c} GMMFQFWTMJNWIBSQVKNXLOITJHOCRBPWMHDCAMYXHJSVVMCJAXIFTENUSBUYYSOKRQNDRUVBOFOLLRZUCSCAOMMCUPDKWLZYKYZA', props),
compute('m_4_4/2: ${c} XOEFFLBPRTDFYCONRNZARBHJGGLAKAYMZYBKJUTVHQZUYGHSXHUBQXDFTLPTAQBQOSJIEFVYOBMPGGRIKEPESQLHGIXCHVILFPUV', props),
compute('m_4_4/3: ${c} CHZALRQAORRDDQEKQZWTASKBJGESXTTDPLZJANDJHSRALYHKAYKNEYLMFOOETRZWRCWJDRFRVCPYSHBPEALCFWTBEZYMRPFJLPRZ', props),
compute('m_4_4/4: ${c} KYLFAEUBBDCTYLSFXTOAZWLUWVQQYMOMNZUVFPDEYFPGWRMNMYGJMBMNSPEVKUHMYPFQGHNSCDQEEPFTJXNSKJDFUMWWOQYZMPGM', props),
compute('m_4_4/5: ${c} EUWEOEBFQPKSGZSENTSWUKSUWEFTULRKMXPNGGVQMVWAFDIQIHCBYLWZFZAAXSHJLHICFRMFHCGYKVYYLGXWYKTVJXDPGXDOSUSK', props),
compute('m_4_4/6: ${c} DESUPJAIOMWAGPMPJUDCXLKSMGIXKAVBMXMKJUAHHAVMSEFQVWEMKRGBCFWYWWPTVSUVTOTJVICDUCZMPDSYMSEKFKJILOXBMXCF', props),
compute('m_4_4/7: ${c} WCNYOTZVRMVADNHJAFJLEXZNNFTNAKBTEUQYWBBABZXGROEZYLJDVDBSJAJOFEJCYSJFYETKYKQLUPWHJFCHYIOTDSNKXPXCXSAQ', props),
compute('m_4_4/8: ${c} ZZCGYWXOAJICJVEXFCIGWTRNBVCWPNMBJWXPIBHFPTBSGBSJOAKWQOELYTQXIQVVZSZNWZZANNNWFJUAIRZOPVHUTPELLHZHJEMD', props),
compute('m_4_4/9: ${c} XYFDREFTKVIWUTMXRFRBMRGSWWDEJSCCWAYZYITMEXQBVBSAJQTIJJAGCKJJWHRIHUTXDXSEXIBKPZCZTDDXKFCARTCBATWSPLDM', props),
compute('m_4_4/10: ${c} NSCOQYXDYALZDQBAYMSRIRIIHRIWKGYEMSFPGKFDLQKCTOBRDSKJEVECPSEYKKOQFPGTGUIWIUPXMKPZGVEPEGGMJDVWFTLCHVSE', props),
compute('m_4_4/11: ${c} ELZIXNNEQBWMXWCCORCMHQAPTTJZNLQYCCIKJLGUPBLGADKCRNQQXPNXSDMCBXMFLOZSIXALITMPXVRJWLGTHZRZPBQRMAYTFACP', props),
compute('m_4_4/12: ${c} GGBFALDBWPZGBFUBGAKNJQTMZYPQBHNKCSOPGYDHRLTSXNOAYEQQNDBLYAEFKEXKOVMZDEJTWGCLGVPIBZYEHTNTVGZCVXUYWNOX', props),
compute('m_4_4/13: ${c} KMISBWDUIUSJGCSSKDVEKFUXWGMRTGDOWKEPHPLOUORHMCHRAKETNJLGTLHGUGLGMLNLSXVZSHSUACQPLDEEBLQQSETIKODJXPSW', props),
compute('m_4_4/14: ${c} UBIPALWUJLEGHEIHGFPJRJNJELFXLBHOWSLDFLVEAKUEAVWELDKVXLVNZXWYQWTSELHWZORECZYQOQTULREYIRCYTIWTJNRSRFGR', props),
compute('m_4_4/15: ${c} XKLYUKHKMWPMOVDYTQSQLVVLVQLTWANRMEYLKEWDDZHJOJBYIGZCSVZCMBKLLLPFUFBINFKVUYUFARTTQEDZQGFSXMHAESQMANMN', props)
        ].join('\n');
      }
    