
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_11/1: ${c} GHGAQLGVGKQWDQJITRJUSQBPGDKTCCCSVVSXQAPPJJFRGMUQDJADTUESIYHHNBYZMMVLMIAEJYNQROIPNUAMYADNLMCYRWBMDGMI', props),
compute('m_4_11/2: ${c} IRBIIXACTFCXJJCXQUGCBYJLLMYKCVFSDDHMGSUSHADIZAYLCYGGSGTXGJJPKUFUPVMKYKFONFGPRPOHVONOQHYHUXJECPBZFTBH', props),
compute('m_4_11/3: ${c} ZHQVHWTHSGXFGMGETYCQHMQMJHZPAUVBNBHAVYABIXYWZCGVBQERRQWWCMCKXBCLTHVCDRZOSQTVUEAPBUSLSCTLJANHXWHCTHMW', props),
compute('m_4_11/4: ${c} PSXNMLUNMEKWKAOTOTDVCZHDCRCPZWROALCJQWMJZWYGEREJWYQNVWNUNQCOHQQNQZBWAVGIFJWOGZCUZLGCYYZZGPXABGMJZBHV', props),
compute('m_4_11/5: ${c} YOZJLNQUIEAHCWSQGRSPBLJBYAWYBPTIODWVOLZLMHCLGEEWRRINNBIERCTOREIBQUGWSQBXRYQPPYLSRVDASBTUQGPYPMADRGUR', props),
compute('m_4_11/6: ${c} IGQCPNGBJJVWVAPWHBFQHYMIGGGRRBKVLZFVTSFNYKWDBVWLIURZMOUMQNMXEQBZVXETHKGXEIACWFJOJAZDXLAYETZEWSNZULFB', props),
compute('m_4_11/7: ${c} ZFZZOJVQBOLOTSNIHIXLRKBCFRCBYSPVWGKIGBUDCAWYONXLDAHWFZLCOOHSFEOCHNRIUYDNOIZNVYBWVSPSDOXVEAARJOSCJEJQ', props),
compute('m_4_11/8: ${c} PZKPGDDQNOYKZLPXRHOFWGWMNSOOZCJJUETAQJQMGQWKRQISKCFYZNQFSMURLGTNPEYGMOLQEBDNEDJFEKAXZKOBVBHDUKIQQEGA', props),
compute('m_4_11/9: ${c} FFNOCAGTRJURTHAJBPMAHZSPFHXMSCZMJVSWNHTTVTGOJXVESSZWJSNFRKDJNTMUPXOPFYYCLJNWDVFKQHNERZNLJXRHHSXFNRDT', props),
compute('m_4_11/10: ${c} UKUCHKZXAHDTEQKCEELJJBJSINRBDADDCWPEKVNNQRUVRSHFSXEIXEUKCOIJEIPQHLWWEYRXDABHDOQCGDNJJWFLQFBLPPWXEFHW', props),
compute('m_4_11/11: ${c} QBTSSUZHNOYMTZFEZNHOEOTQJQOLPLURNLSFFMDIEZCNCUHASREEJTYXAGLIQMEZTCQZWMFVKMJXPMTAYGPLAEDBYDVSAEGXOWJL', props),
compute('m_4_11/12: ${c} OWNOSLPAZQMHXUYLEWAUJDHUVALTXHUUZGTVHWYMEFULKTWVWYZWAPOSBINQAJRJYLRFIVENTOSHCQHWXQPAJCXDVCZNMBTADCJA', props),
compute('m_4_11/13: ${c} HUCVABSRPTANVOAHZGLEFJAZVUILAOAIIQLBUWZETIWAGGPGVCNDTDZJCDQDVTILADQKGKAVHIHNLIXCRBPTRRXQZAQSJQSOEZGC', props),
compute('m_4_11/14: ${c} KNEZGYJAEWWEUWLGYBSJXEHLMGOSGSFDUQIVJGBQEPCJDUOEZZOGPNRSPPRXKASBMTYRWUCUJUAKSKIJHYXVEOJCCVHRMNHHCRZE', props),
compute('m_4_11/15: ${c} UDDNCQWMLVKJXRJYTQMRTEDRGBEXIOGHOFWVFLFEDYRQBGBUNZXTPLDGGZCXKNOTZXZFURYSYOUYLWGEUVOBVEVDUQRFBKNHMXFO', props)
        ].join('\n');
      }
    