
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_13/1: ${c} HQHLVGRYWQILIVXSMQCCKQXOVQVLUVMJVAVCJAWUOHKOWFRJIHZAYOPYWJHQMUUNUFWYYJJSZKQSXLYQRUGOZTGPIJOVKGOOADZM', props),
compute('m_4_13/2: ${c} TEZFLQMUHBINTQMOUXBZRCNVPOAIMIROGHOYKUCZGAESTJVWEFFQHUUVHHAXYYWSYDCMZOEMBYOFLMUHBJQUZBLYOMMNSWLWURZB', props),
compute('m_4_13/3: ${c} EBPGMONIALLQOOHDTRSGNMADJBLZFYXDZKAACKLHBGJXEFIJSNSZNQIIAZPHQXOHFAPHSQOIIVEVNMMNZVTVJOEFZLABQFNVNWWE', props),
compute('m_4_13/4: ${c} DKGEATBUTEHYRBIRDNIQSQIBQUQRIORTGNNYXNQOBKSINXORXEAMXGBJQJTPUOUZBXNGHCHJONEFTJANXTNYALBBZZJNMGSXCETJ', props),
compute('m_4_13/5: ${c} SKUCSPEWMJHDYFFHKVKEOEGPMUHWNJCMSRHAKBPJZTHIGBHTOMWYZHKMCOEFSSMWVZJFEWTNAMZINLRJKSNWZGATSWMSYEXWVDZB', props),
compute('m_4_13/6: ${c} EDROWAFHJSWVBZYJMHFGBHEZICEFGSXIORZRPRIDJBDIONKPKBZSPVEJJULDILWYAOMDZQEPCTSKNYEWFCUCSMFHORKQGUKPJOAV', props),
compute('m_4_13/7: ${c} LWWHZKTEKXXJOQXXFPWWFUVOUGLLJSKIDZNXGYOBFGBQSJKCJMIKMQFQWOOMLEQSYPNXCDKWRJIYAPSBDNSYHRNCWNDQRPRXQPSB', props),
compute('m_4_13/8: ${c} QHEIWEYVFWNUMQIRXMGXIBTTYSJATNFPIHXXEFDOYQXJSHOIRADIAPXCQGJJLIQXTXYKRXIQZDUSDSQCMOYLAGHOVHKLPSRTWWPA', props),
compute('m_4_13/9: ${c} YEWITGSFBPVVRVBQTFJCUDDYXAPOLXDFSZSZMZZGOZLELULENOUZGYIKDZDWUBTXKSTEUJIDXPTNDCXXQAMHZZUZOKCHOSRITNAK', props),
compute('m_4_13/10: ${c} RSZDYUIFGCSZEHTTKIDSIRHOSJFYHAZIVXDMTZQAJZXDOIOCAYVNRRFREZMIWPEBNNQAPMXJUWOFNFCXRACHPZDRIMGACUGRTAWN', props),
compute('m_4_13/11: ${c} TUOHKZPEWTTBIXTJCRCCVCHORPRZCDKSLUKOWAIOQSQSOTDQVACBEYFZCNJGBEPIIYSNNOPSLXNYAAKVOIPLIHYVIWWNABWDMVXU', props),
compute('m_4_13/12: ${c} TWANVMLSPOOGDPVVJBZSILCDCXFTEHVRJOQDQSYREQYAHXSMDZVVELEPAJJOLADJDOICNENDDGOUPZBIENHQYHUOVXHLFCZBZZSI', props),
compute('m_4_13/13: ${c} ZOKGETISWCOHGXZDBIGSIJGYEFJEYNXQZKLTOXIFDPTHENMKKKWDCVCENRXSOBOFQAIZZFXCZAWANOCOIPTTSCQCEGEAIGOSIHQG', props),
compute('m_4_13/14: ${c} UEVUETKMSZDBUVRZIVWLRCNITVRIYLYNPZZCZIVNYVVOQWCJPPODRIUEEYDXOJHUJCPOFWIZVRRPSBAWYEUDDIQZMBIZPWVEBFIQ', props),
compute('m_4_13/15: ${c} WOAYHMKFOHHTIYVEAHHMOIYYJVNGWFEBJGRDZBFDPCDYADNMCQXWPYYTNCVCUIIIDAXNWLHFPMOPBWBGRXWWBXLYKFBZMCWALWEU', props)
        ].join('\n');
      }
    