
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_19/1: ${c} WLCKSVJDOTGBDXGEUDWXGAQDYXSLVJKJKWODKVMHPIONYHPQEXHTACQOFPKJNYZOVJCFPXSUQLBJVQKKCERYGDCTGJOUIVWIZMJK', props),
compute('m_4_19/2: ${c} DPQNDKOFSBNNTZVSGQKPBLVBTDRYCKRVGYSQFGSHMJCYSMKUGSQEORPAGLDAHYWYSXKKJNJVNVHTQLKXYYJDAGCTOMKWBLBISAWA', props),
compute('m_4_19/3: ${c} GCDFPEMEFSJKGDALMUGNOBEWOTLQEMRPJUFBFCRVNMBWNQDITTFEWSRGUAOJBOVFJHEFQQDHBLTQKJEEWLQFJKNNMOUTTBGRNECC', props),
compute('m_4_19/4: ${c} QBMILPONGIKQKKIEODLKWRXKIOTSZENDBTDHQQLDTJTWTNHFZQMIYMFZJRNUGIOBEHDUALWOTDKNXHRTSLHYBVFGUFKPWMGKOKOD', props),
compute('m_4_19/5: ${c} SYEOHNAJSZLUSPRUFNHBTZPUPTBFRJUKDRRTTHNNCKSXKEBMMUJGZDLKXKQULBSTUVXKDATSJQNGJVDAKHHFKPMWIGRHLQQYZMUD', props),
compute('m_4_19/6: ${c} TVCNRSAMTPQRAXCCBVHHEWSAFWSTJLTOKHHIBXQHRALTIAEBATIHKAKLMOOVFCIEWJZNPNSHUHTRDGKLLYLGCWWWXTCOLYDNKZTT', props),
compute('m_4_19/7: ${c} ZTGCDGTCWEBVPKJWULYWSMNHWVQDYKYDKCWORZQOPLRIHLCPXPIVCNFCROGHLNWISZAJALANUYFMQIGVCBMWVBWAPVICMLQBIERJ', props),
compute('m_4_19/8: ${c} GXBYFNQVGRMOAZJQZYBOYIBANGZDPMJKPTSXEHATVQXFPFIQOKPHWGEUURHYFILZOCGSCNCKUGPILRTEMZABQJDUJGGFNXBBLFWI', props),
compute('m_4_19/9: ${c} TMQDJGSWQDPAYHYBFAUGDRNEMZEZXEYBYBZHAVKRFTZNPGBXFPEMRMYVSZAPBKSJEFXCERCETALLXRVZQCUHXZXLENMXGSHHCSHM', props),
compute('m_4_19/10: ${c} XEJFPXWNOYZFVKVXOMRYXLEUCBVFZJJSEALHPWCEKEKVDMCSWROTKIRPKMZQWSPFEUJCAOITSXTTOQXJWGZIMADDLRNBMSWEXLRD', props),
compute('m_4_19/11: ${c} SLOOCIIGJJINMNGMWWZJHDXAPVHAZZINVTAYFKIEPHLTSDFCMLWANQLCPCMUYHBANLWLVECXFDEGLINMNQJJIOKIDEQFMJEACOHP', props),
compute('m_4_19/12: ${c} MOUWJQSEUCJXHAOICNPYRXUZISLMUVDTMNILKEODGTRLHGUJYHOZYBZRSGAVGNWSTPKUOKDMOSOVBSCAESUVOPILIJIYFFKNQTDV', props),
compute('m_4_19/13: ${c} UYKXXDQWLPQTOUWYLFUTBSHYEGLCXCISXEKZFKSZHOAWZNPHPBFVXEVKIBYRLQFXGETYYGQBMEZILEESGAVJDKPXBLPHNOCBQMTM', props),
compute('m_4_19/14: ${c} OWGCPLADNURIXNBQEWOODMMBOEEFHZSBWWMWSVQRIGRABKTDLPSOFMRMCRNEMIBGWSUDZFPFNUMMJNBGNYUILOOZCREFWMNMRGPZ', props),
compute('m_4_19/15: ${c} GWLBQXIWROOQMWZEERFWFNKCOCGYKKYYCQXUHIPVRXNLODLLQCHOXIQMNGKRMJLEOUGOWXEXKQNXAQWKCMUOLYMINYUZFFZMBABX', props)
        ].join('\n');
      }
    