
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_9/1: ${c} IPENNUUSGVRJZHQIDELIPASUHGYORSBQMYPHLQCSQYDRYVGDTMECNSFVVOWFTZLQVNWVIQCNZHRAQYFUHDSEJYLZOEMOIXYOLLOM', props),
compute('m_4_9/2: ${c} BFFEGNYYAFOMTLARKGXAKDPZRNNEUOGVNHOBZDNEVIVLPIUUCGLCVNBYOKVILGCLUIAKISNHOWBUXPNRCYUIZPSJALGBPKQHHRQW', props),
compute('m_4_9/3: ${c} IHPZQLGEEJNVPWVUQEWRSAQTCIAZNQGCUWQYDFVZFKBEGVJKIJASKWNFVYMYXZMPNWPHPXPHDHJVHXYPJTXKBFVHHZSGYZWXLTJF', props),
compute('m_4_9/4: ${c} DQJVWVTEDXWMERTSYIULJLNQTVQYRKXLSEMAWTJZCAEWVJJNZZUEEUODGMEEQDPNQVGPZIWIFFGIFWZYAJJLRRHMSBCQOZHAQBXW', props),
compute('m_4_9/5: ${c} HALRCIHWEMUZKNQTNWZFONJMKPJKLCORFIPYFRDEVRHURTFOQIXDSFIYDHWZJNNLWOFTNDNUCOMUDJWVOMLHMLGHWAXNKEUKBEPM', props),
compute('m_4_9/6: ${c} KVUPETJFCOLLVLGBECLXXGNFYUJUZQXTZWDCZMZKBQNPBNPXRWTWTRSSOEXNLWRKXERWJTRAJWKJLCKZMUCZEVMEITZCBXVZLYDS', props),
compute('m_4_9/7: ${c} OXIEUQVVXGYDAWDWZYEZJMUZGAZDMPLTKFSHWVWXHCJTNFJQAZCQGCIFALJNFYGJVKCBERSVVNNMOINBDUMOYAYLILPUPNPXIDNI', props),
compute('m_4_9/8: ${c} SRGDYXMJMHSBMJYRTGJASNHDBCYDIQFJLOJIXNFAMOVDXUVPGOKXYMMOSVHGBXRQHUAPGJQQATBAAOBFQFANXDEGSXVWBBQIRRVH', props),
compute('m_4_9/9: ${c} SOPBUBEBISFWTJGRWHFHCXGBWTMNNSTFBYSOTEZFKIJHLWAPDCURSJFUJTPQAXUGNJIZNWZHHTYPQTWNWGNRXXWMRXBWZWFLZZWB', props),
compute('m_4_9/10: ${c} SKKLCKJQIERQTIVDYUDZFRTVWGKVAOBFOCGZAEHBZAJRBJMCMRBHJFTVPAAHTBDGUNJHLFMEWTMFGQYHQOGMAPHEPSJYATEHEBVK', props),
compute('m_4_9/11: ${c} VRLOZEDQUJSGWLEHHNOEHSCKVTBRAWCZSQEOTCIQCZYUDAOKUJORVUBNJWNKQIBSITDCXJEUGLOABGIPOTURQNFHVUZQQLUFVYHC', props),
compute('m_4_9/12: ${c} IBYOJYASZXBFLSBNZUZEVVRBJKPIQANGUHIXNSZFKEYTPRBVASRUFYWSOZVXIVPPSAUPUHFUXUMDPJFZYMVGBBIVPVBDQEQDVKNP', props),
compute('m_4_9/13: ${c} UCCEEXNFELDUPEPLPYDEXAHUSJEVCQRDQLIKUMAVZUOYOVQBFMVPNVRWJTCSUQSDMPGOEFDMQAXLACEUVOHEYYFZPLGIOZLLHJWI', props),
compute('m_4_9/14: ${c} XOYZUOLGVRMQROYZRHERQAPYOCOMYJFDYOVIOCIIMPIAUFUBVEORWSAEZHPAJTPHRQKTLUMEMFVMSQZASAQJOPDJGQQDXJVJUNLO', props),
compute('m_4_9/15: ${c} PPOTSBORABQCXNZKMEIJUHNIBIRNYJIGVCEGIJSVMXXPLVPKLSGRGLIDLJICZLJYOEDRWTCZABMSNKXDIFRHNFSRWUUZJPPJKTDH', props)
        ].join('\n');
      }
    