
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_7/1: ${c} QWLRWPXUTUKPPWUMXFRJKHMXGYTQCRAAWFXPESLWIGRKNWJBVGMMKYGOXYJDYYYCAQCHHKEXCZYLETYWYFWMQIUTYXWVWJVSITCJ', props),
compute('m_4_7/2: ${c} YFPWUKLKHBYWSIMIRGAJCDQFJRBCNRXMXDZBUPPXXJXHPKYWTDDUWTQOMLCJNWWNKFYXUQVJPWPKWIHRWEYFZTTTYDLWWSIWZNMU', props),
compute('m_4_7/3: ${c} AJDAXXBFFRFUTTTISGEQEOXWUOUDZOUMSXUSOTXTEGUDOZFFGAMCBILBERLEOXIOJVOAKXTIGESZCTLVTZGODUZISOCFNQSPYRTG', props),
compute('m_4_7/4: ${c} NAEDFQHWCQSOFUMNTUOYKZVUBEQXANURHPVJMATCVYEKTGHSIXKULUFECUUCWEKMZVMKMBNVEMRGSNXSJKYVLKDVWVGHEAXVKHOJ', props),
compute('m_4_7/5: ${c} YYDFWEWKQNYEOIOZGZXQVNGTVEQMQWYUDSOSNSGUVLVAYAPTYOASRLDNYILLJEOQUOFBULHRKRBIUEHSTNQBPNNIOCRWRUSLORGX', props),
compute('m_4_7/6: ${c} OPIBDFIWJYZDQTAEGQLGVFVKSTQHHNDLBBJIIEJQIGWNWAHWSKTOPVNDRDCZVOJSMUZQOEKSJWXGAMSUNGVVPYYJTMTLBKXYDGHE', props),
compute('m_4_7/7: ${c} YYGZXMCKSCUJPIEJLZOIVIXILFYVWUSGKEHOJKRNGKSXXCJTAKQZZXPYSCXSGSAGLSIDDLRFJSUTVBXRMDBYMNYGARECXEEEWANX', props),
compute('m_4_7/8: ${c} TMJOGKXMEOVZHWVNLGDXNNYCITYJBYOFYSRRCCEOYPSAMNWTHROVNIRTMQMALENPSJZTXJNZVQSMRTATZBMMTUFMXDOUIQVZSSYV', props),
compute('m_4_7/9: ${c} TXJMPTRDUJZVIFHTZEDNMPBMTIBYHSUCTCNTHGFOLVLKUAQELBNOAQFDOSQRHYVIBXOJLFHZVQNOUPFDEUJTTKOUTGUISBRULGST', props),
compute('m_4_7/10: ${c} UIKJIHNMWDUQNAWIHASWYZKRWABUHMDNJKYBKZQSUIOGWFSMONBWQIXIXFIZOOIHUKORWUBZNPDBEBEXEBCZIQSJLJLEVUHFLSUI', props),
compute('m_4_7/11: ${c} ONEPSMFOHLWIWQPGDLTCQIKSRWEMLDCMYFEKMZFABURDDGCZHDBNDKRTSHRNDROIXQYARWBUUQZROAOFPAWTGNHDKIDAANZJMYJP', props),
compute('m_4_7/12: ${c} WCEZGKIIKWFZGYPJZIXGIOUNQIKBEFYJRSNNJRBPBFYNUACYCKNQQHIGLWITFQOTWWLZMBOUYBLSXJJJLGLBXERXUBKVOPZSXRDZ', props),
compute('m_4_7/13: ${c} XUWHSHOIWRBANTBCMHLPJPAVEDVQEOSYYASAFAKNWYWTFXAGJGIRVNGSAROZLKUULZFLTNUKJQYLJJVGXELRDEDYCSBIAEQCWLJB', props),
compute('m_4_7/14: ${c} SFYCDQIYTYYHFXUIHVYAADAWAKUQLALGVJFAPEZRVVHUQPRPOIHEQYAPMQNSLVAALVRVEXRNNJGALQJSHSQHFMPFFREGSIYGEKSN', props),
compute('m_4_7/15: ${c} OUKBFBTOBLZQSJWVCXWFCGFBZZFDGCHBESPVMEUKNKLLWEDEMTTYULSERMDMVGMAERFBMWSIPRISUCPETAASNIYJAWROLJOQSWUC', props)
        ].join('\n');
      }
    