
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_3/1: ${c} TMDOCMLWRSCPMWZKXNTXHZHJXDVADDUZLFZFHXDCMIGVSTRXDLDJTQCYSUNMDKRXGHDQTSMFZEIYOEGRNAZVLSTEZKVTWJEMQTNT', props),
compute('m_4_3/2: ${c} LXCAVTWQMXHJXROLXWGIRBNVDRPKWITPPZFRFGWXDVZKPKUWGWLYJIOYRFDDUGKLQWWKBAFQDFLOBZMQKZWZUAFMREMTBURZOYUU', props),
compute('m_4_3/3: ${c} UUURWQYTXNMOQBMXJEMOUSSXOMNTNKMCKOKVYFUSKZUMIGQRRANFDZVIGSSFKFENVFYQSKUAEQCPTBHRBFYVTXWSVPZGCLISWNHH', props),
compute('m_4_3/4: ${c} NBXFYQWVGOMKGCZTPFIHMQJNHOICVOMNQEELROVAJGBQUGPHNOVRCKKBZRTGWEPQITXBXPQJWEFQRROKVQBODVWQDFTGWXDAXRTT', props),
compute('m_4_3/5: ${c} OVHGUMIAPQHZUGMKURHAQUJDCVKLTHKKQBKILLGUZWTPHAGIOPMZFSIHAYZCJKLISARMJCNQGBVXIKFPKVBTFPPSSFSHLPBNOEDW', props),
compute('m_4_3/6: ${c} JLHBJKTHPPNGPBZJXSIJWYDVPKNCWPXJWPMTBMCNYIXXVATXSWSVXMFDLSWWVBLDGXNXYRIRQYGENRUVDUIHMWRFPPUNHFOBRQUY', props),
compute('m_4_3/7: ${c} HBGYQSXVZGUVMJCWYQHHXJGZVYXEAPLTZZLRMCDQZVUYDKJQKXJOPLRMAPWWUTWQJQNJKDKYABXYBIAHDRFOSLKRWTOJIWZUVZAO', props),
compute('m_4_3/8: ${c} GFPDYIWCRSPRMWJOCJVGGIKLUYLVVFLUCXIYGUOJVLCIKGUOONQPHIOQOLUNFSTPKOOTFKMUIRHRDSXKYZWIFZFDKRLMVIYBVAFT', props),
compute('m_4_3/9: ${c} JNAVTCQCGYUAKRFGODBDIHUYEGFYJAGNNRWLRWIRLWHCFFGEKJXKRDQCNLITWBSTSGINYDDLIISDMTIDJXCGDIHOSXFNLJGDCHXK', props),
compute('m_4_3/10: ${c} VNZIFCBJHHRTQWRDZGXNKWOVRQHKUOPZLUEWOPXWLCMINHSPWZFVPRXGVMYOTCXNXXGULLNHSPLNJQANYKMOXCVLFMKCPYBEQWFP', props),
compute('m_4_3/11: ${c} DCHLONTSHGNADRAVIWCLMDDDBBUZTSKQZHUFIMAGLWXGPVDOMOMKUTRYYMXBHXDORHYULCRHUZQIPKKTPASEGEACTLTXVALKRIOW', props),
compute('m_4_3/12: ${c} WBCMHLWPULLDFSWAYDCBIEQYILFCHLSPLXMDMBJAZVODJVGQBSUITHSBKDANXZGERJNHMPUCSSLFDUGVXFZEEWCNSOJLJGRMCOKG', props),
compute('m_4_3/13: ${c} IDMQDYHHMZAOBASIJGHPAVCIWMNLJMOZCOUESHWXIWGLWXIRKMTMMSULTRRETRJOKEJCJYTOFQWDLTFJXPYGXOTLPDOUTNFDFYEN', props),
compute('m_4_3/14: ${c} FMNSLFBYVTEBQOWYWFITWIMTMZAKBNBHVHYBEORILUPRKXLMUNXBTQPXHVULBOMNQZBJSTPDTJBYIRYEDADSRNCGSUKMUNUDRODJ', props),
compute('m_4_3/15: ${c} YUWSQVWCRJJNIICAGPHIMENXPWIBUDIPVGYWEVQZLRQTKCYYWYBNFNHRFQFJWDJJEETIMCDKVCJDDAWHADUXGPGBFUHBTSZBBZYP', props)
        ].join('\n');
      }
    