
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_14/1: ${c} UQCZPWMTWZTXPDPASNQQMVHQCMSMQHCFQXIGWOYXYSKRJCUHUKLFVMQMGSXOEWGUJSSCJGBYUSHJANDPVESCYORXFVMOEEAFXWLO', props),
compute('m_4_14/2: ${c} YQUTEXEEOOUWABPTNOJCXVTPTJUIXKFZKPWBAMNNCPSVAOAHLKENDMNFGYKDNMZIXLZJWWQGYCXBRTCNCDLMGYNRWZRFQEASQBJJ', props),
compute('m_4_14/3: ${c} KKMJVHUKAEVEKCNLWQMNTJYFIZUOHFQDCSYYHOEDWKJYGNFUSBUKQTNYLPKDUFEQBAENNYECIGVFAKYFYARXXXXZTSHCTHEZBWQR', props),
compute('m_4_14/4: ${c} VEUUZTHJZOILWVZNFOYGCFMELPZZQKELYDNPRVYDDYTOQLYMMBJPVVYGNKNPNGDJAKSNRTSDNZHIZUSOQFTXDKGDVMPVTYKHTKFK', props),
compute('m_4_14/5: ${c} ODUSJPVIYYZVAMLWECTBXSEQMBLVABJMZQANGWBTMYCQPTZQYXEQVQGBAUQPOZTKGHSUXUIOYQPXXEOBKOTIXAAIHOPMRIHBHFCG', props),
compute('m_4_14/6: ${c} YGLPKYANKKXIYVADYHREMIIUKLZOXPAKVVLFMARQCYCACQUPTAMWRBZQXKTVKHWJGDMUVYNULKLPTQDXAIWPXSTPJWREAGYWDBLL', props),
compute('m_4_14/7: ${c} KQJWRABGZZLEOBBXPIBGDBDCHIQZFYRWPHAKJHMLZHHJPQHFUMFICQFNIONKPQJJUGXNMFFEIYAAPBVIJAJEYGPULWWWZLRVKUEF', props),
compute('m_4_14/8: ${c} UWYTGISJDBGVWMRBWGHDKFUCPJKTWOFGVCXFVSBGHOWVROQFVHAJZRWTBQHZJELBTVRHFHABDVPENEJSNDNWOLYVIMETRBDTPGHB', props),
compute('m_4_14/9: ${c} HLAIFUAOJEKPODRQKGRBXQYTKZDNIJTICLFXSGOVVRVLUANIXRTBGWCUTBAXNAVDLRGXTEQSBJGDSQKQUELVOFJWUJTGQDBLKAQF', props),
compute('m_4_14/10: ${c} QWEFQLLQOEOHLHJYIRUHNRSMHFDSCWVXDTLGMCHPPDZOKVPOECCSMLRIJKGLGLAXTFCNPIRJCUJFHAHPAOHNRPOXYHCHQWGWUPSE', props),
compute('m_4_14/11: ${c} FIFJWUSMAXKSPHHOCPYJMCPSNFVYHVLWUTTNFJPMVHIDSRSILFIQJONAHKTUFFUXTEBSEXSEBPJCFKGNXRDALVSWXJKZJGCDPJDG', props),
compute('m_4_14/12: ${c} HFAZNVKJKWCTMPMWPHMHLYSYBRWGGEKFFSDTZRHVFMMGUMQQQRVNJCOJDNYQDVPKWZEUDFKHEXYFWHNXPBIADAWQOYTHVUYPSAWH', props),
compute('m_4_14/13: ${c} VBEVJUQRSHVRLSCTCFTNKSXGDOWIIWICXODWMSNYQYDMGFZVLLXPJHMACQLMZCFAXNCCVVSOLRDGGPJMPAZTBKWECBVPUMIWKIME', props),
compute('m_4_14/14: ${c} OMHAIDRYCIAATLMHBDKWIRCTURUVZQCQYTWWLYLSGIUIFXJISMJRODIMFPYYKBYQCRTMCEHZQCWJXDYVUQWYOJMSWEXFMHQRJMGO', props),
compute('m_4_14/15: ${c} IJAKVPRXBZLGYIFNNTOZYTXMKPZACCXXDEAOWTMBLUKREKXUSRETCRCWKMZZDFNJOXRQMRZSVGTRRSQWMJMNWMOVXKGQXSEGNXZS', props)
        ].join('\n');
      }
    