
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_20/1: ${c} FBJUULLDUFOTHJJFAZFHGBZXUQOFLJYINOKVYLBVHMXIDDCFJNMMPBYQGKMORYZZLEGVZLJTEORGABVVLEUFDOSZMEYZAXBEXEYQ', props),
compute('m_4_20/2: ${c} HSZGERMOFGNHOAGGQFWKXQABINYFVJNFALGBRUYRNKGWZAEFMXAEWEGZRTLFOQGJSPJTKNGXQDMEBJBAJCQMJLQSHFZSZPYSFOBP', props),
compute('m_4_20/3: ${c} CPEEZUWJNVCWSYEARELJTVQTFEFSPOAJMFKBZZFFEBOCHWBSEABEVFMMQUSKXNUVLJHISEWYIVWIRPNDHEJLWUJYPSVUUQXTLIEX', props),
compute('m_4_20/4: ${c} FQSDQJCBGYBBJWGNXJFQRJAYPXKOZTVUDWXNKLTAFXGDUBZPWDBCKFKEEUMHKQNLWPGRGXIEPZODTYPZYMORKGORGJXGARWZBGDV', props),
compute('m_4_20/5: ${c} MWGMRACSMLIDIYVIZXOJOMSZJGAFEZUWGYKJPWZRNIOKPYRQOGPJRGNBEZWIMGPHGFGWIQTSQVTEETCOMCYYNEKOFIKDASFEAQEG', props),
compute('m_4_20/6: ${c} YPONHOAPDFKJARJKYRJECSGCHTWURDBTLTLUXUCNEVPSBLWMILUSMUSQCMUIBJUXBBPSEPZWVRAOTQXOFYTPKYLITWIYQRHLANBP', props),
compute('m_4_20/7: ${c} VNWLSMSXERKWZRNGROCFZWJDHTWHIUASHIIAOSQPEKPPIISUAWWDOWJXHBIKMWGPATGWMICRCYDJXCCNRCAFGQGVZAIDQKEWTVFE', props),
compute('m_4_20/8: ${c} BUBHNZTKVGIDFLMSXQMFKZOOSSFZLVDRJJHJRBNQMWTROQBKAQLZLSSMZHCRYWIWDMVPGAGLNYWNHDKPCXGCNAXFMYDXUOLQAUXN', props),
compute('m_4_20/9: ${c} PVLTAOAQYVOGTUSHIRFOXHWPIMLUDRGLBHVBEVDRBNHNNKRMYFDVMCUVOOMRZWOMJDRHCSQRFYFQLBLVXMNAFWMZBFJZWMPDULUV', props),
compute('m_4_20/10: ${c} OUZIDLKZILJUIAURIVWUIWCFTVGYHDPLEOYLXZFFRCOUHHWUALWWNJGHROVHVVIXWAGNDTEAJNXVRNRJEEIGCTDPFNBZLDZJRVRA', props),
compute('m_4_20/11: ${c} IAKLGMYRKNNPNSUHHMYNCXMQEHDWXLSCZMYUQIWCBWGXJDCWUJJYXNXTKFVZZBYCQSKJGZMZDKCBLDGZNWDCBYHQTNTZEDGEIAWG', props),
compute('m_4_20/12: ${c} TPLIAXFPYSCWAPMFTBTRVXNKGCCQKVTJDQBVQUROHZRENMWCZFLZFXSWZVXMVPRVEYCRBAXEQONPYQHIIGGMKZOKLYZUYOMDMHXL', props),
compute('m_4_20/13: ${c} KEITHSEGNSYRIJTORVOMESADUCQDTZEJJVJAURBEVVYOIXWUPJXPTDCHVWOBALRPENLMIMBNCGRLIQYJLSCTBZOBQBNXLOBSNDVX', props),
compute('m_4_20/14: ${c} EOQIPGXEJUQHLMEOIDIUDNDSECXFRMSLCHTWJPSVMUCTJBACMQHQFGZXZUJFBMTDFPURHNZZMWARTHEEWJRPRVUFAJKTAHHPYJYI', props),
compute('m_4_20/15: ${c} WKBPHCWDEAWYURVVIMVWDWOWTFJZVYPHRHRSLWCJLMUUIMSERUIYKHUNDCKACAJLPWKGMLFSRFXTUCROZFAEZCGVCKNTOCVKEMGQ', props)
        ].join('\n');
      }
    