
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_12/1: ${c} RVVSXTRIFYXHUVUPDNDZGRCOLBMGFBASWCRSQCAIEPSYMOZRLTPXKIHRKOBTCBZHJHVMERMDRULKDJYWRVIIMOJNMPTWVWGXKMTZ', props),
compute('m_4_12/2: ${c} BDERLWJYVYHWSETYXKTLSCILKAPEYWCNWSTEFUXREQVFNGELREJLXNALCPFTVBXOTFTXIYPMJBLOPEMABZALOMDRJYCEBGQHLLEJ', props),
compute('m_4_12/3: ${c} KGZLVPSBBJDNCZFIBZCSDTMUEERDAJLXLNTKKFJTHZAPGPHZEIAPDBTWOEUHNAXRMDMLQXEDNZHMDFMIDRFWBJCYBXVYIAKQSDLO', props),
compute('m_4_12/4: ${c} IDMNJBDCLLCOIKJPKWYBLMXOZTKDJNPJMQMDIRNCRIYHNTZRQDYLHPZFDAMBNXZSGFCVYVTNDFKYKXPKZYOWLTUNHBNESEZTVXBH', props),
compute('m_4_12/5: ${c} XQTYOILOQBLOOMSPPPTRVCCRAHTFCOTXHYZZAVADPAZGVMYCKOSJRLVDZPFCCDESQSUSHWZHEFHXXVBPAQWOYGASPNHZHUKSRGDS', props),
compute('m_4_12/6: ${c} PHHIRNOTJTGXUAYUIIHVXLZWLANWOCUPSCWIIIGTSMQMBASHCCJGHFUJDQUNVRJFUVCWDOORNHVCHDUHSFISYOLOHKHVZIECAGMQ', props),
compute('m_4_12/7: ${c} ZEMRAAXSZGXRAHQHREGNHUCGETWYEYSVTRJUKJUQUBOFTYOUOGQADPCPDZMSSZAHCNQUHEYTKUIJOMQLPKZAUMPMPIBFXSEAUCZK', props),
compute('m_4_12/8: ${c} QCWIJRCGSWKACXIXVNMGVFQFDGNYCCTTAAZQTTLOCKICTZOUTWBLNTCQXCMMXCEMVTFKAIVJNZANUWGPKNFAVHDYBWSZENBNEOCB', props),
compute('m_4_12/9: ${c} IKUNPOIBOMOLOUOGOUQCYCSFRCWQAVZRRMQVRYHTKUWAURFLWOIAAWPBAHBTVGZVLCIFBXUKFANFWBOMMZQXEJJHUJTIHGTRJBBS', props),
compute('m_4_12/10: ${c} YTWEBQLWQIYKQUOZJDDWZBVGQPPEPLPLBUWGDKUHEIWYGIYZBFCRKEBNYYEOUZODWMJKNHEXWWSTALACFCVGRLOPDPFQLUKJGGJB', props),
compute('m_4_12/11: ${c} NLNPNGJWDUDEVZXMLLOUOHXAMDXNGTUHCBWCHCZEUGXMUQODOEWGJEPMWCPWLIMNBPGFLHSKMQLPIEKBOIQNOHUFUMCWYRGNSBQC', props),
compute('m_4_12/12: ${c} MDRVKGOMWXCJCVARKXKUQWHZYUDWSRQQBMZPQWBFTATNSWMOKFOOFMRCPXLTADNNXSIVQQOWKWVIPKGEYXYVLMIDARIWFBBLCAEU', props),
compute('m_4_12/13: ${c} UKZOIOGGRSQWCBVUPYPJXFXZQTGCUHXNNXWYVOGOOVJAOEWRAIJZJSLFHWUZOOVOYXYWHLWIRQJKKUOJKZTLMMTXMLJHHPIVBKQQ', props),
compute('m_4_12/14: ${c} QDUBLGMWFUOEPWZHDRIRLFRUQZRPHVAUWDNROFIAZGYRBLLPPMCWONWEFSIHBGTFJCQWQGFTHVHYZWUZLPHSDXZGEWAFNYDNZMTB', props),
compute('m_4_12/15: ${c} HCGMYKALFPFPNVRTQTQZSYPGKCWNIZTNIIHXKCRNXEABHRDVEGDCDCBDFDCQWILHWFPDLGNPLEDRQTPILHGDIHOAGAKDOFAXUDRC', props)
        ].join('\n');
      }
    