
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_10/1: ${c} FTELNZBZOSTTNRZYMDHOUYQTMJNZMGGZGISLAJOHJQBUGLNCOBUJBIPKYIULOYFUDHXDTSXQIVKLSVSLTFCNYCQZZQOQRBSYECAG', props),
compute('m_4_10/2: ${c} NUPEZJYNHNIWFKLIVKSSIFIHYJFLLYMXWGSCLHFGOUYKUTPZUDIHIVJPRZUTQDQUGUBYIIQPNXQDEFYEJNARHELGIMWDFKPRMBLJ', props),
compute('m_4_10/3: ${c} FNSOYBJMPVRSTJHXCIOPXGKGOPOUWRXRJSJLTGDPKDWJZVYHLXWJAFLKNNWRCFNHGODHRWIZSTGZKLTWOBVKRWHPPPNQTSCHUGAT', props),
compute('m_4_10/4: ${c} RFAWFYZPHTQNZMBPOXFXVYXBDARSCQTLBHJLBQEPFNJOAYERORZSJDIAXIIAIVSCXBGGWCCYTAFWZIZZBYAEWNLTVEOBUECYCMCJ', props),
compute('m_4_10/5: ${c} RZTEUOOINRVDEVEVPOOVLPNKCXAHHJFCTHAAFLGSJFLOFQOZMSOMISDGOJMRYDKIHWCDGYQDECWFPCOIRLJEQJXWGVHKTVZXILNG', props),
compute('m_4_10/6: ${c} NGVCAVQTZDSTHVQSYGYPLQZRBUZREISGWEWGXYTPNUSUOYFJUEPBVJGTKYMUGYUYUZCIOVSOBDPJMADCSLDZUXISOQQWBKREJHPE', props),
compute('m_4_10/7: ${c} VJFZNLMGFGBCMZLLUDFRHJPOFZVPVLYLOVVTPKTOZQPLYKKRSGZGQSLSYZNQQTCOKLRRSKNFPOOIDINHTQWTQMDTWMEMKTRSAPWA', props),
compute('m_4_10/8: ${c} FAGYMZXONCRHZSCREOPHIILOPQBLWCUUYLCTXTVBXOMUELZSDALOYTMEFBCMYRTQFNNGLMAOJCKCJQAPVNFOVNFJDUROMDPMAKJA', props),
compute('m_4_10/9: ${c} EEBCCWWSZRVLUDAVGYHAHDFRNWZOJYFFMIGBHCCBWUTUAJZIEUTYUNWDPPGCIGTTEYVTKPQTAQAJQOJMCCCFSHXXSUWBWOOQWYYR', props),
compute('m_4_10/10: ${c} VQQGONEDQNZBYOHJIZNEVGQQXFCPXJSTVLRNFMKFANKYAUPSGBRZTEBGWIBGGNYPUYWKBJAQZZCZTVXYXYCPZHHGKPEXXDSINCBZ', props),
compute('m_4_10/11: ${c} OHLRBMWYHZIHXWANIHTZYEOSUQPLXFNGSLRXIGXWPEKSUTAYKPAAKYYRPSCQWZLQKACWEWLDPKEHNMSLDIZFGZZEONNROYFUDGNQ', props),
compute('m_4_10/12: ${c} WUPLCLRBQAVPGCYSAUGJFLUIKIELAUMUTOHJZNAPYCESHEKPDZZOMTNEXXAVOJPDQTNRUIMMJAIHHIYXJQXRGWCMTAINHTDSPWAV', props),
compute('m_4_10/13: ${c} CDFXIWREWWFRDDQDQXMHEOXFPQCLJSAACADFYHNSPYFLWWPYDMKEPWZJYFUVLCSXTYYKILIWBETEOSMVUDRTYWDMEWTIHWPKQVZK', props),
compute('m_4_10/14: ${c} RMELTIWLKWRCHPTYTEBQJXIABUQKONHFUWETTKHMIRLYKWRSEKYAJXPDTWDIGSUTPBYXANDYNZOPUSADLATZXXWMMBEWXVWBYWCL', props),
compute('m_4_10/15: ${c} YAQBGKCZRQQOUQHBGLUZELLLNKCVADTXHYTLVXKPIIETIXRUBNRZIXCUPMPGUWJZVLYXKMGZSBDCLBSASUOKDCENONBKEKYKRUYY', props)
        ].join('\n');
      }
    