
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_18/1: ${c} SNRIZPCGXLFCIRIIDOJCWAGNSIOVEMWEYRASIQITLTWNLAUWHLESNNQWQLUOPDJEWBCUBEPNRMPDIVMBCVOIEJUPMCMDLVDHOOVX', props),
compute('m_4_18/2: ${c} MJPFFSHUOQSOXUHHZWJUNMBVBHXRARXHFRONBLKQPDYDOSFVIHHDPQNGVGCRUCVGHJDEWQSYGKHDFMPVUUYQLIELKKIUEQAOBONR', props),
compute('m_4_18/3: ${c} DDZAZKVGLLIZAOCHSOLLDXPJXZYUZMNCIEIKFJBSFXFOFINEEDLSDHSESQUDHPNEGLUJCHIAGNCTEEGKDLODDKMMUWXWNEGBMORS', props),
compute('m_4_18/4: ${c} BWWECEHPBJEMBJIHQCDYMZCUGIYHDGHRMOCAKRWQMFGIZMMBUABAECOBXTTDACEJDMLLKVRRBDYLSYAZCFNZZEFTRDSPIMPOEXAP', props),
compute('m_4_18/5: ${c} IMMJMUKDGQGNHJWFMPTNAVOLWWKWYPYKECPZELHJEEYVTZAYECPTRSQUOHCXBTDMTWVNBHRVSBQLMAGPQNTGZLRDSUJDSZWXAEYX', props),
compute('m_4_18/6: ${c} TOENPVFPHYNAODDPDQRETEQXGCIMUSFLHBRFDJQHJXVUAOWSHQGOEZFVPPMVHWEUEZSPTYJZCNRBGONOCNPMWFRXJDQMPBTAJLSL', props),
compute('m_4_18/7: ${c} BYCJMLIXSZYVHYNTYBYPVFRWPWMNAAGQFXSKQOZTTLKOECAKGOIZOHVXIGCFXGKHYFFEHYBZHLRWQJBWTMZNVFJHMBFJOMMMYFUJ', props),
compute('m_4_18/8: ${c} MUYNMNTAFNBHEVKAJWCWWDQIMVAXSXWAYBBBDOTMRMUITTIEUQAUAFSQMOSWAYAIPIVJODDCROCCJCMEEYCVUWYWCYXPTOMGEEUR', props),
compute('m_4_18/9: ${c} GXVFCAXIQWSIFPPSBOITVBGFEXKLQDDHMRLXZWDXNBCIISELSZHLQCXCMMGGCIGXCYCKDGZCOEGRFCUNSKGHYGXUXIDHPZALEJGE', props),
compute('m_4_18/10: ${c} JHYORZCEZQZZSHOXXCQUDWZIPJTHGOQDVSZIVTMZNYWJDMGOXPFETNTQYCDNTPOFMTHSXUYZGZXTLCTKTHAUJJJJMDXHKUKWEYUC', props),
compute('m_4_18/11: ${c} PCBIERFISRCPUDNZDRHRBGZIKYXYFUQHFSMTWMLIRSPYWNWSCCIGYJGGLTTQWSPXYVRXJKEBPNJFHZOOHEAZERCFDIGECOEJYSUB', props),
compute('m_4_18/12: ${c} WUYKQMHYQHEYILDSJPTPGWSGHIKECFDJOIOJYFEKXJTYRNBZNLUCCQDMWUMVGFVSTDQPASSBGSJSFYHULQIWRYBOTOSHVLSIVAJI', props),
compute('m_4_18/13: ${c} OMOMOMARUMKHKVFMEWPWWOLWWRYNOPTFNOZCMWYOMPTNDFJTKZCRWKLHMXGHOKFCXJMQTNGFVKKCRZNBNYFTTBHUWABEZGXWYCZV', props),
compute('m_4_18/14: ${c} XMQBXIRNQASKQRKSTQXJAQZLZSKXEBFTWSUUEYEVJNZUIVBXIPQWJHWBBJPEILBIFGGYYHIEFARYKPNVBAGXHVDGRZPRNEAELAUB', props),
compute('m_4_18/15: ${c} SSQPLXQIYKPDCNPUMXWKWEROIBRNMDPXGSFMIJDZOQOPWSZXVBMRKFRNQMSRPEHDQJPPZOIRPWNKJBUUUUJIFOHKYPQXDOOPTPXN', props)
        ].join('\n');
      }
    