
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_1/1: ${c} WYRWZGNGMFXQLIJXBSAYTQSNTZAHZSGOCLRDXDXVCTXEGEFBFNGOPLLDYUDULWSIWGIRUAHRTGADIJTEKGNWIBASPLZSKMSFMFTN', props),
compute('m_4_1/2: ${c} GOVRXMQSKKOXENOJPZYIJQYLSYCHRANXURCAZNRECTPISYZWBPRCXCIIUNKSBLJZHUCFSNOKRTBEGHFJSIALFWCLVRIYRUWIBUPN', props),
compute('m_4_1/3: ${c} KFIQBYALBZLYYNLUKIRAGYBINYXRUIOUOTUMTWGFOLXHJYTLUNOJPWXWGSGMAJNMCBLAMMFFCMBGPIPLSXLHBYFRPXPJJRJLRRFF', props),
compute('m_4_1/4: ${c} HZRGAGTEFUDSJVELSXGOVBOPBXXIWKKHLKAQUORFSLJHXLMCMKVDGMABQRQWPFBPQGLHNCIXLQQDDECJNUSBWLNFSLLBURTJOXBG', props),
compute('m_4_1/5: ${c} NZVVLHSWMORCQMJBSLYPUVSDHLPKUFYBWBYMDHJUEKDVIZPGTQXCDFDICAXIPYBKUIYJDWQOQXGRZTSHPBNMMHHSKUOANKJOZDBZ', props),
compute('m_4_1/6: ${c} WWUTLYEZJVSYZNSXOGLNIDSVYWOEOGZAVBZVSUOPNKZAYEPRMKCNQGRRZHMDVNMDCYSMMYOUVLOBYZKZDJTKLKUIMHIYTZSALBAG', props),
compute('m_4_1/7: ${c} GSOYZNGYEIPMDDNDUHUILKLZRIKQKTUQFNMUCMCGUYQQLOQZIZSJFWWNBULEIANCRAEOVYJPNYQOJUYTMHQWAADKENSSCNRYYOUO', props),
compute('m_4_1/8: ${c} ASQOJEPYHNVTYLWYZPBLFAWIWYIYODCGZJFKGGXPXVNGBXFFFREEPKWXRDSZPSNJPIZMBTEHWMUIPDAODXEZIVFIVVHZFYMYCZLB', props),
compute('m_4_1/9: ${c} CVUROYKZNQICAKQQCWOPPKXFCJMSTGUFDYXPUSPOHSGHVKYEIACZKEJXHQYAZNDYSGBGGINGYTCNADBJMCJIUMVBQPUPFVFXUCMT', props),
compute('m_4_1/10: ${c} KKTRQDAYXFLSFWBDIBMXUGCWYGKSYVIFHXWUJIXHJPDRXEBUJJYKUNEADNLTPKZDXJHRPAKCHYGYERWTEEIDKHLJYKUUBNUQRYRB', props),
compute('m_4_1/11: ${c} LVQSGSWQCQBDLGBHZVPTAWCJVAWMPUWCQNXBCEIZFMIJCXOCNMQTZUTFCFXRYCKCTCNFMYAWITIQKIYDWAZADAZGGLXVFLOULUQF', props),
compute('m_4_1/12: ${c} IDCBSTOFDUKAPMRQNQYDOOXDPECJMLLJLQYUWVBTCUWPAHTXTCVZQQTGIGDVZNLNTCLYTYUZWILQUFNPPQODXMGROMYXXQSFGQZX', props),
compute('m_4_1/13: ${c} YSRBOQBZIFUVXLHCRSLCPPETPZBBARVBXTZLAAOWEFUYIGGFYCTUKKBHTEAACUJKVIBWTUJYOFGHQWFKHQAISTNXHYNFJICPQZLR', props),
compute('m_4_1/14: ${c} BSNUTOPPNHJDISTXKYAYCDVCJRUZCYYVZOSTFQXZMFEEOFXOREMSZODBBDDIUMFETVVEINXPMBBWVDCZCEXGVXADPFVAIBWTPKOP', props),
compute('m_4_1/15: ${c} LTQKXFXKZUSEEJYXVHMBZUYUMTJUHWLJNGEXDTTDUIDJTDJCUYZJPKVUYCERRZWPUBWFQBTLHYPXBXMFKDQCFGHPKYZXEABKHJWM', props)
        ].join('\n');
      }
    