
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_2/1: ${c} LPEXQLQVBIIJXYUGKWTHFDBGFWKELNWXCGYTWMYTHHTISABZZXXZRKNKZEEVWFGWOSDFDZKDDEXKEIXOSXNYHPOFKVDCDBEZFODO', props),
compute('m_4_2/2: ${c} NMITYYEHJQQBPPWPCSRDQBKRRZPJOGAJUREBHRLJYHQBFHKAALWDTVIGEFGWQGRFMAMZXIGPQCFIYTVLJPLOHNNRZWSTLCRTXOFQ', props),
compute('m_4_2/3: ${c} KUCKVGVDQMWGXNGVYESZYAOPKWTRAFJSQTWZDCRKDGDTIALTHZYBMVSAGHARWZWOVETLJDZDTWVAQFOGLMGGPMYOMWRCPBLZAOQV', props),
compute('m_4_2/4: ${c} VZRTUHKMZIIUATSSOBVFELDUDTDBPZYHVEWZGFPHFJPJDTNGYNRKBOJZZNQWFHGEYEPPQPEPIMUPSGDWZAIKLABQLSVYETCJNSIW', props),
compute('m_4_2/5: ${c} RIYXJEOAZRAGTHOXJUMXRAEMFDUTUQZBFNMRSLMCQMZKBGUXPFOHBYLWCMMMTKOKIJPGYITMBXDTKIZVSYHHUNHSKVCIIRKZKPDO', props),
compute('m_4_2/6: ${c} HASQWUDFRBDLGSBLMHGUCRDTBQTVGTRJUXYLYEWDGJILDKNPQDOMROFAOELZJPOCKLUZGHTUCXVFZQRXCSPATSNTPUTPUTAQEIIS', props),
compute('m_4_2/7: ${c} LVDLOBVCKDJURUXRILNMSOOYXTEUJQAVSAXJXLZEYCZULGOMWPZWAOQQKJXCKWZYSXBMWGQXRARPMLARRQKTGLGPHUHOTPBOLSCK', props),
compute('m_4_2/8: ${c} XGDLFDXTAKIFVFBRJSOETVQUMCFEWMSLTEVSOTPDXLFFQOFTPUENOEBKAVTLFYTHTNCZSIXBLXPUEKXORWERTNELHSAXCOAEQKOT', props),
compute('m_4_2/9: ${c} WSBMROKRQWKNAYWTVKCIUCKZDNPQUAQCCCYZEULSQZHNFGIIBPWVBQSWFRLRWFTJPEEPJTSBOXNTWKJFYOBFGWCKYOJZDHAAWWDN', props),
compute('m_4_2/10: ${c} FCBTVQLCVJEATIUUOFEDVCXQJVHIXLTUFBFVNHEXPZEZVHWTOGWFGJKAVDJALGUTPVFNAGUILGGKLASKHPHDXDYMYUHOBWWSDPOL', props),
compute('m_4_2/11: ${c} ZAFRMPPSTWRTXLRJEFJRVSLVWTMTSPGTUAMIHECPRJSBMXOXVYVTQCBFTNKLEVKTSOFSQFLGBZCRBRLHEAKHQLNLHSZSIICZCZJI', props),
compute('m_4_2/12: ${c} UBOSQOKQHMCEAIUOAASGHRIRTMTEPNMGYIPCQWKLTWVBDLPQXXSYPTITFSAJSVAMGFZHFZGPVTITFASEQFHRBTTAYCALDEVFVUKS', props),
compute('m_4_2/13: ${c} SPQPFUOBRQZRNDFNCSPIRAUMQUXTPBTWSRIFQTKNMGFZTEGTSCDWNEYBNAIKQMFKBALRCTNUKWEUICZTXCOHOFRRKNOPVJFFQGZY', props),
compute('m_4_2/14: ${c} MUFOBMAFIQQXMJEIFRTOVOGDLXOQAWVSYAFSTUWVYNQCKFOXFTYMHPUSHLXKWWRIFLHFHUEUVUPNYOQCURRHPCDUTZPNHTALIKVU', props),
compute('m_4_2/15: ${c} DRDOMIOONIGYLRGPGIFBMJYNIGNNLWUHNEIALCZOXLHQLNDOJZCXIKTMRBMFRSGKOFDZJQNNYELLUBVIXNTVFDLAKFQSNTHYFGBP', props)
        ].join('\n');
      }
    