
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_15/1: ${c} TTYZHBLUWXYMJNKVJIMLZDIBHZOLBWBVOYSKIHZCWNMHSVDCZESJAPUXQBWGTOUVRJJVHSDNRUARWNFFEBTAVEFBPEAWKNUYHUNJ', props),
compute('m_4_15/2: ${c} FGEQEPEVWUWLBKRYKSLBMMAYABENKQEMTBIBPTPSFBFUBMPQQNIIDJIHQTNHDVKGMFWTBRDHTVRUYXJZNOQNVYLRZLJOPPPOFJKI', props),
compute('m_4_15/3: ${c} NIXKNKHFTPZDGJSYMIVXSQAOBNQEASVWUEPGNDSOKNIPQKSKCKMARVCIDHGZKJZPBBTTVSUJUPNPRGJPWOLPTOOPMSPWGJWRVCKH', props),
compute('m_4_15/4: ${c} UTWESVZIWJZSXUSEWNAAZFNEUKQUXCHHGSFAVJFLVZSPQEMVMZKKHHPAVYHSUBKPNCNQLQAJSVQLBXMCVOBQVYLNWLUUZVUCDORM', props),
compute('m_4_15/5: ${c} UBGVNAZHSVCTENYDXVCCKXLJYYYWFFEVYGFCXVAUYBUDGIDYJCZMLKUYOQFNPHVBBDKBXUHZUSUFCBBXUEVKBTYTJBXTHMFXOUZZ', props),
compute('m_4_15/6: ${c} BREYSJZADWDCGWLSTWUHNOWTSXOOVICMYRWTNBYXPOSMRZKTNPLXSNKOERKMISVZBWTELELAOUJCZCBCZVOOPHWJBMBLYWETBRVK', props),
compute('m_4_15/7: ${c} MUZSADBWLTGOHDZRSZQGUTHHVWYFQKTHWEHXZWTEOUAIACXQYWPHORKUIXEPKSHOKUYYJVVIOANROLYXZVACTHOBHMYACGAOSFSZ', props),
compute('m_4_15/8: ${c} VRSPCBCXQBOXRZIKZARWZFZICCDNDDYFZIHVMUIAUZHSSPTUPOIJHAIANESNTLEOWALKNEYYWCCHHFYYSDPAFZPLLJAGXDSGVDIK', props),
compute('m_4_15/9: ${c} DDJWFGBKUOAJCIQVQDGODEYNUXTPJEPWBSPFMTQGFVLTDXESGZVHUBVSAWRJYZLZUXQWMCWJIXOAWVXKRNMWKWJXABKBYPBMRKSS', props),
compute('m_4_15/10: ${c} TYNHVGPSSKTRLGKXAMZTWXYITMKMPOFVZFXSOBZODQLVZOFJMRPNTVIFFNFQDPOMRHHCAYAJEJFIVYVTXWKBGQPRJIJAUMMKBLRH', props),
compute('m_4_15/11: ${c} NXDSZDPYOCMVXGOVEKHTZNFOFTJHEYCXNWJYOWGODLGJWAUXEVUEQPLVDRFFXVSTXCXJPNUJGRSIATPPFSXJNNTRAQFQKIVDPSTK', props),
compute('m_4_15/12: ${c} NOIFPEZZZYULHSYDZZKSOUYWQEDZIIMITZGATEWETFQFELHHWPUYPJNJUDWQWJOYHWATKXXWWFCGJXKNEIHPWUORDAEQZGMBINCV', props),
compute('m_4_15/13: ${c} OYSZVAVKMRMKARFJLVQKUVHAOMFVLSOLTNFMWUILPNEVLTUHTUDZJIUZHMSZNQYUQFRQZYDVYKRTKXNMXPZUKVKBZTURDJMPIKUY', props),
compute('m_4_15/14: ${c} BGYZKANYVKHFQPBSYYHXQKEGZZLWDRQBNMLAOOAODSNGBTXYDBIFHACDHBKICEPREWDTQEHZAQPKUIRKLKKCGSUHMNMSDRDYHZCS', props),
compute('m_4_15/15: ${c} JNZPQCNKGOCWXENPQCTZJBJRRGWFXKVVEDSPZCZKAKGHEFWKADSBOGUEJOFICDHWSBKVLYWLHSXDHKHFAWGEWZPKVSZPNRMBICWM', props)
        ].join('\n');
      }
    