
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_5/1: ${c} IDANQSOUYXHVQNKJNBJWVRKOIZIOYRDWNPVTMKOPAIOXMKPHUHGVVQBBLQMWLBGNTLMSFCMHIPSDQVHSNBIHRDUJHOPVPPGLHALS', props),
compute('m_4_5/2: ${c} NSNFBSIIRFMPBLCZVDEBNWCEGTIPPFZNYDNRIRBGUPSYZBHGVHERUSVROXJYTBKJACOSEGUSQEWNISOERCXUNPIWNEMOVRADCZQO', props),
compute('m_4_5/3: ${c} GIYXZIFUYDZCAIMFFGWEKOMKBFASPAUPKZKRVUYTAXAYUFLSFKFGZASFCODOBHGNOAEBUSSPSDSDIKHFYACLHQUKUPGZLFGVAZNX', props),
compute('m_4_5/4: ${c} WJBITZAWGKLGJXXWVJYYKUQDBTBWGLZEITGIEAWFFAXQLPJGBFQUKPFDRZAVJSULHMXMHVQMGDXYNLYOBXWJZYJECLPKDZTPFIMD', props),
compute('m_4_5/5: ${c} PCQMIUNBKLCRRHWNHDRVRXJAHNATIZHPTDEXSUTHWNFOUVAZOBTOQQJEYVMTSHFYHYBGYJTXJNTXJSNBCLMCDUTHWZOAOBTVANOJ', props),
compute('m_4_5/6: ${c} GWGIJXZBXLGGYHQHFDGBDWLJKXLCCTWRQCKQFLBNUNYKWLDMXUIGMMJRTPQDRVCJUSTNJZIBOOOQIDQSJLAGYUDPTGJYPFKNIHLY', props),
compute('m_4_5/7: ${c} WGQQUBWSBZZFDAJNUARQUKWLHVGPFOSGQJTDSPWSZQSUBIXKJOLSRFOOHBTPAJWWCAIMOSIGCACTBIPNFMTMUHVNSSDRUJKMTUNB', props),
compute('m_4_5/8: ${c} QUFEVIAPONMXJTEIFLEVXZJCQMTSIXGUDCGOAFNAWBFUNAZYNHVLQRRAGZRJVZQZYGNIQWSGUWEGNOHCNOFIGCLCEGAVACVWSFVH', props),
compute('m_4_5/9: ${c} STQNARPKIPCIJOQLVTUQOCYVUOEOFHOPUWYYCRQPIABBYWUMFNVMICJAARBQQBZUCTYDQHSQWMJBULKZXXHVZZCOIDPMIHUCYKCG', props),
compute('m_4_5/10: ${c} FSYVPRFBGWSMOVJXXYVKUMMCKTKUJGANLDCDKVBOKXCHSKQZNRBEMXEJEGHKCSAVPCBLMFOQRQNYBZZUDJNWHCEWIDYTIPMFURZP', props),
compute('m_4_5/11: ${c} CJQLYFNENZVRJANRUOCJWSJMIFVCETRLVPBVBXYADZGPCLRTTKNHOTSNBGKPGRLRLEBKFLPNOOLCYRCSQELDAWBMPTOSAPKAZTHW', props),
compute('m_4_5/12: ${c} RIAJSYMDCMGSNMZNHLKKEPXSCLRDDEYCGUVGUJBMUKVWWYZIIQCMNBPWQKHMLXVFOTIRQIARUMAMQQZEMWEYXNZFRERHUBOREUJH', props),
compute('m_4_5/13: ${c} MNHMPMCARLTPDWRWYOASBQQLTLRICPLSTVYUEVAAMHGVXPUDUMXWTGYMGNROMAEDIWHGQKNARXNASJJQLAKQUZSXHRJAJIBRDYAG', props),
compute('m_4_5/14: ${c} XPJVNXBCJDRXTQTPGQDVVMKPLQMERLOQNZVFXOQZEJHZUAEHXOFZVNMVPFHYCSSZEUBHQNTIHCRLJQAZCRIBXMJEDAWGRGQLAXJW', props),
compute('m_4_5/15: ${c} AFGFQIEPRMDOXRKUWUKGZKVUFLRWBYTEUZAPXXZBOUVECSFDKVETTBBOEGEKTRQAASQXCAIUNVPHGHTBAXLSCCWGVETANTNDUDRC', props)
        ].join('\n');
      }
    