
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_17/1: ${c} YLQEQNVZCHMUPVJLGDDFCIGTOFTYWLMDQEZPSZUCCIFDVDAEHSFKFUEYMVQWENRLUKGUZDJWURQXBLYLFIRYVSUFBMICLDIETYUD', props),
compute('m_4_17/2: ${c} KDPPNMRDGNHBGWWWDHRSAOKBTAARHDAIYHWCNYJMNVLARCQFJAMPCNWUWLDMTEBKYYLWMUBSCYFQPLZHPBLXXHCRRWGLGJUEMYRX', props),
compute('m_4_17/3: ${c} HUURZNCYYFKUGXPSZHNYQRTSEZVOICNZGNHJNTDHZCSVBEJSMXFEQRCYQMEYVLOFPQDUFVEOAXNAINYRRKYKVRFTFJXOVGSQLNEZ', props),
compute('m_4_17/4: ${c} SBZDQWVLTFDSTYKAEXUIWEWBZKMZTCFCUDUFVCUSOCNQAZLTQUIIAGJASYTATDDYMMRUJIIKTLNTUWLQIRCSTCBAWKUXHAQFNCWZ', props),
compute('m_4_17/5: ${c} SYILSTYUHYPYUSCVMIFRWBJOYGZOMYHVCTXGEDFHAFFVJVOWXOARSNDENQQGXZZQEQJDRRAXGGOMXBSPAOMKNRHSKGGILBZQOUKI', props),
compute('m_4_17/6: ${c} EECLABGYCZXCIFFJGOAVASHGPUWWVBIGGPLMZPPQYEFHUURFLVVXNQHHFISDDYCKKIUJUFFSGVCKQHTLSFEWQURPSTSAFJDMHFQC', props),
compute('m_4_17/7: ${c} YXAFVRDFVGDXVELEYEZCGFRHSNEJMUOUTKQVNFAJBSCPICOKNIJOPLVBDNMAZMUYGAGFBYQZEISBFOBWOCGJBALVVMCONQHHRBBO', props),
compute('m_4_17/8: ${c} NEMPPVTBSKYTKPYHQGVGPUHECXLDAMTPKGISNZJWLOVDQTMXWDMHJEGTSVLHIZNAEHNICNGLTOMOVXJLLNPZBLUNRCOEKNOXCWPG', props),
compute('m_4_17/9: ${c} LASMQTVLRFARDEKGFHVABDDCVUOYIASIADQUHXBBAUHAWBDFABCJNXSELITDIMOTJBSUOWAVDZBENVGEMDZKYSQWYKDCOWARDZGS', props),
compute('m_4_17/10: ${c} KUUTQHPHROEWUWNJRNUGPOEPSQZWKGKBAELKLVRPUCHZJEJKYOWAJZBCYQQREWPDXFDJUCVLZYZODDYVHNIVKNZOLCSBPPQJDTAT', props),
compute('m_4_17/11: ${c} WCDDTNDYAQYOBZQZAWTYHRSWCDRFBIMIDTYZGCZIYPBPHCCNWLXWIDEUHENBKBPWLHBKHNHGSVCTGWCLHTTYKBZUGVJVMGXBIMLN', props),
compute('m_4_17/12: ${c} WQTNQDFKXNMXZIJYIIGWRWBCBVZVDXGLIESIEXWEZWFFZGUHLCGICGXAHBZVMGKBWQXBJGYWGEHAFDHTWTSADGLMIKCLOSPAIWSI', props),
compute('m_4_17/13: ${c} AMRERJQCJZRGJMKAZSUDKQWBQDHVYSBMERAWNAHYHRPKWIDNDGRNQFCLKRYWQXVWHZISUMUDNQSZOUKLJRSCWUJWPRLQBZVWWHHS', props),
compute('m_4_17/14: ${c} WIDGMZJKBJBXPNZFBIGMMDKNSRNEXBAXBQUNREIRNGLKLQLRVYGRDLINRTOWIVABXYYAQWMYGOTGUZKAHJSJIPLEKJTERXICBUMR', props),
compute('m_4_17/15: ${c} XYVNCOYIIBCAQJCFKWCMHYCILYDRKHSEVHIXGLKQXGCWIIDPGRYXCUDTCNOQWAJDBTHNMGGFMDPATRLBZYNPWWCIGWOQUKSXYPPB', props)
        ].join('\n');
      }
    