
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_4_8/1: ${c} YAOQQUVSNUAPOALKXZEKSROLMMMYCQHVEBPXRAKMDAFQLAVSSTMIBZYBQMACSIMXPDECVDETFFXZSHLIYCTFFXNPZFXBBVZFOOSG', props),
compute('m_4_8/2: ${c} DHGHVCLNSIVMSVGBMMEBCAYPFBKQCPMTSRAKITOLAXPKMLZKLHHRZQWFMGMKXJWCGVKPDQJYCYQXIMNJEJRSFVTKNLPCKOHPDWWS', props),
compute('m_4_8/3: ${c} FQFUHGUEITXXXHUZQZHGSIJOJTBIUDQLSPNAUOTISOBPRSGCWOUTTFNLODJYEWIBHZBLVRDZFIDPGTDLYYCXOQVCPGVAUNKXCRBB', props),
compute('m_4_8/4: ${c} YSDNZISYXXLEHWTYYSULTWKBKZRAJZPKVIFQMPMZLSUYFHPXBDDXYGXTZEJJIXSGQQJALXSICSAJPJZRGOPKJMJARPRDDAHKFKWL', props),
compute('m_4_8/5: ${c} HACAZYROCVLHGXTSTZQAXZRZCGDJWCPLTMEXSXNGSYSRXPBPAYWDJBHTJNAJRYTSAMSKFMIHTYYTBGEDTQHSDTDZIZBVYPMANINP', props),
compute('m_4_8/6: ${c} OIHHATGGVLNLIOORUUTLRHSQBNIVFEYMXKXYPGOYMPUDLXXICUNKFOVWTEIYUOFBKVOGYBRYHRYLZVHTZMHFGNDFMQNNUDEMFQUH', props),
compute('m_4_8/7: ${c} JXDYXCXAIXROXBMNXYFJGHQVCYHQWPSRLLUZOJCPXWFPAJBJFVTCJUQMKOZHMZLDLALEHMHBZIETSLLLMYAFIYBTRYDFGOIPMTNW', props),
compute('m_4_8/8: ${c} DOOEHFNUJADBXHXXNRNPAFBTUJGXGGEKNGLSGGCPBSBFLBOZQBTTRPQBHHDRIFJGEUHLNVBOXOKHKKSYJDFPMDQAMWBAVLRMHYOY', props),
compute('m_4_8/9: ${c} CWKDWHONBTEIXCOJUNSOBWVPHLJMMKQMUCKRWCHVMZCDWSHLBZLJIXUGEZGCDQQDVXPCEKWKDHCBGFQRNWKJNWDBMYWUJTOLTOBH', props),
compute('m_4_8/10: ${c} JNVIUAPSIGHTOTBHMTEWKOSJPOKVXQQRBLQCWJNDSALNLYYMFUAOIPZMJPCJFNIQLYQTNPSYVWZWJYCVWZSYXBDVTVYULXSZOOAY', props),
compute('m_4_8/11: ${c} CHWGQGSHKOGNSIWWYCRQOXGLVBFZCXMJJSENBXXBMKJVFHXAMRQMPEGNAMDSEFSVXAGJWXOJLRHFRGFAUKHZKFKNUAABOFSQCMLD', props),
compute('m_4_8/12: ${c} LTTWQJCGLDFYOOGBDFAJUQFBLDRLXWSLKHKENBHRKGATGTJUOQZFGXNYRXZIOOWIHOOAOPDTRXKUDNAJWARMEFZHIQBQHDWUKPCJ', props),
compute('m_4_8/13: ${c} ZHGMWFLXRFWCRHDOOELJKSHJCNNEUZOTUQNPTTFUZCOYQGITZWYDCFKTGKKEYKGDAPZFBXVZWVVBJHHLJYJZUAUZKCRAZOLPPSNN', props),
compute('m_4_8/14: ${c} ILLJUSFUQXBJVCDYPPGBIAVLRZESNQMRYRDBEMFBSFSQCXQCLPVKFEAITFGBLBMSITNXDUOLQSHMZFYOZBNAGMVJRGDXVBXAIWJU', props),
compute('m_4_8/15: ${c} DEJNQLQDBYBNZFRWFAMJPATKIRJCRBUJCMHQZIPOVCDZFECQSPMZBUEFSBTFDVUAQNOMUIWHYVPUZWHWBVBFLTSCFWHOLIVWWSQG', props)
        ].join('\n');
      }
    