
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_18/1: ${c} MVOOMTCHHANVFSDTSIARWPWBPXXHXADHHXJYNCAMMNTRARRFQIUWABNOLUVRJAGZOFHUBQLCIUPQPPJGZGYACGZJNTICJSUOTXVV', props),
compute('m_5_18/2: ${c} WZTHFKPJOMQPXAYJOZPKFDUEFCVGLMBECJLJKCHNRGKYCNZXZUENGOBKICNXFRWJJDNGPDEONUFXFWICGJGSQAUDISHFIXDFVGDW', props),
compute('m_5_18/3: ${c} ISTVJRJTHAQTFXCEIPAPUNJKHPOEXRXJHJWFTWGBZCFNRQTLEONNEATDQTTCKHSKDQHFKEIMLWUTOYUYEYIWLIUSGFYBCSAJYBQB', props),
compute('m_5_18/4: ${c} ONWRWXUVWXQHTJOJIWCNDDBOGRBQUQMZHVBONWSOIEFVVIENKBAKDIIQLUQJPKYUTBFLRGPYHZKNBJSZYJGBIQCEXRGKNMHMLUVO', props),
compute('m_5_18/5: ${c} FDTPBGDCLZGCZPEPVVRTDVUIYHPAQKKKHFCYZYDKLDWSBCUNHPYGQAVTVILAYVBZXZKFXGRDUXOJXDAMYPKFFPVMTEGHBLEIDKAJ', props),
compute('m_5_18/6: ${c} VJZEOKZTSRYFTKHUTEQHDEGJLHSEVBUBSXXKWDSGRFUJAMRIUJDOSUOAYQMLWIIPDECEUNMYLMLPJFUNGEMOBMLYRTBNINGMSCZA', props),
compute('m_5_18/7: ${c} NOYUEGVNHQJEQLKFSTZFIAZZPYSQLGUNGUXXUALHOKFKXQKXLNQODCKXIRVRZAOQMEIQHFQYJISYTQJQKHLAWHBVUHTOFAPJCWAU', props),
compute('m_5_18/8: ${c} SIHCGSURIRXMNSBYXFXNXKFZGHIVOJVCYFKLOEIKWQHJUHVBTNWSQPNSBHFJRXJATOEFTYVKITPFNQENBVCMMAXNXEEZGQCVEFUR', props),
compute('m_5_18/9: ${c} YLZQMPAXSXAJOWSEGILHHDSOMKQPLMPBAUDNTBRGJPSGTEFHVUADDBHJCOFNNOWYMGZMANDABMTWJDUPJVQDGDLCXUTEFHDFZPVG', props),
compute('m_5_18/10: ${c} NZJYQMKXKIZZZHDHPMCQVYQLBFQGEFZULCFDCTATDVMMKVPPMBGEFHAPRJAHZFHODMRJPJEDXWTBIXEZTDHXAOQUBLTVZRTHRZGK', props),
compute('m_5_18/11: ${c} EJNVPXWZWDVHUEUVLLMOHXWACTZTKAAGWVAFQHQOTNCGPWETENPQPSSMKMUFWXEMKFVFBVAYPWLQIVMJBEGZSJCJFVNTVXTAVOXB', props),
compute('m_5_18/12: ${c} WQLZZBNFJKJIJRETGPXMEFNFHBBEQPGDDGVWYJGYFWRUIGMDOLVMYHJDWFPKJOOSCGQTHZSQJAPPWWAYKOVTTNYCVLLOWAREHJSO', props),
compute('m_5_18/13: ${c} TPXLNDKFLFLZDADOGLCXEJAVVZAJSUREHPYATSDJAJYDIEMCGCWVLHAINIIWRUIWVFVFTMPIHBUBQIECLKECUYRBQVJUBVQLKHNY', props),
compute('m_5_18/14: ${c} KOEUIIDWQUSGBVSHDMUHHZIFACCFJBNCJHRBGLINDFGPNYMUASDTPIMOTZAGEBIQOUFQSWCEZXTJTDQIMDRUTWLOFSMEBUTPUOEH', props),
compute('m_5_18/15: ${c} SBTJPYPHFJOEBKKVVAVPPCQQVYUGGGPOQMUPQLSLRIYIVRMNJNXRINNUZPCWRJWFERRTDWATFHBWLGYNBKPXRFNCZNWTPWGUIPDF', props)
        ].join('\n');
      }
    