
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_2/1: ${c} LLDJEJAICTURSUVDEOCTFYKEOYYRSBLOQKYFXGJTPHPSDOPNQFJNBZUHNOFTYHMBPJECKDODWOXGZCTKMKFHXXFRDQFVROXVRGZF', props),
compute('m_5_2/2: ${c} HSQAFFNJXTLEXRTDYQSULEMAEBZCEIMGKOPDPQKQUZLXWJNHSCFOJQOWOJOWHBBUAZCPFOYUITJSQMLWEJHBULPQDZYIBBPBJYPW', props),
compute('m_5_2/3: ${c} ICXVGNBXTKKTLYIWMBCTCDIQBRQDMVKDQLOSSIITFWAEDZTIKYEDIRKLJPIFODNMQAEGPWNCBQMEXOUTPESYROSEOFVTICMKHZDL', props),
compute('m_5_2/4: ${c} KYYMTLJUJIHXMYRZEBULIHFUUNVVJWVDUEOLNMTEIGUIVWIMUDWHHPIXJWZEAWBXYKPSOZGOOYRQTIIEILYILTLVYBUISYUMFENN', props),
compute('m_5_2/5: ${c} LGZLBPGCJRFZASRBGOJRHUOHRBWMFIAAOSWQVHBDDZLAWXIJTZFMFHJGEFTKCDKNPZVDTWUUGVTVTLIUHCJASWQEMCVUAIMIDSED', props),
compute('m_5_2/6: ${c} YIATQEODIYJNBQHCRRWBMXTUTELINUFYCARWVNTDJEOOLTXURFRZOSOWACFILWIVHYBGXZZNWKWEHWPCTXPJVPFEWLIXBHBPCDGZ', props),
compute('m_5_2/7: ${c} BRNKFJTBGIHTXSVUHHDHDUKNVOEDFLUXNPNJSJTIMWQNPNXEUDFBJZFNLSUVEBCXPGVJGNFLKOPMPMKFEQSFBTTDNINUQBEFNWRQ', props),
compute('m_5_2/8: ${c} IZLSSTCWIWOICCWGQTQMXHHTNMSRVWJJFWXWXZXHDMQDWGESWMUPWNSZFRDQMIFYTOHRYTWDBFWQYIVNWWYOJSKPQHCISCVMDNZQ', props),
compute('m_5_2/9: ${c} EGQTVARUILOHSBPOCOMHWRPMZOOIEBMGNJULVRZJTBVUXUEEGFNTPWWJTJCIAOVWTIYSMCKBUZEEWFHPSLAJYTEDYTUJRICAKZKC', props),
compute('m_5_2/10: ${c} TYZCWUPJZXICKONKBZQKNTWVIQMARSWPTYFEFRECIBEBNUEDBJJFTYNDITWWLZIDWEYGFZEUOMQNGLABNCXFBEWSBRXBBCBSAXWG', props),
compute('m_5_2/11: ${c} TRZFQIXBRJLXBZGHXLBSZQETTMYNORUNMMHGORXRQOTVFQAKSPANDYLFCANKTRCBXYIHLBIGOBYNDRVJKQTOXEVFTMDDVGKIMZGL', props),
compute('m_5_2/12: ${c} RFKFNXXNFFVRAHKETEKXXAVHDUVHLTLXOBANKAZFKPMHXMQACPIKYSGKPUWVIXNHRQEBWMGNOEFRGVEBKESZUZUOXOUKRXPICAIX', props),
compute('m_5_2/13: ${c} VSDFAQLDKEJNGEBMATLSQFDNXUHRWEIHGEZXYSFHFUDCPVDSGBFLOGNXALOTJSYGCXCTUBOTICEGUTHAKNZVQNOKOJIIPHQWLXYI', props),
compute('m_5_2/14: ${c} RZEBSYLZUNRIPZRMXSUOUFFSAFRUBTPVMAGLFWFMGIJMUTIEFHUIMHFSSWDUHYJJSILSVVRGAALMTZWPVNBMJHUNHCSPOSSIAHCT', props),
compute('m_5_2/15: ${c} CKVLKMNHLTCKBZZICKEPLNOXPWCLJYVFAZFQZZWGMQSGJZEHDFDEHRIIIZLPBGAJMMLWTULWRZLHQPBKGWGUEURKHGHPGJTVAPOH', props)
        ].join('\n');
      }
    