
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_17/1: ${c} GLGMHYIWYGEXSAEIGIMXVJIQVPPAEJYSRLRGTYHDCGWVJPWVKXKYCQFTJIDEINTFIWQFAGIDGRKPDKJRACJHCZQBCDQQYCLMPTAG', props),
compute('m_5_17/2: ${c} VZTPFAHRWIJZRUKEJSUFFGPEQDRVEAZICQPJJWAMPVXXXIUZOGFRVELEUTZLOCNCVICBHJVXWZTJWEQJEZIMQYALIYKPDATXTZOR', props),
compute('m_5_17/3: ${c} KOONMFNHPTWIHFPJONKFIFSTECQNSBMASVUQLYDXMNEBMAOYZGZFCXCNQTJEPAQSIKBZFMDJMBAGTZEQGTOGEHRUNYWZXOAWHZFR', props),
compute('m_5_17/4: ${c} DEDAZOFMBXNWZZUATXOEXIWKIJRKGDUTETNLTGCTZRNUHWEJFCHMEBFLRMAHUJHULIHVASZSKQYTIVLSOFIJSDCQHORIQFGSTWEK', props),
compute('m_5_17/5: ${c} DWJEFHKZYDZYZAIGKFQVSIKELSCJMMDUCCJGNCOPWYLEKIQZIWWOSREWLZWNKKTTYBWKDNLIEAAUCSVEKPCXQHPLBEXHKXOJXQQV', props),
compute('m_5_17/6: ${c} BBTXVCWFWJONQKSEJWVIJJQVHNBAUYSAAENBJHOSCAHZUENCIICRHXMHOLUUEHDLAOAVFJVYIZZVKYINBTSXSAYMKSAJPPPPIWXN', props),
compute('m_5_17/7: ${c} YVKFRHBGFOWYTTDAGIKPEZECRYZOAXBVXXYLTMPGVRZMGSULBACVYXKJAHYICANDVPYUDGFTGDACZSJPOHCXTSLVQJIFQIYYLJHY', props),
compute('m_5_17/8: ${c} BXHEWPUPICQYHSIEQVTZIRWFRFXUQYOFRTRICLEMGOLZVQULKOVVUGYNHPSREOBOETKEEKFBOMHPZYTVFUERMIHOCRQVHVPANJRT', props),
compute('m_5_17/9: ${c} VFEHERKOIJWDMFDPYHYKPCSFTYNGRKLZBLEORSONKWEREZLSSPQKJDBBASGILJLFFVDVJFSQSKVOKZTLKWQLHEMOGKBTBYMSUSUU', props),
compute('m_5_17/10: ${c} FDAJIUDZHTOFSIYMEHOKUXDSDJQZIVIDMJZYEYPSQBJJOPLOPQGKQDTFEOAKRBQEMQJJCVOAGEOJWARKDXYLFBDOPIUBJEBSTLPO', props),
compute('m_5_17/11: ${c} GRFEQDDVUWAUGEABUJESCBPSJXDAPOQKSYRHXGYFCZFVFQWSQELIOFEUALUWKSYSWTKUCULQCQLQUQIWTMDZGKUNLIVYQZRQHFMR', props),
compute('m_5_17/12: ${c} ZNWTTCIYYRMZCKXRZKSJTEOKODEXVRKXEOSTKFVRKZSHKKFCJVKMXUHBNECWJFJASHOVGNRDGRMDXLKIHMUICFQUBLWVQMATTXLY', props),
compute('m_5_17/13: ${c} DDHYNAQJMOIHPGAJZBUUMAHGNRZEFASGSHLGJNWMCKOHWEQKVMQSXMLLQLSIOXHTTDEYDGWILIMOXMUZPCQZQEOKNJGUIBQAJSPP', props),
compute('m_5_17/14: ${c} FHZYGBMNCBCGQOZDIXCQDMFDRWQUKHJXJJEANKACDEFHAZBIWQJHBENKFELUUIZYXQLLXQFKQZVTLDGRHXOJBPSRARYJPJXAIUPB', props),
compute('m_5_17/15: ${c} FFCALYFHWLMIMUXRFJBEWHNOOGYYOTGWPMGMMKBOIQAAGZUVONAOBRNVISLNYPCYUISBHIJDSCVMFBXPFECTAEVSBGVZLKPYQXTO', props)
        ].join('\n');
      }
    