
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_12/1: ${c} RCNNQOUCQLGTZBJSHWGWHYFNVCHGTPHTNFOCVOTQTZXTCNUKUISTIKSLAZHXSATUFMJFUXKPJXQFLCDYBFXSZABXEFVSNTDSLOLO', props),
compute('m_5_12/2: ${c} KVDILLUUJBWDCVUDASVXVURTSDUPYMJEMOZNLRVHAVIMCHKKGULGFJUNDXSLJUIQXDSDVOSQWOCPFLUGQFTPOIHARHTFNUERWMDQ', props),
compute('m_5_12/3: ${c} HURIQRWJQOVFHUDKGLUMTSJQOUPASXXCJSVIPGNPQUYOCUBYKRJMBFSXYMYLWIXVHPARMFAEMGIABGLCNCSHSJWTMHHAVPFUSZWA', props),
compute('m_5_12/4: ${c} ERIMNJLDOQOGDMVZOUXRDYAATKZFQFCKFYKRAWACYOBDVMTIXBUWHUEWCASUTKGXZJDATKXUFCQQMWLCYFCAPZPFQJZJFHJEPBUF', props),
compute('m_5_12/5: ${c} VUNYZEIQGVHUGQIPPZOKLXHUTIJJKALRHPYPQCFMYSOMGCYKQOSWTSPGJXDAPBBNCFRFFPDXGWKEYJVUBYRXPEFKBHOGQCWYSXCI', props),
compute('m_5_12/6: ${c} HXBGCQQRQVXRMMITSTQCSRWAWOAPWHJDQLCHNQFCKTLYGXHHITYKNQZAXVFLHPCKQXZSWVCXJLQFHJSLGNKZELQUTIITPJYETBKA', props),
compute('m_5_12/7: ${c} EKIFELTORIBPKESKACZVBVMXRKJRAPRKUEATCLBHZMQWCVAQWDJXGVMTIALFLOUWCLTWXYUMTGBQXIUHDANCOEEMHJSBUGWGKDTF', props),
compute('m_5_12/8: ${c} CXTULHSHGBUFGCMLKBSRAOQPRTIMURRVVXIXSRYAQTZCHBRULRSBPOOKQLSYDLZJMZBNCVPZIXCUUQRLNRKTGFPCOFRYEKRJFXRK', props),
compute('m_5_12/9: ${c} HIMHWCBXAZHLNXNIKNFMKQYXFBJBTEEPWAMOITMXVKYONDDNCIRLCIQGRFBRPDHDUJAFLSMXXXEIKYTOYAILWUPARWQFZFYZVFFL', props),
compute('m_5_12/10: ${c} OBYGZYALJRGADOQXJHNVVFYZGIAVMODXJCAYXUFJSKKWSNQKEHADUNHABXQOMSDFUCPRSHBAWGRDHQLRSBQKVQUXWLCRUWQGRIBY', props),
compute('m_5_12/11: ${c} CPARFNTXNUJALEFUUTZKSKPPYYQAIVSAFBKWGEHVZJYBXHPEESDJPGJVQSHFOLIWKXWNWXDQBRJLZYPYQBGWZGXVHRNARUNJWSHJ', props),
compute('m_5_12/12: ${c} YUFMCXSPYEHQBPJPSRQHGMEKBSNSKZJAIZVUEYPDLAQOFUTNRTYNFWEJGFHKCUNLJFBVLLQXCDGLHTFRHUPIVWENLTZLFPYSTMJF', props),
compute('m_5_12/13: ${c} MUSXERHWAIKFXPUSCETNYRGGLHNUEPSVTWMTUKULUEFMYFAPHOCOMLZJPZJINBUYMUQWKXWDJTUTTMGOJPMGUWONRENFZKIBJYHB', props),
compute('m_5_12/14: ${c} HTMFSEBCGYGHWTFAYEYOGQPBEOGXDXDEIGXMUMVXKYYTNCVCNCBIPKCXSVSTEMWGKQXPUPHAVZXKXVUMMDMYYDGLFIYMUGOMFYFH', props),
compute('m_5_12/15: ${c} DLTTGSSZBBUMYWXYUVOYVDJQCLLCSUJIVUSQCLBSMCCLUKAJJQZPUQGTWSTGPIXLTFQMTABRNJNWYCLMECGKUXWBBGMWUUEADWMA', props)
        ].join('\n');
      }
    