
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_4/1: ${c} WNMUVAMCARXNVNLVSIBPVDTWFFLQYQZPUMXEDNSZSFAOSDDFYBIGLMWSRFZRHFHICEXKHOPLQHQNDIWQWDJNNTNLQHAVWDYIWEEQ', props),
compute('m_5_4/2: ${c} HBXQUATQKWCYEBIRJSRGHEIZAIGYDFMZICOBLYGMSKVWAOQLMKMYGRWNJIWXIHMFSENHVNQTYUUGKWKAWSYJQGBULZGPBWCITFYY', props),
compute('m_5_4/3: ${c} CNPBKDZTEDQADAMWKMNUHWAOMUDDRJJQYXYCROQFMCHWJAHGRCEXKILMZWJYAYZMVSHSHJJOXFMOLPLRSYPGOEVSJDXJQXFNORRQ', props),
compute('m_5_4/4: ${c} WMGRZKFAEITFZZQMOGEMAZARWHOITQLFDEWYBDOOBONCJISTFJGPQRBYIFPBQQBJMZLAWYCPSJWANEUXOKUERBFRNGIBEPPYQYRI', props),
compute('m_5_4/5: ${c} OKISDHSVIQMMGWFGWVQRULBROEEXSEAUKNLWIGLMEKYJRCGWGOUGORYRGDGZGCSQXSMERZHXZHAHGEUPQPWITSZGOAJNEGVHPPFA', props),
compute('m_5_4/6: ${c} EXIJRPTNWCGWQRWCINXSRXWMIMPDPHKRJQPLIKCSRFUSSEXNPWIVQFRVGHVRIJSGHPLAESZOYTWMGHMWRIQGCBMJOOSZFTLGPAUR', props),
compute('m_5_4/7: ${c} RPDJBEKZZRIEMUZPIHDWNMMWKZBWEEKRHFIXRNIYRGCFBFVSLRQYJBBPSJZHFHHAUYMDMUXEUHFWZCNZEMYLHHTQPHDIBHSXVXFL', props),
compute('m_5_4/8: ${c} LEFCEOJJVRVXXJRSGBQUHWRTUTYWPLATEUJEPFSBSUHVPRBOCYWRXQIMNAMFNLTDXKVZSCCLODTXQVMIYPGTQGQYISFWCBZSFIYP', props),
compute('m_5_4/9: ${c} BFBBGHALILUEVKBBXEBRAODGIIHEHDXCSMFILNNUDEBQGJMDJWUNRKHNFCKKEUMBKVJOZNNFKVAEVSEURLERGHQBWPZKWQYVITVD', props),
compute('m_5_4/10: ${c} HEEDMQINKLXALTZDTDHYAFTRWFLWMRTSSYCVWIBOJOHEYFHUDHYQUIIMKSGIGIMWZUGGMWJIFNIXHMOEDIOTFZDHIKOKSJGVHQCZ', props),
compute('m_5_4/11: ${c} CCIUBJHTDATKYGFDLFBTRUKSGKFXGJYXAYBRFNYPXLCKLMOXUUJVSXQGZLHAGKCFRBJESFRDLEJPVPBIKGNZHUELQIIVRDQIIBOS', props),
compute('m_5_4/12: ${c} NGJSYAMDFPQBVTGWGTTMLDCWEHDNCPXYAADMPNJOLUWIZHSAIOUHXFCAVMOYCBOMEMXRJVTFWBTOZPFAKMMDYAYSTTTUDGSLXUPG', props),
compute('m_5_4/13: ${c} DFVCNYJWJBOPOLGOPWXACRHEVVVDDNWBHXFXPAIFUAXBAUCMEUUCUUCJXVGGTTNRZYNCGXTVCVOHEESGYJXQGJVKAOKZGYJTUNCX', props),
compute('m_5_4/14: ${c} NAPRPINPILMXMKJTBUAYNOOCZXKNQKEKIGBLPQFULSNLDGCCVAFFXKEZNQLOYZZAQRANUBHWICSCBOHOUJPPLGAVGCPDCRUJZXNP', props),
compute('m_5_4/15: ${c} MDHPGPIBLRDZSPLZGPFUSIUUXKETGMYBOAUUWISPQYCZLHUDCVFJLAPTKLMDQVJIIOPGIKIVHIAROBVIPAGGVURLJRXSWOMPYQBB', props)
        ].join('\n');
      }
    