
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_3/1: ${c} VQRFDLCELFNIOCRBKBPQSNYRBLKAJHABPCROOHASXESIQBBRBVJSDMMGQOXUDQTHOGFPPLLUMNQLYVCABPVXCEBPNGRFCDLYUWHE', props),
compute('m_5_3/2: ${c} ZTNZSWTSMSCTIPJFJUDXVCRJGQLCUVRBPRRKHOOKEPIZITFIUNICPCQIAXYPVDYXRRHLWPQTSDTTNVFAPXOORCFKVHLQBTJOCOZX', props),
compute('m_5_3/3: ${c} SWQOZRIDMBQZBADZVRQPVMUQBBUCEYBFNKSSOXXEUDPKWBVTWIWVPTWNLNOLLUGWSGIIOTEAPKHFGXSVMXFJULKYVYQFTJNXYJYN', props),
compute('m_5_3/4: ${c} DOXAEYNRSOTVHQUZJWYUFOPVBKPNWPRMDJQLNMEBWWMCTUFBKSWSERSEHKVGAGZZHZCZOSGMFQALDMXKRLDLVWEHPKXVXEHWMHFD', props),
compute('m_5_3/5: ${c} ZGTETMJMVKSGIBROZVWPEFTFGHWGAKSVZQRYVBGNTWCNOQRUXBLXLVFYWZTJOZHPTMGGANTAAHAJPCMJFWVGBIYZKOAPVJNUXTUX', props),
compute('m_5_3/6: ${c} ECLKYRRATMKWDVZDNARKZORKEXNZVZNPKZXRJZABFGAXSNXSLSAJBSSRBLPGWPCQLQHBFSQFXVQPZQKLMVVFYDRUCLWCZFQGZORB', props),
compute('m_5_3/7: ${c} VLSWRMSINTBFHKXACSHCNMBIPSAYYMDWNWOTDZWLOILMIWGYURAYQSWWTEZQYDFDNMCOATGPSOUOPSCROFYQCEJMPKKNQVWFNMMA', props),
compute('m_5_3/8: ${c} EYDZRIFBZJYCOBXXIECHOLGPTGWEUWOGFLHASDPLWRFYAWQFJTAJUGXGHHCVSDPCLQFDMIQYHBLBOHEISEICTSGPECDNLRUZGIOA', props),
compute('m_5_3/9: ${c} ORVBAFRQKLWLBSQAFCKCBDIKSRCFZDMMQZGSXTIAVFNGDIXDDLEMRAFVVXYUOEPESVJKDLKWBKALLVGUPDDRLCSDGQYBWQHFWZQE', props),
compute('m_5_3/10: ${c} RGEIBOPAYHCYWHLLCXIRAFGGTXWNZOWFTTFZXJZZDDQMMJBPONPRGNKNXVWHVBJNSPOQEMWWHSWKMLILRGMCRQUNBIEYSSHNCPOQ', props),
compute('m_5_3/11: ${c} KIDEPIYZYDFHMQFVKYWPZDLBWTRGCKJOHPRMSXFZUFFKTEQMFTJTRDGCZICDSCMIDMGUDTGDLGQUEWNPXQWKIJZHKGSVJSKLTGTH', props),
compute('m_5_3/12: ${c} UDDJZDYOVDFLMCNBWBBDVUIGJNQYNKKQTVBZEODCPZJMDRBVFMUDRPLIEBFKACXBJIDCKDSUQFPJMEYNBBHIWELPISEMFBYORJRT', props),
compute('m_5_3/13: ${c} WOXEUPWTSDYXHXJRURMULAQIVEBECHSHENWLAUSYKSBUGCSQTXCQZGYEGIFYSOLKUIOAWWMNFMISESZYVRFERIYADSHXHQQPRTWQ', props),
compute('m_5_3/14: ${c} YKJKFJOLSRTUZTRHRCGVAWPLDDZPZYQTJNOQSFBYDJLPCZXBBIAXIMCMFVXJOHSDFLYFTXXJRIYPELOGSBUYVZBXKOLYPOYIZLTH', props),
compute('m_5_3/15: ${c} ACNGYAVOOIXZZFNJFLMHCEGTKTQBNMKBEZJYVUOTCJRVFECMGKTDEAJZZJKHTOYKLLNIXVJEYHKWKJTYOBEQMFIOPYNVYBUXAGJA', props)
        ].join('\n');
      }
    