
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_5/1: ${c} GLVBVNZPUNQNZGBSFFXXFSWOBQMEHHRXUJCNAHRMQWSKLXACNIUYULYGNTYOZKECNCUTGAGNABRDEPKBPKWBDDXOUNHRZJRPSWKQ', props),
compute('m_5_5/2: ${c} ITRDFWAFFDDNJJCILGUGHFKGVRNCJUXHQXMGBHRUSBIIZXCUJRAAHIXSJKHDKSFRXJQCUVNAMPPBTOTMTQTFTRKWLWZPGWQEXAQR', props),
compute('m_5_5/3: ${c} TQUEFBKXEDYWIFAXUGWYYIEJHWUZBVEFPMKQBOJRIEGTGPQWMGHDKWKIIIOXHLOMPUFQOPOEXLWYAZZNGRIDQPIXQZKHMMSBSVVU', props),
compute('m_5_5/4: ${c} DVDGSRQKKJRQUXRNLFBJUONKCDHTOQQKRUMUTDSTPIBEOWTHNMRMJLVQAHDGFKMSJIWFMNMKWKFFRZGPKFNETMUFTSCHJGNJOAWT', props),
compute('m_5_5/5: ${c} BYTZIMGIWKUHVPDZDFFXCOMTRQFERSYLGCLBRWAKSVBEGSEWUCUBYHHEPAUHNBKPARUFWUZNHCDFMFOGUGMFXRUBBRSHDIEWCDYY', props),
compute('m_5_5/6: ${c} JDZXEVTPJMGJRGVDMWNNUHVTOVUZCHWEUFNPQJLUNNDETHLTZSWFRGQHUDECRDGFUXTMVVJDLCSKLIHRUDKLZUQCCVYVKDIIJOIB', props),
compute('m_5_5/7: ${c} NQCFFZMTLZVEPMXBFFOPVVMIWKWTQVRQMTMTQWTLTDCOLFZESCZJGNDDAJXYXQMUUAXMHJKETUUZTSZEPCMJOWHUHUDKELSEPRRE', props),
compute('m_5_5/8: ${c} PSPSLCSLRCFFUJHIKAUVFUDFIKEXCSQUOVNCRVQGZAAYPTHDYPPCCQRGFKDWUECXXJDKJPKWDFZACNOCWCUOYCYTOWUSXSDUYTMM', props),
compute('m_5_5/9: ${c} GEPDHICNMBSRHOSRPGZGHGQOQFGVQNYVSBKKXLEJVUJCXVYMEVKWNLURYZYDEHOUFLIINTPHUKZTUTTZJUQGWYXCQBWXZCZTMQSP', props),
compute('m_5_5/10: ${c} TJYQQLXZJKYOEWYRYSNJSMMIGXDNRHWENKDLGHJNDQAZPABUZNQPSUNTNPCMZXERMJUTDLNYNURHNZGWQIETSQGUHBWINWTEVQNE', props),
compute('m_5_5/11: ${c} CKAEGILJFMVMEZRUEBYUISFPFTDAKRECHOCCKVXHRGXKYUNSMARLATOHVBYUANFRCIVZGYJGKGDKSODWJLAIRGZYJHXTFGGECTWY', props),
compute('m_5_5/12: ${c} DDPKLZFOBAGBUGBLGZLMPBUYWNBQVPOVBMQMCIFSBVAOCNHBLYBVEXLHJITTCANJWXDOKUPJIKKAXLFASKKQNHXVBVXLZWCEQJHI', props),
compute('m_5_5/13: ${c} LUGRESYSYCOQTTJQREELTIUDKDRODCJNBSBBTOYCGSQVOQDYWEHSWWYQWVSGDIKZEEMYOBUJLBRFTNJOMKXPKMBDNPOYQROVSHLF', props),
compute('m_5_5/14: ${c} IQRSFPVASLTYXUSYZPEPWLKHUVBMMDNWMLTMMSQZHMEGLKSUEWIKWQNOGLCKEWIVUNIXCGTSBOPGIZKLTMHAHYIRBHWPRKYBFILY', props),
compute('m_5_5/15: ${c} AJKGCFGBXMWDKSLQAKFTYJBLRFXYMXUBXZCHWNVUBCTSCXZEHIKKTLKJXELTCDZVAIVSVXZDAPBVJHDLXZLSERRVPXDYUHFVECGC', props)
        ].join('\n');
      }
    