
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_16/1: ${c} XCCGHICBKCHMQANQNNABQQNCLCLOGZVTYWUHCDHAWXNDOLYQFILIVGRWOQMWGBDYNDVQGKNKUGOOZLSIXHHPLHHQBUSPVVALACGR', props),
compute('m_5_16/2: ${c} NSTMGOYXHEKAXUVQOAZUSWMJWKFUSFTEHFXHCMMLPJDCYXFDSTHAZQJJCREHSUJLJIPBKYSQPXBDHIAGTLCTITYQOOOIMKHERQXA', props),
compute('m_5_16/3: ${c} WRNMACOLTGZXFVELTZXTCWNQHVOFWGQXRIPOWVVZFEJHFPIRJJUZJAQFSFWBEUDKYWDVMIRZOHKAYEYIXJGSYKFKYEQNZBQHVUNH', props),
compute('m_5_16/4: ${c} OPPLCZGIPNLRRFMRCCUNALAKBWGBSMUAVPIMHGAYZVYJGCBDNXUCGICGNQCGDVTHZDYJIPCMNOIMELNNAYPHNGSRFFDKKCYBXVMS', props),
compute('m_5_16/5: ${c} OLXCRRIUHWBERRSVLAAFXJDDJACNWCLNIUGGXVNYMBCBUVKONHXKUQAWLEHPZAUPVCPJHHLNKSOYMIEFTOFVRYKOTQJLWLYMYTZF', props),
compute('m_5_16/6: ${c} AYTHNARWQJERYAXDXMIZHBRQRYSVTCUSNBQYZJTDTSAYQQSZQTVEBIAJCOSXRNJXZKPXNFQWZTWZYSEXATJPYTTYUVAAZNYDIMTX', props),
compute('m_5_16/7: ${c} AKDGPYKDBIMHPKXQQFPTXMZQCZGZAQTQBBLSARVCDIOVGYCZPBEIRFQZIRVNSEGSDWPTTNINMLHOAMRMMMZDFASRPMFLGVRGQTPB', props),
compute('m_5_16/8: ${c} ZPFJPOHYQOQTTBSXVLOLWQDKKNOSBSWEIKGTCYQYPRQSBTEPSVLMPQEOVSJMMHULQVOWSHBHMOPGICQXPDGSBZTASYCFLDJESOMA', props),
compute('m_5_16/9: ${c} YKFBSHJQUOGVRLLBGGPNSTMKSBDRKWFZDISEUABTRPYWXYWOKIETLKMUNBUGSEAUKLCJWFCJVHLELUUTHUVIHQSZYSVCDISASXOP', props),
compute('m_5_16/10: ${c} KXKDVKSFWMTLOIXWIIVYYYOHPGFRKLJOGEZCAWVSVZMVCGBFMAOKZNJVGRMHMZDQIRHJNJZAMBAEOROEGUVMZRGNXGFMUWHPEYST', props),
compute('m_5_16/11: ${c} IXEJHGSMNDJDAMDYOWBLYSIKAVRXCCFKZZHAEVSQLEKZFOUBIACLYKKGNSDSVYPGSWVZAUTYFSFPXZVKBMRXYWAKFIFOZAAFEXDA', props),
compute('m_5_16/12: ${c} JWIUJQIDOWDDBFWWBJSRDFORCKTATPILJEOUXDFLKQEGFVPZLHYIHSHNOCUVAOILERDLBYAGVVREJSILUULBGTSRKOBWNNPZUYEI', props),
compute('m_5_16/13: ${c} CUECUYVVGMANCMLIMGJCPGUHDLVOBZLAXBKYQIRGFFKNWKWLUDGKIAONYTCORBGLMJTWWMYKQAEPCWTJNNZTATMGMSFCTTMGAFTY', props),
compute('m_5_16/14: ${c} VPHDKKBXHAEJODQSJPYZWTMUEQKPDHKLFVPSKPOYUNIJSCRGETJIIYOLGWPLHHNFIAGOCCKCUBJGKPOCANCIDXZLBPKNGXKKFQWR', props),
compute('m_5_16/15: ${c} IYSHPQDAASECQGDCOHPTYUCTEZQQIBTDHKECXZCOLAZNISBHSGGZJQILCUZXZYITTJEKZACKNCVWMVKNBSYQSPKNMQPMGTYDBRZD', props)
        ].join('\n');
      }
    