
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_20/1: ${c} LKFOUBQZCOSLXDTVGKPEJIXGTJMOKEYPWNSTLDZJKXYYCVYUJTXVEVTXHTPWDYVOPIKSQUFZKJAFWOFEHELHGSHVDCNUVQRNCLOS', props),
compute('m_5_20/2: ${c} PZHPRZMDOQLWFRULLBFTCDDBUMHEWYSCGOXWOOABGKKUBHLCOLOXKOHLDDBSVBJAEWTQDXQKGNZCJJQPSUSBMCTMZRXPZNIEUKOH', props),
compute('m_5_20/3: ${c} ELEMKBAJHEUXEFEOUPZYKXYTJKLARQBDLNQYJQXERZTXLMLHUEGQDJOMMHZPEPMOKIMSHHPPWJSPJMLPBNHYTZRFTZTPPWFJAROB', props),
compute('m_5_20/4: ${c} XPHFQIIHKMMYFPETZGNOTZDNDPZYAJHTVUQSBTMGFWKFMMSONLBDLPJGARCYYUDWNYHPIVSSDRMQGTLIUENXVDALICYAGIYRKLCE', props),
compute('m_5_20/5: ${c} JEWESLRMOMRBOPYKMQSOZNBNGBGHQMPEXJYTVGWYUGTYNJOWPVWISEMXVQZYWNZTDAYSKBMBSVTSEKMGXXILEEPAGBNEZBQVAMIN', props),
compute('m_5_20/6: ${c} CKSTMENLGRNQDBCDLIHDCWWOLUKHFAECAGRRNGCZPCUZHNWWSLGKDCIBOXVZNCJDBKQRKNWFMYEGGNLACNYLQCVULOXOWRWELKYF', props),
compute('m_5_20/7: ${c} WKHWLNHRAIEOVRZJJKNYYWSKLDKRPTUHCUKTKGVPBAFGSTZOUZMNICWISIFESQYEXAPZKAAWXFTKIRJDCXESJVFROGTGTFAEWXTN', props),
compute('m_5_20/8: ${c} OJPMAEOHPMFVEGTEDNIXARIQULKWDLEIDILLZTRJNJCPGIJDZGEGWKPVUBGNCMGWBTVBFYUXZIROKFYJGZEFIVKSINMHLUWLLVKR', props),
compute('m_5_20/9: ${c} ZFYAXGICXFDOZRLPFFPPUVUATFHQCQMJJMOQZFHSIGQBKBVAPIVQIVCIPHUAAZAHCTZWAELIBJVCSUIZEFFAKITBGEDLVPWSCIBO', props),
compute('m_5_20/10: ${c} NMLVLRAVCEZWDBNZKEMKQAABJYDGNDKEQDXPTXDLNWSUTDXFUAROJBUVFNHHUMSFVCACIFIXBWOYYXTWPZRJTALVFNPRNTCTBZWN', props),
compute('m_5_20/11: ${c} XGCTRQXDNFVUSRMIPPZTOYLJIXOIJIVYKIKXGLMTAXAYXGUXVLGUISECZQVVSXWDOQHVWSUIOCHJJPHRFKFAKJRFOVJLXHPOQMWR', props),
compute('m_5_20/12: ${c} MVKLCMLFJFXBBNSFCJMEGONDRDOKCTLOKYARNIWRNKTKSDEVSPPHBOPLDXCPNMRUSHEAIHNTYMXUWSICCDIQQCFVVGJGHTGRBIQG', props),
compute('m_5_20/13: ${c} RJSSCZMYBJVNBKNXCXNPDOCXLZGIUGUTXYYQWTPPPASCQLPQQZGBKBNOTSOTOEMYQYCEZUZSTYRNAAUSFAEFOHYJOCRINGDZJLKN', props),
compute('m_5_20/14: ${c} KHWSBVVCFXEDPREAILFZSEWUQIJRTKZUFMTKYYYENMUJXJARFDSBZLMNHIUQUSSXPEIRUJCVBCXTUDKYFRLUVXDFCZBBUNFBVROF', props),
compute('m_5_20/15: ${c} ZRKXMEDDNSOIVRFLXPYNYEAIKGHPDEERZUNLBCAXTBCIDWQFSBJDMCVIHWNVRCNCZKLWSVKKPTFKEXKHXDGVTDKTAJVTDGBBQIVH', props)
        ].join('\n');
      }
    