
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_1/1: ${c} KGUIOKPOUXIUFDMZCYCIFTAAGEBKHAPOZCAOOCUOAKUINSZUIFZXDVZTXWXQQMRAGZDUSVLMCXHEOYIXWDTRMQGRACVGLQAYMVBV', props),
compute('m_5_1/2: ${c} QLKTNHHDTOGDSQCOKABEYUYSUFDPQJPTMRQNNUVMITKKKQCMRRYQZKZOZBNOOHYLLKZIWDLUIVVXVKCJJHGJJQSJHRUCUUSNORRI', props),
compute('m_5_1/3: ${c} FGZKJOAVDLATIZBKYXDHNBFVDDXDXKJUTMNMRXMGXIACMIHJJULDZEXZXRYLVONXRBMJXOOYINFEIFNAMNVBBHHIHJSJNAPNQGHE', props),
compute('m_5_1/4: ${c} RMFDXQJSUQYJDCJHLEAHTEAPBYPXBLGSTKHEVINUSVHVUNGDMVEQDSPOVGTNVZESDHQOUNROLJNOELSUFNLMZDNQFWXHPKQDZCNK', props),
compute('m_5_1/5: ${c} URZMDMYKNPMACJIBJNMMRLOBFRWUTXGPSDQWEDQAILDIQHZFLIQPMAYWHSYPNSRQJKBWEKCREMYPCMGGOITPOPFFRDARKEQDDZNO', props),
compute('m_5_1/6: ${c} ICQNQLHYNFXPKQZGKSJDPRZJFJNDUCBXWHHCAGMWOWZOOBUTRPSGGZAGJDIUOLYJWJFZUZCYZDEZNHIGUTONZPAQGZAYDRWAJXQC', props),
compute('m_5_1/7: ${c} OPWRHXQXASGUOKAVMTEHMLQPQSWLAEDYQNJJTVYONUGAJUAJQPAVMFNIMRZHJJECBQNZMQXHLBIBWPSORKKBCWIQMKATADYUDZYY', props),
compute('m_5_1/8: ${c} EVUDNGPOQKGPJZFKPIRDKSYTZRYWLCWVXACBDWVJCAWAXDIIFQVHQHBZUSMBEMWAYQJMBYHFHJRQYQMOSRYYGJDXEEQGDXTUUBBW', props),
compute('m_5_1/9: ${c} UPSFRUORYACTTVWDDPQPAHVCRWKKKWECMUWQPZFBOLEQFNAUCMKFSUSHLZIHOBBLMDBBOJIGTGFTYXIFQZIGQBZLQGFLIGGRJEFK', props),
compute('m_5_1/10: ${c} RJPLFROYBAKTVPELTBIIOOQQELLHIDJGWFKLBUICVLJWOPYTBIMAMMIHPQNCTUUPSTZUZYPQFCCEULWRYVLICJFVBSUMHSXJQLSK', props),
compute('m_5_1/11: ${c} XALPPZSCFIKWAXENMBCPMACTGJDSUDUJRJLDSOLNFKEIWMQMESYNTUGLKTXTKCXNBQXYEIXAIJNBSPOGSAVDVTQHJEVFPIJDPMQN', props),
compute('m_5_1/12: ${c} EZMNFLRLDDCXXDUDTDPILAENLIBTDOJUTEBMHOJXOCNBMCYYVCYZNAEMOEHTXOAIQVOWZHYBAVSDIJIXQGFOOCNYDJDDXXIWVZWW', props),
compute('m_5_1/13: ${c} YYIOERXQAJGHUQNJITZSLZFHCOMGISHWJVAODSTSAUFLJGCXDBWRFPTWWFJNUQZQCOKQTKHMDWNJGITSKXBQTVXXSPUSPKYQUWQL', props),
compute('m_5_1/14: ${c} DDTPFPJXIKKGJBEEIOVMGPPXOFVWYIMHWFSAJBTDRNOARKKISRPNZFNKJGNYEYOBIIGMNGIENVQNTEPFTHXWDICQBENKSJAOJZNG', props),
compute('m_5_1/15: ${c} NKYNLKBTDEWDNBQDTJOPMTPOAOCFBTSEFGAAUSXFOGLUQDJWLISQIUFJXPOHGGCJPQKJENKXHCJMHXJKUHRHKOAKSIFRZHGNZUQP', props)
        ].join('\n');
      }
    