
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_7/1: ${c} DXFMVNUTZLVOIHZMDSVHASHRJEIDOXQSBBVTYEGYXWMRAXKVDQMFKIMFOEIUWXIRPSJVXXYSXMNPIUTOHWMRQDWTWGDVGXOCITMQ', props),
compute('m_5_7/2: ${c} WYURXXNZOUOYFPVUUSUJKJHCWMIRPEUVDKUYZVQXCGKFSFPRRVVVADIIKCFCZNFLPNFHQEXRYJKUKYXEILGETWPIJHLXAUAIMVYN', props),
compute('m_5_7/3: ${c} UKZGGZOAZKFKLAVHPIXEZGFNXSDSKAXZGUSZBAVHWQZVBZSSAXEJHVPURLZPLAWVSLDSASYXNTOHTGSJPCCZTTXPQQQMUCQYHLHG', props),
compute('m_5_7/4: ${c} GFAUYNFAXUUPDHDPFCPUDYQXIDJNBMPBBJFUNXSNZNLYQRUBRKXOBFBQCGIOWKCBPXGDDUEZNPWQEMPPJDPTEIQWQPHWKMBRGGNW', props),
compute('m_5_7/5: ${c} ZYCIOSZPPBWYPGBZICFRBSIXCEUCXZNROONAGJZGRQIKHHJNXYNUYLRZPGMSDDPLTWTECSHKJRFDUITNCDYKNGRFVODQEUZUTRBX', props),
compute('m_5_7/6: ${c} VDZABCINQENKFDHDIGBZXKRMQHHDUSGOJGZRADHHDVOBFHCQMGUDMGUOETMVRQHRCFAAZTCPHPSZWMDUXHROOXCFWUBUXYAHXFRD', props),
compute('m_5_7/7: ${c} UTWWXDIMIECBGUUDRFLJLCMIWBGYHHTFKFTRVKWQOZABMCZXEFHIXYHLXUPVBALWPUUIJAKPKBMEPRRPEMTQXMJWHRJDRNTZYGIE', props),
compute('m_5_7/8: ${c} OHCDLBPGHRGSZONDSALBAWEYQOTDXZNWJRDWGDFUOMIUKPSZVZHZRZLGXSEEFBEYMSODFPVUEDFDYYHIUORHBAPNBVWPNJUERTFX', props),
compute('m_5_7/9: ${c} JFWVTOVWVWEOIIPJQMMMPYRPXYDAFVAFKGGWRRJFYCIEIPZAYWWWZOJPEGBARXTPLMCSQNYVXWOJTVTSKNWQWAFMVESZZCMRQLHF', props),
compute('m_5_7/10: ${c} VFBVOTGKUMBQYBTELNQBBKAHTARKOJWQNLAQIKSBNBJHDGPAMBMMQRCCSWISSGTINKOBWTRGUQCZSQCIPTOEAPILCPRLVHPBYIKP', props),
compute('m_5_7/11: ${c} AVWYIGGSSPLVMEYLWEQBNAUOTJVMAOXCFTKDOJHYJCOIASPZZSUEEHHVENDBMDMDXKINMHSCTVCJHGTFDVZUJFBNPKYQZIYGIJIZ', props),
compute('m_5_7/12: ${c} LRTDQAJPSYJDVTCMPZGGHKOREZJMVHZOOMARGOPLSUUSGEDHANWHSGUSKDDHQQNIQKACUVIBGRSXLSVKHGZMIZQIPULBOHWNDELR', props),
compute('m_5_7/13: ${c} CFDWWOVEETWXQKUNBQMTJPJWZAAJLGKKXBBIHTRTWBSBOHZFXFTOVJSNGSMBELWCYIKZSLFUZKNGQPABNKLKPLPFHPNCBJWTDYVK', props),
compute('m_5_7/14: ${c} FLCOCISLUNCIYVGCEHDPHSWTRFIRMVKAFSPPVPNPWCBNRSUPYRNQIJOKTXCVFVZEYBXIDLBFHZBKUYSHBYMBRNZULDAERZBULYIC', props),
compute('m_5_7/15: ${c} WSRCHVIBLATQOYMTRZIIVKPRSICYORTTQUDELOXCFBMNMYLAUBQGFNSAHWSVPQXMQPWYGIDLJTGECOICBUCOSHJGHYLQANEDVDLR', props)
        ].join('\n');
      }
    