
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_13/1: ${c} FYLLNSLVMJUFPZIDGXVWJFVONFKYOVZSHFGRMJGZJXAXDPBDDHQYVFBWBMKVXMNEVKPIZIKXFRVDSQUSRPCUBYJWXQQJKYHZTCHJ', props),
compute('m_5_13/2: ${c} LYGHACSOOBMPLZUPAOAWOVHRWWBRRHONHYJOMRPGVIRUFLYLIAWZHTJYPGNAWXSDQAODQVORNCASCFWEMRKZNVMOYYMWAFODQMKG', props),
compute('m_5_13/3: ${c} ZSYMBVFWPGBZJOPVSOPFEJDORVYFASSLCRBRVUPDTXJHPUYACOLIPZGAKIBDFGPPOUKLGWSFQTXABGAYIXWVYUXMASNZIYXWKZBI', props),
compute('m_5_13/4: ${c} ZTKHHRRAMDXNSQRLWBGRKYTZDIAFYVPJJIHGSVLUDHJUQLKPKLSIRHNWRWDLZRGSKBBKFKGTLOISOHYWWXLAIWYNCQAKQYWKSQIQ', props),
compute('m_5_13/5: ${c} APAPQIIGZWGJSMTXQMCEIWPBPTYGKFHZZDUSTBXURZDLQWSFYZGQCZLESBVYYZXYSDFABAENSFCVGHGFUMEXFJMDMIIUDKACJKOP', props),
compute('m_5_13/6: ${c} OMKQRSYLVBBVYCHYJSRIVDLFTWTASUDHLACKQMTDMTLTGEZBTGNOTHVLGFOBGMUUOSECVTFPLMCBVIAIWWLDEOZQOYPBJWMIEXMV', props),
compute('m_5_13/7: ${c} ZGRCCHOIABQCEKNPNCGKPRYFUGIFVARUKXPUXZLDKBKGQOTOAEJMMREYDJWACWSJDSFDSVDFJEVJNOQXWHFZPGLASCHHDZOTBOHJ', props),
compute('m_5_13/8: ${c} LAKIMWDIKOGHPOUOQPXPUCXCDOTGYGGJPZBHCWZSRZCNSMXRVOHFLKKHSYVTMNXCIQMJIIVUCHICWIJXZDDDXQCAUYEADPJARSGO', props),
compute('m_5_13/9: ${c} KVABOEJOVEAGAUYKOSWXLZFOLIAMSQWYJRCUAONRAWWMWIRSJBWIKLTGTUSPXOMYRMZFAPINGKKCRKQILOJJOQYMMFAQMITCXNAZ', props),
compute('m_5_13/10: ${c} YVEUINJLECMYNPPIWDWWGDITMONUZPHXJHTCNLOLVNOKFANNETDHCXRULIXIIEDMRGPCBIIUWSUZCJWPCAQECSCAMYICMUXZHQMN', props),
compute('m_5_13/11: ${c} KBRAPGOCFEOZGAIIFYBEJPIMJOUGYVAMXXSEVIESVVNROYRJYIMJHSQGGVMELPDSWVOGTJBLRGMZNJGGWHWTSAKGVZHLIXFEJTJT', props),
compute('m_5_13/12: ${c} JIIKWHFCKFAJRJDQTLVGDNZPWXXIDBTMKTMAQDYUBABCDBNKSZCMFSHXIXRUAPNLBIZDTVXCXPFJEDNWRGHXMQJYYKJRTUQYMBBA', props),
compute('m_5_13/13: ${c} AQWJQHBOBNMGOAHTNZPLZXGWCGFVUXJMNFHDAQESQVEUXGAMLTKMWZZWGOFRZEQLSPLIFFDBUHZOKLUKIAYQZOWQBVPPDBLZVQZB', props),
compute('m_5_13/14: ${c} EWOEPNAMIPKWFIHIAZOXVLGPHMRAEDZYWAURHJFFJQXLOWVIYCEIUZKUTMAZYUHESWDXHWOYHYWIAEKVEZBSNCJPMIPIHMXZXHWL', props),
compute('m_5_13/15: ${c} ZYSSWVPJZJKBRKOBMYGPGRYASZNVVUDZSDURSZNTWHHWMYTPBVECLVVVCCSUFSKPQWJLVRBIYBRGHQPAMYOQDJCZLNKJITGZPWYS', props)
        ].join('\n');
      }
    