
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_19/1: ${c} GVDFAAQXZBTHITQDDIKEDVZYQUSUTTKGLCACWDCUMJRGBCMHCXZWWLYYPDMUERLKNZGOKSGXZEKQMRYSLBSSOTIEKSQYIECWFTVU', props),
compute('m_5_19/2: ${c} HAQCWPBMSKESSMIZMQMLVHAUKXRDHETWNDRXDSNPCQPKJOOHVOWEIZIUSJZOPAQLRVKZSDJFLCPAHAHSBRHJHIXWJITVHVQBZQNX', props),
compute('m_5_19/3: ${c} YXEKEQSSNOKXYMMFJZCHSPJXFHVDCXDOOMJRFKXIVEUWXTBQJHWIWQZSZYBEFQTBNHWWKAXYAAMJQLQGYEIYWQIJBCESWWDBPTRR', props),
compute('m_5_19/4: ${c} UDCXABWUBVEISUWHGUDXJGRGASNOBUZDDKLRGCBGIBMVLRTGBHZEABJZQSCOMBQRMSUMUGYEFGYEMRILXQDTUSZNPRLWWFNVLZOH', props),
compute('m_5_19/5: ${c} SCISLDEPOBXPXXZJWEUZTXVHFCHBUVIMODZCEFPODXXJZMYTZVLSHRGZSQVMMPIDUBDXPJNXDUGFSYDHTMLHVHAEMXYZLLGROPXY', props),
compute('m_5_19/6: ${c} ISLIKPIFGXSQPDLKFWATUFIEAVFXEVLWXZLEHEEIRSLTHCXUEJWLWUYVFAQMMYQSUEFLALKHRTBXCOZUYSIEWPGQFENZNICSIRIR', props),
compute('m_5_19/7: ${c} AEJANYDLVKBLSAFOUNKDFEBVSZYXZCPMEBIIVNRPKWQVLXKCEPRLJSAYPHOLWLKYWPANODZPPXIRLSQJDVWWOYHMSCYLBKFDJLGS', props),
compute('m_5_19/8: ${c} HWUAVGKGPIUINDNPDRVZUMIABNSFDKWQPGYMWSMYZENEVGBXCQNKGHHCMEGUQONBEYBMHAKHUJHDSGIEMFHUPRFYCDWVZFOQQIQJ', props),
compute('m_5_19/9: ${c} AKSAFHORSAVKZPVUSTKULLTXRHLJVGEWQJJDWQYHFUVYMQJVZNIMETDNQNTCJCZHUUVUSFIKWDUYUUZMIZEWKNNCWNYMTRWDOXKM', props),
compute('m_5_19/10: ${c} CYJQCWWHNNAEYQSYDZIFYDICFLUJSHVGFVWTGDNTVWMAOUTXFODCZDORGUPHTUXAOZITCPPCKGLEMNYXBEOFZFEFRKKPIYHRQSJQ', props),
compute('m_5_19/11: ${c} HYFWDPYODSEPGTTITPKOGHIDXAKDQUIDEBXDJVSFYVBCEWHNBWYSREVTRFLQVFBDVDWSMIVVMKHVCMDGHKQKLHXFLCABWHGESFKZ', props),
compute('m_5_19/12: ${c} AEYJQUNZWCRDFPTBZIOFSZPIFCJLMJDJPOPOTZTGPWQOAMSNYMLVAVMTWUQGEQIOCMDTIESMWGVXIPKVZJSKBIBPRQKQKRPIQFDL', props),
compute('m_5_19/13: ${c} VMJJCMGSSWMPGOUOFULLCUJRWIHGTYKDEDOBIMPXXCLLKQUSIWSXWGAVGCDIUCHCEEVNTCCUCJRBXYNZBDLXGXUMHGLVVCSZZCAI', props),
compute('m_5_19/14: ${c} OAWICALGPOLPLWUTSENUOFAGTUXDMPFHCUGSJKTBWFGGHULUGQATVAYJIEBKZMIKYLAGGDABWDJDRTJRKMQHKNYNYUYLRRQDEYED', props),
compute('m_5_19/15: ${c} LEJOHXSNGYCUTRVLCCPMFESCCUWBGXTQUWDIFJKUUMPWONQUPCMEUAAPXGHVPUFFTUXWCHICQQQXKEEGNSQROFHNPZYXZCSRONFB', props)
        ].join('\n');
      }
    