
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_9/1: ${c} RWBUKKQRNJWJZGYVVQXBLGMOQKPWOHEXIRJVNGBCGUDKJEVVHAPARDPKIZYCBGKEKGAHROKVCPXTWNRMDQUSWEQEYLNLJNTBYXKJ', props),
compute('m_5_9/2: ${c} ZOJGMWMHPKHLSWRJXFDTQFXCFIUGXRZUKTROXGIACVGRZFXWBNQEKQNEGLEITDPAFHOBIQGKLAZZCMRDCFTAGCLRRWYXMPAXAXLL', props),
compute('m_5_9/3: ${c} PIRKLTSWGNVYBFOAHPDDKEMLGSXMRBHIBKCPYELUXDXYPWQYMRMJGHXTRVVXSDWCGHPAWNPTCPGJYDYOFWHEKBSCLEEUAQCCHPFD', props),
compute('m_5_9/4: ${c} PEAECZAUEVTMOYIJMEUSEYIHBYJSLHCIRQSFPYFOIBHKHFMLPRDHXRDCMWJUNOZZRWSCDPBEDWPFJYVDLYFBQYNRKDVZBOMGAKUC', props),
compute('m_5_9/5: ${c} LAOQUKYSIRQTXKDMZZDYTUVIXDYDQGOYRQBRVANFLKRMVMZUUMXAZNYOHGLUSOWTZJWCDAYZFTCMHSSGADYQXMGVISVKOOUHVPNT', props),
compute('m_5_9/6: ${c} TUAJAUXAXEYTCBSFJEAJCANKVTMRDDVWBMTJWVUKPHFQBYERXKLTYXBYKAIBSMOZQJSKSNJTFIEZAWTCXEMDPBHXBRPICDERFOEA', props),
compute('m_5_9/7: ${c} DOGQBQGQRSAUKLUCTGBDTXQSURUHTJMXSKXWKDSNLTMYMSFOJZCZPXZJTNUFJFPLDKTBUYLUHPJJSJUIZTJIAUTZURGHVNCXBZTK', props),
compute('m_5_9/8: ${c} TDLHUHNWYVEAOLQMYUJACNKHTHOHITBRUHKFFWFYHCFNDCWOVSUAKONMHALNYPSIRRNJAMXNAFWVXWNKNAHSYPOFIAXCICHWEEWT', props),
compute('m_5_9/9: ${c} QGPEADJWQGHINDJURGNHWHOWVEHOEZAFCOYYGHPWCZJRPLLMBWRZOXNTCWENVEKAZFSEGORJJZIBHGHNQUIOSUVEYKDELPMQXSSK', props),
compute('m_5_9/10: ${c} YEHFLHQLWRZUVAMPDLWFMEWDEZICYTFOIVSCGKCEZLIAEGKRJKSQEHUEJCXEEIKJATUUMPHNPLAMOZCJWZEZNEDHMWCGPRONRQQD', props),
compute('m_5_9/11: ${c} OJKNINUPAFOUFWBNOOOSLZLESGWIMJPIYACPLYBXRMSRVNKGQMBKYAEDGVANOFPKRUKLILBAMLSLOHUPBHWOMYJWCALWTNDMQZKV', props),
compute('m_5_9/12: ${c} DLGLZMZKOLMYXNJYUEBZKSGLUUOPHEOCANIBDYOMIXGJIGWXRUTVSGPVVUJNYHILMLXPCFJOOYEOULNBQUPIEAGNIWTCJLGXPHHX', props),
compute('m_5_9/13: ${c} LCEPQNCZWHMXYIBQDBEOVFMXYQBRMZTOUQYXABZQSGYCRRQKABZDLROOBQIPGTQWOPPDUBZLBQTIZZBUXZOKRXLEBPXORSBMXXRE', props),
compute('m_5_9/14: ${c} MPREQZVAWYZIGFGWIAQJIPIYBMMNFGWIKKSSBCKPZYWRKPHBZYMTCCOZHVMPDSRMMTPXJRMLRKPRAFEBBBYFSDIDYOUZWSEVUNVE', props),
compute('m_5_9/15: ${c} KMQKNLNCLSSLMGQFNPQQBRHLBWULMSDAVYEPOXQRGDJPODQLRLDBBUIXVYTQIAFIGPIHWDHBSAXFYGKNKJGBURPFTWNDLSOUXGOV', props)
        ].join('\n');
      }
    