
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_10/1: ${c} WJHSAHONVVRZCVTLECIBYFCZSDMAKDIRZJTDNMHZNUCGISOWUTNXXRTOXXGMEYEUJOIEYSCHEOJSIPFAUVEXYGISQFIRHMXJOELS', props),
compute('m_5_10/2: ${c} NUUSLOPFVNJZVRQDFDIEZNOGXNLZEYUMIHHJSUAOHPQKLKTCZQBVNSIJEZQCREAIJJYVEDVGKEDYPTNMMCDMVDSJDJZZBKRHBQRE', props),
compute('m_5_10/3: ${c} HJTSPPNIWEJNSEVKCAVBYRLCGSXDBSYKVRTAGYKUZURQIPSXVITCJCKONHFIIOEKQDAEIBMQDRSHVWHDTLHIVDGWMZZRAMOTYLUC', props),
compute('m_5_10/4: ${c} NRHSVESIXFXGEGXXRLDJPIBYDPGRGVCNEIURYAOOFFSHKBBFPKNEATGMXVUVRXPPCEOTTVHGEPQSKCDOIPASSASKASLVKPUEKUHR', props),
compute('m_5_10/5: ${c} NEIXCQCHCZZNLQXIBGUSCOZVDUNBUAHBKTZNPLEQRQMWHAUCIXLFOLHTCKEDPXRYSQUOBVXDDDEPVUDYQBCMCDOVDFQILXILITTV', props),
compute('m_5_10/6: ${c} XLDUKUUYTPKYCUNORALINCFCCWYWABRDKRSZSDWPZWNHXBQIJVSKCFRKAXDLPZNMYUTJKCXXRXIDIYHOLAIQFJAPOGPBKRWZPGFL', props),
compute('m_5_10/7: ${c} JREXIOQHMZEKIMVIKRKGPGEFKCFRKKUZLNBZAYHWDLKVBHAMWIBYLNAGRHCFIKCDWBGXVNPBHBNMDLIOLGXGWARFITRMNABFJGXO', props),
compute('m_5_10/8: ${c} PNUHAOGOLWKIOYIXJQMAWPVYKJBNHFXJGHKDZXYCRJTMRHVERCNRKWQNBFQKMGUDQUXOTWDQZKYKXKGOYLARTPCJHLEIZRINSYET', props),
compute('m_5_10/9: ${c} HIYVMYYVSHIYIJYELXSOCLIOWNPYFOHMDQTYYMLRBYLNDIZIHQUHMIWGADNEUMUNDPIWKXVZAZGQVNOYKQKVDKNLGHBWVYXBLNUA', props),
compute('m_5_10/10: ${c} DWXGXMSOXGVWAEIMRLSLDRFRGHXOJDPVNMFWZGEVDIFXSLPEPPEPKOLSZWUEIXRFMAWUOVQXXPZOVQVAKAFGEIIRIAFBEEKXOALH', props),
compute('m_5_10/11: ${c} MNMJFCOSBDZPQAIZTHXOEYHGEJRNDPOHKXOFXPGCQNZAPMOAAIIMLZCTRUZUUMAIVXLQGGXXTBNBAUXTIYCSVQZNKHAOFJONEIEL', props),
compute('m_5_10/12: ${c} QQIHJKOYDPOMUXNZITPQPDHMZDKUHBCTPNTPZFPMGHEHAICIETDDWCXGEEQOQACPMSLPPEUUUVHLZDHDGXRYJZJGJBRCZLCNETFO', props),
compute('m_5_10/13: ${c} RNOJMDJBYLCPTYNAZSCOBETCRQRMCATUNBNAZFDHYLXFYMXTMZKUTCCMQJVYOWRJGFFJSXRPNUFLWGOPCPIEPCVNQSTPHPSPAHOH', props),
compute('m_5_10/14: ${c} QMWCZVXVUBSSLLXIYPXCDFZJQXVVMETHTMHTKDDVYPNGDPUQVWCAWNDSIWJWRZKYFXYSKZPVJOZEOIBNRRAHGDSJCWSLDKEZKFBH', props),
compute('m_5_10/15: ${c} RQHKCRDSNRXCFHTRBPALPPAMLLSKPJRFKAYMEINJENQEFUQFZWQGFCOUEICVZOUOOSOKKFJQVVCPHRDEZFORQTGUOZHNVTSVLUNJ', props)
        ].join('\n');
      }
    