
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_6/1: ${c} UZZAXVXBGUBMYRVWPRIDFSZMPDTQNCTBJAVRYXUNNJBXSGSQRSZDYBVYTIPVAPTCYIPCCJIIHMPVJHJPGYSGIEFLZUIUFIOQCSLG', props),
compute('m_5_6/2: ${c} RHPIEKOTWXEGZATKSWHTJUOJAMAAAPNGSTUHQAYMWXTZSEKHOKDSMKWILMBPDEGRAEMHPRLGKFBNXGWJKWMOQUKYEPQORACNLXIM', props),
compute('m_5_6/3: ${c} ZYUMMDJBKEXPMPHZBAFOWXXLLKAXLRBXVLUIRRXZGTPCOSNXACESZSAPRFLSYGZMZGLAUBCQUAPDJRSZAKEDXKFDEIISHJVUJDFK', props),
compute('m_5_6/4: ${c} KPQZVSDOZVYNWOGRGECWGJBCVWTVDHNXBNHREPBCHGZPSKFHGQYUORXNZIMCEFDSLGPMELRCDAZETLXYOYUAFKGQDIJPRFWSUWFX', props),
compute('m_5_6/5: ${c} SQBKMHSVEMEQQBSRFQGFIRUWZDXCPUMFABYBJNEKYIMXKGWFDAQDHAQACBXWETIIGPIZSQIGYPNCXRPDWLXJMVMBFWNFOIARJROJ', props),
compute('m_5_6/6: ${c} VWEKMKTXBEYEKJKJNPXDZSXYFJYQYIAWDWFHPRDOAGWOHQQLRDSEQSQMLYRSSIXZYRKXLRSIWKRQFLCBANDJDNLEAYIJWVGNIZLB', props),
compute('m_5_6/7: ${c} NERUEIDTNJAAFHDNLVIHZFROZTFTFXIPDLHXJEESAOCRGZVSFSDMCJXMRONJHKJXRNHWBHUMLUZQBUDFASZAWDFSNHFDKMEJCUMQ', props),
compute('m_5_6/8: ${c} XKTWPERKYLYRGFHXCIJFDHMFYYJTGOOSRIVBHKWVWPOMTZHLTJNHXLWQBPQDABFSEXCIAZEWVQCKNOLPHVUZWJLSMRGXURMQJNLY', props),
compute('m_5_6/9: ${c} INMOFFBERNDOBYDOFHSMHHQIJKBNAPFAZYATSHDRJCXPVRDGUCDHHLOLLZKWIHUISWXIGYAXBIMJRBNFEBNIFUEGRFHURDAAQGVC', props),
compute('m_5_6/10: ${c} RTRHEBVQOQPZQSCHGCASEJIGFQXNYKFNWZSFJOCXHKADKXTKOSRRHXLKLTODKMDVMWFJZEQXHHPGWWTXFPEYZZBTURWMEJUUZPBS', props),
compute('m_5_6/11: ${c} AJFNNHTNTXYJODHVRCVILTEWMAHKQLQLNHZPLPXRJCBVTBWJODDQSNGOWAZGIBUYOGYOSWCNZQUEQLKFZPUSOFOFPXLXFTEVCCFD', props),
compute('m_5_6/12: ${c} UKXPRTHQWNQROVVFTDSXLXGTBSUMTAEOUPUOKZDEMKKLQBYNAMFBQMHTLXAWLZEWVMRGTRDLKHZFJYCKRHFSKGDSLYRRBSILYGMS', props),
compute('m_5_6/13: ${c} LVAPCRJISCOZBSYQJGPZUJQEDSXBYQJWHUPJJPWDKSGCADLEVHYOFQYHZAEPQDFFIJPITRRVFFQYULQMEXXBNYTVKGTKJYVPMFFH', props),
compute('m_5_6/14: ${c} DDGXBBVKMVKWMJENQJYGBDMGUNQGGVZSLUSATJMSUNLBLMWQBHGAKTWHXQFHRBFSBVLZFMNZFSASYLRJLNJAWIAKHAYHGEBETXFA', props),
compute('m_5_6/15: ${c} MRJGUWBWFPZQHCBHIGPDRJWPCHYOHPZBCEHXUYQNTSWWHJRUXOSUVFOMOGTVNPMOKBTRVENAEZIAJBDKFJSKDIBDKKCMNKSKDHMK', props)
        ].join('\n');
      }
    