
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_8/1: ${c} BZPKMVISWDRZHUORIOUZGGUHUWHVIIRWWHKDOBAGWPIFMKEBTXZWMGGYCLJPADUWRFDIOHJNMBSJCBKIYBDKYYXQVSMVSYWQOOLT', props),
compute('m_5_8/2: ${c} XUACKWWRJGHEWAAYFGWWUDEXIQVJXVPLEUORZHITRLVGEKILHHDGXXEEVNHWLFKIZLUEBAGDLKDVZAZSDQZYQKZBPEBBXPKMAKZK', props),
compute('m_5_8/3: ${c} NLMQBMWYIXUIOMSXNZVUUEFOKYMZHEKVDJPUSLSQGUHNHGTPQDZPIXWQKSSRZADGWXDBTPWQVQHOSFNTKZNSWOYADHZXLVVXKTMC', props),
compute('m_5_8/4: ${c} PGVEFCZVYZQZVAJYOBSPTQDTCGSARKRJNIVBHWFXPKEYMPHWZNTVPLUDNHXKAHAUTTZOFUOAORJWRGIMBFHNOOZFXPGSGNTUZRUW', props),
compute('m_5_8/5: ${c} USNWUNSWUKAZBTDZIDTIAZOSDCJXMBFNUIEEGMFRIZGUJDZWQQRDCILRZFLUPCCOCPASYLGPDSTLKSVNXEEPHCBRAGQMJKVLUHPZ', props),
compute('m_5_8/6: ${c} ZZCJLBYPDJAWFRUGECOIKCBOTBVFJEXVXWELVZASZHXEUTMOOVWKMFYDLCGMAQUYVAORZSGYOXOBSJQLAVPXNKXFNZRRXIGIPRUD', props),
compute('m_5_8/7: ${c} TNXSCKJBLFBTWGGCPEXAGXQYTUFBRSJGWGDJKZTTMLOMZSVGYYVGLBIRWCUGRWISWVVQCBRMSZASGPTOHKKQPGTDYENVNNCFNDGH', props),
compute('m_5_8/8: ${c} CZDHHVOXCGHFJNWRBZUMNQATDYSFFNSJOCULVZQPPPTRYTBGVGXIJBXADDPIEKPOQUVALCSTFNRXCBCVILONNEUVSKFGIGKIADCM', props),
compute('m_5_8/9: ${c} XQYCZAYNZJYXLQROIYFHLXCXZHAXIICKQLWEIMMCDVTXGYQIWREZSGMBRNZXIEPJJSYMLTNXPVPRLBNYAIXSGXPHIGKNFCOOAWPK', props),
compute('m_5_8/10: ${c} CVUKHONYPVKYTBKIRCBDBBLGNTIQEUWKJZZFIGSEPBWHGHWHLLJZHVEEDUBEHIYJAETRFHMJZYWJRDCMXWJSHXXIENYMBVVWOTNZ', props),
compute('m_5_8/11: ${c} FNKPXZFDKNIGQYQTLZKFHCLIAMBULLCFKIEUHAWGUDIHBUENHGBZBFAJIIWHJREQFNMKEUAGSHVWGGPDZXXUHNEOTOPXIECIFLSV', props),
compute('m_5_8/12: ${c} JAARTDHHBHIBLOQWDNLGFLCGPNAECUDEGARTAZASQRDBYDDKPVQALPBVNTJVCIDOPYLFAXJJZCEEGKHWQJLVSBZXBZLIEVKYLGKN', props),
compute('m_5_8/13: ${c} QNVTUELAFFSLIAQSGQMORXUMPRTQXSCMLGWNSCRUTKDSLHKPIPIVXUJNGSZGEMWRIBJUVDRRDPERAGQCFIOUNEGNEVSCYQLCMRSA', props),
compute('m_5_8/14: ${c} MWXUHLQLCLRRVZCBLNAJDRYTIGWAKHHPUWSBLNHKLYFBNFTRVLZPPTEMSXSSHGFFRENWJFEHMBMQZIXNJXGJRNEHCBEFEDMYXCPU', props),
compute('m_5_8/15: ${c} LPAFPYHYPCDHYMUCUYAGTOTYFOEPOXECZPSWURATQBNVERTCZNFPRFYJHGAJKWUGWXAEPGYJZPYJPVBCECJJAPNJXANPGLVPAIGX', props)
        ].join('\n');
      }
    