
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_5_11/1: ${c} IGLNVZJYVNTUWYNBSBLKLQYLIIOHULWNZHEDIPAPWUMPVZICAOAKNUSYPXXATCSRBHYTGQDZAQOFKWTQUNDUASSGMBOZRBXPDYEN', props),
compute('m_5_11/2: ${c} NWHFPVRAEELPWGNQIXAFAEPKGPBXNWDSJLFUPCXSFOXOAUAAUHEWJACDTCJULXNKLNCLOMRMSBPYOQDTHHAJCHFJPJZEIBWRYEUM', props),
compute('m_5_11/3: ${c} GWOOEKSHARHZEMAEFSQELYIGOPHCKDDDOSXBNTHYAPOZMDKTQPGYAHVUPBJFJFABCLIPGLEREHYQRFUSCPLEQJSAGVVJQZLNKPVW', props),
compute('m_5_11/4: ${c} TXLUBLHZGEXDCJOHKZHKOAPLRIRNVFFROMBVQOUUVOVKIYRLKTNKYAQRSQJHDPGYDIATPWOTYDRPFXEEDRBIFHBYSKAEDYEXRPPE', props),
compute('m_5_11/5: ${c} FTKXHJWJCLTANZHMSSLSIWZSMQHEERBOIOGUMCPJGQDNOPGNNIXXLWQCAFLYUNNXODAJZGWANBVXLZYLONFUFEJXONXUNZRWFMXM', props),
compute('m_5_11/6: ${c} RICQNJRTWSOAQGNGPXTDNEUEZNZQGDNBXRWRGROYZUJZPSQMIKPNNLHEBGLBMISWQPHKZVBFSMQZTTFMSKPHXIXNRMKMBGAPZWMD', props),
compute('m_5_11/7: ${c} OCZEUZWAXIVGHXQLEYJHHOQEYGZPWKGGLZLBWTTEHNEFKEWVTSODBEHFNPPBJOQMTANJOAYLBYNWMEGOYCJNTPGFHRTCUKYRJGCT', props),
compute('m_5_11/8: ${c} IFGHURLJEOEYBNACSGKMQXRKTUVQUJMLBYHIXXWBHNMAHJDOPUWRYMKWLCJTUORPEWRHCMFIZQGAQOCBJAAMTIDPOTDNHOYHAOHM', props),
compute('m_5_11/9: ${c} IMEQUHVLIMDQQPPHQYYSPBRBCRPREECLGFAPLSFAUVRQBAWUFVIGNZBPUSDICVPMBRCXOPXUBDEZYXSNOEIULJMEKKSDNBJNVJQL', props),
compute('m_5_11/10: ${c} IBDWOPLKTAORPDKYEMCBWYCBWJBGMIHTUVOOYJJGRVNBBNKLWPQYDKROSBWIHZSZKBUNUKIQDHSRVKFWKGZDWQJHBWWKCMEMFPIC', props),
compute('m_5_11/11: ${c} DIUIAZUGHMRYGSHTYWTYYPLAGZMZPHLDZCKXAMNEFVHFYSQPHYNOXIFILFBBOWAIAMEYJTJWGIQPVNZUFCPMYHDHRRTVUVWLFQJX', props),
compute('m_5_11/12: ${c} PCGYKFHYHVOIWTYKGIUFVYGPNYIUYTIWNXETWYLPSTTGVJIYOUVYBUVCORRCSQQAONWMUTABSLJHDOTEKEPBVVWNZLXBBYYEIMVT', props),
compute('m_5_11/13: ${c} PUGTEDVTCBNQEQOXJASVAXCANQXVJKUDYYKSESVSZEBCWKETTLPGFJYCIKTEUUIYKVICPHUQLDNWLSPZMUPEDQMPBISOIBKLGCZO', props),
compute('m_5_11/14: ${c} VELCDUAIHOYAFABOMYUCTPVCJFLCNLGOTHCRLWBWJUNJREJUUWHZYTFKZTMTFAVRLVSHZWGCHZAXAWWKVHEGWJBVYOMGGWGWCOAX', props),
compute('m_5_11/15: ${c} TXKZVJSGWRGIZNIVFTKEWXPQNHHFDXMKYNZARZEPICEZQTPRCNDBRNPVLFCZMTDECXOEXLXMNBJFITGYXVOXITWFBSQKYYYXAFGD', props)
        ].join('\n');
      }
    