
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_7/1: ${c} IXBUFNMZXYKOALLONQZUPCKCPJXHQXFABOSLWPTZMFZRKDCCOSULHZQYXUYEFIXUBMLQOZOKOBDOSGKGGJIXGHAPRHPLCNXGACMC', props),
compute('m_6_7/2: ${c} DWPWTBFXEACRCTTAMMOQNWPQCBHQKBRZZAFCLPTRQENZBLKAGGAFKLCNWGALVCOHRSRNVDUZNMEBKWCTUAHCXZJRXNMUUELLXOYI', props),
compute('m_6_7/3: ${c} STSNUYWWUMCYXVRKHXHCJOMWVNDYZUCQZWMKWVYWEOCMDPTTWJBNJKXNPVLUXECSOZLEJJJBXRKRHKGRWVLTCEDFEKOGUXGLEGEC', props),
compute('m_6_7/4: ${c} ZVFTBJKLIKMPCERVZOSFCMSCCFVKUQPJGSUFWCYSOEBARRMBRULPCQADIBGCJCEHZZPBVZYOWCTIGVRKZAKDAJEUWUNVPTYQVSCT', props),
compute('m_6_7/5: ${c} OXBCMVSSQQNJNDTQCBYQWZVHHKOHNGXUQUYDFFJZZSHSREMCJXSBFIWHEIDKZMGVVERWWJDGYZZSXSFDNBFPUOJAZKIINHXYNFQD', props),
compute('m_6_7/6: ${c} XSHDRNPHIQAPKOSYIHZRFYYPMLYJXEVRMQHADYKEXOZEXNMFAUVTKFQVVYJXOCUDNGHVFDDEONQHVGRTDIAUSSSIYOTWKGBPYHSS', props),
compute('m_6_7/7: ${c} JTFWBFFDOQERWWBEAXDUCEAOXWMCVKOCMJEKRWZBMJTVUBRKTCOYNZGGNPOXUUKIFLSWVPCPMDIRVBJNTJXPZOWTSUZQRBZRWGZQ', props),
compute('m_6_7/8: ${c} UWBYXDKOUXYQTAJPFRTWNFYLJTYUAQQGSTVOUKQEDYHCHXRXDVIKRLEFXQQRMGYEIPWGZBDSBFDYFRXXVQJBTFXDGCYZNIXSUSKW', props),
compute('m_6_7/9: ${c} ELFVBFYCAWQTMEMASQDQZLPLAAZLREJZZWBVKOUXPYJRNVWZVZXGTTKYAYFQKIKAKHBZSJRLHXCKCBUJJHPFTUOOXUPENFFWTAWW', props),
compute('m_6_7/10: ${c} ZNWLBFGPBSAKDUNEQPMDZUYQRZNQEFZGTKNBFWUNWGIWNZBCYDMDEBAMMEBRUOTPUMPNAGKVWOZMTPWBUHYUXHFEYTXMNNGNBWQX', props),
compute('m_6_7/11: ${c} TTTRPBXZLWPBHPKQOGSBKGDQGRGRGMYSIXKIWBTKYGKIYCVSFEFMYXSBBGQWNGRBOBINOJEDPSEKTFYUMYSEEYEAKRDPJKMOKNAQ', props),
compute('m_6_7/12: ${c} MENLYVQFIEBUMNAQYPYYTPYCQTERADZPBRGYPHMJOOQSREEWRPXADIOYUPHGOKZFYRALVLRHQCEGFXEMUTJRPBDJLCWRBQPGMGBS', props),
compute('m_6_7/13: ${c} DUFXKFIJWAXWNGCCYJOQOHZJLGSKEJEWZLQRUKNWGXOVVAUGWIDTWLATHWJRTDZUTVZDCFAUMBSMPZHUGZQOVCXTKQEOGMIKHVZB', props),
compute('m_6_7/14: ${c} MCIRHMTYZOHVRFCUZHBJRTFMSQCEBVSPCVQIHDDVJTZXCALRSUESVSMERPZASTNRHYSZQTWEZAREPBAIRJYMOPRQGZSQXPHNAKEJ', props),
compute('m_6_7/15: ${c} MJTWOGRMLJDTESECJWOBIHAHBHOXFXQQPWATZTHTRPRDLMMOWGKSIJLKBSOOETGKNIALDFZVJOVRUZAOWSVMDBIRIRPDAYUUQNJR', props)
        ].join('\n');
      }
    