
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_12/1: ${c} KTBQYOCBWFKXAMJTDZZWUYDMCISIXSAFRCLBHEIQTUIDXDOPKGJAPZLBDCJDFEQKOCYXTJDIEZTUUAWYFEWEMPKPEFYXHVGYQHRI', props),
compute('m_6_12/2: ${c} KIHREHCGPQUNMKVHHXYYFMXBSCZCAGVPGEWLPXAOXUJASVQCWFXGYQYODPOTKRWMKIRMECDYVLYSBORPGNGMUXLPPHKPACXSGDLF', props),
compute('m_6_12/3: ${c} EOBJSHAEIRIGBZYRTYOXUMPZXWOXGUGJBWYYANOBSXDKBVMTWKGWPXDGBMHCVBUYGSSZOYYYVTIILGGPNPUNRIINMHAEWSLLSCUG', props),
compute('m_6_12/4: ${c} EKYTWQLRGYPNQYAZSWVLFRMWMTNVAZMJRBEMOIVYJSOKKTKGIJSYHXHTKWBDZIINOWHFMAINOTMRIJFKLOVECKATFDJCCKLWFNNN', props),
compute('m_6_12/5: ${c} FBRXPPTKOZAFRDUMIMWOCBJZPVAEQLCYCVJELVINXXODFQAGGHJSUZAVVZCHJPGEJIIBYDCICBLKNFWTWLNMNJPQZOTNACNWSEOK', props),
compute('m_6_12/6: ${c} OSOQWNJDTJQJRCXQNYWBUZMLZYCWOQAMZQGBJOFTLHXVQYWTYYICQVNAOQNYSONNNGWCGGUIWZSKHCMGICSGRLVDMQXMHWNLVQXA', props),
compute('m_6_12/7: ${c} WZKFISXEDXDLHNYNAKBQVGZFTSOWYNTAJOLJDHIKXYKUBZCKYCQNQKOHKFCZLNOCFUWSVXYUAPOCWSGREXSABEPNYNEUJAZIGBZV', props),
compute('m_6_12/8: ${c} IVXAXOSIUFZYJHFIUSOTZWTLURBXGGIJHDZLBRADYKBJRUUWJRCBVRYZTHXSTCZOVMRAABQLCPSEJSYZGZTSEINTUIBPOHIMBNPJ', props),
compute('m_6_12/9: ${c} YSZGLXJMJESMRFLYHOGZYJICVTIGJCLWJHEPWGNVYIGMPLCRCLVOECYVYTPOTBGVXQSXHGPEIWJJYGQXGHUVLHTOHRCXAUAQPTOV', props),
compute('m_6_12/10: ${c} GFHXODFXSSUFHKGTXHLCPQYETJWSQZMVMKVXTOBKDTHTLCGENZCDXGOYEJYJHQTXUMGIUXMQLZIWUUNVSXRIFJYURHQNOXWXAZVD', props),
compute('m_6_12/11: ${c} KEGYOHNYIVATXMVLUKEORYOHSSFYPHRBTGLITDRHIDXWURTXQNDEQALPULTPPYSCNYORUZFTGXVMRXYHFMTYZTNJIYNTWKQSODSV', props),
compute('m_6_12/12: ${c} UGSRCFXIJDURGZIRJMLMFJZKBCNFMLYOGOISPSMWHFKKTPZEGREZBRNNRFIEBSSYJKMNRZXYOIIPABBUBSEYCQJCBCJGXSIHLODJ', props),
compute('m_6_12/13: ${c} AUTIYMOFPWXJJCCCXRARPKEEFHJLNNYVIGLSIMZXENYKIRVYUTZJIKNWDKJEUAZWFOICIRBQCUVLWKWNPAUEVJPYIRUJMPLYLANT', props),
compute('m_6_12/14: ${c} NQXSVKAXLMQJZEJOOYMGYKOWHZPQQTBQHWLXATEMYTLMXJGLSMHQCVMFNVOYZHVAXOEDVHICXSZMDDKRQAQSINMFLGZIWVFGUUTQ', props),
compute('m_6_12/15: ${c} UOXEPBUKABTBUVFUMYAJCZHPJZCIJMETEUSXVWMALGUJVDYTKFBGAJPYEXQNMMJFRJBQLQKGANDYCRLOKMGHNNWZDMUCJZEVUTCV', props)
        ].join('\n');
      }
    