
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_10/1: ${c} BGQCVRCSSTBMQQQKEXUMKUQFQAILYFTUNDJLERPWTDYWKTNAOQFXSDOCXZKJEJZUYSFCNZWLAAWSOABCAAOWVBWUNZFKGMDUKZJS', props),
compute('m_6_10/2: ${c} TCRXIXHQJCVQDBIBCTRDYBBYRJQWQTMTZIFHDAVOYBCYQJZMRFUYUOQOZHZJRZMFPPLAXXALNIAARRJQPGOAMLXXFRBILVQQWFUT', props),
compute('m_6_10/3: ${c} MZYMVXQUDPYHLLSZPFTYDNBNTPTHPMNIGCVDMIYCBLXURIXNJPXBKJQTTFTTPHHGZHYWMKXIHMLDFSCASSKLEYZRPUXVWFCSNQTC', props),
compute('m_6_10/4: ${c} HWGAWMMBWZKDAQAXJGFNPEDPSWVBJDZOQXYGSXIEUAJXZAVFFHCZDARKAIKCLBSZSCQRAJLEPNQIGWYJLZUWLZLOUWAYAGMNOQBF', props),
compute('m_6_10/5: ${c} QLUXBCHPCYXGHHAIXJZSOSTCGGORQPVLEEJKMAKSNNNVDLSFWABYMCLGAGEPJBKAQLVDPRJSMAZQNVFWUTCHFSESKMZNAMPTJZKH', props),
compute('m_6_10/6: ${c} YKGGVOHKVWYODEALRFVBNFSJGWHJKXDIPHNOQTCBKIGOMUTOOSAQDYYORZWOEOHVIQEONDSQNZABXZCLNNYRLIVMFVNOYQFWOLSF', props),
compute('m_6_10/7: ${c} JNELNZQDHDVNQJNOLISWIJLUPDTNCVINWFXJRLEDMPGZWUOQKWVPLTUGYDKKSRVBLHDBWOLEHKDRDDGHDLXVAWBHTPKWAMDGUNKL', props),
compute('m_6_10/8: ${c} TCIXTFGYOTWMWANJRGXAWHLFJLXBDHHNNIGMIQGDUZFPOCBLDIKUFTPMRUNPSOUCRLBSGWQMVMKFMPSPFJRAIEKLUSTTTKPLRCXN', props),
compute('m_6_10/9: ${c} YMGWPPKXXHBQJHRTZZBZRUNXUWQCJEUJCHYENNWDBNQYUAQTPKAAJDHDJGSZPUWUILCHWOTJGOMFVRALDZKVKPKEXPXFOVWYLTBC', props),
compute('m_6_10/10: ${c} OZLZTXPSFTAXXKDLPLPXKBXIYCNPKLPQPRTZYEUSYGZWWJNGWLRPEULODSDKYXXRKXSFAFNRICYFPZABHEANHTXTVMOGKFNDDMGZ', props),
compute('m_6_10/11: ${c} ZQWNAOYGMXUBNDSGXDAVCFWIPMIVJSXINAQJDPQVNBHDOWSEOHODIJHPWPDMXQDGMXPVFHCBTUXXSAOSUNXCCAFCAQYYTCSGWJAQ', props),
compute('m_6_10/12: ${c} HCHUSFEOIIOKRXFSJABPZNSOMZHLLLKVURKURKIIVYIPNDYNMWRSZWDGPGGEJWPVPAUPKBMKGSDGISPVSJTHKSDSCTXYTQKBSSDP', props),
compute('m_6_10/13: ${c} EQXTWGXPDDGQJBLMVFSNONADPFVQBDFCLWTDFWCSDXMFBNLHXZRPSDIRFINQPEEHCHTOUQKTXEOGFZDDANVWTSYIGKGSJZKXCDKP', props),
compute('m_6_10/14: ${c} RMAADKMYJPDMMWXUDZWSAGSWJSETMSCCGBOFNRSHRRDIMRFWMQCDXCARUWTAIWCZYWRPSOCHGBPARPDVELIYTRLONYHDFKAOMLKZ', props),
compute('m_6_10/15: ${c} WXFLIWKKKCQUYAKLZFYVGMRIWONYHLXJRRUIIUDMWXCZMLDEYPNDGCZVVSLHDYUMTBBFFAWKUBRXWIBAURVBXMSVCKCJTQLZEDRE', props)
        ].join('\n');
      }
    