
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_9/1: ${c} ZUWBOXFUCQTDLDQECUTXENYGYMWQGKCCBTYAWVNFLKAFPZHWVWBDOZIMRYPQMXLBSYNZQUETGUUJSYFMTWRJYZINTGCLPVLHOGWW', props),
compute('m_6_9/2: ${c} DYDUSPOUWBBIQMYZPVDGGFHDDIHDNUTTCYLOXHYDNCUPYEXXYGBZNGFNFGJOLTLWECPNWLUYOANUMIKWDFKYWBTZXCFYDJOJEZAN', props),
compute('m_6_9/3: ${c} IMQJHTFWRCKTEIESFCKDDKZSULFNHYSZMVQPPLKYEWZVEJYKEBFZFUJNVRRQTNZPPVSSEUNDRAYFAVJLJYPQEAECTGAYLRZIQMWK', props),
compute('m_6_9/4: ${c} HDMMMZAHOTWMIXIWACHSVUNBYCJIOWCKQKJTTFUHYOCUOOLGDOVEGEIWJQKADHONGZDVASRCHNYFAKILKIVGOVCROVJWLVFCBZFB', props),
compute('m_6_9/5: ${c} UTRKNXFVXEFYYVVLPYMNJYMGCOUQEMJXYOUBFLPNNUAGHVAZIRVYKYZPEHWGNNGIRITBVGRALBAQNTPYGBICOQXLLREHSHWDPYMJ', props),
compute('m_6_9/6: ${c} GXXASYJNQRMFDFGGPGXPBFQFKLYZAFRIRABPIIIKEQQCQTCWKDWUMRKKYSMMVQFLYAWNPCBNMGFYGYJROQQSFLPDYSGFQRTTTPEU', props),
compute('m_6_9/7: ${c} FKLKPTGLTVPHJTGNGIUJFLNACRVBXGOXKTWRELBPHRRFVNQXWWAKEVGXXOMZUOFGBLRAULNUJFVGHLLBHGXEWVUXHLJHWHSTISMR', props),
compute('m_6_9/8: ${c} NKSRSZQOOCGAOMWHKSVDJWWJOMFWWJGKYMEPITKTOKSDREYWLXCGGBAFARWQVZYHHGWPFBDNSCAZRUFGDYGSHABUXFXGEODODYMP', props),
compute('m_6_9/9: ${c} HPRQLDRPTNJSAYZFCHGGHARELEZJATTOYVJWVRMONYFOYNEQNAEVWQCDGKIMPSMHTWLJJCAQUQKAHFERWNTPKBVMFHJMYHSXRMNL', props),
compute('m_6_9/10: ${c} YAATZRZRFAHAKXLDHHSPSURAHATNNVKEVWNLIQYCJBPSKVTEAGETEHSIYXNUMFLJKNOFUGIUDYUOECZTUDDNBGGRFDKCWFGJGZQE', props),
compute('m_6_9/11: ${c} NTDYEIXFIMNWVFXYKMPOTQUEEUKFHUAORKQFZNXRQWJVUREGAZXHRGCQZKJDJVTMXAUBPBSWIMDGEYORTFBDRBEGZPBMLEAWEGXM', props),
compute('m_6_9/12: ${c} IRNQPCPOBCDJBWMYOWCYZDJZZZGHZHDWPZOUKXPWWNHWWWQHYQFAYJSLUAVEQFGJCGAYIXKBWMADLETERQKZUZIPMLKDOOWLFDAD', props),
compute('m_6_9/13: ${c} BFJZDOYWYCHQBNXORSHMGNBXVZMADYEDPWEWXKZGQMSRSJNAWSZUGVTSIGCGDOOSVHREVWZKOSZNEKXPTXKYZPBEFNBIKFDUQAQM', props),
compute('m_6_9/14: ${c} YFVOCXHHXNPULWXNTOSCSFDVRYEAWGHIBQNQHZVLZHWSRJGBMBHCZSFXPNTFKIJKKKAKBCSEFVWBQQXXXPKJMZWRZACNZMPRBAJR', props),
compute('m_6_9/15: ${c} TXWDLVMSYSZOPFYLCKEMRLKFFFWQOYWOWHJWMRBSAQDMRBRHXETDDVJDUYARVTCJAMQFVTHFULSKAWJDHLNVGDLJOWRVACFGUEUB', props)
        ].join('\n');
      }
    