
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_19/1: ${c} BDAEDWWOPHVLPNVTXFFZQKTKXADFWIPODPHOQGNXBGKYAJMCHXEFXITXQRETETCVZZBDUZKWHGCEQTBFQVFPKTLCHHMUNRMNUKJX', props),
compute('m_6_19/2: ${c} SNOQRTCKNJRIZMIYBAZBRZLCLVSFBNUYAIBHTBLBSUEFGGLEHBIJOANJJBMNPRODTGDCMVNMSFTTDHOIAUKOCNCVIKHSAVHXLVZM', props),
compute('m_6_19/3: ${c} GAYSBAYYCKIKAKNENZROGQYLCJAPQHKBLSUYYAEVNMGZPOYIRPMVOLCJUWQKXWBRFTELFEDQERNVSDCAVXHJNZWRLZMIENOUSRPP', props),
compute('m_6_19/4: ${c} ZMZCWALBJTUOLYWSYCKCELKLBXFHFEVSUKCLCFVHYDWXUIRTJKSEQMHLTDFVXANBBCJBUAPLJEKQABQHJHROQKEZHMQQHKPZQJRC', props),
compute('m_6_19/5: ${c} BAQESXSVCWLSOMWKCKVSWSXOGDIIOYBLYZXZGXBNKEQBAOZRBVXHIBWQQDWYGDYDYANJIOHLFTUHKDGUVDQPHYFTTXFHYPDPMYJD', props),
compute('m_6_19/6: ${c} BZDXRKIYTSPBBSXGILUTSPGYXZQCHEZCOGWEFYEOERTJOIZLNUPUZHJJZXPVWWNEOROYEAJMLEKUVNAUXVTDBHGWLWMAYCHKSBRL', props),
compute('m_6_19/7: ${c} WNJEUNPOWHANZJSPVPEDAQXLBMRLAGSZGEMWKRSLCBYMCUSZDWJUYSSSALJODSPWTBIDJIVDEOJNBKEKLXWWXMEZSZQPANEEBZJW', props),
compute('m_6_19/8: ${c} HFGPWWGFRMIQVSQAUBWBHWBICRUBPINFUIKJBIXBHILJOQZFQUKKMIZJXCJUPZUGLJFJJFKFNCARMRYQCDXMKKNFACZWNQMYVGVO', props),
compute('m_6_19/9: ${c} ZBLZCPWMNBOAVMTUMZJADRECRGQSXMBYDBAHHTCBAHJGJRRXMJBXOYTKIFQZSKHHFKKAWRSKIESOPUSBMHZTUWOSYHTGPNKJJLOL', props),
compute('m_6_19/10: ${c} TOGLEKZVSNIQUFBZRYOAXATUVLUGWEBISKSFUVPPRXMGKFYYVFCYKCEJGJKDPPHJPMWAKROLIDIQVYSSRLICIGAUOJNOQODDTHOP', props),
compute('m_6_19/11: ${c} JMOMZQVDWJWYAHCNOWYMEGOBEXIXHDTECZYHGTONEWBTHJWJKBURLVWTEJCCOPWEOWNNSCTKVJQLYYZXUIGZXIDGIWRTQAYCYYUS', props),
compute('m_6_19/12: ${c} MPDLUYYLBQTEOXWIQBGGYKSRGBZYPLJJYHRPZMLREQTAVBMAFVJAQTOVZQCESPJFVQSXYNYKVOJVPVNMNKVCJVBHQFCKIEMWVLSC', props),
compute('m_6_19/13: ${c} BTFUKYVADWBOLNZAIGXPAIDVEODWFOTJRTWKNFGDNBKZXFPPHGHCFVIZIVDVEOIVBDWAATUUOKIUGCBGAGZHNXQXMXZIKQJPSSFS', props),
compute('m_6_19/14: ${c} EYDZLJOPHSIIWOOJDRSINKJMHRXDIZEXRLNAWZXMOGFHQUPQSOITLUAGYDFYPYUXDISZTEMLUOOYOIQJMRYXDROJQNFWQDVJOYDP', props),
compute('m_6_19/15: ${c} YBODEBDOOAPXMMEAMAMDOWOPXWDYGSNUKCPMHQSZFZQYLNODWEKVDSPZAUFIGSRMWMHVWMAJCCJDCWJNLYPZUAHPIVKFUSOKHEOE', props)
        ].join('\n');
      }
    