
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_18/1: ${c} YYVDANPFJOFQZHRQNCIJNOOLSPIZCAOFBHZDVAUBXFIBZTZMQHXCPRYKMXVQRIZGETPTVWLVGQDJPJXQSLSHSIGGKNGZWCCANFEM', props),
compute('m_6_18/2: ${c} ISAOFLSSYJDJLZMZKMNXGRKHSWMOXWJDDIHEMDRIKAQGCGTENRAUPOUMOPUPDSMFIEWOEJMEXAALUXYCZAMMRPNGXOANCBCNLQNX', props),
compute('m_6_18/3: ${c} VMTTDQHZVVPDLNVDPPNJSCFZKGKAMZUHAAIOKHQVCPRCPCDDNXXFOSSIPIULBYVFXIWUVXRTFVLXCIPYSPSOCCXUNRZMMKZLQSXZ', props),
compute('m_6_18/4: ${c} HUERBSTULRJNXMQLULWPETLENCHYIQLLSANSIVALHNQHRWIBAUYDYVVPIZNLUVXKTHKJPKHRNPLQAGTUOHQNWCPQSAVGLHZQCMSA', props),
compute('m_6_18/5: ${c} GPQUCFKFLDKFFWVBILVMNQLIOKXKRWNKNHFNLUFEDOZRPHUKWLZZVRBZOHERVNLERCLLOWZOUXIPGZOODPXMWYPSYKQHEQOILLMM', props),
compute('m_6_18/6: ${c} RRBFMYSTURJEPXXQAOMIUYNGKVMRYMCNKDBESMQKQTKUUSPBVEXSDIKTYIHPOLTIUJHJUJVUBTWOUIONTAURYPHHMKDPRJRCSZIS', props),
compute('m_6_18/7: ${c} VCAUPPYQAJULSYOJKUXZPZLMQLLZRGPAQTPULDUWURXFQJNBASIPYRBDJVRPCVBLEUFRIUIFDNDVOVQYCSMPMEXDXVSASQGOIPTT', props),
compute('m_6_18/8: ${c} HCZSXGTNWKEYUZUBSVNYWTYMPCRJTDIXATYTMCTFNKZZXRLGRCSRNLJTUXRXLQYEUBWBQANFPOJPRVXIERYWRZTISBNBYZSKINAH', props),
compute('m_6_18/9: ${c} VSXZPGQBIWSFEDJQOZMBRCRDCULILFVOMFFKAYGMALZSFTNDGBLJHUHEIFQREYBEQNKBBGQVNEPHAGQVRWYHLKEHNNVHWGQQBMBW', props),
compute('m_6_18/10: ${c} HBRGYSYCRIFXFNOQEWIRUWCZVZEMMFMFLBCZNUFNFVYEDOCCHIHYINLYBPVVRUIZLGMROVQLTUMLTFSIRIZTEFNFBGGNNBOQWHYY', props),
compute('m_6_18/11: ${c} HEFWVWMARBKQMWYQOJQMLKXVUSUKBPSXAUWZYJWUDLNSBLYJRLXAWLZAPKFYJKDMWOHLJVTSLAMWZHKSZJSFMFOUPWVSLBQWUXZB', props),
compute('m_6_18/12: ${c} XRYICMNJCONRFDOAAGQMLUZVWGVENGONIFLCOJBMVWZDKNGXEQOQYIRWXCRSZLWPAPQVNTEHAIGTMQFDXDDFHXRGJJCPOOLNDCZT', props),
compute('m_6_18/13: ${c} GNDGVKMNCKSNHHYYQSDWUPMPKDXWKADKTIAVKIKGUISMWJVDMODQGTAISTVAWKRTCYRTMZGMNWINJQFPTGGLBWLVEJSUYWQULRKE', props),
compute('m_6_18/14: ${c} IOKGGWIXUVIKLUEIAQNLQTBTFPSCUSPGYLHOBZWBKLLFOYJROAHFDSTEXMJLFMRMYWZOEFYYAOSMRIUGIXLWLVZJHHNYIVXPIJVQ', props),
compute('m_6_18/15: ${c} KWSQNEESUQOYBINKZLZIFKORNSHBPLLMWIIIUEIFQGQPGAKMSIEQENZFGVJXTIKZDZMEBRRLENOHOMUOZFLJOELASOYXOYWSQOXW', props)
        ].join('\n');
      }
    