
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_11/1: ${c} ZMWNHYHNGSIJEIOHEILFCKKANHKZPHUVUQWIVXAEONCVHZGUTQOCKETBHJVVMKHGIWYQKGCMXPIZHBITZIXMHDQKNWWFVWTZMZCD', props),
compute('m_6_11/2: ${c} JZVZAUXULWWPYCUYRZYESEGMCJXADBBDYPOYXSIUMNXDOKYRSYRFFDQCYCXUIERDYCJSPZLCUJZMNNDACWOSSGBELLCAXZBHZKSU', props),
compute('m_6_11/3: ${c} TCNLKTDIRIBNVXEMYCPMBIIHAMHRQESGHKPHDRWPNCIXANEQQHKYMCOOTNVLHLFQKJHMNTWXQDGFMLZTPTKXUIDUECPQMGOWPJWR', props),
compute('m_6_11/4: ${c} EKVLZXZQXQCTJRRDRIVHNDMWEHWPKHUSHSQQMQLUXINUXWBTTISIPMEAJRSXPARMUUQZYROYXJOKCRCGGQZODKSDTZVJNSBCLBZS', props),
compute('m_6_11/5: ${c} EUBUHMRZDNAHODTYHSKOEYVZLEAAFYBXPASOWFALFHGHHSWLATIHTUQXAGOCGFBGEFXGFKJTKVHFNIJMDTLORADCHUQWQXPNLSVN', props),
compute('m_6_11/6: ${c} EPQVYCEGMREZLIBCFINZASMVKNCHUDMKVYYALWOULLKQBIVFHDBUJUVCVPDTMLBGSBHCSSGMYTFTVRUNMJDNBTPLNAAXHPRHUTZW', props),
compute('m_6_11/7: ${c} QHKMMRJYIKOPSTTTJYBEPWHDIPYFYRRNHVPZOCMOYOURJIRZYIDQXVEYTVKVKOPUXYSKFJWEPNVDYOMLXCPUQUAMZZGCAOXCOTUS', props),
compute('m_6_11/8: ${c} FXKYATWQVHBIVCTTUUICSUFCXNEMKFBGAZZWBTWPLNQLUUILPDUYSTZCDBTVKVFSISPQUYOGBCVJPEICBHKANEHJZVHWCGHJHXCH', props),
compute('m_6_11/9: ${c} GJAPEOTAQQVTTJRGTSOKSFGGGDBYUPZYBLGCPOYDRSEGSHKYQMWRFETHNCHMVPTGEFQHRAMFLDIYMHNJCTZASTISMVKXQHSVNBNN', props),
compute('m_6_11/10: ${c} EFVMKBIRFKNDTCGKQLGPFHFFDKDGCKNEGTMLBECTGSUNWAGLHFRKWCKXUAUDCPPCHQDUMFLBLOCFQMYQMQUDMJYSETNIPDOBJDJF', props),
compute('m_6_11/11: ${c} TGRSSZWHLUOCYSIMPTFDHOREAKWZUKHPKZWDVMFKYZHLZGYZOUWRIDJHOAJORWBZMECNVEMKMJKDTHHZNENNYYBYOXLNNPAUYAXA', props),
compute('m_6_11/12: ${c} NMJZCWTQXUDMERLTPNUFGPJOPZOTLJAFHWYITVXLQVXKPTIINMFVVOLYHMKEIHEJJAHDKMDVLUNWRWMOMTAERONIZUBUSXICCZFB', props),
compute('m_6_11/13: ${c} IFBRODVYLBBXPIDPKVFELATASLHRZLLWTYHDSIPSGISEPGRRVDROZHVIGPYXGPPNTULSPLICXMNCWTVRJIKEURHHZJOXTCNLSJOW', props),
compute('m_6_11/14: ${c} DHVFXZZUDBDUHWFXXGIFZNAIEUJJVVWZTJOLKFTNOYESDSAHARTHOEHKXQAERVKOZXDXIIELLCLEMMTTKKCQADWCPLRFZJBNZKGH', props),
compute('m_6_11/15: ${c} COSEDJBKYQMDKYPHHCATDNLMQWWWGSSEOCLPDCTSVALTGZQJESCZGKQUBDCJURGSRCUVUGSDHZOFZWZCYZTOHSQQQUDVRTDVVMSC', props)
        ].join('\n');
      }
    