
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_5/1: ${c} RNIEACNIXIQAEZFAOILHDMOLDHCZOHLUUHUTQEYPOHQSYCOZGSVBUTHKGRDNDPZICQSBGJDRKOVKPYUIHOAGHANFVNSJQARUCDCN', props),
compute('m_6_5/2: ${c} DZYYILXTCMBFJZEODUGMNJBUZWFMBHLVHFRHNAJENWYYKNDPJZYDPSBXVPYXQZZOBELARXHVDVVDGSQBTGGKYQHPAVHZGDDNVPQQ', props),
compute('m_6_5/3: ${c} BJARQORPFLVKAUAYCWSVAFIOTBZFFBPZYTURHKGYZKKIHHPQFYGBDQQUXXCZVBTTGAJUYVFLRVCELSCUKPXLTNPLOPFAUQJXEZBF', props),
compute('m_6_5/4: ${c} NYUAQLZFGRTEAHJYNLNXIVUHUXRYZWPYKZEFFRDSEHSOQVGXMZWGJCAXVHVIYVTMDUPTIGODQGHNJZQGFRXTEXIXHIGCRTVSMZZF', props),
compute('m_6_5/5: ${c} LKMHUMPNDYBVNXMXGDMZEARWQVLOHCFWAFNAARDLOFRGTZXJWYJYUZWEMNQSWCXQCEEMLENWBVEFUSRISTNAHVUUOIWDVCWPBZCB', props),
compute('m_6_5/6: ${c} AXRUEXLAIWPNQFZNEUSRNBYBTMWJPWVBWGZEYZFDXBVVPIFWIQUUHFWVQKCVDWHVVRMHWRVFYRTCHUHJHBYQXQOLEXCOOLEVSMBU', props),
compute('m_6_5/7: ${c} SRQUHBBQNTMAERMPNHFQFGLDCDUOFHDQGXQLJXAWHKRSNNWCDGQDWNRYHJJUMWWHLWTYMVBQMKOBTWYTVFERMHQGFTGPFCTCGHLX', props),
compute('m_6_5/8: ${c} WHPOBWSJZTGWTSDMVBQWQYIDDOSBIMCDCNXUBFJJWJYRHTFBAKVFCZIRPZUZEFYEDCEDTEJFAGBFRHWENUWJAPEUZSVVBNZJGASC', props),
compute('m_6_5/9: ${c} XKGHUOAHVOZQQZEWGBHFCKOXJHFEILNWVKABDBWGSBIPROFGMDDDUYEKPNLKXYDUXXONQPMCMQRAZDLXLCGGYMIACWWAGQCFFBMF', props),
compute('m_6_5/10: ${c} YPXQTOJMYBEPQTDAXUTREEIQEDPVMVOXLCRSDCCMRSWSDXYMMQUAWDAFIYTQNASSVIZOQTVGUHUCWPKNIQJRPMISDBKGTEVMHRDS', props),
compute('m_6_5/11: ${c} EMWFODOWDKEGKWOPUKXCYNTSIVVJAMNHLHTXAPDCSLIAFNGPOZYFMTAFXDOBQLRHIQLUUDHIVWJSYXBDFUWQOAWPVTAAITXIHBNK', props),
compute('m_6_5/12: ${c} OQXWUIIUFOKQUULVJGKSYWOQIJKMZXCBNUNGSAZKYFAQMDIHTAJNRGWDWNOKXEBISVQQBVEKUENRLMROABELVGVZHWTXFLJPIVHN', props),
compute('m_6_5/13: ${c} OGRIEISTYJHDXLKMQAVHCTSPFLJIVWWMHPSEGLQGTDINTZITTLZTBHAMCRHZRAARIMMCWHANNBVJTJRTUNXASRUDUZQKIJMSXUUV', props),
compute('m_6_5/14: ${c} FDBGNIMDLPBGJGEIZCZRLQQLDJOHSTAKEURXVAODSDWUWHZRPLNOVTSGYRQGONPUVRMONVHMGWXTOJVODLQLRPYDPHJRJBBLELAR', props),
compute('m_6_5/15: ${c} AROYMWFEPOVCQDAWPOONUEQKATJJRZVRUQBODICAAZMMIYWSWWYZQLWLSSUTYGMIATQNGZKMCYQJOAWEMTOJTPLEFCHZTNBZLCFP', props)
        ].join('\n');
      }
    