
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_20/1: ${c} PZATKWMYYCNNXRWTQFEJLZPTPMJLZACBHHJMRCRDNAWKBAHMOEJNXTPZEQNUDCRWADMLSIFPAGETWLJEEGYKGQMFJCPWZKBBYADV', props),
compute('m_6_20/2: ${c} BYQYFRBLWABOYSKFXVGOXXKDUQMMNUXFCTYRAAWKWZKFESAQFIHRMMZYXZJWFNVMDWMZPCMYZYTVZHUUIJWJURCOTIWFRLDOLWNR', props),
compute('m_6_20/3: ${c} LBBDQRBBHSNEIOXLCMTHTVNXMAJYQGJBPURWCAKMQBVYLKZJRTMZDGTQNOJRBGQNMXAIBHPMUYVFHXNOKTKWYFLEUHZVBPTAUZAI', props),
compute('m_6_20/4: ${c} BMJPNBKBORXBWZFAPWBULGLCOEOLGLTOEHVIKZANJXDDLBEMYNEKDFVCQHWDXOSANMLTEMHPVWAOVRZOPOWDPANTEZODRFCEDZVR', props),
compute('m_6_20/5: ${c} FOMXXXCBLGMZQTTLADGWRWTSTMWZAQEXVHUJXKCQXRLKFKEXFHTTGJWDOCZXGBSPAHBQAUBRMJSYYTYQWBLVYWGKXEZEUFWSJFTR', props),
compute('m_6_20/6: ${c} PDQLZVLKFUNZVBHPFBGWTFQZBRRVCQPEQVHBCLSCCWCHBCYJYDXYNWCFPCKIDOXDKISBUBGBNCJSWTDZJNZIWZKLJCVYJWQPNISX', props),
compute('m_6_20/7: ${c} LGKKDXMYANVJVBPYHEADRAIZQSWADHVLKVQNAKIZCMXFPIQOUDCPASILOUBMECMWZJDETIJXORGAYMAKFGGZCHQTXOIJAPFYKADA', props),
compute('m_6_20/8: ${c} AHSYTDBZTAYPQSJDMIIOPHRMCKJTCRCCZXHDGVWYRAHGATRYVVRERVTNCUBOEXSVOILPCZGPDNQKWJBGBNJOOBQIJAVTMJSKSTFD', props),
compute('m_6_20/9: ${c} SOLJJZHCOXAFEOQALFBTHBWUZBWGFHWZAWIXHNYVYQDMWPLVFCLNYAHAOLGFKCANBHSAZHOUWXPGYCCUYUCMOGPMKYQZRUOMAKPW', props),
compute('m_6_20/10: ${c} DNUIOPECCYVWPUBCUUVTMAPVWNDYCXHWYKFMMKUJIFKUPPXSDZSWJOBJOEKQTXDAMXVNCMNKFUCIOVQZNBMLTROZHROSTDSOPFDF', props),
compute('m_6_20/11: ${c} FBXJZDWJAAXIWURWXHQDGZXETJIAMWZPGHDVOTLALJXIGCUSYFAYXONNZZYVTMTNOYNUJBDPBLDLXTAHFPZKLFIWAHERECUUFWDJ', props),
compute('m_6_20/12: ${c} LDJWZNRAXIPKYLCIZSXKXXATQGZOIBCSYEXANPUTSNYKMBRFXTSPPBWNBQZICLDLLNZIFMYTSKTTZHORRTFRGWQINWYXCOTCTIHQ', props),
compute('m_6_20/13: ${c} UJZYUIAUIREKYEZHTLZCEENBGXDJLWAWAXQDGIQYKEKKVVHVIOVLWHKMBJOHZIWPXHODAKACWOCBVVEPFYIJQLWMQLKBPKAYWWOK', props),
compute('m_6_20/14: ${c} BZSHXKTBTXITAYYCZSODFFUCNNFESNVPNVRYDRHLSJTGAPSCVBPEKAZJELVSZPCTCBSNWOZYLIDXRKPIGZYJLWKOGDZOUOCCLLDY', props),
compute('m_6_20/15: ${c} SULCJZKWRTEHYXCCRMPENKJLVBMMGTNHOQLPCRFGFFHZXMJBGMDGBZIGFFOBTBYWXJIEXHIQUYEGYMWOAPSROGBRZVPGKPQLGDFH', props)
        ].join('\n');
      }
    