
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_16/1: ${c} VVLANIUAHVAFKWZQEOGGEQFYJXVXZZBKFUOYPENUIEFAPRYZBWZPCPHKONVKSDGRMFMGISTHOBGANUTAEJSZCRKKSLMFXUGZGFMS', props),
compute('m_6_16/2: ${c} AQRCDNSSCGXXTRBCWALGKGZFQAIUBHNMILAQQUQBYOGTAIVCTVHXRPVORAKZERQKVMUOECYOONFEGIZAKDNKXYHUAJMAWZWWHDHM', props),
compute('m_6_16/3: ${c} LZRMDFHKCGNVMNWSHYHMHPPTCFTHALZMLJVNJLURJVVGRLJRQJEVBTSPQJRELHGSNNCGYIZDJCWDXHEFWMCHLIPFNAKSWTLFVQVJ', props),
compute('m_6_16/4: ${c} IPQFOJANMJEZCEJASJBGLNFBOOKWBAAFPUPACJISSMUDGNGLCMUXQLYPWPXAUAGUUMCNWLYNEAXTXTKAESSPEZNCGKJPNJOXQRPY', props),
compute('m_6_16/5: ${c} UMFTYJFPNMKXLFYUJVEYSECEIJBOBRSUYOKINAHSQCESNEAYVWDVDPVFDGPDJVJRAQJXXCBUUFPIQPNCIWVURGGGKEEALUMGQFKI', props),
compute('m_6_16/6: ${c} OAYWVZKPVJYVYVGZDWUBPAEBAZCSXPCDJGHNHFVVKOPPBWJRFYHXJCAPFZIUMVQLEHDQBPGHLRENPVJAKVEOQLLVWFAIVQADCKYJ', props),
compute('m_6_16/7: ${c} EDLOOGZOEVYWLMFEPWFNRHLSGEGJWLCXLKHICYXEEADOVQOTMTVGWFKEAVWGFSUGUSKCBBUZDCALWHETTUMIHHRZBCPWQXUOZAAV', props),
compute('m_6_16/8: ${c} MILPDSTQMGKQWCHYGGYKZUOSUSHBFLRUJNIZHPKBNUFNLSSYQDBCBEYAAHBBVZYTQQOQCIZAONRBNUTNDEHJNLEMEKQGHFWVHRWJ', props),
compute('m_6_16/9: ${c} HBIJHURYYDXQWNKINHKRVHBXTPFSYHOZGQLYCILDOGDFSCYKFPGZKPOMHOKSNINQGAGDRRFHLRPMEPKICNDWFLOMSWJICERUJMUD', props),
compute('m_6_16/10: ${c} MVWWSVEBBMXGPCEKPWQDNTAPFQZGPJDTJEJJFPZXVBLSKQGNGYOBNSUZXVEUVFCQIQYKHDQFLTMUCLBVHJTMZNLKQDXALWOMGCKA', props),
compute('m_6_16/11: ${c} LBNXMWYXKHIFXCWBCGXPEYVRLPMVDQMPWVUQOZJMKSAQSOLDMZOCVBMCHKDNXLVNPBOEYHLMUWQHAGYWXXBMAXQRBZIIJYRXHPFI', props),
compute('m_6_16/12: ${c} GLDYKNZECYGIGAOBQDANJMEFDWAWBESYKNUSYTZPZCWKONNFQBDIVRPHTWRNEOMFWJXVAHSGETHBLQLZWBCROSTPXFSMTRDXAQRS', props),
compute('m_6_16/13: ${c} AKYBYBYSTULKRQURCSOZHJCWKGELUJDEYTVXJKOIKDMMSSHHZDDIOWMMQYHHUMNUXQPXXQIDRNJOSWDQUNYKOBHRJQSBSQHSWCMJ', props),
compute('m_6_16/14: ${c} KZEKBVUQDEJXWBNELTTFQQRKOORGIUEHQATYSOTVAZPZDJTKYRAKMPFEAFUPOQXLNEEDYKYMJFBYKNWBCRTJXAAULDRAMGDOEOHW', props),
compute('m_6_16/15: ${c} WSPJJIPQDWXAMLCXKQJMLWIAGZKYYLJGPNBJSHNYXCZKFCREZXMKDPXLIADIFDZJCWYQYHESDYQDKCGUQPGFMOQCNCGCUSXUCERK', props)
        ].join('\n');
      }
    