
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_8/1: ${c} KYXURBRYHSCLXNMCEXXXCOZNKDVKGGTWMMPKCGGEIJTBPAJDEXURPJDSCNIZBLZJVMALCGJOTJVGSIYPCWQRTSHJFXJQUCRSZZTC', props),
compute('m_6_8/2: ${c} IMAFFEUEQYRCUAUBUZBKXFJSQNQUNYZDBEKNYLGMQMWXUMESVMKCGADEGZXNFELXUQYJBRILNSKDVCVOWEMWBHSIZSMZKJQLJJRH', props),
compute('m_6_8/3: ${c} HHHOFRDBEBHEMQTDXLIWOTMRQMGWJQFIWCQLPIMAIYEWKYYFOBDFBODSJFJCDLZAXRQQAMDFUWBSSSLYKTWJJXXXKLBRIRCFJTBE', props),
compute('m_6_8/4: ${c} GTGEGTWVVLVKSDWVSDSITWYVMHATONEDEIJVKYWSHXQFBSEYOLZYKUVHCDOMPTQMHJNDOGJKPJVBNHJNIMMUSOZJFAULCNOPZOIP', props),
compute('m_6_8/5: ${c} NENFVEAUKLEHBRBICSVFSUKBPQUFERLZZJGWSTLQCWXTNHFTNAHANZORFFNDXTSGNQHUBIGEUTGIYXBXUHVQGDRTPXQWEJRTFQBP', props),
compute('m_6_8/6: ${c} TOXHNLBBFBPOOTCSYFMJSXPJBSMFMQFUMSFKCWSWDGOPUOCBAPYUKRLLHWGGUOLWJFCONCNDYDXYZJDKEXIAHFVTJRZBJOWKJTJD', props),
compute('m_6_8/7: ${c} UVYIAYRPYPZVBYABYDGWVOUFBVTPMVXTRWSFNLFOUGBYSZTSBKQVRDSOICYQARHPGQYZKDAMIHCXGAPGNGOYOGSZBEYGULPSMNRZ', props),
compute('m_6_8/8: ${c} MHTTMZCGWGSMFIFCLIIOEQBOLUTHWPLUXJLLVUABCVAUAEBSQSPPZVGYWFZSUTPREFERSGJRRWGFFMXWQSONZATRPFZOSDASVJGW', props),
compute('m_6_8/9: ${c} YJAODABMCNKBUHUCCZMWZTOXLQNJXWJSZKQRMYSIYWYGTTIZCGQGEAARJQCLTTEKIHYKWXGTUGVPDEEAPRPWQGPRPGPYJQZTVECB', props),
compute('m_6_8/10: ${c} IHWOVCIAIOPLARRSCAZUYZATLGLSWPKDQTCJZCURWTQIYXBVUIXHEPMAEDWKTPILHSCPHATHAAOTOVVZTRTITEONZADYBHNCUTKS', props),
compute('m_6_8/11: ${c} PILNOCNOYZEXBGZJLEDHOWWKZSHLOJDUHOWSSKDGWIIFBEZKKSFCQNJWFHTLTVSWDIXVMRSLMWVMMYXEELVMPMSURRMMJVEXRQDI', props),
compute('m_6_8/12: ${c} IXBOWQOWHPKWERHEOTIISCQYSMKBWSMOGIZMVVYRKXDATQXBYMXXPEKHZQSAHGRXAXHACPSZRRAWWPXDPABWDQPDUBNIVHYBOCIH', props),
compute('m_6_8/13: ${c} ALKURXCYGUYEVFBTXPUPPJOPTXMCXGGWAXXSOKTGJQTBUMXGZNZXDWZDOOIYNGJAUCHCVVFMJBLEHXPPXNTDODWITJIHICUYVLRA', props),
compute('m_6_8/14: ${c} JZSLWZEKOAXLIHCFKNGARBDYTURJUPGVWSWOEODRZYIRKXGJJEBGYDLIKAMAOVBQUYJCYZMMRIQZLZIFGSOBQWXCTDRYUQBRVYJS', props),
compute('m_6_8/15: ${c} YVSWVSOEFIJBRMMSWCFVRSINJXUYFLCRWAHHPEFKDNGUCLERXDAIHJYVGQXKGGUDGVLAQGYUNNJREQYWDIFLVVGIGBVCWMCUBUVX', props)
        ].join('\n');
      }
    