
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_1/1: ${c} UKYERFSHBYBRFNMSHHVSRKFIMDXTWKNNPITJPTMUUIPPDRRLLACIHJLJBXRWRQBCECDMWUOJZPARGHDFINRQQAXHBHKCPWNHJZJW', props),
compute('m_6_1/2: ${c} EIQGWBHRICEEJMQACWKQBUJPTHUZGCHRTSGRCGTBCKBTPSYATJMXKNTVCJDOCBINAGHZWIOSZAPZHPDWQCMSVMHWSXLXXJUUMBYJ', props),
compute('m_6_1/3: ${c} RQJOHSKZXXVQVKZJJNEKMORMFXMABRRSTWZZKPQXJOCLZTQMBBOEVBBSYJPAENKYVMPNOJMXBWPHSHEFUZZJJJELCLRMIKTLTCMF', props),
compute('m_6_1/4: ${c} BBQUDLNTYEJJORGSIIHRAJQEERORBASPIVJCBSLGOTXZLUXODHSXIPGJILVJLEQFUTEMDJMDHJJUJKSXYZBJIEVZCDRTCECMCWBQ', props),
compute('m_6_1/5: ${c} TUGSYZGDBPEOPGCPMYDKNWVQDQSXQVOWYWXEFZZNJXELIVAAMLQISIXICQZHCTQKBXXAFGQMPCPQALOALBAINAEXQBYYKTWYGQOT', props),
compute('m_6_1/6: ${c} AHSCBJAJBGXVRIGMFNYCKGMBJOQFTFGAWAZRRPOHCZWUEVERKRKYHUXSFOJDTESTQMNPWLHQFVCQAPMSJIBXWNXXTFOJVZHBEAAV', props),
compute('m_6_1/7: ${c} BCQLWFMFSBARAYHIIIMRNHQBXORGXDMCBAVJKWCRTJOVKKJNZZLLCPWZDKREIHOMMIPXAKSRHMBMSBKMAFDXKYKAVSBNSMQUFKCY', props),
compute('m_6_1/8: ${c} ZRKPILCFOACJLGIUBZENRRWKKOWCXCHZUVWAQZQHJJZHPMIQDDROPYBQWNQTDLLMNAOSRBLBOTFLCCMGUZJETWDVEQAWCVFMBIDD', props),
compute('m_6_1/9: ${c} RUMTNNPOLVOKNBVRGTBEDAAVVWVHDMMAYUWPTMGVXYUXTZUTIUTHIGYOJULJZYNYGMCFYOXLEPFBPCYXHCJPCSYVKKQDYPZKWAEG', props),
compute('m_6_1/10: ${c} VVDQKARKLPCYRIMPOJEHYRKFYPWOCCINJUWSCLFWGJBYOTARCASYFYXXTMLRQNWDUWHDOMLRVVMLELXLLMLCPBJJHAFPGLBQCBFT', props),
compute('m_6_1/11: ${c} MGDHMTZWQDQVREDPHEWEAICNBZNIDWQHFASRFXZFXIJIJSYNLXBAJSMBCZHZMGTKFFTZBYIMZJYXMPQLJPJOYWACXOFGTSPMZSIX', props),
compute('m_6_1/12: ${c} ZHXCPCTCPFJXEJPLYJEWOJLBVJPVHRKYTHHZHOLOIQBFMHMZKXUOZUTJOGVLAPPYDWXDFVTLUUMUQPYRHAKKAPEMBAFKHZWKFIAV', props),
compute('m_6_1/13: ${c} GDVVEOGIROZPZEAAOPHRMPRYYCCSREZPROZYEHIJARLCBKLHYIXUJCFNSWCUBZJUERHPMDWMQDZDYWGBLCVLTOPGROFTAQLOAVGX', props),
compute('m_6_1/14: ${c} HCMWHUEVUKUFZCQFFRZAJEFJZYMENUCIPWWDFLLAKEBXSKAHTDFBENYSQHCCBQAMWNNHIKCYJRSQVVMQTIQCQJOSALXHGKJQSYLT', props),
compute('m_6_1/15: ${c} BWVTDBOAIDNDJOBXACFFSPHIMUGUFXCNOBBEIFQAWURUVGYZAXSLBUOUFEOPAGJUEBWQMVMCNFLJSLJVIKPCQUWWDDXZHSTUHYPO', props)
        ].join('\n');
      }
    