
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_15/1: ${c} LMLFPDSSFIYAHDZXWACFEYWFIGJLEGWATJYJNMNQFSICKHGRMRBWNQWLPFMXVQXCPKRZCTBXKWDQJZPOHYDPJHGZXIQGUWNLXLMA', props),
compute('m_6_15/2: ${c} JZWMOJHJZXMLVRPKPAPESJEWRGOJYNYPODTYBQDCVRNPUDTAFVVYGHAONGYEUNYEBTKQPZPCVIOAHPDNYZDCPGOIQWKKALFSUFVR', props),
compute('m_6_15/3: ${c} YSOHPHQWOGLSBXLSYWETWXCQTWCIPEXIRURSLUHDMPFCFRRTLUBMAXWRQMNDSZINIYEVDYMFUBOIIPJAJZLLGOSMIINJHAIIPSQM', props),
compute('m_6_15/4: ${c} ECDIJGYTNPIWWILUCUDXPROQIGGTABNFSPVMSXTDUREJSDCSWLTWTILNVNGPVDXXKLWUZLOZPXQXGWFTVAOCCQWLWEOUFIIPVRSS', props),
compute('m_6_15/5: ${c} JDCKSDZVUTGJDDYCLUAZNUKYDYMKOBUKDTQTIXMWHVIKBLCTFUARTOAEVOJBARTRUOXOMFFZJFGKKRYEXGEZUZPIWMJERXPIZOYO', props),
compute('m_6_15/6: ${c} DZMHNSICHOKRCHCNHTTKQYJIBDFNTMFGCFRFHQXYQXVLHZBRNUQWQJZGRAFXVICZXLJQZOQFNYZTEIZVAIXJGWLFCDTFBMCZRVKI', props),
compute('m_6_15/7: ${c} ZRFBOAMAPLPDIAUTRHFNNLFWCQVZMJBQCNVEFJFIWHKHHSZOWLJFUSPRSYRXXHZJINNFRAYAQEJTNKXSSQEVXYJFASSPSWPMTZXD', props),
compute('m_6_15/8: ${c} ZIPHOKXOZPOFXPEHTXHNLOBTWJIMLLTBIZQOSTPGVWGPBSNXJJFKZGPJXMBOXNYIOMNQQUETGRAXYINELGACDFBBAQXCURDATSJT', props),
compute('m_6_15/9: ${c} PRQIIKVAMJNCBAHGUUVTFEAITZRPTBOBOJNSXHGKSCPXDEBLJBKIAPRNEDXTBTUEPHBFPAKVPZWHINGTQMRKCKQIYXIUFTOKIHHR', props),
compute('m_6_15/10: ${c} JTWXWYWCWVCEAWJTJNCJGBSPKRFSDTXENGOWHBXLEXZNCAJXDVJSUASYVZLPOKQUTUZKKMYUCIGFNMYWIKULAAZJAGMDMYYMAIBB', props),
compute('m_6_15/11: ${c} HBXSVWWNUVWHDVFSHEFEIXCXRWKNZJNBCIYBBFLRVRZTXNBOBIBYOOCLFWUGYUFXPKMBRVJKHGDTIEABRCBZIULRGSBVHSETWYFO', props),
compute('m_6_15/12: ${c} YPKHLQTGABMHSTKXRQCFSQDFEEGQOFSKALDDDVIZJPTOIVGQAYMAXGFZZVTSBFJZUYEACYZYMNJQTHJTHMQPJITSNPMTKKYCAPBZ', props),
compute('m_6_15/13: ${c} TCAIFYRLWXOEYFDWVCAITVINHDUVITDSGGFQYVWXVWQJZWKDMBUOSMWMNYVIBPIKTEYQGKKSYCLMASFNRZYJRSGKWDWGXNREJJIM', props),
compute('m_6_15/14: ${c} XOAHOPYQMADJJNNIQHGDIMMMWHJYAIZRVEZOHPKFHBSYTOJMTNSYRGQATNLXLDUMSLCHRCVGUHBHNQROMEVQHVHCZJDMBGHNRFQM', props),
compute('m_6_15/15: ${c} ANCCGJTQMBPTJLVEKBTKADZMRLRDVFSODBKGKKBEBXOQDXHCJYTGDZLOLQAOSEFJFKQCWYJKEDAVOEGTIYWEUGCKWMUURFSFLXSN', props)
        ].join('\n');
      }
    