
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_6/1: ${c} QIZVOEMXJGXBUZBIDMWPQGQZGBODZMMBAMCGXBKMXVZBTRPWABDURTQXLDIMOTORILKMDJDHHGOULSRNGNUQXSHMRKNTKTTJCPCS', props),
compute('m_6_6/2: ${c} SWDFRFXUOREROMRZPPVCXJOIIQUSKSHXRGTOUFQANBRTFUITSUMMWWQUZNAJALNGHFUDJZRHZWSYGEANCFKBTDHIZLLMLGDAPDWF', props),
compute('m_6_6/3: ${c} THPBPNLVXCSTZCWLSEIZNUHDHJEEDSSNPOVBNKNTVHUCVRQHWQTCJPGMLJJZKYAITUNFMKSMRAAVQBYNOWFSYMSVSYHQULTMUBGY', props),
compute('m_6_6/4: ${c} YIIIMVFFGZYRJRYWWFNXIZOLYDGELXWSIETTISRNBXEWTUOHALSSKASVQHMSYWRKSHOEEVLOCLVFXHUNOVSYNOENWTOUMZAZFPAE', props),
compute('m_6_6/5: ${c} LVZCGIOEJBGGJQAZOBUOZUZHWLHPOODSSGAMIDCVIPRBFUJNSSGUEYBXBNCQUQTRYZIREKZVALCMTEXWLHTFVIRSOYOGOLPCMFYL', props),
compute('m_6_6/6: ${c} HHQMJMJWZWAKQRNYOAXHAOJDAXQPJBBMWUYEDWWGVYTCLVQBGDDYBICHGESKTMOXGQUFKPPTSQAUXUCWSLGGUCIVOWNZIWFSHUDA', props),
compute('m_6_6/7: ${c} VDODAWUXDRMNAAPZQTSXGFDRVHYSRCPCUHKIKVNUQXPRIBKZPWOFZSRAZBJGGALCAKHJGYJKOTHSLZVRZUGVZUEOPPVVBUFDRYAE', props),
compute('m_6_6/8: ${c} YDCJOIXKLNTRXJLFMNFLWQCSRRKISTNPMJDLQVDOFNKRFRJGDAYQMCXOVMANLATYRKSEIMBKMTKLAZJENPHULJWDWOWGWLYZCYSG', props),
compute('m_6_6/9: ${c} JNEAPNALAPMKNXDYFURWAGYTEBWMUBIHQHSQXKLOUPDNNNGHTXLLIZUKIWARYXDNTIQLQPBTOHSAXVJNYZINGBOBYTZYLMYPUKJD', props),
compute('m_6_6/10: ${c} BYGTIOKTCRYODDYYZEFGALRCYCHNDKXSQQNFXPLCEAFBFDESGEBKEEOMZBRBUMQLAPSWLSQWSKFDASDLSPMGUGUOUMHNWXKTCDWY', props),
compute('m_6_6/11: ${c} VNTSYBGIOVJUUNRKANQYHSJLPJBHODLKNPTCGXNSFRTVQRXYSSPLGADYPOETAXDWJYODPCQGTCQPJXVSMGWNHEHZMUMUHQEDKNDY', props),
compute('m_6_6/12: ${c} QHSHPIIJUWOYQDAZTCEIDBBPOXVCKNVQQMIJRLCESDBALURVZQTCSLMJRMVXZJMYEQJJWXQONPFTDUWHWYWXSKRCHJOJJJZYPEHL', props),
compute('m_6_6/13: ${c} FWBIMBVPSDUFDQZOYGFLSNZWEVUKBBRZWZNJIDXUPHAMRLYWATVGYNQRMRZTRTYQBKURMXSPJRRDBTBHBLOQPPCLXRSJLZKLKSVO', props),
compute('m_6_6/14: ${c} MJPNVPIXKEYXNTQSZWYQHGKQJBYLGVJUFQALAFTJNUOVPUFLHMFGEZRPWEGRWGTRHRBHCIHWOAUPJBFSSPWPAJBZXWSUEODBFIKQ', props),
compute('m_6_6/15: ${c} XRIIZUHIWCLKBJOKSLANNNWXSHRVMSZDVLAFVTGXQZIOYMUDAIOUSMHXMCYMVPQJBVWCXYAJTHDSKTBQCUNVJVTNNJVNGKUVWIQF', props)
        ].join('\n');
      }
    