
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_6_4/1: ${c} KLXNFXYTPZWOPYKNQZMCPQDITWGRSODLHNHNPAIHIJOUHMOEAHZHJGMNRGCNASDKYRCPDNQKIOPKVIKCLSPJWDUGJMHGVBQXIDTA', props),
compute('m_6_4/2: ${c} XKJDADLDFCOEHFTQCNHCQYNFYMWHDEHAVHEAIUCDNGTVSHPCBXYRTTXAMSXHLZPBLVVYQFNAFGDKFYFSPRORELGVRZOXWNLPJNYY', props),
compute('m_6_4/3: ${c} ICZAJMSSDXZQMIHSJVAEUTSHOXYLAYDZYNHMPOZPDDMBNVBSBSZFPGPBDFNHLQBQPGTDKIQPZNRQHSYYQHXVYEQYILOBDBDHBNIH', props),
compute('m_6_4/4: ${c} QBRVZSSDGLTDNRGDLVFLQTBEPNMFXBLMOSCVHHWJGNPJYPFGNCIYYWXDEXTNCFYECMROPAMLOYBZHINHKTWBCIAJWQAHQBQCYESK', props),
compute('m_6_4/5: ${c} IBLCEQAZMXMZHOEZJENSEMLTWYCSYLDVBDFEZNLVDIDUIHPIUGUHKOMVNJRZUPDTIXQTFZOAJKQBFOZACXUMHXOUPARIYRHZOYAB', props),
compute('m_6_4/6: ${c} HDVGPQJAGIAZMTUEOZENHRZENOCWDBXXVSMEXLOAWXSYGQEEJCXHNOMTPUWUORKNULKJEDRSLDSGEPLPARENEMJAWEEYHYTBLNCK', props),
compute('m_6_4/7: ${c} KPPJMYIKAORXOOQMJBDLWOJAVXGIAWDNHYSMBBMVQIPJAIDCBPPNKQBKGQODWBFZDXECZVOGNBVZHLIBBDOZMDAQMBHTEUAJJCSE', props),
compute('m_6_4/8: ${c} OIRQBKLNYXQCWXFWZHJIMHHFFFKWHKVJIYOWXKSXGTQEWKRVHOKTGSBCHUUFEELQDQRBBBOUGQHSGKUESEXNROAVIBUSUMNEFXQM', props),
compute('m_6_4/9: ${c} LWMMYWJZJEVRTDAICQAKZGXBHCQTATIVIQQBLDACIQLHQCPUFYLFQAXBNBYGCJXJPDGTLPORAOEGAJDDUETHWUEZQUVQYDINVDDP', props),
compute('m_6_4/10: ${c} KYEBFUQMMUGLOYFQCNHBBDJMHXIBXJAWUHGMDGGZLRLFYUCRSEODJLMLFIHWXGCFDGYTSXPTLNYHWTALXRSORACDDSTHQWATBEGB', props),
compute('m_6_4/11: ${c} MGDRUNYLUPZTITILHIGBMWZHBMQVKUIQGYWFKNMCPEDWAXAMSUJDCKCMKTYSIDYTROGDBQBLHRJHDVDVPYZVBTFKZYDEODDWZVKP', props),
compute('m_6_4/12: ${c} DECNQILNHBYUSCCYSPCFKOPEBVVENGWLWYGEKMLBYYFJRDBFZVIMTXXRQWWUDUHKZYFQKYAXSYMHFRWTVKPJJVBWGMUSPYDODPEJ', props),
compute('m_6_4/13: ${c} DONNGBDVDRHZFAXPTTFYMWIKQAKXEJFLUMODNNECDRIHMAKIQWUZYJLKPGCBBNKEIXITSTQAREGJWLOTJZOMQUHAABNDUZFPZRGZ', props),
compute('m_6_4/14: ${c} CZZIIVTYISMTXQLHCEANFTVELXQQUBDJDKOMUHYXCJXEZDAYSWGNONUWYDETQTMYVRMBFNIWPAKRSMKBSZQUKYHYVCAXYHKZBXTH', props),
compute('m_6_4/15: ${c} PAKHCBKOEERUKIRPLQJADFDOHCIGUQNNEVPJHJXYDGSCSVTHPLNLBZVPMWMKMNSDNCAOWGWLTQCOJTAMROSMOSVHFYZWHTLWNLQR', props)
        ].join('\n');
      }
    