
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_11/1: ${c} PEZMJEAHVPPKHIVJWCXJGXHWRRUWMOJEZQWFUOPLDABVDQGOVNDGKBSZIMKHFVKXEKLWRSYBFPQIRYKBLJZBEWPCOZWJIBSRDKWJ', props),
compute('m_7_11/2: ${c} RAHHWRGBVDYVFDAPHINMAULYOQCDAUFNYVACAYEWPSBPNWFBXRGHMRFVGZKCEBAQOYNADSQWJWOJSCEYICRVMDHGMIGCZRPKCCGU', props),
compute('m_7_11/3: ${c} XFDADZBEFBBDCYRRVYPVTUUMCFMBEDAPLYXPQHJGYIFOUFZHYUSEGEOLSYSOWFJZUKXNWSRINYEIUOUSPILSHUVNWGCZMTCUQHJG', props),
compute('m_7_11/4: ${c} WBVRUATMBJINKNHJYXIVQOLNIERPEAONBEWJTZWRBOZGUQGXIOBQPAOMMRYBNRUHTYTCRKPDEBPKWWOIYQVRXYGTECHGOFKOKTNE', props),
compute('m_7_11/5: ${c} SJUNIGRUOIUDWCZNJDWEUCBCEUJHBWXQPQEWQATIGMVKICROBNRQCKTUUJQTFMKWJQHPYAUOLNEJQDQQFDSFGRPYSXQARRDULGTG', props),
compute('m_7_11/6: ${c} LXTKLHOYMVECCZPVRPLDYWPNGVQHUHHWTYUJIAMXTWLVCRSXILPBRIHEVODNSOBHTVWVEUWDEKDBTCUNBAFPVYQWXMYHJDZRJYRF', props),
compute('m_7_11/7: ${c} ZQGCUYLFTTZKTBAUXPSLBKWNKETDRDAKLEWZVILOFFKFAGIVRXVSWVNJVSTSSANJVSRAIDAKSJMWVCQJYJNRJAGKAFWLUDMAJYCY', props),
compute('m_7_11/8: ${c} OOJWYIDSJRQLHQQUMGZAJVXNTGEPRWMYNBKUQIUIISZKGOSSCVBHZYLVFEHIFKHVLRVMAQCFSQWOLLVHQHDTHBQFWKHTZYDZNJZC', props),
compute('m_7_11/9: ${c} TKSBPNOYSHFZRRRDWOXBPFSBOHJBKVONCKUKXISDXBCXGLWMKQBGATOWAPCYGRLVCJIPBXEANOGUFSOUJQPQTENAVSVMBZFVEVEW', props),
compute('m_7_11/10: ${c} CGQLRPYQEWAAIVBTKPWLARBJAHQJBBHBTDLWOUJSMDWAJFVKTUBDZDUAUEQKBCRRQJTTOJZQLGBJYRSYSATYMMBVEKSBMRAFNJKW', props),
compute('m_7_11/11: ${c} RBAIOOHTHURUNVGJCZIEMHVMVJIJCFSYEXXNRARZROQHXPAKVFWRMWTMFLWGPRTGBSINLWKEAQWVUCNEQZOJKVYGQCHPFXRKWUVJ', props),
compute('m_7_11/12: ${c} PFDJKPEHLJAPNHLPKTSGOFDVSCCDUEPQJFIFQUCJNILODAVBCBVOTVNROSLXVIODYEAIEXUJNYPOOCKTIOCZYSARNPQTLBPJTIKT', props),
compute('m_7_11/13: ${c} GJIWDKOSINYSCMZNIZYEXMPOBUOYVYRZNDSSIVZUYLBJFUBXTGZPTKUBQPHOLWOLTPWLQHNRXIHBBSDOASINJHEZWXGIAFVZDZSC', props),
compute('m_7_11/14: ${c} KEZXOVPZRHTZBURQKGZIPAGZPGSBOJASPATKXXQOKCNEYHVABYYLZMSVSSZHIEJNSQUUDOAAVDODBWKIMZNDHHLSRGUTJCKYTPVY', props),
compute('m_7_11/15: ${c} IMSUNSJXMGOOYJERPYQANGMJMWCARIOTDJHHUAMAXQRMGMFIZUIRRVLSSDRHLTAHTGSDKFDPTQIMIXTEWGJMLFZITRKBEETXYWOC', props)
        ].join('\n');
      }
    