
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_2/1: ${c} KMIYLDLYHVTWOCEYCOWRATBKQFDKFJQFSJNPGWTSNSMEKLJDKKOMJGHWGSAGHIUOCNZYJKCCNMVVKWUOXNSNCLOIOTNOTBTHFYYK', props),
compute('m_7_2/2: ${c} BJUJROATHGENZLJHSPJIZYYCXSPBQWNRFYDQDPCJWCXOOZXTVMKCOAQYLVCHLMYMEALCZLALJHMPCMJROLNGFYEGRAIDPRIEBIHL', props),
compute('m_7_2/3: ${c} ILTWIEOFLYCTCTALHQJIRSPXXRDTRQHBRTOUIANROTFBCEEPOZSFPHKUTVLWYRYDLZQZIDERFPIKXCFWRTYMARQBWWSKNXHIPUXY', props),
compute('m_7_2/4: ${c} JFWXDNWLIJEWOGCFEZDRFKZXVGXIHDOVRJCKEPEUIVHMBHIMMXQWDWRZVXASFACQKIRRRMDGWUHFVZBSXIRWOZKKDSIGAUHPLPAN', props),
compute('m_7_2/5: ${c} HSWIUGBSLWXPZZQEIBKUFQUQODWZJJOCPOSUZLWLWLZURFVTNWYADGWLRPXSIXBLHHDARCNDZKLVBJXVBZGGVPQCFEGXUISRBGSW', props),
compute('m_7_2/6: ${c} OALWIPRAMPCYYRTLODJXNMXXVRWCKVBPBHKOXIMLGDJFXIQIVOIQMXRKXEBWRWQWQFSXLZKOOMNXYLVLNGGELZKXOCEKTNDNGBVV', props),
compute('m_7_2/7: ${c} ADGZDIJNHRWRXDMWBRVGIAFRLCJDTGAWVDYHYXCSVRFCADCKMVDSGMROXIFYOYMEWCMRKXYIRWIWYOSZLNIWKXQVFRTSIXCECHRV', props),
compute('m_7_2/8: ${c} RIQAXUKBNLWIALQNIEVYTPQCFGNJSJSGJJGEPIMGMOSZTLEDHNMDNIPDIJGTVUBXAAOBJACZMSZRCCEYPJCLLEACSDPSOSIWLLZR', props),
compute('m_7_2/9: ${c} YYQBDVFLEMRZZGMRSXFTGHDKZJQKKVYEQDLHITPCDXAITFSHWBBRLZIUVPUDDDVVLCOZRXQNWTHSYNZTINAIKJHCUBFTXMQFEXDG', props),
compute('m_7_2/10: ${c} AHJDCOHNNEHKXTKCSYJHEQXXQVOSUFTQNDNZXETSGXWWRXEDKIISXQTVLPBUZQDMSGJQUAVQRIATLYFDWHESUWGCDBLDGRFLLRLH', props),
compute('m_7_2/11: ${c} WBPEHOTUUFOINMCIGKIODSWEZPTTPVHCGRTVUPLSKDSTOWOJDOETHGAHNKQLZMIKLIFSHSYROHWGSGTACAAKCJXARCKTLSXVHLOA', props),
compute('m_7_2/12: ${c} WUXRDKMBZYATOJQUMKGGYGUPJTEVXXWMCCTWOIOUAESGCTUFEPXFZWLCXXZQELZCWIRNAWKFNHJKDGBYHKDTDDHCFXIHXMQKNKZX', props),
compute('m_7_2/13: ${c} DLOXNQCDDHOYXHVLRTTTJYRCUQBVIVFPZZPRKXBXFULIDSOXZDBFDKPTCFUNFBKJPHSJSIJPKAFQHHGRQGYAJTXMDDCVTXZVJMZK', props),
compute('m_7_2/14: ${c} IPCPZGKKQWCUPCRHUQXULQSBTMVRJUMKUMCRQUBMQETXMFYUAITMLPSLNJHEWNOLWALFQPSWUUQVAHTIGCJPUKOPXBFUFJGNBTCA', props),
compute('m_7_2/15: ${c} AASZXYCSFSHISHZFFTKTQAZTFOWQFXZTFUGDGABSIOEWVYYOXOFECZBMUPZEXNJTNDJZZRRVMXIOMBKUDGOLHUGOFNAQSPCJFNEP', props)
        ].join('\n');
      }
    