
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_15/1: ${c} BUHFYADRNQQHPGRWHJWPVWRNZCXKAKFXHEOCKXNBVQNCHGJNSJTCDTYTRVRRLDQFNZBIVPBJYXDLHUQCBCHTURJQYWBVHZSUHLMC', props),
compute('m_7_15/2: ${c} EQKOWKWRSNRENUQQVCOAOWFIPWGWVAUHYQWLGCGESPECDRBDAYJPJEHYTFCYSJMGSTHWEYCEOZQYGSFVFNABMBOMWXHPFMDZSUQI', props),
compute('m_7_15/3: ${c} SBYMFMGYFBDSDPRLYDGUJYHSKNQSYQYZCHKQCCFJYQLHHNOXWRBHMBKQDUKAMEWFWVYHXPPQCQMTIRIBWNQSIOBZEJCTLZPIIHXS', props),
compute('m_7_15/4: ${c} OTAVQJZHCTHMLJHJDNJEIVNIQKECXMTFMAIQXWCOOCRZIPWNLEKEQNQKIJSUYFAKUVPKAJLYOYTWSIHJZJBJLTGHXHEXWKOBNZND', props),
compute('m_7_15/5: ${c} FRACFVNPBPBVJRZIMKYQEDOPWIIURKFDAPIFTQJOICXEYAQNEGEBZGYXWGTUVPEOQZZFWPAITITHKCTRBJLMUHIAOOWYUZELFNDZ', props),
compute('m_7_15/6: ${c} IDOQJQILAOTASCNUYZTGWWHKHNQMRUWSEQDNGPIFBFCVLFCEISPJBFQZMBJYFSHOQZNXTWBTCWGNLBSHNTFFOPHFJELWRTJHBEPD', props),
compute('m_7_15/7: ${c} WICXCAZSMMZZKQETZURNIYDXIVEQYVHZYVXMYBZHEIISIBHSZVZQNBDIRZECABGWPOIKKUGFXFSHRVDWIWULTRJYIMBMREEUHHKX', props),
compute('m_7_15/8: ${c} LENSOTOPMKRREAXSTUGGRQXFDQBRVERJSHGYMTHUMNXOGWJUPMPQITUGGMGOKNWJTCFZFONJDGOUIABHOSXWPJSCRLGIGNKFCNIF', props),
compute('m_7_15/9: ${c} LMVEPSREQVOAXRXKNXQFDCLHTLCHZADLCQGGWUBRANFSNKHDAOJEAMMEPQDDIEAGJPYVYYSVBDWDVZYIPLMQAVUCXAFJXQKCPDQB', props),
compute('m_7_15/10: ${c} KQDJWKLIRMFKXBZPASUHIAYNIBHYIEUVEREHHZIFFRDREVIEBEZYIGWAHVJJCLOOCFJUNUERNRPHREQOVXZYLOFPWUJXMABVVEQS', props),
compute('m_7_15/11: ${c} XGQJAJBEDVCJWLRQYRAQPHFZZGYYOKXCITCKVZHEOCQLNXYXZSNGJENMHLIXOWEALBIFEDRBATEAYJOOVJDGCOYKMGCTFGZFEMOG', props),
compute('m_7_15/12: ${c} JQUVWMGDGMNGBSFZMSGZZURSDUGFMEGZHYUYVHOXTYYEHYKOLDMCLWKFOMXQRUBISVCFPVYWMFIBNZRWWEFCUSFRJGFGZLWGUTZJ', props),
compute('m_7_15/13: ${c} VBZHQVWNILLTUDOZXZCYUQTHTBBSTCDMRQZEQUVUOKQKJXRTGDFNONGLWBGRTBGQKGIMCXTHPOBNCOLDUABUXIEUIMOUFEOJUBZD', props),
compute('m_7_15/14: ${c} PKQIYCYZFQEQOMREDDKKIOBFLUIHTSHCAGCTEDDBFVPKRJSQGNEHHHYOEOHSUTYYRPCEHYEXPSBBOYROLWLWMJFHSWFHFXFINHEI', props),
compute('m_7_15/15: ${c} URRMSHXAAIVVAUUGGTUDENUDQIZTQLIPMNXDIYADODVSXILWZSZWNWDHLSADGBHZIJMRSIGPLYDIOFZXSXHTHCGGAPTQXQOLSKFI', props)
        ].join('\n');
      }
    