
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_4/1: ${c} TJIVWGPMAIUCOKVTFYLHSYRYOBXJFJXTKZQGMHYADTMKBYTMKPDVFBOPPFUFYQEKIPLHOBLAOJXYWJMKBWISBXADYPGBZBVBVVGW', props),
compute('m_7_4/2: ${c} JWHRDKWGYNIYJPVWYPIWWOENVUGVARPNPXDNBQLPZUBZGNLSZIVCNBVYEHLBPCKYHCUQLRYYQSRAPEYEMTAAVICEACCYNXETCCXU', props),
compute('m_7_4/3: ${c} YALOQOUTZCEDHAVQALAENUCXULXWZDILIKATQBRQRNMNPOIQFTSVJXASZHUFYCWVYRRGDVZVOUKFBUNBFFHSRXGUWSZPCRSMYHSI', props),
compute('m_7_4/4: ${c} QHZCHKWRFDBXWPIEULODQQGSHIUDMCUYYGRSIUQCXEBASGSRUCAEWHYQMIETUNHOSRVQTTUKFTMFNBHLRTQHMTEKOYNMZGLXPMMG', props),
compute('m_7_4/5: ${c} GSAWFNOTELPWCRBGCJBHTLNSJCRDTSUDAPUIVDVNXFCAUXHTCNOJJIJWCLLJMCELAFVXCVBNMOQKTTUMMVSFEPKJGWSOXHSUHRCH', props),
compute('m_7_4/6: ${c} AKAQIKVKKOMAICAPWKPEXGSBZPWVTIZHNXUBFRMZGSDCPNSSXYANUILMZWHBBAMFBTMOOUWNBZUPEZLOPFCRQFNTCCJIQIPDEIBM', props),
compute('m_7_4/7: ${c} PNURUPVZJQDSSHYZBRIVRETZCXEQMQBQJKFJENWMKSCLERGNMWCAMCHWCUVTFRSELJUIBDONUGCPPHOTRDSBEMAEZFHQNKDPNMBE', props),
compute('m_7_4/8: ${c} JROHAXFXYWGRQINAYZPAFGSAQMZBGMUVYYYEFMCIOTQQLMQRSTKKXEQKYGVZYWMTBGSXYOCNWYDZVUKKZHFCJKTHLVVBBHCTLUGH', props),
compute('m_7_4/9: ${c} PPWBIWYKCXHUNOSHPZKXEBOIZWALIGIVOZLAOADVESAYAADDNGRZCPHNZCDQOMCMADMFYCOMOGEZGOJCDADWOOSBOKIPWUVDKYYA', props),
compute('m_7_4/10: ${c} TAJDMCVMOWTUTZRYKPPPYCLCLMAFVRQOLHKFEQIDUCJSOUERPRRIHMRJQOWPOFQSWPKUVEHNIGYGSOKPJUYCGFVFBVUWIRULAFFD', props),
compute('m_7_4/11: ${c} DWRMULMPELHVBQYHZXBOUOKDTMOHIYPHCLLDDBGCTZOOOKHHHNCTYGIYPBGOFXQAXPKLLVDZQLTNVWVUQCDEMFIIMMSMYRXEITRZ', props),
compute('m_7_4/12: ${c} XOUDVIQSSFYXEWMQDTZQPMLEOIYXPFVJDTHOQVYLACGBTCJFHJHBQJMZKKYGIADZLUFTPUSWUZUOERIQZVCZQTPGTSBRPQCPRDMN', props),
compute('m_7_4/13: ${c} MOONEDPIREPGSFCLOGITOHZHABDUDZBXPEHPQZIDLPGECQLQZMHYQKBIZLINHQVRYCVMXWDCLRQSAWHTPYLHRHOUQJEAQGKMYMNF', props),
compute('m_7_4/14: ${c} BQEYNHJLIUGDDCOSUSCMKTVTKSESKYMSJCGYPNTBAAWNHBZCGYDEJIPGMBKVVKAELSUSCZSRBXPNUPPIRRRFTEBGODNSWBHHZXDC', props),
compute('m_7_4/15: ${c} ISYYYZUJMFGKIHYLMNZTUVIWRKQVAHWSLCUNHMASZHXNJLYKJVSHRYLWWRUMZNQMXPWCSAPDXTBRTVNQFRNQNMSJHBWOMBKCOOTC', props)
        ].join('\n');
      }
    