
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_13/1: ${c} EWOSLWPBLAYWRBEYYQUYFPGRUXTEQSNJJPCRSKJZVGBBAGXVILTXUXPDNYODZJMZEQHWFNGTCOUOGDAFNWKABPZZXPLPCGUXYHVG', props),
compute('m_7_13/2: ${c} QZBWHLZNRTGWTSISGCLBNJMHZMHLKGTOFAFRHUQMSPNYPDTWQCIEOLVMPJRIULYHCNHSEGFIYFNWPFFVPQGKLMOJVUCGJHRAZOXZ', props),
compute('m_7_13/3: ${c} LSVERBCFEQWPFOMZMFWPZDYCGHZTSJWYZFFTBUDOUWNVHDBUYFJHRBCSQXNOHMWDYKIPNDLVSBGVJWHMGWXXQBEDQVJNEJLCPKFG', props),
compute('m_7_13/4: ${c} TRCZDEBETOGFAMEQVBSBQKZZCHQMFNBRTRUAWPAGKWBDLWDNGTOWVAFJTKNNYUSRPGMIQXRFFDJTIOQZXOAGIHIKJFWYJBBPPDGA', props),
compute('m_7_13/5: ${c} HLJYYCZDGVNVTGGJRYLFVQQCLAAOGZKYOPZQWZBYTFOMZESEQUIDQSEWDGMJBIWAURTXOXILUPDQRBSZQJUQBHJMTNNALUWAVVBJ', props),
compute('m_7_13/6: ${c} HVQHXRINSLFBOIEMDWSZSXYFONJLWKVICBMLENQUSXWWBLLECSANRIGNKIOJWTBYSFYAHZWVPRWYJCTFXDSATIRMAJCGJNUVSBAD', props),
compute('m_7_13/7: ${c} HLQZRAECBLSCYXQCFRXKKAUWVSQLQGUIFCVROIIIWBSQIJERPBMUPIWHMQCIAKAGFRAWCTPHNKKHLEOGFXJMRKELTOZKLEAEVGDM', props),
compute('m_7_13/8: ${c} EOZDATEUIWVPSVIYPVYLJOQPIIIUKZMYECGUEEHLNLQBHRMOBRFWPAYAJDDEVUETHTTLGXAEVEPPMPUHMOMVPSQRAUABOHHVZIVH', props),
compute('m_7_13/9: ${c} AJNXRAKNASNXMWOQEIUCOHJZNVVZIPQXWFPAULHQLPMVXEHQNUUYTEHFBXAYUYITZTPVRFIWRUKGUPATDIJXDMKRKCTLTWRDPFCM', props),
compute('m_7_13/10: ${c} KCLLMAPIRDROLIJCTBDOKCHBWPKKCFODGBFPKBXPPPQTOZMXKTBNLSNPALKFWJWRDYXXQBVXDAGLDXRBLXSPHVQIDRRDHVOJDLQH', props),
compute('m_7_13/11: ${c} TIOWOJXASCVEIGVRLPDKVUNIKEOHAFRMLRJPQTRRBPMBZKVRVYNBGZSILREKJLVUZKMLXDSCGAEBDZGTTJJGSLWJJUDKPPQOALKB', props),
compute('m_7_13/12: ${c} TZURGETZIWSZEWUAZLARRZPACTVPOJJYQMRGSNTMSLFTDEQZXYNPDSFLYOTXBBHKMGCMDLLYLXJGDOJNWEGFKZSAWHKABGPKDKPP', props),
compute('m_7_13/13: ${c} GFBTSTITDNFJRJXTXKHKHCTPJYBWUSHSMXUQWACYZJDWVKSJQNMARGWKMUUXFGZUQMYNDIRDYCALPIVAVBINISMHVURPWYZMUBZO', props),
compute('m_7_13/14: ${c} LVNKIGPUVGDVVGHDGLREKWNIGWSHCESRMCWHGNSFJKEMBSZPSQXJJJFHXEXDSXBPNZWWQBBDEDGCVTBLMAEYSPJGDHVHOIALGJZO', props),
compute('m_7_13/15: ${c} SNOWPCSEHIMGDCUZXSUTVSNKPWLXTUWGOXAZOHKUNKKNTJHKHEGJXCYULQJORVHMISGMQZNXUDGXSBMGNVRIXDQLJCXHALVIEPYZ', props)
        ].join('\n');
      }
    