
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_14/1: ${c} VMAPIVNSTQMYAZBDQWUYKVQQLELFPAKLDOMYQTVZHRTKSKIDRSKGDVGYESGJFIDJQDFOPMPHZDYAAPRRDIGBBXIJVCBFNMRXKJZA', props),
compute('m_7_14/2: ${c} HQQZIPGBAYDKRAKPKZPFJDPHUHHDHSOINTYCHVIAVEQNWIHUEUGBEDTHYFUYCMVYANOXEHEJCELXQNSEFZFLMATIUIVQMTGLPJJZ', props),
compute('m_7_14/3: ${c} CQNLLFPKKKTRHAHDIPMIDOVPSXOPXBJXEFLTYKUWWJISUMFDHOJIVQSMXSLPNBBTTUYLXBCXLGVHWSQBPKSFUEFLXQKOPBGGLFCQ', props),
compute('m_7_14/4: ${c} AGGJPKLZJPNIPPVQHSLLRVQLKXQJWRUQKLYXHXEFJQNJEAGFGGXROLVDIOXEJMLKILJPXNFVMIVGUVJESOIXWMJDYIYHPCRGLPFK', props),
compute('m_7_14/5: ${c} SPGDJHIAAPIJREGRTSPOQUKKOQEIFZCWTZFYRZJYAQGPIVAPJZVOLNBFQSYGVBSFXPSKMOMEOOVRCCWCIAQWYVVOGAZGTAXKGCZV', props),
compute('m_7_14/6: ${c} RFCLYYMASSKHQWNONEMDYTCOVXELXDXHIPPADVOPNHQPZARWMYCYVRDPVYOSXNUMYPFSTERDCJOZVLUQEPCQOQXELPDACRFNTVZR', props),
compute('m_7_14/7: ${c} HLGLUHCJCXJIGPGIILWKNDNOTUPCHFFYVPSMMJPYMDNJSSFDXNVHSBVEDDAWJDOXXORWSXTXVENPLWUFCLPVYXUQXIVKOCVBCRBO', props),
compute('m_7_14/8: ${c} CMFCZIROUYUJQWIAAUFIXTNMAFOMYRBFKSWITYOWJLTHBGKORJNZVXKIKOSCBVTKBTNHKPNWYUXINVZRUCGPHZIKNSRJGKTANYJK', props),
compute('m_7_14/9: ${c} EMZERCHAWDKQODAUEZRUDKNLTZMWYXQLIKGYSHSMUSNYMBRKAIRMWYUGAWMGFHORDUQQDLXFTBBXQJLRGVQUXICQFSHQZXQSZETL', props),
compute('m_7_14/10: ${c} CODJWKVVZZEIBEFGPUISZRGIYSTLQTSPSSSLTPMPVJZWZBFDLGCNIIGPHKXHRTGNAJHAZKQEYLZGLWTXNFHFTHDTACSBVBPFIOGT', props),
compute('m_7_14/11: ${c} QJHPILQICMQGGPPLOGZGFOLADZBBBSYASMDUZNKOLPJNTDVYAJQWETPXOAHJKVGBWFYMIBAFWXZSSDUAFDILNEQSNBZFVIZVCOQO', props),
compute('m_7_14/12: ${c} RAOYMLAQKIKYNAAFBQCLZRWPJIMHSQJHAFNSOJRSVQNYYCDTUTFMEPLSRJWKTTJHSWDJUMRNEXCLMGQYYLPCYTGVWXQNAWNVRMCM', props),
compute('m_7_14/13: ${c} HHCNAZNDLHPVPLQHNDVLXHTKKGXREKJZZUBKIFXLPTOYGGQRAMRFTMJVYWQIYSSJACJBFXYKWLDILJKSPGHROJCEZSUBDUFZHOLE', props),
compute('m_7_14/14: ${c} ZVGJTBUBRBPBHWZHYIGSKVXNUZMCERVJSIETKMDMWPQTRYHTLALCLXOZHANVSJYJHBCQHAUDELWNMKYQOGZOSCPWPHJPTTHGDABV', props),
compute('m_7_14/15: ${c} RNRYEJGLBBWERPPSGCYCFDFTCPWTSSTZHHPPDKSNAKSDKXXCRDHSDVRDTYTNVESDIFXFQTLJRNKKGCAIWUMFVTCGPKFHFIISPNXO', props)
        ].join('\n');
      }
    