
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_18/1: ${c} AXXSKGXTVPTGAXAJYFPKBDOSZMFPVZGYVGGGDAKVARLAXBRTUYXEKMCYWQYKCAUCQXXZYIDKRQPWTKMPYOCGFWLRWCYMYNLSFULU', props),
compute('m_7_18/2: ${c} QRFTTBKRNZRCBQYAVNOQSEFLSZNLVKZUTCLGJKXDCYRMNHOWGOVOZWCMZCZZZEMGZJFKJQYDSBKOFYWFOWNAFLVSFJSWCOSJNSYN', props),
compute('m_7_18/3: ${c} IYWNHRDTRNORKIHAJDLIWNZXTOWULLNLGKONZBBVFLKEECOBTXCOCSAPADTSAYJMYZXNQRFJNAMTWVLYHCXKXBWFTHGCQNUXZQOP', props),
compute('m_7_18/4: ${c} WTIQVTYCCDQDFSPKTXBYDMTVYNJBEEYDAEERRUGYVETZRQNKGARCOLPQFQLLDQBPOMKCMBJBSFXOPVJHCTUZDZXBYDDCJHQJYPHS', props),
compute('m_7_18/5: ${c} KCXPYPPDVSCHIPHVJFZDBOZCIBYEGOPSOCGYWZVIPFNTUVCWGYJKUUWKCRFAQWWWBCJZHHWYEECFHSUAGFYAJWUVESYFBJEHBWUC', props),
compute('m_7_18/6: ${c} SANCKQNUOGTDROIGXXSJWFGNCVLYBVNUWINPWRJLCPGVVZEFHSUYETSJOPVBPVEELBYYEPYXFHUCKANHGECPWWTKCPQLHIZXZVWH', props),
compute('m_7_18/7: ${c} OJPJGBQXAEPDUHYWINOUQAIPHGEYBQTIWGBUMJRWDVPRKTACEHFXPOVZOCCMSLQARSNCQMLJSBYBNZSFEPYVWBOETPFRXANPHSXW', props),
compute('m_7_18/8: ${c} WEDNCYWWCIDYKUQFOAVTFXUPXNZZLWDCBMWYRXKJEDTWCAETSSUNWHLEBFTHUTWCJMWVTXTUQQHPQYUDIKEJINLGUOJCVMWEDMSS', props),
compute('m_7_18/9: ${c} XUAOGNNEYQJCKYWKIYIRORLNJSNSLFJHDHYSDLEZDXOPURNCWBPDCPKMQWEQLGNEUJQSLMVDHVEXYTBNANMFVNZSXHQWIDUOZGIQ', props),
compute('m_7_18/10: ${c} KLEBJIMFUEKMCJPERAEWRSKNPZJRHDNYYKJFLXOHBZZHUUZRTMKTXXHTNPRZHORRTSGUVPKQETMELFFZYQWGWYBBNZIBCCWUGCXC', props),
compute('m_7_18/11: ${c} IOPDDCNVBZGFQNLZWOETOOXTLYMUIKQRLDZOBSUAPQLZKCUXUWEAQIPGKYJYBDYIBIUNAFKMWHXAZGBIIWSYNMLESKGAVCSTOAYS', props),
compute('m_7_18/12: ${c} ICLQICEAKPJTUYUIOZPUULLHKQDAAEGQBNFLEYXFCOUUVSOUWYNFJGMHZAMAEIOARRYXWTLNOGGXCURXDDUGWKROIQMVIUUIRSFF', props),
compute('m_7_18/13: ${c} MTNADOVZSIBGYBJPLAHEPJBUDEOFVXEDWVRXHFDXNMMRVDMHHPIIYDJZDOURQYPRVGVXWWNBREOPKFKBAASDMSVRPFGFJXAXXGJH', props),
compute('m_7_18/14: ${c} MNFHODZZESBXULIZANAGDHGCYKZWUENXVBDWRYNJYFEKXVCWPFNGBGSSCVLXNMUAFVKGZLGPGXMUOKJGMKTAITYRPMHWUYITJQWK', props),
compute('m_7_18/15: ${c} RAMTGMPYXICJYSHDADDRUZGAUETJARVMZPTLYRXJQBTPHHZACEDBQBYCYSIYZXFIYPHPWZSDQABVZUYRVJIVQTETVIXKDOPZSIUH', props)
        ].join('\n');
      }
    