
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_6/1: ${c} XBATORSYINNXDIAJSUNRLQXIOHHRAWSRZQPPLYYQMQPHAAHHKSAOWQXIIIUROLCJNEWBZWRBYQJLEWQACCSHEQFTPWQYWZBYQYHI', props),
compute('m_7_6/2: ${c} GYPSHBUDMIUNOGHZAOZKEHGUVCPJBXAKLJDIDMCEJULVMPXQZSHGARPIFRYOHIPVCSCUBVPEMKUVFJDLQJFYUZAUELEYOPKIWURB', props),
compute('m_7_6/3: ${c} GSHXZZJXOAFGXHRGAASOJOILTAYNANPTRZYVBQRXUJRMPJDQHAPYFNDCDRUXBICHNUBPVUGEKFSXVDXHVLHCRSFUTEFPAXVXKFIX', props),
compute('m_7_6/4: ${c} ATGBGJDKZJOCHSRURHXUTAHBKDTTHHQUUZDMHKFNSBEHMQKHTRRDYCSVCSMIIBXAJJWAUVZIQAODKYZWMRBPNDXQWPVAZXBFQUKX', props),
compute('m_7_6/5: ${c} QUROFDBBOAIQXTKNVOHHZFRXJMOZVNAKITXZJJLRUDUUZYQXBXEKPXQBQVXYMXFVOVDEEDYFAGOTSQSNYIYNYGAKDGLDFITTPOOV', props),
compute('m_7_6/6: ${c} MTHMZMSSGCRPEWPZHCVBHAVUKISPVKOLHQXGLFMDOWCKLLUFCTXLUUCMQLRVFHMQUCNSROFPYAEAMFUYVMNTGLNTFHIRRUDUKVSE', props),
compute('m_7_6/7: ${c} UBRWSESIQIZFMRBEFDOZJYJJWGFLUYORKIORHPGWNJKCYRATSZNPEAVMXPYFIHQFRUNMDZFVBIHLASLRRYVQKQGCSLJDPEYLZOMY', props),
compute('m_7_6/8: ${c} JTCRFCZZOWGIONVFUGYVMJQGDEQMVPMKRTAYBOGTFNAHGJTRMSGJZCNKOJWYIGLTEYHBHPHESIGZRHAXSSRLKNYHNJTBNIONBNMT', props),
compute('m_7_6/9: ${c} WHIEDAEZULHNNLJFCZISSNJCUVBIWQNKSMRGVYRQPNSYCPLIHCMKMOYWKAAOYDZSKCQOCLJFSLSDZWYSNPCOSXVZSHLKTBGCNGBV', props),
compute('m_7_6/10: ${c} TQARNAELCLFWMCZLUVMNQXIIGHGHSCWQJHSLWAELFLEMNVUEFOIDTCXUVAKQXSJPUOTNMCPWFNYCXMSBHHGNZDMCLLINFFPMKOPK', props),
compute('m_7_6/11: ${c} UEORCWGXICDAEPFTLNBGAQIWEPMLXFENEQNSIFFIEOYUEELBCIYBYDBNQCXQQSEGKNIPNTANFUEBQJKOBJETZZJVCRQAJJGBSGQD', props),
compute('m_7_6/12: ${c} WSJRBLTGTFXPUTLROWQIFCXFHQGNEHISHDQPAEYKMHJERTDJVVYFZHLQFZVLZTBIHSFYNPCZNEHJNKXHFPJYDASKBPABXNCGIZAN', props),
compute('m_7_6/13: ${c} EQBNOHAPCMIGKUVIFFZVSQYCWMJWBQJGFGCGATMCRIQEMQTBWJNXKGSHUKNFGJQXWKVMFZNNUWXHYHTCSSRCNXFACFOXTRXEDYOS', props),
compute('m_7_6/14: ${c} TBZYRYCODWRQNLLLLELEFNZOMBTPSLNESFMRZZWKQAFZPTAWDNKEXRRPNKCHLEMKPERLSFSHVBEUQIWHFRAHXYBLAAPYHMYZYOMG', props),
compute('m_7_6/15: ${c} GXLKKPXMVEKOHROFFXGXNDKERADPDNWLLARRGXNJJNWJIAKORLRCUHSYSONVQLAMEZOGUUCZAMGWKFDUZIYALKEXTBFJWJQJCRYJ', props)
        ].join('\n');
      }
    