
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_10/1: ${c} TGYJIORIONTPJMPJKSFZNCGSAATRBPQHQGGDMTIBEQEAECEIDNFHWKUVNOPQFZJQKPCFAQXGAOPYHSMNIBEKHABJETLYQAGEVWZB', props),
compute('m_7_10/2: ${c} WDXFQNOHOTRJDGVSLRNOAEAURUNKNTXEEHXWUNGEOAYQRUBBJNPVTONSIFBGASOBLYASFNKHZBBUPDVSSNIJCDUMOOTGCQVCORNC', props),
compute('m_7_10/3: ${c} TWUEMEEMMSYQAJYWAYFKZHPXGNXKDSKQGGHUIDBORJCYXCWGUEEEKQXQOEOITHHHUWWYSYIVGYFTRLNEETXAOUJSNWAPBPGFVJHM', props),
compute('m_7_10/4: ${c} BQROCJOSLYNXCRTIWVBQPFPCXRMYQBGENKRYOAUHVPQWRAAUZOINJZXHXLYLSMUMHFRAEQAHUPLAWUFBFSYZGWQWIGJUBGVJGYJE', props),
compute('m_7_10/5: ${c} RQZJXXUFBBXHUYGLVCMCDFUEFLZECPLBGVKVZZSKIEZVRTPTLCLWVEDJCHJVLXPJOKXEEVLEHNCOFRSTXSVFENVIYSUDKVXLUVAE', props),
compute('m_7_10/6: ${c} QKBMONMYYHUHLXGSSVWONRXUTRKDRPHZVFUEYQHWQFSKWVSKXPJSYGPDGRVGSXLQKALXPDQGEBBHJVHILKZPBFWTPRPWGYFBRNKP', props),
compute('m_7_10/7: ${c} XTYEMOSAQZKTVETNTLSHBTDULBXXPCZTXBDXUDQMHHSVELAIOJRMUKJIMMQJQSNXCWNKJOIVURPZTZXXBZDGIFLUKYCQNJXMULFL', props),
compute('m_7_10/8: ${c} YNZUQSRPKRCHXITDIDLOZIHREVPFWRKEJTGDEBORKKGSFVXKSRAPHTSEBFBTHZSOAICIWZLXOFGIQSVJLEHWHHEXVZOXDLKVGGMI', props),
compute('m_7_10/9: ${c} FXAIZBJDZMARJGLUKQRQBPFZLZMAUFJCZQRYXEPERHLOXAWSLMIBPYHKDKZHJQKATEGDLIGXTYZSHRSVZEAJQWLKFCSWNGWACWRT', props),
compute('m_7_10/10: ${c} LHXSWKADGLXPWUACGMEPPHXDIAZKSHWCSASJNNDUXQYFHFQRTUOFRCPCUZWASWEJJWDPLCJKTVVEEBPHTUCSWXOWYUWGKIOTMMOU', props),
compute('m_7_10/11: ${c} WGXAKAGIJJGIYICJFJIDJWLIDBMIBERJIKOYGVZKMDDTQEMNZGWMUQXTWBYLFKZCLNCPOJVUGEMVEFHJIPQICSCNNBRGFJEBYNYV', props),
compute('m_7_10/12: ${c} QGLXFFJYVQNQFQNWFIXSEHXKPRCZPKJLPFLHJSFXWLBCHUKZEYEPZEMQERSZMGDYDTKJHWUDFVNYLLBQJWTQZHNAGJIBOZCADDOP', props),
compute('m_7_10/13: ${c} UWZIHZARRDOCQVGVXODTSOENOITAOOIZTSROUPYYDBVZKCTGOKHQLFKUVHSPHRMKMUKHLMUWVXUISIGLPKXEJSAEUEBOMVASYRPO', props),
compute('m_7_10/14: ${c} ZPWOVPNDCEOOADKBBLPDTAFSEPHNLUERDMKQSQBTDVDQURJQVZOGNSSAXUCZXBABROFANVAYKQJKUBADUOQEDLJRDIBCZNXHDSAN', props),
compute('m_7_10/15: ${c} LHRXMQVFAVWXPAGSRMYOGHGYCBATVOZHVGSYUMKGSFDVPNZXIQTXDSKXASHREAEIGGQLGLJNSMOKICJKUJXIBXHQOUHTMIYOZFYY', props)
        ].join('\n');
      }
    