
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_9/1: ${c} EEYJQECYDELXOWQJYWCYOFOEGJYMCAPKILSUUWVHZJHXXADJRHEWIEJTCYHTHFZNNZRZEGRHRPQHACYRIVXAMROCIYYHNIINGCLG', props),
compute('m_7_9/2: ${c} EZGQUHPDYZZSDNKUZVLOCBRJUFTRWMMPLSHJISOSZTVQQBAKAQHLVKTMWASHUBQEBZHAJDQCZHVNDSSGGBZLZTYKOYFATXLBTYAD', props),
compute('m_7_9/3: ${c} NPKUOEDACRFJEFOXFMXFSGSMQQCFCKAPPXXVYQGYYZGIVNCKPYNCRVWLRFITELBKLSSHRQKPVMUTJXJVNWNGFXFEQSSFTWOYSQZU', props),
compute('m_7_9/4: ${c} NNIEXNRMKHJTPNDLWWKWPHEGWDDPTZAHVCNSCGQSSPYQGGMROKNBXKVOHNSPWMSZZMFSQAWQDPKYTCCMPMNSCBXETZZTXWFLXLIV', props),
compute('m_7_9/5: ${c} YJTWCFXYZFNKUQYXXYMRLELAGEKAAOUXHTFXMSUVETMAIWQFWKENTYZDFMKJHYBKGIGXWIHUHREASRZVWEEUWKZAJVQFIHZMZMUD', props),
compute('m_7_9/6: ${c} HRYBHECVMUHNHNNBAUXBUQOESXFWICXIXGDHVLCMYLJISRXLXAMAKRTETLXYOOUCXLGJJXZBQZARGJIKITQRRSNANOBVJALAOSWE', props),
compute('m_7_9/7: ${c} YKQQHZMHDPCOUVTMFEIBZYJIVSYRKSCDXVEFMCAEYFBIRMSBXKIEUIKMUPIQLOKGGSISVTOBIFJWEULMXTGYTFBSBBXMTMBDDMYZ', props),
compute('m_7_9/8: ${c} ZGPXUYEIQZWSXSYNCTGJOHUGMAAVUZBUINOQDCNRWSUMRIRDHTWBBRKPASPAAVKYFRHWIHXFJSNGKCFKZXOFATWAQUFYZCWNSKVA', props),
compute('m_7_9/9: ${c} OIDXKKXCILUPWDFQVKFJBYHCYXNUEAAQBZORGLKCOHLJJLXNSARIBBQGUUKNWFJTJHKUTGAPQBRKQZEOEEMZMLMMXAMZZJQUAWCR', props),
compute('m_7_9/10: ${c} HCYIMWWJCGBCKAEWZJJRGILFTCGWMZAMCHSJVXFKEFLXLVYZILPAGNXMPJSGZZLXQFTXMUSWCXHPCRFQJYNGCMOPULPYPFNOETGM', props),
compute('m_7_9/11: ${c} EEFOFRJAMPRWUHZJNJKZEXFYOYUMXLZYQKXDBUMFYAECHOEZDPPEOJLCIDTENGKYIRZTNIBXIOBLXKJTJKFOOYMSEXMRZJDAIPMN', props),
compute('m_7_9/12: ${c} RLIICBYCEIZPPNSFXPDCLVDGNHYBMUPMAWFROAJYWMIMAMRZXAKIAKDTTCXKAMKRIVQDQMNUVOHYLYPDBWJUSGGDYIXRETFXJHGN', props),
compute('m_7_9/13: ${c} UBHBQCYSBDGAIWXPFGIWQZDWDPQVWIVKJLUHBZQJRFFXCNSRIHHPRFNWYVKBVTSYPHBXAGJHTHWWNDVXBBTGNDWZIJIFSWXGQPCN', props),
compute('m_7_9/14: ${c} DBFLDFFQJZBOFUIEJWYWBCAOUJHIVFSPRPEQMPXOWEXTDKVOTVPQJLQJHOVKKHWQDWRMGGPNWAWALDVGMRIBKIBMMZWHRNIOJJTO', props),
compute('m_7_9/15: ${c} BOOADYCPXOJGCQTBFOBTLAHVQHIKEUGRJCNZGFHZCKWWHPMAHSBHYYZITXTLUALNUAKBCCIWBVAPZLDMGYDEXPGRHWQHJMHQJVKN', props)
        ].join('\n');
      }
    