
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_5/1: ${c} OWRNALXBXBHHXTCFGTUZWGJMQHUFNYSQZDQJMRNPBHCNGPDRBVHRMSASOZWGWZSXKFRBPTOXNVIVJPTRGPGKJOJMBKLNLZGBNOYX', props),
compute('m_7_5/2: ${c} BVXSPXQGSCXTHSZOZEIHGWORAYSYLACTVNPOEKSIKMQKCCXKEIPBTYYERTDFXMKUIYOSGSHFWFORCVAUFNTUGXZVTNKIAQTAUXYT', props),
compute('m_7_5/3: ${c} KAVKRLIJLBNOZUWNYECMGHDWRXRPRDEETUGBLGNEZGDYLMEPZESMWEILPUCAZYBIKKINCZURVOLXIDSERXVPIKWWEGKESWMKMFQE', props),
compute('m_7_5/4: ${c} UYXUIDRVOZMNEKZGJCTSMMLBEKMXHLMWVEIDYINSUCLJOEHCZYVLTZXGOKCIXTFHHUIEZLOZYZRFLBBEJMCQSYQUQUNRYNUEIEMH', props),
compute('m_7_5/5: ${c} MQKGLGIOLBEXQMHXKDRWSISWFOBTSKFCXQZPMLRYGGQUJOSCAUBJEFHIKRKFINBTSUXAYLAQYWZELLGQHBBSOEJSFSXUXPZAWIFQ', props),
compute('m_7_5/6: ${c} XEBOIKJEEUMCQMKXSHJQUMRNJPFGJKILUGHQKKNPUOCNZEICDYSGECSTANBRVTAFFPMIDLBBQTKKEDIRHWDJIBQOZWFQRMEGZXDT', props),
compute('m_7_5/7: ${c} OEDSNDXITGONPRAIGCAMISULFBBTCRCJKJOZTCVXULIBOXBYHDGJYHMJIDGEMBZYJPWJESPWDWQLKXQBNLRKKDVEPIIOCNWYHZLF', props),
compute('m_7_5/8: ${c} HEWVFIHQDTUSCHFHWQFLOCYVTBNXFEMCMWTWVTEGUZTFYEELUPQPLWGZVWQHZWKLJTINLFGFTZMSZYZCJASDRNNKIOXICTLXZUCF', props),
compute('m_7_5/9: ${c} YWYORISQJVWWKPKZJOKRSMFZZBARTTDFNZEKKVWNPZKWWKYVJJRPPRQIYIQIIXNACIVQOCJQUKQEZKEMQJAOIOXFCNRWODDYCZGJ', props),
compute('m_7_5/10: ${c} OLJQNQSDSBSIHPDPZAEBSCDMKYRRYMWNXVVTYDBBIARNVYXGXXADOKNSDNUQBBYFDNDVVRKFOFCVRVSOMWEYKGWHVODEIORYEJWA', props),
compute('m_7_5/11: ${c} FWTZRPIKUYLTAQQGOVBDESBLPCQZABBKLHLYJQNOCPOJLITADXDBXKESDDSHWYVTDXXTYYQRLCUAQQQIFPASEFOCUOYJNTXKOMFD', props),
compute('m_7_5/12: ${c} KYAXACJBRCBXNDNDSRTKPUPVDDTZQWEKTQDJBZPWAMXFUOKQDUHAEJPLCSNOYDNKGGGLJFPJXPPELNSFDTWPVNZHGUDZRXLRLXYQ', props),
compute('m_7_5/13: ${c} PHWRZOPPGGWGOOPQGPSMGUSNTEZYOCDFGANPHBZWUALALWPFPBLESVLJGKBETDQYKLIBKIXTSEVARHIQJKYHIXJZXICIPOFSFUJR', props),
compute('m_7_5/14: ${c} YARRTFHGBNVRRPDZSAZQDLTYMJFVEFWMOGCGLHTCRLQOHXDSICWRPHXOCDBDZGDCDSTRRLPIQEGRQEBMQNRUBHISPOGHRDULMSAX', props),
compute('m_7_5/15: ${c} CXISOYGPNDPLUQBQYQSIGIYHVBVMCPLPVERCGARHKKPMHCJQLDKYWPAPMWTYGTJYNFOJHLNXFTMHNREARQEDJQVLEOQCCDKRNBPH', props)
        ].join('\n');
      }
    