
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_8/1: ${c} TECZNOKOWLBNLGDLADPDDDQMVMGBJYKEXIYMJTLEBXVOYDKRPJANXJPESOYYIBVPJBXDECZPFSRKKFSNYSPDAHXLEJONAIFUIWVK', props),
compute('m_7_8/2: ${c} RYQQNPREPXMCZVYAMPXRZQOMKAUWKFIHXARTCXLDIUTGUCSBDGFBMIWDXKHYLEKLEGFFKBTFKJPRPMGEEXECKYUNZXTQYIFCTPPJ', props),
compute('m_7_8/3: ${c} CIZRAEZRVCVROHXIDQTMFKYKWDPLUZKENKSBAQNOKWZILUKXPYHADDKKEKLLOHXFPUTAMZWBDUNSKMSWCAPDEEMMFTLKFBIXWQHD', props),
compute('m_7_8/4: ${c} KNSSLXEDMTBXGYGTUYTUNWSBRPRFOZTPIMXGUHLZVWRUIWDYDFRHAJLTNWMKBVTGWGCALNLSLYRAQDUHXGCPLLQVFHCPOWRPQSVX', props),
compute('m_7_8/5: ${c} WBKXSQLHMSGBXEYQLBEGBFDNQZVJYBQMIEIQDUPRVYLRADLHHGKHUHOQXMKZZLAMFOYDWYUOIBVCBRXVDVTZKTDXUMNSOZWVYQTV', props),
compute('m_7_8/6: ${c} GOCGSLWWZFIREDDOQVALYIPEODKHYETADOQOORJNWNFUMTMQCHEMSWTYEAFMPLDOIOIPQOTVOZREUONFVOVZQTTTNWKTOUVXZFGP', props),
compute('m_7_8/7: ${c} CRMHJROUKXIUOPMTUYAATHXNPHKCYWQXNYPADHEJBGSLDFNFJUOMKYLLLFFQSCFBEEOPQMSVPUFNHUMZYKCPCSCIZTTMPEQHOZAU', props),
compute('m_7_8/8: ${c} MOJGLCODCAPMJCDNFTYUSSROHAKDCAYXMADYTTVKLLBBKZSCTSOADXVWJTBIWMHFQETOFMWKOVVBUMDKRRWFHPXQMCBWPQVGOCHS', props),
compute('m_7_8/9: ${c} UITRYRENNBNLFDCXWJLKLYHXQKFOIAGCYTNKUCZHMAGWJWNEOPIUFUHGLXSYCZTGFQHACDKJCFKPCNYAGYBCEROTQTAPSPQXAEGZ', props),
compute('m_7_8/10: ${c} KDHHLLVLZASWECSKCZNXYTGDWXUUDWANQRHTNNVYAQSQKYCOBDCQLVHXWTMTMXBIBBPHGUXPFMWELPGKIYDFBFLRFLWYGYTHBWNG', props),
compute('m_7_8/11: ${c} BFNECXJYNBLZSGCWONFYBBLNWWLOOIOIOXWQFPYBTXVWTGWRAPQTNHNWUWVRWQBRQOCWGCELQTGKFBQGTJAGOCUCNSYLXHSVEGAM', props),
compute('m_7_8/12: ${c} RQPPSSNZQDSAMIXOMZXFPZXWLSXIEDABVDJDNOYCCTONJNEAJVHJKFDQKRCOMDVNFTAPLRSADEERFPSWDMGOSFQAVHRHNGUHNBNR', props),
compute('m_7_8/13: ${c} HUTZXGTQLUFZJMSPESWQJDSFCODTPFVQTVZIETIEFNHXKIFTVEHOTCPDRRPXNCCEVRJBUUDJLPZTRDCSGQOXGCNEOCOKMJFFUUBT', props),
compute('m_7_8/14: ${c} IDZKDCLWITDTBZZYJIEHEVXJHWTRTKHAGXNGTVZCWXVCLSNGVISNQRCOBCEKNOHJMYHROWCBYCWTPUUPAQMKFAERNPWXQJRBVVHY', props),
compute('m_7_8/15: ${c} ESWCIYSARPPMWSTLOHETZHQANIXEXKWGBNVXDJPSQAGDCOAZPFDQQBGOENOCAGANJCOHVQVBLGGXIMNHAQHKZQLLEVSXLEYERDPM', props)
        ].join('\n');
      }
    