
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_20/1: ${c} HMJSGZETHJWYORGFBARICUHVFWSEYCRUFZVBTOCTBAONXDTRQCFYWODXNHJQLHVXKKLSKMCGWZGUWJWNWVYIUWJTUXWWTCYIAXFX', props),
compute('m_7_20/2: ${c} YMIRZVKJJDVQSEPHQYYIKWOOQDDXAVSLUJCPAPQAQFZKPNCYNOMKRHEPQVRUSWKBVWCRICECJJAAHDABPUXOHEWURUOQAHYTYEWC', props),
compute('m_7_20/3: ${c} UPDHNPTCNXGRNAJLCRZYXHQASTCVFVJSHISQDNCFUTMEOGNBDCSZKWWGQNKWZDJTMMLPIDRINIDPOMRMYULFPRAYBAKHKBUHCESP', props),
compute('m_7_20/4: ${c} WVGCOAJXLKUCBDGMNVEGOGCPVDEWFXLRDMGHHZLJFERALNAJYSNRVNCPEOMSWDPAWQSFJSABGGBZQPESXUMOZFMGOBGHGAKUMZMZ', props),
compute('m_7_20/5: ${c} PFVKJKVHSPHAFKEXLLTSCMZKEVZXCDDOIVQMECAYUKGSFYPQXADTUMIQNICNEFWRZTENJLIMQZOHGQQLCNZLGGUOHHBEDRZMLBNO', props),
compute('m_7_20/6: ${c} FJXQYUVWDHCHTZYBENWMWDYOVEZAYNBFDHABVAERNEOWVTCIJCSNDXXCPOHNSAWSIZBRWMEQNLGZNPVYUOPJKUOVUWMFADDVUSTL', props),
compute('m_7_20/7: ${c} OTNZPFERETZMBZPDLNTEMSLOANUBYNWXURXXTAIIOHLTHYIKKININGHSOIXODTDUODJIKMEGPXTKJMZRQYDXDBVQNMFEWKVEOQWZ', props),
compute('m_7_20/8: ${c} BRAXPIQZPFFCVTNQMTDOGVMMTDGTUHUPXNUEANZOQRRGRGHDUWXUFNYDEONGPISJMBFGOQVWQQCHZCGRXDSBVVLDYSTFGQQDHBSA', props),
compute('m_7_20/9: ${c} YSXEERKHUPGJIGFXELDEFGWOCJULUFQXQMJDPBEUSILFPVOJQKGYEOJUCPRWXHEWVWDUKYHBOQOEQWDXJQMDXCRDRTUVEZPKKGZJ', props),
compute('m_7_20/10: ${c} PWHJHZXUYSSEJOMMDZQXPOYELEVODVOHJXGXYVTHIRRRJTDQRRRCBPZDFCWHJRRYDPZHQKUJXRNSVQTKQPDGBNIXJOHUXFPCOGJE', props),
compute('m_7_20/11: ${c} JRFMLAFYPELFEGCIBNJUOULVIBGCCPCQBUWPSXBPYQHRYCMZYLCRJLFKABRGCITDDETAZDEZFTNPMLYDKYTVWVJOLZPYDRQNRQCL', props),
compute('m_7_20/12: ${c} EVLTGCDUCMFBDXJSCNRSWNHXLOHFUIXXOYVKUINTQLKGGKEJLYQLKSBPMPKYBEJZFZWPVNIFKGWZZTKRHVYPDVQADARFUAZKUKPP', props),
compute('m_7_20/13: ${c} ZXYWINYEUMBMMDKQZTSKSXQIOJWBSOROQCUJNZJZRCSHXSUZSPHXTZUIFZZQXNGFLMUJHHYNPTANMEWEVNIMHPHAMLZXKGQWKEPD', props),
compute('m_7_20/14: ${c} KBQOZOSFMKDPYECZELZCXKYVPPEYAIIEDHGXVTIQZAIJMQXIWPDDBMBNRPMCMPNOFNZSMQQPTYKHWNYQDUMFSVIXZEJHEIMJCSPR', props),
compute('m_7_20/15: ${c} IJNJTKJJOYKQEVBKVOKBTYVPDPCDZBHYSGSSVXHEHTEMWCUNQLBAGEEOAYYJSTTTBGHMSNIXMHHZVXQVVBTBWKXKGWKESYJTLDSR', props)
        ].join('\n');
      }
    