
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_12/1: ${c} YNHLGHTWYKAHBFBMHCDTLUWDPAQGOSEPHUNUJMTASCVTJUKCNOBFEGLKIXJVWFIYYDWLGTQGQFBQLCTAUWMXKFKZMCSLXZECIECA', props),
compute('m_7_12/2: ${c} ECKWWNYUXHTDUIPOINGLPNVWFRWORMTYASLMHXHXTDRKWVWLQTVHDHTMTSUUJAAPHWMZABRNGAALVBPYIXXWYPYCVRFWYUKNXOYQ', props),
compute('m_7_12/3: ${c} EEZAYQEAXBWDZHDRQUQBBMYWOPYODVHNIIVQDNPWZVYXEWZFEBJKILGBMAPFKGUDAVLOQGQWWGENHPWLDKPLQDOMPXTTEAPOILZF', props),
compute('m_7_12/4: ${c} CHIFCAEDTUXQLOTGFWTACQVLVQNDBUJBPIVDQXNVYYGBLCVXXAUDHZXEKBZXSLGLWEMRDAEZGKLIWHBNACEENUYTFRWPQRJSVEVG', props),
compute('m_7_12/5: ${c} JFTIIJNMVJPDUCZULQJIHBBVMEOCMZMFREFENHHIJHMLTFMLZWAPPWMFGSHORDAOJZRZXSEGVJAIFNSEHFSZYMSIVRPRRJPFPIMQ', props),
compute('m_7_12/6: ${c} DQTULPQUDJBVSAPNQOVPOFEOTXQQVOOOLBFLUJXRESZJIUVKYYDJJRRBSOWAFPAACATGBPGNQKGMSPFKFKNJYXZBCYRNROHFOTKG', props),
compute('m_7_12/7: ${c} HAKMRXECTQHVEQMRPGIBZIGMBFBTUJLEAEICFXOALHZZMUTXZRVHBHGGHSQIIHEYKHXVOKJAHWUJVMKBLYSVLPEBXZKAFIGYNDYB', props),
compute('m_7_12/8: ${c} OZDAFQGDVRCESVKVAFOHNPDAVRMVBOHFCKLRMEENVXVNGVDKXVRLGOJMXNUIIVHKDSUKPYVAYZJPAMTOWRPUFFUGLIIILKEZAXYY', props),
compute('m_7_12/9: ${c} RKNVJKWLHZZNTBWXXAFFXCOZBYEXIKAALGLVJTFVAVNGUBMNLQTFSDXLRMJJJDIWQKVGDWERWHPFWECEPOTBVCJSTYLWPXGJVCLW', props),
compute('m_7_12/10: ${c} RNKPCJNSCBIDDSHBDPDYGXPNHQUZJAVJQRWMEVRIHGXVIHCIQEAINCBDQJYXWEDOQIBFAOTNJDKBXAOMPAPBDMDJATJIWAAMCBJX', props),
compute('m_7_12/11: ${c} ALICCBZTDSQPYCBGPUUOJHGTGBSMUDMGMEHOFNREMKYPGEAHNDZTBNMNDQSVNODWWZZPTVRPGBHNHABTQQVXUIHDFBPEVEYYMWZQ', props),
compute('m_7_12/12: ${c} DLZLVAIUCGSRWFVAHVPCJQWYHPHCZIASTUXGDHQSAZKOYKQOLUIWDPQVWATASWWMGENPTWNLLJOXFBBMTIUDBIVASMMTSIYDSLUS', props),
compute('m_7_12/13: ${c} CYSAMEQGGNCXJUEHMHFCRIXQAFPAHXQIQCXTAERTJDQJQCCYPRDKZLWKDUCWCSPPQMSBTMVZVKZQJJQEXEPSIHMSZHNUXBNXNUXN', props),
compute('m_7_12/14: ${c} NIWUPRSDFHQKICDKFNAEFMINJCJBDIIGPBMLEOXNEQVWBJRGKXFWAWGOBBNQRIAKLKBSPGFPDHWWQDRLCDCCGSMRYUJDLKMREZKH', props),
compute('m_7_12/15: ${c} VSWZGHXVCONJHCYNSCWYGCBAKULJPUCEFQVOZNYYDHEZIHGXFIQZKANPEZMRDBFNUGAGNKPLAWGQSAGGYJCINMIYJMZPOCMLPEKY', props)
        ].join('\n');
      }
    