
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_7/1: ${c} LWTVVPIZSSLBXLTEGOHDWGNJTTFYDRYNZPXTMZMAUHTLCQEMKXTQDCFBBGKVLSDKKFLASPCVEKGNGUKHMIGUYEUHQRDOFTZBYEET', props),
compute('m_7_7/2: ${c} POVZSMFRDWAVICQEACDFTOEIZCKXVWKAVOBGSMKYGPFHYIEUYPEGJSVUDDLWUVFKHLROHEIHNCOXWGTWEEBEVDNPUOPVNROYNIIA', props),
compute('m_7_7/3: ${c} FKNEVDURUPUQTUBJWYJWJCOVYEJSCLZKRDNGLVOGPMLHKYSJDMRZXZDTYYNPYEHXIQFXRFKJYYBGJJUTSHALXXRSYFHNXAEJMNEB', props),
compute('m_7_7/4: ${c} QMYMKRZTMHISTPXRNQYTJBNLYXBZBVJUBXNKEAUJKVDNIGYMPVSVXJLGKZNHTWFHSMOUFPWVYKNTADMOUJNNSFGFLXIOSEQRBESP', props),
compute('m_7_7/5: ${c} UYFQZOGLRCJWOUVCXAKNITOZSLJTRCERKRGITBPKLJQEKRABLCNSIDDRAPVJRMVMNKLRVLEWMGPWPFWOMSHBPXXVRMFAWEVLJSSL', props),
compute('m_7_7/6: ${c} CEKJWXWMVENKQGVUDSXNQOVXYWQMLKLRERFPBZYHFSJBUAXFKJZFBZFTGXTULYZSJGEUMLEOVOCAZHEFLNXDSCIOCLCMJXLPNLHO', props),
compute('m_7_7/7: ${c} VXHCTYLMYOMACVTDCDHTGOHNRNVYPHMQGYEEBBHVIRXQUXJUNKSMBQLDOQTVJKDHDAWHLBHNFOAZOUBPZGPRJEWMGKPVUOXDCLQB', props),
compute('m_7_7/8: ${c} MUYNQYPQUWURZKAISWNTQVNBFPZUVCPJXLXUZCFGCJWBKWRXEIQRUUKMNWYQADRMUJBVIXQRKVQNKSDWHXDGQRCMEJQPQTFJMQUE', props),
compute('m_7_7/9: ${c} JLUWXBEJYFBALMIBXPQKFTGLDTMXWYISRXRPKUJKJRUJJNIZBQMPBMMIHTKXQPADGABPDLRPGDCCYKJHXZSXOEUUZMTUIZQTRMDM', props),
compute('m_7_7/10: ${c} WIBMJPGBCTENRYTRDWZWTEKAVYKXRHEUMTZOSPPUKTKUTMGWZYOSCHSQHEPJMPNCIMHQJOLXVUNVXKPBFGMYBHMKAHJWHDQPCYUO', props),
compute('m_7_7/11: ${c} NLFDXAYOLFJVVIKKUFSLZLYXAEKRDEYKPOBHWWZJODEOORRZFHQXWCXXUIUPUFGHSXFFRQZLNXYEGBODFEMTSBRWSWPAOEERBPYF', props),
compute('m_7_7/12: ${c} VEMWRPXLNPSDMBWQQITJEZGIAGDCEDRWZMZSWEVYZNSRGRNYAOSPDOVFPANOEENKBBZOAYMYCBYIHOXENDKMJXAXHVWCXXRBVAPN', props),
compute('m_7_7/13: ${c} IOTIZCXBORBYMPUGBIYYVRPJKIVFONPPIVCQNJRTMLEUPLSEUYNHRJSWLXKBRBJSSWRSJDOTISIBGZZQVVJQODXXCAHWXDMGDMVZ', props),
compute('m_7_7/14: ${c} FOJHZIATEHIVXQHVCAPYOKEGLIDUKVZSOVHMEEBVNZFCPKTNFXSHZKUNNAWJUWGTVXHYDTUIQFLWINXZYNKLVFBXPUDIZKVICNOA', props),
compute('m_7_7/15: ${c} TBQPFVTIJPRTEBCCRSWZNYWEPNHOKZUDVIATPIIGYZFOAZMAECFSVZNYKUMDSUNGDHPIXBADWZIPTTTVKIMWPMMLAPBKKFTWOYYT', props)
        ].join('\n');
      }
    