
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_7_19/1: ${c} TIWBMSMVJWIOELEVZTYLJWVWWLBFQMMBCXTOUCWGCHKHPRPMXNFGPPJDPUVNAFCHKRPSTVMJOKRHNDGXBHLZSYAYQQJWHGEHOLHE', props),
compute('m_7_19/2: ${c} DQRJILUCHHVOCNJHXCZSLQGHGGVIHRXEITFEUUZKRUTZMIRMJVVQZRDVMTCLTCCBVDZYQWRPUCKKUYYNXJAFQRFCAVRIOZNCPFWL', props),
compute('m_7_19/3: ${c} YFELGMFPKYENVIVUOHAHAYCTWKEKTGJKWKSTCPLXBZMTHEWDDXTUDGHYBIVWZAXZTYUYRMPCIZKMZNGJDOJGVMMHIOEYJWMTKCVV', props),
compute('m_7_19/4: ${c} QUCUNCTFSKCUMJLIPXFHHTJIDMBWEPOHDJIAQKZKISXNZKFOGOXMNOCQMKBNEUIHQWFYCLBPYWVQZKHKZIJZRDLWGWFVPCIMRXXA', props),
compute('m_7_19/5: ${c} CAVQYDEMQVFIGGTFMOAUSDLGEIHALWOOEWIFWDZZONGQJNXMLMLZPOYLBPZJYUVXEFGOJPACGRUYVLHUBRUFJZRFDOTOYHSPKLVT', props),
compute('m_7_19/6: ${c} XOIBFMJKGEPNDEAZAQAUAISJWARECRGBIKBXWDSVADJZNHZTHFJPPMBGGNQPBEYOFTBITFZMWHEENJIXMZMJFBZWWBSAZSJTSXRB', props),
compute('m_7_19/7: ${c} GAPVIETQMUXPSWWLBGSZSEMXRJYFKRVRORWNYIKUHTKYPOOPDAZEOFCDCJVIMUHZCVMRRLQDNDDXDQIUNZUDNBARRALGSWMUEAQA', props),
compute('m_7_19/8: ${c} VABRHAAHOWSWVBPXXUHZSGPTEQUTCOHXUIRTGEIQBMBDPVGFQCXBJIXFKHZMFTEVYKLGXTWCHKFLOSYHAPKBILIQABWFALIQUZFC', props),
compute('m_7_19/9: ${c} OSHLUTDVVSMGRIAUMCBFFIJNGOEUQNGEEKCFNPLZGUPNBJUDHFPEFATPIETQQVYBLIDOXVAWXFOSSAJBDSEVPPKUSPLCALFPQQIP', props),
compute('m_7_19/10: ${c} IIEEGZXCNUTWRSJVBMZWGPCQEXQDTYPGSOSYJTLVBMYXDUDYIESVTRYOZSVZJVLMZJBWZUYIZELUYHLEBUMCMGJSJZAWWISOQNOK', props),
compute('m_7_19/11: ${c} FVEDUJYPGXWCERQOAVKXOWJDNOMMNZBPCSVMCAZTGUQYHGLYWEYMLWOGTORHCRUULSSYDJLDPBGVYCPIAEXTLOXUUYOVGKTSUOHS', props),
compute('m_7_19/12: ${c} HRDVGLPDMQFLYAHEWOMYAGHKGFXJJIIUPQRHJEJFOMYVDPLDNKBGXDJMTHFQZCSGPOFVFJQQECEOCEJNMDIMUFWZFFVPAXRZTBYM', props),
compute('m_7_19/13: ${c} BSQPZSEACSQTIJFRFTLQQXOISGSKSBDDUAADPCZGAPSSLDJKUATUMASWJLISJZXGPEOOYMGYRCDORMLBDIHDWDCXFKHBMGEPMZAF', props),
compute('m_7_19/14: ${c} TDUPSTBYCBSWDQHUEPXLMUJPSCOXNGSLIHLRYCAJOFCBKVSAJAUTCSXXAUJKGJGCOSFZXQTTDIKNPOTFSUGIFEITMYDJWXEFWXMK', props),
compute('m_7_19/15: ${c} SGIYBEOKNAWTSHQQUYPCPYEPZCSXGAWLWYQPEFCXQCGQYSCTLHWFAMFYTPMIUTDKAZAIKSZHMAASEHDGIJOBRJULEBBXBZHYAEMS', props)
        ].join('\n');
      }
    