
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_18/1: ${c} PAMKIYZMZRGXJDIRMOGKGJZTSYQHFPQKOOVWFZIOCEBBKOURPZCHZPTJPZFOEOWHTSSQZVXRLRSXWNQAHSVVPOCJTAICRKZMCIXE', props),
compute('m_8_18/2: ${c} ZCQWVANRHNIKGPWAHGJBHAGXZRLXJKIMDCMVJZZBEVNIUCLMNKEUCMUROUEAMLFEZXNZWNJCMYYKFFQMTDSJGQPMEATLAOGOOPIP', props),
compute('m_8_18/3: ${c} TRDKPQKRHNZFAUBIUFBPTLAOTAJSCJYOCBOABFEPREAGKJGJDUVBXAIUPKDRFARMSUALYIYIAOQISOVYKRBKIAEDQBBWGDPFTCIZ', props),
compute('m_8_18/4: ${c} EGWAVYNYEBMWFNWOKTNWQBNCAUHENKAOVYKLNZWPRPBNDSNONGPCAQNSZZSAKLWEVFBARAXHPYELPFVFOMXELYHQNVOITKQMXHWG', props),
compute('m_8_18/5: ${c} FDNJHNDSLEYSVMDFVCVWCTJCCYTMYMIGIYEIKSPTYOAJCGVUSMHCCSTMVCQFYWTJWSVKSBTUDHOFUMWVPVGMAXABTNQLDXUCBNNF', props),
compute('m_8_18/6: ${c} OUATJXEFDFKNKNZYBYEAKGJWPYFXZIMFSVRTFQLIGQHQFNIKDWBWSEUIKMWDROBPYPZAJWXLTJWXWANPDZVBHRUSNJURUSICKLKY', props),
compute('m_8_18/7: ${c} YIFSSONLSICLKYRBKEZBQBWPAMGGUHCCFAUNHOMHALSFWSEAWURRNITRLRVNGHMPSGLWUONGKKEWYQLIVEYAKQWRXHFLBUWXMYPK', props),
compute('m_8_18/8: ${c} OBIGZADNRXUQNIEDDYOVXBHHDKSSGCBASTXHJOPPSRSRVJMPLKCWQKGCGAZRZCQFXZMMPSOAKIJOODLJQDARCATHFHHYSIHARDPL', props),
compute('m_8_18/9: ${c} YBXUOLWHLTAPRAWOTAOOPLCSRRTPZFTIEFYFMWMOITBMHMVAUOUNJXMBCBDZEKQGOONFHNGSZLSFFGEZJUPOPTXCJRLDFHLSDOJB', props),
compute('m_8_18/10: ${c} LTXUTJKHSWDXCDJFENAXWOCINJRQUDJEMZNGVMSYMMILBDDYNGXOEQMKMSASCSUSWSUDWVTSHUDMJSMYIYUJMOOUUNPHFANJNXRC', props),
compute('m_8_18/11: ${c} WTGTRMEFEPFQUVPBGPMEXUAFZOSHSIEFXBIUAFHWWJDRXDMXQHOCIEIJZDBLBSIMYGOBPSGVMTBEIPFNRILEUVJQQHMWUACWSLEY', props),
compute('m_8_18/12: ${c} TXFWVZLIZCMADERQWPJWVDCYANTXQLDZGVKUUOOTGFRWVTVPKVKBCCMFOBXMOWEJGKSZVRYMKPOSXFVORGIYCWNLNBQESLMXQZOT', props),
compute('m_8_18/13: ${c} HQFEIUURQAPLMNIHHDDZJDJWVUUEBVFOIMXDVYHGLBJPINJVELIEQNPAITOSOEGCXTYXBUVBGAJFKVYXOQKZFACPTXRXOFAPFICR', props),
compute('m_8_18/14: ${c} FVDYBSRVIWSYDBTWWHNZFGBRETRZZTYXGMJWEACFWYRUNQTIMSYTAUSQAWADOPGJFTKGYLZLXKVVVLPXNJERUAMROVXOZSWTMCJC', props),
compute('m_8_18/15: ${c} SYEQNWNEBBRTEYXEXDFQABYAPJMQDACKOJGWKCPWIETKZWDBMNOPZOPHCBCZVMCXCTHZFLGFUVJFWGTKHKBYTTFPCBNZCAVJVAZP', props)
        ].join('\n');
      }
    