
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_6/1: ${c} FBIBEIWNQCIOTBNEQHGRFMXBJHNUDBQHYKOCCUSSCPJTQFWLQYUYAPEEMRRXFITNVXEOXQUXQKVUQCYSGPCRYJTOXYUNVQJEDZXB', props),
compute('m_8_6/2: ${c} PMPISXOHNBLCVFSHQGIRWRZBPUHJSXVCCJIQSPKQZUUOWZPKYGBSWYLRQQOZNDRCZLLWSNOODQXSNFRZNXBVKQMUSNSTMEGHVSWH', props),
compute('m_8_6/3: ${c} RBXOBEUEYDCIQHGTOPVGCVZULBFWTHUTTYGEEFYWDSEUIKQRSVLZJJYTNPOJUWPBQFSKOXEYCAYWCCTLHEARHULDNTMCRZTKRAHH', props),
compute('m_8_6/4: ${c} ONUUGIAEMUTDZWZRESGEAJFEQHOFDBPXJAQDQQFWRAYPNCNQEXGIAOUZRSGBRGPVUUEPCUCKKCITBWLSTETUQLKFEBKFROCBLBGU', props),
compute('m_8_6/5: ${c} LLRGJTBPIQDRVXDBBSNRKUQWRTPZXLCCLSWSEYKDFBKMWOGQJBGQBWQYRXOXDZQRKVSGKZHADXMDQTIPVFYLFTUPREUTQJPHDMDV', props),
compute('m_8_6/6: ${c} MASQQMRHJTBFINQSMZPSTMYOBFEVWHFPZBOMYAARONTBHILKMQLTFYLDTNXTLTVGTDIQTRIVJOIFPDZBLMGPWAENWAWTVKNGXWML', props),
compute('m_8_6/7: ${c} FZRZTCXQIHNLXAMFSEOMSTZWCAHGUTQUGRRJNYNCGSRIXJIELWIEPNSVEZKDIFPMXATHSEQJGNRQJRVDINSIUUISCPTMJGEGUPBK', props),
compute('m_8_6/8: ${c} WYPFKDKEKQOTFIEBHXIYRTCATSWSZJKJPIGGZPRZFUNEQKVDDKANQZPGUNQCPTOVULERQLRGARTSAPRLUODUCAXHBNWEOEGHPULI', props),
compute('m_8_6/9: ${c} UECZEOUBIBTOGTTDFRRXZFOQTLADVVMBWEVAQFIMERCGWAHVCNESYSFXJRSKEUENMJGDDAYIFZEUUVZRTJSWDXDMKWQKMBWPEUXO', props),
compute('m_8_6/10: ${c} WQQAGPMNEYSDFKQAMQQCYBTWDLIFQAENBKMOPGIIFXDKEHHEZDOFXLTXGKCNIJEDMQBMNRRTJSPTDCRYSACPMFWKPNCJCOJYPWPS', props),
compute('m_8_6/11: ${c} QNGKPMUHUDWXJXFSMUBTYJCTJPDLCAJKXOJVSITPKHQIRJTSEPORDGOMBESKDDOOFQCLVXYTEUWPVDGTGJJRXDLOSJZINDSHKGIU', props),
compute('m_8_6/12: ${c} JKRPKSOGACFNNUWJBNPSTJIEFAFSCVIPNJYSKEKVEVFHNUNVSDJPVRHYISCXXDUQXMRSDXDTXRKUNRNVXFWTRLXMRMYBUGVTNFDF', props),
compute('m_8_6/13: ${c} XJFOQDGIZLDGPRFAIETWYVKTLOCZFBODKGQXWOVRWSHWIJQEPSBQVJQCGTEJWVEKWLOQTFGCQHTCJAEXRPZUSHYFWFBVMFRLBUDI', props),
compute('m_8_6/14: ${c} YZBRMHOLXHAXTGOZXYXEQDHOGGMJNJVKMWOZEJPUEOYYBNIRLEXTMDSDBJYHKNCNEXXQOMWMPTOPPBNORLLZPSWHMADICYCFQECL', props),
compute('m_8_6/15: ${c} XGQWKZQAVBHHIFUBAFTCRNXFBTWJDUHETNNFWEOOKZMEZXDURHYMIXTSUONDEKQRQMSLWKUEDKPZKPMTERPKEGEMXKGIRPIBSKWQ', props)
        ].join('\n');
      }
    