
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_12/1: ${c} EEBNIWUGKJVGOGULFORYECNVVVDOTEGBPFYRECRPJNEHLDMSASRDPGQZHDMLYWDWQSLXGSFQGREXUDFRVYZMDTNAXHLRUEABQQUS', props),
compute('m_8_12/2: ${c} VFYGZVUQKKSWKPLISJNJREPJWIFUPDQEPYYITSWXMLQREXLDPGKFMXYHARRRXWQYNNOOGHQSUJNDUGEHVYDSNSDNOXKPHSIMAHMY', props),
compute('m_8_12/3: ${c} CIKUXQDNUABJRULZAHGQGFUBZCQIZQHTRGXLHXKCGAAUKQGRBLVWZIQJSULDSUBETGYENOYJWFEAIKMEICQZKMZVAVMETHGEGHSF', props),
compute('m_8_12/4: ${c} MMBFRXDEKRUVCKYTGNPWGYOCGUUAXLIVDRNIGQDTTNWHOGBKUSRFHHHLLMKEMSKTSJCTNADPMDGDWVNYXPRDTNOMOCHEDKRZPEFO', props),
compute('m_8_12/5: ${c} RCFAFEKCQAACNNQNKSKZJHMFQVQODSWDTDXPBQZLOYOLMFMCXKSZYUTLMEAEANWSKTJLNQDPWOZIWKICBNICRFKBYPUTILWWFGIE', props),
compute('m_8_12/6: ${c} IOUUIRHDHDZZAILAZCWEUATHGYZOFGQPTDLYZDTGXHZTQIZJKJAWKNRNHHSZKFLHTGVICKXQDFDZPABSZWGIFYQUDDNNUWSJNVHA', props),
compute('m_8_12/7: ${c} TTBWEIVQKPOBACJDDAILYTTKGZSHJWXWZCVNWGNCNAQIKVWICJGKEZEMFUCHRHXZLDYCDGBSLQAHKKAQXREZAYEOKFJQEHTKAYUO', props),
compute('m_8_12/8: ${c} LHXUHNIKWCHOFTKOFQQZPWTVYBUDPHATONZOUSOSUUZZAMGOWWUKZTQUFLWZAHALUWPNODANFTTGDHMABQPMUFFKOKHPOFMTBZOH', props),
compute('m_8_12/9: ${c} FLDMBLAJLUYKESLCFCHJLSDHHHTYNRYZMVDDFAMUQRXTQAXEMQLAMFZXIXGUDBGKJFWKYTNFCUDYXNMAIUFOPYONQFTIMGXMINBL', props),
compute('m_8_12/10: ${c} JNDZBSDAJJKCYGLHSYXKRDIGZKYHYPBLWHFAYKKEDCBOJDVRUEWICKLONJUMNZXAMNTEBOLGAEJAYAWKTKHSZSNWLWRRCTHJAPUS', props),
compute('m_8_12/11: ${c} OMBHYONJPQWRCYFELLDHJHOWWZQVANEWRGCPKUDPHXRFJQWLPWNFDCTHHNENZLEREVQZVLPHTDAMEBVWVNELJSWRVIOKMTFBNEFU', props),
compute('m_8_12/12: ${c} EXZHXUGFIZIYFWCJJXZGMOISYJVCLXVHMELOTPNFQBDGMQVQJYYBAQZAWGVITLBSRVYAHDCFKDPFGMBTYCDPMOSKUZFZFAKITCWC', props),
compute('m_8_12/13: ${c} EJTYOITHGFYZFXOJAYDZYVNUCIKWWGDVZYVLAEVUBPYAOUOANIWCEKAJCVUTJATKHWYTSIOXUPYSMCRAEGUDATZXKDSONAEMTXXT', props),
compute('m_8_12/14: ${c} VLWXSCXOGGJKESNTMIGPEURLSHYOCPMVDISOUNFFQHQRTAYGNOPWSPPNRZDHSYMRBXPIEIPKDBNAZXIGKUYAPVPCXHIATMEPQNJC', props),
compute('m_8_12/15: ${c} OJLVHTAZUMTXNYYFIHFYIVFFHYACFNPMQLABIWLRPAFZANUFXWRQDLFFJFPOIMRQZJRYTMMMVDDKIUWYFSWULEAJDWZBEBKUAHNR', props)
        ].join('\n');
      }
    