
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_20/1: ${c} EGNHENOIJXTRAEZSOOURSHWVHFBUOVZYDCEWKBQAABXJULDHMYNRLIMSEYZNZMXOVDZKNQOTJHAYPLBYSVIKMZQUXXZRMYMRZPAY', props),
compute('m_8_20/2: ${c} HFQPHVGFYQJTKLKAGOEUGZDSESFHRINULPYEGFDCYSYVBFBIGWMTMLWLRROXPEFWXTFTEJYTNWQOEGFWUPRXFPAKVRBREGYROOZN', props),
compute('m_8_20/3: ${c} SBXFPFVDLZYBVDAGESLIOJZEVWEECCINAXDVQFFETSEUWIXTNMCCUFOBXXLZDBRSVKWYVKLVMKQCJGZEHCTALYHFMZSCJWUXMLOA', props),
compute('m_8_20/4: ${c} GVXJCPBTIDPZMSFJOPFXRYJSZNPRULUYLSTTPXHCQNVDOSXBTQGIQJKWTFWNJRNKGMAHGZUCLFKTHQKVEVCGDTGFHXEJDHGRAJJS', props),
compute('m_8_20/5: ${c} PJFCKMQBRNBBEGFRCIAUNOSXLGPHKTYZHKJTCCECIZBXMNVWNVZADGDGBDLEBCSHNFDGZZMRAQZNVROFBOMNYYJPFDYEWKTOOMSM', props),
compute('m_8_20/6: ${c} BSHKPQYXCNQXKLCPNLRQWSQNWPCVLNXOSNUXCNIYAZUBFPNEXVEYNZUSKCOZVTYHVFSUHVIGXHBGUSWGJFAGEWNUXOXCZUYFNAPW', props),
compute('m_8_20/7: ${c} VMGZOSCWCWOJWJRZUYYHIPYPWQPVBYJZCBHVPECZYPKMBZTYVFDTQMHJYLDJDRPUPDSOFWNQAWXBDGJLCRYXVOQUZVDCZPJAETEA', props),
compute('m_8_20/8: ${c} HJKWUCHVZRBNCWJAPERNNHGBDEXXWUYUODEAWZSBWNEVJQORMSFPMPEMEFVDTWGVAHGCQHAKVYZGEFPVEMKCKNVQSAEYDKJZJYKK', props),
compute('m_8_20/9: ${c} YVLFUJMEVZGZWOGVUQSAOMRRLHPPVXOGWKXBYIMVLJYBHHZPLPEDQDFHOQAJLQEIUBBJJWBLDPMAILRFEGGMGVHRDKSTYLJVEPGU', props),
compute('m_8_20/10: ${c} WRDUQCDNMPHIGXYIQQIVCQMQXMMKDJBNQPVHXKGLDSBCMOHGOYIDDOEIGQRFHUPVSTYCAGWYSRDGRTTXBVMKPOYFWXWOOZNEMYKG', props),
compute('m_8_20/11: ${c} TLPPDJUTBZVDDBCMSDUZDHHQAAXMPQMORCHQSZGUUZODHDHOALSROWWGFXBRIOVPGIZBUXWMQJYZBWKSASBAJQTKGQOFWRBNSMFW', props),
compute('m_8_20/12: ${c} MFTAIMKGODQKWHMAIWQJVMKEBPNBUADQAZSIDROOTEQNDSODXORVOLQMWUSCMAOGURYYWQHBSPEHMPAQYTHGIKPSJBYXWGYFGBWS', props),
compute('m_8_20/13: ${c} KRAFUUUZHZKKWVYRDRCDNCODVVIBFPGRJACPFPRGVGILLAMINJXAFSFYYMDZGLKKVUXNHJPTEMQBQZHSXJPQZYODEVNJVYTLCXCN', props),
compute('m_8_20/14: ${c} YYJHLEHNTOCLWVAYZTISPUSDZYAUZEZXNWLVOXLBWGLSMSPXMCOCDFNXRDMQMFDNEMXCQHCOLEEOVFZPVVYHTQNNLTVNHJVMRGJL', props),
compute('m_8_20/15: ${c} VNOLBDTZYTTWGZHVEPPDYBLCOEYFJAXMBURMCASQBKLBHMQHWNRFGATKSAGWTZVOGUEGIMGVNFWVQMHGYXHCMEKJIUCNLENYQNMT', props)
        ].join('\n');
      }
    