
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_8/1: ${c} TESHZJQSUZFGMLJRMDHBDSPQXTLBRLZNFFRRRHLBQVRICIQLIJLBVIAZBUFMNHXNSGICUZTYAMIFVRSTHUIMLFUNLJRSAUSNEOMM', props),
compute('m_8_8/2: ${c} FYOTVHKPLPWKCJKTONODFQLOPEZNCAWENOIMEADGVCUNQFALGYRCVAAFMOMLZIFJVVCMBBTFXHFPWYYZHYBQXVAMEOMUEZNXSELR', props),
compute('m_8_8/3: ${c} FNYESJPIWTYMSVURXVQBXLFYIXCFSLIKLLHZITVPBDTXCJYPRCGXOUDJRZWROGBXNZBUSLVCAGKDCOBSGVKGFEBMFNYSJTCHLGTC', props),
compute('m_8_8/4: ${c} JXCCTDCWNFAAQBSMICDMTVIEVBODCHFYZQXJSIZXTIXZXEXHLXZRKDLMOIVLMLGZZJSPSVJIBCJVLSXJFXBYFUQCABJGLYZGMFTS', props),
compute('m_8_8/5: ${c} XZHLPUGKZFTMFLRDKQPILMRGLUXXQFOKLHEKFWDSHLYBCHKRCVWPMYJUHXBLJDJCNZJWYQINCWOGCFEIKNSDQILPAKXTFQLRFOME', props),
compute('m_8_8/6: ${c} GZYZODZNLWIGIIYTWFVHOGOOGIIKFFNENELGRQHBYLKQGIERQGDVPNQGZXJZJVWYWCVTRLBKBDKJHFNOHHFVNGWAEHVWCYBCNIRD', props),
compute('m_8_8/7: ${c} LXLVDHLVKFSMEOJGQPFUOBFAJRFWIEOZKPLZIPTJUNRUXSQQXPKZMBYTDGALPGHMJLUWTZRYXFFRHPLWDDCVWYEEGYENEAKCWMIT', props),
compute('m_8_8/8: ${c} VFRTADMFVSNGASZASEHBZYGBBABAFZOBLIGLXWTTUPRIVLVHHCAHPSIQHVYSUCBVTXCYPVLBMXDZNVBHAINSBQTJJMTCIHERNCUN', props),
compute('m_8_8/9: ${c} EZAIQSVNDAZHNKDFTGLAZGGQYQXIZUHDQPZDXOEHDFQWOTAJGNFGGFOKURSTTPGDAKICVQJNCIICASNMVIQRBYLTWKTHOJHIVWAY', props),
compute('m_8_8/10: ${c} YFGTTPEJEULDODRGLXIRUBYYNIZGNGOWJAZVQNMWESCPVWWBBYSDXGOPYBQBZRTDPDDHEJTHHOPYYAGMOPCIMBXJBXREVGXNCFMN', props),
compute('m_8_8/11: ${c} XHDNLCMYVMEYBILSLXFTEXSXLGSMGKLONJBVTHNRWQTQHITLPUVKOLKIQUMKIVKGQNETFLNVIYWVJVUDUAMCAYBCOJGQOTMPEVGW', props),
compute('m_8_8/12: ${c} WINVEBRNOAJJUXVYXQLWOVAEYBTYVVHZYXJBFOPHFWTTHDWSJWXJTJISBGXCYXHPXCKMXEFFZSNUNEENQQGDBUXFOSNLPWTWSROB', props),
compute('m_8_8/13: ${c} PARCVUCICKNWUSSHRCUCKUPXOGLENCZGEREOMOUQIJMXDQKLTESAAVHLBLIAANWLQWOVVQPYLLGACFVKXKTJLCJGLWIPBVGTDUSL', props),
compute('m_8_8/14: ${c} QMHGGSYGOHYRNDAYIAEQLBLOEGCBITLJPLMDKGKMGJXKMAGUEWIVTUMQOVKONVTRXXMZRZOQMZJHTBGOVDNJYNRCXVHDESRDKTDJ', props),
compute('m_8_8/15: ${c} AYFCFYKJTIQYFZCXKXPVWSNJSIBVHMRTHRLKTZSZODVYFIDYKIAAEQEGJDQFRYDSEXIYXJNJJILQYRPPQZKFHMPFETMHZHPZWLGA', props)
        ].join('\n');
      }
    