
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_13/1: ${c} LWRUCZHPFKEBCPVYTXXMNBULTKQNFGKAEUEZJRWZRYHVFCEXTWXWTFPDCXYNBPHFXEEYXEKTVAVQMYNJFHIMQQNTQRNAGQDEZNNW', props),
compute('m_8_13/2: ${c} UVEWPEXSQTUPVKUFWQPKOAGCXZNQQYCXBKNYDTKMFXKTNFMRCQAOKHEFRPIIVSTEOBJDFVLPPMVIQJTHXDONFKRUYZORNKGTPENC', props),
compute('m_8_13/3: ${c} QOQUEYUPRWDYEUDFQKIVAYJSMMCOGIMKXYUKTIQNXONJQHWWLYYWUGHKHMTCAYSCYUXIWKQLNEPRWHCVIUTFKPPGLJKQWVOZNDTV', props),
compute('m_8_13/4: ${c} GPPEJNNBYWYJUNLUIZMGGULTETPLXVSWEHMLQBNUKCHSQKLVOVDYQXHVDOVPUBVAVBYWIDWZCDHGCFWDOBUEPVSMIEIZEIGWVCDR', props),
compute('m_8_13/5: ${c} RVELGJBPNJXHYAAYGGHIZBDDZRZWVVETODBVUCCHXHXLVKVHEAWHZDQCSPHSLXCLRSDGMLIVFTKGAQBCRSNWCEGCQQGYCWDSRFIR', props),
compute('m_8_13/6: ${c} YJGNMMZHOUFEDQUSHJSNXRGEQACRIARUNKBVWLZRURFGRFMUPDZGQADEKSKQFOEGWEWGYRKAKWLXATNSLIDNOTVRNTWLXINZATDL', props),
compute('m_8_13/7: ${c} ORDGAGJRARYAIGIXJVPUGNGZOHITWIOGOCSCFLFZYTFVZAJSQDDQLGBMRIYJFCUNXCQKCCIDLIRJUYYXEBAHIOJNZSLUZZTOXFTK', props),
compute('m_8_13/8: ${c} CDAZBKBFXAOGMDRYGSKBSUOWXOBVGCLQBUMLEXPEQBJAQBLNGHPHDOGVPOYSRFAQEVJTGQFCXLTZBXAKIELKNMPWBVKHMEJBEETV', props),
compute('m_8_13/9: ${c} RDMRQGSWSTDHVDZQDDLAIGGWCVQQWFPPATHGQIFTMSELAWGRYBEXTGJFVTYTKWMLXATIWKYNSKKTKPCFTQDWFRJSHFSXMAZKOCGO', props),
compute('m_8_13/10: ${c} FTFUBVFPDCWJGHJCNYHMMNPHIOBQXRTXJTRTDTRODVRJIBJOMYVJLAOZMVBUWZNAGZIPWEGGGZBVAAJWQSCUANEOVAINABCIWBTD', props),
compute('m_8_13/11: ${c} HJDPFWLQVBTLYIOMEUSYQBWEISRSAAWIVGAKHSOXWGSIUKJMDWFQTDRUHEANCEMZBHNQTBWUBCCVLPIHBGYZBIYVNPPBDRVMSWNT', props),
compute('m_8_13/12: ${c} BSRHFRUQEGDDTLYMPUZHLIVWOYFTHESRLLHWSZWADLLZMQDZZAXZOGBLWRNVZHCGLDYXDTBCSZEFJTJXZMWJHDATFCQJXKPWGGNP', props),
compute('m_8_13/13: ${c} LXGZPHGQVKBTOFEDZKQAYSHOGOJWTCNWJKQVZCELBFRJBCYPNDVPXTEWLSGVULLRYLCJFBZLUKBMZUJVWOPUNUQYAUOINXUZBTFH', props),
compute('m_8_13/14: ${c} NQVMJKJQJDEIIVCZRJFLGSIYZSEJEKMESNCRHFWXWAEBTADFWRNWYYTBJXZBKZWRVRSZEIDHITLTVCPNMJEQRJZACVSKJPICAKQU', props),
compute('m_8_13/15: ${c} QFKUVQPXBMPSLXNEGJHUZORSOYMEFAHTOCIVGPXSIQRZSWAQRADAAEXNVQQSBVYTTCPJJGCKBNFBZSXNNIBPMVJESGTSINFXOOYQ', props)
        ].join('\n');
      }
    