
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_16/1: ${c} NFZPJFUVWIVVVIIPSVMMMALACPXUFXYEKHXHCXLYYIYMJCYTEGMEBTMLBKKGSSJUNBRQSBRFBHGDKOGIFGZRUOKCMEDJHWNMZMMT', props),
compute('m_8_16/2: ${c} XUCCHZBQXVPFGGKCPNNJKJDYMSHJNJFLKWPKFCPLIXSCCPCLLTNXCTYCXCNXVTBZWNHPAPLHFUAHTNWLOIPRYXVYYVTZLLTAZNEN', props),
compute('m_8_16/3: ${c} WVPCMGHCECPQEBYKMVALTMSYEKDWJWBAIEOQXJFELMBBUERCAZVFGIRHVCSMTIBXFRVJXDNXKPNXXHEBBZGLWILUQDFOABAZEDGO', props),
compute('m_8_16/4: ${c} FZSAJPPKXOJUGKBNZLTAAVITYIVYUCFWMHQGDHBMCOBXAVERYNGRFVZEGGLXRFXINOQTBMZUBOMLKZILRYTSZQDGGEROBOSXSJBJ', props),
compute('m_8_16/5: ${c} OFJKHQQBWQSCSNGEGHLIELWNBGZLWBRPULLFFWHONVJPGWPHWBGYAGGSWDIATAOQWVQJLSYYCMQEQDQBANSESWASKDJRQEXLPWWY', props),
compute('m_8_16/6: ${c} VBTNMUAHARSRBMWSDGMTXZXXPNUUYISJSQKIRKJMIBCKWPMSQPHRBIIXVDEZPATKXUHUMABEBIVPEWBGVLJNMVDZQCPUEJEARAIJ', props),
compute('m_8_16/7: ${c} KTSWISLXMPAKEQYHKOBHVIUQXDEAMTTXELQBJMIESDDFBQUZRILBQSJZUKEHFIJDIIGUEMNOEHCCBPHIEJMNEFMKFNXBTMHJMNGA', props),
compute('m_8_16/8: ${c} QKVHJFAWADMWJCHIOPDZIMLGHOQENWWXDYIJNEHXJLFBMXKISPNTHJIKVMOXALBONYOXYOEQHTCYPRAJALMOEMOVGDQXESBOJWNJ', props),
compute('m_8_16/9: ${c} KWCPCHXVNNFSOQYQSCUSVMFJYBRVYCWIPSDXYGCZJCCWYFGASMZRCPBKOUZFKYDUABGREUOUWMEVCQRLZIVSJFJGBFVFYTPOJIUM', props),
compute('m_8_16/10: ${c} ZDMYZRWWUOMKVDLYZPBICTLZWPUMXHVJKYJHHDDOBDUTZWYMDIKQAYEXQXZLLKLNVYYIFMBQQWNJABQFGDAEYBANTVTFYVXTHLPQ', props),
compute('m_8_16/11: ${c} RHTUQHFLFLIZIWXMZWWHROCNLEZRVJYKLSVAYFCBAAPUOPKYJWZXQDNDTLSHLLZRCDDFONYGCLQWQTLVKZXSQRHFMTTNGDTLFGTP', props),
compute('m_8_16/12: ${c} ALGBYSOOPBCJKOYVUJFSRTXODFOQWZAEQHCZYREORRJUGBCKZRMGYMSQBTFWYGBQDPZGSDXXZCSGFTMKIGCVOVIMOQTLXSXLBEPJ', props),
compute('m_8_16/13: ${c} FYIOBLKQDCSACVJFYJLRBYAYNPRMXZTEVYLAHAFKFHJBWTDBJHEYSOKTPKKNMQCPZLLTTCZTCDPEPYCBIMJYIWXLTUTKGGETZXSL', props),
compute('m_8_16/14: ${c} BBJODFTWUKYJJWOVTYSUYFFUAYYYPEHTKGGWMMBWGEPNPUBMOOKVTXOWPOKGUGRBZOHHQSFGAJYFXCUVINVFCJEZRUXGJGGZJBJZ', props),
compute('m_8_16/15: ${c} XCRELRBEWMNFUTSKVNVPOPVFLPOLFBSLEGJTXPVLYNDPPRDPMQKWYVAOZAIXMHOPZYGACXALQOEITMOUDHQZHEDQQIZKBYNDPYPX', props)
        ].join('\n');
      }
    