
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_7/1: ${c} RVZUJTRQACGZGKWBXRMXUEDPQPITZHIRXLWLFMSQGOHXCVAQDJMJTNCQQQBMVWPOINEYLAJSKWVVQTYLYDUCULCBIBSFLWJBBTDR', props),
compute('m_8_7/2: ${c} LDMMNKTACVQLLFWUQGXIXPUPHXEZEBWDYOZCFANFPKCOLVEXQQNILNIGZFPAETMPPWIVCCARCPCBESPYAOSHHDIACLJLLTJBSHPT', props),
compute('m_8_7/3: ${c} ORGWMDXIYIXDDEIUNYQGLVHQPKTOECBNSDJWDNASYPXHZFVEDOJZGEMWKNWQDIVHMOCKULESRINXLSGNSZRRIUJHMEQKQSUQSDNP', props),
compute('m_8_7/4: ${c} AJTCWHVYHIHVYJMXCUNJVFKANDIMQIOTLNMSHZFPIZTQAXGCACDEXEGIURTBCJCADDHTVSQCJSDLELCWVDXYFFLRQENDQAQLOIRJ', props),
compute('m_8_7/5: ${c} CJSDMEPQAIWJBYPAHCHZDOGAXDEMDCDORHVZZUMPLIFHDWDQVFCVEIAKFIDUOZJFMMRJJWMTUBPIUWUKZFWFEHEXMVAFZTAOITMY', props),
compute('m_8_7/6: ${c} SFBQQAKQAJDOAALVPIZUYLRZZPOEIIQQQLWRKTPDQFPTLRUXAPXJXEKVCHQUHEZAPIHRBPBNCFPAUECGQIIHSEXSWZGNKSTSAMEK', props),
compute('m_8_7/7: ${c} IKZBEDCSSACFFWRUSLKNQGUYKKTSVJHACTGAIJNUKDGEWVPWRGIUWVSSSJUGCIKQZCHSBQQWMDXFWGHDQVOOZJOPQYTIVIRUMDMT', props),
compute('m_8_7/8: ${c} NHKZTDPWFCVOLIFNHVOFBCIGFBLSCUOTXQNBBYSFEJIAYIEBFGLAYXMCKPGVUWKGOMTBOQOAHTFMKYRDJRYJYTVAQUXISMPZBHBC', props),
compute('m_8_7/9: ${c} CEABKCRSMRLSIPSJSIZXCDYPRMDTZKIOBGSDAXUSVZZZVITDXMEYVJEDYYIIFLVCHSPYTEWRUQKWLNTWOPZNRAYJXMCZQAMCXSSC', props),
compute('m_8_7/10: ${c} NTNIOBIJUXMAHFQAWIOGXNMTJTDOHXYZCZRAMRHSPFCCRDBSFZDATXJDTTKTRCAJMMJAFPNXMEQBLZACPZKYPJOWPFHQKWDDGJMT', props),
compute('m_8_7/11: ${c} TVVOCLPVXUEMODSBGLHXGRBXINJYBHPKTMCAVACEBQEPTQQLRGRVAIGDHPDIKPNGDGFCDNDWSWRONPYXXQYIQIQYIDNQSDLTJSRW', props),
compute('m_8_7/12: ${c} KYXOMDUCTIYOVLPISFAWACBCXHIKJTBXSEFTEHDQTZDLHJHBCGECURWBIZIVPBENXUAAPCJQPAMRPFRYUYKKPCFAVBQXVKATXFWO', props),
compute('m_8_7/13: ${c} XGUPCOVYHQABAUTSHYBEUDAVOBMRMUNYBXQHLUGOOOLYWBYNDQQHHQEQNHRAJRDJUDKHVHAOQMUIXHAUNWUAGJCJKFPDUHUFUCEG', props),
compute('m_8_7/14: ${c} TEWCOADSUAZDWIEPOWETQRUISBJJRFHFIIHMQJRJVAQVIUGWDYBMBSIRDNKFBRWDPRFBTUQJVFCSXVVYNUDCJJWHQUHYWPDLWQCS', props),
compute('m_8_7/15: ${c} LGTRJRXTWYLSYYPHMCBIXCFKEVXBMLGVGTJNYTZYEKPBQZBCEUKFJUCEPUBNOFFQIDCIMIVKMZVNUYPCUSAXLQVLOLHIAXZEVJGZ', props)
        ].join('\n');
      }
    