
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_2/1: ${c} XXLUOTRCSMTOOOFYCONMORTUTOYVMEVPAHQXHELMZASPUEIRTJVSZVRBRQFYHACPRPGBDAQXEICZJIMMWEVKRWPJUSVXPRFWZYQR', props),
compute('m_8_2/2: ${c} IRYOHOTZAEYFLAODCGJKNNFEYBQUXSOOGUDRCRZJQEDYOQXEIZJATAWHQQVXIBVPIBYRPQEJWQLNJVEQZUCKLFRRNBVQMEIJKYIY', props),
compute('m_8_2/3: ${c} WLLPCBWJSFWGHNQHLVHRGMOUIUWZDBRMRUTMJSXPSXKGGAWYDHABTQWYZJWQWCOJJFBETPVRVYOCLHMOKOENJGJKZIWRMJAKTXVZ', props),
compute('m_8_2/4: ${c} NPCQVGYQFPRPOZUZHMLEBYMMDRRYJMKCWFUYMPSWEWYXIEWCLEYKUUJZBMBPNMAUVBZWNBAXBMLJQCIMOLUYQRTKHQFPFXMAHGQL', props),
compute('m_8_2/5: ${c} JOFSGFJCCALJXYCVYMFPZVDWERVWSFNLTAWZEQQCAEEVNDZKFCPPUPPSQQFYCHYAJNAJMTBFXKUUTLKLGVZFAOLEKTDFCITVYFBB', props),
compute('m_8_2/6: ${c} IPXNXMVUCRWRWPPQDQBGFKHMPXJDBQTRTGRKBLPGUYOENDAEYRVISKULBHKFNHFRYNZPWGBLMIMGQTJTWMAJNJTOGXSRFNTXNUSI', props),
compute('m_8_2/7: ${c} KBZDFXIDWRBFMVFAVSEFHOUMMVZTDKVPGPEYDHYSXHAQLXSFLXNBGVDXACDAPMRGIYXUQDRMOQFJBVZTHZMZBHBBUVXTPUKOMIUS', props),
compute('m_8_2/8: ${c} GVEELPRBVNGJGVQEEDEUKGNXTCFWPNRYEHUHGIWRMDZMCVIOCXNIRTHORXOUKZMXZQCRARJGMWJVRNRMFPSRBJYOAGBBWUIALTHB', props),
compute('m_8_2/9: ${c} DRISVHCVXGPBCUZUQQVCOUDQSLFQIHHEXNEWMPCOVZMVAUWGWYVUYASUAUALMIOIWRBURFMOBTOTYLJXWFBKVPIDUXEFNNFPRNVC', props),
compute('m_8_2/10: ${c} IMFIAKMZPJARKMIFBRIYMYCMJCOGLYUZRRQQPVJDTBROQHDMNJFTZWPHHQKUEENJRANNVOAVHUMXTUOMMMUSLQZGKONQGWZVHWVA', props),
compute('m_8_2/11: ${c} GWGBAWMPKGBMSFDMLXAOYHRZOASIUXAAMFNWWXOQPROGHRCMZKUSSXZKDQVBVIAZKRFZUNSAYCJQVPDPRRDNNOHTVTORNEYZZHAO', props),
compute('m_8_2/12: ${c} JKMKOUJMJQCNLCXOQQGKTMTJDBMKXLEHQBXPCLPCNEONUMVMGQZWDGNZLTJWCGMDNANGFJBGYIRZJFFYMJMIJCASLSQIWTHYYMCE', props),
compute('m_8_2/13: ${c} VEOPLQCPEOJDAFBVGQOJVKURSBBKTIKEOBKABIWHYJHIZQDMZNJWVIMOUDCLYNQJSHOBVVZHZHQYQJSHNHWGPXJHIAWQRFETSKFD', props),
compute('m_8_2/14: ${c} YSZFNBQDOVYMHQUHZVZXQKWBRROQZKESBGCRGZODAHEVCRYMDATEZENNNBZLNIZJCSQSESFIJWUSXPOJYBTWJCDGLXBQMEXQZOGW', props),
compute('m_8_2/15: ${c} TUUBFUUXJQXNTWMUWONYTSVJUFGAYDGZUFVFYMEWLSMEPVLOINAFFHADWIOROXXSIYWXUMKAIZFZFEXDLORDWRRBHWSJETBPKPVW', props)
        ].join('\n');
      }
    