
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_1/1: ${c} TKTNGILJUGJHVNMODEDAFEARCJMKJGILNLACPXHWAPVUBZRWJXILDKJBYZVYDNPMBHEUVOLHDFAVELUDLPGWSUCDOHXNKUOXDKIA', props),
compute('m_8_1/2: ${c} KPTFSIFJRKUTZICBMCZWVGUJFKHXDQRPJLBONJPNZIBSUPVDHQWDMWWAZCLBCNDAJTOJZMPRJORLBLQALKFOUGQWTAIFSVLISDHL', props),
compute('m_8_1/3: ${c} KYLGLQIIJZZRJKNHWAOTTFGXUXWOUAMMUUHIONIVOURMYMWHRZBFEXVRCBNVRQOFDSSMUVQCAEQQMUETNIHOFIUGRCAFWJZARKNS', props),
compute('m_8_1/4: ${c} LSMJIOQWTYKUTVMZGUIOGFIXMRSLMLQEHWNRLPGUADVPWGZKNNUEAMNLCNETNMADMGBEBKCQZTZFHUFVSXOKHOHPZRIWRAKTDPWB', props),
compute('m_8_1/5: ${c} NOKDADUFTTIRSYXOWHCWUPMIDAOVNLYSMDAETWVRDRAISCBZIICNHESXLTPVHRMSBDEAPNTWNGKTJOATNEVIQYHNZSNXJKQEPLRB', props),
compute('m_8_1/6: ${c} RBJGBSGLLNRQBPJDGRBTZOLBPWCYHGQHBLCDHVTCDJGZVNEUWQMXFENFGUMEGWIUQHSWVXLSXJQOJSCGPDYDUBMWLWWYJAPWYGQJ', props),
compute('m_8_1/7: ${c} RWMYBZBWUQIREHWESWWEKLSFCHNSQDOGXLRRCSLDLSUAGYTPNUQVXFMDOBBELZPQYUBIFNBCMBESWNSEJNPKZXYJNSOCVTSRGQYB', props),
compute('m_8_1/8: ${c} HUZYVOZMLMCDCLDWYLQMKTMUZMWRHOPXBGIWEHJGZJVIULNAUBRUASKSJPCQRNDOSQYYGWWQIXRDGUHNGLVQLQQLIOLSHGGOLWEO', props),
compute('m_8_1/9: ${c} AZJQTHUOUJWCXQGZPVWAERCVFITWTDOYZBMTTXLBONUANTKSCGDQJOUBRTOLCKJGDOTBIFQDZMIVRWKCEXABAXHEOLFXOWXRUNDP', props),
compute('m_8_1/10: ${c} OTPOYDNCIZJJFSCTHXFPJATHVKXAYUTNJTEKGLCSHDXBNKBHOKZIEBTAJYPFKPNCKBKDPLGQREJXGQBPYZKROAGREQAYNLKEQNKX', props),
compute('m_8_1/11: ${c} FWXRVTFBOGZKNGXQMCAJIKWHLAYYMIDNVXVYEYSISFZIBOJPHBHGCHUKLQPGXNEYICCNNRIZDSYHLRCFOGGAVIRKGRENPZHADKRZ', props),
compute('m_8_1/12: ${c} IBQOZARYSUANWLGEKPPVOGCFUYSKMBFEHYUZGBNWHXLSOXFNRTIRIKMNRLVLWZTJVUGDDGFRLCTUSXMLCPKQTHILMMXPMWZPLMPN', props),
compute('m_8_1/13: ${c} WAGTKNPAQHLXMYWWSOCKIDWHRDHGANJHMNSXUYFBBSOVHXXINHGEYETSKZQCTIXXVXRHYACDWKCCYJWSLHPUYDNIIOLBCXZOKOWP', props),
compute('m_8_1/14: ${c} NZNQELSMWGCTAWIIVCFFBABJKSOCEMBBXQVVQQRXACSKJSQMOZPPESUGMUITGXNTAQGSQXKRWYACPZWMOAPSYBDRRCKVBIFTUNIF', props),
compute('m_8_1/15: ${c} UPNRXLULQANWRGUTCZJKUGQRFFYFGBXZSVRXBWQUBHTKAHPGIVOEECPXEDYKQCZXPSYODNXWMFXZLICFRFEABLOQFMUQZGCZIXNA', props)
        ].join('\n');
      }
    