
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_9/1: ${c} PZKJOIGBNTPCUDDOMIOWBMDDYELEPQAHDLNCPFBWQPMYBIMVQXPZTXUUESXBJZJVVYSXMYCNMWCBUDFFORWQLWBUBCMHUDTVEIWK', props),
compute('m_8_9/2: ${c} ANMDLYTXGQTWDQKHQDRSMJOVJEUZPDUARNHULXISYYRKHXPIXHQBBRKBHRWOAMTGJIGENVYGWLZQTLYZJZTKIUJVJMMCAQVHQPLJ', props),
compute('m_8_9/3: ${c} YBLBHVQGCZTQPPZPIMZNXXRBZSETBJKPLTMXSWZWAXMASGHWCUOWTFKVYSFSRAFOMSAJFYWZTQEOLUADXZIJBTIHGWKFCHWGDERZ', props),
compute('m_8_9/4: ${c} DFGMUJVGHJZTRLPHOLPUJLMIVTOZQERJARVMWNCABQUMFFSZXKTISKDJDUBNMONDUMBFIPHUDZXCMSFCRAYIFHXLQBKSXWPQADIC', props),
compute('m_8_9/5: ${c} EOHGWTFGDXLVGQIKFCUVWTZPBUJBYOSFLRGIZZCEYXVSVZBFDAPGNMIQOGCMSPFQIJTMDVYAXFPJKKDMJLFEJATPXLBKYBABOQSQ', props),
compute('m_8_9/6: ${c} FSIGTUGWWNMNNQBXMJFILPWHZBXQCKLDBHKEKSVNZLQJMLPZWBBJXQYACNCVHPOVXUHAZXHUDCQJNUMCMDNIFMLWHGZSXCKXFQGM', props),
compute('m_8_9/7: ${c} YSOCOXSEUTOGIEZIZPJTDTJOTPZMHTXMNEOLQXXSSGRUNZSOZBEQSUQTVRBVMUDVRWHRLPSGSXMYYVUCONTLPPHYLBZSCIGMCCRT', props),
compute('m_8_9/8: ${c} FTDVFJBAODNAREBOPZXKSMBYQFTTAXQEQZJWLJOAKGEZLQQKNCPICZNHWIQLYYXUZFNLGQZTLPPKMKPPBRIPGGLSEBZLZHYFVNJK', props),
compute('m_8_9/9: ${c} KCPTUFFWLWXQNCBMGPSUMFGJYMZRRJLBRZXLODNDTFRQHDZBINJYTBTPDSKZQFCYLLWSIUMSIGXIXHBUSJXERPPWZNJLDUFRDEEA', props),
compute('m_8_9/10: ${c} JIXBXDGFXAFUGGKOSGBNXLTITHSXSVRNTWLSIXNDBAXOMFSMOZMEPUCFWJYSHOQDCCQXXVVNOTZIFDOTVLDCXEIWWGPZZVRBQFAB', props),
compute('m_8_9/11: ${c} RAIYUVKXOFZXECWCHDYDSGUOPEREJXNWNNUIRKQBFSDCJZPAFVYBDBLHYTGGGHOILDETVTGHAWGIGZTQFBKJGPAONINZHFAUZOEJ', props),
compute('m_8_9/12: ${c} LSQLMYOHETXMCJBPLXMQHKYKFIHQILCEJYYULMRBZGKRPNBRNTBADTRDSOVEPKQTFMSJLSQNOZLSDCFZUGCMGKHWYGKKQMJGKFFW', props),
compute('m_8_9/13: ${c} ICOHIBASROXHCJMEWLCZTPHDVMUYUHUCXFYGTGUNGEXFPZJCDAZDXQWBZFWSAZLSVYELTUMJCDTYTGWVVGCASHLGEQGMHMMDVRRN', props),
compute('m_8_9/14: ${c} FVJMXYZCIRBFWLZMWXTOVMTCWDRFKDJOLDFPHWEWXIUHSCTTMEEMTFSWSBPJXHJLOWVLZWGPHBJOXGNIOZYAVWABPYKUHTIQPMZY', props),
compute('m_8_9/15: ${c} HHXNVSBEFYPIHJQZYAJXVDOMGYCUAQLGRRETCTLSRLTVGDNFIWPMTBYTVPWLRHFXZYPRQZTPJRULULVLHOEBXYKJOOUMVZIXIKAO', props)
        ].join('\n');
      }
    