
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_19/1: ${c} DTYJTATOJHPDSDRUVNVYPVJZIPESBGHFRGNKCGNWGLXAJEXXOVDBTLNSGXDFDROPWVUQKJNMAJBEFIQWAXMPZWBCCWJXKFQAWEPH', props),
compute('m_8_19/2: ${c} HSHOYGJGTBNPDIWPCRLKYZFGXPUXOSCAXSFCSPHRCAQIWGEATHGDFRJXZAMJFHYSFPGVMNQFFTZJCBVRIFNWTUQZQQEONPLFASPN', props),
compute('m_8_19/3: ${c} PVCPGMKJYQKQOQZIFULMAUSZAKNFIVTRLGJJTEURFSUUZIKQRCRVBWMPRMTTGMNWHVRRNMZCASDXYBUFZHLUBLLWQZOCQIIWRMML', props),
compute('m_8_19/4: ${c} ESHNRABLMECPAKWXYSJTAACQNKFRKUQWMOULGOYRCDNJEKATQWGWUYQOMZHSPLVADZVHEWSPLYQFGRIAIUGBYQPTGGTHWITEGWUI', props),
compute('m_8_19/5: ${c} UAWWTQFIGTRJHAUVPVOHJGJXZCBXNWAIBTEDOCDDKLLVXJIAIKSBGTLTEXTVBPMLGSOUAYLOUNBVSFIZPHZASACSGLKGJKHDSZHF', props),
compute('m_8_19/6: ${c} LUPZMAOQMWVBWRFQNBIULEESFQADPPALYKRHCUJPJWTAGRWQVAIUKNTNVRVYAOVWWUKAVFIXINYZNAVQOTEZTTYDTOYMYGUIGLOM', props),
compute('m_8_19/7: ${c} WCWTETOXCZQLNIEHFLCGATAPQHRFCNYIABZQXDWOPWMJWDUKLTVCHVHZYMKACFIGSRIUKGDMSFSTSHCGZKLAWDCNBUASKSISMRFE', props),
compute('m_8_19/8: ${c} UCOUCJYFIZLKKNCLXKFVCIEDSAFBSZVENPQOXNGQGWUDJGYVXUGALIYVLEGDLAEPMFJHXYBSJEECMCWNUEPBSQYDKTJMNQJCIRKL', props),
compute('m_8_19/9: ${c} EUKTBPABOFWYTQSQOURMJPTGTTILFUDWVGAFJRFELYHHUOIZGFYCOAZCVKJSHWKGICRPWETJXPBPNXSHOQMNJMEMFHVGSVFYOYYK', props),
compute('m_8_19/10: ${c} TEKNVXZCZEETXHDNAWIXKXMTTNXNOAUHAXFDMGWCCMFPATSLPBHZDDQDMAKZCBTSLLQUGEBWHDKFWNMTGHDKHEGAYQACKZJIKSVV', props),
compute('m_8_19/11: ${c} OAKTAYFGGTZHMISERJOIWTMBREPCRYSDCGZOWUGZONAKSOQAAQKTBEQZMSPSRZBPUIWNGEACWZMNJNLMWBIAIAXFCKYRFHOKPYPM', props),
compute('m_8_19/12: ${c} WVJTJDZBDDKXLZISBYNQMXKQZJIHVZUAYNKRZONOMAQGRKVYQRBDSJCSKJTKHLCDBYHQTOUYCNRQPTUHAKNQNQQQDZQIEOZZWXID', props),
compute('m_8_19/13: ${c} OKOXQMJUHCDCSIWQXINYXDGGAYEAJGPVXSGIMARCITUKSICRNPEWVELXDDQRGTZLJCSXKCRAVAFRJXOSYTHDYRJRNLHJSUUAJHXB', props),
compute('m_8_19/14: ${c} ZEAEZRBWJRUTTNRXOEBMRTBGPINJWUBQJVHSMDJVKNLCSAUDLSKEZZKPYQTBZIKQGFWZOHVXSSPQBNOCLBDTYOEGBAVUDBZFHWUZ', props),
compute('m_8_19/15: ${c} KXJPBZRZZLIIHXHOQOOSEAOWXXRCNTLCZJTHCIXVFSYRTRNAQHVHLSHVGURQMGQKVKJUCNKDDUYOHQPQWTPNPHNHXPTKMMHLYHPH', props)
        ].join('\n');
      }
    