
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_4/1: ${c} ZLXCYKGIGMLURRKFDTTEXVIMAVYCJDLHCWGRHKDGPKSABFGOZCXRRPVJRMPVMCZFJZHHBCYQGBHXYEDASGDANTGNLNNFOHPCQYWY', props),
compute('m_8_4/2: ${c} TBGYQHDNHEMRZWMNTHRDARECRPBQWFWBDSIETPMGNYGXHFQFBPOBMACZOZMMNGIPTBJEDHOYSOBFJAZYXYWHASYZBXLWHKXPOQCM', props),
compute('m_8_4/3: ${c} UPBTUKOICEHVOFISTECVGUQMPWNTPUUCBXSICUJGSAXNCIECYJCAPGVGBBUEFIYHNNWECGLFGKYFYZCWHCPHANMAGOAGQQBZOWIL', props),
compute('m_8_4/4: ${c} GCTYVFSOHPNCMYHAPAFANQUZLOMNESPWLMSTEJCBRUVQZYOQLFVJUXRAWEAZXESYCORSTACGGJVGLYNMIUMBCHVYIIGUBQEUFHHD', props),
compute('m_8_4/5: ${c} KEJTDYQEVVPZSNPWIGFUDZUEKXSSXQCOKPXJGGGKZQIRYFUTRDXDNMHNAPHLCWQLEUWOVGQDEXMAKBFBPTHHSBUNNHZBYUGRSWDH', props),
compute('m_8_4/6: ${c} SBDXLXOORPPURPFVHSXSYSTHHXUMCFYVNAZCFVBSMXOZWSYQSZKUOJLXQOPAADLAVZJISLAMUFAXEGTFFIAXMWTJGMQVWRWBVQZR', props),
compute('m_8_4/7: ${c} JGZJPHPNXKDPIWRCGFGMFFVGUQIPXAAEJUXARMORCARCPOJSGUJCEYFRDGVXAHVMQCHTDFZWKULOCRCJHSNKVIBXXJHPDHKUQCHM', props),
compute('m_8_4/8: ${c} GWILQRZKZOEILCBINEKJJLKYOKBDHMPFJUNHDCEZTTHCKHBFVAXFRPPGPJFDMTCPVLKEYHKCFCQUABWRGVBLYUNOYIGFBPVJOGYH', props),
compute('m_8_4/9: ${c} JXJBONVLVNQYURTQCJVYXGSHUXYLZPEWFIZRSJMOTHUBQZQSVBXVAGPHXIQVOIKOXCYCJBDNGBMQTSIXHFQUZLLPNTEEGBEJDSUQ', props),
compute('m_8_4/10: ${c} ODCYXLTNEXFJKKWEUIBSIPLYZLZRGRHGGEMLHEQNRTSDHIEIPUQVZKVULNPHQPQCGEOULMEGSSYGYREMZWXCCGCDTKQYGTECYXIQ', props),
compute('m_8_4/11: ${c} IMPZFBNTPSJRXGDFYKBIRERVUCJDZXMZICRSIKXIBWZBUXGVSZFOLYGQKWYLEMWOPUWGQDBDCFSQLOYMPEVDCGITNWMPYFSCIGAB', props),
compute('m_8_4/12: ${c} VARUQODDYEPFJSXVEOBVWOOVWCMLJKHAJMNBVBYTMJDBDUCPUZSPQFVKTGPLOTOPTKWJFGVICOFUVYAVRRZHOWETSZYXHPBHQVQM', props),
compute('m_8_4/13: ${c} RDMXLIWQHIMKFSZCFKJXGIQDHMBUJNITGWODPCIRDHCKZUOZMPCYTWWKFRAMPGUMDTGFWIBDJNBQQQNWTVECGWLNZVLSTWLIWCLP', props),
compute('m_8_4/14: ${c} YGQWYXOGMUFUEPXQCIHUFOMITRLGIKNLWUMUFSQYZBMOKXVPIXPUQKEBIDKNONNLABWUKCHTKHQLZNAFMFZHRWSJZSTAZRAKUKJO', props),
compute('m_8_4/15: ${c} AYRPYDSEOOEWUMOMGMGNGGLWTQJMDHIYXBGUJDOKNRQMVXOCVXHJWELPUOFAXOYIHCSISPOWSBPLCXGYSOBQXTDTUXXSCVWNTWYS', props)
        ].join('\n');
      }
    