
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_14/1: ${c} NJSMLWYDYTUOHZZFLEJFHEVAQZAVCYWMOFHSGFFVOSNYFXXKGODBKUYJOSTEXRHGHAZCHIHKZXWYJUXLTWECUYMLCMCRUXJOHOYO', props),
compute('m_8_14/2: ${c} QKOABMVXPJPRNYZHHGEGKALGBUZTCGJHIRTDBSZRCBXQYQWGCLGMPHWIHZKSHIXGFOZWFJPQWTBWQLTBDFFDTBZKNJJJAERNMOXX', props),
compute('m_8_14/3: ${c} ZACTQAERIUFBICOKFMXXJVNJHWZILLDVLSTCVWUIXDDCLSPINPMQHOTSZGZPSZKKDCPOFVGPRYXQLUVIIHMDWSETGNQVIONMZKGB', props),
compute('m_8_14/4: ${c} WCLLFONXNBZRTJQVPUNCJACZTEBMCXBMXJCMDMHVZYHAQQEILHJRABPMAJJWCEGJXYCVLECWIOJWXWEVRSSPBHNDINJMVEIUZKDC', props),
compute('m_8_14/5: ${c} CTSDLDLCIGVRSNWITSFMKGSFKKFIZRZFOBUHXQNYWDVBEFMDEKKUUNQKTPKLSRICEMYEUPBCQBBTLRIUPYAGPAIWNOASVGLCLOEY', props),
compute('m_8_14/6: ${c} NOEAACRQESFGRPVRONJWGOIMTILCJQIDZQFTKAVJTNIJULAENSZFKUFQBSZJKNHXXPHEBUBUYSPXGHZRLLDMCRCSVEDIDDFPHCEA', props),
compute('m_8_14/7: ${c} IJGGNCGUNLFLWEFDXPQUFRDOPMQSKWGZCQPGFIFZRFUVFDFFUQHQIHQOHNDCRPGLKHJPHQFLVINWKEDTLBAAGZJBCRVVTZJDCLWC', props),
compute('m_8_14/8: ${c} IBJNXFECSNPWRCPCZZUHLQOQRBBBILOWYXYPFOEWWNADRRTZBEEWLGVHCTWOCCXRRSBSOENVNHAGOWXGJOUFHYLQYNKTNEGZWSLG', props),
compute('m_8_14/9: ${c} BLSGVJOAVWPTTCVDIMNFGOFNDGNFABOBWCAMYOVFJDRTBCBVUAODEBMNFSEFFINKZJLNJCAQGOXRTGMDNJWZPEFWRETIKUSSYLJB', props),
compute('m_8_14/10: ${c} JADNBCBINHTWYNELHKDUMKMVPOKKEEIDYKRAULXJTJDVWXIYAAQUMZOQEDVGDDULNHQMSOMRQZXAEEKMKNXCNXRDPFOBYAXLNUCE', props),
compute('m_8_14/11: ${c} ZNIMBQERYTKVMSAIQRARQYLUGJWDPWGLPVPTZHZTILULASJTUBBZDWMKACJBJAEDNGGHFIIQAECYZOYDJPTXUEUQJOWESEVNJQNK', props),
compute('m_8_14/12: ${c} KWMJPBXTPMTBGNOJHFHJEGJWZYHYXYEABVOQZKFWMOXCLYOAXIJTJLPTPIUYWODKJVWYXACORQYBGPKWNXZUVXTJAOVCLWRPTHOE', props),
compute('m_8_14/13: ${c} RFEYGBKLCTZWHFNFHVRLPFQGKWWUFHZJRDDDLMCGOCOQITGQURRIICNDMJRUCBXSWWRVLTRCQGDEGKBJPELMYSICFCTBQEGJSYCD', props),
compute('m_8_14/14: ${c} UKZZWOHIKFZMMXSNWFXBFUXZYOQORINSMBPFCNNKOTHGLJLNQCMFODPBZYDLADZBCSKWODMWDQPMFRRFQJIXQJDPTQHEHMMHVNDE', props),
compute('m_8_14/15: ${c} YWPQYQIXXJPGZGCJUCIBABJLOYTHPXCNOTDVEVNSCPNNIMWJDIHKMQTXHTEVILFAVZIIJXWWHTYFQGNCPPCXOJSZICWIQREJRGWH', props)
        ].join('\n');
      }
    