
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_11/1: ${c} BCGNNHZVVJFIXWHVDSWCDODFQUMCOHATCGICQXATTDIGIJVWGRDNDCSERCAOOAVJKUWNGZSLMJAGTGMUSYTLVGLVLREBUYFTTJGB', props),
compute('m_8_11/2: ${c} TLCRCTATGVJEQZYXEAYVSKPMCBCNGBLURZELJORLUHRLRKQIXCIYWXNAXIBYMYIVWRRDMPRSBYVFAUKBVFHKBIXCJCSXWNXQIPCQ', props),
compute('m_8_11/3: ${c} GNMGVRCLHXLXSLYRJBMQIEYGRJGFTPGWNPBIZTXPMOGHRDZFNQRKNULGTOABYJRJSCIJRQOWTJDFSEADCIEWCNANNRUJHSSZXPGP', props),
compute('m_8_11/4: ${c} NSNNIDUWNLLQIDJGVRWHRMZUMTEFRPEGIXVSAMCZIRRUENIAFGXAZBEFSSNRGPHFLHXVRFKNDOMMEUKZJEBMAEYXLFJUTDXWWUEJ', props),
compute('m_8_11/5: ${c} VXXTPUDNCZLSHZSFWCQVOFTZMVELUXSMBSKKTXNTZIIAVSRGYMBDKLOSQGWYKTCPJVDHVHTXYAESKSVUXZTMSIOSGDPBGJCHMYGO', props),
compute('m_8_11/6: ${c} FTTBTNONBYQOLUKDGSHTAFWBBJWVEAWJXTDOASFYOJMEJCAQOKYFLEFQMNBZZHKTLOSQDLFGQLKMKECIKXOTTEJRSOTJVHYRRSEQ', props),
compute('m_8_11/7: ${c} NSHNVKMFKAELWZGPWRVVOHIOJVPELRJVVKGDPAEMDELMKGPTBZXGLCHHWEWSUBQIIUFFVBVPJVKICKKFRLANWUXMZRWCODMIJCZX', props),
compute('m_8_11/8: ${c} CCJDQIYABJYLDIZOCLLOFCKMZEKAQPYKPCZGDVUOYMOBZZNNODDHKSXWXGZJLAXOEHKFPVRHUCBSBEFFHQCBTRRJEAXBJSXABQXK', props),
compute('m_8_11/9: ${c} NYASGFVGORBQBOKUSFJOKRYAAAOMUTSAEKPQGGLMOGHLNOOTDKFXTTSXEHAFCCDKBYYPPSJGQKUEOODWXKLLXCIQVGZBNGPNRFMM', props),
compute('m_8_11/10: ${c} BCJXIWBGDLDMSNBRASLEEFNFKLSPMJUBTRDSBQDSYYHOBDYATRCWBDIYCGHKPESYRTILZNATDCVYNYNVCDRZSEPCXMKLYVROZZIV', props),
compute('m_8_11/11: ${c} GLASZQBKGQKWCJQAPAYMXEPBSBRBVNFARBFXCRJKLBQGAGBYIAGVJGWGUTPLMSCTMBJOFGTKHFFIRMXOGOHBELZWLRECWBZOPOAE', props),
compute('m_8_11/12: ${c} UKNMAVHAXCBHLFGBHXEUNNCWXAXWDVCDLXCDYNBRETSVXTPSONTWFDBDJJCBROWSMARVFDZZDBCFKTWUPJLSVOIWHQSEGDNSWVGA', props),
compute('m_8_11/13: ${c} XVENJQSFYYXBOWZDZSGBVAWVSLRFYBOVMOERDCDUFDBYGCYZVXKPRJBPVHQPQDEKGZGCTBEMLZXLVOIJGGECXGRVJQIBSOMAEJLT', props),
compute('m_8_11/14: ${c} HLJYVJHGYUXSONKSDBEDFZBLKFUMQRXOVIMIPXAIKORJUNXCPGSNWSAPTONIICVOHKRBJXFHTPQHSVOAVUVUBGONBWQXMBIMKNRC', props),
compute('m_8_11/15: ${c} UTKXXWKEWTKYADYTHPLXNSXZFPAJJHOZVIUZLOACEUZOGHKSSUOJCBNCFSOSXZWNEZCSTPMHGDXVORNHNHEFEXNATWDDHALZEUOZ', props)
        ].join('\n');
      }
    