
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_5/1: ${c} YSOZAQUEMDZVSYVQCERVBXHRQHLKWTZBBOHNVHBNOGNUNXBTJDYLNDGFLJPOHTLPRHNSZMMESBFOLZTVMBRLUTRIQZPXPVARZCPA', props),
compute('m_8_5/2: ${c} SHRSSUVQYHYGALAEJFMXHARGEFJLLUEVULLFVAWZOZJJDZANMGYEGETQVTVMMXUIRWLXJCGXUPGCONHRORFUATAADVHPRMMXUQSB', props),
compute('m_8_5/3: ${c} HKZOORNBQOPBSRYFRJDFCYHXENIBBQOUCKRUIYFBZHYBMGCZSTKMXLTPYUKUOCMQAORREOSJZZZTDYHCSWJRBSDHUBUDLAESEKUO', props),
compute('m_8_5/4: ${c} ANHQFMAABIWDUZGXZKFCWKFQGMHDHZYAKGWRXYLFISNSHJNUWPWMHCTRUAPFOSGNBESVBWORCATQKTBGJUKUPENFUPNBYBBGSREA', props),
compute('m_8_5/5: ${c} HIOOCHDRNGBCDXHMNMYQEBQVCBXBHRZADWPGVSEGWZTYPZUJFVYIGQLFJGASYICVBDOGJAIASVDVFFBRWFIUXNWYZTZLNHPMHYJE', props),
compute('m_8_5/6: ${c} QIBUWYWXUYZLJDIYQFRBHPNXIOQQFSUKWHYVVYNUNSOLYLLORPHRUDVIATXQWWFBWTKXHKRIJAJDVPGRXJBQQAMEXLGBPKXMHRAM', props),
compute('m_8_5/7: ${c} AYVGLFFYZWLUJMQYIOWBPPSZWDCXJKWLUPXHOEOOEXKADJFLAUHLLOUZGITYFYRETXCXANQJRUPMCHSDTLAVHGIQSLJVZTROFGEA', props),
compute('m_8_5/8: ${c} VYWMGJIODBKUMSULQGANIOJWUVIBNBXFQCSBOQACMLJDXBYPSMWRNBKDDUHHSLCSBPOEFNNSZPNVIVUUTXEBXSKFZGYPENZKHPJX', props),
compute('m_8_5/9: ${c} EZPXELDSKYQDXWYFTIWEXJYAVTZQLWESGAARKNJJBHXZZFIPJZNMOXOPUHLRDFCMNFDYHUQSBUZBCLKVYBAWETFQEEEKOLSYQCFG', props),
compute('m_8_5/10: ${c} MIXDCRTVBVITLCTWXETONNRIHWVANFQEFNWSWQCLKDVIHAZNVMNWDIWVNQKXRQVJQNMZAHZVBBIORSDPQUNAKHGLDKOSDVTNEMCQ', props),
compute('m_8_5/11: ${c} WDMSKBFVGTUTLJZFGWLABUIRYXJDGHDGPIPNEJVPAEEQFSONFFZSXENQGWCUJHRUYFIMIKQGFNCWYTIAGAPCMGSFPCFZDJZRCIDO', props),
compute('m_8_5/12: ${c} WNRULLDREJCMQOEZDLIKZRIIIEWNJWQBKAOIYQNJWHZLBQGFXVIHGRKQJFCTHKYHSYIKXIFNHEBZUJFIGECESPTAFCMVCZMTIFZJ', props),
compute('m_8_5/13: ${c} XEKGBSAEZSYASADNVULRFJWFQVWEUPDZABOZTQONPDDILSCJEZSPZOHQLAOABLRXEEDPGAOVGJQLISTKUNDKOBKZPUDSRUPZXHRL', props),
compute('m_8_5/14: ${c} YVXLPWPCUEQMPKVOIVKQHMUTFJARRMPIJENTDEIREOTZTPMKXMNXHJRRZWAECLTXAIAYTAWDNKFCJODWCMIOOTVUQYBCQKWDDDEU', props),
compute('m_8_5/15: ${c} SNFKWBKRNUPTBPXMHQOIFPHCSUBXKLQCVCEJZRKOGHWHMEKXUWJVZERBXSFKBHQFGEEMTUXXQFFFCJYECJYIWTXXQKKZGORWXSHG', props)
        ].join('\n');
      }
    