
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_10/1: ${c} ATRHOFIJPALMBCRMSLTEGKSHJCHIROTFOUMETPZLVERXTAFQEWZNUNLMEXENGHXSSVEREOEDKVQFYYADUMONKVZZDBGXALJIGDWH', props),
compute('m_8_10/2: ${c} LERAAWPWQXQQHBOXZGZPXDXMCHPPKNQHDYYEZNUXHMBUUBJFOHQXXQQAVKABMVOWREMJVCRTPMJSHVVEFBRWNMPMOSKQYHGAXPSF', props),
compute('m_8_10/3: ${c} QTSDETQGFIYIITTWELZQBQTRCNEFIWSEJEYXWEEGOASHWUIQIRQKNLAWKYCYPXNHTDTIJAGBTEJZNAENHSQDLHDSRRSGFKVUQPDY', props),
compute('m_8_10/4: ${c} ZSUIRQPQJLQEIDPRICXZFJAHTFBFESDDJSGESLPMKRAIEPMARDMYYUNTUSWRPUBORKDVIUSGKIUVTUPDDNOQGJOTALECXOJQUIXN', props),
compute('m_8_10/5: ${c} BNBSFAWHDEMZYTATMOYOFJXDBISRQKAAGOWAPJMDMGZMOVKDJITJNTIEQKXOOHRLKAIZZAECJWJRSHCITGGAUTJJUSLEVMUYIHEW', props),
compute('m_8_10/6: ${c} GEBMKLUWHDTXCTDIGKJEDKXTGRSHPRWTYQYIYSMNKQMWLIIWERDZQHNYSMALDSQUPWWDEDZFDSWZNHHRJHDVURDEZXLGLQUUMOJD', props),
compute('m_8_10/7: ${c} UDBRGKTXTCDMEQIXIAMTBVSOOMYKUOMAYGEVVETQXWTSOAZSJMFBKYTZCINNRIFEYXZEBYYIHDWZUONUSFKCZLWNKRFVABHKIDSD', props),
compute('m_8_10/8: ${c} GOTKTIFIGQTGEBDQVXRAXDRRNSSGBMUTGJPHJBSKGGHFSZHSXPKXUERVWSZUXYBDIWUBXFUNTAMNOLTMADSNYXMMCQCSOLJQJMEN', props),
compute('m_8_10/9: ${c} AOXQIBPCEFJHKERTVNOCTRJHYMTKNKTZTQRMMWBMWWCFLHQTRODYRKLZOZIGYFNIKKVRLPAADUEZEKUWFGSXHSNMSCZRQAQIOVWD', props),
compute('m_8_10/10: ${c} BMLHZSVMMYUYOPPPGVMXVULXGUTSVKBKMVICPDSWZDCLOTZHEVGRKPKFGILZFZUNTSWHWKLBCWTHBHWKPNKTBPUQBNXKVHYQQBLN', props),
compute('m_8_10/11: ${c} IEWZXTGAHKZACSBSAUQSVQEOSORSTIWGUKGJFFOVVJHKUJJCSTYYFZGZECKICFVFGIFSEMAJIAFGVRPUGTNAUVIALDEHNTMPKLPW', props),
compute('m_8_10/12: ${c} WYNFKPSMLNCVGHEPMGVZSVJHBYAPUJYJOVREQTYYPNVBURZSLRHMUTCBSGEIGATYUZXPHCNBRSCFOIHHIVFLAQOWAMINRXCGZXOO', props),
compute('m_8_10/13: ${c} WZLAPXPGZHLSPZKRYPXOIQNPBMRWYVHFFABAATCVXUYPQAPXRETPWABOUPDOINFQVLKTDCNYLYGERETYBOCYQSGPZYJBIYAXSOZQ', props),
compute('m_8_10/14: ${c} ZZXMQRKYBCZYTUIFZSUYLHRJPYMWXXBOHJJUGZRVOMLZGQPYHGQUGVMTRFCCVAEFNQZUQXDZEJRUKNYIDPROTCVKCSSXZGCEVSAY', props),
compute('m_8_10/15: ${c} TWHUPOJYYRINTUQYNTBFVJJSADKXVATNKQGRZZKIKEQPRZMAVLEUOQWTCYHMLVFFCMVJSJVRCAHTXXAOKNGORIFQUMKIBSFYLKVX', props)
        ].join('\n');
      }
    