
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_17/1: ${c} WYBORVEGJALRPFXFSHIXQYYZZRFYEDMBXRBFAETMSOGAOUKYNDNQRWNQALUPCIUQSCDHGBVIQQGSIEKMQNLXYYTODEXUXSUJMXMC', props),
compute('m_8_17/2: ${c} QQTUXACGBDUVXXUEFLUJXICWELTDEUFYTAVDWOHNGIAUWLYTRJYVXWOUIQQTWSYDZWAKUSYNAZSSROMKJMUWGITNKXXPDBFXLLLO', props),
compute('m_8_17/3: ${c} ODTCALUAGPOFIGDHJQUMNAXRJEZWWTKCDKLXFBDKTHAMFWVYNVQKQVHYBRPMODQKQDXZEJFIWUIPYANOUOVGFGVLLOWJKQMEQYHC', props),
compute('m_8_17/4: ${c} BJTCEZPEZLOASWTKHCVQTKJIXAJCAIXZWFDDOPWILHUUGBIZRYZHAMOQMFXLGVVYFXQZFJQTUJDVOIPSZVHJUBKYNYNMZEJSIWES', props),
compute('m_8_17/5: ${c} ZBAZAAHFBVQTCUAHZTGBEMASRJNUUWYPVTUSACCXKRBFGKYXZROOMRWOHCHKKWRNBYLSDPDSUGQSWPMFXKJEMUFQMBHFLQFHQAKW', props),
compute('m_8_17/6: ${c} MASCAZPQVJUNAMFJQKURUVOSYEWJXQJGJFBEUPNPVVVSAFHMTRRLUKWQEDIYMHZVHAIUZJJMQVIQARIEOIVBZGCSWNPHNKSMLKEV', props),
compute('m_8_17/7: ${c} NGBNOUXMLAQKDPZYVRIJEZIRVNWGUDREATVLJBSCTBPLCMULRJLZFXBTMOAAOWOPKHDVMTJUHNEQGAGYYKIXKJNOGRYTWYWTETMK', props),
compute('m_8_17/8: ${c} UMNMEEOKIKZNKERYUSZIGSLGKBLXHPHDXTJNUDBANBIQVKEJJLIEDJXPMCNJOUATFUXERPESFPIWTRIKVRNYPKFKXVZTEZHQQEBM', props),
compute('m_8_17/9: ${c} ZXYGZGAPGMHIKXRGNXTUZESYRPXPFAKVIDRYESNAPOZJBGIWAJHWOPKHWQZGIRZQWXUBFHYCGGIKKXVRPLRINWCWDIKCSRRCWJCB', props),
compute('m_8_17/10: ${c} SOSZBPVAPHLOHBSNLQTSEZYGEHCMBDHGPCOZFKZWSYCWYJLIVBAFFJVZBTDLPIWUSXMYRINNYTJTJINQMJYMXXVCWGMTQUHKYSCD', props),
compute('m_8_17/11: ${c} YUEOCUSALTWWXNTDVYQKKNBNYNVVDVBBFFLJJPEBJZQDVWSKLAODMQLGSLVBPIEYBUCKWNFSFCZYQLLVZIGKKLDKWUKJJYEEIINK', props),
compute('m_8_17/12: ${c} INTQYWNTOPSSYPQWNNIFJJKAPRAXQZIJBOYANUJSURNTNQOOINWSIEEAFOKUMGOQZFIQMAAZGQKGKSBEFGXCBYVMQTFNXDJSSEXN', props),
compute('m_8_17/13: ${c} QQGRGHTBSYPCNOPENYXHNHXDPPOCRJSMVJEJXUFHRGNHTAJEXDXOCTKJJPOLMSZGRUJLMGQPCWBHCHBEBCTRHWGMOGWNSRFQXEUF', props),
compute('m_8_17/14: ${c} CJGTPEXKFWAOBNZYFNKUYAPFYNRHZABQIGUEXMGDDOQESTQXXQOXXRPPAATXRXIOORWOQDYMCGDPSUYNVRKQCQVFERGVHEPKCTRP', props),
compute('m_8_17/15: ${c} LOBLBELETRRKAXBZSSCKENVNYFVEEKCAEUZZSXKNPXPPTJVORAXISZRXXKOUCMQEIXIUAZZZXGQPONUULATILQFMITKDLJTQSJIN', props)
        ].join('\n');
      }
    