
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_8_15/1: ${c} CCKUMTLLSYPKFGLBIMWJUKAILXEJPYNGKUNWENBTSPUHGGISCMMPDIFRYKJATSFGSLXYSAVHUFIFWJPPANMPAFXAUAKPJYJKSUCX', props),
compute('m_8_15/2: ${c} ULMHZXSZAOGUTMGBJNUTWWNBVQGINRWIIDJBTXQSBMFJQILHNKYAFKDLBNFLHSPMEJSQGSRPUWBASHHFJLAAGTKUUWQYLNNKUYEX', props),
compute('m_8_15/3: ${c} ULNFLVPUJNYDDTPAAUIHZTAEUVTTGZZPIKUGEGJXZBEVOZIACLQLYBMDPFBCSNBCRIWJSTPXMIMUATPNNJFYDAZHKRNQKUCDFDLC', props),
compute('m_8_15/4: ${c} XSLEWMPFPSTGXNUVGNPRQSIFIJTYFVDWYJJHMEHWOFHJYSRFNIBPUWOUBRHJBCVCODGHAMICEFLIHDEGQOEJODTXMEXCVOSCEPVG', props),
compute('m_8_15/5: ${c} ABQPCYTSGJTDWQPUFYXPFVLQBLQZBYRXEJLEEZITJOEAUSHYXVFKHOOENVJDOMEDGGVIZUVKQIGKRMMKXPSCOGLTPPMMLDBBUMUY', props),
compute('m_8_15/6: ${c} EBWRNYGIDDLAYVBIONZCOUOOEZKAEDUMZVOCTICUDOUSQILCVBWYXRPCWVLUIGLVZFBRPPAAVWFAGCLUNQYWGHDQCKBSBUGNTEQM', props),
compute('m_8_15/7: ${c} AWVVBTYAOMAWTQZGAVEIHIITOAJPGFWGZMBQRXBAMDDTIDYQVFCNYLBVQMYBIRTOHOYCSRIPUSCJXFSIPBTQOXKYDYCSBXZFWVTY', props),
compute('m_8_15/8: ${c} KSPDJCKVMKOGYWWEFRYNLBAXEYHODIIXRHATGMHTWPXXHGTMQAPCXNFGEPMRKGWVULVGTRLOUZCIZPXFFAKBEDGHAXNDTLMKCFDQ', props),
compute('m_8_15/9: ${c} TVWQXNHEOJPSIWHMHUACGMKKVZKBRTYDNIKWLZUGVNSCWNDSIZFQQIWVFGMTIRGBSMMVRCSSJHGLJPWDSFVAQLQEPGQVNNSDBJDJ', props),
compute('m_8_15/10: ${c} BLFZNWMGVQCPJJZOUAHQLBUIOXDLKZCYDKYFYYJEZIXFYHXLVOUWAODRGHIEWJQYNFAFXETYXHNHIJPOSYFCSKHSSWWNEMSNYYXP', props),
compute('m_8_15/11: ${c} RQZYFGEMMBCTBFBCEGGKYLRHJBEJTZMBCNLGBUNMNOOJFSYAVZZMYXFFPMAVSMHOXDPIKSIMTGRMHDOCTJVQXYDFEOMGEETANMXE', props),
compute('m_8_15/12: ${c} WYACHJLWBXHCDTZTSXCSGNKZUJZVNNHOWVNSIAKKPJMEWNADQNWALBTCVLOHEVFIGFTMFPPYOUIMTCXIEFNUYOCAKFAOVEGVYAED', props),
compute('m_8_15/13: ${c} PVCYYDDPLYTISYFWVLVBOLNLSGJOACJACXXTYVLGECGDRNRSTVHFNRNDIVUIREYDIJGRQFHUXILDBEWAPOYXNOHBSQJNFUMOTERR', props),
compute('m_8_15/14: ${c} VQPUALWWDDIZQCXRDGIZIEPBSFQCLITGBLCJADWQERUSYXPNRCRMILNTALDTDLZOFJBQDLGKBBCSAJPAWBHQXLYUPWPGTWFPKCXQ', props),
compute('m_8_15/15: ${c} PEVKYLMKRHNHSTYRJREWRWIHDOJXXCXHBFMZXZMOGREMBKOXHQONXVEGWQWKKBSSHJKBMMGMTLVGFNHODGRGPRASEZORJLXHRGVZ', props)
        ].join('\n');
      }
    