
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_6/1: ${c} COROXPZXLRKARUANYLOGPVXAIZXENNPKDODOMFIINILUSSEPUCSGEUALTZARSXHZULHZPPUVUNSINMDOHVJTBNUVLVXATJUFWMVX', props),
compute('m_9_6/2: ${c} IXMTZLPVBFGGFOPEVWYDVSFORWNYJKCQFICJBRYHWXYEDVDFLLEEICQLAXIPMMUXGDKNRDJZWGGRGULTBRUIUSJMWPJFMTEITRBE', props),
compute('m_9_6/3: ${c} QFGMLRMPXUATIQTPIXGMRTNMXLDIYGEWBDXOHHGXEVXSSZFUSNVPPNLYUSQORFVBDWESKZCCCKCMSTRMGGRVUTBWSIHIEIALLTMY', props),
compute('m_9_6/4: ${c} IUNKLHBDGYDOCDUQSXJVBTROMCBXNWPOKSRCQYIEGVYYVOJZCLJNVJICYRGISGOAMQCBKQRTXNZREQSTORGSDNBSCRWSBYQVTAAQ', props),
compute('m_9_6/5: ${c} EFACUUTROCRBQOTZBDLUQBUDEPZHKYPEYQZRSZIJILXDPEDYUSBFFKECEIWJHPWOYJESANXCWDXPAUYZYQFECCRLUWIUIJQJKRWR', props),
compute('m_9_6/6: ${c} QEVUIKSRUDYPMZZDRWTQJVYFTKDWERBHLVLAWMVWDQVRKOVWPBKCPTGHRIGTDHLOUXSTKNCDFYCNNKPIZRJMXGUIRNVNQXJWUUCS', props),
compute('m_9_6/7: ${c} UAVVNRUYPYFJFIOVSSBGZHYRLKFUOVWKIWOVRTLRGLDOTXABKAOAYVREGUBOOAIMZWRRINRNYXOKWQASAIVXKGJMCHNIYZCLYUDO', props),
compute('m_9_6/8: ${c} YGVRNQGUZOIRRNNWGXHVVVKGDJNKLMYHSFXVQCPOEDMRTGIMXKPLOYYSKSJMOOATLNNHEBCZWHHWKIHKINVERYWHBICRVBBDPXRZ', props),
compute('m_9_6/9: ${c} FYYLDVFSUTMSCDYILVEAEAYZCTBYOQGYYGIGKHNACQVUNIAEETRGSXIMUSWLKKRRJKBGZQXXQGZMXJVQFPUQBCZXKIATOMIRQZIC', props),
compute('m_9_6/10: ${c} ZABPGYQPRCYHLSGHTVOHXOVRHAWTPJRVAMAMHCNALTORKPSOSHDLUEQCIICUBFNFQRAIJYLLSBWOMNRQSQGXNMTKPQPFEMVMEEKE', props),
compute('m_9_6/11: ${c} VZHTDYOCIERODGFQRITFSCKUSRJUCHFBLSCVFTYMTTNTEHCTJVMYCZHFLNKUPEIHKOHVGTJANMKUDYXZXPEUOBFIFKJLOLGAPDRF', props),
compute('m_9_6/12: ${c} CRUBKHCFAWQOHQZBQDOETFXFYYYNDZCBWBWLXWXTLNDNAPFUJDQALJSNVOCQXDNTACBZTDXTGAWEGICRQZGOKSQHUHWYWVWSHZRY', props),
compute('m_9_6/13: ${c} YFUYSKHMQMNLIUFIUDWJSDRSHCLXEEZDBYGNDBYJTVMTTXYZHXTPLVNMGTLMQMHLGRAUJEEIMXUVOJHELHCWBFFGQVTZFUWEYILT', props),
compute('m_9_6/14: ${c} CWDDCOAGFLFDFGMGDIURKBMNHXIVJORUTIXPXDBOBPMZETIESSTNQKCQONNTAYJFKACVOONCCNBEKPSYWSLXKWYTOMSYCEHTAQPQ', props),
compute('m_9_6/15: ${c} RTMSWRCHSGLMRQIFDYUXHYICGSZXGFGTHMUCHTPTSFVEHLKYOLAEXZVLTRXWKCHVDWINDKPCKXSLIMJWTDBRSBWZPCAENCAFURYP', props)
        ].join('\n');
      }
    