
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_8/1: ${c} TEWBOEZMYVHCRZNEMRVQCGOQNANENUTBHVHWHZEWRUOFJWNUJPTAHHMUDTDUNKEHCAZZGABZWPKYOXKMWZAJVGPDFRWNADSWBPOT', props),
compute('m_9_8/2: ${c} OGTEKYZCKOQXDSPMYQYXEQXTUEXOSSTDHSQUAMYTSRRKKHNPFPCUMIFPSJABVGMTKBBSDPHEBDQTZJBJOLLPSKORNKOHBINKZLIJ', props),
compute('m_9_8/3: ${c} TMWCOLFZPOIGIZHJNZBOYFSMFKOKFNCJFKPXZPSFSBQAXMDAZIYLZGADZPHNCXWTWFCTFCHFKQBCDPLXCBAAWFCZUURFSXKDYAPR', props),
compute('m_9_8/4: ${c} KMRDLEYBPJPJMZGNBKADBSDMJPZAXKTPOFGOGZXNXZYPENASHBSVPMYSYTJMZXRQMOTFUFFIXYKAKEFXBFXVLISLUCILWTYMATDP', props),
compute('m_9_8/5: ${c} FXBURPLAANQRSLDJKQIQQLEYQKFJOJSPWCIAVXJMFFJVYSEXBSOWGKWCSGMQWDBCJEKPKEPYNPOARNZNADRPRNDFACMLWHWXIYVH', props),
compute('m_9_8/6: ${c} KYQBSETAXZTXPXULVCPCOBXTVKDFNJPPRZBKUDZKEVNLVNVMCNLEUKGTCADSEUAYNUBLQHJOLFCPYUOGZIEMQLEBYRVKGSOCCFZN', props),
compute('m_9_8/7: ${c} QGJVJKGROISEOYZNMOYBXXPRZOVSRAZSKTZVTQWTHFESHLTUSAYPWXYHIJTJXHJFWCQYVHHKXYKGHGGOGGOWYUVMBEFLJEMJBOPK', props),
compute('m_9_8/8: ${c} ZDEXJTYSOQCAZUVWQSLFAWGQGVELUPPYQAYDKXMIAMAFFVYFVDSERTFBVPVXUGPEBIKRLTQZKONOENOCDIPNQZPYSHAOHMFIOBUA', props),
compute('m_9_8/9: ${c} JDJWZSGWSPXTAUMSTFBTDJBBMOAFJUBOWXADCSEEIRGAYQJCCIJLIMMGXICRUUCMJXCIUFDMCTIURGQQNCQONWJEETKISLYHUNPD', props),
compute('m_9_8/10: ${c} WVEZCYUMJSHURJKYCBZWRMFRCBOFNEABMUGAGPNUAXUPSGFXXIKEBAFQURPNJDJNGJQMTISEUNRBHBOICSAXWVJXZMRQRYQSWMDE', props),
compute('m_9_8/11: ${c} DIPJSLTCDDXWZXPPIVERLTDSPDTYRTGIASCCGMNBFWLSFPZOWXTPJMMYECFRRUCCRRDQZXKITRKMAIAOBRHQGAXISOWOWHGSIHMD', props),
compute('m_9_8/12: ${c} RRWJPBVJPWNWVFOPYMYGLNYGLJHKIITMYYDREBYQYDFLBMHFHVTYZPQTGDOELTLTSRJWKPMUOJGRYHDWLYHWCZYZCGTUQPBYTDHU', props),
compute('m_9_8/13: ${c} VFJLCKDBNFFRHBGMBTTCBVGPVZVQUMMJXFRIBYQMERETHEDAQTNPFXQMXDSHCMSQUZCZARUFBFVILZQNFEGOPWBGTZHEFUHOZVWH', props),
compute('m_9_8/14: ${c} PZIUFKTMKENECCLHIRQYEZBFVNQPGDDMQNNDRRWVMUJUTHXPXSCROMTBHJKSQYYLTJZFUJFOOFNZQLWZOMQWDTQXWCQLGYEVQZLW', props),
compute('m_9_8/15: ${c} RZWFCQPSGAIVSPKPMRYQSKRZHIVEGMURBWNTNNBXYHOMAAIDBVSSTIZXHUJDIPIGUMHTVNIGOKIREVZGHQHLOTUOCAEDAQIPJDXV', props)
        ].join('\n');
      }
    