
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_20/1: ${c} LSYUEFRIPAFSUPNNUJXXYZQGIRURDGWZPVPVOZSNGQKGCSEVVNCPBPZUWZUFNSAKEQCVKIWAPQKDBCRCKPWKYVDYFAJITETRXFXL', props),
compute('m_9_20/2: ${c} ACWOASROACAKWQQBZHEDXSPRFJMKVUVQRUSKCKBMAQSATAWQPDSGVGLJNYNAZBKYNTSRXKVIEYELJJRNGVKBFJKQKBUTUEOOEKLL', props),
compute('m_9_20/3: ${c} GQXPWURUGZPSHTGVSPODOYEVAOVJRITJXMYQWJYTMPVPVWOQCAZDTYDCZTINDPQLAKNMZXTECWKNCRFCDLXRLEQIYGKRVBBTTONW', props),
compute('m_9_20/4: ${c} XZXCUOQBHJAFVYNWDSPCJWJVENDTRDQCQIQEHPPQZHMTEFIVBYSLXBFQVWHKEXCQKYOBNWJLLBNBJAQDQREZAEIVQUJJFQWZJKGC', props),
compute('m_9_20/5: ${c} DKWTCRWIYAAQWSEFODFJAWOCODXQBTCSFLUNELWIHZQWTDYFSQVVOIYQIYXRTOOWHBPRDWKXCFVVVEGJVJKPPSTRBYOPABFKEQHN', props),
compute('m_9_20/6: ${c} TBYDNMDCXBVVEBLLLFCGQJZIOELFJRJSLAGDPAJVPXQVCAYVCYFDWWFNMLEJMOFYXFKYNFOMICTYLFVVNPPNHCOWZEAVNZYTPTXX', props),
compute('m_9_20/7: ${c} LYQDXYPOHRHYZWRVRYBWNGEBFDGAVVKQEHJALOPMNVKKPXPBVEYJASOFIOAOQQMEMIURLOHTXWUUOWJEXNOMJWJNYABWPMSISKBG', props),
compute('m_9_20/8: ${c} TPVDFNBEFBYMUHEHFDUQXDVHJOCAQWQCPUKZUBRAFEBLAVTGTXPWBXWGRBSKGVPPSGSBQYQPICDZBKLJKEWLTHRUXQZAGHBMITCA', props),
compute('m_9_20/9: ${c} JAXRZUDWTPEDNOKXRKTZCQNEZOYQDZKIFWHWRYXGNJVENRHTEMVVTQPKXKEDUHAAIMDMTLBVHQRKECTSRQIJAJONGGLHIQCYQJBE', props),
compute('m_9_20/10: ${c} QQQADUWBJNRYXHLGHEDQMFSEGGRKGXWJDKFOTWKBQZIRPTFJRPDLOLXGAPRNZLXPZLXDIKKQSBLYZBRWFFJSZSDTVAYRRGHRNCWO', props),
compute('m_9_20/11: ${c} AVNEDNUNOVGSXXGNZRVZYTFKDYWQAQKEGWKFGCMNWTQMCCUEJWQPNSEJRKECGNHPWUFKXCPGLFTYPYAGFSJLRVOPQLHZOEDDQMMC', props),
compute('m_9_20/12: ${c} OBVMOZFJTLKJQBDPMDAEYLTJOXYGMEDGEVNDTWWXTSKKIJHLNIPGDXKFSNXEKIGHHDXSKIINNYEYBLHSMUGODHCIELZFLAYZWUPH', props),
compute('m_9_20/13: ${c} LIYEQGEQFZUDJZGIXFDTATBEEPGVLEEVMVMLOQKEQRCSPAACSZJQWSMNCAEWULJQJBCNTEITCMVNNVXJYDMDHGNZHDIUMGMKAWSR', props),
compute('m_9_20/14: ${c} WDTULMBJTGJYPARUUFFAWXGUURTCATKUIGOVVWSHFNQJLDDFFYFNJIBEVBKMVEZXXUPHEQTKCDHFQVAGCKEKRYSDOQGGHYBSCCNO', props),
compute('m_9_20/15: ${c} HSREURDORVTRVYGUKQFFOAUSQFBKYCDPPEXSFVTEOEKTWBNBZGCSFODBQRTGEZCDKSGSAONFWKAWCMFSCJCVHVMMVNDWAZONUIUV', props)
        ].join('\n');
      }
    