
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_18/1: ${c} VVGNHNYIRBXVCRIRMXJYJBTNMWRZTDISXSCWMQHYCEZNJACAUDGTONWCSBMPFVDBKQZLDLRQBCMWNMUKVNZIRZTOHAYLPGOFXLSI', props),
compute('m_9_18/2: ${c} ZMBMFEWNWILEVCAXXPZWNNXZJADBAGJNQTQLOSPNKOCHOJHDKIWTMRMJLPTACGPQRVVGSVPUFFSAWFBEXKVCGCDSMCLKQQTUQRYB', props),
compute('m_9_18/3: ${c} FFWRPLYQLPSWEJMUAGKXZFRUPEYUDBRSSYIBIBCICJPGOZISYMRJVJZKXRJJKDGJDCZXBUSFNHPRORSZTDBOOXBSURJJNVWWEQMZ', props),
compute('m_9_18/4: ${c} GYBCKBMQSJQPIQTTNTKIJKNZMEOQLTMVSWTEDAKVZMGAHDIVONJRDTSRZWGUNCOEXWKQHTJINNTCJCPYQBUKCUZENWZXTLQCKQBW', props),
compute('m_9_18/5: ${c} VLTUDANKFDRCWGDWYDYVOUYVDNPTRJYCEYHFHWMFKCEMONOGRROFTRDBIIJWKJHKMLYPOPYJJFQTWZJDIRNQVNFNXDBTRWYWDRID', props),
compute('m_9_18/6: ${c} WBFVARDUEZJTDCWCGACJAJYKSVLIDBUWWQLWXZPPGCPWIHBRIFHRNJEIDKVRDLWMWVXGIQMUYVBHCBCSAXGXUYINPNQTREZDTLUR', props),
compute('m_9_18/7: ${c} RJDVPXKDHEDJLRDJHGKLZMLIOMRUMJATSKEQOIFVZPJXBSMTQZSCPGRPYXLRNYEQWCGKBJTBXZAUFLVMXDFIOTBLLJWWKUVSPSEU', props),
compute('m_9_18/8: ${c} FOLEYECTBXHBZSMBLGVSEJRPYFDARACAJAFDAZZWEZFVYJLWKGLELWNUGABXCFDZXPHLKMJFEDLFQQACQKJQKASGPFBEVIDMOAIF', props),
compute('m_9_18/9: ${c} ZGNCWBWESMNDYGKTLYTCCSOJEQCEHTNTOXHZDMHMSWPZQHPLSDYXAQKKGZGOQSCEDLYAQDKPIQTXDVXCEZRGHXJFRLFWHUSGSNOQ', props),
compute('m_9_18/10: ${c} ZEPOHLLZWKBRQRTEWJFGZZZBTIWVICLQFBCOHJILVIZZQDLECCKAZMDRWRIGASKDOZZMWRUDLKPGICOAWJHNWMUESZWEHKTDRETH', props),
compute('m_9_18/11: ${c} KDEZEMZYNBPOECDFUWCPPKPXOZTBRLZAQJKTXOFQDDZVAGBUACLKMXODLOOKWAUFGOWNKCKQIVHWKBDHHRJJACHSFRIIFOZXHJHP', props),
compute('m_9_18/12: ${c} VOCHDBLXOZLVMLCBXBYWDBESOOWZTZXDJMBYMVYFXQRVVNJZUKAUXSAZKABLPRHVIQFFGSXLRGSLVRMFQWPZRDFCTCKXHOPJSYFK', props),
compute('m_9_18/13: ${c} OKBHXYBPPCKKVXCSZFDUGOGTVQDIWCFSSXGTIDOOYSPYPCBYZEVDMVARBWHLMJOHQFLCYDPCSPFBUQEFLRQLRQOUGOFVMHMWNEME', props),
compute('m_9_18/14: ${c} JYKNFYWMTMHGDZOBKLCFUZMFIJDMHLTVZOHIMRJCMQKBDZCMDFLRYIJBXAYTJBQKBXTEUVQPVRBMULPQOQEJWYEGXRZZJNCHVHJL', props),
compute('m_9_18/15: ${c} YZZESWRDSWNBMXZLGRABREIMWJFMXAPSNAAVVLFCCTXMWULQJFDYTLEOJEYICFNRRXYYKOWDPNXCFWDKWRFDJQSJGPUGXISVHXSC', props)
        ].join('\n');
      }
    