
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_19/1: ${c} HQWJVNHKOKWBIXQRQCVNMFZHOKVDEGYRTKVKYHJEJSKNGFZKFMLWFEFDXYRDUJBTWDUBFZTPDNFWNXJPSUWLIQVYUUNXEHHETPOX', props),
compute('m_9_19/2: ${c} UXIWTTBSDJEQYFXKQLRKEXOBZUTWJMACXBWKOIAHTMENDCXGLPCPARGZJZPAHKCPYZEKQHHGDTGNMRWCIFYWXCIIDWZZMTCUFJQA', props),
compute('m_9_19/3: ${c} KJSNIOCVYRFFZYSZOZJIMTPPEAIUZNTCMTSPIOBODZMEMYXVHZVTQHHBSYPOGDDQXJYDSOQSIOXFPDKTPCZCBBZCQSJMJMIIEGVX', props),
compute('m_9_19/4: ${c} MCTZIICTIHAMYROABTPDNVSAORTQIKTDJSZQBDGVBIPQAGKZXPFCBONNYSRFQSOZUKHSVXDHABLUEKRSMCPAOXFYJYQUDXYRRWIM', props),
compute('m_9_19/5: ${c} NOWZBXDQDYBAVKWGUWMEFHXYUEHUORBAWMCLQVXNSSZLVYOBGKVDTVUAUWLNLLJULETRZAOZMJXCQXKDKOJLOAXWOHLBATVKGBOX', props),
compute('m_9_19/6: ${c} XOWFSHXGNYQSBYZCQWBBYAWKDSNSMICEAMFCVCQVEOIRZQPZPMVCHREIUYXGFHXSCWMAINACVNDADJCKIXUYASJNTBRTRKXMVEED', props),
compute('m_9_19/7: ${c} YJRTFESSFMYRJLTPGEOQENCMQOFKUJIBNXYALWAXPYMDIUKBXQMFMSJPIEXGUEWZXGXKEQSXTGWWMARQLSZFZRYBXLDAPZBOLOUF', props),
compute('m_9_19/8: ${c} QZHQNZXHPENWPZINSODKNDDNVZDRVHOTXURIZRSQNUTDZRYRYZQIGABBXDMPQLGBCPURIEGXQVPZZOEAZYSLHQSNRAIZMGPMRTUM', props),
compute('m_9_19/9: ${c} BVQKIUTGLFHSYCLBTTLDPAEVWXXDFBIJRTEBOAMJCOGLTVAJEMPJEPMMFGLHTGCAPQPYTVVDUXTVDHWBIEFDDVJCZHXFHNGJUBVY', props),
compute('m_9_19/10: ${c} AJIJYTSQGPRESLTGRTCNZIQWZYUPYWMILFDFQZMVKVPVGCHVFYVBWNUEWMDKGHCPLMPJRTBYCGLRCBZDPBJFCZNNJFXWIJNMLXAX', props),
compute('m_9_19/11: ${c} PNHHDMZNHXUFSKBJBHPBCGAYZWNYBCKEJINZBMSPRCUQVNZYHTPHGHBKJWUDYCCLHBSWKUJKBKMVQCAKPJLTSJAQPEBDOEZDBWLX', props),
compute('m_9_19/12: ${c} QZVJYBJIDTOOKMZFYYOGSJEILBFUGPTMFVWFRSWQEGOAJINGFHTIFRQMBCDSDXHRKHSQVJYAYVJLUCWXRKNRKMTGKCVIJWAQIOZJ', props),
compute('m_9_19/13: ${c} CFDNGDPQLTTSCBNRMYGUSAJLQYULZEVOSDPDUWLMVLYYDVRAJTYLHWBOHAZQFBGBZWCGUJCBBOFHTUNTFATHABYAUNJVZDYBHFVZ', props),
compute('m_9_19/14: ${c} BMMPUMOXYZPQABZPROTRVDUQKMUHSVFAZLABTMOLDXPTNFTYEUUJWOBXMGKJJVYTDKGLHVGEDWVOTZIOWHTCKCCMFNDBQSAQYTTB', props),
compute('m_9_19/15: ${c} XLAGMSYHCFCWQKWOQEAVSNAFOYECQOIBROSTOXSUHVCDYGCYEWGLLYGNAIFQWTLLMXYEVHCJYWTEXXAYKROZTSJEHRIXDRKMARMY', props)
        ].join('\n');
      }
    