
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_5/1: ${c} QLMSRGXSGUIBGBLOUKXAAHKGKHVTMEDEWIAAVNVJXMTDRGYVJAWIEYAGRNASKIELNNGUASPILNXIAHCQMJAVRCKSXDUOUPMZPNQB', props),
compute('m_9_5/2: ${c} JGQBZWGGUDNULPZHEHUAKVYTUTRKVNUZHPCMXDQNLBWNLOCOJALXFUGBJDIOFUDVKAVARCDOMGHQGLPUNIYBIYLDZDVEJFEOKXCU', props),
compute('m_9_5/3: ${c} XVZBVUXTOVRJXYDINJWFYUECWHOMSFOGHDBQBRMVLGACEKOZDTCSROTDUUPFASCSSCFUUKFKPHKBTZXPWFAMVDBMXPELJWBGYBNE', props),
compute('m_9_5/4: ${c} AJCTEDDVJEJPSBIKSJBKBFFGORKNBBWMXJFODELSBSQRJVJIGLSVJXFDLXRJHBXTFALFSKJAFAJIKDADYAXRIBJNZAFJSPJFHXNS', props),
compute('m_9_5/5: ${c} LWSDRUQZLGSBRERFKLZGXFEBPEIQPAUOQDWNXHUPZECMNPSYWIILIRQYXAZRHZAOAPYYHYCSKINMRKXSMLFFNLXCLHXILYQRQZYU', props),
compute('m_9_5/6: ${c} VNFTBKCYJLTCFGRZNPUHMTAWUXDVNNWUZAQYUEWQWSJJMDYWELQOIBPYIRFTHVMNNRXLXSDWTMJTYVKRKJPQDXYULDOHZLQPIVPJ', props),
compute('m_9_5/7: ${c} CTSLGUTEVANNXOGEHZAUDPQIVJFFJARQLVVZSZITESNBXSZFJIZVMWMYYJNBUJIDQYHDGTROVOMDEUVOAKVPTHOHSRMWMZHQZZLH', props),
compute('m_9_5/8: ${c} EYKYRCCERDNSPAGFULMTHQVURURYKZJXKPTVROCASOQWJAABPKAPHIOOKOHBEQNQZWWWHHYITDOANKVHBAWABPQEAMAHKPGUSLMO', props),
compute('m_9_5/9: ${c} XYUCRUZKJTHNUOHVLXTUHQYXSLMTNSCUOSZWFNCTAAZCJFXDHMFUZJCTVAFPSQLDNCQCZYNBWUALKLBLWQHGPGRJBURYWJUJXWBQ', props),
compute('m_9_5/10: ${c} CCIAEJTXYORDKYGNODSHVKVNZNPLKTPAZBSTEUMLILLXQHRXUMZUCPRWUROQUCLCLDKIYEZLLJEOASMVBPISWMNASHEQGSDZADOB', props),
compute('m_9_5/11: ${c} HOVZKKEDFGCWSKXJPGVVGPHOOFBNETVGZOKLLPYGGQNUEVFUNZVLTPLAOEGXBCYZMTDUASKVQBGJYSLGWUBZMLIECSEHKRPHXUMA', props),
compute('m_9_5/12: ${c} ARNVSSZRHWGBCSTCWYAITSYPHUSEJZVXXIBGUHUVTOFHKHCXKVCAFMGZJNOLALLWEWIZPZPYDAOVWDWNJLNQHXMORYWGDLIYXLKD', props),
compute('m_9_5/13: ${c} FAVITLZYIBVHFIESUEHXELBGRRHUDGPDRPRBHBFUHWMIOGOALIFYWUJZSCMTGSULOFUSSUDJXHFTKMIQVAWJSMWZAROCVSESUTSQ', props),
compute('m_9_5/14: ${c} BWXYPBEXTOGACYCNPXPNZVIVLSGCENLNJAQYHPTYWTSYPVEOXXRYOGEAFEQYPBVDQEFXCVGXXOPPWHUMMXCUDFUOTIJDOQGVRNXH', props),
compute('m_9_5/15: ${c} VFOMZQYLBQDFEVKLQZQVDLGICDXLKPPCFJFAPKHQVJKOWPNUFIPTMDACPOBAFBHOJSYZROBKISZMIBPVTKOJJPOFSCCLGMTSKEWA', props)
        ].join('\n');
      }
    