
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_12/1: ${c} AKUYUJSWMKGDXTGODSCIDYVCVZLNYCCHGVLQQFRZBFOZTMRIYNFCHPVESHUNUYYUXXOLMNJQDBDSRVMEWTQIULCOCJJBPSXDDINZ', props),
compute('m_9_12/2: ${c} PQIRTRPTCLZTSWOSAEHEDIBWTPGTLBXVDWNNMRCDLZPTFMXUKFBSQZNWQPYVJVRWPZGFDVECDQCSXRIYXMEMWUEMIMFESCTRZQUP', props),
compute('m_9_12/3: ${c} DMIWWJPVPJHIAWLKKRLXJPKDNAXDVRJEBINAMXQFMHBEQQOPVBANMZXWEOWJFAMCGZWOQJOEGZVVHPFEXTUKXZAEJHGAGZLWHNPS', props),
compute('m_9_12/4: ${c} SZMMBLEKQHURBAUNVPMBGLBMZZENPLRETLYBSERHQFPKGBQJEANRXXSXQFLTOPWELEMSFDZPMJCCBLVNVCHWQIYIMWPARKEPUUAR', props),
compute('m_9_12/5: ${c} RFFACHCYUBDQOFKHQVDSLNADEKIDABBCAEOZEDWAIUPJMQEYDZHSXZVSLVSLMBRPQLOFJUWOLBRTWJGDSECKMFVEVALEWPJLRJCK', props),
compute('m_9_12/6: ${c} RSLLNITZZRTJRQDGSANOTLANUBRPUAKGAKIARKPEZYIEWAKWUWCHKKMDSIOJPPLUIAUGYWUYLXLNICVFEVRVIRRKOLRVCIVQDTFI', props),
compute('m_9_12/7: ${c} AEBMGISDEZPDSZMOJIMRLGHWSRTMMUOBDCOPASBMUAXXQAGCWXWFQZGSZGQLYLUHJDGBZBFMYXUATYTNMKOKNFOWTWPHVOJVULHC', props),
compute('m_9_12/8: ${c} CAQAXIDMONSYVKFQLAGIATUYGELZHCIYKWZNRKTARJGHKQHLSJCTVKTQIMDXNRFDQNCCGACSLQJUTZERMZUIXWBDBULENZYZLQXS', props),
compute('m_9_12/9: ${c} HLFHBMMRTKJGCIZFYDBPPPODQDAAOFUKNYTWFLPISWAPCZJFIYTRJXAHVDQKDADCWSMDLONOVBEYACNBJSLBHLYEHKRTEGKWJNHK', props),
compute('m_9_12/10: ${c} TSVWHXHXZFDRHEZQIQXPTGVPLBTFQAUYXSPYKKCIPRWYAROJIYEAWEIWIBKFEWMYZPOKNUZSQOUJRRBHOWCKKOSJPHKWZVNQPIBW', props),
compute('m_9_12/11: ${c} YYDNNCGTKYSCHKQBBSUXAOKMLOZBOMKVAFKBFCKMFRHGIKNRRYDUPCXIHAKOCGWBILRCPGSCTYSMTWIAFDDJENKBAPUZSXMBPGSL', props),
compute('m_9_12/12: ${c} VJJJIDNJBZGMXOOVRAXHLBXFLPTHRBVJBURGYKMXZFLEZTUJSJPBUKKYECBCAJHUYTZHWOMJUVAIJWZWOSALHCAYHFUQNXMYLBGD', props),
compute('m_9_12/13: ${c} PXSSOXRPKSVGCPFLVIXKJXMZJVIOZCGNLKKPFRXPOUCGLKMAEUOTZPVRVBIJEWBXMSXEGTCAJHGLEGWPBBAWIGKIQKXSPJHTVCSE', props),
compute('m_9_12/14: ${c} JVRSHJGBKPIWNISLVTNBPUJHHBRFRKEBUYWDHJVDKCZWDONFZFVRXJWCSGECKWGZYDWXXDPCBIJLPWPIKHYJBKWFHUXJHOPUAFGJ', props),
compute('m_9_12/15: ${c} NVMZQFJXAQIKKDRMKYXCUAXPCNMNVBZMDDAJXQOPGSMDEXURLYAIDFMFSGZZFNYVTUEDKRGCPPRMVGJAIWVECNTDHJMJIJQVNENQ', props)
        ].join('\n');
      }
    