
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_15/1: ${c} JREMRROVIPCZEXTOZAKPJQDIJZUZCXETJWGRTGXQFVTDEFWYFZPTVBPIUFBYMPRPYJEPSFYJGPAZHTFZWWFYFLADOSDMQMHTYVJJ', props),
compute('m_9_15/2: ${c} SITJMWZQERQMVEWEQMBEPWQTJOPYGVPXJDGZBLHHZGUREXYKHQKHCLTFULNWIWIBZYJWRTHTARDLZYYWLTZJQXOTCCASJADCHLEX', props),
compute('m_9_15/3: ${c} GKAFPLOOVKEDPPYJFICAQHNLUAIFOHXAKZJXJWHDQNCYCKZPCIHRPBGVQCNBEFMRJPLDEXHFZGPSLJKCDEOQVYOAAKOPECNUPQMY', props),
compute('m_9_15/4: ${c} ZJTVTVIDPBPGPDRECNLBOUZAXDBZQLXFBVGDOTJIYNINWONWEHOPZDNNWHBSEBVKWALRIJKZPLPMAJDXHRWCMLSUSLIRRKVOTRQF', props),
compute('m_9_15/5: ${c} ABNIJCIAGHOIDXIOMRXLOPGHXVKBDBTZYKTIQVKFDJPGRTFAWPQFYRAUFKLTDCVZAHIAFUSSAQTRVLNHHMWBVCJCSLXDILERTDET', props),
compute('m_9_15/6: ${c} FZOCTXSTLUBJHIYMSIZAMZGYPCFIMIAIAAOTCGBRSWSFYPTYYKLNCHSSQEXILHRPOIOSZMIMDQXJCPOARISOVVXENODQUDSLSQBN', props),
compute('m_9_15/7: ${c} WOGGLSMPZWNNTDFUXICJHQMBNKWCGSXCIVWLHUQZLZNUQEFKKSCSZNNECBZOMPQQNICKWVYYHCDGEAYRDEREIBZWAONWXFLSCPTK', props),
compute('m_9_15/8: ${c} HZUVOQNBGUXRFHMGFUVODGXNYZOKDZHIAHIPAFBCFPCKXFRFGIDOQSSZYGVCQNCCXNSXAXBWHGVYYBCFUVJTQBISUOPHVXPOQUCP', props),
compute('m_9_15/9: ${c} QIQYUSLFRWNPKONJJSKXVFQGTMRDHIRCFODENGAFSVGDNTRPXCYVPKTGTDOACCGOTNNJEGHFIEGIJSEBYSGHPHVXZHPSIURGXSJD', props),
compute('m_9_15/10: ${c} XNTBXYTOWJKYWFMEUMIYJFKLGEPIXNBHMNOZDQHTRCQQESRFNFIOFJLQZEHGONMXESGUJAJFBHQQANHFDLPPGLJNXIXVUMMVKEMZ', props),
compute('m_9_15/11: ${c} PFEPOIPEVZESWDSDJLJFIBIHEOHSBCDKGIDPATWWEVMLTRSYRQAHZFYAWUSWDMOZGLBUQAGQDSAKQWLPPDPATSWSGAVJCDYRWFPV', props),
compute('m_9_15/12: ${c} QKZJLYLVHNDLCPFYHFNCPBTRCJFDZAZVUSZHGOEZFVQWQDVAKWNNGIYLCFOUMFRNHDZNVIEHORKBRQUUXWFGQZQLPTSOGQGAYIVK', props),
compute('m_9_15/13: ${c} CYQGDOZNFLCBSDSKCOUDSGYPCCPKIBCFFZTQRXVDSEXRDUBOESEYGBVQMKJLIQYDHXEJBCYDISUUKWGMUEWZAKWRDLASBNRWUQMB', props),
compute('m_9_15/14: ${c} JHDFUZMZMXLWMAOWDJRCRMFGGGMQXJLEOLDNXAIXLMCYXCDRDGUUOZDDRQSEUZIEWXKNVNSPIWUUCUPGNBRECXCBGOAGMRZNMJUQ', props),
compute('m_9_15/15: ${c} SEGCABVDRFKFNYWFSBWPZSBCMRMIRVPNIQYERGCLJLUHWVVIGENLCQWGMKVPHGOKGKIROFUCUUNEUXXZTSDHOGWEJFOIBSDMPZIP', props)
        ].join('\n');
      }
    