
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_10/1: ${c} WUUTLCIQBFGVOVDIYDEUIRCMOXXYJGOQDHACVZDRZREVDQVLNENULTTEMFXAKBQISOZNBLUOWZSAQZWWEUWSCQJCRIKYKDMODMJI', props),
compute('m_9_10/2: ${c} QWYPHOSXVJBPDGXRXJMCEYHWODFGTHXGXPAAJKPNLGVFXSKSEXALUQWFMLMAEHINGJVTBEJFNBLJMGYDOPPYXKQOZMWKVJIQCMAV', props),
compute('m_9_10/3: ${c} SJYCQVKKBXXWTREDEOAYXXJDULJLCINIVCEPXDWJAWJZTZZDQHCMMIKXUGEWRUGKJFCCLAJGVVDHZXIIOHWFLFPNMESVBHIJSSBC', props),
compute('m_9_10/4: ${c} AHPCKCVPDNGBMTCAYVONQOVNTYWRNXFIIHKYVZGSIAOOZNGOFHVNOIYIMIAMEQZPINCHSDSKXRREMTAXETTGJXEVIZKSGIUIVWSG', props),
compute('m_9_10/5: ${c} ACYYCWJEHURTIYKLAMFLZIPPIYOSQDKSHBVLNQCSGDZWKPGOTECBLWCRJSBMQTUMMZVUYLOHRVNOXLOOCRCOFOBKQPLZKSLYVZDL', props),
compute('m_9_10/6: ${c} HPHESKTBYABTGWBWTCWSRVGJSQMKMVRPAAAPVCMSUKESKTQESBSFAJHFIBDOWGMWHXLTPHKJPHTAHNVONPYKLUPGHWJDWCJDUMMI', props),
compute('m_9_10/7: ${c} PINMZFQFXRJVOAWRNFVWFWQDBIMWVEAZSNEQLAPBMLLEAWNJWKXVRFMXJXHZKQFTWAVHZPFAWZJGNWSSDCKGWSPWLAEHGMXUNUAO', props),
compute('m_9_10/8: ${c} QQFYHALEJTLLHXYCRVBOBSXRYKZOOBZIUAWLZUVYDCHUJTTFJYLRVMCJJBIRAMLERVTFLJFSKUQLZCASCLNYDOQEOOCXVGSEGIKJ', props),
compute('m_9_10/9: ${c} FNFKPMNXTWSUSHUEBWGGGDQSTJRDWWSBQGVYONRTYTUMSNVSFZTZGKCMBEIOMOQRITALJMRAUKBILJNXHFHRFGTTEFPBRQBKQUYG', props),
compute('m_9_10/10: ${c} TBXHVQLRIDFZMILLTGEURLHZOVUCRVJKJKPNKYMUGTPXLNXBTOTUZEHTXWBPUYWWJFFGRZLVDJPQGWLTJBLBLJPPEAQWKSXCMWYN', props),
compute('m_9_10/11: ${c} CBUMIGGCLEIVWQLUFUXDDANLSFAEEBVWYVPMXYIAHHQJLLFTQHQOACGKPSBGVOFSTSDCPYQKLASUGJXHKMHQKJIEITYYDSXJVQEQ', props),
compute('m_9_10/12: ${c} JSOJODUMIEFRHWVAYERFRESJOFSBYATYAQHQEVHDOUTCMZNLEROPZGXJPCSVJIUSFLRPTQFUSNLBFLDBCXVPDEHJYXVRFNSQVPGC', props),
compute('m_9_10/13: ${c} NVFKEZTVGPDGSNRFCEEMRCHLVEDQEBFEFJMWHNBPKSGDVBJSQPYDLQOJFYUZLMDQKWHZZSJSCMLIVRFHHKZFGHGSNFOQTMXOXBDI', props),
compute('m_9_10/14: ${c} JMTCUOKZFJRPSFGRTFRZJZADIUQLQOJTEMWRQOEVIKTVWENKJOAVAPWSUIUWGAICGMFZDPPBKPXFZXDVNPWMUMFBKSFSHDQLWPIB', props),
compute('m_9_10/15: ${c} OHWYOGFCBSEPGKXADNPTKSBMPGDDUSRWBAVCBSZBNNLOMFPIOPLDXILKXVWPYORGMPSEFOZZFLEWBWGBMXLCXWAJVMINJWAHQRJA', props)
        ].join('\n');
      }
    