
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_4/1: ${c} VAAGCBCIUPMZZUDJGWHSSRURCEUSSERDJFEPKBLNOMXVFHUPZYFPBIVTGIEUAMBXHYTVJIWCAWHDJRKHHIDEPPMEEGKFLUUKBYJA', props),
compute('m_9_4/2: ${c} MHQKUKJHGUUGQWDYBUJQTBLGWUNRUYXRQQJRGSSNNHYPLTGEHANPHBSQGMHYFUJGVVXSLXQVOJPRVWBWEUKSILQJDUHFWFYXPDPM', props),
compute('m_9_4/3: ${c} AEHOYMVCBNBIBJRVNCDIFOHUBXNBBFZWEAWPECLHFUTIKBEBYKANXDEQDYKWNLSYVGMLUALHKTYJLTOXAUXDDJJPJDXAYCEJSAXB', props),
compute('m_9_4/4: ${c} HYMWKMREIHVIJQZNSAVUFHQNBFADZJYYAXVUBSGPWVWDYDXTFRJFAXXQQYDLTIAIYHRIDQQCNUYKJBHBIWTCBOZTTXJPGFSYYDHU', props),
compute('m_9_4/5: ${c} DYUFDBQGWACMLCPRNBVWBVDBVXCQPWPNAGYIVNJSNXACCMJROTQAEKFACVRBJHVYNMHODRSVZALERVJIDAOGILJNTUMITICZXGAZ', props),
compute('m_9_4/6: ${c} IWAJXPCEPQYNSJLEUSDHGHKTZNMFUUFUQXYGQWZUQGKEDHIYDVCVLTYQPOVQNVLUCWUTQNRGPSQJHLEUKKEAWCONCTTGJBFIPGZM', props),
compute('m_9_4/7: ${c} WWDTZKHWADSABIPSQNFDKSQTTJATARFDDDFZGTPIUOARXIRBVHHOZJLNMSRFSUMOJOKYXXZNVUELJTPSIZDGXIWJKNSDEYVETZAE', props),
compute('m_9_4/8: ${c} HXTMJBKZLMFKLOBGCUIHXSPCHJEPELHZWXNIGCTMTSEKEBPKAIOFSGRDPVGSCFOIRFSVNPHHAHBTRMSSSKCLDOCYGTWCOHVJIWRO', props),
compute('m_9_4/9: ${c} ZZLXPYCSQNWRSMBEIVHPNLYUUQAZEHBVSGPBYMTDWXWILQGYEOGAQCIDUKKSXAASNKLMFLWZYAUCGIUROKZHITJZCUOYLXXHGDRH', props),
compute('m_9_4/10: ${c} HQMIWXOTQDBJJCLUYQEXFJQTGJCSQFWNPVBLUHIDSTBHWDCNISEYARICTDZYJJPHWHOSKUVDHBVTQFBNAQTHHLUVOSZXUBDRUOOR', props),
compute('m_9_4/11: ${c} WMHXOQETCNNVOIKYBEHUDTBZZKCXDCEWXBQRCMUHWHKPWNEFHCNZMJZBWUKDESPOQGGXYRDLXEDWENCYXKKGIWHLPIIUEQIEAJAA', props),
compute('m_9_4/12: ${c} LRYUUIOWCSVCVXEJTEYUCEBNZYOFUVFYIDOKSCYSHMWROZANRHZZROBMUHRKTJDPBZYNVCHWTPZOUDJHTDOQLITAEJNXMWCKCZWT', props),
compute('m_9_4/13: ${c} HRGGATUJKUWAQSJHQYBSJJWOHIUVPUPQQOWFPMAIJKZOPWBLKQTCNFYSGHDAQVGMBHMSINELONDEQBMQLVAZHHCSSNCFKLCKQZQP', props),
compute('m_9_4/14: ${c} KSWHEJGLDLFQQFHVFIYAOUJUTLYXJUVVNYXNQEWVDPSZKUBUVQWXFAOKPNKJGXZUUOHTIALXUAOWUUGEXAONALNSORYBWBRFJYRM', props),
compute('m_9_4/15: ${c} YHAWLTOZYUUDHHNXYVOKPPKJGCEUEIOQGGCBYRYMHCDZVOJBTWLLHFPVSLEJUIZZKULOAULQTUISILCJNPHFPGJIACHXSAOLTVRH', props)
        ].join('\n');
      }
    