
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_3/1: ${c} YDCBNJZGPQRBMRKITQOTYPRKXMSMVDGUYEIFWXKQRJUSMREYDGXTBYSBIEULOSLDGZFLGBYKWVLZVVBTSUCXIYZTTRVSRUTNCQOK', props),
compute('m_9_3/2: ${c} RGITAENVXVGHAEHDEKXAPIHRUWKEGWFTFPJKNTHNSDTGLYIUCNKOHYNAXDZIHGDTIQEZYQOSJVFJXRKJTYVGQPIGSXXDNLZQCHSZ', props),
compute('m_9_3/3: ${c} TMCQTMAXTGLNHZEEQORMZNMERQHEVUJOLXVIJKCXXBOAWDZBIDUXFXSTKTKMPQLKDDOELCMIPSNCIENCZIGMLDSVUCESELPFWOEP', props),
compute('m_9_3/4: ${c} LTUYDFDULZLHWGHACXMMFTWRZUJXKBHXSWDETSUCASFEHGHXFMPDSIPDBASYFTTINDZBKPRSGNDBRERUVSNEZLAUAUQSQQUKSCJX', props),
compute('m_9_3/5: ${c} SAPFYLHBIYVQNMSUMQNVXTECYBIZXFHMBSCVGVLNWDIQXYNJWLHWQEAIPMAXTBJHERMEQELRNIASXNXWFNSDHBCIRWJYLRBJMCLD', props),
compute('m_9_3/6: ${c} BSJOQZIICFUJNYJUIZPUIKPTQCSFGUJHVHYORPICICZJAKJZJBOEOULDGDCEUCCQZWMRBJVQVOKCMZEPAUMNFOSUFYBCKBHXJPUE', props),
compute('m_9_3/7: ${c} OOKHWCCXJUWDZOJFAKSESYHRAKRCHAWSRYGXOUFMCOWCORTJPAHQZCNGRNCZXBPNZCYKNXXENGAZVSLAKQXUQIKAGHZNXAUYAIKS', props),
compute('m_9_3/8: ${c} EFPBNLWBGOEPEIEEHHFZCPZFKTTSSKPHUEEGYKRXEXXIVQAZXCVBSCIZUYOJXYVHMOFUGNRHUHBKNGRLXHNYKKOABIEYTPTVTAIG', props),
compute('m_9_3/9: ${c} CAPAQLASKQMXDNKVZGTRCVFSTGZNIIVSNXIWSSGICDIUTTIJDRHMMXCOVSMJSZUXKWXYEFMGYYUMBQYPXJMHOMZOSCKULJFRBKZD', props),
compute('m_9_3/10: ${c} HXAGWPOUQEWHAXPKLPXPIXZIWLQTMOCBTOFOZFWRYMBPKHOFUJRIBMBJRHORKDYLMRVGDOOEODOGNLEVYOGUCNANVBDHBXKVAAAQ', props),
compute('m_9_3/11: ${c} MDLDTHRXYKUFDBGCUCEQNVLEDBCJFYRJVSDDCDQOYBDQKBIBTGJRRORDWYYIIHBVYTSRXXBBUAVEGHDSEJEZLINFYKNATXJROGGN', props),
compute('m_9_3/12: ${c} EHYADKGDFPZSLQAQELJYTABSQKNIOTZYFWFXZNOQRMGTPYKCKZQUVRDPWNMYJVGCWJIXHQBTXREJTOHPDFBJFJCYHCSLONOTMZFP', props),
compute('m_9_3/13: ${c} MDDZJOQAKQDUOUDUQEREGFVDENEVMXECHAYMFSFSDQXYVUNIHPAHBAJCWHBERUFXQWOPHMGDVVYZUKJZPJGCQKHXDYOXHNMTFWZI', props),
compute('m_9_3/14: ${c} AKPRSGOWPJVFHBMLXHQMUEGAMJZSJMFCIKIXYLSYXQHXZQRCSEYIXCTJDJPNFSBLSHFZHSDEHORFYMYXVDGRBFMVZUQSHKIJQTUL', props),
compute('m_9_3/15: ${c} FKSZEBSIGWBKQAABXPJUYMTIIFIDPHJXPQLZGHMSTZLVPLCCDCTACNLQXKYURLRBJSBKNFQYNZEYOYGSATBAJTFPXNIHOAPIWXST', props)
        ].join('\n');
      }
    