
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_7/1: ${c} TLEHADLGTPNBAYMIIUUKAPFQTEPHBGUAHURDNVZTCRZULJZLYPVYTKIGNKZVBYTWTGZCXPNNYLISXUCYLFEJKLPUJLWZVIYJEMDD', props),
compute('m_9_7/2: ${c} YNTXRWYPETIMFNQNGPGQMNTRYALQFESGZDXKUWQVWZNOIONKNVTSIHXYHAKSDXKBGQJEKBEVVQMUYZDPLNUKDMTETYWZJAWKHOZQ', props),
compute('m_9_7/3: ${c} ZLGHPCWQRRYGEGGYHGRVMAVADVMPSNESTOPAMBQYSOSDUODMDJYRKSSXGAWPXKURJBPZFOLUIMUROTMKOVKXPVXOWWDPLAGOVCJA', props),
compute('m_9_7/4: ${c} TSPDILAHXIQGYYGWUAUCECVNGZHOKYQHOTRRMPGFMVPVZMDGVBWFFSYTNGMWZKCDTQCHAUCYXJRWSZPGIXYDSOOBHVJUXBLXHMCH', props),
compute('m_9_7/5: ${c} REHUGPMXSPKRXQMJUPEPHVADHCNTVZVJQMGZDBGTCSUDYAOURIAVFRPIAURNJPRGZJGAGYNYOTUHSWPXGIKPOJXSYPSMGUGJAHNR', props),
compute('m_9_7/6: ${c} JYGKBIVUQUOKZHMWFBIUEHIBDOKNQENBQTJUKRVVVGURWARTMTUEGQZLADSWQBITHWUNZAQQLIEQBDHNCXUBGXAKZDBYWMTGGZZI', props),
compute('m_9_7/7: ${c} CIUJAQWZAXACROIJMDDDFLPFSQJXCDHWCANBBEZHEPCKINHEFVYWBBOYCQODQVQCYHTDDFYEEVBWTGVYIBAVWQGXLFLAKVUUEPHM', props),
compute('m_9_7/8: ${c} HTSWTZRKWSMNSCCRUUUKQFEKVQKRVDMOCORQWSPAGLUAVPOGRDPYLHSOCMRUBGHOTNOTGJILYZBJROPWESIANPMQCCJRCSFVSAMU', props),
compute('m_9_7/9: ${c} ZYWJPUIDYHBNFJJNGOZWFBJPTEWEBDDMYYENHICLMHEBXRLLOWQDYMJCYNHWGRGZZCHIOGYONCPAGOSAAYPCDGEJUDEJJESGZIWW', props),
compute('m_9_7/10: ${c} PCFJXSSBAEAKEQGTBHXRZESEDSRQRWAUFSBCITCQWYEBDXJOYMWBRYGUYKCVVOTIOILXRFOAJHCNQRVLSTQBTEGSXVBJKVREJRFU', props),
compute('m_9_7/11: ${c} ORLXQCWFSNHIXGUHCBHGWTHZIADJXLMPDBMLEIKCAXPWYWRNBTKPBFDKEOGXORSEZHRBHTHWVWNKPEOMXYEZCDXBTQYJMNHQMQAY', props),
compute('m_9_7/12: ${c} QBWLYICUMGQKENMHPUHKMKOQZYSFYESKTSELUJPHRZNGWVSKXNXABKHBQIPNPZRQMKJBDDNVLKRXADHMZOJQHLAUUAEYTSVATKJO', props),
compute('m_9_7/13: ${c} IQGBOQTSSNSHWIKUNSCDHENIRZGVUYFMZZSVRSGCZAPKMLXWLGCQEXBMLIJCRFHTGXMPVWYLDHYZAKPEYIXMGSETNGZCFGGTKWAA', props),
compute('m_9_7/14: ${c} BBILMNFLBPNPSNMSSPJRIBHOMUVLFFHEHGKHLWJMTJCQSFCHROMMCOBSBUGQWAXXOCKRGYKJMMKZJUZCJWIXOSPAHSOOJTWDBVDI', props),
compute('m_9_7/15: ${c} ZMOOKBOFDOPISKGDUAWZIEGNVIJLVCJZWRMOJCRALGDWSFNMAKKTMHOIJOBVJJQLBRCDYOYDBKUDEPNCSMFEIUYGJFIWMPYQKBFT', props)
        ].join('\n');
      }
    