
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_1/1: ${c} FIZZUPBUIYPPWPVBZVVSMNUOZXIENDSRDNMPJLWQTVVUMNHCSRIMHDGHTGIXFGJADAXCRINQBFDGWMZLRVGPNZEXFMNIKGEGJZIK', props),
compute('m_9_1/2: ${c} ZUXBLXBKZSGVDJWITMUIKNHUHNTBLVJKJFMCDOSUYVSHVMWZNPIVYSJSDKUCNNOIKMLECCQTTFNRHLJBBDPXUVDQECMGKIZSWSFP', props),
compute('m_9_1/3: ${c} KEGDXFFDGICUGTGRZAYWLWJGOIWABCAQEFUYPBNGKOSRWHZCJMXJHHFVVFDOLHGYYCNBDFVJZQNDREZUFPJTVBKVCMDFNXFNFJZV', props),
compute('m_9_1/4: ${c} WIMWPCMMZIKEZHLQUYOYNKFEOJATLEIEKUXHBJTESZJHQEQWRUDDAOYEFDGRXKDUZQJJTSZOCWBGGWXOKMVCVAGCWCCRZFWKJOOS', props),
compute('m_9_1/5: ${c} ODIPMLIXLRDDFAVVYYLRRHEXDOWLAKALKOVOUCXDZNMUPCFOCOCMDEWQPFJQQEJRMLHDGCCXAGXQBOPRLMMSNSHBTDKCGCXWOOPM', props),
compute('m_9_1/6: ${c} UULFTBMHEUBUYGTZSLZJFLPOYXQMGIQXKDNJRIXAWSIJPTDQJYXVYOEBPGYSXELFSGLCFBVHKMPPORKILCDPGFWCHVFRQNPJCMYJ', props),
compute('m_9_1/7: ${c} RPEPGJTNJPUMJNLWHVNVRVKVKIIPMQUUPOLEWJWGRXPYVKRBTTSHENOHGSVKHVYFAQQPUAMTSQGAORCBBIKFDHLWJNFQYFQAUYKB', props),
compute('m_9_1/8: ${c} PZFSRVOEYCMEBEKOPMKYVRGODKYFWXPBRWKKHDSKPSRZTXHRMSAKSHCJZCWYSAOZVAUWVYOXIAOACJOFDOSIZCKNOLJJUMUQEOQY', props),
compute('m_9_1/9: ${c} NLPRKERULGIGMNSFUDKOUOSGHXBUDKYLLOJFTHJGAVCLHLONNAAGNDCZDCKZEPRDNRMYTUWCTFDCBVOPJSIRUGWSOXMHOHTIVUFO', props),
compute('m_9_1/10: ${c} VLQZPCPFSRLSWUTAVNPPWVVBPYTECZIUTQCDGEZCMXKVWWVBLDDIROSVDZKBLTCOVBZZSCELBIYRPVVQQNFHYOJNAZZBMUXRVCKF', props),
compute('m_9_1/11: ${c} UPEVXAPWESZTWDOOYECVOPUNJPHWBLHLZSIVIZEGVPDGBYUBJZFHMAGIJQPWCJTJJEMACVGISVCNLWZQYQXORUTOSXEGLFJLFUAH', props),
compute('m_9_1/12: ${c} MZKRSJKGIQZAKDKXFALVRFJUQPFHMKNXEJFHLYURDHYHKBCZQIDECPCCPTUMHXSUIFGLTMPUTGFCHSJDZHGFPBMSZETGOPCAHYHT', props),
compute('m_9_1/13: ${c} ZCUNHYSCQCSFEQXVSNTUEBFIYRLTYNHPQFOELQAUXAGDXEFRJCHLCUUUIYNEMQRKPZWYXEGFGPSNIDJKPKJSYFEMSLBZIVGJAYDX', props),
compute('m_9_1/14: ${c} PCOQQROZNSTZILJRYFNZZNFOPYJLLKGXNFQFFRQZSKPYRRHEODMAASDNJKHYCZZRTBHAVRFXCWHPRCXDYIVITCKODQSIPANBKIXC', props),
compute('m_9_1/15: ${c} DFLRFYBGETYCEPHINWRJQHAOGJNYQHDQMREYTPAALKTNRIOZFMJMXCIEEZIQCTTOTGLGXTQFBCJTXIHWJAMITXSYHTMKFYQQPPEO', props)
        ].join('\n');
      }
    