
      import {compute} from './shared.js';

      export default function render(props) {
        return [
          compute('m_9_13/1: ${c} VFETCLAMPUGWWMPUMOMKUHBLMEWMBVOWVXXTHHPQKDUHVMYXZKCQXUBKOIQFBKAUQSJQHDXXPSDLKPEOQRIEVYVWSNZQEZXXWWMJ', props),
compute('m_9_13/2: ${c} WKXYYYPYEHLZNJTBSBDRDFIWZUFZFQUNENDELRNCCELDKBBABJCJFMUZKGZVMLPHKATXEFXIMHQZPLWJFRBYGGCJUPXXRDETKPEL', props),
compute('m_9_13/3: ${c} RASDZOEQNOCKYQJDAZPHGXXZNBGYHTQXRVGKMBMYNDIYNTQPNHKCKHCWOTIIRZCJQWQAYKSDSVFOBYIKZJRJSMCUNOOSQOACCDQY', props),
compute('m_9_13/4: ${c} SLNWJJQXRDUZSDTIVBCXSIKJUMFFXNZDMOAVWWGFPUSHTRRBIXRECSJFEWYHZOCZRWFUMTVJAPENZIVSZYSOMRNWQWGGLWKXQMOM', props),
compute('m_9_13/5: ${c} QARDGAUFJRXGOWOMFQGJSXAUVERRUEUXPPQUMHPTEFVVFCGTZEUYONAJUYHLDFQXPSKMLHYJLLGVELEIJQKHMMOZCTGMNMRQKDWH', props),
compute('m_9_13/6: ${c} JRNSMYSLEZRSWSBDXUAUTHKWSOEFWZLZLUQOQAFCZETTYFIWHHOYGCIMVBYGIPDJKEIJOCYERJVVBTFGSRACEAFVMLZNMJZHUCJG', props),
compute('m_9_13/7: ${c} HMRZXEOJOHGFJNQTBBWMOZIBWHKSHFYWRUPHBDSWXVNHGLLQIPPZOGXWCTFWKKGVCJMLCIHPMSNEPCDVERSIJCITOOIWVCTOLPKF', props),
compute('m_9_13/8: ${c} WCHGXYUQHNRRPDQMHGOYBYTOGWIMMCCXRPNLUJFJWJECNLGGIFTBJUGHWMTCSCILGBQERQSNNTKPTFNOLALMWSTLVAMJOGDDRKVL', props),
compute('m_9_13/9: ${c} ETWNWXQTKMODZJVCLTCWPVWSCQFIBNABNLTMKMEESIHDUSYWCTKCWQVZWZAOYCPZPDSLINXROMLCKSLBXKTRLALIDCDBPOSWZUEU', props),
compute('m_9_13/10: ${c} ZFPYWPKDZJEWPATXNJCYPYAQTFIGGBJJFMNUSOSTPQZFJLCVSNONCTAHEAMDKPPNENDYBRAPZSJYCLCCOFGOCQKRWGZRWAXDUZKX', props),
compute('m_9_13/11: ${c} VFWQAPSOJGCLTIAGAIXLYPUZGMHIJGQQKNRXMTAQUEWDOMHPYQLMAYPEMFQEUPSBLRDOHTKLTXUEVZHNFYVYXQJLAKDVKQYUXIVN', props),
compute('m_9_13/12: ${c} BTJOWOPVUDHNAMFQLXDFEBDIKWVYXREYFOMHVGYQJFJGIVAQCLEVEKHPOWNNDUUZXWWPTBRQVQSGJBXREDBOQEUKDFCLYRSHTXUE', props),
compute('m_9_13/13: ${c} OIDRMBSELVUBDYZYYEYPSFZBAYGLJGDTYJOXDOSSZZEUHSNCPDVJYASSORREUSWKATYTMQKBHZMQCGXYDRKQNQIJOOCHHHZTHLYE', props),
compute('m_9_13/14: ${c} YCCHCSWZDKCDPVMGWMWZINNVLUTAFUIIRXYSLLXTEFYIFTUSXHNPZMFWIZDVQOSEVFPFEGWRRNAQYTHIHJCWNGGJTSXIBYFTIBEU', props),
compute('m_9_13/15: ${c} QYVUEBHJUIDMUHHAAPEVNPZIGNALHJDGIPLRFNEJXSACQMGANMANVNNZSKBJBLSWSJXEZXQORATOYMYJCDFPBSYPNNWJZBTKXXAS', props)
        ].join('\n');
      }
    